s#XXXaccessing-che-from-openshift-developer-perspectiveXXX#assembly_accessing-che-from-openshift-developer-perspective.adoc#
s#XXXadding-support-for-a-new-debuggerXXX#proc_adding-support-for-a-new-debugger.adoc#
s#XXXadding-support-for-a-new-languageXXX#proc_adding-support-for-a-new-language.adoc#
s#XXXadding-tools-to-che-after-creating-a-workspaceXXX#assembly_adding-tools-to-che-after-creating-a-workspace.adoc#
s#XXXadvanced-configuration-options-for-the-che-server-componentXXX#assembly_advanced-configuration-options-for-the-che-server-component.adoc#
s#XXXadvanced-configuration-optionsXXX#assembly_advanced-configuration-options.adoc#
s#XXXauthenticating-usersXXX#assembly_authenticating-users.adoc#
s#XXXauthenticating-with-openshift-connector-from-eclipse-cheXXX#proc_authenticating-with-openshift-connector-in-eclipse-che.adoc#
s#XXXauthorizing-usersXXX#assembly_authorizing-users.adoc#
s#XXXbackup-and-disaster-recoveryXXX#assembly_backup-and-disaster-recovery.adoc#
s#XXXbranding-che-theiaXXX#assembly_branding-che-theia.adoc#
s#XXXbuilding-and-running-a-custom-registry-imageXXX#assembly_building-and-running-a-custom-registry-image.adoc#
s#XXXcaching-images-for-faster-workspace-startXXX#assembly_caching-images-for-faster-workspace-start.adoc#
s#XXXcalculating-che-resource-requirementsXXX#assembly_calculating-che-resource-requirements.adoc#
s#XXXche-architectureXXX#assembly_che-architecture.adoc#
s#XXXche-extensibility-referenceXXX#assembly_che-extensibility-reference.adoc#
s#XXXche-extension-pointsXXX#con_che-extension-points.adoc#
s#XXXche-glossaryXXX#con_glossary.adoc#
s#XXXche-quick-startsXXX#assembly_che-quick-starts.adoc#
s#XXXche-theia-ide-basicsXXX#assembly_che-theia-ide-basics.adoc#
s#XXXche-theia-plug-in-apiXXX#ref_che-theia-plug-in-api.adoc#
s#XXXche-theia-troubleshootingXXX#assembly_che-theia-troubleshooting.adoc#
s#XXXche-workspace-controllerXXX#assembly_che-workspace-controller.adoc#
s#XXXche-workspaces-architectureXXX#assembly_che-workspaces-architecture.adoc#
s#XXXcollecting-logs-using-chectlXXX#assembly_collecting-logs-using-chectl.adoc#
s#XXXconfiguring-authorizationXXX#assembly_configuring-authorization.adoc#
s#XXXconfiguring-a-workspace-using-a-devfileXXX#assembly_configuring-a-workspace-using-a-devfile.adoc#
s#XXXconfiguring-cheXXX#assembly_configuring-che-overview.adoc#
s#XXXconfiguring-github-oauthXXX#assembly_configuring-github-oauth.adoc#
s#XXXconfiguring-namespace-strategiesXXX#proc_configuring-namespace-strategies.adoc#
s#XXXconfiguring-oauth-authorizationXXX#assembly_configuring-oauth-authorization.adoc#
s#XXXconfiguring-openshift-oauthXXX#assembly_configuring-openshift-oauth.adoc#
s#XXXconfiguring-system-variablesXXX#ref_configuring-system-variables.adoc#
s#XXXconfiguring-the-che-installationXXX#assembly_configuring-the-che-installation.adoc#
s#XXXconfiguring-workspace-exposure-strategiesXXX#assembly_configuring-workspace-exposure-strategies.adoc#
s#XXXconnecting-source-code-from-github-to-a-openshift-component-using-openshift-connectorXXX#proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc#
s#XXXconverting-a-che-6-workspace-to-a-che-7-devfileXXX#assembly_converting-a-che-6-workspace-to-a-che-7-devfile.adoc#
s#XXXcreating-and-configuring-a-new-che-7-workspaceXXX#assembly_creating-and-configuring-a-new-che-7-workspace.adoc#
s#XXXcreating-a-workspace-by-importing-source-code-of-a-projectXXX#proc_creating-a-workspace-by-importing-source-code-of-a-project.adoc#
s#XXXcreating-a-workspace-from-code-sampleXXX#assembly_creating-a-workspace-from-code-sample.adoc#
s#XXXcreating-components-with-openshift-connector-in-eclipse-cheXXX#proc_creating-components-with-openshift-connector-in-eclipse-che.adoc#
s#XXXcustomizing-developer-environmentsXXX#assembly_customizing-developer-environments.adoc#
s#XXXcustomizing-the-devfile-and-plug-in-registriesXXX#assembly_customizing-the-devfile-and-plug-in-registries.adoc#
s#XXXdebug-adapter-protocolXXX#ref_debug-adapter-protocol.adoc#
s#XXXdefining-custom-commands-for-che-theiaXXX#assembly_defining-custom-commands-for-che-theia.adoc#
s#XXXdeploying-che-on-kubernetes-on-awsXXX#assembly_deploying-che-on-kubernetes-on-aws.adoc#
s#XXXdeploying-che-with-support-for-git-repositories-with-self-signed-certificatesXXX#proc_deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc#
s#XXXdeveloping-che-theia-plug-insXXX#assembly_developing-che-theia-plug-ins.adoc#
s#XXXeclipse-che4zXXX#assembly_eclipse-che4z.adoc#
s#XXXediting-a-devfile-and-plug-in-at-runtimeXXX#assembly_editing-a-devfile-and-plug-in-at-runtime.adoc#
s#XXXexternal-database-setupXXX#con_external-database-setup.adoc#
s#XXXfeatures-of-openshift-connectorXXX#con_features-of-openshift-connector.adoc#
s#XXXhigh-level-che-architectureXXX#con_high-level-che-architecture.adoc#
s#XXXhosted-cheXXX#assembly_hosted-che.adoc#
s#XXXimporting-a-kubernetes-application-into-a-che-workspaceXXX#assembly_importing-a-kubernetes-application-into-a-workspace.adoc#
s#XXXincluding-the-plug-in-binaries-in-the-registry-imageXXX#proc_including-the-plug-in-binaries-in-the-registry-image.adoc#
s#XXXinstalling-chectlXXX#assembly_installing-chectl.adoc#
s#XXXinstalling-che-in-restricted-environmentXXX#assembly_installing-che-in-restricted-environment.adoc#
s#XXXinstalling-che-in-tls-mode-with-self-signed-certificatesXXX#assembly_installing-che-in-tls-mode-with-self-signed-certificates.adoc#
s#XXXinstalling-che-on-google-cloud-platformXXX#assembly_installing-che-on-google-cloud-platform.adoc#
s#XXXinstalling-che-on-openshift-3-using-the-operatorXXX#assembly_installing-che-on-openshift-3-using-the-operator.adoc#
s#XXXinstalling-che-on-openshift-4-from-operatorhubXXX#assembly_installing-che-on-openshift-4-from-operatorhub.adoc#
s#XXXinstalling-che-on-premise-with-kubesprayXXX#assembly_installing-che-on-premise-with-kubespray.adoc#
s#XXXinstalling-che-using-storage-classesXXX#proc_installing-che-using-storage-classes.adoc#
s#XXXinstalling-eclipse-che-on-microsoft-azureXXX#assembly_installing-che-on-microsoft-azure.adoc#
s#XXXinstalling-load-balancer-on-a-bare-metal-clusterXXX#proc_installing-load-balancer-on-a-bare-metal-cluster.adoc#
s#XXXinstalling-openshift-connector-in-eclipse-cheXXX#proc_installing-openshift-connector-in-eclipse-che.adoc#
s#XXXinstalling-storage-on-a-bare-metal-clusterXXX#proc_installing-storage-on-a-bare-metal-cluster.adoc#
s#XXXinstalling-the-chectl-management-toolXXX#assembly_installing-the-chectl-management-tool.adoc#
s#XXXintroduction-to-eclipse-cheXXX#assembly_introduction-to-eclipse-che.adoc#
s#XXXlanguage-server-protocolXXX#ref_language-server-protocol.adoc#
s#XXXmaking-a-workspace-portable-using-a-devfileXXX#assembly_making-a-workspace-portable-using-a-devfile.adoc#
s#XXXmanaging-usersXXX#assembly_managing-users.adoc#
s#XXXmonitoring-cheXXX#assembly_monitoring-che.adoc#
s#XXXmounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-containerXXX#assembly_mounting-secrets-as-file-or-env-variable-in-workspace-container.adoc#
s#XXXmounting-custom-ssl-certificates-to-che-workspace-podsXXX#proc_mounting-custom-ssl-certificates-to-che-workspace-pods.adoc#
s#XXXnavigating-che-using-the-dashboardXXX#assembly_navigating-che-using-the-dashboard.adoc#
s#XXXopenshift-connector-overviewXXX#assembly_openshift-connector-overview.adoc#
s#XXXpersistent-volumes-backupsXXX#con_persistent-volumes-backups.adoc#
s#XXXpublishing-che-theia-plug-insXXX#assembly_publishing-che-theia-plug-ins.adoc#
s#XXXremotely-accessing-che-workspacesXXX#assembly_remotely-accessing-workspaces.adoc#
s#XXXremoving-user-dataXXX#assembly_removing-user-data.adoc#
s#XXXretrieving-che-logsXXX#assembly_retrieving-che-logs.adoc#
s#XXXrunning-che-locallyXXX#assembly_running-che-locally.adoc#
s#XXXsecuring-cheXXX#assembly_securing-che.adoc#
s#XXXtag_assembly.htmlXXX#assembly.adoc#
s#XXXtag_chedir.htmlXXX#chedir.adoc#
s#XXXtag_debugger.htmlXXX#debugger.adoc#
s#XXXtag_dev-docs.htmlXXX#dev-docs.adoc#
s#XXXtag_docker.htmlXXX#docker.adoc#
s#XXXtag_extensions.htmlXXX#extensions.adoc#
s#XXXtag_factories.htmlXXX#factories.adoc#
s#XXXtag_getting-started.htmlXXX#getting-started.adoc#
s#XXXtag_installation.htmlXXX#installation.adoc#
s#XXXtag_keycloak.htmlXXX#keycloak.adoc#
s#XXXtag_kubernetes.htmlXXX#kubernetes.adoc#
s#XXXtag_ldap.htmlXXX#ldap.adoc#
s#XXXtag_networking.htmlXXX#networking.adoc#
s#XXXtag_openshift.htmlXXX#openshift.adoc#
s#XXXtag_organizations.htmlXXX#organizations.adoc#
s#XXXtag_plugins.htmlXXX#plugins.adoc#
s#XXXtag_runtime.htmlXXX#runtime.adoc#
s#XXXtag_troubleshooting.htmlXXX#troubleshooting.adoc#
s#XXXtag_workspace.htmlXXX#workspace.adoc#
s#XXXtesting-che-theia-plug-insXXX#assembly_testing-che-theia-plug-ins.adoc#
s#XXXtracing-cheXXX#assembly_tracing-che.adoc#
s#XXXtroubleshooting-for-che-administratorsXXX#assembly_troubleshooting-for-che-administrators.adoc#
s#XXXtroubleshooting-for-che-end-usersXXX#assembly_troubleshooting-for-che-end-users.adoc#
s#XXXuninstalling-cheXXX#assembly_uninstalling-che.adoc#
s#XXXupgrading-cheXXX#assembly_upgrading-che.adoc#
s#XXXusing-alternative-ides-in-cheXXX#assembly_using-alternative-ides-in-che.adoc#
s#XXXusing-artifact-repositories-in-a-restricted-environmentXXX#assembly_using-artifact-repositories-in-a-restricted-environment.adoc#
s#XXXusing-a-visual-studio-code-extension-in-cheXXX#assembly_using-a-visual-studio-code-extension-in-che.adoc#
s#XXXusing-go-artifact-repositoriesXXX#assembly_using-go-artifact-repositories.adoc#
s#XXXusing-gradle-artifact-repositoriesXXX#assembly_using-gradle-artifact-repositories.adoc#
s#XXXusing-maven-artifact-repositoriesXXX#assembly_using-maven-artifact-repositories.adoc#
s#XXXusing-npm-artifact-repositoriesXXX#proc_using-npm-artifact-repositories.adoc#
s#XXXusing-nuget-artifact-repositoriesXXX#assembly_using-nuget-artifact-repositories.adoc#
s#XXXusing-organizationsXXX#assembly_using-organizations.adoc#
s#XXXusing-python-artifact-repositoriesXXX#assembly_using-python-artifact-repositories.adoc#
s#XXXversion-controlXXX#assembly_version-control.adoc#
s#XXXviewing-che-server-logsXXX#assembly_viewing-che-server-logs.adoc#
s#XXXviewing-che-workspaces-logsXXX#assembly_viewing-che-workspaces-logs.adoc#
s#XXXviewing-external-service-logsXXX#assembly_viewing-external-service-logs.adoc#
s#XXXviewing-kubernetes-eventsXXX#proc_viewing-kubernetes-events.adoc#
s#XXXviewing-plug-in-broker-logsXXX#proc_viewing-plug-in-broker-logs.adoc#
s#XXXwhat-is-a-che-theia-plug-inXXX#assembly_what-is-a-che-theia-plug-in.adoc#
s#XXXworkspaces-overviewXXX#con_workspaces-overview.adoc#
