---
title: Mounting a secret as a file or an environment variable into a workspace container
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/
folder: che-7/end-user-guide
summary:
---

:page-liquid:
:parent-context-of-mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container: {context}

[id="mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as a file or an environment variable into a workspace container

:context: mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

Secrets are Kubernetes objects that store sensitive data such as user names, passwords, authentication tokens, and configurations in an encrypted form.

Users can mount a secret that contains sensitive data in a workspace container. This reapplies the stored data from the secret automatically for every newly created workspace. As a result, the user does not have to provide these credentials and configuration settings manually. 

The following section describes how to automatically mount a Kubernetes secret in a workspace container and create permanent mount points for components such as:

* Maven configuration, the `settings.xml` file 
* SSH key pairs
* AWS authorization tokens
* Git credentials store

A Kubernetes secret can be mounted into a workspace container as:

* A file - This creates automatically mounted Maven settings that will be applied to every new workspace with Maven capabilities.

* An environment variable - This uses SSH key pairs and AWS authorization tokens for automatic authentication. 
+
NOTE: SSH key pairs can also be mounted as a file, but this format is primarily aimed at the settings of the Maven configuration.

The mounting process uses the standard Kubernetes mounting mechanism, but it requires additional annotations and labeling for a proper bound of a secret with the required {prod-short} workspace container.

include::proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc[leveloffset=+1]

include::proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc[leveloffset=+1]

include::proc_mounting-a-git-credential-store-into-a-workspace-container.adoc[leveloffset=+1]

include::ref_the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container.adoc[leveloffset=+1]

:context: {parent-context-of-mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container}

