---
title: Configuring OpenShift OAuth
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/configuring-openshift-oauth/
folder: che-7/end-user-guide
summary:
---

:page-liquid:

[id="configuring-openshift-oauth_{context}"]
= Configuring OpenShift OAuth

OAuth for OpenShift allows to authenticate the link:{site-baseurl}/che-7/openshift-connector-overview/[OpenShift connector plugin] in {prod-short}.

.Procedure

ifeval::["{project-context}" == "che"]
* For {prod-short} deployed in link:{site-baseurl}/che-7/running-che-locally/#deploying-multi-user-che-in-multiuser-mode[multiuser mode]:
+
endif::[]
To enable OpenShift OAuth automatically, {prod-short} should be deployed with the `--os-oauth` option (see link:{link-cli-github}#{prod-cli}-serverstart[`{prod-cli} server:start` specification]).

ifeval::["{project-context}" == "che"]
* For {prod-short} deployed in single-user mode:
. Register {prod-short} OAuth client in OpenShift (see link:https://docs.openshift.com/container-platform/4.3/authentication/configuring-internal-oauth.html#oauth-register-additional-client_configuring-internal-oauth[Register an OAuth client in OpenShift]).
+
[subs="+quotes,+attributes"]
----
$ oc create -f <(echo '
kind: OAuthClient
apiVersion: oauth.openshift.io/v1
metadata:
 name: che
secret: "<random set of symbols>"
redirectURIs:
 - "<{prod-short} api url>/oauth/callback"
grantMethod: prompt
')
----
. Add the OpenShift SSL certificate to the {prod-short} Java trust store.
//TODO yhontyk to uncomment later. For now it turns into an xref that breaks the bccutil build :( 
//See link:{site-baseurl}che-7/advanced-configuration-options/#adding-custom-certificates-to-trust-store_advanced-configuration-options[Adding custom public SSL certificates to {prod-short} trust-store]
. Update the OpenShift deployment configuration
(see link:{site-baseurl}che-7/advanced-configuration-options/#che-configmaps-and-their-behavior_advanced-configuration-options[{prod-short} configMaps and their behavior],
link:{site-baseurl}che-7/advanced-configuration-options/#che-installed-using-a-helm-chart[{prod-short} installed using a Helm Chart]).
+
====
[subs="+quotes,macros"]
----
CHE_OAUTH_OPENSHIFT_CLIENTID: _<client-ID>_
CHE_OAUTH_OPENSHIFT_CLIENTSECRET: _<openshift-secret>_
pass:[CHE_OAUTH_OPENSHIFT_OAUTH__ENDPOINT]: _<oauth-endpoint>_
pass:[CHE_OAUTH_OPENSHIFT_VERIFY__TOKEN__URL]: _<verify-token-url>_
----
====
* `_<client-ID>_` a name specified in the OpenShift OAuthClient.
* `_<openshift-secret>_` a secret specified in the OpenShift OAuthClient.
* `_<oauth-endpoint>_` the URL of the OpenShift OAuth service:
** For OpenShift 3 specify the OpenShift master URL.
** For OpenShift 4 specify the `oauth-openshift` route.
* `_<verify-token-url>_` request URL that is used to verify the token. `<OpenShift master url>/api` can be used for OpenShift 3 and 4.
endif::[]
