---
title: Che-Theia Troubleshooting
keywords: troubleshooting, problem, theia
tags: []
sidebar: che_7_docs
permalink: che-7/che-theia-troubleshooting/
folder: che-7/end-user-guide
summary:
---

:page-liquid:
:parent-context-of-che-theia-troubleshooting: {context}

[id="che-theia-troubleshooting_{context}"]
= Che-Theia Troubleshooting

:context: che-theia-troubleshooting

This section describes some of the most frequent issues with the Che-Theia IDE.

Che-Theia shows a notification with the following message: `Plugin runtime crashed unexpectedly, all plugins are not working, please reload the page. Probably there is not enough memory for the plugins.`::

  This means that one of the Che-Theia plug-ins that are running in the Che-Theia IDE container requires more memory than the container has. To fix this problem, increase the amount of memory for the Che-Theia IDE container:

  . Navigate to the {prod-short} Dashboard.
  . Select the workspace in which the problem happened.
  . Switch to the *Devfile* tab.
  . In the `components` section of the devfile, find a component of the `cheEditor` type.
  . Add a new property, `memoryLimit: 1024M` (or increase the value if it already exists).
  . Save changes and restart the workspace.


.Additional resources

* Asking the community for help: link:https://mattermost.eclipse.org/eclipse/channels/eclipse-che[Mattermost channel] dedicated to {prod}.
* Reporting a bug: link:https://github.com/eclipse/che[{prod} repository issues].

:context: {parent-context-of-che-theia-troubleshooting}
