// This assembly is included in the following assemblies:
//
// what-is-a-che-theia-plug-in

:parent-context-of-remote-plug-in-endpoint: {context}

[id="remote-plug-in-endpoint_{context}"]
= Remote plug-in endpoint

:context: remote-plug-in-endpoint

{prod} has a remote plug-in endpoint service to start VS Code Extensions and Che-Theia plug-ins in separate containers. {prod} injects the remote plug-in endpoint binaries into each remote plug-in container. This service starts remote extensions and plug-ins defined in the plug-in `meta.yaml` file and connects them to the Che-Theia editor container.

The remote plug-in endpoint creates a plug-in API proxy between the remote plug-in container and the Che-Theia editor container. The remote plug-in endpoint is also an interceptor for some plug-in API parts, which it launches inside a remote sidecar container rather than an editor container. Examples: terminal API, debug API.

The remote plug-in endpoint executable command is stored in the environment variable of the remote plug-in container: `+PLUGIN_REMOTE_ENDPOINT_EXECUTABLE+`.

{prod} provides two ways to start the remote plug-in endpoint with a sidecar image:

* Defining a launch remote plug-in endpoint using a Dockerfile. To use this method, patch an original image and rebuild it.
* Defining a launch remote plug-in endpoint in the plug-in `meta.yaml` file. Use this method to avoid patching an original image.

include::proc_defining-a-launch-remote-plug-in-endpoint-using-dockerfile.adoc[leveloffset=+1]
include::proc_defining-a-launch-remote-plug-in-endpoint-in-a-meta-yaml-file.adoc[leveloffset=+1]

:context: {parent-context-of-remote-plug-in-endpoint}
