// Module included in the following assemblies:
//
// using-a-visual-studio-code-extension-in-{prod-id-short}

:parent-context-of-publishing-a-vs-code-extension-into-the-che-plug-in-registry: {context}

[id="publishing-a-vs-code-extension-into-the-{prod-id-short}-plug-in-registry_{context}"]
= Publishing a VS Code extension into the {prod-short} plug-in registry

:context: publishing-a-vs-code-extension-into-the-{prod-id-short}-plug-in-registry

The user of {prod-short} can use a workspace devfile to use any plug-in, also known as Visual Studio Code (VS Code) extension. This plug-in can be added to the plug-in registry, then easily reused by anyone in the same organization with access to that workspaces installation.

Some plug-ins need a runtime dedicated container for code compilation. This fact makes those plug-ins a combination of a runtime sidecar container and a VS Code extension.

The following section describes the portability of a plug-in configuration and associating an extension with a runtime container that the plug-in needs.

include::proc_writing-a-meta-yaml-file-and-adding-it-to-a-plug-in-registry.adoc[leveloffset=+1]

// TODO: remove this condition when the downstream counterpart is fixed - currently commented out
ifeval::["{project-context}" == "che"]
.Additional resources
To set up a custom plug-in registry, see: {link-building-a-custom-plug-in-registry}.
endif::[]

:context: {parent-context-of-publishing-a-vs-code-extension-into-the-che-plug-in-registry}
