---
title: Configuring workspace exposure strategies
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/configuring-workspace-exposure-strategies/
folder: che-7/end-user-guide
summary:
---

:page-liquid:
:context: configuring-workspace-exposure-strategies

[id="configuring-workspace-exposure-strategies_{context}"]
= Configuring workspace exposure strategies

The following section describes how to configure workspace exposure strategies of a Che server and ensure that applications running inside are not vulnerable to outside attacks.

The workspace exposure strategy is configured per Che server, using the che.infra.kubernetes.server_strategy configuration property or the `pass:[CHE_INFRA_KUBERNETES_SERVER__STRATEGY]` environment variable.

The possible values are respectively:

* multi-host
* single-host
* default-host

In case of the multi-host strategy, you must set the che.infra.kubernetes.ingress.domain (or the `CHE_INFRA_KUBERNETES_INGRESS_DOMAIN` environment variable) configuration property to the domain name that should host subdomains of the workspace components.

include::con_workspace-exposure-strategies.adoc[leveloffset=+1]

include::proc_configuring-workspace-exposure-strategies-using-the-helm-chart-and-the-operator.adoc[leveloffset=+1]

include::con_security-considerations.adoc[leveloffset=+1]
