---
title: Converting a Che 6 workspace to a devfile
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/converting-a-che-6-workspace-to-a-devfile/
redirect_from:
  - factories-getting-started.html
folder: che-7/end-user-guide
summary:
---

// using-developer-environments-workspaces
:page-liquid:
:parent-context-of-converting-a-che-6-workspace-to-a-devfile: {context}

[id="converting-a-{prod-id-short}-{prod-prev-ver-major}-workspace-to-a-devfile_{context}"]
= Converting a {prod-short} {prod-prev-ver-major} workspace to a devfile

:context: converting-a-{prod-id-short}-{prod-prev-ver-major}-workspace-to-a-devfile

This section describes how to manually convert a {prod-short} {prod-prev-ver-major} workspace configuration to a {prod-short} {prod-ver-major} devfile. The following are the benefits of using a devfile:

* Using a portable file that works with any installation of {prod-short}; nothing needs to be changed on the server to start a workspace.

* Configuration can be stored in project repository and automatically used by {prod-short} to start a workspace. To start a workspace, specify a devfile using the following format: `__<che-instance-domain>__/f?url=path`, for example:
+
----
https://che.openshift.io/f?url=https://raw.githubusercontent.com/redhat-developer/devfile/master/getting-started/vertx/devfile.yaml
----
+
This creates and starts a new workspace based on the link:https://github.com/redhat-developer/devfile/blob/master/getting-started/vertx/devfile.yaml[devfile] defined in the URL attribute.

* A human-readable YAML format for all content.


include::ref_comparing-che-6-workspace-to-a-devfile.adoc[leveloffset=+1]

include::proc_converting-a-che-6-workspace-to-a-basic-che-7-devfile.adoc[leveloffset=+1]

include::proc_accessing-che-6-workspace-configuration.adoc[leveloffset=+1]

:context: {parent-context-of-converting-a-che-6-workspace-to-a-devfile}
