// defining-custom-commands-for-che-theia

[id="che-theia-task-types_{context}"]
= Che-Theia task types

There are two types of tasks in a devfile: tasks in the VS Code format and {prod-short} commands. Tasks from the devfile are copied to the configuration file when the workspace is started. Depending on the type of the task, the task is then available for running:

* {prod-short} commands: From the *Terminal* -> *Run Task* menu in the *configured tasks* section, or from the *My Workspace* panel

* Tasks in the VS Code format: From the *Run Tasks* menu

To run the task definitions provided by plug-ins, select the *Terminal* -> *Run Task* menu option. The tasks are placed in the *detected tasks* section.

////
[discrete]
== Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
