// making-a-workspace-portable-using-a-devfile

[id="what-is-a-devfile_{context}"]
= What is a devfile

A devfile is a file that describes a development environment:

* the source code
* the development components (IDE tools and application runtimes)
* a list of pre-defined commands

Devfiles are YAML files that Che consumes and transforms into a cloud workspace composed of multiple containers. The devfile can be saved in the root folder of a Git repository, a feature branch of a Git repository, a publicly accessible destination, or as a separate, locally stored artifact.

Che uses 'devfile' to define:

* projects to clone
* browser IDE to use
* preconfigured commands
* tools that you need
* application runtime definition

When you create a workspace, Che uses that definition to initiate everything for you and run all the containers for your tools and your application runtimes. Che also mounts filesystem volumes to make your source code available to the workspace.

Devfiles can be versioned with the project source code. When you have to get a workspace to fix an old maintenance branch, the project devfile provides you with a definition of the workspace with the tools and the exact dependencies to start working on the old branch. Use it to easily instantiate workspaces on demand.

Che maintains the devfile up-to-date with the tools you use in the workspace:

* Projects of the workspace (path, Git location, branch)
* Commands to perform daily tasks (build, run, test, debug)
* Runtime environment (container images to run your application)
* Che-Theia plug-ins with tools, IDE features, and helpers that a developer would use in the workspace (Git, Java support, Sonarlint, Pull Request)
