// Module included in the following assemblies:
//
// configuring-workspace-exposure-strategies

[id="security-considerations_{context}"]
= Security considerations

This section explains the security impact of using different {prod-short} workspace exposure strategies.

All the security-related considerations in this section are only applicable to {prod-short} in multiuser mode. The single user mode does not impose any security restrictions.

[id="json-web-token-jwt-proxy_{context}"]
== JSON web token (JWT) proxy

All {prod-short} plug-ins, editors, and components can require authentication of the user accessing them. This authentication is performed using a JSON web token (JWT) proxy that functions as a reverse proxy of the corresponding component, based on its configuration, and performs the authentication on behalf of the component.

The authentication uses a redirect to a special page on the {prod-short} server that propagates the workspace and user-specific authentication token (workspace access token) back to the originally requested page.

The JWT proxy accepts the workspace access token from the following places in the incoming requests, in the following order:

. The token query parameter
. The Authorization header in the bearer-token format
. The `access_token` cookie

== Secured plug-ins and editors

{prod-short} users do not need to secure workspace plug-ins and workspace editors (such as Che-Theia). This is because the JWT proxy authentication is transparent to the user and is governed by the plug-in or editor definition in their `meta.yaml` descriptors.

== Secured container-image components

Container-image components can define custom endpoints for which the devfile author can require {prod-short}-provided authentication, if needed. This authentication is configured using two optional attributes of the endpoint:

* `secure` - A boolean attribute that instructs the {prod-short} server to put the JWT proxy in front of the endpoint. Such endpoints have to be provided with the workspace access token in one of the several ways explained in xref:#json-web-token-jwt-proxy_{context}[]. The default value of the attribute is `false`.

* `cookiesAuthEnabled` - A boolean attribute that instructs the {prod-short} server to automatically redirect the unauthenticated requests for current user authentication as described in xref:#json-web-token-jwt-proxy_{context}[]. Setting this attribute to `true` has security consequences because it makes Cross-site request forgery (CSRF) attacks possible. The default value of the attribute is `false`.

== Cross-site request forgery attacks

Cookie-based authentication can make an application secured by a JWT proxy prone to Cross-site request forgery (CSRF) attacks. See the link:https://en.wikipedia.org/wiki/Cross-site_request_forgery[Cross-site request forgery] Wikipedia page and other resources to ensure your application is not vulnerable.

== Phishing attacks

An attacker who is able to create an Ingress or route inside the cluster with the workspace that shares the host with some services behind a JWT proxy, the attacker may be able to create a service and a specially forged Ingress object. When such a service or Ingress is accessed by a legitimate user that was previously authenticated with a workspace, it can lead to the attacker stealing the workspace access token from the cookies sent by the legitimate user’s browser to the forged URL.
To eliminate this attack vector, configure OpenShift to disallow setting the host of an Ingress.
