// configuring-workspace-exposure-strategies

[id="workspace-exposure-strategies_{context}"]
= Workspace exposure strategies

Specific components of workspaces need to be made accessible to the “world” outside of the Kubernetes or OpenShift cluster. This is typically the user interface of the workspace’s IDE, but can also be the web UI of the application being developed. This enables developers to interact with the application during the development process.

Che supports three ways how to make workspace components available to the users, also referred to as _strategies_:

* multi-host strategy
* single-host strategy
* default-host strategy

These strategies define whether new subdomains will be created for the components of the workspace, and what hosts those components will be available on.

== Multi-host strategy
With this strategy, each workspace component is assigned with a new subdomain of the main domain configured for the Che server. On OpenShift, this is the only possible strategy, and manual configuration of the workspace exposure strategy is therefore always ignored.

This strategy is the easiest to understand from the perspective of component deployment because any paths present in the URL to the component will be received as is by the component.

On the other hand, if the Che server is secured using Transport Layer Security protocol (TLS), creating new subdomains for each component of each workspace requires a wildcard certificate to be available for all such subdomains for the Che deployment to be practical.

== Single-host strategy
This strategy is available on Kubernetes, but not on OpenShift. When it is used, all workspaces are deployed to subpaths of the main Che server domain.

This is convenient for TLS-secured Che servers, because it is enough to have a single certificate for the Che server, which will cover all the workspace component deployments as well.

On the other hand, this strategy poses certain limitations on the exposed components or user applications. Any absolute URL generated on the server side that points back to the server will not work. This is because the server is hidden behind a path-rewriting ingress that hides the workspace and component-specific URL prefix from the server.

For example, when the user accesses the hypothetical _https://che-host/component-prefix-djh3d/app/index.php_ URL, the application sees the request coming to https://internal-host/app/index.php. If the application used the host in the URL that it generates in its UI, this would not work, because the internal host is different from the externally visible host. However,if the application used just an absolute path as the URL(for the example above, this would be _/app/index.php_), such URL would still not work. This is because, on the outside, such URL does not point to the application, because it is missing the component-specific prefix.

Hence, only applications strictly using relative URLs in their UI will work with the single-host workspace exposure strategy.

== Default-host strategy
This strategy exposes the components to the outside world on the subpaths of the default host of the cluster. As such it is quite similar to single-host strategy, with all the limitations and advantages of the single-host mode applying to this mode as well.
