---
title: Workspaces overview
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/workspaces-overview/
redirect_from:
  - what-are-workspaces.html
folder: che-7/end-user-guide
summary:
---

:page-liquid:

[id="workspaces-overview_{context}"]
= Workspaces overview

{prod} provides developer workspaces with everything needed to a code, build, test, run, and debug applications. To allow that, the developer workspaces provide four main components:

. The source code of a project.
. A web-based IDE.
. Tool dependencies, needed by developers to work on a project
. Application runtime: a replica of the environment where the application runs in production

Pods manage each component of a {prod-short} workspace. Therefore, everything running in a {prod-short} workspace is running inside containers. This makes a {prod-short} workspace highly portable.

The embedded browser-based IDE is the point of access for everything running in a {prod-short} workspace. This makes a {prod-short} workspace easily shareable.

IMPORTANT: By default, it is possible to run only one workspace at a time.
To change the default value, see: {link-limits-for-the-workspaces-of-an-user}.

.Features and benefits
[options="header",cols="h,,"]
|===
| Features
| Traditional IDE workspaces
| {prod} workspaces

| Configuration and installation required
| Yes.
| No.

| Embedded tools
| Partial. IDE plug-ins need configuration. Dependencies need installation and configuration. Example: JDK, Maven, Node.
| Yes. Plug-ins provide their dependencies.

| Application runtime provided
| No. Developers have to manage that separately.
| Yes. Application runtime is replicated in the workspace.

| Shareable
| No. Or not easily
| Yes. Developer workspaces are shareable with a URL.

| Versionable
| No
| Yes. Devfiles exist with project source code.

| Accessible from anywhere
| No. Installation is needed.
| Yes. Only requires a browser.
|===

To start a {prod-short} workspace, following options are available:

* link:{site-baseurl}che-7/creating-and-configuring-a-new-che-7-workspace[Creating and configuring a new {prod-short} {prod-ver} workspace using the Dashboard].

* link:{site-baseurl}che-7/configuring-a-workspace-using-a-devfile[Configuring a {prod-short} {prod-ver} workspace using a devfile].

Use the Dashboard to discover {prod-short} {prod-ver}:

* link:{site-baseurl}che-7/creating-a-workspace-from-code-sample[Creating a workspace from code sample]

* link:{site-baseurl}che-7/creating-a-workspace-by-importing-source-code-of-a-project[Creating a workspace by importing source code of a project]

Use a devfile as the preferred way to start a {prod-short} {prod-ver} workspace:

* link:{site-baseurl}che-7/making-a-workspace-portable-using-a-devfile[Making a workspace portable using a devfile]

* link:{site-baseurl}che-7/converting-a-che-6-workspace-to-a-che-7-devfile[Converting a {prod-short} {prod-prev-ver} Workspace to a {prod-short} {prod-ver} devfile]

* link:{site-baseurl}che-7/importing-a-kubernetes-application-into-a-che-workspace[Importing a Kubernetes application into a {prod-short} workspace]

Use the browser-based IDE as the preferred way to interact with a {prod-short} {prod-ver} workspace. For an alternative way to interact with a {prod-short} {prod-ver} workspace, see: link:{site-baseurl}che-7/remotely-accessing-che-workspaces[Remotely accessing workspaces].
