[id="embedded-and-remote-che-theia-plug-ins_{context}"]
= Embedded and remote Che-Theia plug-ins

Developer workspaces in Eclipse Che provide all dependencies needed to work on a project. The application includes the dependencies needed by all the tools and plug-ins used.

There are two different ways a Che-Theia plug-in can run. This is based on the dependencies that are needed for the plug-in:

Embedded (or local) plug-in::
The plug-in does not have specific dependencies -- it only uses a Node.js runtime, and it runs in the same container as the IDE. The plug-in is injected into the IDE.
+
Examples:
+
* Code linting
* New set of commands
* New UI components

Remote plug-in::
The plug-in relies on dependencies or it has a backend. It runs in its own sidecar container, and all dependencies are packaged in the container.
+
Examples:
+
* Java Language Server
* Python Language Server

Depending on your use case and the capabilities provided by your plug-in, select one of the described running modes.


// [discrete]
// == Additional resources
//
// * A bulleted list of links to other material closely related to the contents of the concept module.
// * For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
// * Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
