// Module included in the following assemblies:
//
// configuring-a-workspace-using-a-devfile

[id="disambiguation-between-stacks-and-devfiles_{context}"]
= Disambiguation between stacks and devfiles

This section describes differences between stacks in {prod-short} {prod-prev-ver} and devfiles in {prod-short} {prod-ver}

Starting with {prod-short} {prod-ver}:

* A stack is a pre-configured {prod-short} workspace.
* A devfile is a configuration YAML file that {prod-short} consumes and transforms in a cloud workspace composed of multiple containers.

In {prod-short} {prod-prev-ver}, stacks were defined by a `stacks.json` file that was included with the `che server`.
In contrast, in {prod-short} {prod-ver}, the `stacks.json` file does not exist. Instead, a stack is defined in the devfile registry, which is a separate service. Every single devfile in the registry corresponds to a stack.

Note that in {prod-short} {prod-prev-ver}, stacks and workspaces were defined using two different formats. However, with {prod-short} {prod-ver}, the devfile format is used to define both the stacks and the workspaces. Nevertheless, a user opening the user dashboard does not notice any difference: in {prod-short} {prod-ver}, a list of stacks is still present to choose from as a starting point to create a workspace.


////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
