// Module included in the following assemblies:
//
// defining-custom-commands-for-che-theia

[id="che-theia-task-types_{context}"]
= Che-Theia task types

The `commands` section in a devfile allows a user to automate certain actions when running a Che workspace.

There are three types of Che commands:

* `exec`: Each command of type `exec` is translated into a Che-Theia task of type `che`. A `che` command executes a shell command, but in contrast to regular Che-Theia shell-type tasks, a user can choose a workspace container for the command execution.
* `vscode-task`: `vscode-task` is a single command type that copies the contents of the `referenceContentfield` of the specific command directly to the user-level task configurations in Che-Theia.
* `vscode-launch`: Functions like a `vscode-task` command, but instead of being copied into the task configurations, the content of the `referenceContent` field is copied into the `launch.json` configuration file.

Tasks of type `che`, also known as `exec` commands, can be executed from the *Terminal->Run Task* menu or by clicking them in the *My Workspace* panel.
Other tasks are only available via *Terminal->Run Task*. Launch configurations are available in the Che-Theia debugger.

.Example:

The following example contains a  `che` task and `vscode-task` task sample.

The configuration in link:https://www.eclipse.org/che/docs/che-7/defining-custom-commands-for-che-theia/[Defining custom commands for Che-Theia] sets up the `theia:watch` and `theia:build` tasks in the `theia` workspace:

* `theia:watch`, which runs the `theia` project in `watch` mode.
* `theia:build`, which builds the `theia` project in the `che-dev` component.


.Descriptions of used `che` commands in the above-mentioned example `theia:build`
* The `exec` type implies that the Che runner is used for command execution. 
* The user can specify the component in whose container the command is executed.
* The `command` field contains the command line for execution.
* The `workdir` is the working directory in which the command is executed.

These tasks are available for running in a workspace from the *Terminal->Run Task* menu or by clicking them in the *My Workspace* panel.

.Additional examples
* link:https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus-command-mode/devfile.yaml#L63-L71[Theia task of type `che` example]
* link:https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus-command-mode/devfile.yaml#L84-L100[`vscode-lunch` task example`] 
