// Module included in the following assemblies:
//
// defining-custom-commands-for-che-theia

[id="che-theia-task-types_{context}"]
= Che-Theia task types

The following is an example of the `commands` section of a devfile.

[source,yaml]
----
commands:

  - name: Package Native App
    actions:
      - type: exec
        component: centos-quarkus-maven
        command: "mvn package -Dnative -Dmaven.test.skip"
        workdir: ${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started

  - name: Start Native App
    actions:
      - type: exec
        component: ubi-minimal
        command: ./getting-started-1.0-SNAPSHOT-runner
        workdir: ${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started/target

  - name: Attach remote debugger
    actions:
    - type: vscode-launch
      referenceContent: |
        {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "request": "attach",
              "name": "Attach to Remote Quarkus App",
              "hostName": "localhost",
              "port": 5005
            }
          ]
        }
----

prod-short} commands:: `Package Native App` and `Start Native App`
+
The {prod-short} commands are to be used to define tasks that will be executed in the workspace container.
+
* The `exec` type implies that the {prod-short} runner is used for command execution. The user can specify the component in whose container the command is executed.
* The `command` field contains the command line for execution.
* The `workdir` is the working directory in which the command is executed.
* The `component` field refers to the container where the command will be executed. The field contains the component `alias` where the container is defined.

VS Code launch configurations:: `Attach remote debugger`
+
VS Code launch configurations are usually used to define debugging configuration. To trigger these configurations, press btn:[F5] or choose *Start Debugging* from the *Debug* menu. The configurations provide information to the debugger, such as the port to connect to for debugging or the type of the application to debug (Node.js, Java, and others.).
+
* The type is `vscode-launch`.
* It contains the launch configurations in the VS Code format.
* For more information about VS Code launch configurations, see the Debugging section on the link:https://code.visualstudio.com/docs/editor/debugging#_launch-configurations[Visual Studio documentation page].

Tasks of type `che`, also known as `exec` commands, can be executed from the *Terminal->Run Task* menu or by selecting them in the *My Workspace* panel. Other tasks are only available from *Terminal->Run Task*. Launch configurations are available in the Che-Theia debugger.


.Additional examples
* link:https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus-command-mode/devfile.yaml#L63-L71[Theia task of type `che` example]
* link:https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus-command-mode/devfile.yaml#L84-L100[`vscode-lunch` task example`] 
