// Module included in the following assemblies:
//
// adding-tools-to-{prod-id-short}-after-creating-a-workspace

[id="additional-tools-in-the-{prod-id-short}-workspace_{context}"]
= Additional tools in the {prod-short} workspace

{prod-short} plug-ins are extensions to the Che-Theia IDE that come bundled with a container image that contains their native prerequisites (for example, the OpenShift Connector plug-in needs the `oc` command installed). A Che Plugin is a list of Che-Theia plug-ins together about a Linux container that the plug-in requires to run in. It can also include metadata to define the description, categorization tags, and an icon.
{prod-short} provides a registry of plug-ins available for installation into the user's workspace.

Because many VS Code extensions can run inside the Che-Theia IDE, they can be packaged as {prod-short} plug-ins by combining them with a runtime or a sidecar container. Users can choose from many more plug-ins that are provided out of the box.

From the Dashboard, plug-ins in the registry can be added from the *Plugin* tab or by adding them into a devfile. The devfile can also be used for further configuration of the plug-in, such as to define memory or CPU usage.
Alternatively, plug-ins can be installed from {prod-short} by pressing kbd:[Ctrl+Shift+J] or by navigating to *View -> Plugins*.

.Additional resources

* link:{site-baseurl}che-7/making-a-workspace-portable-using-a-devfile/#adding-components-to-a-devfile_making-a-workspace-portable-using-a-devfile[Adding components to a devfile]

////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
