[id="plug-in-concept-in-detail_{context}"]
= Plug-in concept in detail

Eclipse Che provides a default web IDE for the workspaces which is based on Eclipse Theia. It’s a subtle different version than a plain Eclipse Theia as there are functionalities that have been added based on the nature of the Eclipse Che workspaces. We are calling this version of Eclipse Theia for Che: *CheTheia.*

In CheTheia, you’ll find the following capabilities:

[options="header"]
|===
| *Plug-in*               | *Description* | *Repository*
| *Che Extended Tasks*    | Handles the Che commands and provides the ability to start those into a specific container of the workspace. | link:TODO[TODO LINK]
| *Che Extended Terminal* | Allows to provide terminal for any of the containers of the workspace. | link:TODO[TODO LINK]
| *Che Factory* | Handles the Eclipse Che Factories | link:TODO[TODO LINK]
| *Che Container*         | Provides a container view that shows all the containers that are running in the workspace and allows to interact with them. | https://github.com/eclipse/che-theia/tree/master/plugins/containers-plugin[Containers plugins]
| *Che Dashboard*         | Allows to integrate the IDE with Che Dashboard and facilitate the navigation. | link:TODO[TODO LINK]
| *Che APIs*              | Extends the IDE APis, to allow interacting with the Che specific components (workspaces, preferences, etc.). | link:TODO[TODO LINK]
|===

When extending the IDE provided with Eclipse Che, you’ll be building a *Che Plug-in* . The Che Plug-ins are compatible with *CheTheia* or any other Eclipse Theia based IDE.

A Che Plug-in is built on either:

* A Visual Studio Code Extension
* An Eclipse Theia Plug-in

If you have already built your plug-in as a Visual Studio Code Extension, you can build the corresponding Che Plug-in by repackaging the extension. If the extension is relying on its own set of dependencies, you’ll need to package those into a container. Eclipse Che users will get the plug-in and not have to worry about the tools dependencies.

Learn more about remote and local plug-in in link:TODO[TODO LINK].

Learn more about how to repackage a VSCode Extension into Eclipse Che link:TODO[TODO LINK].

For the purpose of providing tools isolation and easy extensibility in Eclipse Che, we’ve added and maintain plug-ins APIs into Eclipse Theia. The APIs are providing compatibility with the Visual Studio Code Extension. You can read more at link:TODO[TODO LINK].

You can build a Che Plug-in, by implementing an Eclipse Theia plug-in and packaging it to Eclipse Che. Learn more about how to package an Eclipse Che Plug-in at link:TODO[TODO LINK].

If the plug-in you are authoring will rely or interact with the components of Che workspaces (containers, preferences, factories…), you can rely on the Che APIs that are embedded in CheTheia. Learn more about the Che APIsat link:TODO[TODO LINK].


// [discrete]
// == Additional resources
//
// * A bulleted list of links to other material closely related to the contents of the concept module.
// * For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
// * Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
