// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-a-file-into-a-workspace-container_{context}"]
= Mounting a secret as a file into a workspace container

WARNING: On Kubernetes older than v1.13 and OpenShift older than 4, secrets mounted as file overrides volume mounts defined in the devfile.

This section describes how to mount a secret from the user's {orch-namespace} as a file in single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].

.Procedure

. Create a new Kubernetes secret in the Kubernetes {orch-namespace} where a {prod-short} workspace will be created.

* The labels of the secret that is about to be created must match the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}. The default labels are:

* `app.kubernetes.io/part-of: che.eclipse.org` 
* `app.kubernetes.io/component: workspace-secret`:
+
include::examples/{project-context}-ref_a-kubernetes-secret-as-a-file.adoc[levelofset=+1]
