// Module included in the following assemblies:
//
// making-a-workspace-portable-using-a-devfile

[id="writing-a-devfile-for-your-project_{context}"]
= Writing a devfile for a project

This section describes how to create a minimal devfile for your project and how to include more than one projects in a devfile.

[id="preparing-a-minimal-devfile_{context}"]
== Preparing a minimal devfile

A minimal devfile sufficient to run a workspace consists of the following parts:

* Specification version
* Name

.Example of a minimal devfile with no project
[source,yaml]
----
apiVersion: 1.0.0
metadata:
  name: minimal-workspace
----

Without any further configuration, a workspace with the default editor is launched along with its default plug-ins, which are configured on the {prod-short} Server. Che-Theia is configured as the default editor along with the *{prod-short} Machine Exec* plug-in. When launching a workspace within a Git repository using a factory, the project from the given repository and branch is be created by default. The project name then matches the repository name.

Add the following parts for a more functional workspace:

* List of components: Development components and user runtimes
* List of projects: Source code repositories
* List of commands: Actions to manage the workspace components, such as running the development tools, starting the runtime environments, and others

.Example of a minimal devfile with a project
[source,yaml]
----
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/spring-projects/spring-petclinic.git'
components:
  - type: chePlugin
    id: redhat/java/latest
----


[id="specifying-multiple-projects-in-a-devfile_{context}"]
== Specifying multiple projects in a devfile

A single devfile can specify multiple projects. For each project, specify the type of the source repository, its location, and, optionally, the directory the project is cloned to.

.Example of a devfile with two projects
[source,yaml]
----
apiVersion: 1.0.0
metadata:
  name: example-devfile
projects:
- name: frontend
  source:
    type: git
    location: https://github.com/acmecorp/frontend.git
- name: backend
  clonePath: src/github.com/acmecorp/backend
  source:
    type: git
    location: https://github.com/acmecorp/backend.git
----

In the preceding example, there are two projects defined, `frontend` and `backend`. Each project is located in its own repository. The `backend` project has a specific requirement to be cloned into the `src/github.com/acmecorp/backend/` directory under the source root (implicitly defined by the {prod-short} runtime) while the `frontend` project will be cloned into the `frontend/` directory under the source root.


.Additional resources

For a detailed explanation of all devfile component assignments and possible values, see:

* link:https://github.com/redhat-developer/devfile[Specification repository]
* link:https://redhat-developer.github.io/devfile/devfile[Detailed json-schema documentation]

These sample devfiles are a good source of inspiration:

* link:https://github.com/eclipse/che-devfile-registry/tree/master/devfiles[Sample devfiles for {prod} workspaces used by default in the user interface].
* link:https://github.com/redhat-developer/devfile/tree/master/samples[Sample devfiles for {prod} workspaces from Red Hat Developer program].
