// Module included in the following assemblies:
//
// using-a-visual-studio-code-extension-in-{prod-id-short}

[id="choosing-the-sidecar-image_{context}"]
= Choosing the sidecar image

{prod-short} plug-ins are special services that extend the {prod-short} workspace capabilities. {prod-short} plug-ins are packaged as containers. The containers that the plug-ins are packaged into run as _sidecars_ of the {prod-short} workspace editor and augment its capabilities.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].

.Procedure

To choose a sidecar image:

. If the VS Code extension does not have any external dependencies, use `eclipse/che-theia-endpoint-runtime: next` as a sidecar container image for the extension.
+
[NOTE]
====
In addition to the `eclipse/che-theia-endpoint-runtime:next` base image, the following ready-to-use sidecar images that include language-specific dependencies are available:

* eclipse/che-remote-plugin-runner-java8
* eclipse/che-remote-plugin-runner-java11
* eclipse/che-remote-plugin-go-1.10.7
* eclipse/che-remote-plugin-python-3.7.3
* eclipse/che-remote-plugin-dotnet-2.2.105
* eclipse/che-remote-plugin-php7
* eclipse/che-remote-plugin-kubernetes-tooling-1.0.0
* eclipse/che-remote-plugin-kubernetes-tooling-0.1.17
* eclipse/che-remote-plugin-openshift-connector-0.0.17
* eclipse/che-remote-plugin-openshift-connector-0.0.21
====

For a VS Code extension with external dependencies not found in one of the ready-to-use images, use a container image based on the `eclipse/che-theia-endpoint-runtime:next` image that contains the dependencies.

.Example
Base the `FROM` directive on `FROM eclipse/che-theia-endpoint-runtime:next`. This is required because the base image contains tools for running the remote VS Code extension and for communicating between the sidecar and the Che-Theia editor. This way, the VS Code extension operates as if it was not remote.
