[id="adding-the-vs-code-extension-using-the-workspace-configuration_{context}"]
= Adding the VS Code extension using the workspace configuration

.Prerequisites

* A running instance of Eclipse Che. To install an instance of Eclipse Che, see link:{site-baseurl}che-7/che-quick-starts/[Che 'quick-starts'].

* An existing workspace defined on this instance of Eclipse Che link:{site-baseurl}che-7/creating-and-configuring-a-new-che-7-workspace/[Creating a workspace from user dashboard].

.Procedure

To add the VS Code extension using the workspace configuration:

. Click the *Workspaces* tab on the *Dashboard* and select the workspace in which you want to add the plug-in. The *Workspace __<workspace-name>__* window is opened showing the details of the workspace.

. Click the *devfile* tab.

. Locate the *components* section, and add a new entry with the following structure:
+
[source,yaml,subs="+quotes"]
----
 - type: chePlugin
   id:              <1>
----
<1> Link to the `meta.yaml` file in your registry, for example, `https://my-plugin-registry/v3/plugins/__<publisher>__/__<plug-inName>__/__<plug-inVersion>__/meta.yaml`
+
Che automatically adds the other fields to the new component.

. Restart the workspace for the changes to take effect.
