// Module included in the following assemblies:
//
// importing-a-kubernetes-application-into-a-workspace

:page-liquid:

[id="generating-a-devfile-from-an-existing-kubernetes-application_{context}"]
= Generating a devfile from an existing Kubernetes application

This procedure demonstrates how to generate a devfile from an existing Kubernetes application using the `{prod-cli}` tool.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see {link-installing-an-instance}.

* The `{prod-cli}` management tool is available. See link:{site-baseurl}che-7/using-the-{prod-cli}-management-tool/[Using the `{prod-cli}` management tool].

.Procedure

. Use the `{prod-cli} devfile:generate` command to generate a devfile:
+
[subs="+attributes"]
----
$ {prod-cli} devfile:generate
----

* The user can also use the `{prod-cli} devfile:generate` command to generate a devfile from, for example, the `NodeJS-MongoDB` application.
+
The following example generates a devfile that includes the `NodeJS` component:
+
[subs="+attributes"]
----
$ {prod-cli} devfile:generate --selector="app=nodejs"
apiVersion: 1.0.0
metadata:
  name: {prod-cli}-generated
components:
  - type: kubernetes
    alias: app=nodejs
    referenceContent: |
      kind: List
      apiVersion: v1
      metadata:
        name: app=nodejs
      items:
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            labels:
              app: nodejs
            name: web
(...)
----
+
The Node.js application YAML definition is available in the devfile, inline, using the `referenceContent` attribute.

* To include support for a language, use the `--language` parameter:
+
[subs="+attributes"]
----
$ {prod-cli} devfile:generate --selector="app=nodejs" --language="typescript"
apiVersion: 1.0.0
metadata:
  name: {prod-cli}-generated
components:
  - type: kubernetes
    alias: app=nodejs
    referenceContent: |
      kind: List
      apiVersion: v1
(...)
  - type: chePlugin
    alias: typescript-ls
    id: che-incubator/typescript/latest
----

. Use the generated devfile to start a {prod-short} workspace with `{prod-cli}`.

