// Module included in the following assemblies:
//
// using-a-visual-studio-code-extension-in-{prod-id-short}

[id="choosing-the-sidecar-image_{context}"]
= Choosing the sidecar image

{prod-short} plug-ins are special services that extend the {prod-short} workspace capabilities. {prod-short} plug-ins are packaged as containers. The containers that the plug-ins are packaged into run as _sidecars_ of the {prod-short} workspace editor and augment its capabilities.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see {link-installing-an-instance}.

.Procedure

To choose a sidecar image:

. If the VS Code extension does not have any external dependencies, use `eclipse/che-theia-endpoint-runtime: next` as a sidecar container image for the extension.
+
include::examples/che-choosing-the-sidecar-image-images.adoc[leveloffset=+1]

For a VS Code extension with external dependencies not found in one of the ready-to-use images, use a container image based on the `{theia-endpoint-image}` image that contains the dependencies.

.Example
Base the `FROM` directive on `FROM {theia-endpoint-image}`. This is required because the base image contains tools for running the remote VS Code extension and for communicating between the sidecar and the Che-Theia editor. This way, the VS Code extension operates as if it was not remote.
