// version-control

[id="managing-pull-requests-using-the-github-pr-plug-in_{context}"]
= Managing pull requests using the GitHub PR plug-in

To manage GitHub pull requests, the VS Code GitHub Pull Request plug-in is available in the list of plug-ins of the workspace.


== Using the GitHub Pull Requests plug-in

.Prerequisites

* GitHub OAuth should be configured (see https://www.eclipse.org/che/docs/che-7/version-control/#configuring-github-oauth_version-control[Configuring GitHub OAuth)]

.Procedure

 . Authenticate by running the *GitHub authenticate* command.
 . You will be redirected to GitHub to authorize Che.
 . When Che is authorized, refresh the browser page where Che is running to update the plug-in with the GitHub token.

You can also manually https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line[fetch the GitHub token] and paste it to the plug-in by running *GitHub Pull Requests: Manually Provide Authentication Response*.

== Creating a new pull request

. Open the GitHub repository. To be able to execute remote operations, the repository must have a _remote_ with an SSH URL.
. Checkout a new branch and make changes that you want to publish.
. Run the *GitHub Pull Requests: Create Pull Request* command.
