// Module included in the following assemblies:
//
// using-nuget-artifact-repositories

[id="using-self-signed-certificates-in-nuget-projects_{context}"]
= Using self-signed certificates in NuGet projects

Internal artifact repositories often do not have a self-signed TLS certificate signed by an authority that is trusted by default. They are usually signed by an internal company authority or are self-signed. Configure your tools to accept these certificates.

.Procedure

. Obtain the certificate file of a non-standard repository and place it in the `/projects/tls/rootCA.crt` file to make it accessible from all your containers.

. Specify the location of the certificate file in the `SSL_CERT_FILE` environment variable in your devfile for the OmniSharp plug-in and for the .NET container.
+
.Example of the devfile:
[source,yaml,subs="+attributes"]
----
components:
  - id: redhat-developer/che-omnisharp-plugin/latest
    memoryLimit: 1024Mi
    type: chePlugin
    alias: omnisharp
    env:
     - value: /projects/tls/rootCA.crt
       name: SSL_CERT_FILE
 - mountSources: true
   endpoints:
     - name: 5000/tcp
       port: 5000
   memoryLimit: 512Mi
   type: dockerimage
   volumes:
     - name: dotnet
       containerPath: {prod-home}
   alias: dotnet
   image: 'quay.io/eclipse/che-dotnet-2.2:7.7.1'
   env:
     - value: /projects/tls/rootCA.crt
       name: SSL_CERT_FILE
----
