// This module is included in
//
// remote-plug-in-endpoint

[id="defining-a-launch-remote-plug-in-endpoint-using-dockerfile_{context}"]
= Defining a launch remote plug-in endpoint using Dockerfile

To start a remote plug-in endpoint, use the `+PLUGIN_REMOTE_ENDPOINT_EXECUTABLE+` environment variable in the Dockerfile.

.Procedure

* Start a remote plug-in endpoint using the `CMD` command in the Dockerfile:
+
.Dockerfile example
[source]
----
FROM fedora:30

RUN dnf update -y && dnf install -y nodejs htop && node -v

RUN mkdir /home/user

ENV HOME=/home/user

RUN mkdir /projects \
    && chmod -R g+rwX /projects \
    && chmod -R g+rwX "${HOME}"

CMD ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
----

* Start a remote plug-in endpoint using the `ENTRYPOINT` command in the Dockerfile:
+
.Dockerfile example
[source]
----
FROM fedora:30

RUN dnf update -y && dnf install -y nodejs htop && node -v

RUN mkdir /home/user

ENV HOME=/home/user

RUN mkdir /projects \
    && chmod -R g+rwX /projects \
    && chmod -R g+rwX "${HOME}"

ENTRYPOINT ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
----

== Using a wrapper script

Some images use a wrapper script to configure permissions. The script is defined it in the `ENTRYPOINT` command of the Dockerfile to configure permissions inside the container, and it script executes a main process defined in the `CMD` command of the Dockerfile.

{prod} uses such images with a wrapper script to provide permission configurations on different infrastructures with advanced security, for example on OpenShift.

* Example of a wrapper script:
+
[source,bash]
----
#!/bin/sh

set -e

export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

if ! whoami >/dev/null 2>&1; then
    echo "${USER_NAME:-user}:x:${USER_ID}:0:${USER_NAME:-user} user:${HOME}:/bin/sh" >> /etc/passwd
fi

# Grant access to projects volume in case of non root user with sudo rights
if [ "${USER_ID}" -ne 0 ] && command -v sudo >/dev/null 2>&1 && sudo -n true > /dev/null 2>&1; then
    sudo chown "${USER_ID}:${GROUP_ID}" /projects
fi

exec "$@"
----

* Example of a Dockerfile with a wrapper script:
+
.Dockerfile example
[source]
----
FROM alpine:3.10.2

ENV HOME=/home/theia

RUN mkdir /projects ${HOME} && \
    # Change permissions to let any arbitrary user
    for f in "${HOME}" "/etc/passwd" "/projects"; do \
      echo "Changing permissions on ${f}" && chgrp -R 0 ${f} && \
      chmod -R g+rwX ${f}; \
    done

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
----
+
In this example, the container launches the `/entrypoint.sh` script defined in the `ENTRYPOINT` command of the Dockerfile. The script configures the permissions and executes the command using `exec $@`. `CMD` is the argument for `ENTRYPOINT`, and the `exec $@` command calls `+${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}+`. A remote plug-in endpoint then starts in the container after permission configuration.
