[id="starting-a-workspace-with-a-devfile_{context}"]
= Starting a workspace with a devfile

This section describes how to start a Che workspace using your own existing devfile.


.Prerequisites
 
* A running instance of Eclipse Che.
* An existing devfile.


.Procedure

There are several ways to launch a Che workspace based on a prepared devfile:

.Devfile from Git

Add the devfile to a Git source repository and then create a factory from this repository.

. Put a `devfile.yaml` file in the root of your Git repository.
. Execute the factory by opening the following URL:
+
[subs="+quotes"]
----
https://__<your-che-host>__/f?url=https://github.com/__<mygroup>__/__<myrepo>__
----

.Devfile from URL

Execute a devfile by constructing the factory with the URL pointing to the raw content of the devfile, for example:

[subs="+quotes"]
----
https://__<your-che-host>__/f?url=https://pastebin.com/raw/ux6iCGaW
----

.Devfile using the `chectl` tool

Execute workspace from a devfile using the `workspace:start` parameter with the `chectl` tool as follows:

[subs="+quotes"]
----
$ chectl workspace:start --devfile=devfile.yaml
----

// .Additional resources
// 
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
// * Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
