// configuring-a-workspace-using-a-devfile

[id="creating-a-workspace-from-a-feature-branch-of-a-git-repository_{context}"]
= Creating a workspace from a feature branch of a Git repository

A Che workspace can be created by pointing to devfile that is stored in a Git source repository on a feature branch of the user’s choice. The Che instance then uses the discovered devfile to build a workspace.

.Prerequisites
* A running instance of Eclipse Che. To install an instance of Eclipse Che, see link:{site-baseurl}che-7/che-quick-starts/[Che quick-starts].
* The `devfile.yaml` file in the root folder of a Git repository on a specific branch of the user's choice available over HTTPS. See link:{site-baseurl}che-7//making-a-workspace-portable-using-a-devfile/[Making a workspace portable using a devfile] for detailed information about creating and using devfiles.

.Procedure
Execute the workspace by opening the following URL: `++https://__<CheHost>__/f?url=__<GitHubBranch>__++`

.Example
Use following URL format to open an experimental link:https://github.com/quarkusio/quarkus-quickstarts[quarkus-quickstarts] branch hosted on link:https://che.openshift.io[che.openshift.io].

[subs="+quotes"]
----
https://che.openshift.io/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che
----
