// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as an environment variable into a workspace container

The following section describes how to mount a Kubernetes secret from the user’s namespace as an environment variable, or variables, into single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].

.Procedure

. Create a new Kubernetes secret in the k8s namespace where a {prod-short} workspace will be created.

* The labels of the secret that is about to be created must match the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}. By default, it is a set of two labels: 
+
* `app.kubernetes.io/part-of: che.eclipse.org` 
* `app.kubernetes.io/component: workspace-secret` :
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
...
----
+
Annotations must indicate that the given secret is mounted as an environment variable, provides variable names, and optionally, specifies the container name where this mount will be applied. If there is no target-container annotation defined, the secret will be mounted into all user containers of the {prod-short} workspace, but this is applicable only for the {prod-short} version {prod-prev-ver}.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/target-container: maven
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----
+
This results in the environment variable named `FOO_ENV` and the value `myvalue` being provisioned into the container named `maven`.

Since the {prod-short} version 7.15, the `target-container` annotation is deprecated and `automount-workspace-secret` annotation with boolean values is introduced. Its purpose is to define the default secret mounting behavior, with the ability to be overridden in a devfile. The value sets to `true` enables the automatic mounting into all workspace containers. In contrast, the `false` value disables the mounting process until it is explicitly requested in a devfile component using the`automountWorkspaceSecrets:true` property.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: true
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----
+
This results in the environment variable named `FOO_ENV` and the value `myvalue` being provisioned into all workspace containers.
+
If the secret provides more than one data item, the environment variable name must be provided for each of the data keys as follows:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: true
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: myvalue
  otherkey: othervalue
----
+
This results in two environment variables with names `FOO_ENV`, `OTHER_ENV`, and values `myvalue` and `othervalue`, being provisioned into all workpsace containers.
+
NOTE: The maximum length of annotation names in a Kubernetes secret is 63 characters, where 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the secret.

For additional information about Kubernetes annotation items, see: xref:the-use-of-annotations-in-a-process-of-mounting-secret-into-a-workspace-container_{context}[].
