// Module included in the following assemblies:
//
// remotely-accessing-workspaces

[id="downloading-and-uploading-a-file-to-a-workspace-using-the-command-line-interface_{context}"]
= Downloading and uploading a file to a workspace using the command-line interface

This procedure describes how to use the `kubectl` tool to download or upload files remotely from or to an {prod} workspace.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].
* Remote access to the {prod-short} workspace you intend to modify. For instructions see xref:remotely-accessing-workspaces-using-the-kubernetes-command-line-tool_remotely-accessing-workspaces[].
* The `kubectl` binary from the https://kubernetes.io/docs/tasks/tools/install-kubectl/[Kubernetes website].
* Verify the installation of `kubectl` using the `kubectl version` command:

.Procedure

* To download a local file named `downloadme.txt` from a workspace container to the current home directory of the user, use the following in the {prod-short} remote shell.
+
[subs="+quotes",options="+nowrap"]
----
$ REMOTE_FILE_PATH=/projects/downloadme.txt
$ NAMESPACE=che
$ POD=workspace7b2wemdf3hx7s3ln.maven-74885cf4d5-kf2q4
$ CONTAINER=maven
$ kubectl cp ${NAMESPACE}/${POD}:${REMOTE_FILE_PATH} ~/downloadme.txt -c ${CONTAINER}
----

* To upload a local file named `uploadme.txt` to a workspace container in the `/projects` directory:

[subs="+quotes",options="+nowrap"]
----
$ LOCAL_FILE_PATH=./uploadme.txt
$ NAMESPACE=che
$ POD=workspace7b2wemdf3hx7s3ln.maven-74885cf4d5-kf2q4
$ CONTAINER=maven
$ kubectl cp ${LOCAL_FILE_PATH} ${NAMESPACE}/${POD}:/projects -c ${CONTAINER}
----

Using the preceding steps, the user can also download and upload directories.

// HERE SHOULD BE AN EXAMPLE?
