// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-a-file-into-a-workspace-container_{context}"]
= Mounting a secret as a file into a workspace container

This section describes how to mount a secret from the user's namespace as a file in single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].

.Procedure

. Create a new Kubernetes secret in the k8s namespace where a {prod-short} workspace will be created.

* The labels of the secret that is about to be created must match the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}. The default labels are:

* `app.kubernetes.io/part-of: che.eclipse.org` 
* ` app.kubernetes.io/component: workspace-secret` :
+
.Example:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
...
----
+
Annotations must indicate the given secret is mounted as a file, provide the mount path, and specify default mount behavior.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: true
    che.eclipse.org/mount-path: /home/user/.m2/
    che.eclipse.org/mount-as: file
  labels:
...
----
+
Data of the Kubernetes secret may contain several items, whose names must match the desired file name mounted into the container.
+
[source,yaml,subs="+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: true
    che.eclipse.org/mount-path: /home/user/.m2/
    che.eclipse.org/mount-as: file
data:
  settings.xml: __<base64 encoded data content here>__
----
+
This results in a file named `settings.xml` being mounted at the `/home/user/.m2/` path of all
workspace containers.

The secret-s mount path can be overridden for specific components of the workspace using devfile.
To change mount path, an additional volume should be declared in a component of the devfile,
with name matching overriden secret name, and desired mount path.
+
[source,yaml,subs="+quotes"]
----
apiVersion: 1.0.0
metadata:
  ...
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   volumes:
     - name: <secret-name>
       containerPath: /my/new/path
   ...
----
+
Please note that for such kind of overrides, components _MUST_ declare an alias to be possible to distinguish containers which belongs to them, and apply override path exclusively for those containers.

For additional information about Kubernetes annotation items, see: xref:the-use-of-annotations-in-a-process-of-mounting-secret-into-a-workspace-container_{context}[].