// Module included in the following assemblies:
//
// configuring-a-workspace-using-a-devfile

[id="overriding-devfile-values-using-factory-parameters_{context}"]
= Overriding devfile values using factory parameters

Values in the following sections of a remote devfile can be overridden using specially constructed additional factory parameters:

* `apiVersion`
* `metadata`
* `projects`
* `attributes`

.Prerequisites
* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} quick-starts].
* A publicly accessible standalone `devfile.yaml` file. See link:{site-baseurl}che-7/making-a-workspace-portable-using-a-devfile/[Making a workspace portable using a Devfile] for detailed information about creating and using devfiles.

.Procedure
. Open the workspace by navigating to the following URL: `pass:c,a,q[{prod-url}/f?url=https://__<hostURL>__/devfile.yaml&override.__<parameter.path>__=__<value>__]`

.Example of overriding the `generateName` property

Consider the following initial devfile:

[subs="+quotes"]
----
---
apiVersion: 1.0.0
metadata:
  generateName: golang-
projects:
...
----

To add or override `generateName` value, the following factory URL can be used:

[subs="+quotes"]
----
https://che.openshift.io/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&override.metadata.generateName=myprefix
----

The resulting workspace will have the following devfile model:

[subs="+quotes"]
----
---
apiVersion: 1.0.0
metadata:
  generateName: myprefix
projects:
...
----



.Example of overriding project source branch property

Consider the following initial devfile:

[subs="+quotes"]
----
---
apiVersion: 1.0.0
metadata:
  generateName: java-mysql-
projects:
  - name: web-java-spring-petclinic
    source:
      type: git
      location: "https://github.com/spring-projects/spring-petclinic.git"
...
----

To add or override source `branch` value, the following factory URL can be used:

[subs="+quotes"]
----
https://che.openshift.io/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&override.projects.web-java-spring-petclinic.source.branch=1.0.x
----

The resulting workspace will have the following devfile model:

[subs="+quotes"]
----
apiVersion: 1.0.0
metadata:
  generateName: java-mysql-
projects:
  - name: web-java-spring-petclinic
    source:
      type: git
      location: "https://github.com/spring-projects/spring-petclinic.git"
      branch: 1.0.x
...
----



.Example of overriding or creating an attribute value

Consider the following initial devfile:

[subs="+quotes"]
----
---
apiVersion: 1.0.0
metadata:
  generateName: golang-
attributes:
   persistVolumes: false
projects:
...
----

To add or override `persistVolumes` attribute value, the following factory URL can be used:

[subs="+quotes"]
----
https://che.openshift.io/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&override.attributes.persistVolumes=true
----


The resulting workspace will have the following devfile model:

[subs="+quotes"]
----
---
apiVersion: 1.0.0
metadata:
  generateName: golang-
attributes:
   persistVolumes: true
projects:
...
----



When overriding attributes, everything that follows the `attributes` keyword treat as an attribute name, so it's
possible to use dot-separated names:

[subs="+quotes"]
----
https://che.openshift.io/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&override.attributes.dot.name.format.attribute=true
----


The resulting workspace will have the following devfile model:

[subs="+quotes"]
----
---
apiVersion: 1.0.0
metadata:
  generateName: golang-
attributes:
   dot.name.format.attribute: true
projects:
...
----
