// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as an environment variable into a workspace container

The following section describes how to mount a Kubernetes secret from the user’s {orch-namespace} as an environment variable, or variables, into single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].

.Procedure

. Create a new Kubernetes secret in the k8s {orch-namespace} where a {prod-short} workspace will be created.

* The labels of the secret that is about to be created must match the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}. By default, it is a set of two labels: 
+
* `app.kubernetes.io/part-of: che.eclipse.org` 
* `app.kubernetes.io/component: workspace-secret`:
+
include::examples/{project-context}-ref_a-kubernetes-secret-as-an-variable.adoc[levelofset=+1]
