// defining-custom-commands-for-che-theia

[id="editing-a-task-and-a-launch-configuration_{context}"]
= Editing a task and a launch configuration

[Discrete]
== Procedure
To customizing the configuration file:

. Edit the `tasks.json` or a `launch.json` configuration files to customize the configuration.
. Add new configurations to the configuration file or edit the existing ones.
+
NOTE: The changes are stored in the configuration file.

. To customize the task configuration provided by plug-ins by clicking the cog icon (configure task action) from the *Terminal ->  Run Task* menu option or from the *Terminal -> Configure Tasks* menu option.
. The configuration is then copied to the `tasks.json` file and is available for editing.

////
[discrete]
== Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
