// Module included in the following assemblies:
//
// using-maven-artifact-repositories
// using-gradle-artifact-repositories

[id="using-self-signed-certificates-in-java-projects_{context}"]
= Using self-signed certificates in Java projects

Internal artifact repositories often do not have a certificate signed by an authority that is trusted by default in Java. They are usually signed by an internal company authority or are self-signed. Configure your tools to accept these certificates by adding them to the Java truststore.

.Procedure

. Obtain a server certificate file from the repository server. It is often a file named `tls.crt`.

.. Create a Java truststore file:
+
----
$ keytool -import -file tls.crt -alias nexus -keystore truststore.jks -storepass changeit

Trust this certificate? [no]:  yes
Certificate was added to keystore
Owner: CN=example.com
Issuer: CN=example.com
Serial number: 80ca0f6980c6019a
Valid from: Thu Feb 06 11:00:29 CET 2020 until: Fri Feb 05 11:00:29 CET 2021
Certificate fingerprints:
     MD5:  88:3C:EC:E1:BE:57:DD:9D:46:36:8E:DD:BF:14:04:22
     SHA1: 08:D8:79:D3:F8:6B:5C:3D:71:AA:23:CA:72:01:47:BD:9D:91:0A:AD
     SHA256: 5C:BB:66:81:44:D2:50:EE:EB:CE:D6:15:7E:63:E1:9A:71:EA:58:3F:14:01:15:4E:68:5D:71:0A:A0:31:33:29
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 4096-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: *.apps.example.com
]

Trust this certificate? [no]:  yes
Certificate was added to keystore
----
+
ifeval::["{context}" == "using-maven-artifact-repositories"]
.. Upload the truststore file to `/projects/maven/truststore.jks` to make it available for all containers.

. Add the truststore file.
+
* In the Maven container:
+
.. Add the `javax.net.ssl` system property to the `MAVEN_OPTS` environment variable:
+
[source,yaml]
----
  - mountSources: true
    alias: maven
    type: dockerimage
    ...
    env:
       -name: MAVEN_OPTS
        value: >-
          -Duser.home=/projects/maven -Djavax.net.ssl.trustStore=/projects/truststore.jks
----
+
.. Restart the workspace.
+
* In the Java plug-in container:
+
In the devfile, add the `javax.net.ssl` system property for the Java language server:
+
[source,yaml]
----
components:
  - id: redhat/java11/latest
    type: chePlugin
    preferences:
      java.jdt.ls.vmargs: >-
        -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication
        -Duser.home=/projects/maven
        -Djavax.net.ssl.trustStore=/projects/truststore.jks
[...]
----
endif::[]

ifeval::["{context}" == "using-gradle-artifact-repositories"]
.. Upload the truststore file to `/projects/gradle/truststore.jks` to make it available for all containers.

. Add the truststore file in the Gradle container.
+
.. Add the `javax.net.ssl` system property to the `JAVA_OPTS` environment variable:
+
[source,yaml]
----
  - mountSources: true
    alias: maven
    type: dockerimage
    ...
    env:
       -name: JAVA_OPTS
        value: >-
          -Duser.home=/projects/gradle -Djavax.net.ssl.trustStore=/projects/truststore.jks
----
endif::[]
