// Module included in the following assemblies:
//
// adding-{prod-id-short}-plug-in-registry-vs-code-extension-to-a-workspace

[id="adding-the-vs-code-extension-using-the-workspace-configuration_{context}"]
= Adding a VS Code extension using the workspace configuration

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].

* An existing workspace defined on this instance of {prod} link:{site-baseurl}che-7/creating-and-configuring-a-new-workspace/[Creating a workspace from user dashboard].

.Procedure

To add a VS Code extension using the workspace configuration:

. Click the *Workspaces* tab on the *Dashboard* and select the workspace in which you want to add the plug-in. The *Workspace __<workspace-name>__* window is opened showing the details of the workspace.

. Click the *devfile* tab.

. Locate the *components* section, and add a new entry with the following structure:
+
[source,yaml,subs="+quotes"]
----
 - type: chePlugin
   id:              <1>
----
<1> Link to the `meta.yaml` file in your registry, for example, `pass:c,a,q[https://my-plug-in-registry/v3/plugins/__<publisher>__/__<plug-inName>__/__<plug-inVersion>__/meta.yaml]`
+
{prod-short} automatically adds the other fields to the new component.
+
Alternatively, you can link to a `meta.yaml` file hosted on GitHub, using the dedicated reference field.
+
[source,yaml,subs="+quotes"]
----
 - type: chePlugin
   reference:              <1>
----
<1> `pass:c,a,q[https://raw.githubusercontent.com/__<username>__/__<registryRepository>__/v3/plugins/__<publisher>__/__<plug-inName>__/__<plug-inVersion>__/meta.yaml]`
+

. Restart the workspace for the changes to take effect.
