// Module included in the following assemblies:
//
// version-control

[id="accessing-a-git-repository-via-ssh_{context}"]
= Accessing a Git repository using a generated SSH key pair

== Generating an SSH key using the {prod-short} command palette

The following section describes a generation of an SSH key using the {prod-short} command palette and its further use in Git provider communication. This SSH key restricts permissions for the specific Git provider; therefore, the user has to create a unique SSH key for each Git provider in use.

.Prerequisites
* A running instance of {prod-short}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts'].

* An existing workspace defined on this instance of {prod-short} link:{site-baseurl}che-7/creating-and-configuring-a-new-che-7-workspace/[Creating a workspace from user dashboard].

* Personal link:https://help.github.com/en/articles/types-of-github-accounts[GitHub account] or other Git provider account created.

.Procedure

A common SSH key pair that works with all the Git providers is present by default. To start using it, add the public key to the Git provider.

. Generate an SSH key pair that only works with a particular Git provider:

** In the {prod-short} IDE, press kbd:[F1] to open the Command Palette, or navigate to *View -> Find Command* in the top menu.
+
The *command palette* can be also activated by pressing kbd:[Ctrl+Shift+p] (or kbd:[Cmd+Shift+p] on macOS).

** Search for *SSH: generate key pair for particular host* by entering `generate` into the search box and pressing kbd:[Enter] once filled.

** Provide the hostname for the SSH key pair such as, for example, `github.com`.
+
The SSH key pair is generated.

. Click the btn:[View] button and copy the public key from the editor and add it to the Git provider.
+
Because of this action, the user can now use another command from the command palette: *Clone git repository* by providing an SSH secured URL.

== Adding the associated public key to a repository or account on GitHub

To add the associated public key to a repository or account on GitHub:

. Navigate to link:https://github.com[github.com].
. Click the drop-down arrow next to the user icon in the upper right corner of the window.
. Click *Settings* -> *SSH and GPG keys* and then click the btn:[New SSH key] button.
. In the *Title* field, type a title for the key, and in the *Key* field, paste the public key copied from {prod-short}.
. Click the btn:[Add SSH key] button.

== Adding the associated public key to a Git repository or account on GitLab

To add the associated public key to a Git repository or account on GitLab:

. Navigate to link:https://gitlab.com[gitlab.com].
. Click the user icon in the upper right corner of the window.
. Click *Settings* -> *SSH Keys*.
. In the *Title* field, type a title for the key and in the *Key* field, paste the public key copied from {prod-short}.
. Click the btn:[Add key] button.
