// Module included in the following assemblies:
//
// using-maven-artifact-repositories

[id="defining-repositories-in-settings-xml_{context}"]
= Defining repositories in `settings.xml`

To specify your own artifact repositories at `example.server.org`, use the `settings.xml` file.
To do that, ensure, that `settings.xml` is present in all the containers that use Maven tools, in particular the Maven container and the Java plug-in container.

By default, `settings.xml` is located at the `__<home dir>__/.m2` directory. Because the user home directory is not on a persistent volume, you must re-create the file each time you restart the workspace. This is a known issue, see link:https://github.com/eclipse/che/issues/13318[the issue on GitHub].

A workaround is to make the file persist between the restarts of the workspace, create a directory `/projects/maven/.m2`, and move the `settings.xml` file in it. Then set the value of the `user.home` Java system property to `/projects/maven` in all your Maven containers.

.Procedure

. Configure your `settings.xml` file to use artifact repositories at `example.server.org`:
+
[source,xml]
----
<settings>
  <profiles>
    <profile>
      <id>my-nexus</id>
      <pluginRepositories>
        <pluginRepository>
           <id>my-nexus-snapshots</id>
           <releases>
             <enabled>false</enabled>
           </releases>
           <snapshots>
             <enabled>true</enabled>
           </snapshots>
           <url>http://example.server.org/repository/maven-snapshots/</url>
        </pluginRepository>
        <pluginRepository>
           <id>my-nexus-releases</id>
           <releases>
             <enabled>true</enabled>
           </releases>
           <snapshots>
             <enabled>false</enabled>
           </snapshots>
           <url>http://example.server.org/repository/maven-releases/</url>
        </pluginRepository>
      </pluginRepositories>
      <repositories>
        <repository>
           <id>my-nexus-snapshots</id>
           <releases>
             <enabled>false</enabled>
           </releases>
           <snapshots>
             <enabled>true</enabled>
           </snapshots>
           <url>http://example.server.org/repository/maven-snapshots/</url>
        </repository>
        <repository>
           <id>my-nexus-releases</id>
           <releases>
             <enabled>true</enabled>
           </releases>
           <snapshots>
             <enabled>false</enabled>
           </snapshots>
           <url>http://example.server.org/repository/maven-releases/</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>my-nexus</activeProfile>
  </activeProfiles>
</settings>
----

. Configure the devfile to use the `/projects/maven` value for the `user.home` Java system property.

.. For the Java plug-in container, configure the language server start arguments preference:
+
[source,yaml]
----
components:
  - id: redhat/java11/latest
    type: chePlugin
    preferences:
      java.jdt.ls.vmargs: >-
        -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication
        -Duser.home=/projects/maven
----

.. For the Maven container, configure the `MAVEN_OPTS` environment variable:
+
[source,yaml]
----
mountSources: true
    alias: maven
    type: dockerimage
    ...
    env:
       -name: MAVEN_OPTS
        value: >-
          -Duser.home=/projects/maven
----
