[id="che-theia-plug-in-metadata_{context}"]
= Che-Theia plug-in metadata

Che-Theia plug-in metadata is information about individual plug-ins for the plug-in registry.

The Che-Theia plug-in metadata is defined in a `meta.yaml` file for the specific plug-in.

The link:https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins[che-plugin-registry repository] contains .

.`meta.yml`

:===
`apiVersion`: API version (should be `v2`).
`category`: Available \: `Language`, `Other`.
`description`: Description (a phrase).
`displayName`: Display name.
`firstPublicationDate`: Date in the form `"YYYY-MM-DD"`. Example\: `"2019-12-02"`.
`icon`: URL of a svg icon.
`name`: Name (no spaces allowed).
`publisher`: Name of the publisher.
`repository`: URL of the source repository.
`title`: Title (long).
`type`: `{prod-short} Plugin`, `VS Code extension`.
`version`: Version (example\: `7.5.1`).
`spec`: Specifications (see underneath).
:===

.`spec` attributes
:===
`endpoints`: plugin endpoints
`containers`: sidecar containers for plug-in. `{prod-short} plug-in` and `VS Code extension` supports only one container.
`initContainers`: sidecar init containers for plugin
`workspaceEnv`: environment variables for the workspace.
`extensions`: For a VisualStudio Code Extension, list of U4`image`: URI of the container image
:===

.`spec.containers`. Notice: `spec.initContainers` has absolutely the same container definition.
:===
`name`: sidecar container name
`image`: container image
`memorylimit`: Kubernetes/OpenShift-spec memory limit string (e.g. "512Mi")
`env`: list of environment variables to set in sidecar
`command`: string array definition of the root process command inside container.
`args`: string array arguments for the root process command inside container
`volumes`: volumes required by plugin
`ports`: ports exposed by plugin (on the container)
`commands`: development commands available to plugin container
`mountSources`: boolean flag to bound volume with source code `/projects` to the plugin container.
:===

.`spec.containers.env` (and `spec.initContainers.env`) attributes. Notice: `workspaceEnv` has absolutely the same attributes
:===
`name`: env variable name
`value`: env variable value
:===

.`spec.containers.volumes` (and `spec.initContainers.volumes`) attributes
:===
`mountPath`: path to the volume in the container
`name`: volume name
`ephemeral`: if true volume will be ephemeral, otherwise volume will be persisted
:===

.`spec.containers.ports` (and `spec.initContainers.ports`) attributes
:===
`exposedPort`: Exposed port.
:===

.`spec.containers.commands` (and `spec.initContainers.commands`) attributes
:===
`name`: command name
`workingDir`: command working directory
`command`: string array which define development command
:===

.`spec.endpoints` attributes
:===
`name`: Name (no spaces allowed).
`public`: `true`, `false`
`targetPort`: Target port.
`attributes`: Endpoint attributes.
:===

.`spec.endpoints.attributes` attributes
:===
`protocol`: Protocol, example: `ws`
`type`: `ide`, `ide-dev`
`discoverable`: `true`, `false`
`secure`: `true`, `false`
`cookiesAuthEnabled`: `true`, `false`
:===


.Example `meta.yaml` for a Che-Theia plug-in: the {prod-short} machine-exec Service
[source,yaml]
----
apiVersion: v2
category: Other
description: {prod-short} plug-in with che-machine-exec service to provide creation terminal or tasks for {prod} workspace containers.
displayName: {prod-short} machine-exec Service
firstPublicationDate: "2019-12-02"
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
name: che-machine-exec-plugin
publisher: eclipse
repository: https://github.com/eclipse/che-machine-exec/
title: Che machine-exec Service Plugin
type: {prod-short} plug-in
version: 7.5.1
spec:
  endpoints:
   -  name: "che-machine-exec"
      public: true
      targetPort: 4444
      attributes:
        protocol: ws
        type: terminal
        discoverable: false
        secure: true
        cookiesAuthEnabled: true
  containers:
   - name: che-machine-exec
     image: "quay.io/eclipse/che-machine-exec:7.5.1"
     ports:
       - exposedPort: 4444
----

.Example `meta.yaml` for a VisualStudio Code extension: the AsciiDoc support extension
[source,yaml]
----
apiVersion: v2
category: Language
description: This extension provides a live preview, syntax highlighting and snippets for the AsciiDoc format using Asciidoctor flavor.
displayName: AsciiDoc support
firstPublicationDate: "2019-12-02"
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
name: vscode-asciidoctor
publisher: joaompinto
repository: https://github.com/asciidoctor/asciidoctor-vscode
title: AsciiDoctor Plugin.
type: VS Code extension
version: 2.7.7
spec:
  extensions:
  - https://github.com/asciidoctor/asciidoctor-vscode/releases/download/v2.7.7/asciidoctor-vscode-2.7.7.vsix
----
