// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container_{context}"]
= The use of annotations in the process of mounting a secret into a workspace container

Kubernetes annotations and labels are tools used by libraries, tools, and other clients, to attach arbitrary non-identifying metadata to Kubernetes native objects. 

Labels select objects and connect them to a collection that satisfies certain conditions, where annotations are used for non-identifying information that is not used by Kubernetes objects internally.

This section describes Kubernetes annotation values used in the process of Kubernetes secret mounting in a {prod-short} workspace.

Annotations must contain items that help identify the proper mounting configuration. These items are:

include::examples/{project-context}-ref_annotations-description.adoc[levelofset=+1]
