// Module included in the following assemblies:
//
// publishing-che-theia-plug-ins

[id="adding-a-che-theia-plug-in-into-a-workspace_{context}"]
= Adding a Che-Theia plug-in into a workspace

You can add Che-Theia plug-in into the Che-Theia IDE in three ways:

* At Theia runtime
* By configuring a workspace devfile
* By preparing shareable devfile

[id="adding-a-plug-in-at-runtime_{context}"]
== Adding a plug-in at Theia runtime

This method adds a plug-in to an already running workspace. The plug-in is not added permanently; it is removed when the workspace stops. This is a good method to test a plug-in without affecting the permanent workspace configuration.

.Procedure
* Run the `Deploy Plugin by Id` command, and specify the ID of the plug-in to add to the workspace. A plug-in ID can be:
+
A local directory with plug-ins:: {prod-short} loads all the plug-in binaries (`.theia` files) in the specified directory. 
+
.Adding the local directory `/home/theia/plugins/`
====
----
local-dir:///home/theia/plugins/
----
====
+
VS Code extension link:: To obtain the link, go to the VS Code marketplace, find the needed extension, copy its ID, and append the ID to the `vscode:extension/` prefix.
+
.VS Code extension link for the link:https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml[XML language server] plug-in 
====
----
vscode:extension/redhat.vscode-xml
----
====
+
Link to plug-in binaries (`.theia` files):: Can be both HTTP and HTTPS.
+
.Link to plug-in binaries
====
----
https://domain.net/path/plugin.theia
----
====

.Verification steps
* Open the *Plugins panel* (*View* > *Plugins* in the main menu) and search for the plug-in in the list.

[id="adding-a-plug-in-by-configuring-a-workspace_{context}"]
== Adding a plug-in by configuring a workspace devfile

This method is useful when you need to add plug-ins from a non-default registry.

.Procedure

. Navigate to the *Workspaces* tab in the dashboard.
. Select the workspace to which you want to add the plug-in.
. Switch to the *Devfile* tab, and find the `components` section.
. To add plug-ins, append your plugin component to the `components` section. A record has the following format:
+
[subs="+quotes,macros,attributes"]
----
components:
  - type: chePlugin
    reference: >-
      __<registry-base-uri>__/v3/plugins/__<plugin-publisher>__/__<plugin-name>__/__<plugin-version>__
----
+
.`chePlugin` reference URLs pointing to a plug-in `meta.yaml`
====
----
https://custom-registry/v3/plugins/custom-plugin-name/0.0.1/
https://raw.githubusercontent.com/username/che-custom-plugins/master/v3/plugins/custom-plugin-name/0.0.1/meta.yaml
----
====

[id="adding-a-plug-in-by-shareable-devfile_{context}"]
== Adding a plug-in by preparing shareable devfile

This approach brings an advantage of other users being able to contribute to the development, provided they have write access to the repository with the plug-in.

.Procedure

. Create a devfile with the plug-in development environment and share it with reviewers to provide them with the same environment. Reviewers then must build and run the plug-in to test it, using a script or a set of instructions on how to include the build in the plug-in repository.

. Share with reviewers factory link with a URL to a repository with devfile or a direct URL to content of the devfile.
+
.Factory URL pointing to a repository containing a devfile
====
{prod-url}/f?url=https://github.com/eclipse/che
====
+
.Factory URL pointing to a devfile
====
{prod-url}/f?url=https://raw.githubusercontent.com/eclipse/che/master/devfile.yaml
====

. The reviewer starts a workspace by opening a link where they are able to starts a hosted plug-in instance and specify the path to the plug-in project inside the workspace. For instructions on how to start a hosted instance of Che-Theia for plug-in testing, see xref:testing-che-theia-plug-ins.adoc[].

// .Additional resources
// 
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
// * Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
