---
title: Eclipse Che4z
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/eclipse-che4z/
folder: che-7/extensions
summary:
---

:page-liquid:
:parent-context-of-eclipse-che4z: {context}

[id="eclipse-che4z_{context}"]
= Eclipse Che4z

Eclipse Che4z is an all-in-one mainframe extension stack for {prod}, which provides a modern experience for mainframe software developers working with z/OS applications.

Powered by the open-source projects https://www.zowe.org/[Zowe] and link:{site-baseurl}che-7[{prod}], Che4z offers an easy and streamlined on-boarding process to get new developers using the tools they need. Using container technology and stacks, {prod} brings the necessary technology to the task at hand.

Developers can now find the code they need to work on in Explorer for Endevor, Git and Zowe Explorer, edit code assisted by COBOL or HLASM Language Support, and test the resulting code with the Debugger, all in one Mainframe development package.

Eclipse Che4z is an open source project. Many of the components of the Che4z stack are also available on the VS Code marketplace as part of the https://marketplace.visualstudio.com/items?itemName=broadcomMFD.code4z-extension-pack[Code4z] package.

== Use cases

The Eclipse Che4z extension allows:

* Viewing and editing CA Endevor SCM data in the {prod} environment.
* Editing COBOL and High Level Assembler language files with syntax awareness and autocomplete features.
* Browsing mainframe data sets in the {prod} environment.
* Debugging COBOL programs running on a CICS region.
* Performing tasks on mainframe applications using a command-line interface.

== Getting Started

For instructions on how to install the Eclipse Che4z stack, see the https://github.com/eclipse/che-che4z[Che4z Git repository]

== Components

The Eclipse Che4z extension includes the following components:

=== COBOL Language Support

COBOL Language Support standardizes the communication between language tooling and your code editor using the Language Server Protocol (LSP)

The Che4z package includes a bitlang https://marketplace.visualstudio.com/items?itemName=bitlang.cobol[COBOL
extension] which provides an enhanced experience while working with a COBOL Language Support, giving the ability to leverage syntax highlighting.

==== Features:

* Edit COBOL code with assistance including:
** Syntax highlighting
** Real time syntax validation
** Content assist

https://github.com/eclipse/che-che4z-lsp-for-cobol/issues[image:https://img.shields.io/github/issues-raw/eclipse/che-che4z-lsp-for-cobol?style=flat-square[GitHub issues]]
https://join.slack.com/t/che4z/shared_invite/enQtNzk0MzA4NDMzOTIwLWIzMjEwMjJlOGMxNmMyNzQ1NWZlMzkxNmQ3M2VkYWNjMmE0MGQ0MjIyZmY3MTdhZThkZDg3NGNhY2FmZTEwNzQ[image:https://img.shields.io/badge/chat-on%20Slack-blue?style=flat-square[slack]]

* For documentation and release information, see the https://github.com/eclipse/che-che4z-lsp-for-cobol[COBOL Language Support Git repository]
* How can we improve COBOL Language Support? https://github.com/eclipse/che-che4z-lsp-for-cobol/issues[Let us know]

==== Blogs:
* https://medium.com/modern-mainframe/beginners-guide-cobol-made-easy-introduction-ecf2f611ac76[Beginner’s Guide: COBOL Made Easy]

=== Zowe Explorer

Zowe Explorer is a VS Code extension powered by Zowe CLI that streamlines interaction with mainframe data sets, USS files, and jobs

==== Features:
* Access z/OS Datasets, z/OS Unix file system and submit JCL
* View and download job output
* Issue TSO commands

https://github.com/zowe/vscode-extension-for-zowe/issues[image:https://img.shields.io/github/issues-raw/zowe/vscode-extension-for-zowe?style=flat-square[GitHub issues]]
https://openmainframeproject.slack.com/[image:https://img.shields.io/badge/chat-on%20Slack-blue?style=flat-square[slack]]

* For documentation, see https://docs.zowe.org/stable/user-guide/cli-vscodeplugin.html#zowe-explorer-extension-for-vscode[Zowe Docs]
* How can we improve Zowe Explorer? https://github.com/zowe/vscode-extension-for-zowe/issues[Let us know on our Git repository]

==== Blogs:
* https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe[Beginner’s Guide: How to access mainframe via Zowe in 10 easy steps] *
* https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe[Zowe blog]

=== HLASM Language Support

HLASM Language Support is an extension that supports the High Level Assembler language. It provides code completion, highlighting and navigation features, shows mistakes in the source, and lets you trace how the conditional assembly is evaluated with a modern debugging experience.

==== Features:
* Highlights statements with different colors for labels, instructions, operands, remarks and variables.
* Autocomplete is enabled for the instruction field. While typing, a list of instructions starting with the typed characters displays.
* The extension adds the 'go to definition' and 'find all references' functionalities.
* The macro tracer functionality allows you to track the process of assembling HLASM code.

https://github.com/eclipse/che-che4z-lsp-for-hlasm/issues[image:https://img.shields.io/github/issues-raw/zowe/vscode-extension-for-zowe?style=flat-square[GitHub issues]]
https://openmainframeproject.slack.com/[image:https://img.shields.io/badge/chat-on%20Slack-blue?style=flat-square[slack]]

* For documentation and release information, see the https://github.com/eclipse/che-che4z-lsp-for-hlasm[HLASM Language Support Git repository]
* How can we improve HLASM Language Support? https://github.com/eclipse/che-che4z-lsp-for-hlasm/issues[Let us know]

=== Explorer for Endevor

Explorer for Endevor gives you the ability to Browse and Retrieve https://www.broadcom.com/products/mainframe/devops-app-development/app/endevor-software-change-manager[CA Endevor® SCM] elements using a user-friendly, intuitive interface.

This extension offers best developer experience in synergy with https://youtu.be/sjnZuQpUVM4[Bridge for Git], a solution which enables you to concurrently work in Git and mainframe.

==== Features
* Retrieve, browse and search CA Endevor® elements.

https://github.com/eclipse/che-che4z-explorer-for-endevor/issues[image:https://img.shields.io/github/issues-raw/eclipse/che-che4z-explorer-for-endevor?style=flat-square[GitHub issues]]
https://join.slack.com/t/che4z/shared_invite/enQtNzk0MzA4NDMzOTIwLWIzMjEwMjJlOGMxNmMyNzQ1NWZlMzkxNmQ3M2VkYWNjMmE0MGQ0MjIyZmY3MTdhZThkZDg3NGNhY2FmZTEwNzQ[image:https://img.shields.io/badge/chat-on%20Slack-blue?style=flat-square[slack]]

* For documentation and release information, see the https://github.com/eclipse/che-che4z-explorer-for-endevor/[Explorer for Endevor Git repository]
* How can we improve Explorer for Endevor? https://github.com/eclipse/che-che4z-explorer-for-endevor/issues[Let us know]

=== Debugger for Mainframe

Debugger for Mainframe provides the debugging interface to https://www.broadcom.com/products/mainframe/devops-app-development/testing-quality/intertest-cics[CA InterTest™ for CICS]. This extension provides a modern debug experience for COBOL applications running in a CICS region.

==== Features:
* Debug COBOL code for applications running in a CICS region.

https://github.com/BroadcomMFD/debugger-for-mainframe/issues[image:https://img.shields.io/github/issues-raw/broadcomMFD/debugger-for-mainframe?style=flat-square[GitHub issues]]
https://join.slack.com/t/che4z/shared_invite/enQtNzk0MzA4NDMzOTIwLWIzMjEwMjJlOGMxNmMyNzQ1NWZlMzkxNmQ3M2VkYWNjMmE0MGQ0MjIyZmY3MTdhZThkZDg3NGNhY2FmZTEwNzQ[image:https://img.shields.io/badge/chat-on%20Slack-blue?style=flat-square[slack]]

* For documentation and release information, see the https://github.com/BroadcomMFD/debugger-for-mainframe[Debugger for Mainframe Git repository]
* How can we improve Debugger for Mainframe? https://github.com/BroadcomMFD/debugger-for-mainframe/issues[Let us know]

=== Zowe CLI plug-ins

Zowe Command Line-Interface (Zowe CLI) is a command-line interface that lets application developers interact with the mainframe in a familiar format. The following Zowe CLI plug-ins are included in the Che4z basic stack:

* https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ca-endevor-scm.html[CA Endevor SCM plug-in for Zowe CLI]
* https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ca-file-master-plus.html[CA File Master Plus plug-in for Zowe CLI]
* https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-db2-database.html[IBM Db2 plug-in for Zowe CLI]
* https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside/3-0/ca-brightside-command-line-interface-cli/available-cli-plug-ins/ca-brightside-plug-in-for-ibm-cics.html[IBM CICS plug-in for Zowe CLI]

== Sample Workflows

=== COBOL Language Support using CA Endevor Bridge for Git and Explorer for Endevor

* Use VS Code’s built-in Git interface to clone source code from CA Endevor using Endevor’s Bridge for Git.
* Edit COBOL code using COBOL Language Support, taking advantage of all the coding assistance provided by the extension.
* Use VS Code’s built-in Git interface to push, pull and merge changes.
* Search and browse additional code elements in the entire map of Endevor using the Explorer for Endevor extension. The COBOL Language Support extension provides syntax awareness for COBOL elements.
* Download code elements, including their dependencies, into the current workspace using the Explorer for Endevor extension, and synchronize them with the Git project if code modifications are needed.

=== Debugger for Mainframe

* Provide InterTest server location, CICS region, credentials and program/transaction name (either by file or input form).
* Obtain the listing and set breakpoints.
* Trigger the CICS transaction and start a debug session.
* Display and change variable values.
* Stop at designated breakpoints, continue from a designated breakpoint and step through the listing.
* Close the debug session.

=== Zowe Explorer and Zowe CLI

* Access mainframe files and execute jobs, either from an interactive graphical interface or in the terminal with CLI. Whether you want to view a PDS, allocate a dataset, change a JCL, submit a mainframe compile, or download and upload files, both interfaces provide these capabilities.

:context: {parent-context-of-eclipse-che4z}
