---
title: Using OpenShift Connector in Eclipse Che
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/using-openshift-connector-in-eclipse-che/
folder: che-7/extensions
summary:
---

// openshift-connector-overview

ifdef::context[:parent-context-of-using-openshift-connector-in-eclipse-che: {context}]

:context: using-openshift-connector-in-eclipse-che

[id="using-openshift-connector-in-eclipse-che_{context}"]
= Using OpenShift Connector in Eclipse Che

OpenShift Connector makes it possible to create, build, and debug applications in the {prod-short} IDE and then deploy the applications directly to the running OpenShift cluster.

OpenShift Connector acts as a GUI for the OpenShift Do (ODO) utility, which aggregates OpenShift CLI (OC) commands into compact units. As such, OpenShift Connector helps new developers who do not have OpenShift background with creating applications and running them on the cloud. Instead of using several `oc` commands, the user creates a new component or service by selecting a preconfigured template, such as a Project, an Application, or a Service; then and deploys it as an OpenShift Component to their cluste

include::con_features-of-openshift-connector.adoc[leveloffset=+1]
include::proc_installing-openshift-connector-in-eclipse-che.adoc[leveloffset=+1]
include::proc_authenticating-with-openshift-connector-in-eclipse-che.adoc[leveloffset=+1]
include::proc_creating-components-with-openshift-connector-in-eclipse-che.adoc[leveloffset=+1]
include::proc_connecting-source-code-from-guthub-to-a-openshift-component-using-openshift-connector.adoc[leveloffset=+1]

////
.Additional resources
* A bulleted list of links to other material closely related to the contents of the assembly, including xref links to other assemblies in your collection.
* For more details on writing assemblies, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
