---
title: Installing Eclipse Che4z
keywords: 
tags: [Che4z]
sidebar: che_7_docs
permalink: che-7/che4z-installing/
folder: che-7/extensions
summary: 
---

[id="installing-che4z"]
= Installing Eclipse Che4z

:context: installing-che4z

To download and install the Eclipse Che4z plugins, follow the instructions on link:https://projects.eclipse.org/projects/ecd.che.che4z/downloads[this page]..Prerequisites
- Minimum of 2 CPUs and 4GB RAM
- Docker
- Internet access


.Procedure

. Install Eclipse Che by running the following command. Replace `__<DATA_FOLDER>__` with the location of user data on the host machine:
+
[subs="+quotes"]
----
$ docker run -it --rm -e CHE_MULTIUSER=true -e CHE_HOST=`hostname -f` -e \
  CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock -v \
  /var/run/docker.sock:/var/run/docker.sock -v /__<DATA_FOLDER>__:/data eclipse/che:7.0.0-beta-4.0 start
----
+
For more information on configuring Eclipse Che with Docker, see https://www.eclipse.org/che/docs/che-6/docker-multi-user.html[Installation on Docker].

. Log in to Che using the default administrator account (username = `admin`, password = `admin`).

. (Optional) Configure the Keycloak security server by following the instructions https://www.eclipse.org/che/docs/che-6/user-management.html#che-and-keycloak[Managing users].

. Download and unzip the installer.

. Run `start_installer.sh` (on Linux) or `start_installer.cmd` (on Windows).

. When prompted, enter the Che URL and administrator account credentials.



== Creating a workspace


. Log in to Che. Use your credentials or the default administrator account (username = `admin`, password = `admin`).

. Select *Workspaces -> Add Workspace*.

. In *Select Stack*, select *view all*, then choose the *Broadcom Mainframe* stack.

. Create and open the workspace.

You created a workspace and can now use the Eclipse Che4z extensions.