----
title: Eclipse Che4z Release Information
keywords: 
tags: [Che4z]
sidebar: che_7_docs
permalink: che-7/che4z-release-information/
folder: che-7/extensions
summary:
----

[id="che4z-release-information"]
= Che4z Release Information

:context: che4z-release-information

Eclipse Che4z provides components and extensions for {prod} to facilitate mainframe application development.

Eclipse Che4z currently includes the following products:

* COBOL Language Support
* Explorer for Endevor
* Zowe CLI and Zowe Explorer (Including Plugins)

=== Release notes - COBOL Language Support

==== Version 0.8.3

* Java automatic check fixed to recognize all supported JRE/JDK java implementations.

==== Version 0.81

Version 0.8 was released on 1 October 2019.

* Extension name updated.
* Repository corrected including improved description.
* Unexpected error message resolved. Re-directed to internal log.

==== Version 0.8

Version 0.8 was released on 1 August 2019 and includes the following features:

* *Autocomplete for COBOL* +
Provides suggestions for COBOL keywords while you type.
* *COBOL syntax check* +
Checks for mistakes and errors in COBOL code.
* *Third-party COBOL syntax highlighting support* +
Enables syntax highlighting for COBOL code as long as you have an appropriate third-party syntax highlighting extension installed.

=== Release notes - Explorer for Endevor

==== Version 0.8.0
Version 0.8 was released on 1 August 2019 and includes the following features:

* Explore Endevor Data Maps
- Explorer for Endevor lets you browse through Endevor data without any prior knowledge of the file paths being necessary

* Create Filters Based on Your Searches
- Explorer for Endevor lets you create customer filters based on the searches you perform in the Map View

* Customisable Filters
- Explorer for Endevor lets you create customisable filters for ease of browsing data sets.

==== Version 0.9.0
Version 0.9 was released on 19 September 2019 and includes the following features:

* Advanced Create Filter function
- Experienced users can create custom filters without having to use Map View

* Improved Host Creation process
- Streamlined process to create new Host connections

* UX Enhancements

=== Zowe Explorer and Zowe CLI
- link:https://docs.zowe.org/stable/[Zowe CLI and Plugin Documentation]

- link:https://docs.zowe.org/v1-2-x/getting-started/summaryofchanges.html#version-1-2-0-may-2019[Zowe CLI Release Notes]

=== Third-party software agreements

Eclipse Che4z uses the Eclipse Public License v2.0 (link:https://www.eclipse.org/legal/epl-v20.html[full text]) and the Apache License v2.0 (link:https://www.apache.org/licenses/LICENSE-2.0.txt[full text]) for both z/OS Resource Explorer and COBOL Language Support.