---
title: Eclipse Che4z Product Accessibility Features
keywords: 
tags: [Che4z]
sidebar: che_7_docs
permalink: che-7/che4z-product-accessibility-features/
folder: che-7/extensions
summary: 
---

[id="che4z-product-accessibility-features"]
= Product Accessibility Features

:context: che4z-product-accessibility-features

CA Technologies is committed to addressing user accessibility in the development of its products and documentation to help all customers, regardless of ability, to accomplish vital business tasks.

Depending on your emulator, you can use the following accessibility features with Eclipse Che4z:

== Product Enhancements

NOTE: The following information applies to Windows-based and Macintosh-based applications. Java applications run on many host operating systems, some of which already have assistive technologies available to them. For these existing assistive technologies to provide access to programs written in JPL, they need a bridge between themselves in their native environments and the Java Accessibility support that is available from within the Java virtual machine (or Java VM). This bridge has one end in the Java VM and the other on the native platform, so it will be slightly different for each platform it bridges to. Sun is currently developing both the JPL and the Win32 sides of this bridge. 

Eclipse Che4z offers accessibility enhancements in the following areas:

* Display
* Sound
* Keyboard
* Mouse

== Display

To increase visibility on your computer display, you can adjust the following options:

* *Font style, color, and size of items* +
Defines font color, size, and other visual combinations.
* *Screen resolution* +
Defines the pixel count to enlarge objects on the screen.
* *Cursor width and blink rate* +
Defines the cursor width or blink rate, which makes the cursor easier to find or minimize its blinking.
* *Icon size* +
Defines the size of icons. You can make icons larger for visibility or smaller for increased screen space.
* *High contrast schemes* +
Defines color combinations. You can select colors that are easier to see.

== Sound

Use sound as a visual alternative or to make computer sounds easier to hear or distinguish by adjusting the following options:

* *Volume* +
Sets the computer sound up or down.
* *Text-to-Speech* +
Sets the computer's hear command options and text read aloud.
* *Warnings* +
Defines visual warnings.
* *Notices* +
Defines the aural or visual cues when accessibility features are turned on or off.
* *Schemes* +
Associates computer sounds with specific system events.
* *Captions* +
Displays captions for speech and sounds.

== Keyboard

You can make the following keyboard adjustments:

* *Repeat Rate* +
Defines how quickly a character repeats when a key is struck.
* *Tones* +
Defines tones when pressing certain keys.
* *Sticky Keys* +
Defines the modifier key, such as Shift, Ctrl, Alt, or the Windows Logo key, for shortcut key combinations. Sticky keys remain active until another key is pressed.

== Mouse 

You can use the following options to make your mouse faster and easier to use:

* *Click Speed* +
Defines how fast to click the mouse button to make a selection.
* *Click Lock* +
Sets the mouse to highlight or drag without holding down the mouse button.
* *Reverse Action* +
Sets the reverse function controlled by the left and right mouse keys.
* *Blink Rate* +
Defines how fast the cursor blinks or if it blinks at all.
* *Pointer Options* +
Lets you complete the following actions: +
** Hide the pointer while typing.
** Show the location of the pointer.
** Set the speed that the pointer moves on the screen.
** Choose the pointer's size and color for increased visibility.
** Move the pointer to a default location in a dialog box.

== Keyboard Shortcuts

The following table lists the keyboard shortcuts that Eclipse Che4z supports:

[cols=2*,options=header]
|===
|Keyboard
|Description

|Ctrl+X
|Cut

|Ctrl+C
|Copy

|Ctrl+K
|Find Next

|Ctrl+F
|Find and Replace

|Ctrl+V
|Paste

|Ctrl+S
|Save

|Ctrl+Shift+S
|Save All

|Ctrl+D
|Delete Line

|Ctrl+Right
|Next Word

|Ctrl+Down
|Scroll Line Down

|End
|Line End
|===