---
title: Eclipse Che4z Release Information
keywords: 
tags: [Che4z]
sidebar: che_7_docs
permalink: che-7/che4z-release-information/
folder: che-7/extensions
summary: 
---

[id="che4z-release-information"]
= Che4z release information

:context: che4z-release-information

Eclipse Che4z provides components and extensions for {prod} to facilitate mainframe application development.

Eclipse Che4z currently includes one product, COBOL Language Support.

== Release notes - COBOL Language Support

=== Version 0.81

Version 0.8 was released on 1 October 2019.

* Extension name updated.
* Repository corrected including improved description.
* Unexpected error message resolved. Re-directed to internal log.

=== Version 0.8

Version 0.8 was released on 1 August 2019 and includes the following features:

* *Autocomplete for COBOL* +
Provides suggestions for COBOL keywords while you type.
* *COBOL syntax check* +
Checks for mistakes and errors in COBOL code.
* *Third-party COBOL syntax highlighting support* +
Enables syntax highlighting for COBOL code as long as you have an appropriate third-party syntax highlighting extension installed.

== Third-party software agreements

Eclipse Che4z uses the Eclipse Public License v2.0 (link:https://www.eclipse.org/legal/epl-v20.html[full text]) and the Apache License v2.0 (link:https://www.apache.org/licenses/LICENSE-2.0.txt[full text]) for both z/OS Resource Explorer and COBOL Language Support.
