---
title: Installing Eclipse Che4z
keywords:
tags:
sidebar: che_7_docs
permalink: che-7/che4z-installing/
folder: che-7/extensions
summary:
---

[id="installing-eclipse-che4z"]
= Installing Eclipse Che4z

:context: installing-eclipse-che4z

This page describes how to install the Eclipse Che4z basic stack. The Eclipse Che4z basic stack is included with {prod} version 7.6 and above. Follow these instructions if you are using an older version. Eclipse Che4z is compatible with {prod} version 7.3 on Kubernetes.

video::O2kIFFDACE0[youtube]

.Procedure

. Log in to {prod}.

. In a web browser, load the following URL: +
`{prod-url}/f?url=https://github.com/eclipse/che-che4z/raw/1.0.0/mainframe-basic-stack.yaml`
+
* `{prod-url}` specifies the {prod-short} Server URL, for example: `++https://++my-che-server.com`.

* `/f?url=` links the {prod-short} Server URL to the Eclipse Che4z basic stack URL.

* `++https://++github.com/eclipse/che-che4z/raw/1.0.0/mainframe-basic-stack.yaml` is the Eclipse Che4z basic stack URL.

. Press *Enter* and wait for the workspace to initialize.

A workspace is created with Eclipse Che4z extensions available.

To install the Eclipse Che4z Premium stack, replace the basic stack URL with the Premium Stack URL specified in the CA Brightside PDF installation guide available from https://casupport.broadcom.com/download-center/download-center.html[Broadcom Support]. See the *Getting Started* section in the http://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-mainframe-software/devops/ca-brightside-enterprise/2-0/getting-started.html[CA Brightside documentation].
