---
title: Features of OpenShift Connector
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/features-of-openshift-connector/
folder: che-7/extensions
summary:
---
// using-openshift-connector-in-eclipse-che

[id="features-of-openshift-connector_{context}"]

= Features of OpenShift Connector

The OpenShift Connector GUI provides the following benefits to its users:

.Cluster management
* Logging in to clusters using tokens and username and password combinations.
* Switching contexts between different `.kube/config` entries directly from the extension view.
* Viewing and managing OpenShift resources as build and deployment configurations from the *Explorer* view.

.Development
* Connecting to a local or hosted OpenShift cluster directly from {prod-short}.
* Quickly updating the cluster with your changes.
* Creating Components, Services, and Routes on the connected cluster.
* Adding storage directly to a component from the extension itself.

.Deployment
* Deploying to OpenShift clusters with a single click directly from {prod-short}.
* Navigating to the multiple Routes, created to access the deployed application.
* Deploying multiple interlinked Components and Services directly on the cluster.
* Pushing and watching component changes from the {prod-short} IDE.
* Streaming logs directly on the integrated terminal view of {prod-short}.

.Monitoring
* Working with OpenShift resources directly from Che-Theia.
* Starting and resuming build and deployment configurations.
* Viewing and following logs for deployments, pods, and containers.

////
.Additional resources
* A bulleted list of links to other material closely related to the contents of the concept module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
