---
title: Explorer for Endevor
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/Explorer4Endevor/
folder: che-7/extensions
summary:
---

:parent-context-of-Explorer4Endevor: {context}

[id="Explorer4Endevor_{context}"]
= Explorer for Endevor

:context: Explorer4Endevor

Explorer for Endevor lets you view and edit CA Endevor® SCM data using a user-friendly, intuitive modern interface.

Use Explorer for Endevor to investigate the contents of Endevor data repositories, and use these searches to create customized filters. You can then save these filters, and use wildcards to create filters to identify other elements with similar characteristics.

Once you identify the relevant Endevor data, you can retrieve specific elements, either individually or in multiples, without having to navigate the mainframe-based CA Endevor® SCM interface.

* link:{site-baseurl}che-7/E4E-AdministratingE4E[Administrating Explorer for Endevor]
* link:{site-baseurl}che-7/E4E-InstallE4EinVSC[Install Explorer for Endevor]
* link:{site-baseurl}che-7/E4E-UsingE4E4VSC[Using Explorer for Endevor]
* link:{site-baseurl}che-7/E4E-Messages[Explorer for Endevor Messages]
