---
title: Creating Components with OpenShift Connector in Eclipse Che
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/creating-components-with-openshift-connector-in-eclipse-che/
folder: che-7/extensions
summary:
---
// using-openshift-connector-in-eclipse-che

[id="creating-components-with-openshift-connector-in-eclipse-che_{context}"]
= Creating Components with OpenShift Connector in {prod-short}

In the context of OpenShift, Components and Services are basic structures that need to be stored in Application, which is a part of the OpenShift project that organizes deployables into virtual folders for better readability.

This chapter describes how to create OpenShift Components in the {prod-shor} using the OpenShift Connector plug-in and push them to an OpenShift cluster.

.Prerequisites

* A running instance of {prod-short}. To install an instance of {prod-short}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} quick-starts].
* The user is logged in to an OpenShift cluster using the Openshift Connector plug-in.

.Procedure

. In the OpenShift Connector panel, right-click the row with the red OpenShift icon and select *New Project*.
. Enter a name for your project.
. Right-click the created project and select *New Component*.

. When prompted, enter the name for a new OpenShift Application in which the component can be stored.
+
The following options of source for your component are displayed:
+
.. *Git Repository*
+
This prompts you to fill in a Git repository URL and select the intended revision of the runtime.
.. *Binary File*
+
This prompts you to select a file from the file explorer.
.. *Workspace Directory*
+
This prompts you to select a folder from the file explorer.

. Enter the name for the component.
. Select the component type.
+
// this is the runtime - which is a middleware used for running a source code
. Select the component type version.
+
//runtime version
. The component is created. Right-click the component, select *New URL*, and enter a name of your choice.
+
//creates a route with the given name in openshift
. The component is ready to be pushed to the OpenShift cluster. To do so, right-click the component and select *Push*.
+
The component is now deployed to the cluster. Right-click for selecting additional actions, such as debugging and opening in a browser (requires port `8080` to be exposed).

////
.Additional resources
* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
