---
title: Installing OpenShift Connector in Eclipse Che
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/installing-openshift-connector-in-eclipse-che/
folder: che-7/extensions
summary:
---
// using-openshift-connector-in-eclipse-che

:page-liquid:

[id="installing-openshift-connector-in-{prod-id-short}_{context}"]
= Installing OpenShift Connector in {prod-short}

OpenShift Connector is a plug-in designed to create basic OpenShift Components, using {prod-short} as the editor, and to deploy the Component to an OpenShift cluster.
To visually verify that the plug-in is available in your instance, see whether the OpenShift icon is displayed in the {prod-short} left menu.

To install and enable OpenShift Connector in a {prod-short} instance, use instructions in this section.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} quick-starts].

.Procedure

Install OpenShift Connector in {prod-short} by adding it as an extension in the {prod-short} *Plugins* panel.

. Open the *{prod-short} Plugins* panel by pressing kbd:[Ctrl+Shift+J] or by navigating to *View -> Plugins*.
. Search for *vscode-openshift-connector*, and click the btn:[Install] button.
. Restart the workspace for the changes to take effect.
. The dedicated OpenShift Application Explorer icon is added to the left panel.
