---
title: Creating Components with OpenShift Connector in Eclipse Che
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/creating-components-with-openshift-connector-in-eclipse-che/
folder: che-7/extensions
summary:
---
// using-openshift-connector-in-eclipse-che

[id="creating-components-with-openshift-connector-in-eclipse-che_{context}"]

= Creating Components with OpenShift Connector in Eclipse Che

Components and Services, in the context of OpenShift, are basic structures that need to be stored in Application, which is a part of the OpenShift Project that organizes deployables into virtual folders for better readability.

.Prerequisites

* A running instance of {prod-short}. To install an instance of {prod-short}, see link:{site-baseurl}che-7/che-quick-starts/[{prod-short} quick-starts].
* User is logged in to the OpenShift cluster using the Openshift Connector plug-in.

.Procedure

. In the Openshift Connector panel, right-click the row with the red OpenShift icon, and select *New Project*.
. Enter a name for your project.
. Right-click the created project and select *New Component*.
+
You will be prompted to create a new application, in which the component can be stored.

. Enter the name for the application.
+
The following options of source for your component are displayed:
+
.. *Git Repository*
+
This prompts you to fill in a git repository URL and select the intended revision of the runtime.
.. *Binary File*
+
This prompts you to select a file from the file explorer.
.. *Workspace Directory*
+
This prompts you to select a folder from the file explorer.

. Enter the name for your component.
. Select the component type.
+
// this is the runtime - which is a middleware used for running a source code
. Select the component type version.
+
//runtime version
. The component is created. Right-click the component, select *New URL*, and enter a name of your choice.
+
//creates a route with the given name in openshift
. The component is ready to be pushed into the OpenShift cluster. To do so, right-click the component and select *Push*.
+
The component is now deployed to the cluster. You may right-click for selecting additional actions like debug, open in a browser. However, this requires port 8080 to be exposed.

////
.Additional resources
* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
