// using-openshift-connector-in-eclipse-che

[id="authenticating-with-openshift-connector-in-eclipse-che_{context}"]

= Authenticating with OpenShift Connector in Eclipse Che

OpenShift Connector offers the following methods for logging in to the OpenShift Cluster:

* Using Log in to the cluster button
* Using Command palette

Your credentials, while using a localhost (like instances of CRC or minshift), are stored in the workspace `~/.kube/config` file, and may be used for automatic authentication in subsequent logins. In the context of {prod-short}, the `~/.kube/config` is stored as a part of the plug-in sidecar container.

== Using the login button
. In the left panel, select the *OpenShift Application Explorer* icon.
+
The Openshift Connector panel is displayed.
. Click the btn:[Log in to cluster] button.
. If a “You are already logged in a cluster.” message appears, click *Yes*.
+
A selection whether to log in using `Credentials` or `Token` is displayed at the top of the screen.
. Select the method to log in to the cluster and follow the login instructions.
+
NOTE: If you select the token method for authenticating with OpenShift cluster, you can find the required token information in the top right corner of the main {ocp} screen, under *_<User name>_ -> Copy Login Command*.

== Using the Command Palette
. In the left panel, select the *OpenShift Application Explorer* icon.
+
The Openshift Connector panel is displayed.
. Press F1 to open the Command Palette, or navigate to *View -> Find Command* top in the menu.
. Search for `Openshift: Log in to cluster` and press Enter.
. If a “You are already logged in a cluster.” message appears, click *Yes*.
+
A selection whether to log in using `Credentials` or `Token` is displayed at the top of the screen.
. Select the method to log in to the cluster and follow the login instructions.
+
NOTE: If you select the token method for authenticating with OpenShift cluster, you can find the required token information in the top right corner of the main {ocp} screen, under *_<User name>_ -> Copy Login Command*.

////
.Additional resources
* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
