:_content-type: PROCEDURE
:description: Using a Git-provider access token
:keywords: Git, credentials, access-token
:navtitle: Access private repositories with a personal access token
:page-aliases: end-user-guide:using-a-git-provider-access-token.adoc, using-a-Git-credentials-store.adoc, using-git-credentials.adoc, 

[id="using-a-git-provider-access-token"]
= Access private repositories with a personal access token


include::partial$snip_persona-developer.adoc[]

OAuth for GitHub, GitLab, Bitbucket, or Microsoft Azure Repos needs to be xref:administration-guide:configuring-oauth-for-git-providers.adoc[configured by the administrator] of your organization's {prod-short} instance. If your administrator could not configure it for {prod-short} users, the workaround is for you to use a personal access token. You can configure personal access tokens on the *User Preferences* page of your {prod-short} dashboard: `pass:c,a,q[{prod-url}]/dashboard/#/user-preferences?tab=personal-access-tokens`, or apply it manually as a {kubernetes} Secret in the namespace.

Mounting your access token as a Secret enables the {prod-short} Server to access the remote repository that is cloned during workspace creation, including access to the repository's `/.che` and `/.vscode` folders.

Apply the Secret in your user {orch-namespace} of the {orch-name} cluster of your organization's {prod-short} instance.

After applying the Secret, you can create workspaces with clones of private Git repositories that are hosted on GitHub, GitLab, Bitbucket Server, or Microsoft Azure Repos.

You can create and apply multiple access-token Secrets per Git provider. You must apply each of those Secrets in your user {orch-namespace}.

.Prerequisites

* You have logged in to the cluster.
+
[TIP]
====
On OpenShift, you can use the `oc` command-line tool to log in to the cluster:

`$ oc login pass:c,a,q[{prod-url}] --username=__<my_user>__`

====

.Procedure

. Generate your access token on your Git provider's website.
+
[IMPORTANT]
====
Personal access tokens are sensitive information. Treat them like passwords. If you are having trouble with authentication, verify the token locally before applying it as a Secret:

[source,bash]
----
$ git clone https://<PAT>@github.com/username/repo.git
----

Replace `<PAT>` with your personal access token, and `username/repo` with the appropriate repository path. If cloning succeeds, the token is valid and has the necessary permissions.

For GitHub Enterprise Cloud, verify that the token is link:https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on[authorized for use within your organization with SAML single sign-on].
====

. Go to `pass:c,a,q[{prod-url}]/api/user/id` in the web browser to get your {prod-short} user ID.

. Prepare a new {orch-name} Secret.
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: personal-access-token-__<git_provider>__
  labels:
    app.kubernetes.io/component: scm-personal-access-token
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/che-userid: __<{prod-id-short}_user_id>__
    che.eclipse.org/scm-personal-access-token-name: __<git_provider_name>__
    che.eclipse.org/scm-url: __<git_provider_endpoint>__
    che.eclipse.org/scm-organization: __<git_provider_organization>__
type: Opaque
stringData:
  token: __<your_personal_access_token>__
----
+
where:
+
che.eclipse.org/che-userid:: Your {prod-short} user ID.
+
che.eclipse.org/scm-personal-access-token-name:: The Git provider name (`github`, `gitlab`, `bitbucket-server`, or `azure-devops`).
+
che.eclipse.org/scm-url:: The Git provider URL endpoint, for example `https://github.com` or `https://gitlab.com`.
+
che.eclipse.org/scm-organization:: Required only for Azure DevOps: your Git provider user organization, or collection if Azure DevOps Server is used.
+
token:: Your personal access token.
+
Example for GitHub:
+
[source,yaml,subs="+quotes,+attributes"]
----
kind: Secret
apiVersion: v1
metadata:
  name: personal-access-token-github
  labels:
    app.kubernetes.io/component: scm-personal-access-token
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/che-userid: 1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p
    che.eclipse.org/scm-personal-access-token-name: github
    che.eclipse.org/scm-url: https://github.com
type: Opaque
stringData:
  token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
----

. Visit `pass:c,a,q[{prod-url}]/api/kubernetes/namespace` to get your {prod-short} user namespace as `name`.

. Switch to your {prod-short} user namespace in the cluster.
+
[TIP]
====
On OpenShift:

* The `oc` command-line tool can return the namespace you are currently on in the cluster, which you can use to check your current namespace:
+
`$ oc project`

* You can switch to your {prod-short} user namespace on a command line if needed:
+
`$ oc project __<your_user_namespace>__`

====

. Apply the Secret.
+
[TIP]
====
On OpenShift, you can use the `oc` command-line tool:
[source,subs="+quotes,+attributes"]
----
$ oc apply -f - <<EOF
__<Secret_prepared_in_step_5>__
EOF
----
====

[IMPORTANT]
====
If you are using Azure DevOps Server, you must also modify the xref:end-user-guide:mounting-git-configuration.adoc[workspace's
gitconfig] with the following section:

[source,http]
----
    extraheader = "Authorization: Basic <base64-encoded(:personal-access-token)>"
----
To generate the key-value pair, use the following command:

[source,commandline]
----
echo -n "extraheader = \"Authorization: Basic "$(printf ":%s" <personal access token> | base64)\"
----
see link:https://learn.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops&tabs=Linux#personal-access-tokens[the documentation page] for more information.

The `extraheader` configuration is needed for remote git operations to Azure Devops Server, for example `git clone`. This authorization method has a higher priority over the git credentials store, and as a result, the remote operations to other Git providers will fail.
====

.Verification

. xref:starting-a-workspace-from-a-git-repository-url.adoc[Start a new workspace by using the URL of a remote Git repository] that the Git provider hosts.
. Make some changes and push to the remote Git repository from the workspace.

.Additional resources

* xref:configure:deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc[Deploying Che with support for Git repositories with self-signed certificates]
* link:https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on[Authorizing a personal access token for use with SAML single sign-on]






