:_content-type: PROCEDURE

[id="adding-or-removing-extensions-on-linux_{context}"]
= Add or remove extensions from the Linux command line

[role="_abstract"]
Build and publish a custom plugin registry from the Linux command line to create a tailored Open VSX registry with the specific extensions your organization needs.

.Prerequisites

* You have {docker-cli} installed.
* You have Node.js version 18.20.3 or higher installed.
* You have created a link:https://access.redhat.com/RegistryAuthentication[Red Hat Registry Service Account] and have the username and token available.
* You have a container image based on the latest tag or SHA to include the latest security fixes.

.Procedure

. Clone the plugin registry repository:
+
[source,terminal,subs="+attributes"]
----
$ git clone {plugin-registry-repo-url}.git
----

. Change to the plugin registry directory:
+
[source,terminal]
----
$ cd che-plugin-registry/
----

. Log in to the Red Hat registry:
+
[source,terminal,subs="+attributes"]
----
$ {docker-cli} login registry.redhat.io
----

. Identify the publisher and extension name for each extension you want to add:
.. Find the extension on the link:https://open-vsx.org/[Open VSX registry website].
.. Copy the URL of the extension's listing page.
.. Extract the __<publisher>__ and __<name>__ from the URL:
+
[source,text,subs="+quotes"]
----
https://open-vsx.org/extension/__<publisher>__/__<name>__
----
+
[TIP]
====
If the extension is only available from link:https://marketplace.visualstudio.com/VSCode[Microsoft Visual Studio Marketplace] and not link:https://open-vsx.org[Open VSX], ask the extension publisher to publish it on link:https://open-vsx.org[open-vsx.org]. See the link:https://github.com/eclipse-openvsx/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension[publishing instructions] and the link:https://github.com/marketplace/actions/publish-vs-code-extension[GitHub action].

If the publisher is unavailable or unwilling, and no Open VSX equivalent exists, consider link:https://github.com/open-vsx/publish-extensions/issues[reporting an issue] to the Open VSX team.
====

. Open the link:{plugin-registry-repo-url}/blob/main/openvsx-sync.json[`openvsx-sync.json`] file.

. Add or remove extensions using the following JSON syntax:
+
[source,json,subs="+quotes"]
----
    {
        "id": "__<publisher>__.__<name>__",
        "version": "__<extension_version>__"
    }
----
+
[TIP]
====
If you have a closed-source or internal-only extension, you can add it directly from a `.vsix` file. Use a URL accessible to your custom plugin registry container:

[source,json,subs="+quotes"]
----
    {
        "id": "__<publisher>__.__<name>__",
        "download": "__<url_to_download_vsix_file>__",
        "version": "__<extension_version>__"
    }
----

Read the link:https://aka.ms/vsmarketplace-ToU[Terms of Use] for the link:https://marketplace.visualstudio.com/VSCode[Microsoft Visual Studio Marketplace] before using its resources.
====

. Build the plugin registry container image:
+
[source,bash,subs="+attributes,+quotes"]
----
$ ./build.sh -o __<username>__ -r quay.io -t custom
----
+
[NOTE]
====
Verify that the `CHE_CODE_VERSION` in the link:{plugin-registry-repo-url}/blob/main/build-config.json[`build-config.json`] file matches the version of the editor currently used with {prod-short}. Update it if necessary.
====

. Push the image to a container registry such as link:https://quay.io/[quay.io]:
+
[source,bash,subs="+attributes,+quotes"]
----
$ {docker-cli} push quay.io/__<username>__/plugin_registry:custom
----

. Edit the `CheCluster` custom resource in your organization's cluster to point to the image and save the changes:
+
[source,yaml,subs="+quotes"]
----
spec:
  components:
    pluginRegistry:
      deployment:
        containers:
          - image: quay.io/__<username>__/plugin_registry:custom
      openVSXURL: ''
----

.Verification

. Check that the `plugin-registry` pod has restarted and is running.
. Restart your workspace.
. Open the *Extensions* view in the IDE and verify that your added extensions are available.

[role="_additional-resources"]
.Additional resources

* link:{plugin-registry-repo-url}[Plugin registry repository]
* xref:proc_deploy-open-vsx-from-source.adoc[]
