---
title: "Editor and Code Assistance"
keywords: workspace, runtime, project, editor, code-completion, code completion, code assistance, intellisense
tags: [workspace, runtime]
sidebar: user_sidebar
permalink: editor-code-assistance.html
folder: user-guide
---


[id="orion-editor"]
== Orion Editor

Eclipse Che wraps Orion editor to integrate it with language servers, Git, debugger and other servvices that run on server and client side. Use of custom (user provided editors is possible). See: link:editor.html[Editor].

[id="syntax-highlighting"]
== Syntax Highlighting

Syntax highlighting is provided by Orion editor out of the box. For some file types Che overrides styles, for others uses them as is. If the opened file does not have syntax coloring, it means that that Orion does not know anything about such file type. You can provide own syntax coloring for custom file types or override existing styles. See: link:editor.html[Editor].

[id="code-assistant"]
== Code-Assistant

At this moment, code assistance (including error marking, quick fixes, refactoring, go to definition, javadoc etc) for *Java* is provided by Java plugin that wraps JDT. This will change though, once https://github.com/eclipse/che/issues/6157[JDT.LS] implementation is finalized.

Code assistance for **JavaScript** is provided by Orion editor itself.

Code assistance for other languages is provided by [Language Servers][language-servers]. Eclipse Che supports code assistance for Java, C#, PHP, Python, TypeScript, YAML and JSON. There are plans to add a language servers for Golang.

[id="editor-settings"]
== Editor Settings

Editor settings can be configured in the Che IDE under `Profile > Preferences > IDE > Editor`. Preferences can change key bindings, tabbing rules, language tools, whitespace and ruler preferences. Note that in some cases the editor will need to be refreshed for the new settings to be applied.

You can edit your files as you would in any other editor (you can even switch to vi or emacs keybindings in `Profile > Preferences`).

Additionally it’s possible to configure the error/warning preferences for the Java compiler at `Profile > Preferences > Java Compiler > Errors/Warnings`.

*Multi-Pane Editors*

You can split the editor into multiple panes. This makes it easier to edit across different files or parts of the same file at the same time. `Split Vertical` and `Split Horizontal` can be selected through the drop down menu accessible by right clicking on a tab in the editor.

*Multi-Pane Consoles*

You can split the consoles into multiple panes. This allows easier navigation when trying to see different console outputs at the same time. `Split Vertical` and `Split Horizontal` can be selected through the drop down menu accessible by at the top right of the console area. To put new console in a newly created pane select the open area below the tabs area.

*Fullscreen Mode for Panes*

Editor tabs and console outputs can be displayed fullscreen.

*Fullscreen for Editors*

Editor tabs can easily get displayed in fullscreen mode by double-clicking on one of the editor’s tabs. All other panes will be collapsed when you do this. To exit the fullscreen mode, double-click again on the tab.

*Fullscreen for Consoles*

Console outputs and processes tabs can be displayed in fullscreen mode by double-clicking on one of the terminal’s (or output’s) tab to maximize it. All other panes will be collapsed when you do this. To exit the fullscreen mode, double-click again on the tab.

You can also use the quick pane option displayed in the top right corner of the pane to move to fullscreen mode.

*Preview HTML Files*

You can preview an HTML file by right-clicking it in the project explorer and selecting preview from the popup menu.

*Preview Images*

You can easily preview image by simple double-clicking it in the project explorer. The image will be opened in the editor area. Also you can open the image in the dedicated browser tab by right-clicking the image in the project explorer and selecting `Preview` from the popup menu.
