---
#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Configuration file for htmltest
# See: https://github.com/wjdp/htmltest

DirectoryPath: build/site # Not build/site to avoid false positives on 404.html
# IgnoreInternalEmptyHash: true # Legit empty hash present in every page
OutputDir: .cache/htmltest
CacheExpires: "12h" # Default is 2 weeks.
ExternalTimeout: 60 # (seconds) default is 15.
IgnoreURLs:
  - https://cse.google.com/cse.js
  - https://marketplace.visualstudio.com
  - https://github.com/eclipse-che/che-docs/edit/master/
  - https://www.eclipse.org/che/docs/che-7/
  - https://projectlombok.org/
  - https://developers.redhat.com/products/openshift_dev_spaces/overview
  - https://developers.redhat.com/products/openshift-dev-spaces/overview
  - https://access.redhat.com/documentation/en-us/red_hat_openshift_devspaces/3.0/html/release_notes_and_known_issues/about-devspaces_crw  
  - https://docs.github.com/en/*
  - https://velero.io/*
