---
#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

# Configuration file for htmltest
# See: https://github.com/wjdp/htmltest

DirectoryPath: build/site # Not build/site to avoid false positives on 404.html
# IgnoreInternalEmptyHash: true # Legit empty hash present in every page
OutputDir: .cache/htmltest
CacheExpires: "12h" # Default is 2 weeks.
ExternalTimeout: 60 # (seconds) default is 15.
IgnoreExternalBrokenLinks: true
IgnoreURLs:
  - https://cse.google.com/cse.js
  - https://marketplace.visualstudio.com
  - https://github.com/eclipse-che/che-docs/edit/main/
  - https://projectlombok.org/
  - https://developers.redhat.com/*
  - https://docs.github.com/en/*
  - https://velero.io/*
  - https://che.eclipseprojects.io/
  - https://app.vsaex.visualstudio.com/app/register/
  - https://mattermost.eclipse.org/eclipse/channels/eclipse-che
  - https://git.example.com:8443
  - https://stackoverflow.com/questions/tagged/eclipse-che
  - https://example.com/
  - https://gdpr.eu/
  - https://prometheus.io/*
  - https://www.gnu.org/*
  - https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpsslCAInfo
  - https://minikube.sigs.k8s.io/docs/

