---
site:
  title: Eclipse Che Documentation
  # The url property is mandatory to generate the 404 and sitemap files.
  url: https://www.eclipse.org/che/docs
  start_page: che-7:overview:introduction-to-eclipse-che.adoc
  keys:
    google_analytics: "UA-37306001-2"
  robots: allow
content:
  sources:
    - url: ./
      branches: 7.31.x
      edit_url: "https://github.com/eclipse/che-docs/edit/7.31.x/{path}"
output:
  destinations:
    - provider: fs
      clean: true
      path: build/site
    - provider: archive
      path: build/site.zip
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
urls:
  html_extension_style: indexify
  redirect_facility: static
runtime:
  cache_dir: ./.cache/antora
