= Getting started with first-draft pull requests

1. In the local clone of your fork of the che-docs repo, checkout a new feature branch and in the /che-docs/ directory create a new file in which you will document your new feature for the docs:
docs-draft-<your_issue_number>-<your_github_username>.adoc
2. In this file, write everything you think readers of the docs should know about your new feature: it can be a sentence about the use case, conceptual info, procedure(s) with steps, links to additional resources, or reference materials, as applicable to your new feature.
3. Focus on the quality and completeness of the technical content you are providing, which is your main contribution.
4. Limit your headings to one or two levels (in exceptional cases at most three levels).
5. Write it in plain text, adding basic AsciiDoc formatting syntax.
6. In this one file, you can also add pieces of text destined for different sections of one or more guides in the docs, just each time paste a link to the published docs page under which you think your draft belongs. Under the link, write your text for that published docs page.
7. If there is any info that you want us to add, remove, replace, or edit, within existing sections of the docs - paste the link to the published docs page and tell us command-style on a separate line what to do (e.g., ADD; DELETE; REPLACE; WITH). If something is unclear to us, we'll respond with a comment in your Draft PR.
8. When your draft is ready, go to GitHub and create a new Draft PR from your fork to the che-docs repo. This will be a handover of your draft to us, and we'll get in touch with you for more information in the comments on your Draft PR page in the *Files changed* tab when we are ready to start working on it ourselves. We'll then create our own PR, link your Draft PR, and, when done, we'll close your Draft PR.

If anything is unclear, get in touch!
Your Technical Writing Team
PS: Below are some tips and examples.



https://www.eclipse.org/che/docs/che-7/<specific-user-guide>/<existing-che-docs-page-where-you-want-us-to-add-your-new-text-below>/
Example: https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration/


= Your first-level heading

In this draft, we only need your text formatted using a very basic subset of AsciiDoc syntax that we provide as examples below.
(For additional AsciiDoc syntax, should you ever need it, see the left and right menus in link:https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[].)

== Your second-level heading

New text (concept info, procedure, reference info) for your feature.

== Doing procedure this-and-this

You need to do this-and-this in such and such context.
Doing this-and-this is necessary in such and such situation.

.Prerequisites
* Prerequisite one.
* Prerequisite two.

.Procedure
. Do step one.
. Do step two.
. Do step three.


// Single-line comment.

////
Comment block.
////


The following is a YAML block:
[source,yaml,subs="+quotes,+attributes"]
----
YAML line <1>
YAML line <2>
----
<1> Does something.
<2> Is something.


The following is a shell block:
[source,shell,subs="+quotes,+attributes"]
----
command abc \ <1>
command abc continued \ <2>
command abc ended
----
<1> Is something.
<2> Does something.


.Optional title of an example
====
Example text. Try to avoid examples if you can use user-replaced values as explained below.
====


(Excerpt from link:https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values)
A user-replaced value, also known as a replaceable or variable value, is a value that the user must replace with a value that is relevant for their situation. User-replaced values are often found in places such as code blocks, file paths, and commands.
Use descriptive names for user-replaced values and follow this general format: <value_name>.
Ensure that user-replaced values have the following characteristics:
* Surrounded by angle brackets (< >)
* Separated by underscores (_) for multi-word values
* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme
* Italicized
* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value
Command-line example:
  $ oc describe node __<node_name>__
File path example:
  Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.


. ordered list item 1
. ordered list item 1
. ordered list item 2
.. ordered list item 2.a
.. ordered list item 2.b


* unordered list item
* unordered list item
* unordered list item
** unordered list item
** unordered list item


`monospace` (inline code)
*bold* for ...
_italic_ for ...
*_italic-bold_*
`_italic-monospace_`
`*bold-monospace*`
`*_italic-bold-monospace_*`


NOTE: Text.
TIP: Text.
IMPORTANT: Text.
WARNING: Text.


btn:[OK]
kbd:[Ctrl+Shift+N]


.Additional resources
* For Red Hat style guide, see link:https://redhat-documentation.github.io/supplementary-style-guide/[]
