:toc: 

pass:[<!-- vale RedHat.Headings = NO -->]

= Publishing Eclipse Che documentation

pass:[<!-- vale RedHat.Headings = YES -->]

== Understanding the publication workflow

The publication workflow is the following:

_Source Repository_ => _Publication repository_ => _Publication website_

Publication website (link:https://www.eclipse.org/che/[]):: 
Eclipse Che website containing:

Eclipse Che website::: 
link:https://www.eclipse.org/che/[]
Landing page and PHP website.

Eclipse Che documentation:::
link:https://www.eclipse.org/che/docs/[]
Documentation in HTML format.

Publication repository (`link:https://git.eclipse.org/c/www.eclipse.org/che.git/[]):: 
Git repository containing:

`docs` directory:::
Eclipse Che documentation content in HTML format.

`_` directory::: 
Eclipse Che documentation UI requirements.

other directories:::
Eclipse Che website.

A process managed by the Eclipse Infrastructure team pushes the content of the _Publication repository_ to the _Publication website_.

Source repository (`https://github.com/eclipse/che-docs/`):: 
Git repository containing the sources for the Eclipse Che documentation in the form of a Modular Documentation compliant Antora component.

`publication` branch:::
Git branch containing the docs content to publish to the _publication repository_.

`publication-builder` branch:::
Git branch building, validation and publishing the documentation website to the `publication` branch.

Antora playbook (`xref:publication-builder-antora-playbook.yml[]`)::::
link:https://docs.antora.org/antora/2.3/playbook/[Antora playbook] defining how to assemble the documentation.

Antora UI (`xref:supplemental-ui[]`)::::
Additions to the default Antora UI, defining the menu and style refinements.

GitHub workflow (`xref:.github/workflows/publication-builder.yml[]`)::::
GitHub workflow orchestrating the publication.

`main` and release branches (`7.42.x` pattern):::
These branches contain the documentation content in the form of a Modular Documentation compliant Antora component.

`antora.yml`::::
link:https://docs.antora.org/antora/2.3/component-version-descriptor/[Antora component version descriptor]


`.github/workflows/call-publication-builder.yaml`::::
GitHub workflow calling the _Publication builder_ workflow. See: link:https://github.com/eclipse/che-docs/actions/workflows/call-publication-builder.yaml[Call publication builder runs].


== Checking Eclipse Che documentation publication continuous integration status

.Procedure

. Check the most recent link:https://github.com/eclipse/che-docs/actions/workflows/call-publication-builder.yaml[Call publication builder GitHub workflow] run completed successfully.

. Check the most recent link:https://ci.eclipse.org/che/job/che-docs-pipeline/job/publication/[Eclipse Jenkins pipeline] run completed successfully.


.Next steps

When at least one job run failed:

. Escalate to link:https://coreos.slack.com/archives/CK3V11UER[#forum-devtools-docs].

. If necessary, report an issue on link:https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues[Eclipse Foundation bug tracker].

== Building for publication on Eclipse Che hosted by Red Hat

.Procedure

. link:https://workspaces.openshift.com#https://github.com/eclipse/che-docs/tree/publication-builder[Open a workspace containing the _Source repository_ `publication-builder` branch]

. Run the _Publication builder_ task to assemble the documentation in HTML format.

. Validate the build artifacts in the `build/site` directory.


== Building for publication on a local environment

.Procedure

. Checkout the _Source repository_ `publication-builder` branch to get the publication instructions.

. Run the `xref:tools/runnerpublication-builder.sh[]` script to assemble the documentation in HTML format:
+
----
$ ./tools/runnerpublication-builder.sh
----

. Validate the build artifacts in the `build/site` directory.
