:toc:

= Releasing Eclipse Che Documentation


== Release workflow automation

The xref:.github/workflows/release.yml[`release.yml`] workflow implements and performs release procedures for the Eclipse Che Documentation, using the xref:make-release.sh[`make-release.sh`] script.

The publication is decoupled. See link:https://github.com/eclipse/che-docs/tree/publication-builder[Publishing Eclipse Che documentation].


== Releasing a major or minor version


.Prerequisites

* Define the Eclipse Che version to release: `__<major>__.__<minor>__.0`.

.Procedure

. Create the `__<major>__.__<minor>__.x` branch from the `main` branch.

. Edit the `antora.yml` file in the `__<major>__.__<minor>__.x` branch to define:
+
[source,yaml,subs="+attributes,+quotes"]
----
prerelease: false
version: "_<major>_._<minor>_.x"
display_version: "_<major>_._<minor>_.x"
asciidoc:
  attributes:
    prod-ver-patch: "_<major>_._<minor>_.0"
    prod-ver: "_<major>_._<minor>_"
    prod-ver-major: "_<major>_"
----


// . Replace the stable branch version (`"__<major>__.__<minor>__.x"`) in the link:https://github.com/eclipse/che-docs/blob/publication-builder/publication-builder-antora-playbook.yml[`publication-builder-antora-playbook.yml` file in the `publication-builder` branch]. Keep the other branches (`main`, `master`, `che-7`, `che-7-redirections`). See: link:https://github.com/eclipse/che-docs/tree/publication-builder#changing-the-versions-to-publish[Changing the versions to publish]
// +
// [source,yaml,subs="+attributes,+quotes"]
// ----
// # [...]
// content:
//   sources:
//     - url: https://github.com/eclipse/che-docs
//       branches:
//         - "main"
//         - "__<major>__.__<minor>__.x"
// # [...]
// ----

== Releasing a patch version

.Prerequisites

* Define the stable `__<major>__.__<minor>__.__<patch>__` Eclipse Che version to release.

.Procedure

. Define `asciidoc.attributes.prod-ver-patch` in the `antora.yml` file in the `__<major>__.__<minor>__.x` branch:
+
[source,yaml,subs="+attributes,+quotes"]
----
asciidoc:
  attributes:
    prod-ver-patch: "__<major>__.__<minor>__.__<patch>__"
----
