:toc:

= Releasing Eclipse Che documentation

== Release workflow automation

The xref:.github/workflows/release.yml[`release.yml`] workflow implements and performs release procedures for the Eclipse Che Documentation, using the xref:make-release.sh[`make-release.sh`] script.

The publication is decoupled. See link:https://github.com/eclipse-che/che-docs/tree/publication-builder[Publishing Eclipse Che documentation].


== Releasing a major or minor version

.Prerequisites

* The new release is published on https://github.com/eclipse/che/releases and https://mattermost.eclipse.org/eclipse/channels/eclipse-che-releases.

.Procedure

. From the `main` branch, create a release branch with a branch name in the format `__<major>__.__<minor>__.x`, and then checkout the created release branch.
+
NOTE: The name of the release branch differs from the number of the release in the trailing `x`.

. In the `__<major>__.__<minor>__.x` branch, update the following product-version-related values in `antora.yml`:
+
[source,yaml,subs="+attributes,+quotes"]
----
prerelease: false
version: __<major>__.__<minor>__.x # name of release branch
asciidoc:
  attributes:
    prod-ver-patch: "_<major>_._<minor>_.0"
    prod-ver: "_<major>_._<minor>_"
    prod-ver-major: "_<major>_"
----

. Look up the latest DWO release in https://github.com/devfile/devworkspace-operator/tags, double-check it with the SMEs, and update the DWO version patch value in `antora.yml`:
+
[source,yaml,subs="+attributes,+quotes"]
----
asciidoc:
  attributes:
    ...
    # for the project
    ...
    devworkspace-operator-version-patch: "x.y.z"
    ...
----

. Commit and push the changes to the release branch.

. Edit the link:https://github.com/eclipse-che/che-docs/blob/publication-builder/publication-builder-antora-playbook.yml[`publication-builder-antora-playbook.yml` file in the `publication-builder` branch]. Change the latest branch to "__<major>__.__<minor>__.x". Keep the other branches (`7.43.x` and `main`).
+
[source,yaml,subs="+attributes,+quotes"]
----
# [...]
content:
  sources:
    - url: https://github.com/eclipse-che/che-docs
      branches:
        - 7.57.x
        - che-7-redirections
        - main
# [...]
----

== Releasing a patch version

.Prerequisites

* Define the stable `__<major>__.__<minor>__.__<patch>__` Eclipse Che version to release.

.Procedure

. Define `asciidoc.attributes.prod-ver-patch` in the `antora.yml` file in the `__<major>__.__<minor>__.x` branch:
+
[source,yaml,subs="+attributes,+quotes"]
----
asciidoc:
  attributes:
    prod-ver-patch: "__<major>__.__<minor>__.__<patch>__"
----
