:toc:

= Releasing Eclipse Che documentation

== Release workflow automation

The xref:.github/workflows/release.yml[`release.yml`] workflow implements and performs release procedures for the Eclipse Che Documentation, using the xref:make-release.sh[`make-release.sh`] script.

The publication is decoupled. See link:https://github.com/eclipse-che/che-docs/tree/publication-builder[Publishing Eclipse Che documentation].


== Releasing a major or minor version

.Prerequisites

* The new release is published on https://github.com/eclipse/che/releases.

.Procedure

. From the `main` branch, open and merge a PR to `main` to update the Che version values in link:https://github.com/eclipse-che/che-docs/blob/main/antora.yml[`antora.yml`]:
+
TIP: You can proceed to step 2 without waiting for this PR to be merged.

.. Update the `prod-...` version values to the just released Che version:
+
[source,yaml,subs="+attributes,+quotes"]
----
    prod-ver-major: "7" # update this only if there is a major version change
    prod-ver-patch: "7.62.0"
    prod-ver: "7.62"
----

.. Add a commit message and PR title like `chore: update product version values in antora.yml to Che 7.62` and explain the changes:
+
----
## What does this pull request change?
Bump up the Che version to the latest release for the main branch.

## Specify the version of the product this pull request applies to
Merge to `main`
----

. From the `main` branch, create a release branch with a branch name in the format `__<major>__.__<minor>__.x`.
+
NOTE: The name of the release branch differs from the number of the release in the trailing `x`.

. In the `__<major>__.__<minor>__.x` branch, update the following product-version-related values in `antora.yml`:
+
[source,yaml,subs="+attributes,+quotes"]
----
prerelease: false
version: __<major>__.__<minor>__.x # name of release branch
asciidoc:
  attributes:
    prod-ver-patch: "_<major>_._<minor>_.0"
    prod-ver: "_<major>_._<minor>_"
    prod-ver-major: "_<major>_"
----

. In the `publication-builder` branch, update the first `branches` value to the latest release branch (from step 2) in link:https://github.com/eclipse-che/che-docs/blob/publication-builder/publication-builder-antora-playbook.yml[`publication-builder-antora-playbook.yml`].
+
[source,yaml,subs="+attributes,+quotes"]
----
content:
  sources:
    - url: https://github.com/eclipse-che/che-docs
      branches:
        - 7.62.x
        - che-7-redirections
        - main
----
+
WARNING: Do not remove the other branches like `main`!

== Releasing a patch version

.Prerequisites

* Define the stable `__<major>__.__<minor>__.__<patch>__` Eclipse Che version to release.

.Procedure

. Define `asciidoc.attributes.prod-ver-patch` in `antora.yml` in the `__<major>__.__<minor>__.x` branch:
+
[source,yaml,subs="+attributes,+quotes"]
----
asciidoc:
  attributes:
    prod-ver-patch: "__<major>__.__<minor>__.__<patch>__"
----
