// Module included in the following assemblies:
//
// publishing-che-theia-plug-ins

[id="che-theia-plug-in-registries_{context}"]
= Che-Theia plug-in registries

A plug-in registry is a simple service that hosts metadata about the enabled plug-ins.

To retrieve a full list of plug-ins hosted in a registry, navigate to the `<registry-base-uri>/v3/plugins/index.json` file.

Each plug-in item in the list is represented by a JSON definition.

.Sample plug-in definition
[source,json]
----
  {
    "description": "This extension provides a live preview, syntax highlighting and snippets for the AsciiDoc format using Asciidoctor flavor.",
    "displayName": "AsciiDoc support",
    "id": "joaompinto/vscode-asciidoctor/latest",
    "links": {
      "self": "/v3/plugins/joaompinto/vscode-asciidoctor/latest/" 
    },
    "name": "vscode-asciidoctor",
    "publisher": "joaompinto",
    "type": "VS Code extension",
    "version": "latest"
  }
----

This definition contains a `links` section that points to the complete plug-in description (`meta.yaml`).

.Sample plug-in `meta.yaml` file
[source,yaml]
----
publisher: joaompinto
apiVersion: v2
version: latest
type: VS Code extension
name: vscode-asciidoctor
displayName: AsciiDoc support
title: AsciiDoctor Plugin.
description: This extension provides a live preview, syntax highlighting, and snippets
  for the AsciiDoc format using Asciidoctor flavor.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
category: Language
repository: https://github.com/asciidoctor/asciidoctor-vscode
firstPublicationDate: '2019-09-09'
spec:
  extensions:
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/joaompinto/vsextensions/asciidoctor-vscode/2.7.6/vspackage
latestUpdateDate: "2019-12-09"
----

For more details about the `meta.yaml` structure, see xref:che-theia-plug-in-metadata_what-is-a-che-theia-plug-in[].


[id="official-plug-in-registry_{context}"]
== Official plug-in registry

The official {prod-short} plug-in registry is at link:https://che-plugin-registry.openshift.io[che-plugin-registry.openshift.io]. By default, the {prod-short} dashboard shows editors and plug-ins from this registry.

The source is located at link:https://github.com/eclipse/che-plugin-registry[github.com/eclipse/che-plugin-registry].


[id="custom-plug-in-registries_{context}"]
== Custom plug-in registries

For more information about setting up a custom registry, see the description of the link:https://github.com/eclipse/che-plugin-registry[official registry repository].

To use plug-ins from a custom registry, follow one of the following methods:

* Specify a link to the plug-in in the configuration of a workspace. See xref:adding-a-plug-in-by-configuring-a-workspace_publishing-che-theia-plug-ins[Adding a plug-in into a workspace using the workspace configuration].

* Replace the default official registry with a custom one in your {prod-short} instance. To do so, set the `PLUGIN_REGISTRY_IMAGE` environment variable in your {prod-short} configuration. Note that plug-ins from the official registry are not available from the dashboard interface. To include them, add references to your registry from the official registry.

.Additional resources

* xref:che-theia-plug-in-metadata_what-is-a-che-theia-plug-in[]
