[id="che-theia-plug-in-registries_{context}"]
= Che-Theia plug-in registries

A plug-in registry is a simple service that hosts information (metadata) about the plug-ins.

To retrieve a full list of plug-ins hosted in a registry, navigate to the following address: `<registry-base-uri>/v3/plugins/index.json`.

Each plug-in item in the list is represented by a JSON definition:

.Sample plug-in definition
[source,json]
----
{
  "publisher": "joaompinto",
  "apiVersion": "v2",
  "version": "2.7.7",
  "type": "VS Code extension",
  "name": "vscode-asciidoctor",
  "displayName": "AsciiDoc support",
  "title": "AsciiDoctor Plugin",
  "description": "Provides a live preview, syntax highlighting and snippets for the AsciiDoc format",
  "icon": "https://www.eclipse.org/che/images/logo-eclipseche.svg",
  "category": "Language",
  "repository": "https://github.com/asciidoctor/asciidoctor-vscode",
  "firstPublicationDate": "2019-12-02",
  "spec": {
    "extensions": [
      "https://github.com/asciidoctor/asciidoctor-vscode/releases/download/v2.7.7/asciidoctor-vscode-2.7.7.vsix"
    ]
  }
}
----
<1> Points to a more complete plug-in description (`meta.yaml`).

.Sample plug-in `meta.yaml` file
[source,yaml]
----
publisher: joaompinto
apiVersion: v2
version: 2.7.7
type: VS Code extension
name: vscode-asciidoctor
displayName: AsciiDoc support
title: AsciiDoctor Plugin
description: Provides a live preview, syntax highlighting and snippets for the AsciiDoc format
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
category: Language
repository: https://github.com/asciidoctor/asciidoctor-vscode
firstPublicationDate: "2019-12-02"
spec:
  extensions:
  - https://github.com/asciidoctor/asciidoctor-vscode/releases/download/v2.7.7/asciidoctor-vscode-2.7.7.vsix
----

For more details about the `meta.yaml` structure, see xref:che-theia-plug-in-metadata_what-is-a-che-theia-plug-in[].


[id="official-plug-in-registry_{context}"]
== Official plug-in registry

The official {prod-short} plug-in registry is at link:https://che-plugin-registry.openshift.io[che-plugin-registry.openshift.io]. By default, the {prod-short} dashboard shows editors and plug-ins from this registry.

The source is located at link: https://github.com/eclipse/che-plugin-registry[github.com/eclipse/che-plugin-registry].


[id="custom-plug-in-registries_{context}"]
== Custom plug-in registries

For more information about setting up a custom registry, see the description of the link:https://github.com/eclipse/che-plugin-registry[official registry repository].

There are two ways of using plug-ins from a custom registry:

* Specify a link to the plug-in in the configuration of a workspace. See xref:adding-a-plug-in-by-configuring-a-workspace_publishing-che-theia-plug-ins[Adding a plug-in into a workspace via configuration].

* Replace the default official registry with a custom one in your {prod-short} instance. To do that, set the `PLUGIN_REGISTRY_IMAGE` environment variable in your {prod-short} configuration. Note that plug-ins from the official registry are not available from the dashboard interface. To include them, add references into your registry from the official registry.


.Additional resources

* xref:che-theia-plug-in-metadata_what-is-a-che-theia-plug-in[]
