---
title: Adding support for a new debugger
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/adding-support-for-a-new-debugger/
folder: che-7/contributor-guide
summary:
---

[id="adding-support-for-a-new-debugger"]
= Adding support for a new debugger

This section describes how to add a new debugger into {prod}.

.Prerequisites

* Install the latest Che-Theia plug-in Yeoman generator by running the following command:
+
----
$ npm install -g yo @theia/generator-plugin
----

.Procedure

. Generate a sample by running the `yo @theia/plugin` command. When prompted, confirm the choices for *Backend plug-in*, *Samples*, and then *Debugger sample*. This creates a project and a ready-to-use plug-in, which can be deployed.

. Replace the mock implementation of the debug adapter in the `src/vscode-mockDebug.ts` and `src/vscode-mockRuntime.ts` files with code that interacts with a real debugger or runtime.

. Build the plug-in by running the `yarn` command in the root of the project.

. Deploy the Che-Theia plug-in via the plug-in registry.


.Additional resources

* link:https://microsoft.github.io/debug-adapter-protocol/[Debug Adapter Protocol]
* link:https://code.visualstudio.com/api/extension-guides/debugger-extension[VS Code debugger extension documentation]
* link:https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/[Implementations Debug Adapters]
* link:{site-baseurl}che-7/publishing-che-theia-plug-ins/#adding-a-che-theia-plug-in-to-the-che-plug-in-registry_publishing-che-theia-plug-ins[Adding a Che-Theia plug-in to the {prod-short} plug-in registry]
