// Module included in the following assemblies:
//
// setup-{prod-id-short}-in-tls-mode

[id="generating-self-signed-certificates_{context}"]
= Generating self-signed TLS certificates

This section describes how to prepare self-signed TLS certificates to use with {prod-short} on different platforms.


[discrete]
== Prerequisites

* Find out expected domain name where {prod-short} deployment is planned

+
[subs="+quotes"]
----
# default for minishift
$( minishift ip ).nip.io

# default for minikube
$( minikube ip ).nip.io

# default for crc
apps-crc.testing
----

* Find out `openssl.cnf` file location on target machine.
  Usual openssl configuration file location is given below.

+
[subs="+quotes"]
----
# Fedora, Red Hat, CentOS
/etc/pki/tls/openssl.cnf
# Debian, Ubuntu, Mint, Arch
/etc/ssl/openssl.cnf
----

[discrete]
== Procedure

. Set necessary environment variables

+
[subs="+quotes"]
----
$ CA_CN="Local Eclipse Che Signer"
$ DOMAIN=*.<expected.domain.com>
$ OPENSSL_CNF=<path_to_openssl.cnf>
----

+
[subs="+quotes"]
----
# Example with minikube on Fedora 31
$ CA_CN="Local Eclipse Che Signer"
$ DOMAIN=\*.$( minikube ip ).nip.io
$ OPENSSL_CNF=/etc/pki/tls/openssl.cnf

# Example with crc on OSX
$ export CA_CN="Local Eclipse Che Signer"
$ export DOMAIN=*.apps-crc.testing
$ export OPENSSL_CNF=/System/Library/OpenSSL/openssl.cnf
----

. Generate root CA key. Add `-des3` parameter if passphrase is needed

+
[subs="+quotes"]
----
$ openssl genrsa -out ca.key 4096
----


. Generate root CA certificate.

+
[subs="+quotes"]
----
$ openssl req -x509 \
  -new -nodes \
  -key ca.key \
  -sha256 \
  -days 1024 \
  -out ca.crt \
  -subj /CN="${CA_CN}" \
  -reqexts SAN \
  -extensions SAN \
  -config <(cat ${OPENSSL_CNF} \
      <(printf '[SAN]\nbasicConstraints=critical, CA:TRUE\nkeyUsage=keyCertSign, cRLSign, digitalSignature'))
----


. Generate domain key.

+
[subs="+quotes"]
----
$ openssl genrsa -out domain.key 2048
----

. Generate certificate signing request for the domain.

+
[subs="+quotes"]
----
$ openssl req -new -sha256 \
    -key domain.key \
    -subj "/O=Local Eclipse Che/CN=${DOMAIN}" \
    -reqexts SAN \
    -config <(cat ${OPENSSL_CNF} \
        <(printf "\n[SAN]\nsubjectAltName=DNS:${DOMAIN}\nbasicConstraints=critical, CA:FALSE\nkeyUsage=digitalSignature, keyEncipherment, keyAgreement, dataEncipherment\nextendedKeyUsage=serverAuth")) \
    -out domain.csr
----


. Generate domain certificate.

+
[subs="+quotes"]
----
$ openssl x509 \
    -req \
    -sha256 \
    -extfile <(printf "subjectAltName=DNS:${DOMAIN}\nbasicConstraints=critical, CA:FALSE\nkeyUsage=digitalSignature, keyEncipherment, keyAgreement, dataEncipherment\nextendedKeyUsage=serverAuth") \
    -days 365 \
    -in domain.csr \
    -CA ca.crt \
    -CAkey ca.key \
    -CAcreateserial -out domain.crt
----


After executing those steps, it will be possible to use domain.crt and domain.key for Route/Ingress TLS
and link:{site-baseurl}che-7/setup-che-in-tls-mode-with-self-signed-certificate/#che-usage-with-tls_setup-che-in-tls-mode-with-self-signed-certificate[ca.crt for importing into browsers].
