.List of recommended images to pre-pull
[options="header"]
|===
|Image |URL |Tag

|che-plugin-metadata-broker |quay.io/eclipse/che-plugin-metadata-broker:{broker-ver} |{broker-ver} 

|che-plugin-artifacts-broker |quay.io/eclipse/che-plugin-artifacts-broker:{broker-ver} |{broker-ver}

|che-theia |quay.io/eclipse/che-theia:{prod-ver} |{prod-ver}

|che-python-3.7 |quay.io/eclipse/che-python-3.7:{prod-ver} |{prod-ver}

|che-php-7 |quay.io/eclipse/che-php-7:{prod-ver} |{prod-ver}

|che-cpp-rhel7 |quay.io/eclipse/che-cpp-rhel7:{prod-ver} |{prod-ver}

|che-golang-1.14 |quay.io/eclipse/che-golang-1.14:{prod-ver} |{prod-ver}

|che-java11-maven |quay.io/eclipse/che-java11-maven:{prod-ver} |{prod-ver}

|che-nodejs10-ubi |quay.io/eclipse/che-nodejs10-ubi:{prod-ver} |{prod-ver}

|che-quarkus |quay.io/eclipse/che-quarkus:{prod-ver} |{prod-ver}
|===

[NOTE]
====
The table of recommended images to pre-pull is updated once per release and might vary from the most updated build at the time.

To get the latest build:

. Install the dependencies:
+
----
# dnf install -y jq python-pip
----
+
----
# pip install yq
----

.Procedure

. Use the following scriptlet:
+
[subs="+attributes,+quotes"]
----
$ curl -sSLo- https://raw.githubusercontent.com/eclipse/che-operator/master/olm/eclipse-che-preview-openshift/deploy/olm-catalog/eclipse-che-preview-openshift/{che-ver}/eclipse-che-preview-openshift.v{che-ver}.clusterserviceversion.yaml | \
  yq -r '.spec.relatedImages[]
----
+
[source,json]
----
#[...]
{
  "name": "che-theia-7.19.2",
  "image": "quay.io/eclipse/che-theia@sha256:11b5fe33edd72df22f76d7933ba79029051f4c0c6adc6c1a91f2dfe4228455c9"
}
{
  "name": "che-theia-7.20.0",
  "image": "quay.io/eclipse/che-theia@sha256:92a8bac94e446f1f933d1a92bc96dace9450c9f4efdef5539a429a37d14be904"
}
{
  "name": "che-theia-7.20.1",
  "image": "quay.io/eclipse/che-theia@sha256:a56428ee28ceefca2a1cba51093f6015e0eee82659fec786f2e1fdc939fdb856"
}
#[...]
----
+
The following images from the list cannot be pre-pulled and need to be pulled manually using:

[subs="+quotes"]
----
$ skopeo copy --all _<image>_
----
+
* machine-exec image
* images without a sleep command installed
* images that mount volumes in the docker file

====
