:_content-type: PROCEDURE

:parent-context-of-manually-upgrading-{prod-id-short}-{prod-last-version-pre-dwo}-to-7.49-on-openshift: {context}

[id="manually-upgrading-{prod-id-short}-{prod-last-version-pre-dwo}-to-7.49-on-openshift_{context}"]
= Manually upgrading Che 7.41 to 7.49 on Red Hat OpenShift

You can manually upgrade Che 7.41 to 7.49 on Red Hat OpenShift.

.Prerequisites

* An instance of {prod-prev-short} deployed on one of the xref:supported-platforms.adoc[]. The instance uses the default internal PostgreSQL database and has OAuth enabled on Red Hat OpenShift. See {prod-docs-url-enable-oauth}.
* The following command line tools are available:
** `oc`
** `curl`
** `jq`
* The host running the upgrade commands is running on Linux.
* Optional:
.. All changes from all workspaces have been committed and pushed to their Git remotes.
.. All workspaces have been stopped to avoid UX degradation.
.. The {prod-prev-short} data have been backed up. See {prod-docs-url-backup-recovery}.

.Procedure

. Download xref:attachment$migration/1-prepare.sh[1-prepare.sh].
+
`1-prepare.sh` shuts down {prod-prev-short} and {identity-provider}, fetches the existing users' data, and dumps the {prod-short} database.

. Download xref:attachment$migration/2-migrate.sh[2-migrate.sh].
+
`2-migrate.sh` fetches {prod-prev-short} {identity-provider} and database data, and repopulates the database with updated data.

. Download xref:attachment$migration/3-subscribe.sh[3-subscribe.sh].
+
`3-subscribe.sh` deletes {prod-prev-short} Operator and {identity-provider} resources, updates the CheCluster CR, and creates a new {prod-short} Operator subscription.

. Download xref:attachment$migration/4-wait.sh[4-wait.sh].
+
`4-wait.sh` waits until {prod-short} is ready, which can take more than 5 minutes.

. Set the environment variables to use in the upgrade scripts:
+
[source,bash,subs="+attributes"]
----
export INSTALLATION_NAMESPACE={prod-namespace} # <1>
export PRODUCT_ID={prod-id}
export PRODUCT_DEPLOYMENT_NAME={prod-deployment}
export PRODUCT_OPERATOR_NAME={prod-operator}
export PRODUCT_OLM_STABLE_CHANNEL={prod-stable-channel}
export PRODUCT_OLM_CATALOG_SOURCE={prod-stable-channel-catalog-source}
export PRODUCT_OLM_PACKAGE={prod-stable-channel-package}
export PRODUCT_OLM_STARTING_CSV={prod-stable-channel-starting-csv}
export PRE_MIGRATION_PRODUCT_OPERATOR_NAMESPACE={prod-namespace} # <2>
export PRE_MIGRATION_PRODUCT_SHORT_ID={pre-migration-prod-id-short}
export PRE_MIGRATION_PRODUCT_DEPLOYMENT_NAME={pre-migration-prod-deployment}
export PRE_MIGRATION_PRODUCT_OPERATOR_NAME={pre-migration-prod-operator}
export PRE_MIGRATION_PRODUCT_CHE_CLUSTER_CR_NAME={pre-migration-prod-checluster}
export PRE_MIGRATION_PRODUCT_IDENTITY_PROVIDER_DEPLOYMENT_NAME={identity-provider-id}
export PRE_MIGRATION_PRODUCT_SUBSCRIPTION_NAME={pre-migration-prod-subscription}
----
<1> `{prod-namespace}` or another {orch-namespace} where {prod-prev-short} was previously installed.
<2> `{prod-namespace}` or another {orch-namespace} where {prod-prev-short} was previously installed.


. Run the upgrade scripts:
+
[source,terminal]
----
$ chmod +x ./1-prepare.sh ./2-migrate.sh ./3-subscribe.sh ./4-wait.sh; \
  ./1-prepare.sh && ./2-migrate.sh && ./3-subscribe.sh && ./4-wait.sh
----

.Verification
 
* In the {prod-short} dashboard, go to menu:About[Server Version] to verify that it is *7.49*.

:context: {parent-context-of-manually-upgrading-{prod-id-short}-{prod-last-version-pre-dwo}-to-7.49-on-openshift}