[id="accessing-che-from-openshift-developer-perspective_{context}"]
= Accessing Che from OpenShift Developer Perspective

:context: accessing-che-from-openshift-developer-perspective

The OpenShift Developer Perspective enables a developer-focused view in the OpenShift 4 web console. OpenShift Developer Perspective provides a view switcher to transition between:

* `Administrator` - the traditional administration focused console
* `Developer` -  this perspective provides a high-level of abstraction over Kubernetes and OpenShift components to allow developers to focus on their application development.

[NOTE]
====
OpenShift Developer Perspective is a default part of OpenShift Container Platform starting with version 4.2. Note also that namespace is the OpenShift Container Platform name for OpenShift project (instead of workspace).
====

include::con_openshift-developer-perspective-integration-with-che.adoc[leveloffset=+1]

include::proc_editing-the-code-of-applications-running-in-openshift-container-platform-using-che.adoc[leveloffset=+1]

include::proc_accessing-che-from-red-hat-applications-menu.adoc[leveloffset=+1]

////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
