---
title: Installing Che on bare metal using Kubespray
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/installing-che-on-bare-metal-using-kubespray
folder: che-7/overview
summary:
---

:page-liquid:
:parent-context-of-installing-che-on-bare-metal-using-kubespray: {context}

[id="installing-{prod-id-short}-on-bare-metal-using-kubespray_{context}"]
= Installing {prod-short} on bare metal using Kubespray

:context: installing-{prod-id-short}-on-bare-metal-using-kubespray

This article explains how to create a single or multi-nodes bare metal Kubernetes cluster using Kubespray to deploy {prod-short}.

A bare metal cluster has multiple advantages (performance, density, etc.) but also drawbacks (longer to reset, etc.). An other type of installation is inside Virtual Machines for example. 

There are a lot of ways to deploy a bare metal cluster, we will use Kubespray in this article for its simplicity.

== Configuration

Hardware:

* CPU: 2 preferable (no check performed by Kubespray)
* RAM: 1024MB/1500MB minimum for worker/master nodes enforced in Kubespray (configurable)

[NOTE]
====
{prod} requires minimum CPU and RAM to run itself and to spawn user environments
====

Software:

* O/S: link:https://github.com/kubernetes-sigs/kubespray#supported-linux-distributions[check the supported distributions]
* Kubespray: 2.12.5
* Python: 3.7
* Helm: 3.1.2

include::proc_using-kubespray-to-set-up-kubernetes.adoc[leveloffset=+1]

include::proc_installing-load-balancer-on-a-bare-metal-cluster.adoc[leveloffset=+1]

include::proc_installing-storage-on-a-bare-metal-cluster.adoc[leveloffset=+1]

include::assembly_installing-{prod-cli}.adoc[leveloffset=+1]

include::proc_installing-{prod-id-short}-on-kubespray-using-{prod-cli}.adoc[leveloffset=+1]

:context: {parent-context-of-installing-{prod-id-short}-on-bare-metal-using-kubespray}
