---
title: Accessing Che from OpenShift Developer Perspective
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/accessing-che-from-openshift-developer-perspective/
folder: che-7/overview
summary:
---

:page-liquid:

[id="accessing-{prod-id-short}-from-openshift-developer-perspective_{context}"]
= Accessing {prod-short} from OpenShift Developer Perspective

:context: accessing-{prod-id-short}-from-openshift-developer-perspective

The OpenShift Developer Perspective enables a developer-focused view in the OpenShift 4 web console. OpenShift Developer Perspective provides a view switcher to transition between:

* *Administrator* - The traditional administration-focused console.
* *Developer* -  A high-level of abstraction over Kubernetes and OpenShift components to allow developers to focus on application development.

[NOTE]
====
OpenShift Developer Perspective is a default part of OpenShift Container Platform starting with version 4.2.
====

include::con_openshift-developer-perspective-integration-with-che.adoc[leveloffset=+1]

include::proc_editing-the-code-of-applications-running-in-openshift-container-platform-using-che.adoc[leveloffset=+1]

include::proc_accessing-che-from-red-hat-applications-menu.adoc[leveloffset=+1]

////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
