---
title: Che quick-starts
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/che-quick-starts/
redirect_from:
  - quick-start.html
folder: che-7/overview
summary:
---

:page-liquid:
:parent-context-of-che-quick-starts: {context}

[id="{prod-id-short}-quick-starts_{context}"]
= {prod-short} quick-starts

:context: {prod-id-short}-quick-starts

This section contains instructions for getting quickly started with {prod}.

{prod-short} is available in two modes:

* *Single-user*: Non-authenticated {prod-short}, lighter and suited for personal environments

* *Multi-user*: Authenticated {prod-short} suited for organizations and developer teams

You need a Kubernetes (version 1.9 or higher) or OpenShift cluster to deploy {prod-short} on.

Various installation methods are covered in this documentation.
It goes from 

== On a local single-node cluster

WARNING: Remember that single-node Kubernetes clusters are suited only for testing or single-user development.
Do *NOT* use such clusters to run {prod-short} for organizations or developer teams.

* link:{site-baseurl}che-7/installing-{prod-id-short}-on-codeready-containers/[CodeReady containers]

* link:{site-baseurl}che-7/installing-{prod-id-short}-on-docker-desktop/[Docker Desktop]

* link:{site-baseurl}che-7/installing-{prod-id-short}-on-minikube/[Minikube]

* link:{site-baseurl}che-7/installing-{prod-id-short}-on-minishift/[Minishift]


== On a private (__on-premise__) cluster

Create your Kubernetes `production-capable` cluster _on-premise__ to run {prod-short}.

NOTE: `production-capable` means you can deploy clusters from __test-like__ xref:on-a-local-single-node-cluster[local single-node clusters] to production grade high-availability ones depending on your configuration (number of nodes, etc.)

* link:{site-baseurl}che-7/installing-{prod-id-short}-on-bare-metal-using-kubespray/[Bare metal] __using Kubespray__

* link:{site-baseurl}che-7/installing-{prod-id-short}-on-openshift-3-using-the-operator/[OpenShift 3] __using the Operator__

* link:{site-baseurl}che-7/installing-{prod-id-short}-on-openshift-4-using-operatorhub/[OpenShift 4] __using OperatorHub__

== On a cloud provided cluster

Use a cloud provided Kubernetes cluster from one of the most popular cloud providers to deploy {prod-short}. 

It offers convenient (but chargeable) on-demand horsepower.

* link:{site-baseurl}che-7/deploying-che-on-kubernetes-on-aws/[Amazon Web Services]

* link:{site-baseurl}che-7/installing-che-on-google-cloud-platform/[Google Cloud Platform]

* link:{site-baseurl}che-7/installing-eclipse-che-on-microsoft-azure/[Microsoft Azure]

* link:{site-baseurl}che-7/accessing-che-from-openshift-developer-perspective/[OpenShift Developer Perspective]

:context: {parent-context-of-che-quick-starts}
