// Module included in the following assemblies:
//
// {prod-id-short}-workspace-configuration

[id="storage-strategies-for-{prod-id-short}-workspaces_{context}"]
= Storage strategies for {prod-short} workspaces

Workspace Pods use Persistent Volume Claims (PVCs), which are bound to the physical Persistent Volumes (PVs) with https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[ReadWriteOnce access mode]. The way how {prod-short} server uses PVCs for workspaces is configurable, and it is called PVC strategy:

include::examples/{project-context}-pvc-strategies.adoc[]

[id="unique-pvc-strategy_{context}"]
== Unique PVC strategy

.How the unique PVC strategy works

Every {prod-short} Volume of workspace gets its own PVC, which means workspace PVCs are created when a workspace starts for the first time. Workspace PVCs are deleted when a corresponding workspace is deleted.

User-defined PVCs are created with few modifications:

* They are provisioned with generated names to guarantee that it is not conflicting with other PVCs in namespace.

* Subpaths of mount volumes that reference user-defined PVCs are prefixed with `{workspace id}/{PVC name}`.
It is done to have the same data structure on PV on different PVC strategies (see xref:how-the-subpaths-are-used_{context}[]).


[id="common-pvc-strategy_{context}"]
== Common PVC Strategy

.How the common PVC strategy works

All workspaces (within one {k8s-namespace}) use the same PVC to store data in their declared volumes (projects and workspace logs by default and whatever additional volumes that a user can define.)

User-defined PVCs are ignored and volumes that reference PVCs are replaced with volume that references common PVC.

The corresponding containers volume mounts are relinked to common volume and sub-paths are prefixed with `'{workspaceID}/{originalPVCName}'` (see xref:how-the-subpaths-are-used_{context}[]).

User-defined PVC name is used as {prod-short} Volume name. It means that if Machine is configured to use {prod-short} Volume with the same name as user-defined
PVC has then they will use the same shared folder in common PVC.

When a workspace is deleted, a corresponding subdirectory (`${ws-id}`) is deleted in the PV directory.

.Restrictions on using the common PVC strategy

When the `common` strategy is used and a workspace PVC access mode is ReadWriteOnce (RWO), only one {admin-context} node can simultaneously use the PVC.

If there are several nodes, you can use the `common` strategy, but:

* The workspace PVC access mode must be reconfigured to `ReadWriteMany` (RWM), so multiple nodes can use this PVC simultaneously.

* Only one workspace in the same namespace may be running. See link:{site-baseurl}che-7/advanced-configuration-options/#configuring-namespace-strategies_advanced-configuration-options[Configuring namespace strategies].


[id="per-workspace-pvc-strategy_{context}"]
== Per-workspace PVC strategy

.How the per-workspace PVC strategy works

The `per-workspace` strategy works similarly to the `common` PVC strategy. The only difference is that all workspace volumes (but not all workspaces) use the same PVC to store data (projects and workspace logs by default and any additional volumes that a user can define).


[id="how-the-subpaths-are-used_{context}"]
== How the subpaths are used in PVCs

----
/pv0001
  /workspaceID1
  /workspaceID2
  /workspaceIDn
    /che-logs
    /projects
    /<volume1>
    /<volume2>
    /<User-defined PVC name 1 | volume 3>
    ...
----

Volumes can be anything that a user defines as volumes for workspace machines. The volume name is equal to the directory name in `${PV}/${ws-id}`.
