[id="che-plug-in-broker_{context}"]
= Che plug-in broker

Plug-in brokers are special services that, given a plug-in `meta.yaml` file:

* Gather all the information to provide a Che plug-in definition that the Che server knows.

* Perform preparation actions in the workspace namespace (download, unpack files, process configuration).

The main goal of the plug-in broker is to decouple the Che plug-in definition from the actual plug-ins that Che can support. With brokers, Che can support different plug-ins without updating the Che server.

The Che server starts the plug-in broker. The plug-in broker runs in the same Kubernetes namespace as the workspace. It has access to the plug-ins and project persistent volumes.

A plug-in broker is defined as a container image (for example, `eclipse/che-plugin-broker`). The plug-in type determines the type of the broker that is started. Two types of plug-ins are supported: Che plug-in and Che editor.

[cols=2*]
|===
| Source code
| link:https://github.com/eclipse/che-plugin-broker[Che Plug-in broker]

| Container image
| `eclipse/che-init-plugin-broker` +
`eclipse/che-unified-plugin-broker`
|===
