[id="{prod-id-short}-plug-in-broker_{context}"]
= {prod-short} plug-in broker

Plug-in brokers are special services that, given a plug-in `meta.yaml` file:

* Gather all the information to provide a {prod-short} plug-in definition that the {prod-short} server knows.

* Perform preparation actions in the workspace namespace (download, unpack files, process configuration).

The main goal of the plug-in broker is to decouple the {prod-short} plug-in definition from the actual plug-ins that {prod-short} can support. With brokers, {prod-short} can support different plug-ins without updating the {prod-short} server.

The {prod-short} server starts the plug-in broker. The plug-in broker runs in the same Kubernetes namespace as the workspace. It has access to the plug-ins and project persistent volumes.

A plug-in broker is defined as a container image (for example, `eclipse/che-plugin-broker`). The plug-in type determines the type of the broker that is started. Two types of plug-ins are supported: {prod-short} plug-in and {prod-short} editor.

[cols=2*]
|===
| Source code
| link:https://github.com/eclipse/che-plugin-broker[{prod-short} Plug-in broker]

| Container image
| `eclipse/che-init-plugin-broker` +
`eclipse/che-unified-plugin-broker`
|===
