// Module included in the following assemblies:
//
// {prod-id-short}-workspace-configuration

[id="storage-strategies-for-{prod-id-short}-workspaces_{context}"]
= Storage strategies for {prod-id-short} workspaces

Workspace Pods use Persistent Volume Claims (PVCs), which are bound to the physical Persistent Volumes (PVs) with link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[ReadWriteOnce access mode]. It is possible to configure how the {prod-short} server uses PVCs for workspaces. The individual methods for this configuration are called PVC strategies:

include::examples/{project-context}-pvc-strategies.adoc[]

{prod} uses the `common` PVC strategy in combination with the "one namespace per user" namespace strategy when all {prod-short} workspaces operate in the user's namespace, sharing one PVC.

[id="the-common-pvc-strategy_{context}"]
== The `common` PVC strategy

All workspaces inside a Kubernetes-native namespace use the same Persistent Volume Claim (PVC) as the default data storage when storing data such as the following in their declared volumes: 

* projects
* workspace logs
* additional Volumes defined by a use

When the `common` PVC strategy is in use,  user-defined PVCs are ignored and volumes that refer to these user-defined PVCs are replaced with a volume that refers to the common PVC.
In this strategy, all {prod-short) workspaces use the same PVC. When the user runs one workspace, it only binds to one node in the cluster at a time.

The corresponding containers volume mounts link to a common volume, and sub-paths are prefixed with `'{workspaceID}/{originalPVCName}'`. For more details, see xref:how-subpaths-are-used-in-pvcs_{context}[].

The {prod-short} Volume name is identical to the name of the user-defined PVC. It means that if a machine is configured to use a {prod-short} volume with the same name as the user-defined
PVC has, they will use the same shared folder in the common PVC.

When a workspace is deleted, a corresponding subdirectory (`${ws-id}`) is deleted in the PV directory.

.Restrictions on using the `common` PVC strategy

When the `common` strategy is used and a workspace PVC access mode is ReadWriteOnce (RWO), only one {admin-context} node can simultaneously use the PVC.

If there are several nodes, you can use the `common` strategy, but:

* The workspace PVC access mode must be reconfigured to `ReadWriteMany` (RWM), so multiple nodes can use this PVC simultaneously.

* Only one workspace in the same namespace may be running. See link:{site-baseurl}che-7/configuring-namespace-strategies[Configuring namespace strategies].

The `common` PVC strategy is not suitable for large multi-node clusters. Therefore, it is best to use it in single-node clusters. However, in combination with `per-workspace` namespace strategy, the `common` PVC strategy is usable for clusters with around 75 nodes. The PVC used in this strategy must be large enough to accommodate all projects since there is a risk of the event, in which one project depletes the resources of others. 

[id="the-per-workspace-pvc-strategy_{context}"]
== The `per-workspace` PVC strategy

The `per-workspace` strategy is similar to the `common` PVC strategy. The only difference is that all workspace Volumes, but not all the workspaces, use the same PVC as the default data storage for:

* projects
* workspace logs
* additional Volumes defined by a user

It’s a strategy when {prod-short} keeps its workspace data in assigned PVs that are allocated by a single PVC. 

The `per-workspace` PVC strategy is the most universal strategy out of the PVC strategies available and acts as a proper option for large multi-node clusters with a higher amount of users. Using the `per-workspace` PVC strategy, users can run multiple workspaces simultaneously, results in more PVCs being created.

[id="the-unique-pvc-strategy_{context}"]
== The `unique` PVC strategy

When using the `unique `PVC strategy, every {prod-short} Volume of a workspace has its own PVC. This means that workspace PVCs are:

Created when a workspace starts for the first time. 
Deleted when a corresponding workspace is deleted.

User-defined PVCs are created with the following specifics:

* They are provisioned with generated names to prevent naming conflicts with other PVCs in a namespace.

*  Subpaths of the mounted Physical persistent volumes that reference user-defined PVCs are prefixed with `{workspace id}/{PVC name}`. This ensures that the same PV data structure is set up with different PVC strategies. For details, see xref:how-subpaths-are-used-in-pvcs_{context}[].

The `unique` PVC strategy is suitable for larger multi-node clusters with a lesser amount of users. Since this strategy operates with separate PVCs for each volume in a workspace, vastly more PVCs are created.


[id="how-subpaths-are-used-in-pvcs_{context}"]
== How subpaths are used in PVCs

Subpaths illustrate the folder hierarchy in the Persistent Volumes (PV).

----
/pv0001
  /workspaceID1
  /workspaceID2
  /workspaceIDn
    /che-logs
    /projects
    /<volume1>
    /<volume2>
    /<User-defined PVC name 1 | volume 3>
    ...
----

When a user defines volumes for components in the devfile, all components that define the volume of the same name will be backed by the same directory in the PV as `${PV}/${ws-id}/${volume-name}`. Each component can have this location mounted on a different path in its containers.


.Example
Using the `common` PVC strategy, user-defined PVCs are replaced with subpaths on the common PVC. When the user references a volume as `my-volume`, it is mounted in the common-pvc with the `/workspace-id/my-volume` subpath.

