// Module included in the following assemblies:
//
// accessing-{prod-id-short}-from-openshift-developer-perspective

[id="openshift-developer-perspective-integration-with-che_{context}"]
= OpenShift Developer Perspective integration with {prod-short}

This section provides information about OpenShift Developer Perspective support for {prod-short}.

When the {prod-short} Operator is installed into OpenShift Container Platform 4.2 and later, it creates a `ConsoleLink` Custom Resource (CR). This adds an interactive link to the *Red Hat Applications* menu for accessing the {prod-short} installation using the OpenShift Developer Perspective console.

To access the *Red Hat Applications* menu, click the three-by-three square icon (░) on the main screen of the OpenShift web console. The {prod-short} *Console Link*, displayed in the drop-down menu, creates a new workspace or redirects the user to an existing one.

[NOTE]
====
.{ocp} console links are not created when {prod-short} is used with HTTP resources

When installing {prod-short} with the `From Git` option, the OpenShift Developer Perspective ConsoleLink is only created if {prod-short} is deployed with HTTPS supported URL link. The ConsoleLink will not be created if an HTTP resource is used.
====

////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the concept module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
