// Module included in the following assemblies:
//
// :context: installing-{prod-id-short}-on-openshift-3-using-the-operator

[id="installing-{prod-id-short}-on-openshift-3-using-the-operator-and-ssl_{context}"]
= Installing {prod-short} on OpenShift 3 using the Operator and SSL

This section describes how to install {prod-short} on OpenShift 3 with the CLI management tool, using the Operator method and the SSL option.

.Prerequisites

* A running instance of OpenShift 3.11.
* Administrator rights on this OpenShift 3 instance.
* The `{prod-cli}` management tool is installed. See link:{site-baseurl}che-7/using-the-chectl-management-tool/[Installing the `{prod-cli}` management tool].
* The URL for applications on this OpenShift instance is known as `<OPENSHIFT_APPS_URL>`. See xref:preparing-openshift-3-for-installing-che_{context}[].
* To apply settings that can't be set directly by the main {prod-cli} command line parameters, prepare a YAML file `configuration.yaml` containing the configuration options. See link:{site-baseurl}che-7/configuring-the-che-installation[Configuring the {prod-short} installation].

.Procedure

. Run the following command to create the {prod-short} instance:
+
[subs="+quotes,+attributes",options="nowrap"]
----
$ {prod-cli} server:start -n _<project-name>_ --domain=<OPENSHIFT_APPS_URL> \
  --che-operator-cr-patch-yaml=configuration.yaml
----
+
[NOTE]
====
* To create the {prod-short} instance on demo OpenShift clusters that have not been setup with a valid certificate for the routes, run the command with the `--self-signed-cert` flag.
* To install {prod-short} with the default values, omit the `--che-operator-cr-patch-yaml=configuration.yaml` option.
====

.Verification steps

. The output of the previous command ends with:
+
----
Command server:start has completed successfully.
----

. Navigate to the {prod-short} cluster instance. The domain is now prefixed with HTTPS and using _Let’s Encrypt_ ACME certificates: `{prod-url-secure}.__<OPENSHIFT_APPS_URL>__`
