// Module included in the following assemblies:
//
// installing-{prod-cli}

[id="installing-the-{prod-cli}-management-tool-on-linux-or-macos_{context}"]
= Installing the {prod-cli} management tool on Linux or macOS

This section describes how to install the `{prod-cli}` management tool on Linux or macOS.

.Prerequisites

* The directory `/usr/local/bin` is in the user `$PATH`.
* The `sudo` command is configured for the current user.
* No old or undesired versions of `{prod-cli}` present on the system.

.Procedure

. Run the following command in the terminal (this downloads and executes the `install.sh` script):
+
[subs="+attributes"]
----
$ bash <(curl -sL  https://www.eclipse.org/che/{prod-cli}/)
----

. Run the following command to verify that the `{prod-cli}` binary file used is `/usr/local/bin/{prod-cli}`:
+
[subs="+attributes"]
----
$ which {prod-cli}
/usr/local/bin/{prod-cli}
----
+

. Run the following command to verify that the version of {prod-cli} that is the expected one.
+
[subs="+attributes"]
----
$ {prod-cli} --version
----
+
[TIP]
====
To identify the latest stable release, see the link:https://github.com/che-incubator/{prod-cli}/releases[list of {prod-cli} releases] and search for a release not containing "next" in the name.
====

. Read the installation logs.
+
[subs="+attributes"]
----
$ cat {prod-cli}-install.log
----
