[id="upgrading-the-chectl-management-tool_{context}"]
= Upgrading the chectl management tool

This section describes how to upgrade the chectl management tool.

[discrete]
== Prerequisites

* `chectl` is installed. See link:#installing-the-chectl-management-tool-on-windows_{context}[Installing the chectl management tool on Windows] and link:#installing-the-chectl-management-tool-on-linux-or-macos_{context}[Installing the chectl management tool on Linux or macOS].

[discrete]
== Procedure

* Run the following command in the terminal to update `chectl` to the latest version.
+
----
# chectl update
----
+
The command updates chectl based on its current channel.


[NOTE]
====
Two update channels are available for `chectl`: `stable` and `next`.

`stable` is for the latest released version of Eclipse Che. 

`next` is updated after each activity in master branch of the link:https://github.com/che-incubator/chectl[chectl repository].

To move to a different channel, invoke the update with the name of the channel as an optional argument.

----
# chectl update [next|stable]
----
====

[discrete]
== Additional resources

* link:https://github.com/che-incubator/chectl/blob/master/README.md[`chectl` README]
