// Module included in the following assemblies:
//
// running-{prod-id-short}-locally

[id="installing-{prod-id-short}-on-kind-using-{prod-cli}_{context}"]
= Installing {prod-short} on kind using {prod-cli}

This section describes how to install {prod-short} on https://github.com/kubernetes-sigs/kind[kind] using {prod-cli}. kind is a tool for running local Kubernetes clusters using Docker-formatted containers as nodes. It is useful for quickly creating ephemeral clusters, and is used as part of the test infrastructure of the Kubernetes project. Running {prod-short} in kind is a way to try the application, or for a contributor to test their change quickly with a real cluster.

.Prerequisites

* The `{prod-cli}` management tool is installed. See link:{site-baseurl}che-7/using-the-chectl-management-tool/[Installing the `{prod-cli}` management tool].
* A running kind cluster. See link:https://kind.sigs.k8s.io/#installation-and-usage[kind installation and usage documentation].

.Procedure

For {prod-short} installation, kind cluster should have an Ingress backend and a persitent volumes storage backend. If these requirements are met, go directly to xref:run-{prod-cli}-on-kind[deploying {prod-short}].

Following instruction is a way of configuring Kind cluster to have all needed for Eclipse Che components:

. Install https://github.com/kubernetes-csi/csi-driver-host-path[csi-driver-host-path] in the kind cluster:
+
Install snapshotter CRDs as described in the https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/docs/deploy-1.17-and-later.md#volumesnapshot-crds-and-snapshot-controller-installation[docs]:
+
[subs="+quotes"]
----
$ SNAPSHOTTER_VERSION=v2.1.1

# Apply VolumeSnapshot CRDs
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

# Create snapshot controller
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
----
Value of the latest `SNAPSHOTTER_VERSION` could be found on https://github.com/kubernetes-csi/external-snapshotter/releases[corresponding release page].
+
Then deploy:
+
[subs="+quotes"]
----
$ git clone https://github.com/kubernetes-csi/csi-driver-host-path && cd csi-driver-host-path
$ ./deploy/kubernetes-__<version>__/deploy.sh
$ kubectl apply -f examples/csi-storageclass.yaml
----
Kubernetes version could be obtained via `kubectl version` command (see `Server Version`).

. Set `csi-hostpath-sc` as the default `StorageClass`:
+
----
$ kubectl patch storageclass csi-hostpath-sc -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
$ kubectl patch storageclass standard -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "false"}}}'
----

. Install the https://kubernetes.github.io/ingress-nginx/deploy/[NGINX Ingress Controller]:
+
----
$ VERSION=0.30.0
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-${VERSION}/deploy/static/mandatory.yaml
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-${VERSION}/deploy/static/provider/cloud-generic.yaml
----

. Install the https://metallb.universe.tf/[MetalLB] load balancer:
+
[subs="+quotes"]
----
$ kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
$ kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
$ kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
----
+
[NOTE]
====
The above command may apply to an out-of-date version of MetalLB Kubernetes manifests. See https://metallb.universe.tf/installation/[the installation instructions] for the most up-to-date command.
====

. Determine an IP range to allocate to MetalLB from the `docker` bridge network:
+
----
$ docker inspect bridge | grep -C 5 Subnet
"IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
----
+
In this case, there is a `/16` subnet range to allocate. Choose a section in the `172.17.250.0` range.

. Create a `ConfigMap` for MetalLB specifying the IP range to expose:
+
----
$ cat << EOF > metallb-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.250.1-172.17.250.250
EOF
$ kubectl apply -f metallb-config.yaml
----

. The `ingress-nginx` service now has an external IP:
+
----
$ kubectl get svc -n ingress-nginx
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
ingress-nginx   LoadBalancer   10.107.194.26   172.17.250.1   80:32033/TCP,443:30428/TCP   19h
----

[id="run-{prod-cli}-on-kind"]
. Run `{prod-cli}`, using the external IP of the `ingress-nginx` Service as an https://nip.io[nip.io] URL:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start --installer operator --platform k8s --domain 172.17.250.1.nip.io
----
+
[NOTE]
====
In some cases, after all the steps above, it is still not possible to reach {prod-short} from the host machine. If you encounter such problem, refer to kind cluster documentation or forums on how to make an endpoint available outside the kind cluster for your system and network configuration.
====
