[id="proc_installing-{prod-id-short}-using-storage-classes_{context}"]

= Installing {prod} using storage classes

:context: installing-che-using-storage-classes

{prod} has two components which require Persistent Volumes to store data:
 * a PostgreSQL database.
 * an {prod} workspaces. {prod} workspaces store source code using volumes, for example `/projects` volume.

[NOTE]
====
Source code is stored in the Persistent Volume only if workspace is not ephemeral.
====

{prod} does not create Persisted Volumes in the infrastructure. {prod} uses Persisted Volume Claims (PVC) to mount Persisted Volumes. {prod} server creates Persisted Volume Claims.
You can define storage class name in the {prod} configuration to use storage classes feature in the {prod} PVC. With storage classes, you can configure infrastructure storage in a flexible way with many storage parameters. You can also bind static provisioned Persisted Volumes to {prod} PVC using class name.

.Procedure

== Defining storage class names with the `server:start command`

* To provide storage class name for PostgreSQL PVC, use the `{prod-cli}` `server:start` command with the `--postgres-pvc-storage-class-name` flag:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start -m -p minikube -a operator --postgres-pvc-storage-class-name=postgress-storage
----

* To provide storage class name for {prod-short} workspaces, use the `server:start` command with the `--workspace-pvc-storage-class-name` flag:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start -m -p minikube -a operator --workspace-pvc-storage-class-name=workspace-storage
----

For {prod} workspaces, storage class name has different behavior depending on a workspace PVC strategy.

[NOTE]
====
`postgres-pvc-storage-class-name=postgress-storage` and `workspace-pvc-storage-class-name` work for the Operator installer and the Helm installer.
====

== Defining storage class names using a custom resources YAML file
You can define storage classes names using {prod} custom resources definition YAML.

.Procedure

.  Create a YAML file with custom resources defined for the {prod} installation.
.  Define fields: `spec#storage#postgresPVCStorageClassName` and `spec#storage#workspacePVCStorageClassName`.
+
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  # ...
  storage:
    # ...
    # keep blank unless you need to use a non default storage class for PostgreSQL PVC
    postgresPVCStorageClassName: 'postgres-storage'
    # ...
    # keep blank unless you need to use a non default storage class for workspace PVC(s)
    workspacePVCStorageClassName: 'workspace-storage'
    # ...
----

. Start the {prod-id-short} server with your custom resources:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start -m -p minikube -a operator --che-operator-cr-yaml=/path/to/custom/che/resource/org_v1_che_cr.yaml
----

== Binding static provisioned volumes

Administrators can provision Persisted Volumes using class names.

.Procedure

. Define Persistent Volume for a PostgreSQL database:
+
[source,yaml]
----
# che-postgres-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/che/postgres"
----

. Define Persistent Volume for a {prod-short} workspace:
+
[source,yaml]
----
# che-workspace-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv-volume
  labels:
    type: local
spec:
  storageClassName: workspace-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/che/workspace"
----

. Bind the two Persisted Volumes:
[subs="+quotes,+attributes"]
----
$ kubectl apply -f che-workspace-pv.yaml -f che-postgres-pv.yaml
----

[NOTE]
====
You must provide valid file permissions for volumes. You can do it using storage class configuration or manually. To manually define permission, define `storageClass#mountOptions` `uid` and `gid`. PostgreSQL volume requires `uid=26` and `gid=26`.
====

== Configuring {prod} to store workspaces in one Persisted Volume

.Procedure

To configure {prod} to store all workspaces in one Persisted Volume:

. Modify your custom resources YAML file:

* Set `pvcStrategy` as `common`.

* Configure {prod-short} to start workspaces in the single namespace.

* Define storage class names for `postgresPVCStorageClassName` and `workspacePVCStorageClassName`.

* Example of the YAML file:
+
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    # ...
    workspaceNamespaceDefault: 'che'
    # ...
  storage:
    # ...
    # Defaults to common
    pvcStrategy: 'common'
    # ...
    # keep blank unless you need to use a non default storage class for PostgreSQL PVC
    postgresPVCStorageClassName: 'postgres-storage'
    # ...
    # keep blank unless you need to use a non default storage class for workspace PVC(s)
    workspacePVCStorageClassName: 'workspace-storage'
    # ...
----

. Start the {prod-id-short} server with your custom resources:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start -m -p minikube -a operator --che-operator-cr-yaml=/path/to/custom/che/resource/org_v1_che_cr.yaml
----
