// Module included in the following assemblies:
//
// installing-{prod-id-short}-on-openshift-4-from-operatorhub

[id="viewing-the-state-of-the-{prod-id-short}-cluster-deployment-using-openshift-4-cli-tools_{context}"]
= Viewing the state of the {prod-short} cluster deployment using OpenShift 4 CLI tools

This section describes how to view the state of the {prod-short} cluster deployment using OpenShift 4 CLI tools.

.Prerequisites

* An installation of an {prod} cluster. See xref:installing-{prod-id-short}-using-the-{prod-id-short}-operator-in-openshift-4-web-console_{context}[].

.Procedure

. Run the following commands to select the `{project-context}` project:
+
[subs="+quotes"]
----
$ oc project _<project_name>_
----

. Run the following commands to get the name and status of the Pods running in the selected project:
+
----
$ oc get pods
----

. Check that the status of all the Pods is `Running`.
+
[subs="+attributes",options="nowrap",role=white-space-pre]
----
NAME                            READY     STATUS    RESTARTS   AGE
{prod-deployment}-8495f4946b-jrzdc            0/1       Running   0          86s
{prod-operator}-578765d954-99szc   1/1       Running   0          42m
keycloak-74fbfb9654-g9vp5       1/1       Running   0          4m32s
postgres-5d579c6847-w6wx5       1/1       Running   0          5m14s
----

. To see the state of the {prod-short} cluster deployment, run:
+
[subs="+attributes",options="nowrap",role=white-space-pre]
----
$ oc logs --tail=10 -f `oc get pods -o name | grep operator`
----
+
Example output of the command:
+
[options="nowrap",role="white-space-pre",subs="+quotes,+attributes"]
----
include::examples/{project-context}-cluster-deployment-openshift-logs.adoc[]
----
