// Module included in the following assemblies:
//
// installing-{prod-id-short}-on-google-cloud-platform
// preparing-google-cloud-platform-for-installing-che

[id="creating-a-google-kubernetes-engine-instance_{context}"]
= Creating a Google Kubernetes Engine instance

This section describes how to create a Google Kubernetes Engine instance.


.Prerequisites

* The Google Cloud SDK is available. See link:https://cloud.google.com/sdk/install[Installing Google Cloud SDK].
+
[TIP]
====
To install the SDK on macOS, use the `$ brew cask install google-cloud-sdk` command.
====

.Procedure

. Ensure `gcloud` CLI is setup
+
----
$ gcloud init
----

. Create a new project with the `eclipse-che-1` ID
+
----
$ gcloud projects create eclipse-che-1
----

. Check from GCP webconsole kubernetes engine is available on this project
+
. Configure the different default options (such as using the `europe-west1-b` zone) in the shell:
+
----
$ gcloud config set project eclipse-che-1
$ gcloud config set compute/zone europe-west1-b
$ gcloud config set compute/region europe-west1
----

. Check if all the components are up-to-date:
+
----
$ gcloud components update
All components are up to date.
----

. Create a cluster with the name `eclipse-che`:
+
----
$ gcloud container clusters create eclipse-che --zone europe-west1-b
----

. Wait for the cluster to be ready.

. This commands updates the Kubernetes context. To verify it:
+
----
$ kubectl config current-context
gke_eclipse-che-1_europe-west1-b_eclipse-che
----
