// Module included in the following assemblies:
//
// installing-{prod-id-short}-on-minishift

[id="adding-self-signed-certificates-to-minishift"]
= Adding self-signed certificates to Minishift

This section describes how to add user-generated certificates to a Minishift cluster.

NOTE: This method involves reconfiguration of the OpenShift router to use user-provided TLS certificates.

.Prerequisites

* A running OpenShift 3 instance, version 3.11 or higher.
* All required keys and certificates. See xref:generating-self-signed-tls-certificates_{context}[].

.Procedure

. Log in to the default OpenShift project:
+
----
$ oc login -u system:admin --insecure-skip-tls-verify=true
$ oc project default
----

. Reconfigure the router with the generated certificate:
+
[subs="+quotes,+attributes"]
----
$ oc delete secret router-certs
$ cat domain.crt domain.key > openshift.crt
$ oc create secret tls router-certs --key=domain.key --cert=openshift.crt
$ oc rollout latest router
----

. Create a {orch-namespace} for {prod-short}:
+
[subs="+quotes,+attributes"]
----
$ oc create namespace {prod-namespace}
----

. Create a secret from the CA certificate:
+
[subs="+quotes,+attributes"]
----
$ oc create secret generic self-signed-certificate --from-file=ca.crt -n={prod-namespace}
----

.Additional resources

* xref:importing-self-signed-tls-certificates-to-browsers_{context}[]
