// Module included in the following assemblies:
//
// installing-{prod-id-short}-with-kubespray

[id="installing-{prod-id-short}-on-kubespray-using-{prod-cli}_{context}"]
= Installing che on Kubespray using {prod-cli}

.Prerequisites

* A running Kubernetes cluster set up with Kubespray on bare metal. See xref:using-kubespray-to-set-up-kubernetes_{context}[].
* A load balancer is running on your cluster. See xref:installing-a-load-balancer-on-bare-metal-cluster_{context}[].
* A storage is defined with a provisioner. See xref:installing-a-storage-on-bare-metal-cluster_{context}[].
* `{prod-cli}` management tool is installed. See xref:installing-the-{prod-cli}-management-tool_{context}[].

.Procedure

* Deploy an ingress controller
+
We will use nginx for that, get the __cloud__ deployment since you have configured a load balancer!
+
----
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml
----

* Get the IP attributed by the load balancer
+
----
$ kubectl get svc -n ingress-nginx
----
+
It corresponds to the `EXTERNAL-IP` of the `ingress-nginx-controller` service. We will refer it as <ip-from-load-balancer>.

* Run the following command:
+
[subs="+attributes"]
----
$ {prod-cli} server:start --platform k8s --domain <ip-from-load-balancer>.nip.io --self-signed-cert
----
+
[TIP]
====
Unless you provide a certificate, don't forget the __self-signed-cert__ flag
====
