[id="installing-the-che-operator-in-openshift-4-web-console_{context}"]
= Installing the Che Operator in OpenShift 4 web console

This section describes how to install the Che Operator in OpenShift 4 web console.

[discrete]
== Prerequisites

* An administrator account on a running instance of OpenShift 4.

* Administrative rights on an existing project named `che` on this instance of OpenShift 4.
See xref:creating-the-che-project-in-openshift-4-web-console_{context}[].

* The Eclipse Che 6 Operator is not installed.

[discrete]
== Procedure

. Open the OpenShift web console.

. In the left panel, navigate to the *Operators* -> *OperatorHub* section.

. In the *Search by keyword* field, type `Eclipse Che`.

. Click on the *Eclipse Che* tile.

. Click the btn:[Install] button in the *Eclipse Che* pop-up window.

. In the *A specific namespace on the cluster* field, in the cluster drop-down list, select *che*. 

. Click the btn:[Subscribe] button.

. In the left panel, navigate to the *Operators* -> *Installed Operators* section.

. Eclipse Che is displayed as an installed Operator having the *InstallSucceeded* status.

. Click on the *Eclipse Che* name in the list of installed operators.

. Navigate to the *Overview* tab.

. In the *Conditions* sections at the bottom of the page, wait for this message: `install strategy completed with no errors`.

. Navigate to the *Events* tab.

. Wait for this message: `install strategy completed with no errors`.
