// Module included in the following assemblies:
//
// installing-{prod-id-short}-on-openshift-4-from-operatorhub

[id="finding-{prod-id-short}-cluster-url-using-openshift-4-cli-tools_{context}"]
= Finding {prod-short} cluster URL using the OpenShift 4 CLI
This section describes how to obtain the {prod-short} cluster URL using the OpenShift 4 CLI (command line interface). The URL can be retrieved from the OpenShift logs or from the `checluster` Custom Resource.
.Prerequisites
* {prod-short} is deployed in an OpenShift cluster. To verify the state of the deployment, see xref:viewing-the-state-of-the-{prod-id-short}-cluster-deployment-using-openshift-4-cli-tools_{context}[].
* User is located in a {prod-short} installation namespace.
.Procedure
. To retrieve a {prod-short} cluster URL from the `checluster` CR (Custom Resource), run:
+
[options="nowrap",role=white-space-pre]
----
$ oc get checluster --output jsonpath='{.items[0].status.cheURL}'
----
. The {prod-short} cluster URL is displayed.

Alternatively, wait for the deployment logs as mentioned in the Prerequisites section to display the message: `{prod} is now available at:` followed by the {prod-short} cluster URL:
+
[subs="+attributes",options="nowrap",role=white-space-pre]
----
include::examples/{project-context}-cluster-url-logs.adoc[]
----
+
After the deployment is finished, in the log output, click the {prod-short} cluster URL to start the {prod-short} instance, or use the following command to isolate it:
+
[options="nowrap",role=white-space-pre]
----
$ oc logs --tail=10 `oc get pods -o name | grep operator` | \
  grep "available at" | \
  awk -F'available at: ' '{print $2}' | sed 's/"//'
----
