[id="installing-the-chectl-management-tool-on-linux-or-macos_{context}"]
= Installing the chectl management tool on Linux or MacOS

This section describes how to install the chectl management tool on Linux or MacOS.

[discrete]
== Prerequisites

* The directory `/usr/local/bin` is in the user `$PATH`.

* The `sudo` command is configured for the current user.

* Remove all old or undesired versions of `chectl`.

[discrete]
== Procedure

. Run the following command in the terminal (this downloads and executes the `install.sh` script):
+
----
$ bash <(curl -sL  https://www.eclipse.org/che/chectl/)
----

. Run the following command to verify that the `chectl` binary used is `/usr/local/bin/chectl`:
+
----
$ which chectl
/usr/local/bin/chectl
----
+

. Run the following command to verify that the version of chectl that is the expected one.
+
----
$ chectl --version
----
+
[TIP]
====
To identify the latest stable release, see the link:https://github.com/che-incubator/chectl/releases[list of chectl releases] and search for a release not containing "next" in the name.
====

. Read the installation logs.
+
----
$ cat chectl-install.log
----

[discrete]
== Additional resources

* link:#upgrading-the-chectl-management-tool_{context}[Upgrading the `chectl` management tool]

* link:https://github.com/che-incubator/chectl/blob/master/README.md[`chectl` README]
