[id='{prod-id-short}-known-issues']
= {prod-short} {prod-ver}.3 known issues

This section contains information about selected existing issues known at the time of the {prod} 7.3 release that affect user experience.

== Permission denied errors when installing {prod} in the default namespace

When installing {prod} in the `default` namespace, the proper security contexts and file permissions are not set appropriately, causing the installation to fail.  Users should avoid installing {prod} in the `default` namespace and instead create a new namespace, for example, `che`, to contain the {prod} installation.

Issue: link:https://github.com/eclipse/che/issues/14426[]


== Language-support plug-ins potential malfunction

Some language-support plug-ins (in particular Java, Python, and C#) may experience issues detecting newly cloned projects. When experiencing problems with features such as code assist, try refreshing the page in the browser (press kbd:[F5]).

Issue: link:https://github.com/eclipse/che/issues/13427[]


== Bright fonts are not set in dark theme in Firefox

When using the {prod} dark theme in Firefox, workspace content is rendered using a black-color font. This makes the content unreadable.

Issue: link:https://github.com/eclipse/che/issues/13442[]


== Other issues

* link:https://github.com/eclipse/che/issues/13717[Prevent Operator removal while it still has some CRs to manage]

See the full list of link:https://github.com/eclipse/che/issues?&q=is%3Aopen+is%3Aissue+label%3Atarget%2Fche7+label%3Akind%2Fbug[{prod-short} {prod-ver} issues on GitHub].
