// Module included in the following assemblies:
//
// hosted-che
:page-liquid:

[id="about-hosted-che_{context}"]
= About Hosted Che

Hosted Che is link:https://www.eclipse.org/che/[Eclipse {prod-short}] hosted by Red Hat.
A {prod-short} server is running on OpenShift Dedicated, and the user base is spread across multiple OpenShift Online clusters where workspaces are created.

[id="terms-of-service_{context}"]
== Terms of service

Hosted Che has the following usage limits and terms of service:

* Storage: 2 GB
* RAM: 7 GB
* Concurrent workspaces: 1
* Number of workspaces: Unlimited
* Number of projects per workspace: Unlimited
* Usage time limit: None
* Maximum account inactivity period: 30 days
+
NOTE: Hosted Che automatically deactivates accounts that have been inactive for more than 30 days. All existing workspaces in a deactivated account are lost. To start using Hosted Che again, a user must re-register.

* Workspace idling time: 15 minutes
+
NOTE: A started workspace can be used for an unlimited period of time. When there are no interactions with the IDE, the workspace is stopped after 15 minutes.

* Temporary Storage: Defaults to *Active*
+
NOTE: In the temporary storage mode, workspaces have no persistent storage attached. All content changes are lost when the workspace is stopped unless they are pushed to a source-code repository first. This is done to improve the performance of workspace starts and file-system operations in the IDE.

It is possible to disable the temporary storage mode while xref:creating-a-worskpace-from-the-user-dashboard_hosted-che[creating a workspace from the user dashboard]. For more information about the temporary storage mode, including how to disable it after workspace creation, see link:{site-baseurl}che-7/workspaces-overview[Using developer environments - workspaces].
