[id="{prod-id-short}-known-issues_{context}"]
= {prod-short} {prod-ver} known issues

This section contains information about selected existing issues known at the time of the {prod} {prod-ver} release that affect user experience.

== Permission denied errors when installing {prod} in the default namespace

When installing {prod} in the `default` namespace, the proper security contexts and file permissions are not set appropriately, causing the installation to fail. Recommendation: do not install {prod-short} in the `default` namespace. Instead, create a new namespace, for example, `{project-context}`, to contain the {prod-short} installation.

Issue description: link:https://github.com/eclipse/che/issues/14426[]

== Language-support plug-ins potential malfunction

Some language-support plug-ins (in particular Java, Python, and C#) may experience issues detecting newly cloned projects. When experiencing problems with features such as code assist, try refreshing the page in the browser (press kbd:[F5]).

Issue description: link:https://github.com/eclipse/che/issues/13427[]

== Bright fonts are not set in dark theme in Firefox

When using the {prod} dark theme in Firefox, workspace content is rendered using a black-color font. This makes the content unreadable.

Issue description: link:https://github.com/eclipse/che/issues/13442[]

== Problems opening workspace in newest Chrome versions on non-TLS installations on distributed clusters

When {prod} is installed in a non-TLS (for example HTTP) mode and, at the same time, on a distributed cluster where the host names of {prod-short} server and workspace routes are different, latest Chrome versions may reject to open workspaces due to limitations in using `SameSite` and `Secure` policies of auth cookies set by JWTProxy.

Issue description: link:https://github.com/eclipse/che/issues/16384[]

== Workspace start failures when StorageClass configured with `volumeBindingMode` set to `WaitForFirstConsumer` on OpenShift older than 4.2

When {prod} is installed on OpenShift older than 4.2, and StorageClass is configured with the `volumeBindingMode` property set to `WaitForFirstConsumer`, workspaces may fail to start with a `Unrecoverable event occurred: 'FailedScheduling'` message.

To work around the issue, use one the following:

* Reconfigure {prod} and remove `FailedScheduling` from the `che.infra.kubernetes.workspace_unrecoverable_events` property value (in the `che.properties` file or deployment configuration)
* Upgrade the OpenShift installation to version 4.2 or higher.

Issue description: link:https://github.com/eclipse/che/issues/14670[]

== Other issues

* link:https://github.com/eclipse/che/issues/13717[Prevent Operator removal while it still has some CRs to manage].

See the full list of link:https://github.com/eclipse/che/issues?&q=is%3Aopen+is%3Aissue+label%3Atarget%2Fche7+label%3Akind%2Fbug[{prod-short} {prod-ver} issues on GitHub].
