:_content-type: PROCEDURE

[id="configuring-number-of-replicas"]
= Scale {prod-short} for high availability

Scale {prod-short} for high availability by defining a {kubernetes} `HorizontalPodAutoscaler` (HPA) resource for {prod-short} operands. The HPA dynamically adjusts the number of replicas based on specified metrics.

.Procedure

. Create an `HPA` resource for a deployment, specifying the target metrics and desired replica count.
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaler
  namespace: {prod-namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: __<deployment_name>__
  ...
----
+
where:
+
`__<deployment_name>__`:: One of the following deployments:
+
* `{prod-deployment}`
* `che-gateway`
* `{prod-deployment}-dashboard`
* `plugin-registry`
* `devfile-registry`
+
For example:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {prod-deployment}-scaler
  namespace: {prod-namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {prod-deployment}
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
----
+
In this example, the HPA targets the `{prod-deployment}` deployment with a minimum of 2 replicas, a maximum of 5 replicas, and scales based on CPU utilization.

.Verification

* Verify that the HPA resource is created and targeting the correct deployment:
+
[source,shell,subs="+quotes,+attributes"]
----
{orch-cli} get hpa -n {prod-namespace}
----

.Additional resources
* link:https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale[Horizontal Pod Autoscaling]
