:_content-type: PROCEDURE
:description: View language server and debug adapter logs in the editor
:keywords: administration-guide, logs
:navtitle: View language server and debug adapter logs in the editor
:page-aliases: end-user-guide:viewing-language-servers-and-debug-adapters-logs-in-visual-studio-code.adoc

[id="viewing-language-servers-and-debug-adapters-logs-in-visual-studio-code"]
= View language server and debug adapter logs in the editor


View language server and debug adapter logs in the Microsoft Visual Studio Code - Open Source editor to diagnose extension issues.


.Prerequisites
* You have a running {prod-short} workspace with Microsoft Visual Studio Code - Open Source as the editor.
* You have a language server or debug adapter extension installed in the editor.

.Procedure
. Configure the extension: click *File* > *Preferences* > *Settings*, expand the *Extensions* section, search for your extension, and set the `trace.server` or similar configuration to `verbose`, if such configuration exists.
Refer to the extension documentation for further configuration.

. View your language server logs by clicking *View* > *Output*, and selecting your language server in the drop-down list for the Output view.

.Verification
* The *Output* view displays language server or debug adapter log messages.

.Additional resources
* link:https://open-vsx.org/[Open VSX registry]
