:_content-type: REFERENCE
:description: Cloud Development Environment logs
:keywords: administration-guide, viewing-che-workspaces-logs
:navtitle: Cloud Development Environment logs
:page-aliases: .:viewing-che-workspaces-logs.adoc, administration-guide:viewing-che-workspaces-logs.adoc

[id="viewing-{prod-id-short}-workspaces-logs"]
= Cloud Development Environment logs


View {prod-short} workspace logs to diagnose startup failures, debug misbehaving extensions, and identify memory issues.

An IDE extension misbehaves or needs debugging::
The logs list the plugins that have been loaded by the editor.

The container runs out of memory::
The logs contain an `OOMKilled` error message.
Processes running in the container attempted to request more memory than is configured to be available to the container.

A process runs out of memory::
The logs contain an error message such as `OutOfMemoryException`.
A process inside the container ran out of memory without the container noticing.


.Additional resources
* xref:viewing-workspace-logs-in-cli.adoc[]
* xref:viewing-workspace-logs-in-the-openshift-console.adoc[]
* xref:viewing-language-servers-and-debug-adapters-logs-in-visual-studio-code.adoc[]
