extends: substitution
message: "Use '%s' rather than '%s'."
ignorecase: false
level: error
action:
  name: replace
source: Red Hat
swap:
  '[nN]odejs|[nN]ode\.JS|node\.js': Node.js
  "Operator [hH]ub|[oO]peratorhub": OperatorHub
  "Spring boot": Spring Boot
  "VS Code|VSCode|VisualStudioCode|VisualStudio Code": Visual Studio Code
  "podman": Podman
