// Module included in the following assemblies:
//
// supported_platforms

[id="supported-platforms-and-installation-methods_{context}"]
= Supported platforms and installation methods

The following section provides information about the availability of {prod-short} {prod-ver} on Kubernetes and OpenShift infrastructures, and about their supported installation methods.

{prod} can be installed on:

* Kubernetes infrastructures starting at version 1.9
* {ocp} versions 3.11, 4.3, and 4.4

The following options are available:

.Local installation on Kubernetes
[options="header",cols="2*.^"]
|===
|Kubernetes
|Installation method

a|* minikube
* microk8s
* docker-desktop
* kind
|`{prod-cli}` using Helm Chart or Operator
|===

.Local installation on OpenShift
[options="header",cols="2,2"]
|===
|{ocp}
|Installation method

|CodeReady Containers
|OperatorHub
|===

.Public cloud installation on Kubernetes and OpenShift
[options="header",cols="25,25,25,25"]
|===
|
|Kubernetes +
1.9 or higher
|{ocp} +
3.11
|{ocp} +
4.3 and 4.4

a|* Microsoft Azure
* Amazon Web Services
* Google Cloud
* IBM Cloud
.^|`{prod-cli}` using Helm Chart
.^|`{prod-cli}` using Operator
.^|OperatorHub
|===

It is possible to use the `{prod-cli}` utility for deploying {prod-short} on {ocp} version 4.3 and 4.4. This method is considered unofficial and serves as a backup installation method for situations where installation using OperatorHub is not available.

////
Starting with the {prod-short} version 7.14, the `{prod-cli}` acts as secondary supported and official installation method that serves also as an backup installation method for situations where the installation method using OperatorHub is not available.
////

.Additional resources

*  Installation instructions: link:{site-baseurl}che-7/che-quick-starts/[{prod-short} 'quick-starts']
