[id="building-{registry-mode}-{registry-id}-registry-image_{context}"]
= Building {registry-mode-name} {registry-name} registry image

This section describes how to build {registry-mode-name} {registry-name} registry image.
ifeval::["{registry-mode}" == "offline"]
Starting workspaces without relying on resources from the outside Internet requires building this image.
ifeval::["{registry-id}" == "devfile"]
The image contains all sample projects referenced in devfiles as `zip` files.
endif::[]
ifeval::["{registry-id}" == "plugin"]
The image contains plug-in metadata and all plug-in or extension artifacts. 
endif::[]
endif::[]
ifeval::["{registry-mode}" == "custom"]
The procedure explains how to add a new {registry-name}.
ifeval::["{registry-id}" == "devfile"]
The image contains all sample projects referenced in devfiles.
endif::[]
ifeval::["{registry-id}" == "plugin"]
The image contains plug-ins or extensions metadata. 
endif::[]
endif::[]


.Procedure

. Clone the {registry-name} registry repository and check out the version to deploy:
+
[subs="+attributes,+quotes"]
----
include::snip_{project-context}-clone-the-registry-repository.adoc[]
----

ifeval::["{registry-mode}" == "custom"]
include::contributor-guide:example$snip_customizing-the-{registry-name}-registry.adoc[]
endif::[]

. Build {registry-mode-name} {registry-name} registry image:
+
[subs="+quotes"]
----
include::snip_{project-context}-build-a-registry.adoc[]
----
+
[TIP]
====
To display full options for the `build.sh` script, use the `--help` parameter.
ifeval::["{registry-mode}" == "custom"]
ifeval::["{registry-id}" == "plugin"]

To include the plug-in binaries in the registry image, add the `--offline` parameter.
endif::[]
endif::[]
====

