pass:[<!-- vale off -->]

[id="{prod-id-short}-server"]
= {prod-short} server

.{prod-short} server 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_API+`,"`+http://${CHE_HOST}:${CHE_PORT}/api+`","API service. Browsers initiate REST communications to {prod-short} server with this URL." 
 `+CHE_API_INTERNAL+`,"`+NULL+`","API service internal network URL. Back-end services should initiate REST communications to {prod-short} server with this URL" 
 `+CHE_WEBSOCKET_ENDPOINT+`,"`+ws://${CHE_HOST}:${CHE_PORT}/api/websocket+`","{prod-short} WebSocket major endpoint. Provides basic communication endpoint for major WebSocket interactions and messaging." 
 `+CHE_WEBSOCKET_INTERNAL_ENDPOINT+`,"`+NULL+`","{prod-short} WebSocket major internal endpoint. Provides basic communication endpoint for major WebSocket interactions and messaging." 
 `+CHE_WORKSPACE_PROJECTS_STORAGE+`,"`+/projects+`","Your projects are synchronized from the {prod-short} server into the machine running each workspace. This is the directory in the machine where your projects are placed." 
 `+CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE+`,"`+1Gi+`","Used when {orch-name}-type components in a devfile request project PVC creation (Applied in case of `unique` and `per workspace` PVC strategy. In case of the `common` PVC strategy, it is rewritten with the value of the `che.infra.kubernetes.pvc.quantity` property.)" 
 `+CHE_WORKSPACE_LOGS_ROOT__DIR+`,"`+/workspace_logs+`","Defines the directory inside the machine where all the workspace logs are placed. Provide this value into the machine, for example, as an environment variable. This is to ensure that agent developers can use this directory to back up agent logs." 
 `+CHE_WORKSPACE_HTTP__PROXY+`,"","Configures environment variable HTTP_PROXY to a specified value in containers powering workspaces." 
 `+CHE_WORKSPACE_HTTPS__PROXY+`,"","Configures environment variable HTTPS_PROXY to a specified value in containers powering workspaces." 
 `+CHE_WORKSPACE_NO__PROXY+`,"","Configures environment variable NO_PROXY to a specified value in containers powering workspaces." 
 `+CHE_WORKSPACE_AUTO__START+`,"`+true+`","By default, when users access a workspace with its URL, the workspace automatically starts (if currently stopped). Set this to `false` to disable this behavior." 
 `+CHE_WORKSPACE_POOL_TYPE+`,"`+fixed+`","Workspace threads pool configuration. This pool is used for workspace-related operations that require asynchronous execution, for example, starting and stopping. Possible values are `fixed` and `cached`." 
 `+CHE_WORKSPACE_POOL_EXACT__SIZE+`,"`+30+`","This property is ignored when pool type is different from `fixed`. It configures the exact size of the pool. When set, the `multiplier` property is ignored. If this property is not set (`0`, `<0`, `NULL`), then the pool size equals the number of cores. See also `che.workspace.pool.cores_multiplier`." 
 `+CHE_WORKSPACE_POOL_CORES__MULTIPLIER+`,"`+2+`","This property is ignored when pool type is not set to `fixed`, `che.workspace.pool.exact_size` is set. When set, the pool size is `N_CORES * multiplier`." 
 `+CHE_WORKSPACE_PROBE__POOL__SIZE+`,"`+10+`","This property specifies how many threads to use for workspace server liveness probes." 
 `+CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS+`,"`+NULL+`","HTTP proxy setting for workspace JVM." 
 `+CHE_WORKSPACE_JAVA__OPTIONS+`,"`+-XX:MaxRAM=150m-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom+`","Java command-line options added to JVMs running in workspaces." 
 `+CHE_WORKSPACE_MAVEN__OPTIONS+`,"`+-XX:MaxRAM=150m-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom+`","Maven command-line options added to JVMs running agents in workspaces." 
 `+CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB+`,"`+1024+`","RAM limit default for each machine that has no RAM settings in its environment. Value less or equal to 0 is interpreted as disabling the limit." 
 `+CHE_WORKSPACE_DEFAULT__MEMORY__REQUEST__MB+`,"`+200+`","RAM request for each container that has no explicit RAM settings in its environment. This amount is allocated when the workspace container is created. This property may not be supported by all infrastructure implementations. Currently it is supported by {orch-name}. A memory request exceeding the memory limit is ignored, and only the limit size is used. Value less or equal to 0 is interpreted as disabling the limit." 
 `+CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES+`,"`+-1+`","CPU limit for each container that has no CPU settings in its environment. Specify either in floating point cores number, for example, `0.125`, or using the Kubernetes format, integer millicores, for example, `125m`. Value less or equal to 0 is interpreted as disabling the limit." 
 `+CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES+`,"`+-1+`","CPU request for each container that has no CPU settings in environment. A CPU request exceeding the CPU limit is ignored, and only limit number is used. Value less or equal to 0 is interpreted as disabling the limit." 
 `+CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB+`,"`+128+`","RAM limit for each sidecar that has no RAM settings in the {prod-short} plug-in configuration. Value less or equal to 0 is interpreted as disabling the limit." 
 `+CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__REQUEST__MB+`,"`+64+`","RAM request for each sidecar that has no RAM settings in the {prod-short} plug-in configuration." 
 `+CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES+`,"`+-1+`","CPU limit default for each sidecar that has no CPU settings in the {prod-short} plug-in configuration. Specify either in floating point cores number, for example, `0.125`, or using the Kubernetes format, integer millicores, for example, `125m`. Value less or equal to 0 is interpreted as disabling the limit." 
 `+CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES+`,"`+-1+`","CPU request default for each sidecar that has no CPU settings in the {prod-short} plug-in configuration. Specify either in floating point cores number, for example, `0.125`, or using the Kubernetes format, integer millicores, for example, `125m`." 
 `+CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY+`,"`+Always+`","Defines image-pulling strategy for sidecars. Possible values are: `Always`, `Never`, `IfNotPresent`. For any other value, `Always` is assumed for images with the `:latest` tag, or `IfNotPresent` for all other cases." 
 `+CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__PERIOD__S+`,"`+60+`","Period of inactive workspaces suspend job execution." 
 `+CHE_WORKSPACE_ACTIVITY__CLEANUP__SCHEDULER__PERIOD__S+`,"`+3600+`","The period of the cleanup of the activity table. The activity table can contain invalid or stale data if some unforeseen errors happen, as a server failure at a peculiar point in time. The default is to run the cleanup job every hour." 
 `+CHE_WORKSPACE_ACTIVITY__CLEANUP__SCHEDULER__INITIAL__DELAY__S+`,"`+60+`","The delay after server startup to start the first activity clean up job." 
 `+CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__DELAY__S+`,"`+180+`","Delay before first workspace idleness check job started to avoid mass suspend if {prod-short} server was unavailable for period close to inactivity timeout." 
 `+CHE_WORKSPACE_CLEANUP__TEMPORARY__INITIAL__DELAY__MIN+`,"`+5+`","Time to delay the first execution of temporary workspaces cleanup job." 
 `+CHE_WORKSPACE_CLEANUP__TEMPORARY__PERIOD__MIN+`,"`+180+`","Time to delay between the termination of one execution and the commencement of the next execution of temporary workspaces cleanup job" 
 `+CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD+`,"`+1+`","Number of sequential successful pings to server after which it is treated as available. the {prod-short} Operator: the property is common for all servers, for example, workspace agent, terminal, exec." 
 `+CHE_WORKSPACE_SERVER_PING__INTERVAL__MILLISECONDS+`,"`+3000+`","Interval, in milliseconds, between successive pings to workspace server." 
 `+CHE_WORKSPACE_SERVER_LIVENESS__PROBES+`,"`+wsagent/http,exec-agent/http,terminal,theia,jupyter,dirigible,cloud-shell,intellij+`","List of servers names which require liveness probes" 
 `+CHE_WORKSPACE_STARTUP__DEBUG__LOG__LIMIT__BYTES+`,"`+10485760+`","Limit size of the logs collected from single container that can be observed by che-server when debugging workspace startup. default 10MB=10485760" 
 `+CHE_WORKSPACE_STOP_ROLE_ENABLED+`,"`+true+`","If true, 'stop-workspace' role with the edit privileges will be granted to the 'che' ServiceAccount if OpenShift OAuth is enabled. This configuration is mainly required for workspace idling when the OpenShift OAuth is enabled." 
 `+CHE_DEVWORKSPACES_ENABLED+`,"`+false+`","Specifies whether {prod-short} is deployed with DevWorkspaces enabled. This property is set by the {prod-short} Operator if it also installed the support for DevWorkspaces. This property is used to advertise this fact to the {prod-short} dashboard. It does not make sense to change the value of this property manually." 
,=== 

[id="authentication-parameters"]
= Authentication parameters

.Authentication parameters 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_AUTH_USER__SELF__CREATION+`,"`+false+`","{prod-short} has a single identity implementation, so this does not change the user experience. If true, enables user creation at API level" 
 `+CHE_AUTH_ACCESS__DENIED__ERROR__PAGE+`,"`+/error-oauth+`","Authentication error page address" 
 `+CHE_AUTH_RESERVED__USER__NAMES+`,"","Reserved user names" 
 `+CHE_OAUTH2_GITHUB_CLIENTID__FILEPATH+`,"`+NULL+`","Configuration of GitHub OAuth2 client. Used to obtain Personal access tokens. Location of the file with GitHub client id." 
 `+CHE_OAUTH2_GITHUB_CLIENTSECRET__FILEPATH+`,"`+NULL+`","Location of the file with GitHub client secret." 
 `+CHE_OAUTH_GITHUB_AUTHURI+`,"`+https://github.com/login/oauth/authorize+`","GitHub OAuth authorization URI." 
 `+CHE_OAUTH_GITHUB_TOKENURI+`,"`+https://github.com/login/oauth/access_token+`","GitHub OAuth token URI." 
 `+CHE_OAUTH_GITHUB_REDIRECTURIS+`,"`+http://localhost:${CHE_PORT}/api/oauth/callback+`","GitHub OAuth redirect URIs. Separate multiple values with comma, for example: URI,URI,URI" 
 `+CHE_OAUTH_OPENSHIFT_CLIENTID+`,"`+NULL+`","Configuration of OpenShift OAuth client. Used to obtain OpenShift OAuth token. OpenShift OAuth client ID." 
 `+CHE_OAUTH_OPENSHIFT_CLIENTSECRET+`,"`+NULL+`","Configurationof OpenShift OAuth client. Used to obtain OpenShift OAuth token. OpenShift OAuth client ID. OpenShift OAuth client secret." 
 `+CHE_OAUTH_OPENSHIFT_OAUTH__ENDPOINT+`,"`+NULL+`","ConfigurationofOpenShift OAuth client. Used to obtain OpenShift OAuth token. OpenShift OAuth client ID. OpenShift OAuth client secret. OpenShift OAuth endpoint." 
 `+CHE_OAUTH_OPENSHIFT_VERIFY__TOKEN__URL+`,"`+NULL+`","ConfigurationofOpenShiftOAuth client. Used to obtain OpenShift OAuth token. OpenShift OAuth client ID. OpenShift OAuth client secret. OpenShift OAuth endpoint. OpenShift OAuth verification token URL." 
 `+CHE_OAUTH1_BITBUCKET_CONSUMERKEYPATH+`,"`+NULL+`","Configuration of Bitbucket Server OAuth1 client. Used to obtain Personal access tokens. Location of the file with Bitbucket Server application consumer key (equivalent to a username)." 
 `+CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH+`,"`+NULL+`","Configurationof Bitbucket Server OAuth1 client. Used to obtain Personal access tokens. Location of the file with Bitbucket Server application consumer key (equivalent to a username). Location of the file with Bitbucket Server application private key" 
 `+CHE_OAUTH1_BITBUCKET_ENDPOINT+`,"`+NULL+`","ConfigurationofBitbucket Server OAuth1 client. Used to obtain Personal access tokens. Location of the file with Bitbucket Server application consumer key (equivalent to a username). Location of the file with Bitbucket Server application private key Bitbucket Server URL. To work correctly with factories the same URL has to be part of `che.integration.bitbucket.server_endpoints` too." 
,=== 

[id="internal"]
= Internal

.Internal 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+SCHEDULE_CORE__POOL__SIZE+`,"`+10+`","{prod-short} extensions can be scheduled executions on a time basis. This configures the size of the thread pool allocated to extensions that are launched on a recurring schedule." 
 `+DB_SCHEMA_FLYWAY_BASELINE_ENABLED+`,"`+true+`","DB initialization and migration configuration If true, ignore scripts up to the version configured by baseline.version." 
 `+DB_SCHEMA_FLYWAY_BASELINE_VERSION+`,"`+5.0.0.8.1+`","Scripts with version up to this are ignored. Note that scripts with version equal to baseline version are also ignored." 
 `+DB_SCHEMA_FLYWAY_SCRIPTS_PREFIX+`,"","Prefix of migration scripts." 
 `+DB_SCHEMA_FLYWAY_SCRIPTS_SUFFIX+`,"`+.sql+`","Suffix of migration scripts." 
 `+DB_SCHEMA_FLYWAY_SCRIPTS_VERSION__SEPARATOR+`,"`+__+`","Separator of version from the other part of script name." 
 `+DB_SCHEMA_FLYWAY_SCRIPTS_LOCATIONS+`,"`+classpath:che-schema+`","Locations where to search migration scripts." 
,=== 

[id="kubernetes-infra-parameters"]
= Kubernetes Infra parameters

.Kubernetes Infra parameters 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_INFRA_KUBERNETES_MASTER__URL+`,"","Configuration of Kubernetes client master URL that Infra will use." 
 `+CHE_INFRA_KUBERNETES_TRUST__CERTS+`,"`+false+`","Boolean to configure Kubernetes client to use trusted certificates." 
 `+CHE_INFRA_KUBERNETES_CLUSTER__DOMAIN+`,"`+NULL+`","Kubernetes cluster domain. If not set, svc names will not contain information about the cluster domain." 
 `+CHE_INFRA_KUBERNETES_SERVER__STRATEGY+`,"`+multi-host+`","Defines the way how servers are exposed to the world in Kubernetes infra. List of strategies implemented in {prod-short}: `default-host`, `multi-host`, `single-host`." 
 `+CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE+`,"`+native+`","Defines the way in which the workspace plugins and editors are exposed in the single-host mode. Supported exposures: `native`:: Exposes servers using Kubernetes Ingresses. Works only on Kubernetes. `gateway`:: Exposes servers using reverse-proxy gateway." 
 `+CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE+`,"`+multi-host+`","Defines the way how to expose devfile endpoints, as end-user's applications, in single-host server strategy. They can either follow the single-host strategy and be exposed on subpaths, or they can be exposed on subdomains. `multi-host`:: expose on subdomains `single-host`:: expose on subpaths" 
 `+CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS+`,"`+app=che,component=che-gateway-config+`","Defines labels which will be set to ConfigMaps configuring single-host gateway." 
 `+CHE_INFRA_KUBERNETES_INGRESS_DOMAIN+`,"","Used to generate domain for a server in a workspace in case property `che.infra.kubernetes.server_strategy` is set to `multi-host`" 
 `+CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED+`,"`+true+`","Indicates whether {prod-short} server is allowed to create {orch-namespace} for user workspaces, or they're intended to be created manually by cluster administrator. This property is also used by the OpenShift infra." 
 `+CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT+`,"`+<username>-che+`","Defines Kubernetes default namespace in which user's workspaces are created if user does not override it. It's possible to use `<username>` and `<userid>` placeholders (for example: `che-workspace-<username>`). In that case, new namespace will be created for each user. Used by OpenShift infra as well to specify a Project. The `<username>` or `<userid>` placeholder is mandatory." 
 `+CHE_INFRA_KUBERNETES_NAMESPACE_LABEL+`,"`+true+`","Defines whether che-server should try to label the workspace namespaces." 
 `+CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATE+`,"`+true+`","Defines whether che-server should try to annotate the workspace namespaces." 
 `+CHE_INFRA_KUBERNETES_NAMESPACE_LABELS+`,"`+app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace+`","List of labels to find {orch-namespace} that are used for {prod-short} Workspaces. They are used to:  - find prepared {orch-namespace} for users in combination with `che.infra.kubernetes.namespace.annotations`.  - actively label {orch-namespace} with any workspace." 
 `+CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS+`,"`+che.eclipse.org/username=<username>+`","List of annotations to find {orch-namespace} prepared for {prod-short} users workspaces. Only {orch-namespace} matching the `che.infra.kubernetes.namespace.labels` will be matched against these annotations. {orch-namespace} that matches both `che.infra.kubernetes.namespace.labels` and `che.infra.kubernetes.namespace.annotations` will be preferentially used for User's workspaces. It's possible to use `<username>` placeholder to specify the {orch-namespace} to concrete user. They are used to:  - find prepared {orch-namespace} for users in combination with `che.infra.kubernetes.namespace.labels`.  - actively annotate {orch-namespace} with any workspace." 
 `+CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME+`,"`+NULL+`","Defines Kubernetes Service Account name which should be specified to be bound to all workspaces Pods. the {prod-short} Operator that Kubernetes Infrastructure will not create the service account and it should exist. OpenShift infrastructure will check if project is predefined(if `che.infra.openshift.project` is not empty):  - if it is predefined then service account must exist there  - if it is 'NULL' or empty string then infrastructure will create new OpenShift project per workspace    and prepare workspace service account with needed roles there" 
 `+CHE_INFRA_KUBERNETES_WORKSPACE__SA__CLUSTER__ROLES+`,"`+NULL+`","Specifies optional, additional cluster roles to use with the workspace service account. the {prod-short} Operator that the cluster role names must already exist, and the {prod-short} service account needs to be able to create a Role Binding to associate these cluster roles with the workspace service account. The names are comma separated. This property deprecates `che.infra.kubernetes.cluster_role_name`." 
 `+CHE_INFRA_KUBERNETES_USER__CLUSTER__ROLES+`,"`+NULL+`","Cluster roles to assign to user in his namespace" 
 `+CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN+`,"`+8+`","Defines wait time that limits the Kubernetes workspace start time." 
 `+CHE_INFRA_KUBERNETES_INGRESS__START__TIMEOUT__MIN+`,"`+5+`","Defines the timeout in minutes that limits the period for which Kubernetes Ingress become ready" 
 `+CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS+`,"`+FailedMount,FailedScheduling,MountVolume.SetUpfailed,Failed to pull image,FailedCreate,ReplicaSetCreateError+`","If during workspace startup an unrecoverable event defined in the property occurs, stop the workspace immediately rather than waiting until timeout. the {prod-short} Operator that this SHOULD NOT include a mere 'Failed' reason, because that might catch events that are not unrecoverable. A failed container startup is handled explicitly by {prod-short} server." 
 `+CHE_INFRA_KUBERNETES_PVC_ENABLED+`,"`+true+`","Defines whether use the Persistent Volume Claim for {prod-short} workspace needs, for example: backup projects, logs, or disable it." 
 `+CHE_INFRA_KUBERNETES_PVC_STRATEGY+`,"`+common+`","Defined which strategy will be used while choosing PVC for workspaces. Supported strategies: `common`::        All workspaces in the same {orch-namespace} will reuse the same PVC.        Name of PVC may be configured with `che.infra.kubernetes.pvc.name`.        Existing PVC will be used or a new one will be created if it does not exist. `unique`::        Separate PVC for each workspace's volume will be used.        Name of PVC is evaluated as `'{che.infra.kubernetes.pvc.name} + '-' + \{generated_8_chars}'`.        Existing PVC will be used or a new one will be created if it does not exist. `per-workspace`::        Separate PVC for each workspace will be used.        Name of PVC is evaluated as `'{che.infra.kubernetes.pvc.name} + '-' + \{WORKSPACE_ID}'`.        Existing PVC will be used or a new one will be created if it doesn't exist." 
 `+CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS+`,"`+true+`","Defines whether to run a job that creates workspace's subpath directories in persistent volume for the `common` strategy before launching a workspace. Necessary in some versions of {orch-name} as workspace subpath volume mounts are created with root permissions, and therefore cannot be modified by workspaces running as a user (presents an error importing projects into a workspace in {prod-short}). The default is `true`, but should be set to `false` if the version of {orch-name} creates subdirectories with user permissions. See: link:https://github.com/kubernetes/kubernetes/issues/41638[subPath in volumeMount is not writable for non-root users #41638] the {prod-short} Operator that this property has effect only if the `common` PVC strategy used." 
 `+CHE_INFRA_KUBERNETES_PVC_NAME+`,"`+claim-che-workspace+`","Defines the settings of PVC name for {prod-short} workspaces. Each PVC strategy supplies this value differently. See documentation for `che.infra.kubernetes.pvc.strategy` property" 
 `+CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME+`,"","Defines the storage class of Persistent Volume Claim for the workspaces. Empty strings means 'use default'." 
 `+CHE_INFRA_KUBERNETES_PVC_QUANTITY+`,"`+10Gi+`","Defines the size of Persistent Volume Claim of {prod-short} workspace. See: link:https://docs.openshift.com/container-platform/4.4/storage/understanding-persistent-storage.html[Understanding persistent storage]" 
 `+CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE+`,"`+registry.access.redhat.com/ubi8-minimal:8.3-230+`","Pod that is launched when performing persistent volume claim maintenance jobs on OpenShift" 
 `+CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY+`,"`+IfNotPresent+`","Image pull policy of container that used for the maintenance jobs on {orch-name} cluster" 
 `+CHE_INFRA_KUBERNETES_PVC_JOBS_MEMORYLIMIT+`,"`+250Mi+`","Defines Pod memory limit for persistent volume claim maintenance jobs" 
 `+CHE_INFRA_KUBERNETES_PVC_ACCESS__MODE+`,"`+ReadWriteOnce+`","Defines Persistent Volume Claim access mode. the {prod-short} Operator that for common PVC strategy changing of access mode affects the number of simultaneously running workspaces. If the OpenShift instance running {prod-short} is using Persistent Volumes with RWX access mode, then a limit of running workspaces at the same time is bounded only by {prod-short} limits configuration: RAM, CPU, and so on. See: link:https://docs.openshift.com/container-platform/4.4/storage/understanding-persistent-storage.html[Understanding persistent storage]" 
 `+CHE_INFRA_KUBERNETES_PVC_WAIT__BOUND+`,"`+true+`","Defines if {prod-short} Server should wait workspaces Persistent Volume Claims to become bound after creating. Default value is `true`. The parameter is used by all Persistent Volume Claim strategies. It should be set to `false` when `volumeBindingMode` is configured to `WaitForFirstConsumer` otherwise workspace starts will hangs up on phase of waiting PVCs." 
 `+CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON+`,"`+NULL+`","Defines annotations for ingresses which are used for servers exposing. Value depends on the kind of ingress controller. OpenShift infrastructure ignores this property because it uses Routes rather than Ingresses. the {prod-short} Operator that for a single-host deployment strategy to work, a controller supporting URL rewriting has to be used (so that URLs can point to different servers while the servers do not need to support changing the app root). The `che.infra.kubernetes.ingress.path.rewrite_transform` property defines how the path of the ingress should be transformed to support the URL rewriting and this property defines the set of annotations on the ingress itself that instruct the chosen ingress controller to actually do the URL rewriting, potentially building on the path transformation (if required by the chosen ingress controller). For example for Nginx ingress controller 0.22.0 and later the following value is recommended: `{'ingress.kubernetes.io/rewrite-target': '/$1','ingress.kubernetes.io/ssl-redirect': 'false',\     'ingress.kubernetes.io/proxy-connect-timeout': '3600','ingress.kubernetes.io/proxy-read-timeout': '3600',     'nginx.org/websocket-services': '<service-name>'}` and the `che.infra.kubernetes.ingress.path.rewrite_transform` should be set to `'%s(.*)'`. For nginx ingress controller older than 0.22.0, the rewrite-target should be set to merely `/` and the path transform to `%s` (see the `che.infra.kubernetes.ingress.path.rewrite_transform` property). See the Nginx ingress controller documentation for the explanation of how the ingress controller uses the regular expression available in the ingress path and how it achieves the URL rewriting." 
 `+CHE_INFRA_KUBERNETES_INGRESS_PATH__TRANSFORM+`,"`+NULL+`","Defines a recipe on how to declare the path of the ingress that should expose a server. The `%s` represents the base public URL of the server and is guaranteed to end with a forward slash. This property must be a valid input to the `String.format()` method and contain exactly one reference to `%s`. See the description of the `che.infra.kubernetes.ingress.annotations_json` property to see how these two properties interplay when specifying the ingress annotations and path. If not defined, this property defaults to `%s` (without the quotes) which means that the path is not transformed in any way for use with the ingress controller." 
 `+CHE_INFRA_KUBERNETES_INGRESS_LABELS+`,"`+NULL+`","Additional labels to add into every Ingress created by {prod-short} server to allow clear identification." 
 `+CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER+`,"`+NULL+`","Defines security context for Pods that will be created by Kubernetes Infra This is ignored by OpenShift infra" 
 `+CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP+`,"`+NULL+`","Defines security context for Pods that will be created by Kubernetes Infra. A special supplemental group that applies to all containers in a Pod. This is ignored by OpenShift infra." 
 `+CHE_INFRA_KUBERNETES_POD_TERMINATION__GRACE__PERIOD__SEC+`,"`+0+`","Defines grace termination period for Pods that will be created by {orch-name} infrastructures. Default value: `0`. It allows to stop Pods quickly and significantly decrease the time required for stopping a workspace. the {prod-short} Operator: if `terminationGracePeriodSeconds` have been explicitly set in {orch-name} recipe it will not be overridden." 
 `+CHE_INFRA_KUBERNETES_CLIENT_HTTP_ASYNC__REQUESTS_MAX+`,"`+1000+`","Number of maximum concurrent asynchronous web requests (HTTP requests or ongoing  WebSocket calls) supported in the underlying shared HTTP client of the `KubernetesClient` instances. Default values: `max=64`, and `max_per_host:5`. Default values are not suitable for multi-user scenarios, as {prod-short} keeps open connections, for example for command or ws-agent logs." 
 `+CHE_INFRA_KUBERNETES_CLIENT_HTTP_ASYNC__REQUESTS_MAX__PER__HOST+`,"`+1000+`","Number of maximum concurrent asynchronous web requests per host." 
 `+CHE_INFRA_KUBERNETES_CLIENT_HTTP_CONNECTION__POOL_MAX__IDLE+`,"`+5+`","Max number of idle connections in the connection pool of the Kubernetes-client shared HTTP client." 
 `+CHE_INFRA_KUBERNETES_CLIENT_HTTP_CONNECTION__POOL_KEEP__ALIVE__MIN+`,"`+5+`","Keep-alive timeout of the connection pool of the Kubernetes-client shared HTTP client in minutes." 
 `+CHE_INFRA_KUBERNETES_TLS__ENABLED+`,"`+false+`","Creates Ingresses with Transport Layer Security (TLS) enabled. In OpenShift infrastructure, Routes will be TLS-enabled." 
 `+CHE_INFRA_KUBERNETES_TLS__SECRET+`,"","Name of a secret that should be used when creating workspace ingresses with TLS. This property is ignored by OpenShift infrastructure." 
 `+CHE_INFRA_KUBERNETES_TLS__KEY+`,"`+NULL+`","Data for TLS Secret that should be used for workspaces Ingresses. `cert` and `key` should be encoded with Base64 algorithm. These properties are ignored by OpenShift infrastructure." 
 `+CHE_INFRA_KUBERNETES_TLS__CERT+`,"`+NULL+`","Certificate data for TLS Secret that should be used for workspaces Ingresses. Certificate should be encoded with Base64 algorithm. This property is ignored by OpenShift infrastructure." 
 `+CHE_INFRA_KUBERNETES_RUNTIMES__CONSISTENCY__CHECK__PERIOD__MIN+`,"`+-1+`","Defines the period with which runtimes consistency checks will be performed. If runtime has inconsistent state then runtime will be stopped automatically. Value must be more than 0 or `-1`, where `-1` means that checks won't be performed at all. It is disabled by default because there is possible {prod-short} Server configuration when {prod-short} Server doesn't have an ability to interact with Kubernetes API when operation is not invoked by user. It DOES work on the following configurations: - workspaces objects are created in the same namespace where {prod-short} Server is located; - `cluster-admin` service account token is mounted to {prod-short} Server Pod. It DOES NOT work on the following configurations: - {prod-short} Server communicates with Kubernetes API using token from OAuth provider." 
 `+CHE_INFRA_KUBERNETES_TRUSTED__CA_SRC__CONFIGMAP+`,"`+NULL+`","Name of the ConfigMap in {prod-short} server namespace with additional CA TLS certificates to be propagated into all user's workspaces. If the property is set on OpenShift 4 infrastructure, and `che.infra.openshift.trusted_ca.dest_configmap_labels` includes the `config.openshift.io/inject-trusted-cabundle=true` label, then cluster CA bundle will be propagated too." 
 `+CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP+`,"`+ca-certs+`","Name of the ConfigMap in a workspace namespace with additional CA TLS certificates. Holds the copy of `che.infra.kubernetes.trusted_ca.src_configmap` but in a workspace namespace. Content of this ConfigMap is mounted into all workspace containers including plugin brokers. Do not change the ConfigMap name unless it conflicts with the already existing ConfigMap. the {prod-short} Operator that the resulting ConfigMap name can be adjusted eventually to make it unique in {orch-namespace}. The original name would be stored in `che.original_name` label." 
 `+CHE_INFRA_KUBERNETES_TRUSTED__CA_MOUNT__PATH+`,"`+/public-certs+`","Configures path on workspace containers where the CA bundle should be mounted. Content of ConfigMap specified by `che.infra.kubernetes.trusted_ca.dest_configmap` is mounted." 
 `+CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP__LABELS+`,"","Comma separated list of labels to add to the CA certificates ConfigMap in user workspace. See the `che.infra.kubernetes.trusted_ca.dest_configmap` property." 
,=== 

[id="openshift-infra-parameters"]
= OpenShift Infra parameters

.OpenShift Infra parameters 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_INFRA_OPENSHIFT_TRUSTED__CA_DEST__CONFIGMAP__LABELS+`,"`+config.openshift.io/inject-trusted-cabundle=true+`","Comma separated list of labels to add to the CA certificates ConfigMap in user workspace. See `che.infra.kubernetes.trusted_ca.dest_configmap` property. This default value is used for automatic cluster CA bundle injection in OpenShift 4." 
 `+CHE_INFRA_OPENSHIFT_ROUTE_LABELS+`,"`+NULL+`","Additional labels to add into every Route created by {prod-short} server to allow clear identification." 
 `+CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX+`,"`+NULL+`","The hostname that should be used as a suffix for the workspace routes. For example: Using `domain_suffix=__<{prod-host}>__`, the route resembles: `routed3qrtk.__<{prod-host}>__`. It has to be a valid DNS name." 
 `+CHE_INFRA_OPENSHIFT_PROJECT_INIT__WITH__SERVER__SA+`,"`+true+`","Initialize OpenShift project with {prod-short} server's service account if OpenShift OAuth is enabled." 
,=== 

[id="experimental-properties"]
= Experimental properties

.Experimental properties 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_WORKSPACE_PLUGIN__BROKER_METADATA_IMAGE+`,"`+quay.io/eclipse/che-plugin-metadata-broker:v3.4.0+`","Docker image of {prod-short} plugin broker app that resolves workspace tools configuration and copies plugins dependencies to a workspace. The {prod-short} Operator overrides these images by default. Changing the images here will not have an effect if {prod-short} is installed using the Operator." 
 `+CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE+`,"`+quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0+`","Docker image of {prod-short} plugin artifacts broker. This broker runs as an init container on the workspace Pod. Its job is to take in a list of plugin identifiers (either references to a plugin in the registry or a link to a plugin meta.yaml) and ensure that the correct .vsix and .theia extensions are downloaded into the /plugins directory, for each plugin requested for the workspace." 
 `+CHE_WORKSPACE_PLUGIN__BROKER_DEFAULT__MERGE__PLUGINS+`,"`+false+`","Configures the default behavior of the plugin brokers when provisioning plugins into a workspace. If set to true, the plugin brokers will attempt to merge plugins when possible: they run in the same sidecar image and do not have conflicting settings. This value is the default setting used when the devfile does not specify the `mergePlugins` attribute." 
 `+CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY+`,"`+Always+`","Docker image of {prod-short} plugin broker app that resolves workspace tools configuration and copies plugins dependencies to a workspace" 
 `+CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN+`,"`+3+`","Defines the timeout in minutes that limits the max period of result waiting for plugin broker." 
 `+CHE_WORKSPACE_PLUGIN__REGISTRY__URL+`,"`+https://che-plugin-registry.prod-preview.openshift.io/v3+`","Workspace plug-ins registry endpoint. Should be a valid HTTP URL. Example: ++http://che-plugin-registry-eclipse-che.192.168.65.2.nip.io++ In case {prod-short} plug-ins registry is not needed value 'NULL' should be used" 
 `+CHE_WORKSPACE_PLUGIN__REGISTRY__INTERNAL__URL+`,"`+NULL+`","Workspace plugins registry internal endpoint. Should be a valid HTTP URL. Example: ++http://devfile-registry.che.svc.cluster.local:8080++ In case {prod-short} plug-ins registry is not needed value 'NULL' should be used" 
 `+CHE_WORKSPACE_DEVFILE__REGISTRY__URL+`,"`+https://che-devfile-registry.prod-preview.openshift.io/+`","Devfile Registry endpoint. Should be a valid HTTP URL. Example: ++http://che-devfile-registry-eclipse-che.192.168.65.2.nip.io++ In case {prod-short} plug-ins registry is not needed value 'NULL' should be used" 
 `+CHE_WORKSPACE_DEVFILE__REGISTRY__INTERNAL__URL+`,"`+NULL+`","Devfile Registry 'internal' endpoint. Should be a valid HTTP URL. Example: ++http://plugin-registry.che.svc.cluster.local:8080++ In case {prod-short} plug-ins registry is not needed value 'NULL' should be used" 
 `+CHE_WORKSPACE_STORAGE_AVAILABLE__TYPES+`,"`+persistent,ephemeral,async+`","The configuration property that defines available values for storage types that clients such as the Dashboard should propose to users during workspace creation and update. Available values:   - `persistent`: Persistent Storage slow I/O but persistent.   - `ephemeral`: Ephemeral Storage allows for faster I/O but may have limited storage       and is not persistent.   - `async`: Experimental feature: Asynchronous storage is combination of Ephemeral       and Persistent storage. Allows for faster I/O and keep your changes, will backup on stop       and restore on start workspace.       Will work only if:           - `che.infra.kubernetes.pvc.strategy='common'`           - `che.limits.user.workspaces.run.count=1`           - `che.infra.kubernetes.namespace.default` contains `<username>`      in other cases remove `async` from the list." 
 `+CHE_WORKSPACE_STORAGE_PREFERRED__TYPE+`,"`+persistent+`","The configuration property that defines a default value for storage type that clients such as the Dashboard should propose to users during workspace creation and update. The `async` value is an experimental feature, not recommended as default type." 
 `+CHE_SERVER_SECURE__EXPOSER+`,"`+jwtproxy+`","Configures in which way secure servers will be protected with authentication. Suitable values:   - `default`: `jwtproxy` is configured in a pass-through mode. Servers should authenticate requests themselves.   - `jwtproxy`: `jwtproxy` will authenticate requests. Servers will receive only authenticated requests." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_ISSUER+`,"`+wsmaster+`","`Jwtproxy` issuer string, token lifetime, and optional auth page path to route unsigned requests to." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_TTL+`,"`+8800h+`","JWTProxy issuer token lifetime." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_AUTH_LOADER_PATH+`,"`+/_app/loader.html+`","Optional authentication page path to route unsigned requests to." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_IMAGE+`,"`+quay.io/eclipse/che-jwtproxy:0.10.0+`","JWTProxy image." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_MEMORY__REQUEST+`,"`+15mb+`","JWTProxy memory request." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_MEMORY__LIMIT+`,"`+128mb+`","JWTProxy memory limit." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_CPU__REQUEST+`,"`+0.03+`","JWTProxy CPU request." 
 `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_CPU__LIMIT+`,"`+0.5+`","JWTProxy CPU limit." 
,=== 

[id="configuration-of-the-major-websocket-endpoint"]
= Configuration of the major WebSocket endpoint

.Configuration of the major WebSocket endpoint 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_CORE_JSONRPC_PROCESSOR__MAX__POOL__SIZE+`,"`+50+`","Maximum size of the JSON RPC processing pool in case if pool size would be exceeded message execution will be rejected" 
 `+CHE_CORE_JSONRPC_PROCESSOR__CORE__POOL__SIZE+`,"`+5+`","Initial JSON processing pool. Minimum number of threads that used to process major JSON RPC messages." 
 `+CHE_CORE_JSONRPC_PROCESSOR__QUEUE__CAPACITY+`,"`+100000+`","Configuration of queue used to process JSON RPC messages." 
 `+CHE_METRICS_PORT+`,"`+8087+`","Port the HTTP server endpoint that would be exposed with Prometheus metrics." 
,=== 

[id="cors-settings"]
= CORS settings

.CORS settings 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_CORS_ALLOWED__ORIGINS+`,"`+*+`","Indicates which request origins are allowed. CORS filter on WS Master is turned off by default. Use environment variable 'CHE_CORS_ENABLED=true' to turn it on." 
 `+CHE_CORS_ALLOW__CREDENTIALS+`,"`+false+`","Indicates if it allows processing of requests with credentials (in cookies, headers, TLS client certificates)." 
,=== 

[id="factory-defaults"]
= Factory defaults

.Factory defaults 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_FACTORY_DEFAULT__PLUGINS+`,"`+redhat/vscode-commons/latest+`","Editor and plugin which will be used for factories that are created from a remote Git repository which does not contain any {prod-short}-specific workspace descriptor Multiple plugins must be comma-separated, for example: `pluginFooPublisher/pluginFooName/pluginFooVersion,pluginBarPublisher/pluginBarName/pluginBarVersion`" 
 `+CHE_FACTORY_DEFAULT__DEVFILE__FILENAMES+`,"`+devfile.yaml,.devfile.yaml+`","Devfile filenames to look on repository-based factories (for example GitHub). Factory will try to locate those files in the order they enumerated in the property." 
,=== 

[id="devfile-defaults"]
= Devfile defaults

.Devfile defaults 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_FACTORY_DEFAULT__EDITOR+`,"`+eclipse/che-theia/next+`","Editor that will be used for factories that are created from a remote Git repository which does not contain any {prod-short}-specific workspace descriptor." 
 `+CHE_FACTORY_SCM__FILE__FETCHER__LIMIT__BYTES+`,"`+102400+`","File size limit for the URL fetcher which fetch files from the SCM repository." 
 `+CHE_FACTORY_DEVFILE2__FILES__RESOLUTION__LIST+`,"`+.che/che-editor.yaml,.che/che-theia-plugins.yaml,.vscode/extensions.json+`","Additional files which may be present in repository to complement devfile v2, and should be referenced as links to SCM resolver service in factory to retrieve them." 
 `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR+`,"`+eclipse/che-theia/next+`","Default Editor that should be provisioned into Devfile if there is no specified Editor Format is `editorPublisher/editorName/editorVersion` value. `NULL` or absence of value means that default editor should not be provisioned." 
 `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS+`,"`+NULL+`","Default Plug-ins which should be provisioned for Default Editor. All the plugins from this list that are not explicitly mentioned in the user-defined devfile will be provisioned but only when the default editor is used or if the user-defined editor is the same as the default one (even if in different version). Format is comma-separated `pluginPublisher/pluginName/pluginVersion` values, and URLs. For example: `eclipse/che-theia-exec-plugin/0.0.1,eclipse/che-theia-terminal-plugin/0.0.1,https://cdn.pluginregistry.com/vi-mode/meta.yaml` If the plugin is a URL, the plugin's `meta.yaml` is retrieved from that URL." 
 `+CHE_WORKSPACE_PROVISION_SECRET_LABELS+`,"`+app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspace-secret+`","Defines comma-separated list of labels for selecting secrets from a user namespace, which will be mount into workspace containers as a files or environment variables. Only secrets that match ALL given labels will be selected." 
 `+CHE_WORKSPACE_DEVFILE_ASYNC_STORAGE_PLUGIN+`,"`+eclipse/che-async-pv-plugin/latest+`","Plugin is added in case asynchronous storage feature will be enabled in workspace configuration and supported by environment" 
 `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_IMAGE+`,"`+quay.io/eclipse/che-workspace-data-sync-storage:0.0.1+`","Docker image for the {prod-short} asynchronous storage" 
 `+CHE_WORKSPACE_POD_NODE__SELECTOR+`,"`+NULL+`","Optionally configures node selector for workspace Pod. Format is comma-separated key=value pairs, for example: `disktype=ssd,cpu=xlarge,foo=bar`" 
 `+CHE_WORKSPACE_POD_TOLERATIONS__JSON+`,"`+NULL+`","Optionally configures tolerations for workspace Pod. Format is a string representing a JSON Array of taint tolerations, or `NULL` to disable it. The objects contained in the array have to follow the link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#toleration-v1-core[toleration v1 core specifications]. Example: `[{'effect':'NoExecute','key':'aNodeTaint','operator':'Equal','value':'aValue'}]`" 
 `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_SHUTDOWN__TIMEOUT__MIN+`,"`+120+`","The timeout for the Asynchronous Storage Pod shutdown after stopping the last used workspace. Value less or equal to 0 interpreted as disabling shutdown ability." 
 `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_SHUTDOWN__CHECK__PERIOD__MIN+`,"`+30+`","Defines the period with which the Asynchronous Storage Pod stopping ability will be performed (once in 30 minutes by default)" 
 `+CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS+`,"`+NULL+`","Bitbucket endpoints used for factory integrations. Comma separated list of Bitbucket server URLs or NULL if no integration expected." 
 `+CHE_INTEGRATION_GITLAB_SERVER__ENDPOINTS+`,"`+NULL+`","GitLab endpoints used for factory integrations. Comma separated list of GitLab server URLs or NULL if no integration expected." 
 `+CHE_INTEGRATION_GITLAB_OAUTH__ENDPOINT+`,"`+NULL#+`","Address of the GitLab server with configured OAuth 2 integration" 
,=== 

[id="che-system"]
= Che system

.Che system 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_SYSTEM_SUPER__PRIVILEGED__MODE+`,"`+false+`","System Super Privileged Mode. Grants users with the manageSystem permission additional permissions for getByKey, getByNameSpace, stopWorkspaces, and getResourcesInformation. These are not given to admins by default and these permissions allow admins gain visibility to any workspace along with naming themselves with administrator privileges to those workspaces." 
 `+CHE_SYSTEM_ADMIN__NAME+`,"`+admin+`","Grant system permission for `che.admin.name` user. If the user already exists it'll happen on component startup, if not - during the first login when user is persisted in the database." 
,=== 

[id="workspace-limits"]
= Workspace limits

.Workspace limits 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_LIMITS_WORKSPACE_ENV_RAM+`,"`+16gb+`","Workspaces are the fundamental runtime for users when doing development. You can set parameters that limit how workspaces are created and the resources that are consumed. The maximum amount of RAM that a user can allocate to a workspace when they create a new workspace. The RAM slider is adjusted to this maximum value." 
 `+CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT+`,"`+1800000+`","The length of time in milliseconds that a user is idle with their workspace when the system will suspend the workspace and then stopping it. Idleness is the length of time that the user has not interacted with the workspace, meaning that one of the agents has not received interaction. Leaving a browser window open counts toward idleness." 
 `+CHE_LIMITS_WORKSPACE_RUN_TIMEOUT+`,"`+0+`","The length of time in milliseconds that a workspace will run, regardless of activity, before the system will suspend it. Set this property if you want to automatically stop workspaces after a period of time. The default is zero, meaning that there is no run timeout." 
,=== 

[id="users-workspace-limits"]
= Users workspace limits

.Users workspace limits 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_LIMITS_USER_WORKSPACES_RAM+`,"`+-1+`","The total amount of RAM that a single user is allowed to allocate to running workspaces. A user can allocate this RAM to a single workspace or spread it across multiple workspaces." 
 `+CHE_LIMITS_USER_WORKSPACES_COUNT+`,"`+-1+`","The maximum number of workspaces that a user is allowed to create. The user will be presented with an error message if they try to create additional workspaces. This applies to the total number of both running and stopped workspaces." 
 `+CHE_LIMITS_USER_WORKSPACES_RUN_COUNT+`,"`+1+`","The maximum number of running workspaces that a single user is allowed to have. If the user has reached this threshold and they try to start an additional workspace, they will be prompted with an error message. The user will need to stop a running workspace to activate another." 
,=== 

[id="organizations-workspace-limits"]
= Organizations workspace limits

.Organizations workspace limits 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_LIMITS_ORGANIZATION_WORKSPACES_RAM+`,"`+-1+`","The total amount of RAM that a single organization (team) is allowed to allocate to running workspaces. An organization owner can allocate this RAM however they see fit across the team's workspaces." 
 `+CHE_LIMITS_ORGANIZATION_WORKSPACES_COUNT+`,"`+-1+`","The maximum number of workspaces that a organization is allowed to own. The organization will be presented an error message if they try to create additional workspaces. This applies to the total number of both running and stopped workspaces." 
 `+CHE_LIMITS_ORGANIZATION_WORKSPACES_RUN_COUNT+`,"`+-1+`","The maximum number of running workspaces that a single organization is allowed. If the organization has reached this threshold and they try to start an additional workspace, they will be prompted with an error message. The organization will need to stop a running workspace to activate another." 
,=== 

[id="multi-user-specific-openshift-infrastructure-configuration"]
= Multi-user-specific OpenShift infrastructure configuration

.Multi-user-specific OpenShift infrastructure configuration 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_INFRA_OPENSHIFT_OAUTH__IDENTITY__PROVIDER+`,"`+NULL+`","Alias of the OpenShift identity provider registered in Keycloak, that should be used to create workspace OpenShift resources in OpenShift namespaces owned by the current {prod-short} user. Should be set to NULL if `che.infra.openshift.project` is set to a non-empty value. See: link:https://www.keycloak.org/docs/latest/server_admin/#openshift-4[OpenShift identity provider]" 
,=== 

[id="oidc-configuration"]
= OIDC configuration

.OIDC configuration 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_OIDC_AUTH__SERVER__URL+`,"`+http://${CHE_HOST}:5050/auth+`","Url to OIDC identity provider server Can be set to NULL only if `che.oidc.oidcProvider` is used" 
 `+CHE_OIDC_AUTH__INTERNAL__SERVER__URL+`,"`+NULL+`","Internal network service Url to OIDC identity provider server" 
 `+CHE_OIDC_ALLOWED__CLOCK__SKEW__SEC+`,"`+3+`","The number of seconds to tolerate for clock skew when verifying `exp` or `nbf` claims." 
 `+CHE_OIDC_USERNAME__CLAIM+`,"`+NULL+`","Username claim to be used as user display name when parsing JWT token if not defined the fallback value is 'preferred_username' in Keycloak installations and `name` in Dex installations." 
 `+CHE_OIDC_OIDC__PROVIDER+`,"`+NULL+`","Base URL of an alternate OIDC provider that provides a discovery endpoint as detailed in the following specification link:https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Obtaining OpenID Provider Configuration Information] Deprecated, use `che.oidc.auth_server_url` and `che.oidc.auth_internal_server_url` instead." 
,=== 

[id="keycloak-configuration"]
= Keycloak configuration

.Keycloak configuration 
,=== 
 Environment Variable Name,Default value, Description 
 
 `+CHE_KEYCLOAK_REALM+`,"`+che+`","Keycloak realm is used to authenticate users Can be set to NULL only if `che.keycloak.oidcProvider` is used" 
 `+CHE_KEYCLOAK_CLIENT__ID+`,"`+che-public+`","Keycloak client identifier in `che.keycloak.realm` to authenticate users in the dashboard, the IDE, and the CLI." 
 `+CHE_KEYCLOAK_OSO_ENDPOINT+`,"`+NULL+`","URL to access OSO OAuth tokens" 
 `+CHE_KEYCLOAK_GITHUB_ENDPOINT+`,"`+NULL+`","URL to access Github OAuth tokens" 
 `+CHE_KEYCLOAK_USE__NONCE+`,"`+true+`","Use the OIDC optional `nonce` feature to increase security." 
 `+CHE_KEYCLOAK_JS__ADAPTER__URL+`,"`+NULL+`","URL to the Keycloak Javascript adapter to use. if set to NULL, then the default used value is `$++{che.keycloak.auth_server_url}++/js/keycloak.js`, or `<che-server>/api/keycloak/OIDCKeycloak.js` if an alternate `oidc_provider` is used" 
 `+CHE_KEYCLOAK_USE__FIXED__REDIRECT__URLS+`,"`+false+`","Set to true when using an alternate OIDC provider that only supports fixed redirect Urls This property is ignored when `che.keycloak.oidc_provider` is NULL" 
 `+CHE_OAUTH_SERVICE__MODE+`,"`+delegated+`","Configuration of OAuth Authentication Service that can be used in 'embedded' or 'delegated' mode. If set to 'embedded', then the service work as a wrapper to {prod-short}'s OAuthAuthenticator ( as in Single User mode). If set to 'delegated', then the service will use Keycloak IdentityProvider mechanism. Runtime Exception `wii` be thrown, in case if this property is not set properly." 
 `+CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED+`,"`+false+`","Configuration for enabling removing user from Keycloak server on removing user from {prod-short} database. By default it's disabled. Can be enabled in some special cases when deleting a user in {prod-short} database should execute removing related-user from Keycloak. For correct work need to set administrator username $++{che.keycloak.admin_username}++ and password $++{che.keycloak.admin_password}++." 
 `+CHE_KEYCLOAK_ADMIN__USERNAME+`,"`+NULL+`","Keycloak administrator username. Will be used for deleting user from Keycloak on removing user from {prod-short} database. Make sense only in case $++{che.keycloak.cascade_user_removal_enabled}++ set to 'true'" 
 `+CHE_KEYCLOAK_ADMIN__PASSWORD+`,"`+NULL+`","Keycloak administrator password. Will be used for deleting user from Keycloak on removing user from {prod-short} database. Make sense only in case $++{che.keycloak.cascade_user_removal_enabled}++ set to 'true'" 
 `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+`,"`+NULL+`","User name adjustment configuration. {prod-short} needs to use the usernames as part of Kubernetes object names and labels and therefore has stricter requirements on their format than the identity providers usually allow (it needs them to be DNS-compliant). The adjustment is represented by comma-separated key-value pairs. These are sequentially used as arguments to the String.replaceAll function on the original username. The keys are regular expressions, values are replacement strings that replace the characters in the username that match the regular expression. The modified username will only be stored in the {prod-short} database and will not be advertised back to the identity provider. It is recommended to use DNS-compliant characters as replacement strings (values in the key-value pairs). Example: `\\=-,@=-at-` changes `\` to `-` and `@` to `-at-` so the username `org\user@com` becomes `org-user-at-com.`" 
,=== 


