

:parent-context-of-accessing-che-from-openshift-developer-perspective: {context}

[id="accessing-{prod-id-short}-from-openshift-developer-perspective_{context}"]
= Accessing {prod-short} from OpenShift Developer Perspective

:context: accessing-{prod-id-short}-from-openshift-developer-perspective


The OpenShift Container Platform web console provides two perspectives; the *Administrator* perspective and the *Developer* perspective.

The Developer perspective provides workflows specific to developer use cases, such as the ability to:

* Create and deploy applications on OpenShift Container Platform by importing existing codebases, images, and dockerfiles.

* Visually interact with applications, components, and services associated with them within a project and monitor their deployment and build status.

* Group components within an application and connect the components within and across applications.

* Integrate serverless capabilities (Technology Preview).

* Create workspaces to edit your application code using {prod-short}.

include::partial$con_openshift-developer-perspective-integration-with-che.adoc[leveloffset=+1]

include::partial$proc_editing-the-code-of-applications-running-in-openshift-container-platform-using-che.adoc[leveloffset=+1]

include::partial$proc_accessing-che-from-red-hat-applications-menu.adoc[leveloffset=+1]

:context: {parent-context-of-accessing-che-from-openshift-developer-perspective}
