

:parent-context-of-mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container: {context}

[id="mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as a file or an environment variable into a workspace container

:context: mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

Secrets are {platforms-name} objects that store sensitive data such as user names, passwords, authentication tokens, and configurations in an encrypted form.

Users can mount a secret that contains sensitive data in a workspace container. This reapplies the stored data from the secret automatically for every newly created workspace. As a result, the user does not have to provide these credentials and configuration settings manually. 

The following sections describe how to automatically mount the {platforms-name} secret in a workspace container and create permanent mount points for components such as:

* Maven configuration, the `settings.xml` file 
* SSH key pairs
* AWS authorization tokens
* Git credentials store file

A secret can be mounted into a workspace container as a file or an environment variable:

File:: Creates automatically mounted Maven settings that will be applied to every new workspace with Maven capabilities.

Environment variable:: Uses SSH key pairs and AWS authorization tokens for automatic authentication. 
+
NOTE: SSH key pairs can also be mounted as a file, but this format is primarily aimed at the settings of the Maven configuration.

The mounting process uses the standard {platforms-name} mounting mechanism, but it requires additional annotations and labeling to properly bind a secret with the required {prod-short} workspace container.

include::partial$proc_mounting-a-secret-as-a-file-into-a-workspace-container.adoc[leveloffset=+1]

include::partial$proc_overriding-the-mount-path-of-the-secret-for-a-workspace-component.adoc[leveloffset=+2]

include::partial$proc_mounting-a-secret-as-an-environment-variable-into-a-workspace-container.adoc[leveloffset=+1]

include::partial$proc_mounting-a-git-credential-store-into-a-workspace-container.adoc[leveloffset=+1]

include::partial$ref_the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container.adoc[leveloffset=+1]

:context: {parent-context-of-mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container}

