// This assembly is included in the following assemblies:
//
// what-is-a-che-theia-plug-in

[id="che-theia-plug-in-lifecycle_{context}"]
= Che-Theia plug-in lifecycle

Every time a user starts a Che workspace, a Che-Theia plug-in life cycle process starts. The steps of this process are as follows:

. {prod-short} server checks for plug-ins to start from the workspace definition.
. {prod-short} server retrieves plug-in metadata, recognizes each plug-in type, and stores them in memory. 
. {prod-short} server selects a broker according to the plug-in type.
. The broker processes the installation and deployment of the plug-in. The installation process of the plug-in differs for each specific broker.

NOTE: Plug-ins exist in various types. A broker ensures the success of a plug-in deployment by meeting all installation requirements. 

// TODO: plug-in types (link:link[LINK])


.Che-Theia plug-in lifecycle
image::extensibility/che-theia-plug-in-lifecycle.svg[link="../_images/extensibility/che-theia-plug-in-lifecycle.svg"]

Before a {prod-short} workspace is launched, {prod-short} server starts the workspace containers:

. The Che-Theia plug-in broker extracts the information about sidecar containers that a particular plug-in needs from the `.theia` file.
. The broker sends the appropriate container information to {prod-short} server.
. The broker copies the Che-Theia plug-in to a volume to have it available for the Che-Theia editor container.
. {prod-short} server then starts all the containers of the workspace.
. Che-Theia starts in its container and checks the correct folder to load the plug-ins.

.A user experience with Che-Theia plug-in lifecycle
. When a user opens a browser tab with Che-Theia, Che-Theia starts a new plug-in session with:
+ 
* Web Worker for frontend
* Node.js for backend

. Che-Theia notifies all Che-Theia plug-ins with the start of the new session by calling the `start()` function for each triggered plug-in.

. A Che-Theia plug-in session runs and interacts with the Che-Theia backend and frontend.

. When the user closes the Che-Theia browser tab, or the session ended on a timeout limit, Che-Theia notifies all plug-ins with the `stop()` function for each triggered plug-in.


// .Additional resources
//
// * A bulleted list of links to other material closely related to the contents of the concept module.
// * For more details on writing concept modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
// * Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
