// This assembly is included in the following assemblies:
//
// what-is-a-che-theia-plug-in

[id="che-theia-plug-in-concept-in-detail_{context}"]
= Che-Theia plug-in concept in detail

{prod} provides a default web IDE for workspaces: Che-Theia. It is based on Eclipse Theia. It is a slightly different version than the plain Eclipse Theia one because there are functionalities that have been added based on the nature of the {prod} workspaces. This version of Eclipse Theia for {prod-short} is called *Che-Theia*.

You can extend the IDE provided with {prod} by building a *Che-Theia plug-in*. Che-Theia plug-ins are compatible with any other Eclipse Theia-based IDE.


[id="client-side-and-server-side-che-theia-plug-ins_{context}"]
== Client-side and server-side Che-Theia plug-ins

The Che-Theia editor plug-ins let you add languages, debuggers, and tools to your installation to support your development workflow. Plug-ins run when the editor completes loading. If a Che-Theia plug-in fails, the main Che-Theia editor continues to work.

Che-Theia plug-ins run either on the client side or on the server side. This is a scheme of the client and server-side plug-in concept:

.Client and server-side Che-Theia plug-ins
image::extensibility/client-server-side-plug-ins.svg[]

The same Che-Theia plug-in API is exposed to plug-ins running on the client side (Web Worker) or the server side (Node.js).


[id="che-theia-plug-in-apis_{context}"]
== Che-Theia plug-in APIs

For the purpose of providing tool isolation and easy extensibility in {prod}, the Che-Theia IDE has a set of plug-in APIs. The APIs are compatible with Visual Studio Code extension APIs. In most cases, Che-Theia can run VS Code extensions as its own plug-ins.
// TODO: VS Code extensions as Che-Theia plug-ins. Read more at link.

When developing a plug-in that depends on or interacts with components of {prod-short} workspaces (containers, preferences, factories), use the {prod-short} APIs embedded in Che-Theia.
// TODO: Learn more about the {prod-short} APIs at link.


[id="che-theia-plug-in-capabilities_{context}"]
== Che-Theia plug-in capabilities

Che-Theia plug-ins have the following capabilities:

[options="header",cols="3"]
|===
| *Plug-in*
| *Description*
| *Repository*

| *{prod-short} Extended Tasks*
| Handles the {prod-short} commands and provides the ability to start those into a specific container of the workspace.
|link:https://github.com/eclipse/che-theia/tree/master/plugins/task-plugin[Task plug-in]

| *{prod-short} Extended Terminal*
| Allows to provide terminal for any of the containers of the workspace.
|link:https://github.com/eclipse/che-theia/tree/master/extensions/eclipse-che-theia-terminal[Extended Terminal extension]

| *{prod-short} Factory*
| Handles the {prod} Factories
|link:https://github.com/eclipse/che-theia/tree/master/plugins/workspace-plugin[Workspace plug-in]

| *{prod-short} Container*
| Provides a container view that shows all the containers that are running in the workspace and allows to interact with them.
| link:https://github.com/eclipse/che-theia/tree/master/plugins/containers-plugin[Containers plug-in]

| *Dashboard*
| Integrates the IDE with the *Dashboard* and facilitate the navigation.
|link:https://github.com/eclipse/che-theia/tree/master/extensions/eclipse-che-theia-dashboard[Che-Theia Dashbord extension]

| *{prod-short} APIs*
| Extends the IDE APIs to allow interacting with {prod-short}-specific components (workspaces, preferences).
|link:https://github.com/eclipse/che-theia/tree/master/extensions/eclipse-che-theia-plugin-ext[Che-Theia API extension]
|===



[id="vs-code-extensions-and-eclipse-theia-plug-ins_{context}"]
== VS Code extensions and Eclipse Theia plug-ins

A Che-Theia plug-in can be based on a VS Code extension or an Eclipse Theia plug-in.

A Visual Studio Code extension:: To repackage a VS Code extension as a Che-Theia plug-in with its own set of dependencies, package the dependencies into a container. This ensures that {prod} users do not need to install the dependencies when using the extension. See xref:adding-a-vs-code-extension-to-a-workspace.adoc[].

An Eclipse Theia plug-in:: You can build a Che-Theia plug-in by implementing an Eclipse Theia plug-in and packaging it to {prod}.
// TODO: Learn more about how to package a Che-Theia plug-in at link.


.Additional resources

* xref:embedded-and-remote-che-theia-plug-ins_{context}[]
