// Module included in the following assemblies:
//
// adding-tools-to-{prod-id-short}-after-creating-a-workspace

[id="additional-tools-in-the-{prod-id-short}-workspace_{context}"]
= Additional tools in the {prod-short} workspace

{prod-short} plug-ins are extensions to the Che-Theia IDE that come bundled with a container image that contains their native prerequisites.
An example of such a native prerequisite is having the OpenShift command-line tool, `oc`,  and a command to install it for the proper functionality of the OpenShift Connector plug-in available in the dedicated image.

Plug-ins can also include metadata to define a description, categorization tags, and an icon. {prod-short} provides a registry of plug-ins available for installation into the user's workspace.

The Che-Theia IDE is generally compatible with the VS Code extensions API and VS Code extensions are automatically compatible with Che-Theia. These extensions are possible to package as {prod-short} plug-ins by combining them with their dependencies. By default, {prod-short} includes a plug-in registry containing common plug-ins.

.Adding a plug-in
 
* Using the Dashboard: 
** Add a plug-in from the plug-in registry using the *Plugins* tab in the *Workspace details* page.

** Add a plug-in directly into a devfile using the *Devfile* tab.
+
The devfile can also further the plug-in configuration, such as defining memory or CPU usage.

* Using  the Che-Theia IDE:
** By pressing kbd:[Ctrl+Shift+J] or by navigating to *View -> Plugins*.

.Additional resources

* xref:making-a-workspace-portable-using-a-devfile.adoc#adding-components-to-a-devfile_{context}[]
