// Module included in the following assemblies:
//
// configuring-a-workspace-using-a-devfile
// making-a-workspace-portable-using-a-devfile


[id="what-is-a-devfile_{context}"]
= What is a devfile

A devfile is a file that describes and define a development environment:

* the source code
* the development components, such as browser IDE tools and application runtimes
* a list of pre-defined commands
* projects to clone

Devfiles are YAML files that {prod-short} consumes and transforms into a cloud workspace composed of multiple containers. A devfile can be stored remotely or locally, in any number of ways, for example:

* In a git repository, in the root folder or on a feature branch
* On a publicly accessible web server, fetchable via HTTP
* Locally as a file, and deployed via `{prod-cli}`
* In a collection of devfiles, known as a xref:administration-guide:customizing-the-registries.adoc#understanding-the-che-registries_{prod-short}[devfile registry]

When creating a workspace, {prod-short} uses that definition to initiate everything and run all the containers for the required tools and application runtimes. {prod-short} also mounts file-system volumes to make source code available to the workspace.

Devfiles can be versioned with the project source code. When there is a need for a workspace to fix an old maintenance branch, the project devfile provides a definition of the workspace with the tools and the exact dependencies to start working on the old branch. Use it to instantiate workspaces on demand.

{prod-short} maintains the devfile up-to-date with the tools used in the workspace:

* Projects of the workspace (path, Git location, branch)
* Commands to perform daily tasks (build, run, test, debug)
* Runtime environment (container images to run the application)
* Che-Theia plug-ins with tools, IDE features, and helpers that a developer would use in the workspace (Git, Java support, SonarLint, Pull Request)
