// Module included in the following assemblies:
//
// adding-tools-to-{prod-id-short}-after-creating-a-workspace

[id="additional-tools-in-the-{prod-id-short}-workspace_{context}"]
= Additional tools in the {prod-short} workspace

{prod-short} plug-ins are extensions to the Che-Theia IDE that come bundled with a container image that contains their native prerequisites (for example, the OpenShift Connector plug-in needs the `oc` command installed). Plug-ins can also include metadata to define a description, categorization tags, and an icon.
{prod-short} provides a registry of plug-ins available for installation into the user's workspace.

The Che-Theia IDE is generally compatible with the VS Code extensions API. This means that many VS Code extensions are automatically compatible with Che-Theia, and can be packaged as {prod-short} plug-ins by combining them container that contains their dependencies. By default, {prod-short} includes a plug-in registry containing common plug-ins.

From the Dashboard, plug-ins in the registry can be added from the *Plugin* tab in the *Workspace details* page, or by adding them directly into a devfile. The devfile can also be used for further configuration of the plug-in, such defining memory or CPU usage.
Alternatively, plug-ins can also be installed from within the Che-Theia IDE by pressing kbd:[Ctrl+Shift+J] or by navigating to *View -> Plugins*.

.Additional resources

* xref:making-a-workspace-portable-using-a-devfile.adoc#adding-components-to-a-devfile_{context}[]
