[id="con_support-for-jetbrains-ides_{context}"]
= IntelliJ-based IDEs

This section contains information about supported IntelliJ-based IDEs that can be used in {prod} workspaces.

This is an experimental project that is being developed under {prod} organisation.

{prod} provides the ability to run a workspace with the one of the following predefined IntelliJ-based IDE:

* IntelliJ IDEA Community Edition
* PyCharm Community Edition

Prebuilt images can be found in public repositories in link:https://quay.io[Quay.io]:

* link:https://quay.io/repository/che-incubator/che-idea?tab=tags[che-incubator/che-idea]
* link:https://quay.io/repository/che-incubator/che-pycharm?tab=tags[che-incubator/che-pycharm]

This is available through using the Projector framework. Projector framework consists from the Projector Server and Projector Client. This is a set of libraries, that allow to run Swing applications without any windowing system and accessing them either locally or remotely.

NOTE: The full information about using Projector can be found here: link:https://jetbrains.github.io/projector-client/mkdocs/latest/[Projector documentation]

NOTE: Projector doesn't support to run IntelliJ-based IDEs for version 2021. So the latest supported version for IntelliJ-based IDEs is 2020.3.

The following sections describe how to create an image with a specific IDE and workspace based on the built image:

* xref:using-projector-to-build-editor-images.adoc[]
* xref:configuring-an-existing-workspace-to-use-intellij-idea.adoc[]
* xref:provisioning-jetbrains-activation-code-for-offline-use.adoc[]
