// Module included in the following assemblies:
//
// importing-kubernetes-applications-into-a-workspace

[id="including-kubernetes-applications-in-a-workspace-devfile-definition_{context}"]
= Including a {platforms-name} application in a workspace devfile definition

This procedure describes how to define a {prod-short} workspace devfile to include a {orch-name} application.

The devfile format is used to define a {prod-short} workspace, and its format is described in the xref:configuring-a-workspace-using-a-devfile.adoc[] section.

.Prerequisites

* You are logged in to the cluster with a running instance of {prod}. To install an instance of {prod}, see xref:installation-guide:installing-che.adoc[].

* `{prod-cli}` management tool is available. See xref:overview:using-the-chectl-management-tool.adoc[].


.Procedure
// TO DO Supply URL for that file location

. Create the simplest devfile:
+
[source,yaml]
----
apiVersion: 1.0.0
metadata:
 name: minimal-workspace <1>
----
+
<1> Only the name `minimal-workspace` is specified. After the {prod-short} server processes this devfile, the devfile is converted to a minimal {prod-short} workspace that only has the default editor (Che-Theia) and the default editor plug-ins, including, for example, the terminal.

. To add {orch-name} applications to a workspace, modify the devfile and add the `{kubernetes}` component type.
+
For example, to embed the NodeJS-Mongo application in the `minimal-workspace`:
+
include::example$snip_including-kubernetes-applications-in-a-workspace-devfile-definition-nodejs-minimal.adoc[]
+
<1> The `sleep infinity` command is added as the entrypoint of the Node.js application. The command prevents the application from starting at the workspace start phase. This configuration allows the user to start the application when needed for testing or debugging purposes.

. Add the commands in the devfile to make it easier for a developer to test the application:
+
include::example$snip_including-kubernetes-applications-in-a-workspace-devfile-definition-nodejs-minimal-added-commands.adoc[]
+
<1> The `run` command added to the devfile is available as a task in Che-Theia from the command palette. When executed, the command starts the Node.js application.

. Use the devfile to create and start a workspace:
+
[subs="+attributes,+quotes"]
----
$ {prod-cli} workspace:start --devfile __<devfile-path>__
----
