// Module included in the following assemblies:
//
// remotely-accessing-workspaces

[id="accessing-workspaces-remotely-using-{orch-cli}_{context}"]
= Remotely accessing workspaces using `{orch-cli}`

To access {prod-short} workspaces remotely using {orch-name} command-line tool (`{orch-cli}`), follow the instructions in this section.

ifeval::["{project-context}" == "che"]
NOTE: The `{orch-cli}` tool is used in this section to open a shell and manage files in a {prod-short} workspace. Alternatively, it is possible to use the `oc`  OpenShift command-line tool.
endif::[]

.Prerequisites

* The `{orch-cli}`, version 1.5.0 or higher, is available. For information about installed version, use:
+
[subs="+quotes,+attributes",options="+nowrap"]
----
$ {orch-cli} version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0"

...

----


.Procedure

In the example below:
 
* `workspace7b2wemdf3hx7s3ln.maven-74885cf4d5-kf2q4` is the name of the Pod.
* `{project-context}` is the {orch-namespace}.

. To find the name of the {platforms-name} {orch-namespace} and the Pod that runs the {prod-short} workspace:
+
[subs="+attributes,+quotes",options="+nowrap"]
----
$ {orch-cli}  get pod -l che.workspace_id --all-namespaces
NAMESPACE   NAME                                               READY   STATUS    RESTARTS   AGE
{project-context}         workspace7b2wemdf3hx7s3ln.maven-74885cf4d5-kf2q4   4/4     Running   0          6m4s
----


. To find the name of the container:
+
[subs="+attributes,+quotes",options="+nowrap"]
----
$ NAMESPACE={project-context}
$ POD=workspace7b2wemdf3hx7s3ln.maven-74885cf4d5-kf2q4
$ {orch-cli}  get pod $\{POD} -o custom-columns=CONTAINERS:.spec.containers[*].name
CONTAINERS
maven,che-machine-execpau,theia-ide6dj,vscode-javaw92
----

. When you have the {orch-namespace}, pod name, and the name of the container, use the `{orch-cli} ` command to open a remote shell:
+
[literal,subs="+attributes,+quotes",options="nowrap"]
--
$ NAMESPACE={project-context}
$ POD=workspace7b2wemdf3hx7s3ln.maven-74885cf4d5-kf2q4
$ CONTAINER=maven
$ {orch-cli} exec -ti -n $\{NAMESPACE} $\{POD} -c $\{CONTAINER} bash
user@workspace7b2wemdf3hx7s3ln $
--

. From the container, execute the `build` and `run` commands (as if from the {prod-short} workspace terminal):
+
[subs="+quotes",options="+nowrap"]
----
user@workspace7b2wemdf3hx7s3ln $ mvn clean install
[INFO] Scanning for projects...
(...)
----

.Additional resources

* For more about `{orch-cli}`, see the {orch-cli-link}.
