[id="jetbrains-intellij-idea-community-edition_{context}"]
= IntelliJ Idea Community Edition

You will need to clone
https://github.com/che-incubator/che-editor-intellij-community[the
repository] which is needed to build IntelliJ Idea Community Edition
located under che-incubator organization.

To build IntelliJ Idea Community Edition it is enough to call the
following command inside repository folder:

....
$ docker build -t idea-ic .
....

____
Optionally, you can provide build argument:

....
PRODUCT_NAME=ideaIC
....

but it is uneccessary. If no `--build-arg` was passed, `ideaIC` is used
instead.

The whole command will look like:

....
$ docker build -t idea-ic --build-arg PRODUCT_NAME=ideaIC .
....
____

This command will build image with *2020.2.3* version by default. Then
it is enough to tag result image and push tagged image to your
repository:

....
$ docker tag idea-ic:latest <username>/idea-ic:latest
$ docker push <username>/idea-ic:latest
....

Now this image can be used as Che Editor. To achive this there are two
yaml configurations needs to be created:

* `workspace.yaml` – workspace configuration. Do not forged to provide
correct url to the `meta.yaml` file:
+
....
metadata:
  name: che-ideaic
components:
  - type: cheEditor
    reference: '<url for the meta.yaml goes here>'
    alias: ideaic-editor
apiVersion: 1.0.0
....
* `meta.yaml` – Che Editor configuration. Do not forget to replace
`<username>` with the user name where image is pushed to:
+
....
apiVersion: v2
publisher: <username>
name: ideaic-NOVNC
version: 2020.2.3
type: Che Editor
displayName:  IntelliJ IDEA Community Edition
title:  IntelliJ IDEA Community Edition (in browser using noVNC) as editor for {prod}
description:  IntelliJ IDEA Community Edition running on the Web with noVNC
icon: https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_logo_300x300.png
category: Editor
repository: https://github.com/che-incubator/che-editor-intellij-community
firstPublicationDate: "2020-10-27"
spec:
  endpoints:
   -  name: "intellij"
      public: true
      targetPort: 8080
      attributes:
        protocol: http
        type: ide
        path: /vnc.html?resize=remote&autoconnect=true&reconnect=true
  containers:
   - name: ideaic-novnc
     image: "<username>/idea-ic:latest"
     mountSources: true
     volumes:
         - mountPath: "/JetBrains/ideaIC"
           name: ideaic-configuration
     ports:
         - exposedPort: 8080
     memoryLimit: "2048M"
....
