// This module is included in
//
// remote-plug-in-endpoint

[id="defining-a-launch-remote-plug-in-endpoint-in-a-meta-yaml-file_{context}"]
= Defining a launch remote plug-in endpoint in a `meta.yaml` file

Use this method to re-use images to start remote a plug-in endpoint without modifications.

.Procedure

Modify the plug-in `meta.yaml` file properties `command` and `args`:

* `command` - {prod} uses to override `Dockerfile#ENTRYPOINT`.
* `args`  - {prod} uses to override `Dockerfile#CMD`.


* Example of a YAML file with the `command` and `args` properties modified:
+
[source,yaml]
----
apiVersion: v2
category: Language
description: "Typescript language features"
displayName: Typescript
firstPublicationDate: "2019-10-28"
icon: "https://www.eclipse.org/che/images/logo-eclipseche.svg"
name: typescript
publisher: che-incubator
repository: "https://github.com/Microsoft/vscode"
title: "Typescript language features"
type: "VS Code extension"
version: remote-bin-with-override-entrypoint
spec:
  containers:
    - image: "example/fedora-for-ts-remote-plugin-without-endpoint:latest"
      memoryLimit: 512Mi
      name: vscode-typescript
      command:
        - sh
        - -c
      args:
        - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
  extensions:
    - "https://github.com/che-incubator/ms-code.typescript/releases/download/v1.35.1/che-typescript-language-1.35.1.vsix"
----

* Modify `args` instead of `command` to use an image with a wrapper script pattern and to keep a call of the `entrypoint.sh` script:
+
[source,yaml]
----
apiVersion: v2
category: Language
description: "Typescript language features"
displayName: Typescript
firstPublicationDate: "2019-10-28"
icon: "https://www.eclipse.org/che/images/logo-eclipseche.svg"
name: typescript
publisher: che-incubator
repository: "https://github.com/Microsoft/vscode"
title: "Typescript language features"
type: "VS Code extension"
version: remote-bin-with-override-entrypoint
spec:
  containers:
    - image: "example/fedora-for-ts-remote-plugin-without-endpoint:latest"
      memoryLimit: 512Mi
      name: vscode-typescript
      args:
        - sh
        - -c
        - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
  extensions:
    - "https://github.com/che-incubator/ms-code.typescript/releases/download/v1.35.1/che-typescript-language-1.35.1.vsix"
----
+
{prod} calls the `entrypoint.sh` wrapper script defined in the `ENTRYPOINT` command of the Dockerfile. The script executes `+[ ‘sh’, ‘-c”, ‘ ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}’ ]+` using the `exec “$@”` command.

[NOTE]
====
To execute a service when starting the container and also to start a remote plug-in endpoint, use `meta.yaml` with modified `command` and `args` properties. Start the service, detach the process, and start the remote plug-in endpoint, and they then work in parallel.
====
