// Module included in the following assemblies:
//
// creating-a-workspace-from-a-remote-devfile

[id="allowing-users-to-define-workspace-creation-strategy_{context}"]
= Allowing users to define workspace creation strategy


This section describes how to control the strategy of creating a {prod-short} workspace using a factory URL. {prod-short} currently supports the following options: 

* `perclick`:  `perclick` is the default creation strategy, which creates a new workspace each time the same factory URL is accepted.

* `peruser`: `peruser` creation strategy will re-use an existing workspace for second and any other subsequent acceptance of the same factory URL.

.Prerequisites

* A running instance of {prod-short}. See xref:installation-guide:installing-che.adoc[].
* The Git repository __<GIT_REPOSITORY_URL>__ is available over HTTPS.


.Procedure

pass:[<!-- vale CheDocs.TechnicalTerms = NO -->]

* Run the workspace by opening the factory URL and specify the additional policy parameter:
+
`pass:c,a,q[{prod-url}/f?url=__<GIT_REPOSITORY_URL>&policies.create=<value>__]`
+

pass:[<!-- vale CheDocs.TechnicalTerms = YES -->]
