[id="building-default-intellij-editor-images_{context}"]
= Building default IntelliJ editor images

This procedure describes how to build an IntelliJ-based editor image using the default values proposed by the build script.

.Prerequisites

* Define the following locations to publish the editor image and metadata:
+
`__<IntelliJ-container-image>__`::
Location of the IntelliJ editor image in a registry accessible by {prod-short}.
+
`__<URL_to_meta.yaml>__`::
HTTPS resource containing the editor metadata.

* The following tools are available:
** A Docker version supporting link:https://docs.docker.com/develop/develop-images/build_enhancements/[Docker BuildKit]. Docker 18.09 or greater.
** `git`
** `jq`
** Java Development Kit (JDK) version 11
** `wget`
** On the macOS platform: `+gnu-getopt+`


.Procedure

. Get a local copy of the link:https://github.com/che-incubator/jetbrains-editor-images[JetBrains Projector Editor Images repository].
+
----
$ git clone https://github.com/che-incubator/jetbrains-editor-images
$ cd jetbrains-editor-images
----

. Build JetBrains IDE based on the predefined configuration, and reply to the prompt to identify the IDE name and version to build:
+
----
$ ./projector.sh build
[info] Select the IDE package to build (default is 'IntelliJ IDEA Community'):
       1) IntelliJ IDEA Community
       2) PyCharm Community
[info] Select the IDE package version to build (default is '2020.3.3'):
       1) 2020.3.3
       2) 2020.3.2
       3) 2020.3.1
----

. To test the container, run it locally and navigate to `++http://localhost:8887++`, to access the IntelliJ-based IDE.
+
----
$ ./projector.sh run
----

. Publish the container to __<IntelliJ-container-image>__.

. Create a `+meta.yaml+` file with the following content, and publish it to `__<URL_to_meta.yaml>__`:
+
[source,yaml,subs="+quotes,macros,attributes"]
----
apiVersion: v2
publisher: <username>
name: intellij-ide
version: latest
type: Che Editor
displayName: IntelliJ-based IDE
title: IntelliJ-based IDE as Editor for Eclipse Che
description: IntelliJ-based IDE running using Projector
icon: https://www.jetbrains.com/apple-touch-icon.png
category: Editor
repository: https://github.com/che-incubator/jetbrains-editor-images
firstPublicationDate: "2021-04-10"
spec:
  endpoints:
   -  name: "intellij"
      public: true
      targetPort: 8887
      attributes:
        protocol: http
        type: ide
        path: /projector-client/index.html?backgroundColor=434343&wss
  containers:
   - name: intellij-ide
     image: "__<IntelliJ-container-image>__"
     mountSources: true
     volumes:
         - mountPath: "/home/projector-user"
           name: projector-user
     ports:
         - exposedPort: 8887
     memoryLimit: "4096M"
----

.Additional resources

* xref:using-intellij-based-ides.adoc[]
* link:https://github.com/che-incubator/jetbrains-editor-images[JetBrains Projector Editor Images repository]
* link:https://docs.docker.com/develop/develop-images/build_enhancements/[Docker BuildKit]
