// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-a-file-into-a-workspace-container_{context}"]
= Mounting a secret as a file into a workspace container

WARNING: On 
ifeval::["{project-context}" == "che"]
{platforms-name} older than v1.13 and
endif::[]
OpenShift {ocp3-ver}, secrets mounted as a file override volume mounts defined in the devfile.

A secret can be mounted from the user's {orch-namespace} as a file in single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod-short}.
+
To install an instance of {prod-short}, see {link-installing-an-instance}.

.Procedure

To mount a secret as a file, complete the following steps as shown in the next example:

. Create a new {platforms-name} secret in the {platforms-namespace} of the {prod-short} workspace.
. Match the secret's `labels` to the set of labels configured in the `che.workspace.provision.secret.labels` property of {prod-short}.
. Define the default behavior for mounting secrets in the `automount-workspace-secret` annotation, which takes a boolean value:
** `'true'` enables automatic mounting into all workspace containers.
** `'false'` disables automatic mounting into all workspace containers. To mount a secret, a user must request it in the devfile component by using the `automountWorkspaceSecrets:true` property.
. Set a `mount-path` for the file.
. Include the `mount-as: file` annotation.
. Add the file's name in the secret's `data` field.

NOTE: A {orch-name} secret can contain several `data` items. The names of `data` items must match the name of the secret's file mounted into the container.

.Example: Mounting a secret as a file
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org <1>
    app.kubernetes.io/component: workspace-secret <2>
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true' <3>
    che.eclipse.org/mount-path: {prod-home}/.m2/ <4>
    che.eclipse.org/mount-as: file <5>
data:
  settings.xml: __<base64-encoded_value>__ <6>
----
<1> Default label.
<2> Default label.
<3> Enabled automatic mounting into all workspace containers.
<4> Mount path, `{prod-home}/.m2/`, set for the file in all workspace containers.
<5> Included `mount-as: file` annotation.
<6> Name of the file to mount, `settings.xml`.

.Procedure

Optionally, to override the mount path of a secret for a workspace component, edit the devfile as follows:

. Declare a component alias for the containers in the override path.
. Declare an additional volume for the component.
. Use the name of the secret as the name of the volume.
. Set the new mount path for the secret as `containerPath`.
+
.Example: Overriding a secret's mount path for a workspace component
[source,yaml,subs="+quotes"]
----
  ...
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   volumes:
     - name: <__secret_name__>
       containerPath: /__<new_mount_path>__
   ...
----

.Additional resources
ifeval::["{project-context}" == "che"]
* For more information about creating secrets, see link:https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret[Kubernetes Documentation].
endif::[]
* xref:mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container.adoc#the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container[The use of annotations in the process of mounting a secret into a workspace container]
* xref:installation-guide:mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container.adoc[]
//overlapping content in doc xref'ed on previous line