// Module included in the following assemblies:
//
// making-a-workspace-portable-using-a-devfile

[id="writing-a-devfile-for-your-project_{context}"]
= Writing a devfile for a project

This section describes how to create a minimal devfile for your project and how to include more than one projects in a devfile.

[id="preparing-a-minimal-devfile_{context}"]
== Preparing a minimal devfile

A minimal devfile sufficient to run a workspace consists of the following parts:

* Specification version
* Name

.Example of a minimal devfile with no project
[source,yaml]
----
apiVersion: 1.0.0
metadata:
  name: minimal-workspace
----

Without any further configuration, a workspace with the default editor is launched along with its default plug-ins, which are configured on the {prod-short} Server. Che-Theia is configured as the default editor along with the *{prod-short} Machine Exec* plug-in. When launching a workspace within a Git repository using a factory, the project from the given repository and branch is be created by default. The project name then matches the repository name.

Add the following parts for a more functional workspace:

* List of components: Development components and user runtimes
* List of projects: Source code repositories
* List of commands: Actions to manage the workspace components, such as running the development tools, starting the runtime environments, and others

.Example of a minimal devfile with a project
[source,yaml]
----
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/spring-projects/spring-petclinic.git'
components:
  - type: chePlugin
    id: redhat/java/latest
----


[id="specifying-multiple-projects-in-a-devfile_{context}"]
== Specifying multiple projects in a devfile

A single devfile can define multiple projects, which are cloned to the desired destination. These projects are created inside a user’s workspace after the workspace is started.

For each project, specify the following:

* The type of the source repository - this can be .git or .zip. For additional information, see the xref:devfile-reference_making-a-workspace-portable-using-a-devfile[Devfile reference] section.

* The location of the source repository - an URL to a Git repository or ZIP archive.

* Optionally, the directory to which the project is cloned. If none is specified, the default directory is used, which is a directory that matches the project name or project Git repository.



.Example of a devfile with two projects

In the following example, the projects `frontend` and `backend` act as examples of a user's projects. Each project is located in a separate repository. 

* The `backend` project has a specific requirement to be cloned into the `src/github.com/__<github-organization>__/__<backend>__/` directory under the source root, implicitly defined by the {prod-short} runtime. 

* The `frontend` project will be cloned into the `__<frontend/>__` directory under the source root.

[source,yaml,subs="+quotes"]
----
apiVersion: 1.0.0
metadata:
  name: example-devfile
projects:
- name: __<frontend>__
  source:
    type: git
    location: https://github.com/__<github-organization>__/__<frontend>__.git
- name: __<backend>__
  clonePath: src/github.com/__<github-organization>__/__<backend>__
  source:
    type: git
    location: https://github.com/__<github-organization>__/__<backend>__.git
----


.Additional resources

For a detailed explanation of all devfile component assignments and possible values, see:

* link:https://github.com/redhat-developer/devfile[Specification repository]
* link:https://redhat-developer.github.io/devfile/devfile[Detailed json-schema documentation]

These sample devfiles are a good source of inspiration:

* link:https://github.com/eclipse/che-devfile-registry/tree/master/devfiles[Sample devfiles for {prod} workspaces used by default in the user interface].
* link:https://github.com/redhat-developer/devfile/tree/master/samples[Sample devfiles for {prod} workspaces from Red Hat Developer program].
