// Module included in the following assemblies:
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as an environment variable into a workspace container

In {prod-short}, you can mount the {platforms-name} secret from your {orch-namespace} as an environment variable (or variables) in single-workspace or multiple-workspace containers.

.Prerequisites

* A running instance of {prod-short}. See {link-installing-an-instance}.

.Procedure

. Create a new secret in the {platforms-namespace} where a new workspace is deployed.
. Define the default behavior for mounting secrets in the `automount-workspace-secret` annotation, which takes a boolean value:
** `'true'` enables automatic mounting into all workspace containers.
** `'false'` disables automatic mounting into all workspace containers. To mount a secret, a user must request it in the devfile component by using the `automountWorkspaceSecrets:true` property.
. Set the name of the secret's environment variable in the `env-name` annotation.
. Include the `mount-as: env` annotation.
. Match the secret's `labels` to the set of labels configured in the `che.workspace.provision.secret.labels` property of {prod-short}.
. Set the secret's key-value pair in the secret's `data` field.
. If the secret must have multiple key-value pairs in the `data` field, set a different environment variable name with the `<__key__>_env-name` annotation for each key-value pair.
+
NOTE: The maximum length of an annotation name in a {orch-name} secret is 63 characters, of which 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the secret.

.Example: Mounting a secret as an environment variable
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true' <1>
    che.eclipse.org/env-name: FOO_ENV <2>
    che.eclipse.org/mount-as: env <3>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org <4>
    app.kubernetes.io/component: workspace-secret <5>
data:
  mykey: myvalue <6>
----
<1> Enables automatic mounting into all workspace containers.
<2> Provisions the `FOO_ENV` environment variable into all workspace containers.
<3> Mounts the secret as a variable.
<4> Matches the configured default label.
<5> Matches the configured default label.
<6> Provisions the `myvalue` data key value into all workspace containers.

.Example: Mounting a secret with multiple key-value pairs in the `data` field
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV <1>
    che.eclipse.org/otherkey_env-name: OTHER_ENV <2>
  labels:
   ...
data:
  mykey: myvalue <3>
  otherkey: othervalue <4>
----
<1> Environment variable provisioned with the `myvalue` value.
<2> Environment variable provisioned with the `othervalue` value.
<3> Key-value pair provisioned with the `FOO_ENV` environment variable.
<4> Key-value pair provisioned with the `OTHER_ENV` environment variable.

.Additional resources
ifeval::["{project-context}" == "che"]
* For more information about creating secrets, see link:https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret[Kubernetes Documentation].
endif::[]
* xref:mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container.adoc#the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container_{context}[]
* xref:installation-guide:mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container.adoc[]
//overlapping content in doc xref'ed on previous line
