[id="using-jetbrains-webstorm_{context}"]
= Using WebStorm

.Procedure

. Clone the link:https://github.com/che-incubator/jetbrains-editor-images/tree/cdc002c5c1a9f7376acc40b0b04039b413d4bf04[jetbrains-editor-images] repository, needed for building IntelliJ Idea Community Edition located under the _che-incubator_ organization.

. Build the image:
+
----
$ podman build -t webstorm --build-arg PRODUCT_NAME=WebStorm .
----
+
This command builds an image with a `2020.2.3` version by default.

. Tag and push the built image to a user repository:
+
[subs="+quotes"]
----
$ podman tag webstorm:latest __<username>__/webstorm:latest
$ podman push __<username>__/webstorm:latest
----

. Provision the activation code for offline use to be able to use WebStorm with a registered license. See section xref:provisioning-jetbrains-activation-code-for-offline-use.adoc[].

. Create a workspace with the following `workspace.yaml` and `meta.yaml` files:
+
* `workspace.yaml` – workspace configuration. Do not forget to provide a correct URL to the `meta.yaml` file:
+
[source,yaml,subs="+quotes"]
----
metadata:
  name: che-webstorm
components:
  - type: cheEditor
    reference: '__<URL to meta.yaml>__'
    alias: webstorm-editor
    automountWorkspaceSecrets: true
apiVersion: 1.0.0
----
+
NOTE: In the current workspace definition, there is a new property: `automountWorkspaceSecrets: true`. This property instructs {prod} to provision secrets into a specific component. In this case, it provisions it into the {prod-short} editor based on IntelliJ Idea Ultimate Edition. This parameter is *mandatory* to successfully register the IDE with an activation code for offline use.

* `meta.yaml` – {prod-short} editor configuration. Do not forget to replace `<username>` with the user name of the repository to which the image is pushed:
+
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v2
publisher: _<username>_
name: webstorm-NOVNC
version: 2020.2.3
type: Che Editor
displayName:  WebStorm
title:  WebStorm (in browser using noVNC) as editor for {prod}
description:  WebStorm running on the Web with noVNC
icon: https://resources.jetbrains.com/storage/products/webstorm/img/meta/webstorm_logo_300x300.png
category: Editor
repository: https://github.com/che-incubator/che-editor-intellij-community
firstPublicationDate: "2020-10-27"
spec:
  endpoints:
   - name: "intellij"
     public: true
     targetPort: 8080
     attributes:
       protocol: http
       type: ide
       path: /vnc.html?resize=remote&autoconnect=true&reconnect=true
  containers:
   - name: webstorm-novnc
     image: "__<username>__/webstorm:latest"
     mountSources: true
     volumes:
      - mountPath: "/JetBrains/WebStorm"
        name: webstorm-configuration
     ports:
      - exposedPort: 8080
     memoryLimit: "2048M"
----
