// Module included in the following assemblies:
//
// configuring-a-workspace-using-a-devfile

[id="creating-a-workspace-using-{prod-cli}-and-a-local-devfile_{context}"]
= Creating a workspace using {prod-cli} and a local devfile

A {prod-short} workspace can be created by pointing the `{prod-cli}` tool to a locally stored devfile. The {prod-short} instance then uses the discovered devfile to build a workspace.

.Prerequisites
* A running instance of {prod}. To install an instance of {prod}, see xref:overview:che-quick-starts.adoc[].
* The {prod-short} CLI management tool. See xref:overview:using-the-chectl-management-tool.adoc[].
* The devfile is available on the local filesystem in the current working directory. See xref:making-a-workspace-portable-using-a-devfile.adoc[] for detailed information about creating and using devfiles.
+
.Example
Download the `devfile.yaml` file from the link:https://github.com/eclipse/che/blob/master/devfile.yaml[GitHub repository]  to the current working directory.

.Procedure
. Run a workspace from a devfile using the `workspace:start` parameter with the `{prod-cli}` tool as follows:

[subs="+attributes,+quotes"]
----
$ {prod-cli} workspace:start --devfile=devfile.yaml
----
