// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-a-file-into-a-workspace-container_{context}"]
= Mounting a secret as a file into a workspace container

WARNING: On 
ifeval::["{project-context}" == "che"]
{platforms-name} older than v1.13 and
endif::[]
OpenShift {ocp3-ver}, secrets mounted as file overrides volume mounts defined in the devfile.

A secret can be mounted from the user's {orch-namespace} as a file in single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod-short}.
+
To install an instance of {prod-short}, see {link-installing-an-instance}.

.Procedure

To mount a secret as a file, complete the following steps in the devfile as shown in the next example:

. Create a new {platforms-name} secret in the {platforms-namespace} where a {prod-short} workspace will be created.
. Match the secret's `labels` to the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}.
. Define the default behavior for mounting secrets in the `/automount-workspace-secret` annotation, which takes a boolean value:
** `'true'` enables automatic mounting into all workspace containers.
** `'false'` disables automatic mounting into all workspace containers. To mount a secret, a user must request it in the devfile component by using the `automountWorkspaceSecrets:true` property.
. Provide a `mount-path` for the file.
. Include the `mount-as: file` annotation.
. Add the file name under `data`.

.Example:
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org <1>
    app.kubernetes.io/component: workspace-secret <2>
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true' <3>
    che.eclipse.org/mount-path: {prod-home}/.m2/ <4>
    che.eclipse.org/mount-as: file <5>
data:
  settings.xml: __<base64 encoded data content here>__ <6>
----
<1> Default label.
<2> Default label.
<3> Enables automatic mounting into all workspace containers. Developers can override this default in a devfile.
<4> `{prod-home}/.m2/` is the mount path of all workspace containers.
<5> The `mount-as: file` annotation.
<6> Mounts the `settings.xml` file. 
+
NOTE: The `data` of the {orch-name} secret can contain several items. The names of these items must match the desired file name mounted into the container.

.Procedure

Optionally, override the mount path of the secret for a workspace component by editing the devfile as follows:

. Declare a component alias for the containers in the override path.
. Declare an additional volume for the component.
. Use the name of the secret as the name of the volume.
. Provide the new mount path for the secret as `containerPath`.
+
.Example:
[source,yaml,subs="+quotes"]
----
  ...
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   volumes:
     - name: <__secret_name__>
       containerPath: /<__new_mount_path__>
   ...
----

//Additional resouces must be added here pointing to how to create a secret