// Module included in the following assemblies:
//
// authenticating-on-scm-server-with-a-personal-access-token

[id="configuring_bitbucket_authentication_{context}"]

= Authenticating on Bitbucket servers

The following section describes the configuration needed to enables {prod-short} to use Bitbucket (BB) repositories with Git cloning operations.

BB authentication is based on using personal access tokens. Each BB user is able to request several personal access tokens with different attributes, such as names, permissions, or expiration times. Those tokens can also be used to sign BB REST API calls and perform Git repository operations.

* {prod-short} users may use public or private repositories on the BB Source Code Management (SCM) system as a source of their projects.

NOTE: Before configuring the OAuth 1 authentication that is required for reading from private repositories and writing to both private and public repositories, configure the BB server with {prod-short} first. To do so, see the Prerequisites section below.


.Additional resources

For a remote Git repository that uses a self-signed certificate, add an additional server configuration. See xref:installation-guide:deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc[].


.Prerequisites

* A BB endpoint has been registered with {prod-short}. Follow the xref:administration-guide:configuring-authorization#configuring_bitbucket_servers_{context}[Configuring Bitbucket servers] procedure and register a BB server using the `CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS` YAML secret property.

.Procedure

. Configure the OAuth 1 authentication by following the xref:administration-guide:configuring-authorization#proc_configuring-bitbucket-server-oauth1_{context}[Configuring Bitbucket Server OAuth 1] procedure.
