[id="building-custom-intellij-editor-images_{context}"]
= Building custom IntelliJ editor images

This procedure describes how to build an IntelliJ-based editor image using a custom archive and a custom image name.

.Prerequisites

* The `git`, `jq`, and `wget` tools are available.

* Docker version 18.09 or greater, supporting link:https://docs.docker.com/develop/develop-images/build_enhancements/[Docker BuildKit].

* Java Development Kit (JDK) version 11 is available.

* On the macOS platform: the `+gnu-getopt+` tool is available.

* The build platform has at least 2 GB of RAM.

.Procedure

. Get a local copy of the link:https://github.com/che-incubator/jetbrains-editor-images[JetBrains Projector Editor Images repository].
+
----
$ git clone https://github.com/che-incubator/jetbrains-editor-images
$ cd jetbrains-editor-images
----

. Build the container using build parameters:
+
[subs="+quotes,macros,attributes"]
----
$ ./projector build --tag __<tag>__ --url __<URL>__
----
+
`--tag __<tag>__`::
Tag to apply to the image after build.
+
`--url __<URL>__`::
URL pointing to an archive of the custom IntelliJ-based distribution. The editor version can be at most 2020.3 because Projector doesn't support later versions. The archive must target the Linux platform, be in `+tar.gz+` format, and include JetBrains Runtime (JBR). 
+
.Building the Docker image with IntelliJ IDEA Community 2020.3.3
====
----
./projector.sh build --tag che-idea:2020.3.3 \
  --url https://download-cdn.jetbrains.com/idea/ideaIC-2020.3.3.tar.gz
----
====
+
.Building the Docker image with PyCharm Community 2020.3.5
====
----
$ ./projector.sh build --tag che-pycharm:2020.3.5 \
  --url https://download.jetbrains.com/python/pycharm-community-2020.3.5.tar.gz
----
====
+
.Building the Docker image with WebStorm 2020.3.3
====
----
$ ./projector.sh build --tag che-webstorm:2020.3.3 \
  --url https://download.jetbrains.com/webstorm/WebStorm-2020.3.3.tar.gz
----
====
+
.Building the Docker image with IntelliJ IDEA Ultimate 2020.2.2
====
----
$ ./projector.sh build --tag che-idea-ultimate:2020.2.2 \
  --url https://download.jetbrains.com/idea/ideaIU-2020.2.2.tar.gz
----
====

. To test the container, run the container locally, and navigate to `++http://localhost:8887++` to access the JetBrains IDE.
+
[subs="+quotes,macros,attributes"]
----
$ ./projector.sh run __<tag>__
----
+
.Testing the Docker image with IntelliJ IDEA Community 2020.3.3
====
----
$ ./projector.sh run che-idea:2020.3.3
----
====
+
.Testing the Docker image with PyCharm 2020.3.5
====
----
$ ./projector.sh run che-pycharm:2020.3.5
----
====
+
.Testing the Docker image with WebStorm 2020.3.3
====
----
$ ./projector.sh run che-webstorm:2020.3.3
----
====
+
.Testing the Docker image with IntelliJ IDEA Ultimate 2020.2.2
====
----
$ ./projector.sh run che-idea-ultimate:2020.2.2
----
====

. Publish the IntelliJ editor image to a registry accessible by {prod-short}, and remember the location: __<IntelliJ-container-image>__.

. Create a `+meta.yaml+` file with the following content:
+
[source,yaml,subs="+quotes,macros,attributes"]
----
apiVersion: v2
publisher: __<publisher>__ <1>
name: intellij-ide
version: latest
type: Che Editor
displayName: IntelliJ-based IDE
title: IntelliJ-based IDE as Editor for Eclipse Che
description: IntelliJ-based IDE running using Projector
icon: https://www.jetbrains.com/apple-touch-icon.png
category: Editor
repository: https://github.com/che-incubator/jetbrains-editor-images
firstPublicationDate: "2021-04-10"
spec:
  endpoints:
   -  name: "intellij"
      public: true
      targetPort: 8887
      attributes:
        protocol: http
        type: ide
        path: /projector-client/index.html?backgroundColor=434343&wss
  containers:
   - name: intellij-ide
     image: "__<IntelliJ-container-image>__" <2>
     mountSources: true
     volumes:
         - mountPath: "/home/projector-user"
           name: projector-user
     ports:
         - exposedPort: 8887
     memoryLimit: "4096M"
----
<1> __<publisher>__: Your publisher name.
<2> __<IntelliJ-container-image>__: Location of the IntelliJ editor image in a registry accessible by {prod-short}.

. Publish the `meta.yaml` file to an HTTPS resource accessible by {prod-short}: `__<URL_to_meta.yaml>__`.

.Additional resources

* xref:using-intellij-based-ides.adoc[]
* link:https://github.com/che-incubator/jetbrains-editor-images[JetBrains Projector Editor Images repository]
* link:https://docs.docker.com/develop/develop-images/build_enhancements/[Docker BuildKit]
