[id="setting-up-che-editor-yaml_{context}"]
= Setting up che-editor.yaml

To define the same in-browser IDE for all workspaces that will clone the same remote Git repository of your project, you can use the `che-editor.yaml` file. This is convenient when, as a developer using {prod-short}, you clone your personal fork of the project repository into your {prod-short} user's workspaces, and this way you don't have to specify your IDE every time you start another workspace with a clone of that repository.

.Prerequisites

* The IDE `id` from the table in xref:selecting-a-workspace-ide.adoc[].

.Procedure

* In the remote Git repository of your project, create a `/.che/che-editor.yaml` file that specifies the `id` of your selected IDE. For example:
+
[source,yaml]
----
id: che-incubator/che-idea/latest
----

.Verification

. Visit the URL for starting a new workspace. See xref:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[].
. Verify that the selected in-browser IDE loads in the browser tab of the started workspace.

