// Module included in the following assemblies:
//
// creating-a-workspace-from-a-remote-devfile

[id="allowing-users-to-define-workspace-creation-strategy_{context}"]
= Allowing users to define workspace creation strategy


As a developer, you can configure {prod-short} to create a new workspace each time it accepts a factory URL, or to reuse the existing workspace if a user already has one.

{prod-short} supports the following options: 

* `perclick`:  The default strategy, which creates a new workspace each time a given factory URL is accepted.

* `peruser`: Initially, a workspace is created using a factory URL. Other user's calls then re-use the particular workspace created by the factory URL (1 factory = 1 workspace).

.Prerequisites

* A running instance of {prod-short}. See xref:installation-guide:installing-che.adoc[].
* The Git repository __<GIT_REPOSITORY_URL>__ is available over HTTPS.


.Procedure

pass:[<!-- vale CheDocs.TechnicalTerms = NO -->]

* Run the workspace by opening the factory URL and specify the additional strategy parameter:
+
`pass:c,a,q[{prod-url}/f?url=__<GIT_REPOSITORY_URL>&policies.create=<value>__]`
+

pass:[<!-- vale CheDocs.TechnicalTerms = YES -->]
