[id="provisioning-jetbrains-activation-code-for-offline-use_{context}"]
= Provisioning the JetBrains offline activation code

Some editions of JetBrains IDEs require a paid subscription beyond the evaluation period, which means buying a license from JetBrains. To register a license, you need to provision to Che the JetBrains activation code for offline usage. When you renew your subscription, you will need to generate a new activation code and provision the new offline activation code.

.Prerequisites

* An active link:https://account.jetbrains.com/login[JetBrains account].
* An active link:https://www.jetbrains.com/store/comparison.html[subscription for organizations or for personal use].
* A `base64` conversion tool.
* An image containing the editor. See xref:building-images-for-ides-based-on-the-intellij-platform.adoc[].
* A workspace running with the editor. See xref:using-intellij-based-ides.adoc[].

.Procedure

. Retrieve the activation code from the JetBrains account. JetBrains provides a zip archive with two types of the activation code. Use the `<License{nbsp}ID>{nbsp}-{nbsp}for{nbsp}2018.1{nbsp}or{nbsp}later.txt` file. Save the content in the `jetbrains_license.txt` file.

. Run the `base64` command on `jetbrains_license.txt` to convert the activation code to base64 encoding for use as __<base64_encoded_activation_code>__ in the next step.
+
----
$ base64 jetbrains_license.txt
----

. Create a `secret.yaml` file defining the {orch-name} Secret to provision the activation code to {prod-short}.
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: v1
kind: Secret
metadata:
  name: jetbrains-offline-activation-code
  labels:
    app.kubernetes.io/component: workspace-secret
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/automount-workspace-secret: 'false' <1>
    che.eclipse.org/mount-path: /tmp/
    che.eclipse.org/mount-as: file
data:
  idea.key: __<base64_encoded_activation_code>__
  pycharm.key: __<base64_encoded_activation_code>__
  webstorm.key: __<base64_encoded_activation_code>__
  phpstorm.key: __<base64_encoded_activation_code>__
  goland.key: __<base64_encoded_activation_code>__
----
+
<1> `+che.eclipse.org/automount-workspace-secret: 'false'+`: disables the mounting process until a workspace component explicitly requests it with the `+automountWorkspaceSecrets: true+` property.

. Apply the {orch-name} Secret to the {orch-name} {orch-namespace} running the workspace.
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f secret.yaml
----

. To mount the activation codes into a workspace, update the workspace devfile configuration to set `+automountWorkspaceSecrets: true+`.
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
components:
  - type: cheEditor
    automountWorkspaceSecrets: true
    reference: "__<URL_to_meta.yaml>__"
----

. Restart the workspace.

