[id="downloading-different-versions-of-gradle_{context}"]
= Downloading different versions of Gradle

The recommended way to download any version of Gradle is by using the Gradle Wrapper script. If your project does not have a `gradle/wrapper` directory, run `$ gradle wrapper` to configure the Wrapper.

.Prerequisites

* The Gradle Wrapper is present in your project.

.Procedure

To download a Gradle version from a non-standard location, change your Wrapper settings in `/projects/<your_project>/gradle/wrapper/gradle-wrapper.properties`:

 * Change the `distributionUrl` property to point to a URL of the Gradle distribution ZIP file:
+
----
properties
distributionUrl=http://<url_to_gradle>/gradle-6.1-bin.zip
----

Alternatively, you may place a Gradle distribution zip file locally in `/project/gradle` in your workspace.

* Change the `distributionUrl` property to point to a local address of the Gradle distribution zip file:
+
----
properties
distributionUrl=file\:/projects/gradle/gradle-6.1-bin.zip
----
