// Module included in the following assemblies:
//
// using-gradle-artifact-repositories

[id="configuring-global-gradle-repositories_{context}"]
= Configuring global Gradle repositories

Use an initialization script to configure global repositories for the workspace.
Gradle performs extra configuration before projects are evaluated, and this configuration is used in each Gradle project from the workspace.

.Procedure

To set global repositories for Gradle that could be used in each Gradle project in the workspace, create an `init.gradle` script in the `~/.gradle/` directory:

[source,groovy]
----
allprojects {
  repositories {
    mavenLocal ()
    maven {
      url "http://repo.mycompany.com/maven"
      credentials {
        username "admin"
        password "my_password"
      }
    }
  }
}
----

This file configures Gradle to use a local Maven repository with the given credentials.

[NOTE]
====
The `~/.gradle` directory does not persist in the current Java plug-in versions, so you must create the `init.gradle` script at each workspace start in the Java plug-in sidecar container.
====
