
[id="listing-workspaces"]
= Listing all workspaces

As a user, you can list your workspaces by using the command line.

.Prerequisites

* An active `{orch-cli}` session with permissions to `get` the `DevWorkspace` resources in your {orch-namespace} on the cluster. See {orch-cli-link}.

* You know the relevant {prod-short} user namespace on the cluster.
+
TIP: You can visit `pass:c,a,q[{prod-url}]/api/kubernetes/namespace` to get your {prod-short} user namespace as `name`.

* You are in the {prod-short} user namespace on the cluster.
+
[TIP]
====
On OpenShift, you can use link:https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/developer-cli-commands.html#oc-project[the `oc` command-line tool] to display your current namespace or switch to a namespace.
====

.Procedure

* To list your workspaces, enter the following on a command line:
+
[source,subs="+attributes"]
----
$ {orch-cli} get devworkspaces
----
+
.Output
====
----
NAMESPACE   NAME                 DEVWORKSPACE ID             PHASE     INFO
user1-dev   spring-petclinic     workspace6d99e9ffb9784491   Running   https://url-to-workspace.com
user1-dev   golang-example       workspacedf64e4a492cd4701   Stopped   Stopped
user1-dev   python-hello-world   workspace69c26884bbc141f2   Failed    Container tooling has state CrashLoopBackOff
----
====

[TIP]
====
You can view *PHASE* changes live by adding the `--watch` flag to this command.
====

[NOTE]
====
Users with administrative permissions on the cluster can list all workspaces from all {prod-short} users by including the `--all-namespaces` flag.
====