[id="creating-an-image-pull-secret-from-a-.dockercfg-file_{context}"]
= Creating an image pull Secret from a `.dockercfg` file

If you already store the credentials for the private container registry in a `.dockercfg` file, you can use that file to create an image pull Secret.

.Prerequisites

* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* For CLI users: The `{orch-cli}` and link:https://www.gnu.org/software/coreutils/base64[`base64`] command line tools are installed in the operating system you are using.

.Procedure

. Encode the `.dockercfg` file to Base64. 
+
[TIP]
====
CLI users can use the `base64` command as needed:

`$ cat .dockercfg | base64 | tr -d '\n'`
====

. Create a new {orch-name} Secret in your user {orch-namespace}:

+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: v1
kind: Secret
metadata:
  name: __<Secret_name>__
  labels:
    controller.devfile.io/devworkspace_pullsecret: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  .dockercfg: __<Base64_content_of_.dockercfg>__
type: kubernetes.io/dockercfg
----

. Use the CLI or GUI to apply the Secret to the {orch-name} cluster of your organization's {prod-short} instance.

+
[TIP]
====
CLI users can apply the Secret with `{orch-cli}`:

[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----
====