// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as an environment variable into a workspace container

A secret can be mounted from the user’s {orch-namespace} as an environment variable, or variables, into single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod-short}.
+
To install an instance of {prod-short}, see {link-installing-an-instance}.

.Procedure

To mount a secret as a variable

. Create a new {platforms-name} secret in the {platforms-namespace} where a {prod-short} workspace will be created.
. Define the default behavior for mounting secrets in the `/automount-workspace-secret` annotation, which takes a boolean value:
** `'true'` enables automatic mounting into all workspace containers.
** `'false'` disables automatic mounting into all workspace containers. To mount a secret, a user must request it in the devfile component by using the `automountWorkspaceSecrets:true` property.
. Include the `mount-as: env` annotation.
. Match the secret's `labels` to the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}.
+
.Example:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true' <1>
    che.eclipse.org/env-name: FOO_ENV <2>
    che.eclipse.org/mount-as: env <3>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org <4>
    app.kubernetes.io/component: workspace-secret <5>
data:
  mykey: myvalue
----
<1> Enables automatic mounting into all workspace containers. Developers can override this default in a devfile.
<2>
<3> The `mount-as: env` annotation.
<4> Default label.
<5> Default label.

+
In this example, the `FOO_ENV` environment variable and `myvalue` key value are provisioned into all workspace containers as follows:

** The secret's environment variable, `env-name`, is declared as `FOO_ENV` in the `annotations`.

** The `automount-workspace-secret` annotation with a boolean value defines the default secret mounting behavior (that can be overridden in a devfile):

*** `'true'` enables automatic mounting into all workspace containers.

*** `'false'` disables the mounting process until it is explicitly requested in a devfile component using the `automountWorkspaceSecrets:true` property.

* If the secret has more than one data key, declare an environment variable name using a `<__key__>_env-name` annotation for each data key, as shown in the following example. In this example, you provision the `myvalue` and `othervalue` data key values, and the environment variable names, `FOO_ENV` and `OTHER_ENV`, into all workspace containers.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: myvalue
  otherkey: othervalue
----

NOTE: The maximum length of an annotation name in a {orch-name} secret is 63 characters, of which 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the secret.

//Additional resouces must be added here pointing to how to create a secret