// Module included in the following assemblies:
//
// troubleshooting-che

[id="investigating-failures-at-a-workspace-start-using-the-verbose-mode_{context}"]
= Investigating failures at a workspace start using the Verbose mode

Verbose mode allows users to reach an enlarged log output, investigating failures at a workspace start.

In addition to usual log entries, the Verbose mode also lists the container logs of each workspace.


[id="restarting-a-{prod-id-short}-workspace-in-verbose-mode-after-start-failure_{context}"]
== Restarting a {prod-short} workspace in Verbose mode after start failure

This section describes how to restart a {prod-short} workspace in the Verbose mode after a failure during the workspace start. Dashboard proposes the restart of a workspace in the Verbose mode once the workspace fails at its start.


.Prerequisites

* A running instance of {prod-short}. To install an instance of {prod-short}, see {link-installing-an-instance}.

* An existing workspace that fails to start.

.Procedure

. Using Dashboard, try to start a workspace.
. When it fails to start, click on the displayed *Open in Verbose mode* link.
. Check the *Logs* tab to find a reason for the workspace failure.


[id="starting-a-{prod-id-short}-workspace-in-verbose-mode_{context}"]
== Starting a {prod-short} workspace in Verbose mode

This section describes how to start the {prod} workspace in Verbose mode.

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see xref:administration-guide:installing-che.adoc[].

* An existing workspace defined on this instance of {prod-short}.

.Procedure

. Open the *Workspaces* tab.
. On the left side of a row dedicated to the workspace, access the drop-down menu displayed as three horizontal dots and select the *Open in Verbose mode* option. Alternatively, this option is also available in the workspace details, under the *Actions* drop-down menu.
. Check the *Logs* tab to find a reason for the workspace failure.
