// Module included in the following assemblies:
//
// using-python-artifact-repositories

[id="using-self-signed-certificates-in-python-projects_{context}"]
= Using self-signed certificates in Python projects

Internal artifact repositories often do not have a self-signed TLS certificate signed by an authority that is trusted by default. They are usually signed by an internal company authority or are self-signed. Configure your tools to accept these certificates.

Python uses certificates from a file defined in the `PIP_CERT` environment variable.

.Procedure

. Obtain the certificate from the non-standard repository and place the certificate file in the `/projects/tls/rootCA.pem` file to make it accessible from all your containers.
+
[NOTE]
====
pip accepts certificates in the Privacy-Enhanced Mail (PEM) format only. Convert the certificate to the PEM format using OpenSSL if necessary.
====
+
. Configure the devfile:
+
include::example${project-context}-python-use-self-signed-cert.adoc[]