// Module included in the following assemblies:
//
// adding-{prod-id-short}-plug-in-registry-vs-code-extension-to-a-workspace

[id="adding-the-vs-code-extension-using-recommendations-{prod-id-short}_{context}"]
= Adding a VS Code extension using recommendations

.Prerequisites

* A running instance of {prod-short}. To install an instance of {prod-short}, see {link-installing-an-instance}.
* Featured VS Code extensions are available in the {prod-short} plug-in registry.

.Procedure

Open a workspace without any existing devfile using the *{prod-short} dashboard*:

Recommendations plug-in will scan files, discover languages and install VS Code extensions matching these languages.
Disable this feature by setting `extensions.ignoreRecommendations` to true in the devfile attributes.

Recommendations plug-in can suggest VS Code extensions to install when opening files. It suggests extensions allowing to work with the given files.
Enable this feature by setting `extensions.openFileRecommendations` to true in the devfile attributes.

