// Module included in the following assemblies:
//
// adding-tools-to-{prod-id-short}-after-creating-a-workspace

[id="adding-language-support-plug-in-to-the-{prod-id-short}-workspace_{context}"]
= Adding a language support plug-in to a {prod-short} workspace

This procedure describes adding a tool to an existing workspace by enabling a dedicated plug-in from the Dashboard.

To add tools that are available as plug-ins into a {prod-short} workspace, use one of the following methods:

* xref:installing-the-plug-in-from-the-plugin-tab_{context}[Enable the plug-in from the Dashboard *Plugins* tab.]
* xref:installing-the-plug-in-by-adding-content-to-the-devfile_{context}[Edit the workspace devfile from the Dashboard *Devfile* tab.]

This procedure uses the Language Support for Java plug-in as an example.

.Prerequisites

* A running instance of {prod-short}. To install an instance of {prod-short}, see {link-installing-an-instance}.

* An existing workspace defined in this instance of {prod}; see:
** xref:configuring-a-workspace-with-dashboard.adoc[]
** xref:creating-a-workspace-from-code-sample.adoc#creating-a-workspace-from-get-started-view-of-user-dashboard_{context}[Creating a workspace from Get Started view of user dashboard]

 * The workspace must be in a **stopped** state. To stop a workspace:

.. Navigate to the {prod-short} Dashboard. See xref:navigating-che-using-the-dashboard.adoc[].

.. In the *Dashboard*, click the *Workspaces* menu to open the workspaces list and locate the workspace.

.. On the same row with the displayed workspace, on the right side of the screen, click the square btn:[Stop] button to stop the workspace.

.. Wait a few seconds for the workspace to stop (the workspace's icon on the list will turn grey), then configure the workspace by clicking on it.

.Procedure

To add the plug-in from the Plug-in registry to an existing {prod-short} workspace, use one of the following methods:

[id="installing-the-plug-in-from-the-plugin-tab_{context}"]

//<<installing-the-plug-in-from-the-plugin-tab_{context}>>

** Installing the plug-in from the *Plugins* tab.
. Navigate to the *Plugins* tab. The list of available plug-ins is displayed.
. Enable the desired plug-in, for example, the Language Support for Java 11, by using the *Enable* slide-toggle. This will add the plug-in's ID to the workspace's devfile, enabling the plug-in.
. On the bottom right side of the screen, save the changes by clicking the btn:[Save] button. After changes are saved, the workspace can be restarted and will include the new plug-in.

[id="installing-the-plug-in-by-adding-content-to-the-devfile_{context}"]

//<<installing-the-plug-in-by-adding-content-to-the-devfile_{context}>>

** Installing the plug-in by adding content to the devfile.
. Navigate to the *Devfile* tab. The devfile YAML is displayed.
. Locate the `components` section of the devfile and add the following lines to add the Java language plugin with Java 8 to the workspace:
+
include::example${project-context}-java-language-support.adoc[]
+
An example of the final result:
+
include::example${project-context}-workspace-from-the-php-stack-java-language-support.adoc[]
. On the bottom right side of the screen, save the changes by clicking the btn:[Save] button. After changes are saved, the workspace can be restarted and will include the new plug-in.


.Additional resources

* link:https://redhat-developer.github.io/devfile/devfile[Devfile specifications]
