

[id="using-a-git-credentials-store"]
= Using a Git credentials store

If the administrator of your organization's {prod-short} instance has not configured xref:administration-guide:oauth-for-github-gitlab-or-bitbucket.adoc[OAuth for GitHub, GitLab, or Bitbucket], you can apply your Git credentials store as a {kubernetes} Secret.

Mounting your Git credentials store as a Secret results in the {devworkspace} Operator applying your Git credentials to the `.gitconfig` file in the workspace container.

Apply the {kubernetes} Secret in your user {orch-namespace} of the {orch-name} cluster of your organization's {prod-short} instance.

When you apply the Secret, a Git configuration file with the path to the mounted Git credentials store is automatically configured and mounted to the `{devworkspace}` containers in the cluster at `/etc/gitconfig`. This makes your Git credentials store available in your workspaces.

.Prerequisites

* An active `{orch-cli}` session, with administrative permissions, to the {orch-name} cluster. See {orch-cli-link}.

* The link:https://www.gnu.org/software/coreutils/base64[`base64`] command line tools are installed in the operating system you are using.

.Procedure

. In your home directory, locate and open your `.git-credentials` file if you already have it. Alternatively, if you do not have this file, save a new `.git-credentials` file, using the link:https://git-scm.com/docs/git-credential-store#_storage_format[Git credentials storage format]. Each credential is stored on its own line in the file:
+
[subs="+quotes,+attributes"]
----
https://__<username>__:__<token>__@__<git_server_hostname>__
----

+
.A line in a `.git-credentials` file
====
[subs="+quotes,+attributes,+macros"]
----
pass:a,c,q[https://trailblazer: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@github.com]
----
====

. Select credentials from your `.git-credentials` file for the Secret. Encode the selected credentials to Base64 for the next step.
+
[TIP]
====
* To encode all lines in the file:
+
`$ cat .git-credentials | base64 | tr -d '\n'`

* To encode a selected line:
+
`$ echo -n '__<copied_and_pasted_line_from_.git-credentials>__' | base64`
====

. Create a new {orch-name} Secret in your user {orch-namespace}.
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-secret
  labels:
    controller.devfile.io/git-credential: 'true' <1>
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-path: /etc/secret <2>
data:
  credentials: __<Base64_content_of_.git-credentials>__ <3>
----
+
<1> The `controller.devfile.io/git-credential` label marks the Secret as containing Git credentials.
<2> A custom absolute path in the `{devworkspace}` containers. The Secret is mounted as the `credentials` file at this path. The default path is `/`.
<3> The selected content from `.git-credentials` that you encoded to Base64 in the previous step.
+
[TIP]
====
You can create and apply multiple Git credentials Secrets in your user {orch-namespace}. All of them will be copied into one Secret that will be mounted to the `{devworkspace}` containers. For example, if you set the mount path to `/etc/secret`, then the one Secret with all of your Git credentials will be mounted at `/etc/secret/credentials`. You must set all Git credentials Secrets in your user {orch-namespace} to the same mount path. You can set the mount path to an arbitrary path because the mount path will be automatically set in the Git configuration file configured at `/etc/gitconfig`.
====

. Apply the Secret.
+
[source,terminal,subs="+quotes,+attributes"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----


