// Module included in the following assemblies:
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

[id="mounting-a-secret-as-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as an environment variable into a workspace container

In {prod-short}, you can mount the {platforms-name} secret from your {orch-namespace} as an environment variable (or variables) in single-workspace or multiple-workspace containers.

.Prerequisites

* A running instance of {prod-short}. See {link-installing-an-instance}.

.Procedure

. Create a new secret in the {platforms-namespace} where a new workspace is deployed.
. Define the default behavior for mounting secrets in the `automount-workspace-secret` annotation, which takes a string value:
** `'true'` enables automatic mounting into all workspace containers.
** `'false'` disables automatic mounting into all workspace containers. (To mount a secret, a user must request it in the devfile component by using the `automountWorkspaceSecrets:true` property.)
. Set the name of the environment variable of the secret in the `env-name` annotation.
. Include the `mount-as: env` annotation.
. Match the `labels` of the secret to the set of labels configured in the `che.workspace.provision.secret.labels` property of {prod-short}.
. Set the key-value pair of the secret in the `data` field of the secret.
. To set multiple key-value pairs in the `data` field of the secret, use a different environment variable name in the `<__key__>_env-name` annotation format for each key-value pair.

.Example: Mounting a secret as an environment variable
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: v1
kind: Secret
metadata:
  name: __<secret_name>__
  annotations: <1>
    che.eclipse.org/automount-workspace-secret: 'true' <2>
    che.eclipse.org/mount-as: env <3>
    che.eclipse.org/__<key_1>___env-name: __<VAR_1>__ <4>
    che.eclipse.org/__<key_2>___env-name: __<VAR_2>__ <5>
  labels: <6>
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
data:
  __<key_1>__: __<base64_encoded_value_1>__ <7>
  __<key_2>__: __<base64_encoded_value_2>__ <8>
----
<1> See link:https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set[Syntax and character set] for annotations.
<2> Enables automatic mounting into all workspace containers.
<3> Mounts the secret as an environment variable. 
<4> Provisions the `__<VAR_1>__` environment variable into all workspace containers using `__<key_1>__`.
<5> Provisions the `__<VAR_2>__` environment variable into all workspace containers using `__<key_2>__`.
<6> DRAFT: Matches the configured default label. xref:
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#devfile-defaults
<7> Provisions the `__<value_1>__` data key value into all workspace containers.
<8> Provisions the `__<value_2>__` data key value into all workspace containers.

include::snip_tip-annotation-name.adoc[]

.Additional resources
ifeval::["{project-context}" == "che"]
* For more information about creating secrets, see link:https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret[Kubernetes Documentation].
endif::[]
* xref:mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container.adoc#the-use-of-annotations-in-the-process-of-mounting-a-secret-into-a-workspace-container_{context}[]
* xref:installation-guide:mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container.adoc[]
//overlapping content in doc xref'ed on previous line
