
[id="creating-workspaces"]
= Creating workspaces

It is recommended however, for users to create workspaces using the {prod-short} Dashboard instead of using {orch-name} APIs to manually create `DevWorkspace` and `DevWorkspaceTemplate` custom resources.

This is because creating workspaces using the {prod-short} Dashboard helps {prod-short} and its components convert the workspace project's devfile to `DevWorkspace` and `DevWorkspaceTemplate` custom resources on the cluster.

Creating workspaces using the {prod-short} dashboard allows {prod-short} to make the following additions to the newly created `DevWorkspaces`:

* Recognition of configurations in `spec.devEnvironments` specified in the `CheCluster` custom resource including:
** persistent storage strategy specified with `devEnvironments.storage`
** default editor specified with `devEnvironments.defaultEditor`
** default plugins specified with `devEnvironments.defaultPlugins`
** container build configuration specified with `devEnvironments.containerBuildConfiguration`
* Recognition of the `DevWorkspaceOperatorConfig` configuration managed by {prod-short}

Because workspaces on the {orch-name} cluster are represented by custom resources, you can create workspaces with {orch-name} APIs by applying custom resources to the cluster.

.Prerequisites

* An active `{orch-cli}` session with permissions to create `DevWorkspace` and `DevWorkspaceTemplate` resources in your {orch-namespace} on the {orch-name} cluster. See {orch-cli-link}.

NOTE: For admins creating workspaces for users, the `DevWorkspace` and `DevWorkspaceTemplate` custom resources should be created in a user namespace that is provisioned by {prod-short} or provisioned by the admin. See xref:administration-guide:configuring-namespace-provisioning.adoc[].

.Procedure

. Create a `DevWorkspaceTemplate` for the editor.
+
.Creating a `DevWorkspaceTemplate` named `che-code` for the link:https://github.com/microsoft/vscode[Microsoft Visual Studio Code - Open Source] IDE
====
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: che-code#<1>
  namespace: __<user_{orch-namespace}>__#<2>
spec:
  commands:
    - apply:
        component: vscode-injector
      id: init-container-command
  components:
    - container:
        command:
          - /entrypoint-init-container.sh
        cpuLimit: 500m
        cpuRequest: 30m
        image: 'quay.io/che-incubator/che-code:insiders'
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        sourceMapping: /projects
        volumeMounts:
          - name: checode
      name: vscode-injector
    - attributes:
        app.kubernetes.io/component: vscode-runtime
        app.kubernetes.io/part-of: vscode.eclipse.org
        controller.devfile.io/container-contribution: true
      container:
        cpuRequest: 30m
        command:
          - /checode/entrypoint-volume.sh
        env:
          - name: CODE_HOST
            value: 0.0.0.0
        memoryRequest: 256Mi
        sourceMapping: /projects
        cpuLimit: 500m
        volumeMounts:
          - name: checode
            path: /checode
        memoryLimit: 1024Mi
        image: 'quay.io/che-incubator/che-code:insiders' # no-op ignored image
        endpoints:
          - attributes:
              cookiesAuthEnabled: true
              discoverable: false
              type: main
              urlRewriteSupported: true
            exposure: public
            name: che-code
            protocol: https
            secure: false
            targetPort: 3100
          - attributes:
              discoverable: false
              urlRewriteSupported: true
            exposure: public
            name: code-redirect-1
            protocol: http
            targetPort: 13131
          - attributes:
              discoverable: false
              urlRewriteSupported: true
            exposure: public
            name: code-redirect-2
            protocol: http
            targetPort: 13132
          - attributes:
              discoverable: false
              urlRewriteSupported: true
            exposure: public
            name: code-redirect-3
            protocol: http
            targetPort: 13133
      name: vscode-runtime-description
    - name: checode
      volume:
        ephemeral: true
  events:
    preStart:
      - init-container-command
----
<1> Name of the `DevWorkspaceTemplate`. This name will be used to reference the `DevWorkspaceTemplate` within the `DevWorkspace`.
<2> Target {orch-namespace} for the new workspace.
====

. To prepare the `DevWorkspace` custom resource, copy the contents of a project Devfile.
+
.Copied devfile contents
====
[source,yaml,subs="+quotes,+attributes"]
----
schemaVersion: 2.1.0    
components:
  - name: tooling-container
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
----
====
+
TIP: For more details, see the link:https://devfile.io/docs/2.1.0/what-is-a-devfile[devfile v2 documentation].

. Use the devfile to create a `DevWorkspace` definition.
+
.Example title
====
[source,yaml,subs="+quotes,+attributes"]
----
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: my-devworkspace#<1>
  namespace: __<user_{orch-namespace}>__#<2>
spec:
  started: true#<3>
  contributions:#<4>
    - name: editor
      kubernetes:
        name: che-code#<5>
  template:
    projects:#<6>
      - name: my-project-name
        git:
          remotes:
            origin: https://github.com/eclipse-che/che-docs
    components:#<7>
      - name: tooling-container
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
----
<1> Name of `DevWorkspace` resource. This is will be the name of the new workspace.
<2> Target {orch-namespace} for the new workspace.
<3> Determines whether the workspace should be started upon creating the `DevWorkspace` resource.
<4> Reference to the editor's `DevWorkspaceTemplate`.
<5> Name of the editor's `DevWorkspaceTemplate` from the previous step.
<6> Details about the Git project to clone upon workspace startup. The Git project that will be cloned for this example is https://github.com/eclipse-che/che-docs.
<7> List of components such as workspace containers and volume components.
====

. Apply the `DevWorkspace` custom resource to the cluster. 

. Verify that the workspace is starting by checking the `PHASE` status of the `DevWorkspace`.
+
[subs="+quotes,attributes"]
----
$ {orch-cli} get devworkspaces -n __<user_{orch-namespace}>__  --watch
----
+
.Output
====
[subs="+quotes,attributes"]
----
NAMESPACE            NAME                  DEVWORKSPACE ID             PHASE      INFO
user1-dev	     my-devworkspace       workspacedf64e4a492cd4701   Starting   Waiting for workspace deployment
----
====

. When the workspace starts with the *PHASE* status *Running*, open the workspace by either way:
** Visit the URL provided in the `INFO` section of the output from `{orch-cli} get devworkspaces`.
** Open the workspace from the {prod-short} dashboard.
+
.Output
====
[subs="+quotes,attributes"]
----
NAMESPACE            NAME                  DEVWORKSPACE ID             PHASE      INFO
user1-dev	     my-devworkspace       workspacedf64e4a492cd4701   Running    https://url-to-workspace.com
----
====
