[id="parameters-for-che-editor-yaml"]
= Parameters for che-editor.yaml

The simplest way to select a cloud IDE in the `che-editor.yaml` is to specify the `id` of an IDE from the table of supported cloud IDEs:

.Supported cloud IDEs
[cols="1,1a,1a"]
|===
| IDE | `id` | Note

include::example$snip_{project-context}-table-of-supported-editors.adoc[]

|===


.`id` selects a cloud IDE from the plugin registry
====
[source,yaml]
----
id: che-incubator/che-idea/latest
----
====

As alternatives to providing the `id` parameter, the `che-editor.yaml` file supports a `reference` to the URL of another `che-editor.yaml` file or an `inline` definition for a cloud IDE outside of a plugin registry:

.`reference` points to a remote `che-editor.yaml` file
====
[source,yaml,subs="+quotes"]
----
reference: https://__<hostname_and_path_to_a_remote_file>__/che-editor.yaml
----
====

.`inline` specifies a complete definition for a customized cloud IDE without a plugin registry
====
[source,yaml]
----
inline:
  schemaVersion: 2.1.0
  metadata:
    name: JetBrains IntelliJ IDEA Community IDE
  components:
    - name: intellij
      container:
        image: 'quay.io/che-incubator/che-idea:next'
        volumeMounts:
          - name: projector-user
            path: /home/projector-user
        mountSources: true
        memoryLimit: 2048M
        memoryRequest: 32Mi
        cpuLimit: 1500m
        cpuRequest: 100m
        endpoints:
          - name: intellij
            attributes:
              type: main
              cookiesAuthEnabled: true
              urlRewriteSupported: true
              discoverable: false
              path: /?backgroundColor=434343&wss
            targetPort: 8887
            exposure: public
            secure: false
            protocol: https
      attributes: {}
    - name: projector-user
      volume: {}
----
====

For more complex scenarios, the `che-editor.yaml` file supports the `registryUrl` and `override` parameters:

.`registryUrl` points to a custom plugin registry rather than to the default {prod-short} plugin registry
====
[source,yaml,subs="+quotes"]
----
id: __<editor_id>__ # <1>
registryUrl: __<url_of_custom_plugin_registry>__
----
<1> The `id` of the IDE in the custom plugin registry.
====

.`override` of the default value of one or more defined properties of the cloud IDE
====
[source,yaml,subs="+quotes"]
----
... # <1>
override:
  containers:
    - name: che-idea
      memoryLimit: 1280Mi
      cpuLimit: 1510m
      cpuRequest: 102m
    ...
----
<1> `id:`, `registryUrl:`, or `reference:`.
====
