[id="options-for-che-editor-yaml_{context}"]
= Options for che-editor.yaml

The `che-editor.yaml` file supports using a `reference` to a remote IDE definition or an `inline` IDE definition as an alternative to the `id` parameter. This is useful when the IDE is not defined in the plug-in registry:

.`reference` points to a remote `che-editor.yaml` file
====
[source,yaml]
----
reference: https://gist.github.com/.../che-editor.yaml
----
====

.`inline` specifies a complete IDE definition when your project requires a customized IDE
====
[source,yaml]
----
inline:
  components:
  (...)
  events:
  (...)
   commands:
  (...)
----
====

The `che-editor.yaml` file supports optional parameters to suit the needs of more complex scenarios: `regisryUrl` and `override`:

.`registryUrl` points to a custom plug-in registry rather than to the default {prod-short} plug-in registry
====
[source,yaml]
----
id: eclipse/che-theia/next            # required
registryUrl: https://my-registry.com  # optional
override:                             # optional
  containers:
    - name: theia-ide
      memoryLimit: 1280Mi
----
====

Can I remove the `reference` line below? And can this work also with the `registryURL`?
.`override` does what?
====
[source,yaml]
----
reference: https://gist.github.com/.../che-editor.yaml # required
override:                                              # optional
  containers:
      - name: theia-ide
        memoryLimit: 1280Mi 
----
====

.Additional resources

include::example$snip_{project-context}-link-to-example-che-editor-yaml-file.adoc[]
