:_content-type: PROCEDURE
:description: Connect {prod-short} to your Bitbucket Server OAuth 1.0 application
:keywords: bitbucket, bitbucket-server, application-link, bitbucket-secret
:navtitle: Connect {prod-short} to your Bitbucket Server OAuth 1.0 application
// :page-aliases:

[id="applying-an-application-link-secret-for-the-bitbucket-server"]
= Connect {prod-short} to your Bitbucket Server OAuth 1.0 application

Connect {prod-short} to your Bitbucket Server OAuth 1.0 application so that developers can access Bitbucket Server repositories from workspaces without re-entering credentials.

.Prerequisites

* You have configured the application link on the Bitbucket Server.

* You have the following files, which were created when configuring the application link:
** `privatepkcs8-stripped.pem`
** `bitbucket-consumer-key`
** `bitbucket-shared-secret`

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: __<bitbucket_server_url>__ <2>
type: Opaque
stringData:
  private.key: __<Content_of_privatepkcs8-stripped.pem>__ <3>
  consumer.key: __<Content_of_bitbucket-consumer-key>__ <4>
  shared_secret: __<Content_of_bitbucket-shared-secret>__ <5>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The URL of the Bitbucket Server.
<3> The content of the `privatepkcs8-stripped.pem` file.
<4> The content of the `bitbucket-consumer-key` file.
<5> The content of the `bitbucket-shared-secret` file.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

.Verification

* Verify that the output displays `secret/bitbucket-oauth-config created`.
