:_content-type: PROCEDURE
:description: Connect {prod-short} to your Microsoft Entra ID application
:keywords: microsoft-azure-devops-entra-id-oauth-app, apply, secret
:navtitle: Connect {prod-short} to your Microsoft Entra ID application
// :page-aliases:

[id="applying-the-microsoft-entra-id-oauth-app-secret"]
= Connect {prod-short} to your Microsoft Entra ID application

Connect {prod-short} to your Microsoft Entra ID application so that developers can access Azure DevOps repositories from workspaces without re-entering credentials.

.Prerequisites

* You have configured the Microsoft Entra ID OAuth App.

* You have the following values, which were generated when configuring the Microsoft Entra ID OAuth App:
** *Application (client) ID*
** *Directory (tenant) ID*
** *Client Secret*

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: azure-devops-oauth-config
  namespace: {prod-namespace}# <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: azure-devops
type: Opaque
stringData:
  tenant-id: __<Microsoft_Entra_ID_Tenant_ID>__# <2>
  id: __<Microsoft_Entra_ID_App_ID>__# <3>
  secret: __<Microsoft_Entra_ID_Client_Secret>__# <4>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The Microsoft Entra ID *Directory (tenant) ID*.
<3> The Microsoft Entra ID *Application (client) ID*.
<4> The Microsoft Entra ID *Client Secret*.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

.Verification

* Verify that the output displays `secret/azure-devops-oauth-config created`.

* Verify that the rollout of the {prod-short} server components is complete:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} rollout status deployment/che -n {prod-namespace}
----