:_content-type: PROCEDURE
:description: Connect {prod-short} to your Bitbucket Server OAuth 2.0 application
:keywords: bitbucket, bitbucket-server, application-link, bitbucket-secret
:navtitle: Connect {prod-short} to your Bitbucket Server OAuth 2.0 application
// :page-aliases:

[id="applying-an-oauth-2-application-link-secret-for-the-bitbucket-server"]
= Connect {prod-short} to your Bitbucket Server OAuth 2.0 application

Connect {prod-short} to your Bitbucket Server OAuth 2.0 application so that developers can access Bitbucket Server repositories from workspaces without re-entering credentials.

.Prerequisites

* You have configured the OAuth 2.0 application link on the Bitbucket Server.

* You have the following values, which were generated when configuring the Bitbucket application link:
** Bitbucket *Client ID*
** Bitbucket *Client secret*

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: __<bitbucket_server_url>__ <2>
type: Opaque
stringData:
  id: __<Bitbucket_Client_ID>__ <3>
  secret: __<Bitbucket_Client_Secret>__ <4>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The URL of the Bitbucket Server.
<3> The Bitbucket *Client ID*.
<4> The Bitbucket *Client secret*.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

.Verification

* Verify that the output displays `secret/bitbucket-oauth-config created`.
