:_content-type: PROCEDURE
:description: Connect {prod-short} to your Bitbucket Cloud OAuth consumer
:keywords: bitbucket, bitbucket-cloud, oauth-consumer, bitbucket-consumer, oauth-consumer-secret, bitbucket-client-secret
:navtitle: Connect {prod-short} to your Bitbucket Cloud OAuth consumer
// :page-aliases:

[id="applying-an-oauth-consumer-secret-for-the-bitbucket-cloud"]
= Connect {prod-short} to your Bitbucket Cloud OAuth consumer

Connect {prod-short} to your Bitbucket Cloud OAuth consumer so that developers can access Bitbucket Cloud repositories from workspaces without re-entering credentials.

.Prerequisites

* You have configured the OAuth consumer in the Bitbucket Cloud.

* You have the following values, which were generated when configuring the Bitbucket OAuth consumer:
** Bitbucket OAuth consumer Key
** Bitbucket OAuth consumer Secret

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
type: Opaque
stringData:
  id: __<Bitbucket_Oauth_Consumer_Key>__ <2>
  secret: __<Bitbucket_Oauth_Consumer_Secret>__ <3>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The *Bitbucket OAuth consumer Key*.
<3> The *Bitbucket OAuth consumer Secret*.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

.Verification

* Verify that the output displays `secret/bitbucket-oauth-config created`.
