:_content-type: PROCEDURE
:description: Connect {prod-short} to your GitHub OAuth application
:keywords: github-oauth-app, apply, secret, github
:navtitle: Connect {prod-short} to your GitHub OAuth application
// :page-aliases:

[id="applying-the-github-oauth-app-secret"]
= Connect {prod-short} to your GitHub OAuth application

Connect {prod-short} to your GitHub OAuth application so that developers can access GitHub repositories from workspaces without re-entering credentials.

.Prerequisites

* You have configured the GitHub OAuth App.

* You have the following values, which were generated when configuring the GitHub OAuth App:
** *GitHub OAuth Client ID*
** *GitHub OAuth Client Secret*

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
    che.eclipse.org/scm-server-endpoint: __<github_server_url>__ <2>
    che.eclipse.org/scm-github-disable-subdomain-isolation: 'false' <3>
type: Opaque
stringData:
  id: __<GitHub_OAuth_Client_ID>__ <4>
  secret: __<GitHub_OAuth_Client_Secret>__ <5>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> This depends on the GitHub product your organization is using: When hosting repositories on GitHub.com or GitHub Enterprise Cloud, omit this line or enter the default `https://github.com`. When hosting repositories on GitHub Enterprise Server, enter the GitHub Enterprise Server URL.
<3> If you are using GitHub Enterprise Server with a disabled link:https://docs.github.com/en/enterprise-server/admin/configuration/hardening-security-for-your-enterprise/enabling-subdomain-isolation#about-subdomain-isolation[subdomain isolation] option, you must set the annotation to `true`, otherwise you can either omit the annotation or set it to `false`.
<4> The *GitHub OAuth Client ID*.
<5> The *GitHub OAuth Client Secret*.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

. Optional: To configure OAuth 2.0 for another GitHub provider, repeat the previous steps and create a second GitHub OAuth Secret with a different name.

.Verification

* Verify that the output displays `secret/github-oauth-config created`.
