:navtitle: Configuring user secrets
:keywords: user-guide, configuring, user, secrets
:page-aliases: mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container 


[id="configuring-user-secrets_{context}"]
= Configuring user secrets

Secrets are {platforms-name} objects that store sensitive data such as user names, passwords, authentication tokens, and configurations in an encrypted form.

Users can mount a secret that contains sensitive data in a workspace container. This reapplies the stored data from the secret automatically for every newly created workspace. As a result, the user does not have to provide these credentials and configuration settings manually. 

Do not mount secrets that you define in a devfile.

The following section describes how to automatically mount a {platforms-name} secret in a workspace container and create permanent mount points for components such as:

* Maven configuration, the `settings.xml` file 
* SSH key pairs
* AWS authorization tokens
* Git credentials store file

A {platforms-name} secret can be mounted into a workspace container as:

* A file - This creates automatically mounted Maven settings that will be applied to every new workspace with Maven capabilities.

* An environment variable - This uses SSH key pairs and AWS authorization tokens for automatic authentication. 
+
NOTE: SSH key pairs can also be mounted as a file, but this format is primarily aimed at the settings of the Maven configuration.

The mounting process uses the standard {platforms-name} mounting mechanism, but it requires additional annotations and labeling for a proper bound of a secret with the required {prod-short} workspace container.

{orch-name} annotations and labels are tools used by libraries, tools, and other clients, to attach arbitrary non-identifying metadata to {platforms-name} native objects. 

Labels select objects and connect them to a collection that satisfies certain conditions, where annotations are used for non-identifying information that is not used by {platforms-name} objects internally.

This section describes {platforms-name} annotation values used in the process of {platforms-name} secret mounting in a {prod-short} workspace.

Annotations must contain items that help identify the proper mounting configuration. These items are:

include::example$snip_{project-context}-annotations-description.adoc[leveloffset=+1]
