:_content-type: CONCEPT
:description: {prod} provides developer workspaces with everything you need to code, build, test, run, and debug applications.
:keywords: user-guide, workspaces-overview
:navtitle: Developer workspaces
:page-aliases: .:using-developer-workspaces.adoc, .:workspaces-overview.adoc, .:what-are-workspaces.html, .:creating-and-configuring-a-new-workspace.adoc, creating-and-configuring-a-new-workspace.adoc, authenticating-on-scm-server-with-a-personal-access-token.adoc, navigating-che.adoc, navigating-che-using-the-dashboard.adoc, importing-certificates-to-browsers.adoc, creating-a-workspace-from-local-devfile-using-chectl.adoc, importing-kubernetes-applications-into-a-workspace.adoc, workspaces-overview.adoc, configuring-a-workspace-with-dashboard.adoc, creating-a-workspace-from-a-code-sample.adoc, creating-a-workspace-from-a-template-devfile.adoc, creating-a-workspace-from-remote-devfile.adoc, running-a-workspace-with-dashboard.adoc, remotely-accessing-workspaces.adoc, importing-the-source-code-of-a-project-into-a-workspace.adoc, using-developer-workspaces.adoc

[id="developer-workspaces"]
= Developer workspaces

{prod} provides developer workspaces with everything you need to code, build, test, run, and debug applications:

* Project source code
* Web-based integrated development environment (IDE)
* Tool dependencies needed by developers to work on a project
* Application runtime: a replica of the environment where the application runs in production

Pods manage each component of a {prod-short} workspace.
Therefore, everything running in a {prod-short} workspace is running inside containers.
This makes a {prod-short} workspace highly portable.

The embedded browser-based IDE is the point of access for everything running in a {prod-short} workspace.
This makes a {prod-short} workspace easy to share.

Visual Studio Code is the default browser-based IDE. {prod-short} adds these features:

Tasks::
Commands that are defined in the devfile appear as tasks.
+
To execute such command, go to menu:Terminal[Run Task].
+
Alternatively, kbd:[F1] to open the *Command Palette* and type `Tasks: Run Tasks` to see a drop-down list of available task-related commands.

Process monitoring::
When a process starts listening to a port, {prod-short} displays an alert with a link to open the resulting resource.
