[id="introduction-to-devfile"]
= Introduction to devfile in {prod-short}

link:https://devfile.io/[Devfiles] are `yaml` text files used for development environment customization. Use them to configure a devfile to suit your specific needs and share the customized devfile across multiple workspaces to ensure identical user experience and build, run, and deploy behaviours across your team.

.{prod}-specific devfile features

[NOTE]
====    
{prod} is expected to work with most of the popular images defined in the `components` section of devfile. For production purposes, it is recommended to use one of the link:https://catalog.redhat.com/software/containers/search?gs&q=ubi[Universal Base Images] as a base image for defining the Cloud Development Environment.
====

[WARNING]
====
Some images can not be used as-is for defining Cloud Development Environment since Visual Studio Code - Open Source ("Code - OSS") can not be started in the containers with missing `openssl` and `libbrotli`. Missing libraries should be explicitly installed on the Dockerfile level e.g. `RUN yum install compat-openssl11 libbrotli`
====

.Devfile and Universal Developer Image

You do not need a devfile to start a workspace. If you do not include a devfile in your project repository, {prod} automatically loads a default devfile with a Universal Developer Image (UDI).

.Devfile Registry

link:https://registry.devfile.io/viewer[Devfile Registry] contains ready-to-use community-supported devfiles for different languages and technologies. Devfiles included in the registry should be treated as samples rather than templates.


.Additional resources

* link:https://devfile.io/docs/{devfile-api-version}/what-is-a-devfile[What is a devfile]
* link:https://devfile.io/docs/{devfile-api-version}/benefits-of-devfile[Benefits of devfile]
* link:https://devfile.io/docs/{devfile-api-version}/overview[Devfile customization overview]
* link:https://devfile.io/[Devfile.io]
* link:https://che.eclipseprojects.io/2024/02/05/@mario.loriedo-cde-customization.html[Customizing Cloud Development Environments]
