:navtitle: Enabling persistent storage in workspaces
:keywords: user-guide, configuring, user, volumes, persistent, volume, claim, mounting, mount
:page-aliases:

[id="enabling-persistent-storage-in-workspaces_{context}"]
= Enabling persistent storage in workspaces

****
THIS PAGE IS WORK IN PROGRESS. max-cx
****

You can mount a Persistent Volume Claim (PVC) to your {devworkspace} containers. A PVC is used to request persistent storage resources which are abstracted from the user.

{prod-short} provisions containerized development environments (workspaces). Without persistent volumes, every change would be lost when a running workspace is stopped.

To avoid losing changes a user can either:

* Pre-create a PVC with the right labels. This procedure is described in this section.
* Specify a Persistent Volume (PV) in a Devfile that will be managed by {prod-short}. See link:https://devfile.io/docs/devfile/2.1.0/user-guide/specifying-persistent-storage[Specifying persistent storage].

Users will want to use Devfile-defined volumes when persisted data is mandatory for development and doesn't need to be shared across multiple workspaces.

Alternatively, users should favor pre-created PVs when:

* not all the developers of a project will need the PV, or
* the PV lifecycle goes beyond the lifecycle of a single workspace, or
* the data included in the PV is shared across workspaces.

An example of a Devfile-defined PV is the `/projects/` folder of a workspace, which is by default.

Pre-created PVs are mounted even if the workspace is run in ephemeral mode (the devfile uses the attribute `controller.devfile.io/storage-type: ephemeral`).

[NOTE]
====
Persistent Volumes come at a cost: attaching a persistent volume slows workspace startup.
====


[WARNING]
====
There is a limitation when trying to run two concurrent workspaces if mounting a PV with the `ReadWriteOnce` access mode. The second workspace may fail to start.
====

To automatically mount an existing PVC to workspace containers:

.Prerequisites

* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* You have created a new PVC or determined an existing one in your user {orch-namespace} to mount to all workspaces containers.
* For CLI users: The `{orch-cli}` command-line tool is installed in the operating system you are using.

.Procedure

. Add label `controller.devfile.io/mount-to-devworkspace: true` to `__<PVC_name>__`.

+
[TIP]
====
CLI users can apply the label like so:

`$ {orch-cli} -n __<user_{orch-namespace}>__ label persistentvolumeclaim __<PVC_name>__ controller.devfile.io/mount-to-devworkspace=true`
====

. Optional: Use the annotations to configure how the PVC is mounted.
+
.Optional annotations
|===
| Annotation |Description

| `controller.devfile.io/mount-path:`
| The mount path for the PVC.

Defaults to `/tmp/__<PVC_name>__`.

| `controller.devfile.io/read-only:`
| Set to `'true'` or `'false'` to specify whether the PVC is to be mounted as read-only.

Defaults to `'false'`, resulting in the PVC mounted as read-write.
|===

.Mounting a read-only PVC
====
[source,yaml,subs="+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __<pvc_name>__
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
  annotations:
    controller.devfile.io/mount-path: __</example/directory>__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi <1>
  volumeName: __<pv_name>__
  storageClassName: manual
  volumeMode: Filesystem
----
<1> Example storage request value.

When you start a workspace, the PVC is mounted at `/tmp/my-directory` in the `{devworkspace}` containers.
====

.Additional resources

* link:https://docs.openshift.com/container-platform/latest/storage/understanding-persistent-storage.html[Red Hat OpenShift Documentation: Understanding persistent storage]
* link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Kubernetes Documentation: Persistent Volumes]