:_content-type: PROCEDURE
:description: You can enable an npm artifact repository in npm workspaces that run in a restricted environment.
:keywords: npm, artifact-repository, artifact-repositories
:navtitle: npm
:page-aliases: using-npm-artifact-repositories.adoc

[id="enabling-npm-artifact-repositories"]
= Enabling npm artifact repositories

You can enable an npm artifact repository in npm workspaces that run in a restricted environment.

.Prerequisites

* You are not running any npm workspace.

include::partial$snip_warning-about-applying-a-configmap-that-sets-environment-variables.adoc[]

.Procedure

. Apply the Secret for the TLS certificate:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: tls-cer
  annotations:
    controller.devfile.io/mount-path: /public-certs/nexus.cer
    controller.devfile.io/mount-as: file
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  tls.cer: >-
    __<Base64_encoded_content_of_public_cert>__ <1>
----
<1> Base64 encoding with disabled line wrapping.

. Apply the ConfigMap to set the following environment variables in the `tools` container:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: disconnected-env
  annotations:
    controller.devfile.io/mount-as: env
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
data:
  NPM_CONFIG_REGISTRY: >-
    https://__<npm_artifact_repository_route>__/repository/npm-all/
----

= Disabling self-signed certificate validation

Follow the instructions below to disable self-signed certificate validation.

.Procedure

* Run the following command in the terminal:
+
[source, yaml]
----
npm config set strict-ssl false
----

= Restoring correct NODE_EXTRA_CA_CERTS variable value

Use the command described below to restore the correct NODE_EXTRA_CA_CERTS variable value before dependencies are downloaded every time.

.Procedure

* Run the following command in the terminal:
+
[source, yaml]
----
`export NODE_EXTRA_CA_CERTS=/public-certs/nexus.cer` <1>
----
<1> `/public-certs/nexus.cer` is the path to self-signed SSL/TLS certificate of Nexus artifactory.