:navtitle: Enabling persistent storage in workspaces
:keywords: user-guide, configuring, user, volumes, persistent, volume, claim, mounting, mount
:page-aliases:

[id="enabling-persistent-storage-in-workspaces_{context}"]
= Enabling persistent storage in workspaces

{prod-short} workspaces and workspace data are ephemeral and are lost when the workspace stops.

To have persistent storage between workspace restarts, specify a {kubernetes} PersistentVolume (PV) for the `{devworkspace}` containers. You can do this by either defining and mounting a volume from the project devfile or using a {kubernetes} PersistentVolumeClaim (PVC) with the necessary labels.

[NOTE]
====
Persistent Volumes come at a cost: attaching a persistent volume slows workspace startup.
====

[WARNING]
====
There is a limitation when trying to run two concurrent workspaces if mounting a PV with the `ReadWriteOnce` access mode. The second workspace may fail to start.
====

.Additional resources

* link:https://docs.openshift.com/container-platform/latest/storage/understanding-persistent-storage.html[Red Hat OpenShift Documentation: Understanding persistent storage]
* link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Kubernetes Documentation: Persistent Volumes]

== Specifying persistant storage in a devfile

Persistent storage can be defined in the project's devfile if it is mandatory for development and sharing storage across multiple workspaces isn't needed.
When persistent storage is defined in the devfile, {prod-short} will manage the necessary PVCs.

[NOTE]
====
An example of a devfile-defined PV is the `/projects/` folder of a workspace, which is mounted by default.
====

.Procedure

. Create a `volume` component in the project's devfile with a name and the desired volume size.

. Create a `volumeMount` in a `container` for mounting. The `volumeMount` is defined with the `name` of the volume from the previous step, and a `path` to where the PV is to be mounted.

.Specifying and mounting the `cache` volume into a container
====

[source,yaml,subs="+quotes,+attributes,+macros"]
----
schemaVersion: 2.1.0
metadata:
  name: mydevfile
components:
  - name: golang
    container:
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: cache <1>
          path: /.cache
  - name: cache     <2>
    volume:
      size: 2Gi
----
<1> The `volumeMount` definition for mounting the `cache` volume.
<2> The `volume` component definition for the `cache` volume.

When a workspace is started with a project using this devfile, a persistent volume is mounted to the `golang` container in `./cache` container path.
====

== Specifying persistant storage with a PVC

You may opt to mount a PersistentVolumeClaim (PVC) to request a PersistentVolume (PV) for your workspaces in the following cases:

* Not all developers of the project need the PV.
* The PV lifecycle goes beyond the lifecycle of a single workspace.
* The data included in the PV are shared across workspaces.

PVCs are mounted to the workspace containers even if the workspace is run in ephemeral mode (in other words, when the devfile has the attribute `controller.devfile.io/storage-type: ephemeral`).

.Prerequisites

* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* You have created a new PVC or determined an existing one in your user {orch-namespace} to mount to all workspace containers.
* For CLI users: The `{orch-cli}` command-line tool is installed in the operating system you are using.

.Procedure

. Add label `controller.devfile.io/mount-to-devworkspace: true` to `__<PVC_name>__`.

+
[TIP]
====
CLI users can apply the label like so:

[subs="+quotes,+attributes,+macros"]
----
`$ {orch-cli} label persistentvolumeclaim __<PVC_name>__ \
          controller.devfile.io/mount-to-devworkspace=true`
----
====

. Optional: Use the annotations to configure how the PVC is mounted.
+
.Optional annotations
|===
| Annotation |Description

| `controller.devfile.io/mount-path:`
| The mount path for the PVC.

Defaults to `/tmp/__<PVC_name>__`.

| `controller.devfile.io/read-only:`
| Set to `'true'` or `'false'` to specify whether the PVC is to be mounted as read-only.

Defaults to `'false'`, resulting in the PVC mounted as read-write.
|===

.Mounting a read-only PVC
====
[source,yaml,subs="+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __<pvc_name>__
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
  annotations:
    controller.devfile.io/mount-path: __</example/directory>__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi <1>
  volumeName: __<pv_name>__
  storageClassName: manual
  volumeMode: Filesystem
----
<1> Example storage request value.

When you start a workspace, the PV is mounted at `/tmp/my-directory` in the `{devworkspace}` containers.
====