:navtitle: Enabling persistent storage in workspaces
:keywords: user-guide, configuring, user, volumes, persistent, volume, claim, mounting, mount
:page-aliases:

[id="enabling-persistent-storage-in-workspaces_{context}"]
= Enabling persistent storage in workspaces

{prod-short} workspaces and workspace data are ephemeral and are lost when the workspace stops.

When you need to avoid data loss when the workspace stops, request persistent storage in the {orch-name} cluster of your organization's {prod-short} instance. You do this by claiming a {kubernetes} PersistentVolume (PV) for the `{devworkspace}` containers in the cluster.

You can claim a PV for your workspaces in the devfile or in a {kubernetes} PersistentVolumeClaim (PVC).

[NOTE]
====
Persistent Volumes come at a cost: attaching a persistent volume slows workspace startup.
====

[WARNING]
====
There is a limitation when trying to run two concurrent workspaces if mounting a PV with the `ReadWriteOnce` access mode. The second workspace may fail to start.
====

.Additional resources

* link:https://docs.openshift.com/container-platform/latest/storage/understanding-persistent-storage.html[Red Hat OpenShift Documentation: Understanding persistent storage]
* link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Kubernetes Documentation: Persistent Volumes]

== Claiming a PersistentVolume in a devfile

When persistent data are mandatory for development and shared across multiple workspaces isn't needed, claim a PersistentVolume (PV) in the devfile and let {prod-short} manage it.

I'm not sure where the following line belongs here. max-cx:
the devfile uses the attribute `controller.devfile.io/storage-type: ephemeral`

.Procedure

* Is it possible to write a procedure based on link:https://devfile.io/docs/devfile/2.1.0/user-guide/specifying-persistent-storage[]?

.Can this example be reworked for our purposes?
====

[source,yaml,subs="+quotes,+attributes,+macros"]
----
schemaVersion: 2.1.0
metadata:
  name: mydevfile
components:
  - name: mydevfile
    container:
      image: golang
      memoryLimit: 512Mi
      mountSources: true
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: cache
          path: /.cache <1>
  - name: cache
    volume:
      size: 2Gi
----
<1> An example of a devfile-defined PV is the `/projects/` folder of a workspace, which is by default.
====

== Claiming a PersistentVolume in a PVC

You may opt to use a PersistentVolumeClaim (PVC) to claim a PersistentVolume (PV) for your workspaces when you need it:

* The devfile contains no PV claim.
* Not all developers on your project need the PV.
* The PV lifecycle goes beyond the lifecycle of a single workspace.
* The data included in the PV are shared across workspaces.

.Prerequisites

* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* You have created a new PVC or determined an existing one in your user {orch-namespace} to mount to all workspaces containers.
* For CLI users: The `{orch-cli}` command-line tool is installed in the operating system you are using.

.Procedure

. Add label `controller.devfile.io/mount-to-devworkspace: true` to `__<PVC_name>__`.

+
[TIP]
====
CLI users can apply the label like so:

`$ {orch-cli} -n __<user_{orch-namespace}>__ label persistentvolumeclaim __<PVC_name>__ controller.devfile.io/mount-to-devworkspace=true`
====

. Optional: Use the annotations to configure how the PVC is mounted.
+
.Optional annotations
|===
| Annotation |Description

| `controller.devfile.io/mount-path:`
| The mount path for the PVC.

Defaults to `/tmp/__<PVC_name>__`.

| `controller.devfile.io/read-only:`
| Set to `'true'` or `'false'` to specify whether the PVC is to be mounted as read-only.

Defaults to `'false'`, resulting in the PVC mounted as read-write.
|===

.Mounting a read-only PVC
====
[source,yaml,subs="+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __<pvc_name>__
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
  annotations:
    controller.devfile.io/mount-path: __</example/directory>__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi <1>
  volumeName: __<pv_name>__
  storageClassName: manual
  volumeMode: Filesystem
----
<1> Example storage request value.

When you start a workspace, the PVC?or?PV is mounted at `/tmp/my-directory` in the `{devworkspace}` containers.
====