:navtitle: Git credential store
:keywords: user-guide, configuring, user, secrets
:page-aliases: 

[id="mounting-a-git-credential-store-into-a-workspace-container_{context}"]
= Mounting a Git credentials store into a workspace container

This section describes how to mount Git credentials store as secret from the user's {orch-namespace} into the file in single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod-short}.

.Procedure
. Prepare Git credential file in the link:https://git-scm.com/docs/git-credential-store#_storage_format[Storage format].
. Encode content of the file to the base64 format.
. Create a new {platforms-name} secret in the {platforms-name} {orch-namespace} where a {prod-short} workspace will be created.

* The labels of the secret that is about to be created must match the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}. The default labels are:

* `app.kubernetes.io/part-of: che.eclipse.org` 
* `app.kubernetes.io/component: workspace-secret`:
+
include::example${project-context}-ref_git-credential-file-as-kubernetes-secret-into-the-file.adoc[levelofset=+1]
