:navtitle: Creating a {orch-name} Secret for a Git credentials store
:keywords: user-guide, configuring, user, secrets
:page-aliases: 

[id="mounting-a-git-credential-store-into-workspace-containers_{context}"]
= Creating a {orch-name} Secret for a Git credentials store

This section describes how to create a Secret containing a Git credentials store in the user's {orch-namespace}. The Git credentials store specified in the Secret is mounted as a file in the {devworkspace}'s containers.

.Prerequisites

* A running instance of {prod-short}.
* You have CLI or GUI access to the {orch-name} cluster of your organization's {prod-short} instance.

ifeval::["{project-context}" == "che"]
** For CLI users: `{orch-cli}` is installed in the operating system you are using. See link:https://kubernetes.io/docs/tasks/tools/#kubectl[Install Tools: kubectl].
endif::[]

ifeval::["{project-context}" == "crw"]
** For CLI users: `{orch-cli}` is installed in the operating system you are using. See link:https://docs.openshift.com/container-platform/4.10/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli[Installing the OpenShift CLI].
endif::[]


.Procedure
. Prepare a Git credential file in the link:https://git-scm.com/docs/git-credential-store#_storage_format[Storage format].

. Encode content of the file to the base64 format.

. Create a new {platforms-name} secret in the user's {orch-namespace}.
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-secret
  labels:
    controller.devfile.io/git-credential: 'true'                 <1>
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-path: __<path_in_container>__        <2>
data:
  credentials: __<base64_content_of_the_git_credentials_store>__     <3>
----
+
<1> The `controller.devfile.io/git-credential` label marks the secret as containing Git credentials. All Git credential secrets in the same {orch-namespace} will be merged into a single secret that would be mounted to the {devworkspace} containers. All the original secrets are kept in-tact.
<2> The path in the {devworkspace}'s containers at which the merged Git credentials secrets are to be mounted. For example, if set to `/tmp/git-credentials`, the merged Git credentials store is mounted at `/tmp/git-credentials/credentials`.
<3> The Git credentials store content encoded with `base64`.

. Apply the secret by entering it with `{orch-cli}` on a command line:
+
[source,subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<secret_prepared_in_the_previous_step>__
EOF
----
