:navtitle: Creating image pull Secrets
:keywords: user-guide, configuring, user, secrets
:page-aliases: 

[id="image-pull-secrets_{context}"]
= Creating image pull Secrets

You can create an image pull Secret containing credentials to allow {devworkspace} Pods to access private container registries.

An existing Docker credentials file such as `.dockercfg` or `$HOME/.docker/config.json` can be used to create the image pull Secret. Alternatively, the Secret can be created by running `{orch-cli} create secret docker-registry`.

== Create an image pull Secret with an existing `.dockercfg` or `config.json` file

.Prerequisites

* A running instance of {prod-short}.
* You have a `.dockercfg` or `$HOME/.docker/config.json` file containing credentials for the private container  registry.
* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* For CLI users: The `{orch-cli}` and link:https://www.gnu.org/software/coreutils/base64[`base64`] command line tools are installed in the operating system you are using.

.Procedure

. Encode the `.dockercfg` or `$HOME/.docker/config.json` file to Base64. 
+
[TIP]
====
CLI users can use the `base64` command as needed:

`$ cat config.json | base64 | tr -d '\n'`
====

. Create a new {orch-name} Secret in your user {orch-namespace}.

* For `.dockercfg` create:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: v1
kind: Secret
metadata:
  name: __<Secret_name>__
  labels:
    controller.devfile.io/devworkspace_pullsecret: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  .dockercfg: __<Base64_content_of_.dockercfg>__
type: kubernetes.io/dockercfg
----

* For `$HOME/.docker/config.json` create:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: v1
kind: Secret
metadata:
  name: __<Secret_name>__
  labels:
    controller.devfile.io/devworkspace_pullsecret: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  .dockerconfigjson: __<Base64_content_of_.dockerconfigjson>__
type: kubernetes.io/dockerconfigjson
----

. Use the CLI or GUI to apply the Secret to the {orch-name} cluster of your organization's {prod-short} instance.

+
[TIP]
====
CLI users can apply the Secret with `{orch-cli}`:

[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----
====

== Create an image pull Secret from scratch with {orch-cli}

.Prerequisites

* A running instance of {prod-short}.
* You have CLI access to the {orch-name} cluster of your organization's {prod-short} instance.

.Procedure

. In your user {orch-namespace}, create an image pull Secret with your private container registry details and credentials by running:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} create secret docker-registry __<Secret_name>__ \         
    --docker-server=__<registry_server>__ \
    --docker-username=<user_name> \
    --docker-password=<password> \
    --docker-email=<email>
----

. Add the required label to the image pull Secret by running:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} label secret __<Secret_name>__ controller.devfile.io/devworkspace_pullsecret=true controller.devfile.io/watch-secret=true
----
