:_content-type: ASSEMBLY
:navtitle: Managing workspaces with {orch-name} APIs
:description: Managing workspaces with {orch-name} APIs
:keywords: api, list workspaces, create workspace, restart workspace, stop workspace, start workspace, remove workspace
// :page-aliases:

[id="managing-workspaces-with-apis"]
= Managing workspaces with {orch-name} APIs

On your organization's {orch-name} cluster, {prod-short} workspaces are represented as `DevWorkspace` custom resources of the same name.
As a result, if there is a workspace named `my-workspace` in the {prod-short} dashboard, there is a corresponding `DevWorkspace` custom resource named `my-workspace` in the user's {orch-namespace} on the cluster.

Because each `DevWorkspace` custom resource on the cluster represents a {prod-short} workspace, you can manage {prod-short} workspaces by using {orch-name} APIs with clients such as the command-line `{orch-cli}`.

Each `DevWorkspace` custom resource contains details derived from the devfile of the Git repository cloned for the workspace. For example, a devfile might provide devfile commands and workspace container configurations.

include::partial$proc_listing-workspaces.adoc[leveloffset=+1]

include::partial$proc_creating-workspaces.adoc[leveloffset=+1]

include::partial$proc_stopping-workspaces.adoc[leveloffset=+1]

include::partial$proc_starting-stopped-workspaces.adoc[leveloffset=+1]

include::partial$proc_removing-workspaces.adoc[leveloffset=+1]
