:navtitle: Mounting ConfigMaps
:keywords: user-guide, configuring, user, configmaps, configmap, mounting, mount
:page-aliases:

[id="mounting-configmaps_{context}"]
= Mounting ConfigMaps

To mount non-confidential configuration data into your workspaces, use {kubernetes} ConfigMaps.

Using {kubernetes} ConfigMaps, you can mount non-sensitive data such as configuration values for an application.

Mount {kubernetes} ConfigMaps to the `{devworkspace}` containers in the {orch-name} cluster of your organization's {prod-short} instance.

.Prerequisites

* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* You have created a new ConfigMap or determined an existing one in your user {orch-namespace} to mount to all `{devworkspace}` containers.
* For CLI users: The `{orch-cli}` command line tool is installed in the operating system you are using.

.Procedure

. Determine an existing ConfigMap in your user {orch-namespace} to mount to all workspace containers.

. Set the required labels for mounting.
+
[TIP]
====
CLI users can run `{orch-cli}`:

[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} label configmap __<ConfigMap_name>__ \
        controller.devfile.io/mount-to-devworkspace=true \
        controller.devfile.io/watch-configmap=true
----
====

. Optional: Use the annotations to configure how the ConfigMap is mounted.
+
.Optional annotations
|===
|Annotation | Description

|`controller.devfile.io/mount-path:`
| Specifies the mount path.

Defaults to `/etc/config/__<ConfigMap_name>__`.

|`controller.devfile.io/mount-as:`
| Specifies how the resource should be mounted: `file`, `subpath`, or `env`.

Defaults to `file`.

`mount-as:file` mounts the keys and values as files within the mount path.

`mount-as:subpath` mounts the keys and values within the mount path using subpath volume mounts.

`mount-as:env` mounts the keys and values as environment variables in all `{devworkspace}` containers.
|===

.Mounting a ConfigMap as environment variables
====
[source,yaml,subs="+quotes"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-settings
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  __<env_var_1>__: __<value_1>__
  __<env_var_2>__: __<value_2>__
----

When you start a workspace, the `__<env_var_1>__` and `__<env_var_2>__` environment variables will be available in the `{devworkspace}` containers.
====
