:navtitle: Mounting Secrets
:keywords: user-guide, configuring, user, configmap, secret, secrets, mounting, mount
:page-aliases:

[id="mounting-secrets_{context}"]
= Mounting Secrets

You can automatically mount {orch-name} Secrets to all {devworkspace} containers, creating permanent mount points for components such as SSH key pairs or AWS authorization tokens.

Secrets are {orch-name} objects that store confidential data such as user names, passwords, authentication tokens, and configurations in an encrypted form.

.Prerequisites

* A running instance of {prod-short}.
* You have GUI or CLI access to the {orch-name} cluster of your organization's {prod-short} instance.
* For CLI users: The `{orch-cli}` command line tool is installed in the operating system you are using.

.Procedure

. Determine an existing ConfigMap or Secret in your user {orch-namespace} to mount to all {devworkspace} containers.

. Set the required labels for mounting.
+
[TIP]
====
CLI users can run `{orch-cli}`: 

`$ {orch-cli} label secret __<Secret_name>__ controller.devfile.io/mount-to-devworkspace=true controller.devfile.io/watch-secret=true`
====

. Optional: Use the annotations to configure how the Secret is mounted.
+
.Optional annotations
|===
|Annotation | Description

|`controller.devfile.io/mount-path:`
| Specifies the mount path.

Defaults to `/etc/secret/__<Secret_name>__`.

|`controller.devfile.io/mount-as:`
| Specifies how the resource should be mounted: `file`, `subpath`, or `env`.

Defaults to `file`.

If `file`, mounts the keys and values as files within the mount path.

If `subpath`, mounts the keys and values as files within the mount path using subpath volume mounts.

If `env`, mounts the keys and values as environment variables in all containers in the {devworkspace}.
|===

.Mounting a Secret as a file
====
[source,yaml,subs="+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-path: '/home/user/.m2'
data:
  settings.xml: __<Base64-encoded content>__
----

When a {devworkspace} starts, the `/home/user/.m2/settings.xml` file will be available in the {devworkspace} containers.
====