:_content-type: CONCEPT
:description: Restoring a Che workspace from a DevWorkspace backup
:keywords: workspace, backup, restore, devworkspace, dashboard
:navtitle: Restoring workspaces from backups
:page-aliases:

[id="restoring-workspaces-from-backups"]
= Restoring workspaces from backups

When backups are enabled for {devworkspace} instances on your cluster, a cron job will backup workspace data for stopped workspaces.

Backing up and restoring workspaces allows you to recover uncommitted source code changes. Note that restored workspaces use a minimal devfile rather than the original project devfile.

[NOTE]
====
Backup storage, registry access, and schedules are configured cluster-wide by administrators in the {devworkspace} Operator.
For administrator steps, see xref:administration-guide:devworkspace-backup.adoc[].
====

== Understanding workspace backups

After an administrator enables cluster-wide backups, source code data of stopped workspaces will be backed up in a container image, and automatically pushed to an OCI-compatible registry.

*Internal* backups are backups the {prod-short} dashboard detects and lists.
On {ocp}, they are represented as `ImageStream` resources in your namespace.

*External* backups are backups from a registry not specified by the administrator when cofiguring cluster-wide backups.

From the dashboard you can:

* Open the list of backups and inspect backup status.
* Restore a workspace from a backup that is already available to you (*internal* backup), or from an image reference you provide (*external* backup).
* Choose compute limits and the editor for the new workspace before you start the restore.

When the restored workspace is ready, the dashboard opens it in a new browser tab.

[NOTE]
====
A restored workspace is created from a minimal devfile with the restored source code being transfered to the workspace from an init container.
The *Devfile* tab in the workspace will not show the original devfile from the workspace's Git repository.
====

include::proc-viewing-backups-in-the-dashboard.adoc[leveloffset=+1]

include::proc-restoring-a-workspace-from-backup.adoc[leveloffset=+1]
