:navtitle: Secret as environment variable
:keywords: user-guide, configuring, user, secrets
:page-aliases: 

[id="mounting-a-secret-as-an-environment-variable-into-a-workspace-container_{context}"]
= Mounting a secret as an environment variable into a workspace container

The following section describes how to mount a {platforms-name} secret from the user’s {orch-namespace} as an environment variable, or variables, into single-workspace or multiple-workspace containers of {prod-short}.

.Prerequisites

* A running instance of {prod-short}.

.Procedure

. In the {platforms-namespace} where a {prod-short} workspace will be created, generate a new {platforms-name} secret.

* The labels of the secret that is about to be generated must match the set of labels configured in `che.workspace.provision.secret.labels` property of {prod-short}. By default, it is a set of two labels: 
+
* `app.kubernetes.io/part-of: che.eclipse.org` 
* `app.kubernetes.io/component: workspace-secret`:
+
include::example$snip_{project-context}-a-kubernetes-secret-as-an-variable.adoc[levelofset=+1]
