:_content-type: PROCEDURE
:description: Starting a workspace from a raw devfile URL
:keywords: start-new-workspace, start-a-new-workspace, how-to-start-new-workspace, how-to-start-a-new-workspace, starting-a-new-workspace, how-to-start-workspace, how-to-start-a-workspace
:navtitle: Starting a workspace from a raw devfile URL
:page-aliases:

[id="starting-a-workspace-from-a-raw-devfile-url"]
= Starting a workspace from a raw devfile URL

With {prod-short}, you can open a *devfile* URL in your browser to start a new workspace.

pass:[<!-- vale RedHat.Spelling = NO -->]

TIP: You can use the *Git Repo URL* field on the *Create Workspace* page of your {prod-short} dashboard to enter the URL of a *devfile* to start a new workspace.

pass:[<!-- vale RedHat.Spelling = YES -->]

[IMPORTANT]
====
To initiate a clone of the Git repository in the filesystem of a new workspace, the devfile must contain project info.

See https://devfile.io/docs/2.2.0/adding-projects.
====

.Prerequisites

* Your organization has a running instance of {prod-short}.
* You know the FQDN URL of your organization's {prod-short} instance: `pass:c,a,q[{prod-url}]`.

.Procedure

To start a new workspace from a devfile URL:

. Optional: Visit your {prod-short} dashboard pages to authenticate to your organization's instance of {prod-short}.

. Visit the URL to start a new workspace from a *public* repository using the basic syntax:
[source,subs="+quotes,+attributes,+macros"]
+
----
pass:c,a,q[{prod-url}]#__<devfile_url>__
----
+
You can pass your personal access token to the URL to access a devfile from *private* repositories:
[source,subs="+quotes,+attributes,+macros"]
+
----
pass:c,a,q[{prod-url}]#__https://__<token>__@__<host>__/__<path_to_devfile> <1>
----
<1> Your personal access token that you generated on the Git provider's website.
+
This works for GitHub, GitLab, Bitbucket, Microsoft Azure, and other providers that support Personal Access Token.
+
[IMPORTANT]
====
Automated Git credential injection does not work in this case.
To configure the Git credentials, use the xref:using-a-git-provider-access-token.adoc[configure personal access token] guide.
====
+
[TIP]
====
You can extend this URL with optional parameters:
[source,subs="+quotes,+attributes,+macros"]
----
pass:c,a,q[{prod-url}]#__<devfile_url>__?__<optional_parameters>__ <1>
----
<1> See xref:optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc[].
====
+
.A URL for starting a new workspace from a public repository
====

`pass:c,a,q[{prod-url}#https://raw.githubusercontent.com/che-samples/cpp-hello-world/main/devfile.yaml]`

====
+
.A URL for starting a new workspace from a private repository
====

`pass:c,a,q[{prod-url}#https://__<token>__@raw.githubusercontent.com/che-samples/cpp-hello-world/main/devfile.yaml]`

====
+
.Verification

After you enter the URL to start a new workspace in a browser tab, the workspace starting page appears. When the new workspace is ready, the workspace IDE loads in the browser tab.
+
The workspace has a unique URL: `pass:c,a,q[{prod-url}]/__<user_name>__/__<unique_url>__`.

.Additional resources

* xref:optional-parameters-for-the-urls-for-starting-a-new-workspace.adoc[]
* xref:basic-actions-you-can-perform-on-a-workspace.adoc[]
* xref:using-a-git-provider-access-token.adoc[]
* xref:mounting-git-configuration.adoc[]
* link:https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#configuring-devworkspaces-to-use-ssh-keys-for-git-operations[Configuring DevWorkspaces to use SSH keys for Git operations]
