:_content-type: PROCEDURE
:description: Troubleshooting network problems
:keywords: user-guide, troubleshooting-network-problems
:navtitle: Troubleshooting network problems
:page-aliases: .:troubleshooting-network-problems.adoc

[id="troubleshooting-network-problems"]
= Troubleshooting network problems

This section describes how to prevent or resolve issues related to network policies. 
{prod-short} requires the availability of the WebSocket Secure (WSS) connections.
Secure WebSocket connections improve confidentiality and also reliability because they reduce the risk of interference by bad proxies.

.Prerequisites

* The WebSocket Secure (WSS) connections on port 443 must be available on the network. Firewall and proxy might need additional configuration.
* Use a supported web browser:
** Google Chrome
** Mozilla Firefox

.Procedure

. Verify the browser supports the WebSocket protocol. See: link:https://www.google.com/search?q=websocket+test[Searching a websocket test].

. Verify firewalls settings: WebSocket Secure (WSS) connections on port 443 must be available.

. Verify proxy servers settings: The proxy transmits and intercepts WebSocket Secure (WSS) connections on port 443.
