:_content-type: CONCEPT
:description: URL parameter for a CPU limit
:keywords: parameter, URL, container, CPU limit
:navtitle: URL parameter for a CPU limit
//:page-aliases:

[id="url-parameter-for-cpu-limit"]
= URL parameter for a CPU limit

You can use the `cpuLimit` parameter to specify or override the container CPU limit
when starting a new workspace from a devfile URL. This is useful when you want to ensure that the workspace has enough memory allocated for your development tasks.

The URL parameter for the CPU limit is `cpuLimit=`:

[source,subs="+quotes,+attributes,+macros"]
----
pass:c,a,q[{prod-url}]#__<git_repository_url>__?cpuLimit=__<container_cpu_limit>__
----
You can specify the CPU limit in cores.

.Example

====

`pass:c,a,q[{prod-url}]#https://github.com/eclipse-che/che-docs?cpuLimit=2`

====
[IMPORTANT]
====
When you specify the `cpuLimit` parameter, it overrides the CPU limit defined for the first container of the devfile.

The sum of the limits from the target devfile and from the editor-definition will be applied to the workspace pod `spec.containers[0].resources.limits.cpu`.
====

.Additional resources

* link:https://devfile.io/docs/2.3.0/limiting-resources-usage[Limiting resources usage]

* {editor-definition-samples-link}
