:_content-type: CONCEPT
:description: URL parameter for the IDE
:keywords: ide, editor, workspace-ide, workspace-editor
:navtitle: URL parameter for the IDE
:page-aliases: url-parameter-for-the-in-browser-ide.adoc

[id="url-parameter-for-the-ide"]
= URL parameter for the IDE

You can use the `che-editor=` URL parameter to specify a supported IDE when starting a workspace.

TIP: Use the `che-editor=` parameter when you cannot add or edit a xref:defining-a-common-ide.adoc[`/.che/che-editor.yaml`] file in the source-code Git repository to be cloned for workspaces.

NOTE: The `che-editor=` parameter overrides the xref:defining-a-common-ide.adoc[`/.che/che-editor.yaml`] file.

This parameter accepts two types of values:

* `che-editor=__<editor_key>__`
+
[source,subs="+quotes,+attributes,+macros"]
----
pass:c,a,q[{prod-url}]#__<git_repository_url>__?che-editor=__<editor_key>__
----
+
.The URL parameter `__<editor_key>__` values for supported IDEs
[cols="1,1a,1a"]
|===
| IDE | `__<editor_key>__` value | Note

include::example$snip_{project-context}-table-of-supported-editors.adoc[]

|===

* `che-editor=__<url_to_a_file>__`
+
[source,subs="+quotes,+attributes,+macros"]
----
pass:c,a,q[{prod-url}]#__<git_repository_url>__?che-editor=__<url_to_a_file>__# <1>
----
<1> URL to a file with link:https://devfile.io/docs/2.2.0/what-is-a-devfile[devfile content].
+
[TIP]
====

* The URL must point to the raw file content.

* To use this parameter with a xref:defining-a-common-ide.adoc[`che-editor.yaml`] file, copy the file with another name or path, and remove the line with `inline` from the file.

include::example$snip_{project-context}-ide-default-yaml-file.adoc[]

====

