:_content-type: PROCEDURE
:description: Using a Git-provider access token
:keywords: Git, credentials, access-token
:navtitle: Using a Git-provider access token
:page-aliases: using-a-Git-credentials-store.adoc, using-git-credentials.adoc, 

[id="using-a-git-provider-access-token"]
= Using a Git-provider access token

pass:[<!-- vale RedHat.CaseSensitiveTerms = NO -->]

OAuth for GitHub, GitLab, Bitbucket, or Microsoft Azure Repos needs to be xref:administration-guide:configuring-oauth-for-git-providers.adoc[configured by the administrator] of your organization's {prod-short} instance. If your administrator could not configure it for {prod-short} users, the workaround is for you to use a personal access token. You can configure personal access tokens on the *User Preferences* page of your {prod-short} dashboard: `pass:c,a,q[{prod-url}]/dashboard/#/user-preferences?tab=personal-access-tokens`, or apply it manually as a {kubernetes} Secret in the namespace.

Mounting your access token as a Secret enables the {prod-short} Server to access the remote repository that is cloned during workspace creation, including access to the repository's `/.che` and `/.vscode` folders.

Apply the Secret in your user {orch-namespace} of the {orch-name} cluster of your organization's {prod-short} instance.

After applying the Secret, you can create workspaces with clones of private Git repositories that are hosted on GitHub, GitLab, Bitbucket Server, or Microsoft Azure Repos.

You can create and apply multiple access-token Secrets per Git provider. You must apply each of those Secrets in your user {orch-namespace}.

.Prerequisites

* You have logged in to the cluster.
+
[TIP]
====
On OpenShift, you can use the `oc` command-line tool to log in to the cluster:

`$ oc login pass:c,a,q[{prod-url}] --username=__<my_user>__`

====

.Procedure

. Generate your access token on your Git provider's website.

+
[IMPORTANT]
====
Personal access tokens are sensitive information and should be kept confidential. Treat them like passwords. If you are having trouble with authentication, ensure you are using the correct token and have the appropriate permissions for cloning repositories:

. Open a terminal locally on your computer
. Use the `git` command to clone the repository using your personal access token. The format of the `git` command vary based on the Git Provider. As an example, GitHub personal access token verification can be done using the following command:

----
git clone https://<PAT>@github.com/username/repo.git
----

Replace `<PAT>` with your personal access token, and `username/repo` with the appropriate repository path.
If the token is valid and has the necessary permissions, the cloning process should be successful. Otherwise, this is an indicator of incorrect personal access token, insufficient permissions, or other issues.
====

+
[IMPORTANT]
====
For GitHub Enterprise Cloud, verify that the token is link:https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on[authorized for use within the organization].
====


. Go to `pass:c,a,q[{prod-url}]/api/user/id` in the web browser to get your {prod-short} user ID.

. Prepare a new {orch-name} Secret.
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: personal-access-token-__<your_choice_of_name_for_this_token>__
  labels:
    app.kubernetes.io/component: scm-personal-access-token
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/che-userid: __<{prod-id-short}_user_id>__# <1>
    che.eclipse.org/scm-personal-access-token-name: _<git_provider_name>_# <2>
    che.eclipse.org/scm-url: __<git_provider_endpoint>__# <3>
    che.eclipse.org/scm-organization: __<git_provider_organization>__# <4>
stringData:
  token: __<Content_of_access_token>__
type: Opaque
----
+
<1> Your {prod-short} user ID.
<2> The Git provider name: `github` or `gitlab` or `bitbucket-server` or `azure-devops`.
<3> The Git provider URL.
<4> This line is only applicable to `azure-devops`: your Git provider user organization, or collection if Azure DevOps Server is used.

. Visit `pass:c,a,q[{prod-url}]/api/kubernetes/namespace` to get your {prod-short} user namespace as `name`.

. Switch to your {prod-short} user namespace in the cluster.
+
[TIP]
====
On OpenShift:

* The `oc` command-line tool can return the namespace you are currently on in the cluster, which you can use to check your current namespace:
+
`$ oc project`

* You can switch to your {prod-short} user namespace on a command line if needed:
+
`$ oc project __<your_user_namespace>__`

====

. Apply the Secret.
+
[TIP]
====
On OpenShift, you can use the `oc` command-line tool:
[source,subs="+quotes,+attributes"]
----
$ oc apply -f - <<EOF
__<Secret_prepared_in_step_5>__
EOF
----
====

[IMPORTANT]
====
If you are using Azure DevOps Server, you must also modify the xref:mounting-git-configuration.adoc[workspace's
gitconfig] with the following section:
```
[http]
    extraheader = "Authorization: Basic <base64-encoded(:personal-access-token)>"
```
To generate the key-value pair, use the following command:
```
echo -n "extraheader = \"Authorization: Basic "$(printf ":%s" <personal access token> | base64)\"
```
see link:https://learn.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops&tabs=Linux#personal-access-tokens[the documentation page] for more information.

This header is needed for remote git operations to Azure Devops Server, e.g. `git clone`. This authorization method has higher priority over the git credentials store, so git will fail on remote operations to other git providers. To be able to use other providers you need to remove the `extraheader` from the gitconfig.
====

.Verification

. xref:starting-a-workspace-from-a-git-repository-url.adoc[Start a new workspace by using the URL of a remote Git repository] that the Git provider hosts.
. Make some changes and push to the remote Git repository from the workspace.

.Additional resources

* xref:administration-guide:deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc[Deploying Che with support for Git repositories with self-signed certificates]
* link:https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on[Authorizing a personal access token for use with SAML single sign-on]

pass:[<!-- vale RedHat.CaseSensitiveTerms = YES -->]





