:_content-type: CONCEPT
:description: Using the fuse-overlayfs storage driver for Podman
:keywords: authentication, authenticate, github, gitlab, bitbucket
:navtitle: Using the fuse-overlayfs storage driver for Podman
:page-aliases:

[id="using-the-fuse-overlay-storage-driver-for-podman"]
= Using the fuse-overlayfs storage driver for Podman

By default, newly created workspaces that do not specify a devfile will use the Universal Developer Image (UDI).
The UDI contains common development tools and dependencies commonly used by developers.

Podman is included in the UDI, allowing developers to build and push container images from their workspace.

By default, Podman in the UDI is configured to use the `vfs` storage driver.
For more efficient image management, it is recommended to use the fuse-overlayfs storage driver which supports copy-on-write in rootless environments.

To use fuse-overlayfs in a workspace, there are three requirements:

. The administrator has configured `/dev/fuse` access on the cluster by following xref:administration-guide:configuring-fuse.adoc[].
. The workspace has the necessary annotations for using the `/dev/fuse` device. See xref:accessing-fuse.adoc[].
. The `storage.conf` file in the workspace container has been configured to use fuse-overlayfs. See xref:enabling-overlay-with-a-configmap.adoc[].

.Additional resources
* link:https://github.com/devfile/developer-images[Universal Developer Image]
