:navtitle: Using credentials and configurations in workspaces
:keywords: user-guide, configuring, user, configmaps, secrets, volumes, mounting, mount
:page-aliases: 

[id="using-credentials-and-configurations-in-workspaces_{context}"]
= Using credentials and configurations in workspaces

You can use your credentials and configurations in your workspaces.

To do so, mount your credentials and configurations to the `{devworkspace}` containers in the {orch-name} cluster of your organization's {prod-short} instance:

* Mount your credentials and sensitive configurations as {kubernetes} xref:mounting-secrets.adoc[Secrets]. One example is a xref:using-a-git-credentials-store.adoc[Git credentials store].

* Mount your non-sensitve configurations as {kubernetes} xref:mounting-configmaps.adoc[ConfigMaps].

If you need to allow the `{devworkspace}` Pods in the cluster to access container registries that require authentication, create an xref:creating-image-pull-secrets.adoc[image pull Secret] for the `{devworkspace}` Pods.

The mounting process uses the standard {kubernetes} mounting mechanism and requires applying additional labels and annotations to your existing resources. Resources are mounted when starting a new workspace or restarting an existing one.

You can create permanent mount points for various components:

* Maven configuration, such as the `settings.xml` file 
* SSH key pairs
* AWS authorization tokens
* Configuration files
* Persistent storage
* Git credentials store files

.Additional resources

* link:https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes Documentation: Secrets]
* link:https://kubernetes.io/docs/concepts/configuration/configmap/[Kubernetes Documentation: ConfigMaps]