:_content-type: REFERENCE
:description: Viewing {prod-short} workspaces logs
:keywords: administration-guide, viewing-che-workspaces-logs
:navtitle: Viewing {prod-short} workspaces logs
:page-aliases: .:viewing-che-workspaces-logs.adoc, administration-guide:viewing-che-workspaces-logs.adoc

[id="viewing-{prod-id-short}-workspaces-logs"]
= Viewing {prod-short} workspaces logs

You can view {prod-short} logs to better understand and debug background processes should a problem occur.

An issue with an extension::
The logs list the plugins that have been loaded by the editor.

The container runs out of memory::
The logs contain an `OOMKilled`error message.
The processes in the container requested more memory than is available in the container.

A process runs out of memory::
The logs contain an error message such as `OutOfMemoryException`.
A process inside the container ran out of memory without the container noticing.

.Additional resources
* xref:viewing-workspace-logs-in-cli.adoc[]
* xref:viewing-workspace-logs-in-the-openshift-console.adoc[]
* xref:viewing-language-servers-and-debug-adapters-logs-in-visual-studio-code.adoc[]
