:_content-type: PROCEDURE
:description: Viewing {prod-short} workspace logs in the OpenShift console
:keywords: administration-guide, logs, code
:navtitle: Workspace logs in OpenShift console
:page-aliases:

[id="viewing-{prod-id-short}-workspace-logs-in-the-openshift-console"]
= Viewing {prod-short} workspace logs in the OpenShift console

You can use the OpenShift console to observe the {prod-short} workspace logs.

.Procedure
. In the {prod-short} dashboard, go to *Workspaces*.

. Click on a workspace name to display the workspace overview page.
This page displays the {orch-name} {orch-namespace} name __<{orch-namespace}_name>__.

. Click on the upper right *Applications* menu, and click the OpenShift console link.

. Run the next steps in the OpenShift console, in the *Administrator* perspective.

. Click *Workloads* > *Pods* to see a list of all the active workspaces.

. In the *Project* drop-down menu, select the __<{orch-namespace}_name>__ {orch-namespace} to narrow the search.

. Click on the name of the running pod that runs the workspace.
The *Details* tab contains the list of all containers with additional information.

. Go to the *Logs* tab.
