---
title: Overview
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/customizing-the-devfile-and-plug-in-registries/
folder: che-7/administration-guide
summary:
---

:parent-context-of-customizing-the-devfile-and-plug-in-registries: {context}

[id='customizing-the-devfile-and-plug-in-registries']
= Customizing the devfile and plug-in registries

:context: customizing-the-devfile-and-plug-in-registries

{prod-short} {prod-ver} introduces two registries: the plug-in registry and the devfile registry. They are static websites where the metadata of {prod-short} plug-ins and {prod-short} devfiles is published.

The plug-in registry makes it possible to share a plug-in definition across all the users of the same instance of {prod-short}. Only plug-ins that are published in a registry can be used in a devfile.

The devfile registry holds the definitions of the {prod-short} stacks. These are available on the {prod-short} user dashboard when selecting *Create Workspace*. It contains the list of {prod-short} technological stack samples with example projects.

The devfile and plug-in registries run in two separate pods and are deployed when the {prod-short} server is deployed (that is the default behavior of the {prod-short} Operator). The metadata of the plug-ins and devfiles are versioned on GitHub and follow the {prod-short} server life cycle.

In this document, the following two ways to customize the default registries that are deployed with {prod-short} (to modify the plug-ins or devfile metadata) are described:

. Building a custom image of the registries
. Running the default images but modifying them at runtime

* link:{site-baseurl}che-7/building-and-running-a-custom-registry-image[Building and running a custom registry image]
* link:{site-baseurl}che-7/including-the-plug-in-binaries-in-the-registry-image[Including the plug-in binaries in the registry image]
* link:{site-baseurl}che-7/editing-a-devfile-and-plug-in-at-runtime[Editing a devfile and plug-in at runtime]

:context: {parent-context-of-customizing-the-devfile-and-plug-in-registries}
