---
title: Administration tasks
keywords: 
tags: []
sidebar: che_7_docs
permalink: che-7/administration-tasks.html
folder: che-7/administration-guide
summary: 
---

:parent-context-of-administration-tasks: {context}

[id='administration-tasks_{context}']
= Administration tasks

:context: administration-tasks


This paragraph is the assembly introduction. It explains what the user will accomplish by working through the modules in the assembly and sets the context for the user story the assembly is based on. Can include more than one paragraph. Consider using the information from the user story.

[id='prerequisites-{context}']
== Prerequisites

* A bulleted list of conditions that must be satisfied before the user starts following this assembly.
* You can also link to other modules or assemblies the user must follow before starting this assembly.
* Delete the section title and bullets if the assembly has no prerequisites.



include::proc_monitoring-che.adoc[leveloffset=+1]

include::proc_removing-user-data.adoc[leveloffset=+1]

include::proc_retrieving-che-logs.adoc[leveloffset=+1]



[id='related-information-{context}']
== Related information

* A bulleted list of links to other material closely related to the contents of the concept module.
* For more details on writing assemblies, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

:context: {parent-context-of-administration-tasks}
