---
title: Overview
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/retrieving-che-logs/
folder: che-7/administration-guide
summary:
---

:page-liquid:
:parent-context-of-retrieving-che-logs: {context}

[id="retrieving-{prod-id-short}-logs_{context}"]
= Retrieving {prod-short} logs

:context: retrieving-{prod-id-short}-logs

An application log is a file that contains information about events that have occurred within a software application. These events are logged out by the application and written to the file. These logs provide information about deployment and run-time events, including errors and warning notifications.

For information about obtaining various types of application logs in {prod-short}, see the following sections:

* link:{site-baseurl}che-7/viewing-kubernetes-events[Viewing Kubernetes events]
* link:{site-baseurl}che-7/viewing-che-server-logs[Viewing {prod-short} server logs]
* link:{site-baseurl}che-7/viewing-external-service-logs[Viewing external service logs]
* link:{site-baseurl}che-7/viewing-che-workspaces-logs[Viewing {prod-short} workspaces logs]
* link:{site-baseurl}che-7/viewing-plug-in-broker-logs[Viewing the plug-in broker logs]
* link:{site-baseurl}che-7/collecting-logs-using-{prod-cli}[Collecting {prod} logs using {prod-cli}]


:context: {parent-context-of-retrieving-che-logs}
