---
title: "Using organizations"
keywords: organizations, user management, permissions
tags: [organizations]
sidebar: che_7_docs
permalink: che-7/using-organizations/
redirect_from:
  - organizations.html
folder: che-7/administration-guide
---

:parent-context-of-using-organizations: {context}

:context: using-organizations

[id="organizations-in-eclipse-che"]
== Organizations in Eclipse Che

Organizations allow administrators to group Eclipse Che users and allocate resources. The system administrator controls and allocates resources and permissions within the administrator dashboard.


[id="roles-in-an-organization"]
=== Roles in an organization

A user can have the following roles in an organization:

Members:: Create workspaces, manage their own workspaces, and use any workspaces they have permissions for.
Administrators:: Manage the organization, members, resources, and sub-organization, and can edit settings.
System Administrators:: Create root organizations, manages resources, members and sub-organizations. System administrators have more permissions than the administrators and members. 


[id="root-organizations-and-sub-organizations"]
=== Root organizations and sub-organizations 

The top-level organizations are called root organizations.   Multiple root organizations can be created.  Any organization can have zero to a set number of sub-organizations.  Only the system administrator can create root organizations and manage the resources of the root organization. 


[id="creating-an-organization"]
=== Creating an organization

Only the system administrator can create root organizations. An administrator can create sub-organizations. 

To create an organization:

.  Click the menu in the left sidebar.  A new page displays all the organizations in your system.

.  Click on the upper-left button to create a new organization.


[id="displaying-the-list-of-organizations"]
=== Displaying the list of organizations

The *Organization* page displays a list of all the organizations. The list contains the following information for each organization: number of members, total RAM, available RAM, and number of sub-organizations.


[id="adding-members-to-organizations"]
=== Adding members to organizations

To add members to an organization:

. Click the *Add* button to add a member.  A new pop-up window displays.  You can change the role of a member or remove them from the organization at any time. 

. Enter the new member name.  

[NOTE]
====
Users with the green checkmark beside their name already have an Eclipse Che account and can be added to the organization. Users without a checkmark do not have an account and cannot be added into the organization.
====


[id="workspaces-in-organizations"]
=== Workspaces in organizations

A workspace is created inside of an organization and uses the resources of the organization. The workspace creator chooses the organization on the *Workspace Creation* page.  


[id="setting-email-notifications"]
=== Setting email notifications

To send notifications from the Che server when a user joins or leaves an organization, you can do either of the following:

* Configure the SMTP server in the `che.env` file.  

* For OpenShift, add environment variables to the deployment. 

Che does not have a built-in SMTP server by default. You may use any mail server.

For example, to send a notification email to your Gmail account, set the following environment variables:

----
CHE_MAIL_PORT=465
CHE_MAIL_HOST=smtp.gmail.com
CHE_MAIL_SMTP_STARTTLS_ENABLE=true
CHE_MAIL_SMTP_AUTH=true
CHE_MAIL_SMTP_AUTH_USERNAME=no-reply@gmail.com
CHE_MAIL_SMTP_AUTH_PASSWORD=password
----


[id="creating-sub-organizations"]
=== Creating sub-organizations

To create a sub-organization:

*  On the *Organization Details* page, select the *Sub-Organizations* tab.

*  Click the *Add Sub-Organization* button.


The steps to create a sub-organization are the same as that for creating an organization. Use them to create the organization.

[id="adding-members-to-sub-organizations"]
=== Adding members to sub-organizations

You can only add members of the parent organization as members of the sub-organization.


[id="organization-and-sub-organization-administration"]
=== Organization and sub-organization administration

The settings of the organization are visible to all members of the organization.  Only the Eclipse Che system administrator can modify the settings.


[id="renaming-an-organization-or-sub-organization"]
=== Renaming an organization or sub-organization

[NOTE]
====
Only an Eclipse Che system administrator and administrator of the organization can rename an organization or sub-organization.
====

To rename an organization:

. Click the *Name* field to edit the name of the organization.  The save mode appears.

. Click the *Save* button to update the name.

The name of the organization or sub-organization must follow these rules: 

* Only alphanumeric characters and a single dash (-) can be used. 

* Spaces cannot be used. 

* Each organization name must be unique within the Eclipse Che installation. 

* Each sub-organization name must be unique within an organization.


[id="leaving-an-organization-or-sub-organization"]
=== Leaving an organization or sub-organization

To leave an organization, members need to contact the administrator of the organization or the system administrator of Eclipse Che.  


[id="deleting-an-organization-or-sub-organization"]
=== Deleting an organization or sub-organization

[IMPORTANT]
====
* Only system administrators or administrators of the organization can delete an organization or sub-organization.
* This action cannot be reverted, and all workspaces created under the organization will be deleted.
* All members of the organization will receive an email notification to inform them about the deletion of the organization.
====

To delete an organization or a sub-organization:

* Click the *Delete* button.


[id="allocating-resources-for-organizations"]
=== Allocating resources for organizations

Workspaces use the resources of the organization that are allocated by the system administrator. The resources for sub-organizations are taken from the parent organization. Administrators control the portion of resources, of the parent organization, that are available to the sub-organization.


[id="managing-limits"]
=== Managing limits

[NOTE]
====
Managing limits is restricted to the Eclipse Che system administrator and administrator of the organization.
====

The system configuration defines the default limits. The administrator of the organization manages only the limits of its sub-organizations. No resource limits apply to the organization by default.  The following are the limits defined by the system administrator:

* *Workspace Cap*: The maximum number of workspaces that can exist in the organization. 
* *Running Workspace Cap*: The maximum number of workspaces that can run simultaneously in the organization. +
* *Workspace RAM Cap*: The maximum amount of RAM that a workspace can use in GB.


[id="updating-organization-and-sub-organization-member-roles"]
=== Updating organization and sub-organization member roles

[NOTE]
====
Updating the members of an organization or sub-organization is restricted to the Eclipse Che system administrator and administrator of the organization.
====

To edit the role of an organization member:

. Click the *Edit* button in the *Actions* column. Update the role of the selected member in the pop-up window. 

. Click *Save* to confirm the update.


[id="removing-organization-and-sub-organization-members"]
=== Removing members from an organization and sub-organization

[NOTE]
====
Removing the members of an organization or sub-organization is restricted to the Eclipse Che system administrator and administrator of the organization.
====

To remove a member:

. Click the *Delete* button in the *Actions* column.  In the confirmation pop-up window, confirm the deletion.

To remove multiple members:

. Select the check boxes to select multiple members from the organization. 

. Click the *Delete* button that appears in the header of the table. The members that are removed from the organization will receive an email notification.

:context: {parent-context-of-using-organizations}
