// Module included in the following assemblies:
//
// authorizing-users

[id="che-system-permissions_{context}"]
= Che system permissions

Che system permissions control aspects of the whole Che installation. The following permissions are applicable to the system:

.Che system permission
[options="header",cols="2"]
|===
| Permission
| Description

| manageSystem
| Allows control of the system, workspaces, and organizations.
| setPermissions
| Allows updating the permissions for users on the system.
| manageUsers
| Allows creating and managing users.
| monitorSystem
| Allows accessing endpoints used for monitoring the state of the server.
|===

All system permissions are granted to the administrative user. The administrative user is configured in the `CHE_SYSTEM_ADMIN__NAME` property (the default is `admin`). The system permissions are granted when the Che server starts. If a user is not present in the Che user database when the Che server starts, the system permissions are granted after the first user’s login.
