---
title: External database setup
keywords:
tags: [database]
sidebar: che_7_docs
permalink: che-7/external-database-setup/
redirect_from:
  - che-7/database-setup/
folder: che-7/administration-guide
summary:
---

:page-liquid:
:parent-context-of-external-database-setup: {context}

[id="external-database-setup_{context}"]
= External database setup

:context: external-database-setup

The PostgreSQL database is used by the {prod-short} server for persisting data about the state of {prod-short}. It contains information about user accounts, workspaces, preferences, and other details.

By default, the {prod-short} Operator creates and manages the database deployment.

However, the {prod-short} Operator does not support full life-cycle capabilities, such as backups and recovery.

For a business-critical setup, configure an external database with the following recommended disaster-recovery options:

* High Availability (HA)
* Point In Time Recovery (PITR)

Configure an external PostgreSQL instance on-premises or use a cloud service, such as Amazon Relational Database Service (Amazon RDS). With Amazon RDS, it is possible to deploy production databases in a Multi-Availability Zone configuration for a resilient disaster recovery strategy with daily and on-demand snapshots.

The recommended configuration of the example database is:

[options="header"]
|===
|Parameter | Value
|Instance class | db.t2.small
|vCPU | 1
|RAM | 2 GB
|Multi-az | true, 2 replicas
|Engine version | 9.6.11
|TLS | enabled
|Automated backups | enabled (30 days)
|===

To make the Operator skip deploying a database and pass connection details of an existing database to a {prod-short} server using `chePostgresHostName`, `chePostgresPort`, `chePostgresUser`, `chePostgresPassword`, `chePostgresDb` parameters, specify the `externalDb: true` property in the {prod-short} Custom Resource.

.Additional resources

* link:https://www.postgresql.org/[PostgreSQL]
* link:https://aws.amazon.com/rds/[RDS]

:context: {parent-context-of-external-database-setup}
