// {prod-id-short}-compute-resources-requirements

[id="a-workspace-example_{context}"]
= A Workspace Example

This section describes a {prod-short} workspace example.

The following devfile defines the {prod-short} workspace:

[source,yaml]
----
apiVersion: 1.0.0
metadata:
 generateName: guestbook-nodejs-sample-
projects:
 - name: guestbook-nodejs-sample
   source:
     type: git
     location: "https://github.com/l0rd/nodejs-sample"
components:
 - type: chePlugin
   id: che-incubator/typescript/latest
 - type: kubernetes
   alias: guestbook-frontend
   reference: https://raw.githubusercontent.com/l0rd/nodejs-sample/master/kubernetes-manifests/guestbook-frontend.deployment.yaml
   mountSources: true
   entrypoints:
     - command: ['sleep']
       args: ['infinity']
----

This table provides the memory requirements for each workspace component:

[cols="1,3,1,1", options="header"]
.Total Workspace Memory Requirement and Limit
|===
|Pod
|Container Name
|Default Memory Limit
|Default Memory Request

|Workspace
|theia-ide (default `cheEditor`)
|512Mi
|512Mi

|Workspace
|machine-exec (default `chePlugin`)
|128Mi
|128Mi

|Workspace
|vscode-typescript (`chePlugin`)
|512Mi
|512Mi

|Workspace
|frontend (`kubernetes`)
|1Gi
|512Mi

|JWT Proxy
|verifier
|128Mi
|128Mi

2+>s|Total
>s|2.25Gi
>s|1.75Gi
|===

The `theia-ide` and `machine-exec` components are implicitly added to the workspace, even if they don't figure in the devfile. The resources required by `machine-exec` are the default for a `chePlugin` and the resources for `theia-ide` are specifically set in the `cheEditor` `meta.yaml` to **512Mi** as memoryLimit.

The typescript VS Code extension has overridden the default memory limits as well. In its `meta.yaml` file the limits are explicitly specified to **512Mi**.

{prod-short} is applying the defaults for the `kubernetes` component type: a memory limit of **1Gi** and memory request of **512Mi**.
It does that because the `kubernetes` component references a `Deployment` manifest that has a container specification with no resources limits or requests.

At last we need to consider the JWT container as well that requires **128Mi** of memory.

Summing all together we get **1.75Gi** of memory requests with a **2.25Gi** limit.
