// {prod-id-short}-compute-resources-requirements

[id="a-workspace-example_{context}"]
= A workspace example

This section describes a {prod-short} workspace example.

The following devfile defines the {prod-short} workspace:

[source,yaml]
----
apiVersion: 1.0.0
metadata:
 generateName: guestbook-nodejs-sample-
projects:
 - name: guestbook-nodejs-sample
   source:
     type: git
     location: "https://github.com/l0rd/nodejs-sample"
components:
 - type: chePlugin
   id: che-incubator/typescript/latest
 - type: kubernetes
   alias: guestbook-frontend
   reference: https://raw.githubusercontent.com/l0rd/nodejs-sample/master/kubernetes-manifests/guestbook-frontend.deployment.yaml
   mountSources: true
   entrypoints:
     - command: ['sleep']
       args: ['infinity']
----

This table provides the memory requirements for each workspace component:

[cols="1,3,1,1", options="header"]
.Total workspace memory requirement and limit
|===
|Pod
|Container name
|Default memory limit
|Default memory request

|Workspace
|theia-ide (default `cheEditor`)
|512 Mi
|512 Mi

|Workspace
|machine-exec (default `chePlugin`)
|128 Mi
|128 Mi

|Workspace
|vscode-typescript (`chePlugin`)
|512 Mi
|512 Mi

|Workspace
|frontend (`kubernetes`)
|1 Gi
|512 Mi

|JWT Proxy
|verifier
|128 Mi
|128 Mi

2+>s|Total
>s|2.25 Gi
>s|1.75 Gi
|===

* The `theia-ide` and `machine-exec` components are implicitly added to the workspace, even when not included in the devfile.
* The resources required by `machine-exec` are the default for `chePlugin`.
* The resources for `theia-ide` are specifically set in the `cheEditor` `meta.yaml` to *512 Mi* as `memoryLimit`.
* The Typescript VS Code extension has also overridden the default memory limits. In its `meta.yaml` file, the limits are explicitly specified to *512 Mi*.
* {prod-short} is applying the defaults for the `kubernetes` component type: a memory limit of *1 Gi* and a memory request of *512{nbsp}Mi*. This is because the `kubernetes` component references a `Deployment` manifest that has a container specification with no resource limits or requests.
* The JWT container requires *128 Mi* of memory.

Adding all together results in *1.75 Gi* of memory requests with a *2.25 Gi* limit.
