// Module included in the following assemblies:
//
// authentication-inside-the-workspace

[id="workspace-jwt-token-_{context}"]
= Workspace JWT token

Workspace tokens are JSON web tokens (link:https://jwt.io/[JWT]) that contain the following information in their claims:

* uid: The ID of the user who owns this token

* uname: The name of the user who owns this token

* wsid: The ID of a workspace which can be queried with this token

Each user is provided with a unique personal token for each workspace.
The structure of a token and the signature are different than they are in Keycloak. The following is an example token view:
```
# Header
{
  "alg": "RS512",
  "kind": "machine_token"
}
# Payload
{
  "wsid": "workspacekrh99xjenek3h571",
  "uid": "b07e3a58-ed50-4a6e-be17-fcf49ff8b242",
  "uname": "john",
  "jti": "06c73349-2242-45f8-a94c-722e081bb6fd"
}
# Signature
{
  "value": "RSASHA256(base64UrlEncode(header) + . +  base64UrlEncode(payload))"
}
```
The SHA-256 with RSA algorithm is used for signing machine tokens and it is not configurable. Also, there is no public service that distributes the public part of the key pair with which the token is signed.
