// authenticating-users

[id="authentication-modes_{context}"]
= Authentication modes

{prod-short} supports `multiuser` and `singleuser` mode.
 
.Single-user mode
`singleuser` mode is a mode that requires no authentication and anyone can access all cluster resources. In `singleuser` mode server performs all operations as the predefined user, regardless of who accesses the server. Therefore, this mode is suitable only for use in a private instance for testing product possibilities and configurations.
 
* H2 database is used. 
 
If {prod-short} is deployed in `singleuser` mode then there is no authentication and anyone who can access the URL of the {prod-short} deployment sees all workspaces and owns all resources. Since the deployment in this mode has fewer containers, RAM and CPU usage requirements are decreased. This mode is useful if the whole {prod-short} deployment is used by a single person or for lowering resources which are used for {prod-short} itself, but since the server does not authenticate, actions of several users logged in the same workspace can easily interfere with each other.
 
Usually, in `singleuser` mode {prod-short} has protection by third party services such as `haproxy` and `nginix`, but it is the responsibility of the user to configure them.

.Multi-user mod 
`multiuser` mode is the default mode for {prod-short} that requires user authentication and offers isolated workspaces and their resources. In multi-user mode workspaces are used in the scope of registered users and workspace definitions, the devfiles of particular workspaces, can be shared and reused between many users.
 
* {identity-provider} is used to authenticate users.
* PostgreSQL database is used. 
 
["changing-the-authentication-mode_{context}"]
== Changing the authentication mode
 
By default, the {prod-short} Operator deploys {prod-short} in `multiuser` mode. To change that: 

. Update the `CheCluster` Custom Resource (CR) to set the`CHE_MULTIUSER` property to `false`:
+
[source, yaml]
----
spec:
 server:
   customCheProperties:
      CHE_MULTIUSER: "false"
----
 
If {prod-short} is deployed via Helm installer, it defaults to `singleuser` mode. 

** To deploy {prod-short} in `multiuser` mode with Helm installer:

. Set the `multiuser` Helm chart field to `true`:
+
[subs="+quotes,+attributes"]
----
$ helm upgrade --install che --force --namespace che --set global.cheDomain=__<{prod-host}>__  -f multi-user.yaml
----

** To deploy {prod-short} in `multiuser` mode with {prod-cli}:
 
. Use `--multiuser` flag, or `-m` option to `{prod-cli} server:start` command:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start --platfrom=minikube --installer=helm --multiuser
----

////
.Additional resources
////
