---
title: Persistent Volumes backups
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/persistent-volumes-backups
folder: che-7/administration-guide
summary:
---

:parent-context-of-persistent-volumes-backups: {context}

[id="persistent-volumes-backups_{context}"]
= Persistent Volumes backups

Persistent Volumes (PVs) are used for storing the {prod-short} workspace data like a source code of a repository. 

To prevent data loss, you must back up PVs periodically. While it is possible to use backup solutions that are dependent on the underlying storage system (for example solutions that are Gluster / Ceph specific), it is recommended to use the storage agnostic tools for back up and restoring the Kubernetes cluster resources including PVs.

Use Velero, a recommended open source tool, to back up Kubernetes applications and their PVs. Velero can be run with a cloud provider or on-premises; it allows you to: 

* take backups of the cluster and restore in case of loss.
* migrate cluster resources to other clusters.
* replicate the production cluster to development and testing clusters.

.Additional resources

* link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Persistent Volumes documentation]
* link:https://www.gluster.org/[Gluster Gluster is a scalable network filesystem.]
* link:https://ceph.io[Ceph]
* link:https://github.com/vmware-tanzu/velero[Velero tool on GitHub]