---
title: Database Setup
keywords:
tags: [database]
sidebar: che_7_docs
permalink: che-7/database-setup/
folder: che-7/administration-guide
summary:
---

:page-liquid:
:parent-context-of-database-setup: {context}

[id="database-setup_{context}"]
= Database setup

PostgreSQL database is used by Che server for persisting data about the state of {prod-short}. It contains information about the user accounts, workspaces, preferences, and so on.

By default, {prod-short} operator creates and manages a database deployment.

However, {prod-short} operator does not support the full lifecycle capabilities like backups and recovery. For business-critical setup, it is recommended to configure an external database with the following disaster recovery options:

* High Availability (HA)
* Point In Time Recovery (PITR)

Configure an External PostgreSQL instance on-premises or use a cloud services such as Amazon Relational Database Service (Amazon RDS). With Amazon RDS, it is possible to deploy production databases in a Multi-Availability Zone configuration for a resilient disaster recovery strategy with daily and on-demand snapshots.

The recommended configuration of the example database is:

----
Instance class: db.t2.small
vCPU: 1
RAM: 2GB
Multi-az: True, 2 replicas
Engine version: 9.6.11
TLS: Enabled
Automated backups: Enabled (30 Days)
----

To make the operator skip deploying a database and pass connection details of an existing DB to a {prod-short} server using `chePostgresHostName`, `chePostgresPort`, `chePostgresUser`, `chePostgresPassword`, `chePostgresDb` parameters, specify the `externalDb: true` property in the {prod-short} Custom Resource.

.Additional resources

* link:https://www.postgresql.org/[PostgreSQL]
* link:https://aws.amazon.com/rds/[RDS]
