// deploying-the-registries

[id="deploying-registries-in-openshift_{context}"]
= Deploying registries in OpenShift

.Procedure

An OpenShift template to deploy the plug-in registry is available in the `openshift/` directory of the GitHub repository.

. To deploy the plug-in registry using the OpenShift template, run the following command:
+
[subs="+quotes"]
----
NAMESPACE=__<namespace-name>__  <1>
IMAGE_NAME="my-plug-in-registry"
IMAGE_TAG="latest"
oc new-app -f openshift/che-plugin-registry.yml \
 -n "$\{NAMESPACE}" \
 -p IMAGE="$\{IMAGE_NAME}" \
 -p IMAGE_TAG="$\{IMAGE_TAG}" \
 -p PULL_POLICY="IfNotPresent"
----
<1> If installed using {prod-cli}, the default {prod-short} namespace is `{prod-namespace}`. The OperatorHub installation method deploys {prod-short} to the users current namespace.

. The devfile registry has an OpenShift template in the `deploy/openshift/` directory of the GitHub repository. To deploy it, run the command:
+
[subs="+quotes"]
----
NAMESPACE=__<namespace-name>__  <1>
IMAGE_NAME="my-devfile-registry"
IMAGE_TAG="latest"
oc new-app -f openshift/che-devfile-registry.yml \
 -n "$\{NAMESPACE}" \
 -p IMAGE="$\{IMAGE_NAME}" \
 -p IMAGE_TAG="$\{IMAGE_TAG}" \
 -p PULL_POLICY="IfNotPresent"
----
<1> If installed using {prod-cli}, the default {prod-short} namespace is `{prod-namespace}`. The OperatorHub installation method deploys {prod-short} to the users current namespace.

. Check if the registries are deployed successfully on OpenShift.
ifeval::["{project-context}" == "crw"]
For details, see the xref:deploying-registries-in-kubernetes_deploying-the-registries[Deploying registries in Kubernetes] section, where the only difference when deploying in OpenShift is that Ingresses are replaced with routes.
endif::[]
ifeval::["{project-context}" == "che"]
The steps to check are similar to the Kubernetes steps. For details, see the xref:deploying-registries-in-kubernetes_deploying-the-registries[] section, where the only difference when deploying in OpenShift is that Ingresses are replaced with routes.
endif::[]
