// caching-images-for-faster-workspace-start

[id="deploying-image-puller-using-openshift-templates_{context}"]
= Deploying Image Puller using OpenShift templates

The Image Puller repository contains OpenShift templates for deploying on OpenShift.

ifeval::["{project-context}" == "che"]
Alternatively, you can use link:{site-baseurl}che-7/caching-images-for-faster-workspace-start/#deploying-the-kubernetes-image-puller-using-helm_caching-images-for-faster-workspace-start[Helm for deploying the Image Puller to OpenShift].
endif::[]

.Prerequisites

* A running OpenShift cluster.
* The `oc` binary file.

The following parameters are available to further configure the OpenShift templates:

include::examples/{project-context}-proc_deploying-image-puller-using-openshift-templates_parameters.adoc[] 

include::examples/{project-context}-prepulled-images-table.adoc[]

See xref:kubernetes-image-puller-configuration[] for more information about configuration values, such as `DAEMONSET_NAME`, `CACHING_INTERVAL_HOURS`, and `CACHING_MEMORY_REQUEST`.

.Procedure

*Installing*

. Clone the `kubernetes-image-puller` repository:
+
include::examples/{project-context}-proc_deploying-image-puller-using-openshift-templates_cloning-project.adoc[]

. Create a new OpenShift project to deploy the puller into:
+
include::examples/{project-context}-proc_deploying-image-puller-using-openshift-templates_prepare.adoc[]

. Process and apply the templates to deploy the puller:
+
include::examples/{project-context}-proc_deploying-image-puller-using-openshift-templates_process.adoc[]

*Verifying the installation*

. Confirm that a new deployment, `kubernetes-image-puller`, and a DaemonSet (named based on the value of the `DAEMONSET_NAME` parameter) exist. The DaemonSet needs to have a Pod for each node in the cluster:
+
[source%nowrap,dummy]
----
$ oc get deployment,daemonset,pod --namespace k8s-image-puller
deployment.extensions/kubernetes-image-puller   1/1       1            1           2m19s

NAME                                           DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.extensions/kubernetes-image-puller   1         1         1         1            1           <none>          2m10s

NAME                                           READY     STATUS    RESTARTS   AGE
pod/kubernetes-image-puller-5495f46497-mkd4p   1/1       Running   0          2m18s
pod/kubernetes-image-puller-n8bmf              3/3       Running   0          2m10s
----

. Check that the `ConfigMap` named `k8s-image-puller` has the values you specified in your parameter substitution, or that they contain the default values:
+
include::examples/{project-context}-proc_deploying-image-puller-using-openshift-templates_verify-configmap.adoc[]

