// editing-a-devfile-and-plug-in-at-runtime
// modifying-the-registries

[id="adding-a-devfile-at-runtime_{context}"]
= Adding a devfile at runtime

.Procedure

To add a devfile:

. Check out the devfile registry sources.
+
[subs="attributes+"]
----
$ git clone {url-devfile-registry-repo}; \
  cd {repo-path}che-devfile-registry
----

. Create a `devfile.yaml` and `meta.yaml` in some local folder. This can be done from scratch or by copying from an existing devfile.
+
[subs="+attributes"]
----
$ STACK="new-stack"; \
  mkdir -p devfiles/${STACK}; cp devfiles/{nodejs-stack}/* devfiles/${STACK}/
----

. If copying from an existing devfile, make changes to the devfile to suit your needs. Make sure the new devfile has a unique `displayName` and `description`.

. Get the name of the Pod that hosts the devfile registry container. To do this, filter the `component=devfile-registry` label:
+
[subs="+attributes"]
----
$ DEVFILE_REG_POD=$({orch-cli} get -o custom-columns=NAME:.metadata.name \
  --no-headers pod -l component=devfile-registry)
----

. Regenerate the registry's `index.json` file to include the new devfile.
+
[subs="+attributes"]
----
$ cd {repo-path}che-devfile-registry; \
  "$(pwd)/build/scripts/check_mandatory_fields.sh" devfiles; \
  "$(pwd)/build/scripts/index.sh" > index.json
----

. Copy the new `index.json`, `devfile.yaml` and `meta.yaml` files from the new local devfile folder to the container.
+
[subs="+attributes"]
----
$ cd che-devfile-registry; \
  {orch-cli} exec ${DEVFILE_REG_POD} -i -t -- mkdir -p /var/www/html/devfiles/${STACK}; \
  {orch-cli} cp $(pwd)/devfiles/${STACK}/meta.yaml ${DEVFILE_REG_POD}:/var/www/html/devfiles/${STACK}/meta.yaml; \
  {orch-cli} cp $(pwd)/devfiles/${STACK}/devfile.yaml ${DEVFILE_REG_POD}:/var/www/html/devfiles/${STACK}/devfile.yaml; \
  {orch-cli} cp $(pwd)/index.json ${DEVFILE_REG_POD}:/var/www/html/devfiles/index.json
----

. The new devfile can now be used from the existing {prod-short} instance of the devfile registry. To discover it, go to the {prod-short} dashboard, then click the *Workspaces* link. From there, click *Add Workspace* to see the updated list of available devfiles.
