// configuring-authorization

[id="setting-up-user-federation_{context}"]
= Setting up user federation

{identity-provider} federates external user databases and supports LDAP and Active Directory. You can test the connection and authenticate users before choosing a storage provider.

ifeval::["{project-context}" == "che"]
See the link:{identity-provider-docs-url}{identity-provider-version}/server_admin/index.html#_user-storage-federation[User storage federation] page in {identity-provider} documentation to learn how to add a provider.

See the link:{identity-provider-docs-url}{identity-provider-version}/server_admin/index.html#_ldap[LDAP and Active Directory] page in {identity-provider} documentation to specify multiple LDAP servers.
endif::[]

ifeval::["{project-context}" != "che"]
See the link:{identity-provider-docs-url}{identity-provider-version}/html-single/server_administration_guide/index#user-storage-federation[User storage federation] page in {identity-provider} documentation to learn how to add a provider.

See the link:{identity-provider-docs-url}{identity-provider-version}/html-single/server_administration_guide/index#user-storage-federation[LDAP and Active Directory] page in {identity-provider} documentation to specify multiple LDAP servers.
endif::[]
