// installing-the-jaeger-tracing-tool

[id="installing-the-jaeger-tracing-tool-for-{prod-id-short}-on-openshift-4_{context}"]
= Installing the Jaeger tracing tool for {prod-short} on OpenShift 4

This section provide information about using Jaeger tracing tool for testing an evaluation purposes.

To install the Jaeger tracing tool from a {prod-short} project in {ocp}, follow the instructions in this section.

.Prerequisites

* The user is logged in to the {ocp} web console.
* A instance of {prod-short} in an {ocp} cluster.

.Procedure

. In the {prod-short} installation {orch-namespace} of the {ocp} cluster,  use the `oc` client to create a new application for the Jaeger deployment.
+
[subs="+quotes,attributes"]
----
$ oc new-app -f / ${CHE_LOCAL_GIT_REPO}/deploy/openshift/templates/jaeger-all-in-one-template.yml:

--> Deploying template "__<project_name>__/jaeger-template-all-in-one" for "/home/user/{project-context}-projects/{project-context}/deploy/openshift/templates/jaeger-all-in-one-template.yml" to project __<project_name>__

     Jaeger (all-in-one)
     ---------
     Jaeger Distributed Tracing Server (all-in-one)

     * With parameters:
        * Jaeger Service Name=jaeger
        * Image version=latest
        * Jaeger Zipkin Service Name=zipkin

--> Creating resources ...
    deployment.apps "jaeger" created
    service "jaeger-query" created
    service "jaeger-collector" created
    service "jaeger-agent" created
    service "zipkin" created
    route.route.openshift.io "jaeger-query" created
--> Success
    Access your application using the route: 'jaeger-query-__<project_name>__.apps.ci-ln-whx0352-d5d6b.origin-ci-int-aws.dev.rhcloud.com'
    Run 'oc status' to view your app.
----

. Using the *Workloads -> Deployments* from the left menu of main {ocp} screen, monitor the Jaeger deployment until it finishes successfully.

. Select *Networking -> Routes* from the left menu of the main {ocp} screen, and click the URL link to access the Jaeger dashboard.

. Follow the steps in xref:enabling-{prod-id-short}-traces-collections_{context}[Enabling {prod-short} traces collections] to finish the procedure.
