// uninstalling-the-che-instance

[id="uninstalling-the-che-instance-using-chectl-after-chectl-installation_{context}"]
= Uninstalling the Che instance using chectl after chectl installation

The following section describes how to uninstall an instance of Eclipse Che that was installed using the `chectl` tool.

If Che was installed using the `chectl server:start` command and the `-n` argument was used, use the `-n` argument also to uninstall the Che instance. If `-n` was not used during namespace creation, the created namespace is named `che` by default.

// The default namespace for installations that use `crwctl` is `workspaces`, if a different name was not specified.

.Prerequisites

* Che was installed on an OpenShift cluster using `chectl`.
* OpenShift command-line tools and `chectl` are installed on the local workstation.
* The user is logged in a Che cluster using `oc` CLI.

.Procedure

. Stop the Eclipse Che Server.
+
----
# chectl server:stop
----

. Obtain the name of the namespace.
+
----
# oc get checluster --all-namespaces -o=jsonpath="{.items[*].metadata.namespace}"
----

. Remove Che from the cluster.
+
----
# chectl server:delete -n <namespace>
----
+
This will remove all the Che installations in the cluster.

////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
