// deploying-the-registries

[id="deploying-registries-in-openshift_{context}"]
= Deploying registries in OpenShift

.Procedure

An OpenShift template to deploy the plug-in registry is available in the `openshift/` directory of the GitHub repository.

. To deploy the plug-in registry using the OpenShift template, run the following command:
+
[subs="+quotes"]
----
NAMESPACE=__<namespace-name>__  <1>
IMAGE_NAME="my-plug-in-registry"
IMAGE_TAG="latest"
oc new-app -f openshift/che-plugin-registry.yml \
 -n "$\{NAMESPACE}" \
 -p IMAGE="$\{IMAGE_NAME}" \
 -p IMAGE_TAG="$\{IMAGE_TAG}" \
 -p PULL_POLICY="IfNotPresent"
----
<1> If installed using {prod-cli}, the default {prod-short} namespace is `{prod-namespace}`. The OperatorHub installation method deploys {prod-short} to the users current namespace.

. The devfile registry has an OpenShift template in the `deploy/openshift/` directory of the GitHub repository. To deploy it, run the command:
+
[subs="+quotes"]
----
NAMESPACE=__<namespace-name>__  <1>
IMAGE_NAME="my-devfile-registry"
IMAGE_TAG="latest"
oc new-app -f openshift/che-devfile-registry.yml \
 -n "$\{NAMESPACE}" \
 -p IMAGE="$\{IMAGE_NAME}" \
 -p IMAGE_TAG="$\{IMAGE_TAG}" \
 -p PULL_POLICY="IfNotPresent"
----
<1> If installed using {prod-cli}, the default {prod-short} namespace is `{prod-namespace}`. The OperatorHub installation method deploys {prod-short} to the users current namespace.

. Check if the registries are deployed successfully on OpenShift.

.. To verify that the new plug-in is correctly published to the plug-in registry, make a request to the registry path `/v3/plugins/index.json` (or `/devfiles/index.json` for the devfile registry).
+
[subs="+quotes,+attributes"]
----
$ URL=$(oc get -o 'custom-columns=URL:.spec.rules[0].host' \
  -l app=che-plugin-registry route --no-headers)
$ INDEX_JSON=$(curl -sSL http://$\{URL}/v3/plugins/index.json)
$ echo $\{INDEX_JSON} | grep -A 4 -B 5 "\"name\":\"my-plug-in\""
,\{
 "id": "my-org/my-plug-in/1.0.0",
 "displayName":"This is my first plug-in for {prod-short}",
 "version":"1.0.0",
 "type":"VS Code extension",
 "name":"my-plug-in",
 "description":"This plugin shows that we are able to add plugins to the registry",
 "publisher":"my-org",
 "links": \{"self":"/v3/plugins/my-org/my-plug-in/1.0.0" }
}
--
--
,\{
 "id": "my-org/my-plug-in/latest",
 "displayName":"This is my first plug-in for {prod-short}",
 "version":"latest",
 "type":"VS Code extension",
 "name":"my-plug-in",
 "description":"This plugin shows that we are able to add plugins to the registry",
 "publisher":"my-org",
 "links": \{"self":"/v3/plugins/my-org/my-plug-in/latest" }
}
----

.. Verify that the {prod-short} server points to the URL of the registry. To do this, compare the value of the `pass:[CHE_WORKSPACE_PLUGIN__REGISTRY__URL]` parameter in the `che` ConfigMap (or `pass:[CHE_WORKSPACE_DEVFILE__REGISTRY__URL]` for the devfile registry):
+
[subs="+quotes,+attributes"]
----
$ oc get \
  -o "custom-columns=URL:.data['CHE_WORKSPACE_PLUGIN__REGISTRY__URL']" \
  --no-headers cm/che
URL
http://che-plugin-registry-che.192.168.99.100.nip.io/v3
----
+
with the URL of the route:
+
[subs="+quotes,+attributes"]
----
$ oc get -o 'custom-columns=URL:.spec.rules[0].host' \
  -l app=che-plugin-registry route --no-headers
che-plugin-registry-che.192.168.99.100.nip.io
----

.. If they do not match, update the ConfigMap and restart the {prod-short} server.
+
[subs="+quotes,+attributes"]
----
$ oc edit cm/che
(...)
$ oc scale --replicas=0 deployment/che
$ oc scale --replicas=1 deployment/che
----

When the new registries are deployed and the {prod-short} server is configured to use them, the new plug-ins are available in the *Plugin* view of a workspace and the new stacks are displayed in the *New Workspace* tab of the user dashboard.
