// tracing-{prod-id-short}

[id="enabling-{prod-id-short}-metrics-collections_{context}"]
= Enabling {prod-short} metrics collections

.Prerequisites

* Installed Jaeger v1.12.0 or above. See instructions at xref:installing-the-jaeger-tracing-tool_tracing-{prod-id-short}[]

.Procedure

For Jaeger tracing to work, enable the following environment variables in your {prod-short} deployment:

[source,bash,subs="+quotes,+attributes"]
----
# Activating {prod-short} tracing modules
CHE_TRACING_ENABLED=true

# Following variables are the basic Jaeger client library configuration.
JAEGER_ENDPOINT="http://jaeger-collector:14268/api/traces"

# Service name
JAEGER_SERVICE_NAME="che-server"

# URL to remote sampler
JAEGER_SAMPLER_MANAGER_HOST_PORT="jaeger:5778"

# Type and param of sampler (constant sampler for all traces)
JAEGER_SAMPLER_TYPE="const"
JAEGER_SAMPLER_PARAM="1"

# Maximum queue size of reporter
JAEGER_REPORTER_MAX_QUEUE_SIZE="10000"
----

To enable the following environment variables:

. In the  `yaml` source code of the {prod-short} deployment, add the following configuration variables under `spec.server.customCheProperties`.
+
[source,yaml]
----
customCheProperties:
      CHE_TRACING_ENABLED: 'true'
      JAEGER_SAMPLER_TYPE: const
      DEFAULT_JAEGER_REPORTER_MAX_QUEUE_SIZE: '10000'
      JAEGER_SERVICE_NAME: che-server
      JAEGER_ENDPOINT: 'http://jaeger-collector:14268/api/traces'
      JAEGER_SAMPLER_MANAGER_HOST_PORT: 'jaeger:5778'
      JAEGER_SAMPLER_PARAM: '1'
----

. Edit the `JAEGER_ENDPOINT` value to match the name of the Jaeger collector service in your deployment.
+
From the left menu of the main {ocp} screen, obtain the value of JAEGER_ENDPOINT by navigation to *Networking -> Services*. Alternatively, execute the following `oc` command:
+
----
$ oc get services
----
+
The requested value is included in the service name that contains the `collector` string.



.Additional resources
* For additional information about custom environment properties and how to define them in CheCluster Custom Resource, see link:{site-baseurl}che-7/advanced-configuration-options/[Advanced configuration options].
*  For custom configuration of Jaeger, see the list of link:https://github.com/jaegertracing/jaeger-client-go#environment-variables[Jaeger client environment variables].
