[id="crw-including-the-plug-in-binaries-in-the-registry-image_{context}"]
= Including the plug-in binaries in the registry image

:context: including-the-plug-in-binaries-in-the-registry-image

The plug-in registry of {prod-short} differs from the upstream version.  Where the upstream only hosts {prod-short} plug-in metadata, the {prod-short} plug-in registry also hosts the corresponding binaries, and is built in an offline mode by default.  This means the binaries are already hosted in the plug-in-registry image.  

There may be times where you want to add a new plug-in, or reference a different version of one.  

This section describes how to modify a plug-in `meta.yaml` file to point to a new plug-in and rebuild a new registry in offline mode that contains the modified plug-in `meta.yaml` file and the plug-in binary file. 

.Prerequisites

* An instance of {prod-short} is available.
* The `oc` tool is available.

.Procedure

. Clone the `codeready-workspaces` repository

+
```shell
git clone https://github.com/redhat-developer/codeready-workspaces
cd codeready-workspaces/dependencies/che-plugin-registry
```

. Identify the binaries you wish to change in your plugin registry

+ 
A `meta.yaml` has an `extension` section describing the URLs of required extensions for a plugin.  For example, the `redhat/java11/0.63.0` plugin lists the following two extensions:

+
.meta.yaml
[source,yaml]
----
extensions:
  - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix
  - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.63.0-2222.vsix
----

+
We will change the first extension and to refernce the version hosted on GitHub and rebuild the plug-in registry so that when we use the `redhat/java11/0.63.0` che plugin, the GitHub binary will be fetched from our che-plugin-registry server.  Set the following environment variables to help with the subsequent commands:

+
```shell
ORG=redhat
NAME=java11
CHE_PLUGIN_VERSION=0.63.0
VSCODE_JAVA_DEBUG_VERSION=0.26.0
VSCODE_JAVA_DEBUG_URL="https://github.com/microsoft/vscode-java-debug/releases/download/0.26.0/vscjava.vscode-java-debug-0.26.0.vsix"
OLD_JAVA_DEBUG_META_YAML_URL="https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix"
```

. Get the plug-in registry URL:
+
```shell
oc get route plugin-registry -o jsonpath='{.spec.host}' -n ${CHE_NAMESPACE}
```

+
Save this value in a variable called `PLUGIN_REGISTRY_URL`

+

. Update the URLs in the `meta.yaml` file, so that they point to the VS Code extension binaries that are saved in the registry container:

+
IMPORTANT: By default, {prod-short} is deployed with TLS enabled.  If your installation does not use tls, be sure to substitute `http://` in `NEW_JAVA_DEBUG_URL` and `NEW_JAVA_LS_URL`

+
```shell
sed -i -e "s#${OLD_JAVA_DEBUG_META_YAML_URL}#${VSCODE_JAVA_DEBUG_URL}#g" \
  ./v3/plugins/${ORG}/${NAME}/${CHE_PLUGIN_VERSION}/meta.yaml
  ./v3/plugins/${ORG}/${NAME}/${CHE_PLUGIN_VERSION}/meta.yaml
```

+
TIP: We use the delimiter `#` in our `sed` substitution script because our substitutions contain forward slashes, which will confuse `sed` if we use the default `/` delimiter.


. Confirm that the `meta.yaml` has the correctly substituted URLs:

+
```shell`
cat ./v3/plugins/${ORG}/${NAME}/${CHE_PLUGIN_VERSION}/meta.yaml
```

+
.meta.yaml
[source,yaml]
----
extensions:
  - https://plugin-registry-che.apps-crc.testing/v3/plugins/redhat/java11/0.63.0/vscode-java-debug-0.26.0.vsix
  - https://plugin-registry-che.apps-crc.testing/v3/plugins/redhat/java11/0.63.0/java-0.63.0-2222.vsix
----

. Build and deploy the plug-in registry using the instructions in the link:{site-baseurl}che-7/building-and-running-a-custom-registry-image[Building and running a custom registry image] section.

:context: {parent-context-of-including-the-plug-in-binaries-in-the-registry-image}
