// authenticating-to-the-{prod-id-short}-server

[id="authenticating-to-the-{prod-id-short}-server-using-oauth_{context}"]
= Authenticating to the {prod-short} server using OAuth

For easy user interaction with third-party services, the {prod-short} server supports OAuth authentication. OAuth tokens are also used for GitHub-related plug-ins.

OAuth authentication has two main flows:

embedded:: Used build in {prod-short} server mechanism to communicate with OAuth providers
delegated:: Default. Delegate OAuth authentication to {identity-provider} server.

To switch between the two implementations, use the `che.oauth.service_mode=__<embedded|delegated>__` configuration property.

The main REST endpoint in the OAuth API is `/api/oauth`, which contains:

* An authentication method `/authenticate` that the OAuth authentication flow can start with.
* A callback method `/callback` to process callbacks from the provider.
* A token method 'GET' `/token` to retrieve the current user's OAuth token.
* A token method 'DELETE' `/token` to invalidated the current user's OAuth token.
* A 'GET' method `/` to get the list of configured identity providers.
