[id="viewing-che-theia-ide-logs-on-the-cli_{context}"]
= Viewing Che-Theia editor logs using the OpenShif CLI

Observing Che-Theia editor logs helps get a better understanding and insight over the plugins that got loaded by the editor. This section describes how to access the Che-Theia editor logs and obtain their output using the OpenShift CLI.

.Prerequisites
* {prod-short} is deployed in a OpenShift cluster. This can validated by osbserving Openshift logs. See xref:viewing-the-state-of-the-{prod-id-short}-cluster-deployment-using-openshift-4-cli-tools_{context}[].
* A workspace is created.
* User is located in a {prod-short} installation namespace.

.Procedure

. Obtain the list of the available pods:
+
----
$ oc get pods
----
+
.Example
[subs="quotes", options="nowrap",role=white-space-pre]
----
$ oc get pods
NAME                                              READY  STATUS   RESTARTS  AGE
{prod-deployment}-9-xz6g8                                 1/1    Running  1         15h
workspace0zqb2ew3py4srthh.go-cli-549cdcf69-9n4w2  4/4    Running  0         1h
----

. Obtain the list of the available containers in the particular pod:
+
[subs="quotes", options="nowrap",role=white-space-pre]
----
$ oc get pods <name-of-pod> -o jsonpath='\{.spec.containers[*].name}'
----
+
.Example:
[subs="quotes", options="nowrap",role=white-space-pre]
----
$ oc get pods workspace0zqb2ew3py4srthh.go-cli-549cdcf69-9n4w2 -o
jsonpath='\{.spec.containers[*].name}'
> go-cli che-machine-exechr7 theia-idexzb vscode-gox3r
----

. Get logs from the `theia/ide` container:
+
[subs="+quotes"]
----
$ oc logs -f <name-of-pod> -c <name-of-container>
----
+
.Example:
[subs="quotes", options="nowrap",role=white-space-pre]
----
$ oc logs -f workspace0zqb2ew3py4srthh.go-cli-549cdcf69-9n4w2 -c
theia-idexzb
>root INFO unzipping the plug-in 'task_plugin.theia' to directory: /tmp/theia-unpacked/task_plugin.theia
root INFO unzipping the plug-in 'theia_yeoman_plugin.theia' to directory: /tmp/theia-unpacked/theia_yeoman_plugin.theia
root WARN A handler with prefix term  is already registered.
root INFO [nsfw-watcher: 75] Started watching: /home/theia/.theia
root WARN e.onStart is slow, took: 367.4600000013015 ms
root INFO [nsfw-watcher: 75] Started watching: /projects
root INFO [nsfw-watcher: 75] Started watching: /projects/.theia/tasks.json
root INFO [4f9590c5-e1c5-40d1-b9f8-ec31ec3bdac5] Sync of 9 plugins took: 62.26000000242493 ms
root INFO [nsfw-watcher: 75] Started watching: /projects
root INFO [hosted-plugin: 88] PLUGIN_HOST(88) starting instance
----
