.Example:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
...
----

// The corresponding procedure is underdeveloped. Parts of this example will likely end up in the procedure. A comprehensive rewrite is needed. max-cx

* The following example shows you how to mount the secret as a file by including the `<url>/mount-as: file` annotation.
+
[source,yaml,subs="+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/target-container: maven
    che.eclipse.org/mount-path: {prod-home}/.m2/
    che.eclipse.org/mount-as: file
  labels:
...
----

* To define the default behavior for mounting secrets, use the `/automount-workspace-secret` annotation. Developers can override this default in a devfile. This annotation takes a boolean value:
** `true` enables automatic mounting into all workspace containers.
** `false` disables automatic mounting into all workspace containers. To mount a secret, a user must request it in the devfile component by using the `automountWorkspaceSecrets:true` property.
+
[source,yaml,subs="+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: {prod-home}/.m2/
    che.eclipse.org/mount-as: file
  labels:
...
----

* The following example shows you how to mount the `settings.xml` file at the `{prod-home}/.m2/` path of all workspace containers.
+
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: {prod-home}/.m2/
    che.eclipse.org/mount-as: file
data:
  settings.xml: __<base64 encoded data content here>__
----
+
NOTE: The `data` of the {orch-name} secret can contain several items. The names of these items must match the desired file name mounted into the container.

* You can override the mount path of the secret for specific workspace components. To do this, declare an additional volume for a component. Match its `name` and `containerPath` with the mount path of the secret, as shown in the following example.
//"volume" here means storage volume? max-cx
+
[source,yaml,subs="+quotes"]
----
apiVersion: 1.0.0
metadata:
  ...
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   volumes:
     - name: <secret-name>
       containerPath: /my/new/path
   ...
----

NOTE: With overrides, an alias declared in the components will distinguish the containers for the override, and the override path will apply only to those containers.
