.Example:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
...
----

// The corresponding procedure is underdeveloped. Parts of this example will likely end up in the procedure. A comprehensive rewrite is needed. max-cx

* The following example shows how to mount the secret as an environment variable by including the `<url>/mount-as: env` annotation:

+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----
+
In this example, the `FOO_ENV` environment variable and `myvalue` key value are provisioned into all workspace containers as follows:

** The secret's environment variable, `env-name`, is declared as `FOO_ENV` in the `annotations`.

** The `automount-workspace-secret` annotation with a boolean value defines the default secret mounting behavior (that can be overridden in a devfile):

*** `'true'` enables automatic mounting into all workspace containers.

*** `'false'` disables the mounting process until it is explicitly requested in a devfile component using the `automountWorkspaceSecrets:true` property.

* If the secret has more than one data key, declare an environment variable name using a `<__key__>_env-name` annotation for each data key, as shown in the following example. In this example, you provision the `myvalue` and `othervalue` data key values, and the environment variable names, `FOO_ENV` and `OTHER_ENV`, into all workspace containers.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: myvalue
  otherkey: othervalue
----

* The maximum length of an annotation name in a {orch-name} secret is 63 characters, of which 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the secret.
