[NOTE]
====
Note that the following example describes variations in the usage of the `target-container` annotation in versions 7.14 and 7.15 of {prod}.
====
+
.Example:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
...
----
+
Annotations must indicate that the given secret is mounted as an environment variable, provides variable names, and optionally, specifies the container name where this mount will be applied. If there is no target-container annotation defined, the secret will be mounted into all user containers of the {prod-short} workspace, but this is applicable *_only for the {prod-short} version 7.14_*.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/target-container: maven
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----
+
This results in the environment variable named `FOO_ENV` and the value `myvalue` being provisioned into the container named `maven`.
+
*_Since the {prod-short} version 7.15_*, the `target-container` annotation is deprecated and `automount-workspace-secret` annotation with Boolean values is introduced. Its purpose is to define the default secret mounting behavior, with the ability to be overridden in a devfile. The `true` value enables the automatic mounting into all workspace containers. In contrast, the `false` value disables the mounting process until it is explicitly requested in a devfile component using the `automountWorkspaceSecrets:true` property.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----
+
This results in the environment variable named `FOO_ENV` and the value `myvalue` being provisioned into all workspace containers.
+
If the secret provides more than one data item, the environment variable name must be provided for each of the data keys as follows:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: myvalue
  otherkey: othervalue
----
+
This results in two environment variables with names `FOO_ENV`, `OTHER_ENV`, and values `myvalue` and `othervalue`, being provisioned into all workpsace containers.
+
NOTE: The maximum length of annotation names in a Kubernetes secret is 63 characters, where 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the secret.
