.Example:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
...
----

Annotations must indicate that the given secret is to be mounted as an environment variable and must also provide the variable name for it.

The `automount-workspace-secret` annotation with a boolean value defines the default secret mounting behavior, which can be overridden in a devfile:

** The `true` value enables automatic mounting into all workspace containers.

** The `false` value disables the mounting process until it is explicitly requested in a devfile component using the `automountWorkspaceSecrets:true` property.

In the following example, the environment variable `FOO_ENV` and the value `myvalue` will be provisioned into all workspace containers:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----

If the secret provides more than one data key, you must provide an environment variable name for each of the keys.

In the following example, the two environment variables `FOO_ENV` and `OTHER_ENV` and the two values `myvalue` and `othervalue` will be provisioned into all workspace containers:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: myvalue
  otherkey: othervalue
----

NOTE: The maximum length of an annotation name in a {orch-name} secret is 63 characters, of which 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the secret.
