.Example:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
...
----

The following examples show more `metadata` of a secret:

* The `annotations` must specify that the given secret is to be mounted as a file: `/mount-as: file`.
+
[source,yaml,subs="+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/target-container: maven
    che.eclipse.org/mount-path: {prod-home}/.m2/
    che.eclipse.org/mount-as: file
  labels:
...
----

* The `/automount-workspace-secret` annotation with a boolean value defines the default secret mounting behavior (that can be overridden in a devfile):
** `true` enables automatic mounting into all workspace containers.
** `false` disables the mounting process until it is explicitly requested in a devfile component using the `automountWorkspaceSecrets:true` property.
+
[source,yaml,subs="+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: {prod-home}/.m2/
    che.eclipse.org/mount-as: file
  labels:
...
----

* In the next example, the file `settings.xml` will be mounted at the `{prod-home}/.m2/` path of all workspace containers.
+
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: {prod-home}/.m2/
    che.eclipse.org/mount-as: file
data:
  settings.xml: __<base64 encoded data content here>__
----
+
NOTE: The `data` of the {orch-name} secret may contain several items, whose names must match the desired file name mounted into the container.

* It is possible to override the secret's mount path for specific components of the workspace by declaring an additional volume for a component with the volume's `name` matching the secret's name and with the desired mount path (`/my/new/path`) as `containerPath`, as shown next.
//"volume" here means storage volume? max-cx
+
[source,yaml,subs="+quotes"]
----
apiVersion: 1.0.0
metadata:
  ...
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   volumes:
     - name: <secret-name>
       containerPath: /my/new/path
   ...
----

NOTE: For such overrides, you must declare an alias for the components to distinguish the containers which belong to them and to apply the override path exclusively to those containers.
