kind: Secret
apiVersion: v1
metadata:
  name: nexus-cer
  annotations:
    controller.devfile.io/mount-path: /home/user/certs
    controller.devfile.io/mount-as: file
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  nexus.cer: >-
    <base64_encoded_public_cert(base64 -w0 nexus.cer)>