:_content-type: PROCEDURE
:description: Cache default {prod-short} images on all nodes
:keywords: administration-guide, image-puller, CLI
:navtitle: Cache default {prod-short} images on all nodes
:page-aliases: administration-guide:configuring-image-puller-to-pre-pull-default-che-images.adoc

[id="configuring-image-puller-to-pre-pull-default-che-images"]
= Cache default {prod-short} images on all nodes

Cache default {prod-short} images on all nodes by enabling {image-puller-name}.
The {prod} Operator controls the list of images to pre-pull and automatically updates them
on {prod-short} upgrade.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running on {kubernetes} cluster.

* {image-puller-name-short} is installed on {kubernetes} cluster.

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Configure the {image-puller-name-short} to pre-pull {prod-short} images.
+
[source,shell,subs="+attributes,"]
----
{orch-cli} patch checluster/{prod-checluster} \
    --namespace {prod-namespace} \
    --type='merge' \
    --patch '{
              "spec": {
                "components": {
                  "imagePuller": {
                    "enable": true
                  }
                }
              }
            }'
----

.Verification

* Verify that the image puller is enabled:
+
[source,shell,subs="+attributes"]
----
{orch-cli} get checluster {prod-checluster} -n {prod-namespace} -o jsonpath='{.spec.components.imagePuller.enable}'
----

.Additional resources

* xref:retrieving-default-list-of-images-for-kubernetes-image-puller.adoc[]
