:_content-type: PROCEDURE
:description: Cache additional images for faster starts
:keywords: administration-guide, image-puller, CLI
:navtitle: Cache additional images for faster starts
:page-aliases: administration-guide:configuring-image-puller-to-pre-pull-additional-images.adoc

[id="configuring-image-puller-to-pre-pull-additional-images"]
= Cache additional images for faster starts

Cache additional images with {image-puller-name} to reduce workspace startup time by ensuring that required images are already cached on each node.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running on {kubernetes} cluster.

* {image-puller-name-short} is installed on {kubernetes} cluster.

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Create `{image-puller-namespace}` namespace:
+
[source,shell,subs="+attributes,"]
----
{orch-cli} create namespace {image-puller-namespace}
----

. Create `{image-puller-cr-name}` Custom Resource:
+
[source,shell,subs="+attributes,"]
----
{orch-cli} apply -f - <<EOF
apiVersion: che.eclipse.org/v1alpha1
kind: KubernetesImagePuller
metadata:
  name: k8s-image-puller-images
  namespace: {image-puller-namespace}
spec:
  images: "__NAME-1__=__IMAGE-1__;__NAME-2__=__IMAGE-2__"
EOF
----
+
where:
+
`images`:: The semicolon-separated list of images in `name=image` format.

.Verification

* Verify that the image puller `DaemonSet` is running in the `{image-puller-namespace}` namespace:
+
[source,shell,subs="+attributes"]
----
{orch-cli} get daemonset -n {image-puller-namespace}
----

.Additional resources

* https://github.com/che-incubator/kubernetes-image-puller[{image-puller-name} source code repository]

* https://github.com/che-incubator/kubernetes-image-puller-operator[{image-puller-operator-name} source code repository]

