:_content-type: PROCEDURE
:description: Cache your organization's custom images
:keywords: administration-guide, image-puller, CLI
:navtitle: Cache your organization's custom images
:page-aliases: administration-guide:configuring-image-puller-to-pre-pull-custom-images.adoc

[id="configuring-image-puller-to-pre-pull-custom-images"]
= Cache your organization's custom images

Cache your organization's custom images with {image-puller-name} so that workspaces using organization-specific container images start without waiting for large image downloads.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running on {kubernetes} cluster.

* {image-puller-name-short} is installed on {kubernetes} cluster.

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Configure the {image-puller-name-short} to pre-pull custom images.
+
[source,shell,subs="+attributes,+quotes"]
----
{orch-cli} patch checluster/{prod-checluster} \
    --namespace {prod-namespace} \
    --type='merge' \
    --patch '{
              "spec": {
                "components": {
                  "imagePuller": {
                    "enable": true,
                    "spec": {
                      "images": "__NAME-1__=__IMAGE-1__;__NAME-2__=__IMAGE-2__"
                    }
                  }
                }
              }
            }'
----
+
where:
+
`images`:: The semicolon-separated list of images in `name=image` format.

.Verification

* Verify that the image puller is configured with the custom images:
+
[source,shell,subs="+attributes"]
----
{orch-cli} get checluster {prod-checluster} -n {prod-namespace} -o jsonpath='{.spec.components.imagePuller.spec.images}'
----