:_content-type: CONCEPT
:description: How image caching speeds up workspace starts
:navtitle: How image caching speeds up workspace starts

[id="how-image-caching-speeds-up-workspace-starts"]
= How image caching speeds up workspace starts

To improve workspace start time, use the {image-puller-name-short}, a community-supported {prod-short}-agnostic component that can be used to pre-pull images for {platforms-name} clusters.

The {image-puller-name-short} is an additional {platforms-name} deployment which creates a _DaemonSet_ that can be configured to pre-pull relevant {prod-short} workspace images on each node.
These images would already be available when a {prod-short} workspace starts, therefore improving the workspace start time.

For instructions on deploying, configuring, and reviewing cached images, see Additional resources.

[role="_additional-resources"]
.Additional resources

* xref:installing-image-puller-on-kubernetes-by-using-cli.adoc[]
* xref:installing-image-puller-on-openshift-using-cli.adoc[]
* xref:installing-image-puller-on-openshift-by-using-the-web-console.adoc[]
* xref:configuring-image-puller-to-pre-pull-default-che-images.adoc[]
* xref:configuring-image-puller-to-pre-pull-custom-images.adoc[]
* xref:configuring-image-puller-to-pre-pull-additional-images.adoc[]
* xref:retrieving-default-list-of-images-for-kubernetes-image-puller.adoc[]
* link:https://github.com/che-incubator/{image-puller-repository-name}[{image-puller-name} source code repository]
