:_content-type: REFERENCE
:description: Collect logs with {prod-cli}
:keywords: administration-guide, collecting-logs-using-chectl
:navtitle: Collect logs with {prod-cli}
:page-aliases: .:collecting-logs-using-chectl.adoc

[id="collecting-logs-using-{prod-cli}"]
= Collect logs with {prod-cli}

The `{prod-cli}` management tool provides commands to collect {prod-short} logs for troubleshooting and diagnostics. These commands automate log collection from the multiple containers that comprise a {prod} installation in the {orch-name} cluster.

The following commands collect {prod} logs from the {orch-name} cluster:

`{prod-cli} server:logs`:: 
Collects existing {prod} server logs and stores them in a directory on the local machine.
By default, logs are downloaded to a temporary directory on the machine.
However, this can be overwritten by specifying the `-d` parameter.
For example, to download {prod-short} logs to the `/home/user/che-logs/` directory, use the command
+
[source,shell,subs="+attributes"]
----
{prod-cli} server:logs -d /home/user/che-logs/
----
+
When run, `{prod-cli} server:logs` prints a message in the console specifying the directory that will store the log files:
+
[subs="+attributes"]
----
{prod} logs will be available in '/tmp/chectl-logs/1648575098344'
----
+
If {prod} is installed in a non-default {orch-namespace}, `{prod-cli} server:logs` requires the `-n <NAMESPACE>` parameter, where `<NAMESPACE>` is the {platforms-namespace} in which {prod} was installed. For example, to get logs from {prod-short} in the `my-namespace` {orch-namespace}, use the command
+
[source,shell,subs="+attributes"]
----
{prod-cli} server:logs -n my-namespace
----

`{prod-cli} server:deploy`:: 
Logs are automatically collected during the {prod-short} installation when installed using `{prod-cli}`. As with `{prod-cli} server:logs`, the directory logs are stored in can be specified using the `-d` parameter.

.Additional resources

* {link-prod-cli-documentation}
