---
title: "Getting started with factories"
keywords: chedir, factories
tags: [chedir, factories]
sidebar: che_6_docs
permalink: che-6/factories-getting-started.html
redirect_from: factories-getting-started.html
folder: che-6/portable-workspaces
---

A factory is a template containing configuration to automate the generation of a new workspace using a factory identifier added to the IDE URL. Factories can be used to create replicas of existing workspaces or to automate the provisioning of statically or dynamically defined workspaces.


[id="trying-a-factory"]
== Trying a factory

Clone a public workspace on `che.openshift.io` by clicking https://che.openshift.io/f?id=factorymtyoro1y0qt8tq2[try a factory].


[id="using-factories"]
== Using factories

Factories can be invoked from a factory URL built in multiple ways. You can replace the `localhost:8080` domain with the hostname of any Che installation.

Using factories on `che.openshift.io` requires the user to be authenticated. Users who are not authenticated see a login screen after they click on the factory URL. Users without an account can create one using the same dialog.


[id="invoking-factories-using-their-unique-hashcodes"]
== Invoking factories using their unique hashcodes

[cols="1,5"]
|===
|Format | `/f?id={hashcode}` +
 `/factory?id={hashcode}`
|Sample |  https://localhost:8080/f?id=factorymtyoro1y0qt8tq2j
|===


[id="invoking-a-named-factory"]
== Invoking a named factory

[cols="1,5"]
|===
|Format | `/f?user={username}&name={factoryname}` +
 `/factory?user={username}&name={factoryname}`
|Sample | https://localhost:8080/f?user=che&name=starwars +
 https://localhost:8080/factory?user=che&name=starwars
|===


[id="invoking-a-factory-for-a-specific-git-repository"]
== Invoking a factory for a specific git repository

[cols="1,5"]
|===
|Format | `/f?url={git URL}`
|Sample | http://localhost:8080/f?url=https://github.com/eclipse/che +
 http://localhost:8080/f?url=https://github.com/eclipse/che/tree/language-server +
 http://localhost:8080/f?url=https://gitlab.com/benoitf/simple-project
|===

Once a factory is executed, it either loads an existing workspace or generates a new one, depending on the factory configuration. The name of the workspace is determined by the factory configuration, and its name becomes a part of the URL used to access the factory. The format is: `{hostname}/{username}/{workspace}`.


[id="next-steps"]
== Next steps

You have just created your first developer workspace using factories. Read on to learn more about:

* How to link:creating-factories.html[create factories]
* Customizing factories with the link:factories_json_reference.html[factory JSON reference]
