:prod-short: Che
:prod-url: https://__<che_fqdn>__

[id="uo-prod-short-urls_{context}"]
= {prod-short} URLs

Working with {prod-short} involves regular use of the following URLs:

* URL of your organization's {prod-short} instance
* URL of your {prod-short} dashboard
* URLs for starting a new workspace
* URLs of your workspaces

[TIP]
====
Save each URL to your browser bookmarks for convenience!

* In Mozilla Firefox, go to *☰* *>* *Bookmarks* *>* *Manage bookmarks Ctrl+Shift+O* *>* *Bookmarks Toolbar* *>* *Organize* *>* *Add bookmark*.

* In Google Chrome, go to *⋮* *>* *Bookmarks* *>* *Bookmark manager* *>* *Bookmarks bar* *>* *⋮* *>* *Add new bookmark*.
====

== URL of your organization's {prod-short} instance

Your {prod-short} administrator must provide you with the URL of your organization's {prod-short} instance that you need as a user to access your {prod-short} dashboard and start and manage your workspaces. This URL is a fully qualified domain name (FQDN):

[subs="+quotes,+attributes"]
----
{prod-url}
----

== URL of your {prod-short} dashboard

The *Workspaces* page of your {prod-short} dashboard is where you manage your workspaces and verify their current states. The URL syntax for this page is like so:

[subs="+quotes,+attributes"]
----
{prod-url}/dashboard/#/workspaces
----

== URLs for starting a new workspace

For every remote Git repository that you plan to use inside a workspace, you can prepare the following URL:
[subs="+quotes,+attributes"]
----
{prod-url}#__<Git_repository_URL>__
----

Visiting this URL in a browser tab starts a new workspace that contains a clone of that repository.

.URL syntax for starting a new workspace that contains a clone of a GitHub-hosted repository
====
* `{prod-url}#https://github.com/__<user_or_org>__/__<repository>__` starts a new workspace with a clone of the default branch.
* `{prod-url}#https://github.com/__<user_or_org>__/__<repository>__/tree/__<branch_name>__` starts a new workspace with a clone of the specified branch.
* `{prod-url}#https://github.com/__<user_or_org>__/__<repository>__/pull/__<pull_request_id>__` starts a new workspace with a clone of the branch of the pull request.
====

.URL syntax for starting a new workspace that contains a clone of a GitLab-hosted repository
====
* `{prod-url}#https://gitlab.com/__<user_or_org>__/__<repository>__` starts a new workspace with a clone of the default branch.
* `{prod-url}#https://gitlab.com/__<user_or_org>__/__<repository>__/-/tree/__<branch>__` starts a new workspace with a clone of the specified branch.
====

//Looks like we need to check with Florent whether the merge request links for GitLab are supported like GH PRs. Or why don't I test it myself, if I can? Will I be able to?

== URLs of your workspaces

When {prod-short} starts a new workspace for you, the workspace has a unique URL that you can visit in a browser tab to open the workspace:

[subs="+quotes,+attributes"]
----
{prod-url}#__<URL_of_your_workspace>__
----