//i can reuse some parts of this module for both Projects without Git and Projects with Git, with or without a shared snip

1. "Che host URL"

the URL of your organization's {prod-short} instance

Your administrator must provide you with "Che host URL" which you need to access the {prod-short} dashboard and start and manage your workspaces. Save this 
for example in your browser favorites toolbar or another location which you keep open daily, so that you can simply click on the previously saved link, as opposed to having to put this link together from the "Che host URL" and the repository URL. Keep it somewhere handy.
//reuse the last setence(s)
+
[subs="+quotes,+attributes"]
----
https://__<{prod-url}>__#__<Git_repository_URL>__
----
//PROB NEED TO UPDATE THE UPSTREAM VALUE FOR {prod-url} BEFOREHAND
//need to mention that the {prod-short} URL is FQDM?
//`pass:c,a,q[{prod-url}/#__<GIT_REPOSITORY_URL>__]`
//pass:[<!-- vale CheDocs.TechnicalTerms = YES -->]
+
.Example
Eclipse Che hosted by Red Hat: link:https://workspaces.openshift.com#https://github.com/eclipse-che/che-server[].

2. New workspace starting URLs
//THIS IS USEFUL **ONLY** FOR STARTING A NEW WORKSPACE, BUT THE USER SHOULD FULLY EXPLORE THE OPTIONS OF STOPPING AND RESTARTING AN ALREADY CREATED WORKSPACE

//BEFORE TELLING READERS ABOUT THE DEVFILE URL, WE NEED MENTION WHAT A DEVFILE IS AND WHAT IT DOES

//REWRITE THIS PAR, NEEDS MORE WORK:
When you have the Che host URL from your administrator, then for every remote Git repository that you have to work with inside workspaces, you can prepare and save, for example in your browser favorites toolbar or another location which you keep open daily, so that you can simply click on the previously saved link, as opposed to having to put this link together from the "Che host URL" and the repository URL. Keep it somewhere handy.
//HERE WE GET INTO ISSUES WITH NEW WORKSPACE NAMING/STARTING POLICY
//However, the following is applicable only to Projects with Git: TIP: For git repositories with webpages (like GitHub, GitLab, BitBucket?), entering this URL is simple: Copy the Che/CRW URL, open the git repository page in your internet browser, paste your copied Che/CRW URL in the address bar in front of the URL of the git repository page, and type # in between your Che/CRW and the git repository page. Press Enter.
source: proc_uo-starting-a-new-workspace-with-git.adoc



MERGE:
=========================================================================
// the unstated first and second steps appear to be one and the same
//vague sentence:
* Create the workspace by opening(wrong) the factory(dropped)  URL:
+
`pass:c,a,q[{prod-url}/#__<GIT_REPOSITORY_URL>__]`
+
.Create a workspace on Eclipse Che hosted by Red Hat from the default branch of the `https://github.com/eclipse-che/che-server` repository using the short factory URL format.
[subs="+quotes"]
====
link:https://workspaces.openshift.com/#https://github.com/eclipse-che/che-server[]
====
pass:[<!-- vale CheDocs.TechnicalTerms = YES -->]

//it is not clear from the above if entering the same url again later will open or restart the same workspace
=========================================================================
.Procedure
Create the workspace by opening(wrong) the following(wrong:syntax) URL: `pass:c,a,q[{prod-url}/#__<GitHubBranch>__]`

.Example
Use following URL format to open an experimental link:https://github.com/quarkusio/quarkus-quickstarts[quarkus-quickstarts] branch hosted on link:https://workspaces.openshift.com[workspaces.openshift.com].

[subs="+quotes"]
----
https://workspaces.openshift.com/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che
----

================================================================================
.Example

== URL syntax by Git provider

SHORTEN IN SENTENCE LENGTH AND IN THE NUMBER OF SENTENCES USED:

URL syntax for cloning GitHub-hosted repositories to the starting workspace:

* To clone the default branch on GitHub to the starting workspace:
+
`#https://github.com/_<user_or_org>_/_<repository>_`
+
Example: `#https://github.com/eclipse-che/che-plugin-registry`

* To clone a specified branch on GitHub to the starting workspace:
+
`#https://github.com/_<user_or_org>_/_<repository>_/tree/_<branch-name>_`
+
Example: `#https://github.com/eclipse-che/che-plugin-registry/tree/7.39.x`

* To clone the branch of a pull request on GitHub to the starting workspace:
+
`#https://github.com/_<user_or_org>_/_<repository>_/pull/_<pull-request-id>_`
+
Example: `#https://github.com/eclipse-che/che-plugin-registry/pull/1097`

URL syntax for cloning GitLab-hosted repositories:

* To clone the default branch on GitLab to the starting workspace:
+
`#https://gitlab.com/_<user_or_org>_/_<repository>_`

* To clone a specified branch on GitLab to the starting workspace:
+
`#https://gitlab.com/_<user_or_org>_/_<repository>_/-/tree/_<branch>_`
