[id="uo-getting-and-using-the-essential-links_{context}"]
= Getting and using the essential links

When you work {prod-short}, you will be regularly using three kinds of URLs:
* URL of your organization's {prod-short} instance
* URLs for starting a new workspace
* URLs of your workspaces

[TIP]
====
Save each URL to your browser bookmarks:

In Mozilla Firefox, go to *☰* *>* *Bookmarks* *>* *Manager bookmarks Ctrl+Shift+O* *>* *Bookmarks Toolbar* *>* *Organize* *>* *Add bookmark*.

In Google Chrome, go to
*⋮* *>* *Bookmarks* *>* *Bookmark manager* *>* *Bookmarks bar* *>* *⋮* *>* *Add new bookmark*.
====

== URL of your organization's {prod-short} instance

Your {prod-short} administrator must provide you with the URL of your organization's instance of {prod-short} which you need as a user to access the {prod-short} dashboard and start and manage your workspaces. This URL is a fully qualified domain name.
//reuse the last setence(s)
+
[subs="+quotes,+attributes"]
----
https://__<{prod-url}>__#__<Git_repository_URL>__
----
//PROB NEED TO UPDATE THE UPSTREAM VALUE FOR {prod-url} BEFOREHAND
//need to mention that the {prod-short} URL is FQDM?
//`pass:c,a,q[{prod-url}/#__<GIT_REPOSITORY_URL>__]`
//pass:[<!-- vale CheDocs.TechnicalTerms = YES -->]
+
.Example
Eclipse Che hosted by Red Hat: link:https://workspaces.openshift.com#https://github.com/eclipse-che/che-server[].

== URLs for starting a new workspace
//THIS IS USEFUL **ONLY** FOR STARTING A NEW WORKSPACE, BUT THE USER SHOULD FULLY EXPLORE THE OPTIONS OF STOPPING AND RESTARTING AN ALREADY CREATED WORKSPACE

//BEFORE TELLING READERS ABOUT THE DEVFILE URL, WE NEED MENTION WHAT A DEVFILE IS AND WHAT IT DOES

//MENTION THAT THIS URL USES THE URL OF YOUR ORGANIZATION'S {PROD-SHORT} INSTANCE The URL to your organization's instance of {prod-short} is used as part of the new workspace starting URLs and workspace URLs.

//REWRITE THIS PAR, NEEDS MORE WORK:
When you have the Che host URL from your administrator, then for every remote Git repository that you have to work with inside workspaces, you can prepare and save, for example in your browser favorites toolbar or another location which you keep open daily, so that you can simply click on the previously saved link, as opposed to having to put this link together from the "Che host URL" and the repository URL. Keep it somewhere handy.
//HERE WE GET INTO ISSUES WITH NEW WORKSPACE NAMING/STARTING POLICY
//However, the following is applicable only to Projects with Git: TIP: For git repositories with webpages (like GitHub, GitLab, BitBucket?), entering this URL is simple: Copy the Che/CRW URL, open the git repository page in your internet browser, paste your copied Che/CRW URL in the address bar in front of the URL of the git repository page, and type # in between your Che/CRW and the git repository page. Press Enter.
source: proc_uo-starting-a-new-workspace-with-git.adoc

MERGE:
=========================================================================
.Create a workspace on Eclipse Che hosted by Red Hat from the default branch of the `https://github.com/eclipse-che/che-server` repository using the short factory URL format.
[subs="+quotes"]
====
link:https://workspaces.openshift.com/#https://github.com/eclipse-che/che-server[]
====
pass:[<!-- vale CheDocs.TechnicalTerms = YES -->]

//it is not clear from the above if entering the same url again later will open or restart the same workspace
=========================================================================
.Procedure
Create the workspace by opening(wrong) the following(wrong:syntax) URL: `pass:c,a,q[{prod-url}/#__<GitHubBranch>__]`

.Example
Use following URL format to open an experimental link:https://github.com/quarkusio/quarkus-quickstarts[quarkus-quickstarts] branch hosted on link:https://workspaces.openshift.com[workspaces.openshift.com].

[subs="+quotes"]
----
https://workspaces.openshift.com/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che
----

================================================================================
.Example

== URL syntax by Git provider

SHORTEN IN SENTENCE LENGTH AND IN THE NUMBER OF SENTENCES USED:

//REWRITE FOR THIS TOPIC IF NECESSARY: As a user, you can create a workspace containing a clone of a Git repository by entering a custom URL in the address bar of your browser.

//REWRITE STARTS WORKSPACE+CLONES REPO!
URL syntax for cloning a GitHub-hosted repository to a new workspace:

//REWRITE STARTS WORKSPACE+CLONES REPO!
//CONSIDER ADDING PROD-URL!
`#https://github.com/_<user_or_org>_/_<repository>_` clones the default branch on GitHub to the new workspace.
+
Example: `#https://github.com/eclipse-che/che-plugin-registry`

//REWRITE STARTS WORKSPACE+CLONES REPO!
//CONSIDER ADDING PROD-URL!
`#https://github.com/_<user_or_org>_/_<repository>_/tree/_<branch-name>_` clones a specified branch on GitHub to the new workspace.
+
Example: `#https://github.com/eclipse-che/che-plugin-registry/tree/7.39.x`

//REWRITE STARTS WORKSPACE+CLONES REPO!
//CONSIDER ADDING PROD-URL!
`#https://github.com/_<user_or_org>_/_<repository>_/pull/_<pull-request-id>_` clones the branch of a pull request on GitHub to the new workspace.
+
Example: `#https://github.com/eclipse-che/che-plugin-registry/pull/1097`

//REWRITE STARTS WORKSPACE+CLONES REPO!
//CONSIDER ADDING PROD-URL!
URL syntax for cloning a GitLab-hosted repository to a new workspace:

//REWRITE STARTS WORKSPACE+CLONES REPO!
//CONSIDER ADDING PROD-URL!
`#https://gitlab.com/_<user_or_org>_/_<repository>_` clones the default branch on GitLab to the starting workspace.

//REWRITE STARTS WORKSPACE+CLONES REPO!
//CONSIDER ADDING PROD-URL!
`#https://gitlab.com/_<user_or_org>_/_<repository>_/-/tree/_<branch>_` clones a specified branch on GitLab to the starting workspace.

TWO EXAMPLES FROM ELSEWHERE, IF NEEDED. IF NOT, DELETE:
.Example
Creates a workspace on Eclipse Che hosted by Red Hat from the default branch of the `https://github.com/eclipse-che/che-server` repository using the short factory URL format.
[subs="+quotes"]
====
link:https://workspaces.openshift.com/#https://github.com/eclipse-che/che-server[]
====
.Example
Use following URL format to open an experimental link:https://github.com/quarkusio/quarkus-quickstarts[quarkus-quickstarts] branch hosted on link:https://workspaces.openshift.com[workspaces.openshift.com].
[subs="+quotes"]
----
https://workspaces.openshift.com/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che
----


== URLs of your workspaces

workspace limits https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#workspace-limits

//MENTION THAT THIS URL USES THE URL OF YOUR ORGANIZATION'S {PROD-SHORT} INSTANCE The URL to your organization's instance of {prod-short} is used as part of the new workspace starting URLs and workspace URLs.
