[id="starting-a-new-workspace-without-git_{context}"]
= Starting a new workspace (without Git)

//[id="creating-a-workspace-from-a-publicly-accessible-standalone-devfile-using-http_{context}"]
//= Creating a workspace from a publicly accessible standalone devfile using HTTP

////
THIS CREATES AND STARTS THE NEW WORKSPACE
LATER NEED TO DESCRIBE HOW TO:
  REOPEN AFTER (ACCIDENTALLY) CLOSING THE BROWSER TAB/WINDOW
  STOP
  RESTART/REOPEN?
  MODIFY? (DEVFILE?)
  DELETE/REMOVE
NB: other terms used in the equivalent procs in the old docs: execute a (new) workspace, run a (new) workspace.
////
////it is not clear yet or under which conditions: if entering the same url again later opens or restarts the same workspace

////
Alternative procedure that can be mentioned:
In the {prod-short} Dashboard:
.(check the running UI which tab to describe here)
. Enter the url of the remote publicly accessible standalone devfile in the *URL of devfile* field and click *Load devfile*.
more info for inspiration: https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-the-source-code-of-a-project-into-a-workspace/#creating-a-custom-workspace-from-the-dashboard_che
////

Projects that do not use Git use a hosted devfile that is available over HTTPS for configuring new workspaces. As a user, you can start a new workspace by entering a custom URL to the hosted devfile in the address bar of your browser.

MERGE:
* The `devfile.yaml` or `.devfile.yaml` file is available over HTTPS. See xref:authoring-devfiles-version-2.adoc[] for detailed information about creating and using devfiles.

MERGE:
This section describes how to start a {prod-short} workspace using a factory URL. The factory URL is a link pointing {prod-short} to a Git source repository containing a devfile. 

.Prerequisites

* Your administrator maintains a remotely hosted `devfile.yaml` or `.devfile.yaml`.
//HERE LINK TO THE RELEVANT PROCEDURE IN THE ADMIN GUIDE
* The devfile is currently available over HTTPS.

.Procedure

//i'm adding a separate concept module about logging in to {prod-short}

To start a workspace with a clone of a GitHub, GitLab, or Bitbucket repository, go to your browser's address bar and enter your team's or organization's {prod-short} URL, prepended with a `#` character and appended with the repository link. Using the example of Eclipse Che hosted by Red Hat: link:https://workspaces.openshift.com#https://github.com/eclipse-che/che-server[].

//this sentence looks like it belongs in the intro par. consider moving it there and provide a more verification-focused procedure step:
Then {prod-short} starts a workspace and clones the repository `https://github.com/eclipse-che/che-server`.

MERGE:
=========================================================================
// the unstated first and second steps appear to be one and the same
//vague sentence:
* Create the workspace by opening(wrong) the factory(dropped)  URL:
+
`pass:c,a,q[{prod-url}/#__<GIT_REPOSITORY_URL>__]`
+
.Create a workspace on Eclipse Che hosted by Red Hat from the default branch of the `https://github.com/eclipse-che/che-server` repository using the short factory URL format.
[subs="+quotes"]
====
link:https://workspaces.openshift.com/#https://github.com/eclipse-che/che-server[]
====
pass:[<!-- vale CheDocs.TechnicalTerms = YES -->]
=========================================================================
.Procedure
Create the workspace by opening(wrong) the following(wrong:syntax) URL: `pass:c,a,q[{prod-url}/#__<GitHubBranch>__]`

.Example
Use following URL format to open an experimental link:https://github.com/quarkusio/quarkus-quickstarts[quarkus-quickstarts] branch hosted on link:https://workspaces.openshift.com[workspaces.openshift.com].

[subs="+quotes"]
----
https://workspaces.openshift.com/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che
----
=========================================================================
.Prerequisites
* The publicly-accessible standalone `devfile.yaml` file. See xref:authoring-devfiles-version-2.adoc[] for detailed information about creating and using devfiles.

.Procedure
. Execute the workspace by opening the following URL: `pass:c,a,q[{prod-url}/#https://__<yourhosturl>__/devfile.yaml]`

ifeval::["{project-context}" == "che"]
.Example
[subs="+quotes"]
----
https://workspaces.openshift.com/f?url=https://github.com/eclipse/che-docs
----
endif::[]

================================================================================

