[id="restarting-a-workspace_{context}"]
= Restarting a workspace

You may stop your running workspace manually, or it may stop automatically due to reaching an idle timeout limit or a running timeout limit (as set by the administrator of your {prod-short} instance). In some cases, you may need to restart your workspace while it is still running.

To start a stopped workspace or restart a running workspace by using the dashboard:
*Progress* tab
Clicking on the workspace name (re)starts the workspace and opens a new browser tab with a page that shows the page tab with the overview points of the progress of starting the workspace.

////
todo: link to the corresponding sections in the new docs:
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_idle_timeout
&
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_run_timeout
NB: Do not mention the variable names for these limits in the user guide, just provide the necessary links.
////

.Procedure

A
. Go to the {prod-short} dashboard.
. Locate the workspace under *RECENT WORKSPACES*.
. Hover on the workspace name.
. Go to *⋮* *>* *Restart Workspace* or *Start in Background*.

B
If the workspace is stopped, and you enter the workspace link, the workspace will start.
* Go to the workspace URL by clicking a bookmark or by entering the workspace URL in the address bar of your browser.

C
TIP: To open the workspace in a new tab a new tab with the workspace:
//Click the workspace name
. Go to the {prod-short} dashboard.
. Locate the workspace under *RECENT WORKSPACES*.
. Click the workspace name.
