[id="stopping-the-running-workspace_{context}"]
= Stopping the running workspace

//ADD A SENTENCE ABOUT THE STATUS UI ELEMENT OF EACH WORKSPACE UNDER *RECENT WORKSPACES*
//STANDARDIZE ALL OF THESE MENU-INVOLVING PROCEDURES/TIPS AROUND *WORKSPACES* (NOT *RECENT WORKSPACES*)
//RECOMMEND THE USEFULNESS OF THE DASHBOARD FOR WORKSPACE MANAGEMENT AND HEALTH/STATUS MONITORING?

You can stop your running workspace in the {prod-short} dashboard. When you stop a workspace, its state at the moment you stopped it is preserved until you restart it. Stopping a running workspace can be useful when you need to work with the workspace over a number of days. You can start the workspace at the beginning of your workday, stop the workspace at the end of the workday, and restart it the next day or whenever you need to work with it again.

TIP: If you do not stop a running workspace manually in the dashboard, the workspace will stop automatically when it reaches an idle timeout limit or a running timeout limit, which are set by the administrator of your {prod-short} instance. When the workspace stops automatically because of a timeout limit, its latest state is preserved until you restart it.

////
todo: link to the corresponding sections in the new docs:
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_idle_timeout
&
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_run_timeout
NB: Do not mention the variable names for these limits in the user guide, just provide the necessary links.
////

.Procedure

. Go to the {prod-short} dashboard.
. Locate the workspace under *RECENT WORKSPACES*.
. Hover on the workspace name.
. Go to *⋮* *>* *Stop Workspace*.