////it is not clear yet or under which conditions: if entering the same url again later opens or restarts the same workspace

//WHAT ABOUT GIT SERVERS AND LOCAL GITLAB? DOUBLE-CHECK THE CONCEPT SOURCES, ASK SME, AND TEST TO VERIFY

[id="uo-starting-a-new-workspace-with-a-clone-of-a-git-repository_{context}"]
= Starting a new workspace with a clone of a Git repository

//does this mean that this procedure is inapplicable to Git servers and GitLab servers?
//To start a new workspace that contains a clone of a GitHub, GitLab, or Bitbucket repository:
//To start [ADD TO WHAT WHERE?] a new workspace

//the following requires import of git config and possibly also git credentials, how?
//git config in theory can be included in a git repository, however, that would mean importing two git repositories, because the project git repository cannot contain the individual user's git config file and such
{prod-short} allows you to  start a new workspace that contains a clone of a Git repository. You can have your origin or fork cloned into a new starting workspace. Or you can have a common repository of a project cloned into a new starting workspace. With such Git providers as GitHub and GitLab, you can also specify the branch for the new starting workspace to checkout.

NOTE: Advanced users can compose and use their own devfiles, as well as use a local devfile.
//provide links on "compose" and "local devfile" to the corresponding sections in Advanced Use (User Guide). Max

.Prerequisites

* Your administrator maintains the  `devfile.yaml` or `.devfile.yaml` file in the root directory of the Git repository.
* The devfile is currently available over HTTPS.

.Procedure

TIP: For git repositories with webpages (like GitHub, GitLab, BitBucket?), entering this URL is simple: Copy the Che/CRW URL, open the git repository page in your internet browser, paste your copied Che/CRW URL in the address bar in front of the URL of the git repository page, and type # in between your Che/CRW and the git repository page. Press Enter.

//i'm adding a separate concept module about logging in to {prod-short}

. In the login page, authenticate yourself as a {prod-short} user with your username and password, according to the information provided by your {prod-short} administrator.
//here must not say "{prod-short} username and password" or "{prod-short} credentials
//although i'm adding a separate concept module about logging in to {prod-short}, this procedure may require it as a step, in which case i should just xref to the separate module about logging in (for more info); in any case, the logging in happens after the step of entering the URL in the browser's address bar, and then probably before seeing the progress UI; however, THIS MUST BE TESTED WITH THE USER ALREADY LOGGED IN AND HAVING A DASHBOARD OPEN, BUT CHECK IF AUTHENTICATION IS REPOSITORY-SPECIFIC.
+
{prod-short} opens the dashboard and displays the progress of starting the new workspace. {prod-short} clones the Git repository in the background.
//Test and describe what the user is seeing here, enough vague, without unnecessary details which may change later (WORKSPACE STARTING PROGRESS UI >  OPENED WORKSPACE?)

. Enter your username and password in the login page to be redirected to the {prod-short} dashboard. If you are already logged in, the {prod-short} dashboard is loaded without requesting your credentials.
//the first sentence may be entirely redundant and totally confusing (a user who already has a dashboard open would open one more tab with the dashboard, which doesn't make sense) if the second sentence applies.
//{prod-url} this is the URL that is also mentioned in the next step for a different purpose, so it'd be useful to introduce it here or overall for this procedure

. Open the URL of your organization's {prod-short} instance. See PREVIOUS MODULE ON ESSENTIAL URLs.

In this tab, {prod-short} redirects you to a page that displays workspace starting progress.
When the workspace is ready, it loads in the tab. A clone of the Git repository is present in the filesystem of the workspace.


.Additional resources

* LINK TO ADVANCED USE FOR FEATURE BRANCHES THAT THE USER CAN HAVE A CUSTOM DEVFILE FOR
* LINK TO ADVANCED USE FOR LONG-URL SYNTAX AND THE FEATURES IT ENABLES

=================================================================================
//QUESTIONS TO ASK:
1. what happens when i fork a GH/GL repo that contains a devfile and when i use that devfile to create a new workspace for my fork of that repository (assuming this applies both to the default branch like master or main and any feature branch that I have created in my fork
2. in theory, this should also apply to non-authorized users of other {prod-short} clusters cloning the same repo and using the embedded devfile to start their own workspaces, correct?
//the sentence about the devfile doesn't need to be in the prerequisites (it's something that should be set up, so the user shouldn't worry about it), preferably move it elsewhere in the module:
//the heading is currently branch-specific: this needs to change
//actually, i can't use 'create' because the user is not creating anything, {prod-short} creates the workspace for the user, so the gerund procedure cannot have its heading start with 'Creating ...'
//the second reason why i can't use 'create' in the heading (and prob in the module text as well) is that a new workspace is both 'created' and 'started'
//'add a workspace` is another alternative to 'create a workspace': source: https://people.gnome.org/~bmsmith/build/overview-workspaces.html. However, i can't use add because all the relevant UI uses 'Start' everywhere.
//NONE.Prerequisites

//SOMEWHERE IN THIS MODULE MENTION IN SPECIFIC TERMS:
// ✔ 1. THE USER CAN CLONE THE PROJECT'S REPOSITORY OR THE USER'S FORK OF IT
//2. THE USER CAN CLONE THE REPOSITORY FROM THE DEFAULT BRANCH OR FROM A FEATURE BRANCH
//NB: DOUBLE-CHECK (ASK AND TEST) THAT THE WHOLE REPOSITORY, NOT JUST ONE BRANCH, GETS CLONED

// ✔ NO LONGER USING THIS PHRASE DUE TO USE CASE REQUIRING THE USER TO SAVE THE URL SOMEWHERE:in the address bar of your internet browser, enter a custom URL like so:

//. Enter your team's {prod-short} URL in the address bar of your browser.
//this sentence may be entirely redundant and totally confusing (a user who already has a dashboard open would open one more tab with the dashboard, which doesn't make sense)

////
I CAN NO LONGER SAY THIS BECAUSE ENTERING THE LINK IN THE ADDRESS BAR IS NOT THE PREFERRED UX IN THE ACTUAL USE CASE:
To start a workspace with a clone of a GitHub, GitLab, or Bitbucket repository, go to your browser's address bar and enter your team's or organization's {prod-short} URL, prepended with a `#` character and appended with the repository link. Using the example of Eclipse Che hosted by Red Hat: link:https://workspaces.openshift.com#https://github.com/eclipse-che/che-server[].
////

////
//this sentence looks like it belongs in the intro par. consider moving it there and provide a more verification-focused procedure step:
Then {prod-short} starts a workspace and clones the repository `https://github.com/eclipse-che/che-server`.
////