---
title: "Configuring Kubernetes"
keywords: kubernetes, configuration
tags: [installation, kubernetes]
sidebar: che_6_docs
permalink: che-6/kubernetes-config.html
redirect_from: kubernetes-config.html
folder: che-6/setup-kubernetes
---

You can configure the behavior of the Che server by passing environment variables to the Che deployment.

There are multiple ways to edit the Che deployment to add new or edit existing environment variables:

* To open the Che deployment YAML file in text editor, use:
+
----
kubectl edit dc/che
----
+
* To manually edit the Che deployment, in the Kubernetes web console, click *Deployments* -> *Che* -> *Edit*.
* To update the Che deployment with new environment variables or to modify the values of existing ones, use:
+
----
$ kubectl set env dc/che <key>=<value> <key1>=<value1>
----

[id="configurable-che-properties"]
== Configurable Che properties

You can find the deployment environment variables or configuration map in the YAML files. For a complete list of all the properties that are configurable for the Che server, see https://github.com/eclipse/che/tree/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che[Che properties].

To manually convert properties into environment variables, follow the instructions on the link:properties.html#properties-and-environment-variables[properties page].

For more information about critical configuration options, see the link:kubernetes-admin-guide.html[Kubernetes Administration guide].

[id="specifying-the-default-unrecoverable-events"]
== Specifying the default unrecoverable events

By default, if the `Failed Mount`, `Failed Scheduling`, or `Failed to pull image` Kubernetes or OpenShift events occur during a startup, the workspace is immediately terminated before timeout. To change or disable (using a blank value) the default unrecoverable events, use the following environment variable: `CHE_INFRA_KUBERNETES_WORKSPACE_UNRECOVERABLE_EVENTS`.
