---
title: "Configuring Kubernetes"
keywords: kubernetes, configuration
tags: [installation, kubernetes]
sidebar: che_6_docs
permalink: kubernetes-config.html
folder: setup-kubernetes
---

You can configure the behavior of the Che server by passing environment variables to the Che deployment.

There are multiple ways to edit the Che deployment to add new or edit existing environment variables:

* To open the Che deployment YAML file in the nano editor, use the `kubectl edit dc/che` command. The Vim editor is used by default.

* To manually edit the Che deployment, in the Kubernetes web console, click *Deployments* > *Che* > *Edit*.

* To update the Che deployment with new environment variables or to modify the values of existing ones, use the `kubectl set env dc/che KEY=VALUE KEY1=VALUE1` command.

[id="configurable-che-properties"]
== Configurable Che properties

You can find the deployment environment variables or configuration map in the YAML files. For a complete list of all the properties that are configurable for the Che server, see https://github.com/eclipse/che/tree/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che[Che properties].

To manually convert properties into environment variables, follow the instructions on the link:properties.html#properties-and-environment-variables[properties page].

For more information about critical configuration options, see the link:kubernetes-admin-guide.html[Kubernetes Administration guide].

[id="changing-the-unrecoverable-events"]
== Changing the unrecoverable events

By default, if the `Failed Mount`, `Failed Scheduling`, or `Failed to pull image` Kubernetes or OpenShift events occur during a startup, the workspace is immediately terminated before timeout. To change or disable (via a blank value) the default unrecoverable events, use the following environment variable:

`CHE_INFRA_KUBERNETES_WORKSPACE_UNRECOVERABLE_EVENTS`

