:_content-type: PROCEDURE
:description: Deploy {prod-short} on an {orch-name} cluster with no internet access by mirroring the required container images and Operator catalogs to a private registry.
:keywords: install, restricted, air-gapped, disconnected, openshift
:navtitle: Deploy in an air-gapped environment
:page-aliases: installation-guide:installing-che-in-restricted-environment.adoc, installation-guide:installing-che-in-a-restricted-environment.adoc, preparing-a-restricted-environment.adoc, configuring-che-to-run-in-a-restricted-environment.adoc, installing-che-in-a-restricted-environment.adoc

[id="proc_installing-che-in-a-restricted-environment"]
= Deploy in an air-gapped environment

[role="_abstract"]
Deploy {prod-short} on an {orch-name} cluster with no internet access by mirroring the required container images and Operator catalogs to a private registry.

On a restricted network, deploying {prod-short} and running workspaces requires the following public resources:

* Operator catalog
* Container images
* Sample projects

To make these resources available, you can replace them with their copy in a registry accessible by the {orch-name} cluster.

.Prerequisites

include::partial$snip_preparing-images-for-a-restricted-environment.adoc[]

.Procedure

. Download and execute the mirroring script to install a custom Operator catalog and mirror the related images: xref:administration-guide:attachment$restricted-environment/prepare-restricted-environment.sh[prepare-restricted-environment.sh].
+
[source,bash,subs="+attributes,+quotes"]
----
$ bash prepare-restricted-environment.sh \
  --devworkspace_operator_index {devworkspace-operator-index-disconnected-install}\
  --devworkspace_operator_version "v{devworkspace-operator-version-patch}" \
  --prod_operator_index "{prod-operator-index}" \
  --prod_operator_package_name "{prod-operator-package-name}" \
  --prod_operator_bundle_name "{prod-operator-bundle-name}" \
  --prod_operator_version "v{prod-ver-patch}" \
  --my_registry "__<my_registry>__" <1>
----
<1> The private Docker registry where the images will be mirrored

. Install {prod-short} with the configuration set in the `che-operator-cr-patch.yaml` created in step 1:
+
[source,bash,subs="+attributes,+quotes"]
----
$ {prod-cli} server:deploy \
  --platform=openshift \
  --olm-channel stable \
  --catalog-source-name={prod-operator-package-name}-disconnected-install \
  --catalog-source-namespace=openshift-marketplace \
  --skip-devworkspace-operator \
  --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml
----

. Allow incoming traffic from the {prod-short} namespace to all Pods in the user {orch-namespace}s. See: xref:administration-guide:configuring-network-policies.adoc[].

.Verification

* Verify that the {prod-short} instance is running:
+
[source,bash,subs="+attributes,+quotes"]
----
$ {prod-cli} server:status
----

[role="_additional-resources"]
.Additional resources

* link:https://docs.openshift.com/container-platform/{ocp4-ver}/operators/understanding/olm-rh-catalogs.html[Red Hat-provided Operator catalogs]
* link:https://docs.openshift.com/container-platform/{ocp4-ver}/operators/admin/olm-managing-custom-catalogs.html[Managing custom catalogs]
