:_content-type: PROCEDURE
:description: To enable centralized user authentication through an external identity provider, install {prod-short} on {orch-name} with {keycloak} as the OIDC provider.
:keywords: install, openshift, keycloak, oidc, identity provider
:navtitle: Install {prod-short} on OpenShift with {keycloak} as external identity provider
:page-aliases: installing-che-on-openshift-with-keycloak-as-oidc.adoc

[id="proc_installing-che-on-openshift-with-keycloak-as-oidc"]
= Install {prod-short} on OpenShift with {keycloak} as external identity provider

[role="_abstract"]
To enable centralized user authentication through an external identity provider, install {prod-short} on {orch-name} with {keycloak} as the OIDC provider.

include::partial$snip_persona-admin.adoc[]

.Prerequisites

* You have an active `{orch-cli}` session with administrative permissions to the {orch-name} cluster. See {orch-cli-link}.

* You have {keycloak} configured as an external identity provider for {orch-name}. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/external-auth[Enabling direct authentication with an external OIDC identity provider].

.Procedure

. Create a `{prod-id-short}` client in the {keycloak} Admin Console:
+
--
.. Within the realm used for {orch-name} authentication, select *Clients* on the left side of the navigation bar.
.. Select the *Create client* button.
.. On the *General Settings* page:
+
... Enter `{prod-id-short}` in the *Client ID* field.
... Optional: Enter a *Name* and *Description* for the OAuth client.
... Click *Next*.
.. On the *Capability config* page:
+
... Toggle *Client authentication* to *On*.
... Click *Next*.
.. On the *Login settings* page:
+
... Enter `{prod-short}` redirect URL in the *Valid redirect URIs* field.
+
NOTE: Run the following command to obtain the `{prod}` redirect URL:
+
[source,bash,subs="+quotes,+attributes"]
----
echo "$(
  oc whoami --show-console |
  sed 's|console-openshift-console|{prod-id}|g'
)/oauth/callback"
----

... Click *Save*.

.. Navigate to the *Credentials* tab of the newly created client and copy the *Client secret* value for use when applying the OAuth client secret.
--
. Add the `{prod-id-short}` client to the audiences list in the {orch-name} authentication configuration:
+
[source,bash,subs="+quotes,+attributes"]
----
{orch-cli} patch authentication.config/cluster \
  --type='json' \
  -p='[
    {
      "op": "add",
      "path": "/spec/oidcProviders/0/issuer/audiences/-",
      "value": "{prod-id-short}"
    }
  ]'
----
+
[NOTE]
====
If you have multiple OIDC providers configured, adjust the array index in the path (currently `0`)
to match your {keycloak} provider's position in the configuration.
====

. Wait for the `kube-apiserver` cluster Operator to roll out the configuration changes:
+
[source,bash,subs="+quotes,+attributes"]
----
watch {orch-cli} get co kube-apiserver
----

. Create a {orch-namespace} for {prod-short}:
+
[source,bash,subs="+quotes,+attributes"]
----
{orch-cli} create {orch-namespace} {prod-namespace}
----

. Create a Secret for OAuth authentication:
+
[source,yaml,subs="+quotes,+attributes"]
----
{orch-cli} apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: {prod-id-short}-oidc-client-secret
  namespace: {prod-namespace}
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
stringData:
  oAuthSecret: __<client_secret>__ <1>
EOF
----
+
<1> The client secret value from the `{prod-id-short}` client credentials tab in {keycloak}.

. Prepare the `CheCluster` patch:
+
[source,yaml,subs="+quotes,+attributes"]
----
cat > che-patch.yaml <<EOF
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    auth:
      oAuthClientName: {prod-id-short}
      oAuthSecret: {prod-id-short}-oidc-client-secret
      gateway:
        oAuthProxy:
          cookieExpireSeconds: 300
        deployment:
          containers:
            - name: oauth-proxy
              env:
                - name: OAUTH2_PROXY_BACKEND_LOGOUT_URL
                  value: "__<issuer_url>__/protocol/openid-connect/logout?id_token_hint=\{id_token}" <1>
EOF
----
+
<1> The {keycloak} OIDC issuer URL.

. Create the {prod-short} instance with `{prod-cli}`:
+
[source,bash,subs="+attributes"]
----
{prod-cli} server:deploy \
  --platform openshift \
  --che-operator-cr-patch-yaml che-patch.yaml
----

.Verification

. Verify the {prod-short} instance status:
+
[source,bash,subs="+attributes"]
----
{prod-cli} server:status
----

. Navigate to the {prod-short} cluster instance:
+
[source,bash,subs="+attributes"]
----
{prod-cli} dashboard:open
----

. Log in to the {prod-short} instance.

[role="_additional-resources"]
.Additional resources

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp4-ver}/html/authentication_and_authorization/external-auth[Enabling direct authentication with an external OIDC identity provider]
