:_content-type: PROCEDURE
:description: Remove {prod-short} and all related user data from an {orch-name} cluster by using the {prod-cli} management tool.
:keywords: uninstall, remove, delete
:navtitle: Uninstall {prod-short}
:page-aliases: installation-guide:uninstalling-che.adoc, installation-guide:uninstalling-che-after-operatorhub-installation.adoc, uninstalling-che-on-openshift.adoc, installation-guide:uninstalling-che-after-chectl-installation.adoc, uninstalling-che-by-using-chectl.adoc, uninstalling-che.adoc

[id="proc_uninstalling-che"]
= Uninstall {prod-short}

[role="_abstract"]
Remove {prod-short} and all related user data from an {orch-name} cluster by using the `{prod-cli}` management tool.

include::discover:partial$snip_persona-admin.adoc[]

[WARNING]
====
Uninstalling {prod-short} removes all {prod-short}-related user data.
====

.Prerequisites

* You have the `{prod-cli}` management tool installed. See xref:installing-the-chectl-management-tool.adoc[].

.Procedure

. Remove the {prod-short} instance:
+
[source,bash,subs="+attributes,+quotes"]
----
$ {prod-cli} server:delete
----
+
[TIP]
====
The `--delete-namespace` option removes the {prod-short} namespace.

The `--delete-all` option removes the {devworkspace} Operator and the related resources.
====
+
[IMPORTANT]
====
Standard operating procedure (SOP) for removing {devworkspace} Operator manually without `{prod-cli}` is available in the {ocp} link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp4-ver}/html/web_console/web-terminal#removing-devworkspace-operator_uninstalling-web-terminal[official documentation].
====

.Verification

* Verify that the {prod-short} namespace has been removed:
+
[source,bash,subs="+attributes"]
----
{orch-cli} get namespace {prod-namespace}
----
+
The expected output is `NotFound`.

[role="_additional-resources"]
.Additional resources

* xref:installing-the-chectl-management-tool.adoc[]
