

:parent-context-of-openshift-connector-overview: {context}

[id="openshift-connector-overview_{context}"]
= OpenShift Connector overview

:context: openshift-connector-overview

OpenShift Connector, also referred to as Visual Studio Code OpenShift Connector for Red Hat OpenShift, is a plug-in for {prod-short} that provides a method for interacting with Red Hat OpenShift 3 or 4 clusters.

OpenShift Connector makes it possible to create, build, and debug applications in the {prod-short} IDE and then deploy the applications directly to a running OpenShift cluster.

OpenShift Connector is a GUI for the OpenShift Do (`odo`) utility, which aggregates OpenShift CLI (`oc`) commands into compact units. As such, OpenShift Connector helps new developers who do not have OpenShift background with creating applications and running them on the cloud. Instead of using several `oc` commands, the user creates a new component or service by selecting a preconfigured template, such as a Project, an Application, or a Service, and then deploys it as an OpenShift Component to their cluster.

This section provides information about installing, enabling, and basic use of the OpenShift Connector plug-in.

* xref:features-of-openshift-connector.adoc[]

* xref:installing-openshift-connector-in-che.adoc[]

* xref:authenticating-with-openshift-connector-from-che.adoc[]

* xref:creating-components-with-openshift-connector-in-che.adoc[]

* xref:connecting-source-code-from-github-to-a-openshift-component-using-openshift-connector.adoc[]

:context: {parent-context-of-openshift-connector-overview}
