// using-openshift-connector-in-eclipse-che


[id="features-of-openshift-connector_{context}"]
= Features of OpenShift Connector

The OpenShift Connector plug-in enables the user create, deploy, and push OpenShift Components to an OpenShift Cluster in a GUI.

When used in {prod-short}, the OpenShift Connector GUI provides the following benefits to its users:

.Cluster management
* Logging in to clusters using tokens and username and password combinations.
* Switching contexts between different `.kube/config` entries directly from the extension view.
* Viewing and managing OpenShift resources as build and deployment. configurations from the *Explorer* view.

.Development
* Connecting to a local or hosted OpenShift cluster directly from {prod-short}.
* Quickly updating the cluster with your changes.
* Creating Components, Services, and Routes on the connected cluster.
* Adding storage directly to a component from the extension itself.

.Deployment
* Deploying to OpenShift clusters with a single click directly from {prod-short}.
* Navigating to the multiple Routes, created to access the deployed application.
* Deploying multiple interlinked Components and Services directly on the cluster.
* Pushing and watching component changes from the {prod-short} IDE.
* Streaming logs directly on the integrated terminal view of {prod-short}.

.Monitoring
* Working with OpenShift resources directly from the {prod-short} IDE.
* Starting and resuming build and deployment configurations.
* Viewing and following logs for deployments, pods, and containers.
