// using-openshift-connector-in-eclipse-che



[id="creating-components-with-openshift-connector-in-{prod-id-short}_{context}"]
= Creating Components with OpenShift Connector in {prod-short}

In the context of OpenShift, Components and Services are basic structures that need to be stored in Application, which is a part of the OpenShift project that organizes deployable assets into virtual folders for better readability.

This chapter describes how to create OpenShift Components in the {prod-short} using the OpenShift Connector plug-in and push them to an OpenShift cluster.

.Prerequisites

* A running instance of {prod-short}.
* The user is logged in to an OpenShift cluster using the OpenShift Connector plug-in.

.Procedure

. In the OpenShift Connector panel, right-click the row with the red OpenShift icon and select *New Project*.
. Enter a name for your project.
. Right-click the created project and select *New Component*.

. When prompted, enter the name for a new OpenShift Application in which the component can be stored.
+
The following options of source for your component are displayed:
+
.. *Git Repository*
+
This prompts you to specify a Git repository URL and select the intended revision of the runtime.
.. *Binary File*
+
This prompts you to select a file from the file explorer.
.. *Workspace Directory*
+
This prompts you to select a folder from the file explorer.

. Enter the name for the component.
. Select the component type.
+
// this is the runtime - which is a middleware used for running a source code
. Select the component type version.
+
//runtime version
. The component is created. Right-click the component, select *New URL*, and enter a name of your choice.
+
//creates a route with the given name in openshift
. The component is ready to be pushed to the OpenShift cluster. To do so, right-click the component and select *Push*.
+
The component is deployed to the cluster. Use a right-click for selecting additional actions, such as debugging and opening in a browser, which requires the exposure of the port `8080`.
