// using-openshift-connector-in-eclipse-che



[id="connecting-source-code-from-github-to-a-openshift-component-using-openshift-connector_{context}"]
= Connecting source code from GitHub to an OpenShift Component using OpenShift Connector

When the user has a Git-stored source code that is wanted for further development, it is more efficient to deploy it directly from the Git repository into the OpenShift Connector Component.

This chapter describes how to obtain the content from the Git repository and connect it with a {prod-short}-developed OpenShift Component.

.Prerequisites
* Have a running  {prod-short} workspace.
* Be logged in to the OpenShift cluster using the OpenShift Connector.

.Procedure

To make changes to your GitHub component, clone the repository into {prod-short} to obtain this source code:

. In the {prod-short} main screen, open the *Command Palette* by pressing kbd:[F1].
. Type the `Git Clone` command in the *Command Palette* and press kbd:[Enter].
. Provide the GitHub URL and select the destination for the deployment.
. Add source-code files to your Project using the btn:[Add to workspace] button.

