// using-openshift-connector-in-eclipse-che

[id="authenticating-with-openshift-connector-from-{prod-id-short}_{context}"]
= Authenticating with OpenShift Connector from {prod-short} when the OpenShift OAuth service does not authenticate the {prod-short} instance

This section describes how to authenticate with an OpenShift cluster when the OpenShift OAuth service does not authenticate the {prod-short} instance. It enables the user to develop and push Components from {prod-short} to the OpenShift instance that contains {prod-short}.

[NOTE]
====
When the OpenShift OAuth service authenticates the {prod-short} instance, the OpenShift Connector plug-in automatically establishes the authentication with the OpenShift instance containing {prod-short}.
====

OpenShift Connector offers the following methods for logging in to the OpenShift Cluster from the {prod-short} instance:

* Using the notification asking to log in to the OpenShift instance containing {prod-short}.
* Using the btn:[Log in to the cluster] button.
* Using the Command Palette.

[NOTE]
====
OpenShift Connector plug-in requires manual connecting to the target cluster.

The OpenShift Connector plug-in logs in to the cluster as `inClusterUser`. If this user does not have manage project permission, this error message appears when creating a project using OpenShift Application Explorer:

[quote]
____
Failed to create Project with error 'Error: Command failed: "/tmp/vscode-unpacked/redhat.vscode-openshift -connector.latest.qvkozqtkba.openshift-connector-0.1.4-523.vsix/extension/out/tools/linux/odo" project create test-project ✗ projectrequests.project.openshift.io is forbidden
____

To work around this issue:

. Log out from the local cluster.
. Log in to OpenShift cluster using the OpenShift user's credentials.
====

include::example$snip_{project-context}-authenticating-with-openshift-connector-from-a-local-instance.adoc[]


.Prerequisites

* A running instance of {prod-short}.

* A {prod-short} workspace is available.

* The OpenShift Connector plug-in is available. See xref:installing-openshift-connector-in-che.adoc[].

* The OpenShift OAuth provider is available only for the auto-login to the OpenShift instance containing {prod-short}. 

.Procedure

. In the left panel, click the *OpenShift Application Explorer* icon.

. In the OpenShift Connector panel, log in using the OpenShift Application Explorer. Use one of the following methods:
** Click the btn:[Log in to cluster] button in the top left corner of the pane.
** Press kbd:[F1] to open the Command Palette, or navigate to *View > Find Command* in the top menu.
+
Search for *OpenShift: Log in to cluster* and press kbd:[Enter].
. If a *You are already logged in a cluster.* message appears, click *Yes*.

. Select the method to log in to the cluster: *Credentials* or *Token*, and follow the login instructions.
+
NOTE: To authenticate with a token, the required token information is in the upper right corner of the main {ocp} screen, under *__<User name>__ > Copy Login Command*.
