

:parent-context-of-backup-and-disaster-recovery: {context}

[id="backup-and-disaster-recovery_{context}"]
= Backup and disaster recovery

:context: backup-and-disaster-recovery


{prod} Operator can create backups of {prod-short} instances and restore them from a backup snapshot if needed. The following chapter describes ways of preparing such backups and their use in the follow-up recovery phase:

* xref:managing-backups-using-cli.adoc[]
* xref:managing-backups-using-custom-resources.adoc[]


[CAUTION]
====
* The standard backup mechanism of {prod-short} does not back up the content of users' workspaces. To preserve local changes, see xref:persistent-volumes-backups.adoc[].

* Backup snapshots are bound to their own specific cluster and must be used only there.
====

{prod} Operator creates a new backup on every {prod-short} update.
Depending on the xref:define-backup-server-for-operator.adoc[configuration], backups before {prod-short} update are stored in:

* The only configured backup server
* Backup server which configuration marked with `che.eclipse.org/backup-before-update: true` annotation if there is more than one configuration
* Internal backup server if no backup servers configured or configured several and `che.eclipse.org/backup-before-update: true` annotation missing

.Additional resources


* xref:external-database-setup.adoc[]

:context: {parent-context-of-backup-and-disaster-recovery}
