:parent-context-of-restoring-a-{prod-id-short}-instance-from-a-backup: {context}

[id="restoring-a-{prod-id-short}-instance-from-a-backup_{context}"]
= Restoring a {prod-short} instance from a backup

:context: restoring-a-{prod-id-short}-instance-from-a-backup

You can xref:managing-backups-of-che-instances-using-custom-resources.adoc#creating-a-backup-of-a-che-instance-using-a-checlusterbackup-object_{context}[create] and xref:managing-backups-of-che-instances-using-custom-resources.adoc#restoring-a-che-instance-from-a-backup-using-a-checlusterrestore-object_{context}[restore] backups of {prod-short} instances using custom resources. To manage backups using custom resources, you must have a xref:backup-server-setup.adoc[configured backup server] and {prod-short} xref:managing-backups-of-che-instances-using-custom-resources.adoc#configuring-prod-short-to-use-a-backup-server_{context}[configured to use the backup server].

Alternatively, you can manage backups of {prod-short} instances xref:managing-backups-of-che-instances-using-prod-cli.adoc[using {prod-cli}].

include::partial$proc_restoring-a-che-instance-from-a-backup-using-the-checlusterrestore-object.adoc[leveloffset=+1]

include::partial$assembly_restoring-a-che-instance-from-a-backup-using-prod-cli.adoc[leveloffset=+1]

:context: {parent-context-of-restoring-a-{prod-id-short}-instance-from-a-backup}