

:parent-context-of-using-a-visual-studio-code-extension-in-che: {context}

[id="using-a-visual-studio-code-extension-in-{prod-id-short}_{context}"]
= Using a Visual Studio Code extension in {prod-short}

:context: using-a-visual-studio-code-extension-in-{prod-id-short}

Starting with {prod} {prod-ver}, Visual Studio Code (VS Code) extensions can be installed to extend the functionality of a {prod-short} workspace. VS Code extensions can run in the Che-Theia editor container, or they can be packaged in their own isolated and pre-configured containers with their prerequisites.

This document describes:

* Use of a VS Code extension in {prod-short} with workspaces.
* {prod-short} Plug-ins panel.
* How to publish a VS Code extension in the {prod-short} plug-in registry (to share the extension with other {prod-short} users).
+
** The extension-hosting sidecar container and the use of the extension in a devfile are optional for this.
** How to review the compatibility of the VS Code extensions to be informed whether a specific API is supported or has not been implemented yet.

include::partial$assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc[leveloffset=+1]

include::partial$assembly_adding-che-plug-in-registry-vs-code-extension-to-a-workspace.adoc[leveloffset=+1]

:context: {parent-context-of-using-a-visual-studio-code-extension-in-che}
