

:parent-context-of-removing-user-data: {context}

[id="removing-user-data_{context}"]
= Removing user data

:context: removing-user-data

== Removing user data according to GDPR

The General Data Protection Regulation (GDPR) law enforces the right for individuals to have personal data erased.

The following procedure describes how to remove a user’s data from a cluster and the Keycloak database.

.Prerequisites

* A user or an administrator authorization token. If a user wants to delete any other data except the data bound to their user account, the `admin` privileges are required.
The `admin` is a  special Che administrator account pre-created and enabled using the `CHE_SYSTEM_ADMIN__NAME / CHE_SYSTEM_SUPER__PRIVILEGED__MODE = true` Custom Resource definition .
+
----
spec:
 server:
   customCheProperties:
     CHE_SYSTEM_SUPER__PRIVILEGED__MODE: 'true'
     CHE_SYSTEM_ADMIN__NAME: '<admin_name>'
----
+
If needed, use commands below for creating an `admin` user:
+
[subs="+quotes,attributes"]
----
$ oc patch checluster eclipse-che --type merge  -p '{ "spec": { "server": {"customCheProperties": {"CHE_SYSTEM_SUPER__PRIVILEGED__MODE": "true"} } }}'  -n {prod-namespace}
----
+
[subs="+quotes,attributes"]
----
$ oc patch checluster eclipse-che --type merge  -p '{ "spec": { "server": {"customCheProperties": {"CHE_SYSTEM_ADMIN__NAME": "<admin_name>"} } }}'  -n {prod-namespace}
----
+
[NOTE]
====
All system permissions are granted to the administrative user who is configured in the `CHE_SYSTEM_ADMIN__NAME` property (the default is `admin`). The system permissions are granted when the {prod-short} server starts. If the user is not present in the {prod-short} user database, it happens after the first user’s login.

.Authorization token privileges:

* `admin` - Can delete all personal data of all users
* `user` - Can delete only the data related to the user
====

* A user or an administrator is logged in the OpenSift cluster with deployed {prod-short}.

* A user ID is obtained. Get the user ID using the commands below:

** For the current user:
+
[subs="+quotes,attributes"]
----
 $ curl -X GET 'http(s)://{prod-host}/api/user'
----
 
 
** To find a user by name: 
+
[subs="+quotes,attributes"]
----
$ curl -X GET 'http(s)://{prod-host}/api/user/find?name=__<username>__'
----
 
** To find a user by email: 
+
[subs="+quotes,attributes"]
----
$ curl -X GET 'http(s)://{prod-host}/api/user/find?email=__<email>__'
----

.Example of obtaining a user ID

This example uses `vparfono` as a local user name.

====
[subs="+quotes,attributes"]
----
$ curl -X GET --header 'Accept: application/json' --header 'Authorization: token 'https://che-vp-che.apps.che-dev.x6e0.p1.openshiftapps.com/api/user/find?name=vparfono'
----

The user ID is at the bottom of the curl command output.

----
{
 "name": "vparfono",
 "links": [
   {
.
.
.
   }
 ],
 "email": "vitaly.parfonov@gmail.com",
 "id": "921b6f33-2657-407e-93a6-fb14cf2329ce"
}
----
====

.Procedure

. Update the `customresourceCR` file to permit the removal of a user’s data from the Keycloak database:
+
[subs="+quotes,attributes"]
----
$ oc patch checluster/{prod-checluster} --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED\": \"true\"}}}}" --type=merge -n {prod-namespace}
----

. Remove the data using the API:
+
[subs="+quotes,attributes"]
----
$ curl -X DELETE `http(s)://{prod-host}/api/user/__<user-id>__`
----


.Verification

The execution of the `curl -X DELETE `http(s)://{prod-host}/api/user/__<user-id>__` command, ` returns the code 204 as a API response.


.Additional resources
To remove the data of all the users, follow the instructions for xref:installation-guide:uninstalling-che.adoc[].


:context: {parent-context-of-removing-user-data}
