

:parent-context-of-backup-and-disaster-recovery: {context}

[id="backup-and-disaster-recovery_{context}"]
= Backup and disaster recovery

:context: backup-and-disaster-recovery


{prod} Operator can create backups of {prod-short} instances and restore them from a backup snapshot if needed. The following chapter describes ways of preparing such backups and their use in the follow-up recovery phase:

* xref:managing-backups-using-cli.adoc[]
* xref:managing-backups-using-custom-resources.adoc[]


[CAUTION]
====
* The standard backup mechanism of {prod-short} does not back up the content of users' workspaces. To preserve local changes, see xref:persistent-volumes-backups.adoc[].

* Backup snapshots are bound to their own specific cluster and must be used only there.
====

{prod} Operator creates a new backup on every {prod-short} update.
If a backup server is xref:define-backup-server-for-operator.adoc[configured], then it is used to store the backup.
If no backup server configured, then internal backup server is used.
If there is more than one backup server configured, the server with `che.eclipse.org/backup-before-update: true` annotation is used.
If none have the annotation, then internal backup server is used.

.Additional resources


* xref:external-database-setup.adoc[]

:context: {parent-context-of-backup-and-disaster-recovery}
