:parent-context-of-enabling-readiness-init-containers: {context}

[id="assembly_enabling-readiness-init-containers_{context}"]
= Enabling and disabling readiness init containers

:context: enabling-and-disabling-readiness-init-containers-for-operator-installer

{prod-short} Operator installs {prod-short} and starts its containers in the right order.
If a node with {prod-short} is restarted and all {prod-short} containers start simultaneously, some containers may fail because some other component they depend on is not ready.
To avoid such failures, readiness init containers queue the containers for {prod-short} components to start in the right order.

Readiness init containers are not enabled by default.

You can enable or disable readiness init containers for {prod-short} installed using the Operator installer.

You can enable and disable readiness init containers for {prod-short} installed using the Operator Lifecycle Manager (OLM) installer.

include::partial$proc_enabling-readiness-init-containers-for-operator-installer.adoc[leveloffset=+1]
include::partial$proc_disabling-readiness-init-containers-for-operator-installer.adoc[leveloffset=+1]

include::partial$proc_enabling-readiness-init-containers-for-olm-installer.adoc[leveloffset=+1]
include::partial$proc_disabling-readiness-init-containers-for-olm-installer.adoc[leveloffset=+1]

:context: {arent-context-of-enabling-startup-init-containers}
