:parent-context-of-configuring-server-logging: {context}

[id="configuring-sever-logging_{context}"]
= Configuring server logging

:context: configuring-server-logging

It is possible to fine tune the log levels of individual loggers available in the {prod-short} server.

The log level of the whole {prod-short} server is configured globally using the xref:installation-guide:configuring-the-che-installation.adoc#checluster-custom-resources-fields-reference_configuring-the-che-installation[`cheLogLevel` configuration property] of the Operator.
To set the global log level in installations not managed by the Operator, the `CHE_LOG_LEVEL` environment variable specified in the `che`
ConfigMap might be used for the same purpose.

It is possible to configure the log levels of the individual loggers in the {prod-short} server using the `CHE_LOGGER_CONFIG` environment
variable.

include::partial$proc_configuring-server-logging.adoc[leveloffset=+1]

include::partial$con_logger-naming.adoc[leveloffset=+1]

include::partial$con_logging-http-traffic.adoc[leveloffset=+1]
