:parent-context-of-assembly_enabling-readiness-init-containers: {context}

[id="assembly_enabling-readiness-init-containers_{context}"]
= Enabling readiness init containers

:context: assembly_enabling-startup-init-containers

{prod-short} Operator installs {prod-short} and starts its containers in the right order. However, suppose a node with {prod-short} gets restarted. In that case, all {prod-short} containers start simultaneously, causing some containers to fail because of the dependent component that might not be ready yet. To handle such a case,  enable readiness init containers for {prod-short} components.

To troubleshoot this situation, enable readiness init containers by following the procedure that matches the used installation method:

* xref:enabling-readiness-init-containers.adoc#enabling-readiness-init-containers-for-operator-installer_{context}[]
* xref:enabling-readiness-init-containers.adoc#enabling-readiness-init-containers-for-olm-installer_{context}[]

include::partial$proc_enabling-readiness-init-containers-for-operator-installer.adoc[leveloffset=+1]
include::partial$proc_enabling-readiness-init-containers-for-olm-installer.adoc[leveloffset=+1]

:context: {arent-context-of-assembly_enabling-startup-init-containers}
