[id="managing-backups-using-custom-resources_{context}"]
= Managing backups using custom resources

This section describes how to create backups of {prod-short} installation and recover directly using Custom Resource objects.

.Prerequisites

* xref:setup-backup-server.adoc[A backup server is set up].

* xref:define-backup-server-for-operator.adoc[{prod-short} Operator is configured to use the backup server].

include::partial$snip_internal-backup-server-warning.adoc[]

.Procedure

 * xref:operator-creating-a-new-backup[]
 * xref:operator-restoring-from-a-backup[]

[id="operator-creating-a-new-backup"]
== Creating a new backup

. Create a `CheClusterBackup` backup object to create a new backup:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-short}-backup
spec:
  backupServerConfigRef: backup-server-configuration <1>
----
+
<1> Name of the `CheBackupServerConfiguration` object defining what backup server to use.

NOTE: To reusing the name of an existing backup object for a new backup object, delete the old object:
+
[subs="+attributes,+quotes"]
----
{orch-cli} delete CheClusterBackup _<name>_ -n {prod-namespace}
----

.Alternative

To use the internal backup server, request automatic configuration from {prod-short} Operator. The preparation described above is not required.

* Configure the automatic setup and sending of the backup to the internal backup server:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-short}-backup
spec:
  useInternalBackupServer: true
----

[id="operator-restoring-from-a-backup"]
== Restoring from a backup

. Create a new object of `CheClusterRestore` to recover a {prod-short} installation from a backup:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterRestore
metadata:
  name: {prod-short}-restore
spec:
  backupServerConfigRef: backup-server-configuration <1>
  snapshotId: ba92c7e0                               <2>
----

<1> Name of the `CheBackupServerConfiguration` object that defines what backup server to use.
<2> Optional parameter defining the Snapshot ID to restore from. The default value is the last snapshot on the backup server.

. Create a new `CheClusterRestore` object to request a new recovery.

* Before reusing the same name for a new backup object, delete the old object first:
+
[subs="+attributes,+quotes"]
----
{orch-cli} delete CheClusterBackup _<name>_ -n {prod-namespace}
----

. Wait until the recovery process finishes.
+
In a case of errors occurrences in your browser after the recovery, clean up the browser data for the {prod-short} domain.

[NOTE]
====
Editing of `CheClusterRestore` objects has no effect.
====

.Verification

. Verify backup process state:

.. Read the `status` section of the `CheClusterBackup` object to check the backup process:
+
[source,yaml,subs="+attributes"]
----
status:
  message: 'Backup is in progress. Start time: <timestamp>' <1>
  stage: Collecting {prod-short} installation data          <2>
  state: InProgress                                         <3>
  snapshotId: ba92c7e0                                      <4>
----
<1> Displays the overall state or error message.
<2> Current phase of the backup process in a human-readable format.
<3> Backup process state. One of `InProgress`, `Succeeded`, or `Failed`.
<4> ID of the created backup snapshot. The field appears only when `state` is `Succeeded`.

. Verify recovery process state

.. Read the `status` section of the `CheClusterRestore` object to check the recovery process:
+
[source,yaml,subs="+attributes"]
----
status:
  message: 'Restore is in progress. Start time: <timestamp>' <1>
  stage: Restoring {prod-short} related cluster objects      <2>
  state: InProgress                                          <3>
----
<1> Overall state or error message.
<2> Current phase of the recovery process in a human-readable format.
<3> Recovery process state. One of `InProgress`, `Succeeded`, or `Failed`.
