
// securing-che


:parent-context-of-authenticating-users: {context}

[id="authenticating-users_{context}"]
= Authenticating users

:context: authenticating-users

This document covers all aspects of user authentication in {prod}, both on the {prod-short} server and in workspaces. This includes securing all REST API endpoints, WebSocket or JSON RPC connections, and some web resources.

All authentication types use the link:https://jwt.io/introduction/[JWT open standard] as a container for transferring user identity information. In addition, {prod-short} server authentication is based on the link:https://openid.net/connect/[OpenID Connect] protocol implementation, which is provided by default by {identity-provider-url}[{identity-provider}].

Authentication in workspaces implies the issuance of self-signed per-workspace JWT tokens and their verification on a dedicated service based on link:https://github.com/eclipse/che-jwtproxy/[JWTProxy].

ifeval::["{project-context}" == "che"]
include::partial$con_authentication-modes.adoc[leveloffset=+1]
endif::[]

include::partial$assembly_authenticating-to-the-che-server.adoc[leveloffset=+1]

include::partial$assembly_authenticating-in-a-che-workspace.adoc[leveloffset=+1]

:context: {parent-context-of-authenticating-users}
