:parent-context-of-assembly_enabling-readiness-init-containers: {context}

[id="assembly_enabling-readiness-init-containers_{context}"]
= Enabling readiness init containers

:context: assembly_enabling-startup-init-containers

{prod-short} Operator installs {prod-short} and starts its containers in the right order. If a node with {prod-short} is restarted and all {prod-short} containers start simultaneously, some containers may fail because some other component they depend on is not ready. To avoid such failures, queue init containers queue the containers for {prod-short} components to start in the right order.

Queue init containers are not enabled by default. You can enable and disable them according to the installation method used to install {prod-short}:

* xref:enabling-readiness-init-containers.adoc#enabling-readiness-init-containers-for-operator-installer_{context}[]
* xref:enabling-readiness-init-containers.adoc#enabling-readiness-init-containers-for-olm-installer_{context}[]

include::partial$proc_enabling-readiness-init-containers-for-operator-installer.adoc[leveloffset=+1]
include::partial$proc_enabling-readiness-init-containers-for-olm-installer.adoc[leveloffset=+1]

:context: {arent-context-of-assembly_enabling-startup-init-containers}
