[id="supported-restic-compatible-backup-servers_{context}"]
= Supported restic-compatible backup servers

In a production environment, {prod-short} uses {prod-short} Operator and restic for backing up and restoring {prod-short} instances from backup snapshots on a configured external backup server. To back up, {prod-short} Operator gathers the data needed for a backup snapshot, and then restic creates and manages the snapshot. To restore, restic retrieves and decrypts the snapshot, and then {prod-short} Operator applies the retrieved data to perform the recovery.

{prod-short} can use the following external backup servers that are compatible with restic:

SFTP:: See link:https://access.redhat.com/solutions/2399571[How to configure an SFTP server] and link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp[Restic Docs on SFTP].
ifeval::["{project-context}" == "che"]
Also see link:https://www.manpagez.com/man/8/sftp-server/[SFTP man page].
endif::[]

Amazon S3:: See link:https://docs.aws.amazon.com/s3/index.html[Amazon S3 Documentation] and link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3[Restic docs on Amazon S3].

REST:: See link:https://github.com/restic/rest-server[Rest Server] and link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#rest-server[Restic docs on Rest Server].

For testing the backing up and restoring of {prod-short} instances in a non-production environment, {prod-short} offers the xref:backups-of-che-instances-to-the-internal-backup-server.adoc[internal backup server].

.Additional resources
* link:https://restic.readthedocs.io/en/latest/[restic.readthedocs.io]
* link:https://restic.net/[restic.net]
