// {prod-id-short}-compute-resources-requirements

[id="controller-requirements_{context}"]
= Controller requirements

The Workspace Controller consists of a set of five services running in five distinct containers. The following table presents the default resource requirements of each of these services.

[cols="2,2,1,1", options="header"]
.ControllerServices
|===
|Pod
|Container name
|Default memory limit
|Default memory request

|{prod-short} Server and Dashboard
|che
|1 GiB
|512 MiB

|PostgreSQL
|`postgres`
|1 GiB
|512 MiB

|{identity-provider}
|`{identity-provider-id}`
|2 GiB
|512 MiB

|Devfile registry
|`che-devfile-registry`
|256 MiB
|16 MiB

|Plug-in registry
|`che-plugin-registry`
|256 MiB
|16 MiB
|===

These default values are sufficient when the {prod-short} Workspace Controller manages a small amount of {prod-short} workspaces. For larger deployments, increase the memory limit. See the xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc[] article for instructions on how to override the default requests and limits. For example, the Eclipse Che hosted by Red Hat that runs on link:https://workspaces.openshift.com[] uses 1 GB of memory.

.Additional resources

* xref:administration-guide:server-components-with-che-server.adoc[].
