[id="restic-compatible-backup-servers_{context}"]
= Restic-compatible backup servers

{prod-short} uses Che Operator and restic for backing up and restoring {prod-short} instances from backup snapshots. To back up, Che Operator gathers the data needed for a backup snapshot, and then restic creates and manages the snapshot. To restore, restic retrieves and decrypts the snapshot, and then Che Operator applies the retrieved data to perform the recovery.

{prod-short} can use the following backup servers that are compatible with restic:

REST:: See link:https://github.com/restic/rest-server[Rest Server] and link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#rest-server[Restic docs on Rest Server].

Amazon S3:: See link:https://docs.aws.amazon.com/s3/index.html[Amazon S3 Documentation] and link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3[Restic docs on Amazon S3].

SFTP:: See link:https://access.redhat.com/solutions/2399571[How to configure an SFTP server] and link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp[Restic Docs on SFTP].
ifeval::["{project-context}" == "che"]
Also see link:https://www.manpagez.com/man/8/sftp-server/[SFTP man page].
endif::[]

.Additional resources
* link:https://restic.readthedocs.io/en/latest/[restic.readthedocs.io]
* link:https://restic.net/[restic.net]