[id="supported-restic-compatible-backup-servers_{context}"]
= Supported Restic-compatible backup servers

{prod-short} uses the {prod-short} Operator and integrated Restic to back up and restore {prod-short} instances from backup snapshots on a configured backup server. The {prod-short} Operator automates the creation of a Restic backup repository on the backup server. To back up data, the {prod-short} Operator gathers the data required for a backup snapshot and uses Restic to create and manage the snapshot. To restore data, the {prod-short} Operator uses Restic to retrieve and decrypt the snapshot, and then the {prod-short} Operator applies the retrieved data to perform the recovery.

{prod-short} can use the following backup servers that are compatible with the integrated Restic:

SFTP:: See the documentation for the SFTP server solution you plan to use (link:https://www.openssh.com/[OpenSSH] or a derived commercial product) and the link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#sftp[Restic Docs on SFTP].

Amazon S3:: See the documentation for link:https://docs.aws.amazon.com/s3/index.html[Amazon S3] (or the chosen S3 API compatible storage) and the link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#amazon-s3[Restic Docs on Amazon S3].

REST:: See the README for link:https://github.com/restic/rest-server[Rest Server] and the link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#rest-server[Restic Docs on Rest Server].

For testing the backing up and restoring of {prod-short} instances, {prod-short} offers the xref:backing-up-of-che-instances-to-the-internal-backup-server.adoc[internal backup server].

.Additional resources
* link:https://restic.readthedocs.io/en/latest/[Restic Documentation]
* link:https://restic.net/[restic · Backups done right!]
* https://www.openssh.com/[OpenSSH.com]
* link:https://access.redhat.com/solutions/2399571[How to configure an sftp server with restricted chroot users with ssh keys]