// authenticating-users

[id="authentication-modes_{context}"]
= Authentication modes

{prod-short} supports multiuser and single-user mode.
 
.Single-user mode

Single-user mode requires no authentication and anyone can access all cluster resources. In single-user mode, the server performs all operations as the predefined user, regardless of who accesses the server. Therefore, this mode is suitable only for use in a private instance for testing product possibilities and configurations.
 
* H2 database is used. 
 
{prod-short} deployed in single-user mode has no authentication and anyone who can access the URL of the {prod-short} deployment sees all workspaces and owns all resources. Because the deployment in this mode requires fewer containers, RAM and CPU requirements are lower. This mode is useful when the whole {prod-short} deployment is used by a single person or for lowering resources used. As the server does not authenticate, actions of multiple users logged in the same workspace can interfere with each other.
 
Use third-party services, such as HAproxy or NGINX, to secure {prod-short} in single-user mode.

.Multiuser mode

Multiuser mode is the default mode for {prod-short}. It requires user authentication and offers isolated workspaces and their resources. In multiuser mode, workspaces are used in the scope of registered users and workspace definitions, and devfiles of particular workspaces can be shared and reused between many users.
 
* {identity-provider} is used to authenticate users.
* PostgreSQL database is used. 


["changing-the-authentication-mode_{context}"]
== Changing the authentication mode
 
This procedure describes how to change authentication mode for various deployment types.

.Procedure

{prod-short} deployed using the {prod-short} Operator defaults to multiuser mode. To change to sing-user mode:

. Update the `CheCluster` Custom Resource (CR) to set the `CHE_MULTIUSER` property to `false`:
+
[source, yaml]
----
spec:
 server:
   customCheProperties:
      CHE_MULTIUSER: "false"
----

{prod-short} deployed using the Helm installer defaults to single-user mode. To change to multiuser mode:

. Set the `multiuser` Helm chart field to `true`:
+
[subs="+quotes,+attributes"]
----
$ helm upgrade --install che --force --namespace che --set global.cheDomain=__<{prod-host}>__  -f multi-user.yaml
----

{prod-short} deployed using the `{prod-cli}` command-line tool defaults to single-user mode. To change to multiuser mode:

. Use the `--multiuser` (`-m`) option with the `{prod-cli} server:start` command:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start --platfrom=minikube --installer=helm --multiuser
----

