[id="external-postgresql-setup_{context}"]
= External PostgreSQL setup

The PostgreSQL database is used by the {prod-short} server for persisting data about the state of {prod-short}. It contains information about user accounts, workspaces, preferences, and other details.

By default, the {prod-short} Operator creates and manages the database deployment.

However, the {prod-short} Operator does not support full life-cycle capabilities such as backups and recovery.

For a business-critical setup, configure an external PostgreSQL database with the following recommended disaster-recovery options:

* High Availability (HA)
* Point In Time Recovery (PITR)

Configure the external PostgreSQL instance on-premises or use a cloud service such as Amazon Relational Database Service (Amazon RDS). Amazon RDS enables deployment of production databases in a Multi-Availability Zone configuration for a resilient disaster recovery strategy with daily and on-demand snapshots.

The recommended configuration of an example database:

[options="header"]
|===
|Parameter | Value
|Instance class | db.t2.small
|vCPU | 1
|RAM | 2 GB
|Multi-az | true, 2 replicas
|Engine version | 9.6.11
|TLS | enabled
|Automated backups | enabled (30 days)
|===

To make workspace metadata and user information persistent, you must:
* xref:[Configure the external PostgreSQL.]
* xref:[Configure {prod-short} to work with the configured external PostgreSQL.]

.Additional resources

* link:https://postgresql.org/docs/current/[PostgreSQL Documentation]
* link:https://postgresql.org/docs/current/backup.html[PostgreSQL Documentation - Backup and Restore]
* link:https://aws.amazon.com/rds/[Amazon RDS]