[id="{prod-id-short}-architecture-overview_{context}"]
= {prod-short} architecture overview

We are currently replacing {prod-short} existing workspace engine, the {prod-id-short}-server, with a new one, the https://github.com/devfile/devworkspace-operator[DevWorkspace Operator]. The former is a Java web service that exposes an HTTP REST API to manage {prod-short} workspaces and users. The latter is an {orch-name} Operator that extends the {orch-name} API so that {prod-short} workspaces can be managed as first class {prod-short} objects.

{prod-short} default workspace engine is still the {prod-id-short}-server but from v.7.28.0 of {prod-short} an administrator can configure it to use the DevWorkspace Operator following the instructions in xref:installation-guide:enabling-dev-workspace-engine.adoc[this article].

include::partial$con_che-with-dw-warning.adoc[]

The following sections describe the different architectures of {prod-short} configured with the DevWorkspace Operator or the {prod-id-short}-server. 

.Additional resources

* xref:administration-guide:che-architecture-overview-with-che-server.adoc[]
* xref:administration-guide:che-architecture-overview-with-dw.adoc[]
