[id="managing-backups-of-persistent-volumes_{context}"]
= Managing backups of persistent volumes

Persistent Volumes (PVs) store the {prod-short} workspace data similarly to how workspace data is stored for desktop IDEs on the local hard disk drive.

To prevent data loss, back up PVs periodically. The recommended approach is to use storage-agnostic tools for backing up and restoring {platforms-name} resources, including PVs.

[id="recommended-backup-tool-velero_{context}"]
== Velero backup tool

Velero is the recommended, open-source tool for backing up {orch-name} applications and their PVs.

Velero offers the following features:

* Deploy in the cloud or on premises.
* Back up the cluster and restore backed up data in case of data loss.
* Migrate cluster resources to other clusters.
* Replicate a production cluster to development and testing clusters.

NOTE: Alternatively, you can use backup solutions that depend on the underlying storage system: for example, solutions specific to Gluster or Ceph.

.Additional resources

* link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[Kubernetes Documentation - Persistent Volumes documentation]
* link:https://docs.gluster.org/en/latest/Quick-Start-Guide/Quickstart/[Gluster Docs]
* link:https://docs.ceph.com/docs/master/[Ceph Documentation]
* link:https://velero.io/docs/main/disaster-case/[Velero Docs - Disaster Recovery]
* link:https://velero.io/docs/main/restore-reference/[Velero Docs - Restore Reference]
