// Module included in the following assemblies:
//
// {prod-id-short}-workspace-controller-with-dw

[id="{prod-id-short}-plug-in-registry-with-dw_{context}"]
= {prod-short} plug-in registry (in the DevWorkspace context)

The {prod-short} plug-in registry is a service that provides the list editors and editors' extensions for {prod-short} workspaces. Those editors and their extensions are specified as fragment of a https://docs.devfile.io/[v2 Devfile] and can be referenced from the files ``.che/che-editor.yaml`` and ``.che/che-theia-plugins.yaml`` at the root of a git repository or from a v2 Devfile ``che-editor.yaml`` and ``che-theia-plugins.yaml`` attributes. The plugin registry runs in a container and can be deployed wherever {prod-short} server connects.

[cols=2*]
|===
ifeval::["{project-context}" == "che"]
| Source code
| link:{url-plug-in-registry-repo}[{prod-short} plug-in registry]
endif::[]

| Container image
| `{che-plugin-registry-container-image}`
|===

ifeval::["{project-context}" == "che"]
.Additional resources

* xref:building-and-running-a-custom-registry-image.adoc[]
endif::[]
