// configuring-authorization

[id="authorization-and-user-management_{context}"]
= Authorization and user management

{prod} uses {identity-provider-url}[{identity-provider}]  to create, import, manage, delete, and authenticate users. {identity-provider} uses built-in authentication mechanisms and user storage. It can use third-party identity management systems to create and authenticate users. {prod} requires a {identity-provider} token when you request access to {prod-short} resources.

Local users and imported federation users must have an email address in their profile.

The default {identity-provider} credentials are `admin:admin`. You can use the `admin:admin` credentials when logging into {prod} for the first time. It has system privileges.

.Procedure

To find your {identity-provider} URL:

ifeval::["{project-context}" == "che"]
If {prod-short} is running on Kubernetes:

* Go to `+$CHE_HOST:5050/auth+`.

If {prod-short} is deployed on OpenShift:
endif::[]

* Go to the OpenShift web console and navigate to the *{identity-provider}* {orch-namespace}.
