[id="external-postgresql-setup_{context}"]
= External PostgreSQL setup

By default, {prod-short} Operator creates and manages deployment of the internal PostgreSQL database. However, {prod-short} Operator does not support full life-cycle capabilities such as backups and recovery.

An external PostgreSQL database is recommended for a business-critical setup. The external PostgreSQL can be configured for High Availability (HA) and Point In Time Recovery (PITR).

The external PostgreSQL instance can be configured as on-premises or to use a cloud service such as Amazon Relational Database Service (Amazon RDS). Amazon RDS, for example, enables deployment of production databases in a Multi-Availability Zone configuration for a resilient disaster recovery strategy with daily and on-demand snapshots.

The recommended configuration of an example database:

[options="header"]
|===
|Parameter | Value
|Instance class | db.t2.small
|vCPU | 1
|RAM | 2 GB
|Multi-az | true, 2 replicas
|Engine version | 9.6.11
|TLS | enabled
|Automated backups | enabled (30 days)
|===

Making workspace metadata and user information persistent involves configuring the external PostgreSQL database and configuring Che to use the configured external PostgreSQL database:

* xref:configuring-the-external-postgresql_{context}[]

* xref:configuring-{prod-id-short}-to-work-with-the-external-postgresql_{context}[]

.Additional resources

* link:https://postgresql.org/docs/current/[PostgreSQL Documentation]
* link:https://postgresql.org/docs/current/backup.html[PostgreSQL Documentation - Backup and Restore]
* link:https://aws.amazon.com/rds/[Amazon RDS]