// authorizing-users

[id="{prod-id-short}-system-permissions_{context}"]
= {prod-short} system permissions

{prod-short} system permissions control aspects of the whole {prod-short} installation. The following permissions are applicable to the system:

.{prod-short} system permission
[options="header",cols="2"]
|===
| Permission
| Description

| manageSystem
| Allows control of the system and workspaces.
| setPermissions
| Allows updating the permissions for users on the system.
| manageUsers
| Allows creating and managing users.
| monitorSystem
| Allows accessing endpoints used for monitoring the state of the server.
|===

All system permissions are granted to the administrative user. To configure the administrative user, use the `CHE_SYSTEM_ADMIN__NAME` property. The default value is `admin`. The system permissions are granted when the {prod-short} server starts. If the record of the user is not in the {prod-short} user database, the permissions are granted after the first login of the user.
