[id="proc_collecting-dev-workspace-operator-metrics-with-prometheus"]
= Collecting {devworkspace} Operator metrics

[role="_abstract"]
To use the in-cluster Prometheus instance to collect, store, and query metrics about the {devworkspace} Operator:

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* An instance of {prod-short} running in {orch-name}.

* The `devworkspace-controller-metrics` Service is exposing metrics on port `8443`. This is preconfigured by default.

.Procedure

. Create the ServiceMonitor for detecting the Dev Workspace Operator metrics Service
+
.ServiceMonitor
====
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devworkspace-controller
  namespace: {prod-namespace} <1>
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 10s <2>
      port: metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - openshift-operators
  selector:
    matchLabels:
      app.kubernetes.io/name: devworkspace-controller
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The rate at which a target is scraped.
====

. Allow the in-cluster Prometheus instance to detect the ServiceMonitor in the {prod-short} namespace. The default {prod-short} namespace is `{prod-namespace}`.
+
[source,subs="+attributes"]
----
$ oc label namespace {prod-namespace} openshift.io/cluster-monitoring=true
----

.Verification

. For a fresh installation of {prod-short}, generate metrics by creating a {prod-short} workspace from the Dashboard.

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `devworkspace_started_total` and click *Run queries*.
+
For more metrics, see xref:ref_devworkspace-specific-metrics[].

[TIP]
====
To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:
. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----
. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----
====
.Additional resources
* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]
* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]

