[id="backing-up-a-{prod-id-short}-instance-using-the-checlusterbackup-custom-object_{context}"]
= Backing up a {prod-short} instance using the CheClusterBackup custom object

You can use a `CheClusterBackup` custom object to take a backup snapshot of a {prod-short} instance and to send the snapshot to the configured backup server. To create each and every backup snapshot requires a new `CheClusterBackup` custom object; that is, editing an already consumed `CheClusterBackup` custom object, during or after backing up, has no effect.

include::snip_warning-does-not-back-up-content-of-workspaces.adoc[]

.Prerequisites

* Configured backup server. See xref:supported-restic-compatible-backup-servers.adoc[].
* Created `CheBackupServerConfiguration` custom object. See the previous section of this guide.

.Procedure

. Create the `CheClusterBackup` custom object, which creates a backup snapshot:
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-id}-backup
  namespace: {prod-namespace}
spec:
  backupServerConfigRef: backup-server-configuration <1>
  useInternalBackupServer: false <2>
----
<1> Name of the `CheBackupServerConfiguration` custom object defining what backup server to use.
<2> Configures the custom resource to back up to a backup server.
+
[TIP]
====
If you intend to reuse a `name` for `CheClusterBackup` custom objects, first make sure to delete any existing custom object with the same `name`. To delete it on the command line, use {orch-cli}:
[subs="+attributes,+quotes"]
----
$ {orch-cli} delete CheClusterBackup _<name>_ -n {prod-namespace}
----
====

. Read the `status` section of the `CheClusterBackup` custom object to verify the backup process, for example:
+
[source,yaml,subs="+quotes,+attributes"]
----
status:
  message: 'Backup is in progress. Start time: <timestamp>' <1>
  stage: Collecting {prod-short} installation data <2>
  state: InProgress <3>
----
<1> Summary of the latest state of the backup process.
<2> Current stage of the backup process in a human-readable format.
<3> Backup process state: `InProgress` or `Succeeded` or `Failed`.
+
The {prod-short} instance is backed up in a snapshot when `state` is `Succeeded`:
+
[source,yaml,subs="+quotes,+attributes"]
----
status:
  ...
  message: >-
    Backup successfully finished at 2021-12-03 10:07:51.151090621 +0000 UTC
    m=+999.553272281 <1>
  snapshotId: 9f0adce2 <2>
  state: Succeeded <3>
----
<1> Summary of the latest state of the backup process.
<2> ID of the created backup snapshot. This field appears only when `state` is `Succeeded`.
<3> Backup process state: `Succeeded` (or `Failed`).
