:_content-type: PROCEDURE

[id="importing-extensions-that-are-not-in-the-open-vsx-registry"]
= Importing extensions that are not in the Open VSX Registry

This section describes how to add VS Code extensions that are not in the link:https://open-vsx.org/[Open VSX Registry] to {prod-short}'s embedded Open VSX Registry.

To use an extension that has not been published to the link:https://open-vsx.org/[Open VSX Registry], contact the extension's author to ask them to publish the extension. See link:https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension[How to Publish an Extension].

If you need the extension and the owner cannot or will not publish it, you may be able to fork it and publish it yourself. Consult the license terms of the extension to find out if this is possible. 

You can also import the extension into the local registry from the procedure in this document. 

.Prerequisites
. The VS Code extension file (.vsix) must be available to download via direct link.
. The ID and version of the extension to be added.  

.Procedure
. Modify `openvsx-sync.json` file in the link:https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/dependencies/che-plugin-registry/openvsx-sync.json[plugin-registry repository] to add an information about the extension:
+
[source,json]
----
    {
        "id": "extension_id",
        "download": "url_to_download_vsix_file",
        "version": "extension_version"
    }
----
for example:
+
[source,json]
----
    {
        "id": "redhat.vscode-yaml",
        "version": "1.10.1",
        "download": "https://github.com/redhat-developer/vscode-yaml/releases/download/1.10.1/yaml-1.10.1-19523.vsix"
    }
----
NOTE: If the extension is available in link:https://marketplace.visualstudio.com/vscode[VS Code Marketplace], the download link could be build like https://extension_publisher.gallery.vsassets.io/_apis/public/gallery/publisher/extension_publisher/extension/extension_name/extension_version/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage. For GoogleCloudTools.cloudcode extension it is https://GoogleCloudTools.gallery.vsassets.io/_apis/public/gallery/publisher/GoogleCloudTools/extension/cloudcode/1.20.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
. To build the plug-in registry container image and publish it to a container registry, run the following commands:
+
[subs="+attributes,+quotes"]
----
$ ./build.sh -o username -r quay.io -t next
$ {docker-cli} push quay.io/username/che-plugin-registry:custom
----
. Customize an instance of `CheCluster` Custom Resource in the cluster to point the image and save the changes:
+
[source,yaml,subs="+quotes"]
----
spec:
  components:
    pluginRegistry:
      deployment:
        containers:
          - image: quay.io/username/pluginregistry-rhel8:next
      openVSXURL: '' 
----
. Check that `che-plugin-registry` pod restarted and it's running. Restart the workspace and check plugins in the Plugins view.
