[id="creating-a-new-backup-using-the-internal-backup-server"]
== Creating a new backup using the internal backup server

WARNING: This procedure does not back up the content of users' workspaces. To back up the content of users' workspaces, see xref:managing-backups-of-persistent-volumes.adoc[Managing backups of persistent volumes].

//CHECK WITH SME IF THESE PREREQS ARE NOT REQUIRED
.Prerequisites
* xref:setup-backup-server.adoc[A backup server is set up].

* xref:define-backup-server-for-operator.adoc[{prod-short} Operator is configured to use the backup server].

include::partial$snip_internal-backup-server-warning.adoc[]

To use the internal backup server, request automatic configuration from {prod-short} Operator.
//"The preparation described above is not required."???

.Procedure

* Configure the automatic setup and sending of the backup to the internal backup server:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-short}-backup
spec:
  useInternalBackupServer: true
----