[id="creating-a-new-backup-using-an-object"]
== Creating a new backup using an object

This section describes how to create backups of {prod-short} using Custom Resource objects.

WARNING: This procedure does not back up the content of users' workspaces. To back up the content of users' workspaces, see xref:managing-backups-of-persistent-volumes.adoc[Managing backups of persistent volumes].

.Prerequisites

* xref:setup-backup-server.adoc[A backup server is set up].

* xref:define-backup-server-for-operator.adoc[{prod-short} Operator is configured to use the backup server].

include::partial$snip_internal-backup-server-warning.adoc[]

.Procedure

. Create a `CheClusterBackup` backup object to create a new backup:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-short}-backup
spec:
  backupServerConfigRef: backup-server-configuration <1>
----
+
<1> Name of the `CheBackupServerConfiguration` object defining what backup server to use.

NOTE: To reusing the name of an existing backup object for a new backup object, delete the old object:
+
[subs="+attributes,+quotes"]
----
{orch-cli} delete CheClusterBackup _<name>_ -n {prod-namespace}
----