:_content-type: PROCEDURE
:description: Setting up the Bitbucket application link
:keywords: configuring-authorization, configure-authorization, private-repository, private-git-repository, private-repo, private-git-repo, private-bitbucket, private, bitbucket, bitbucket-repo, bitbucket-repository
:navtitle: Setting up the Bitbucket application link
// :page-aliases:

[id="setting-up-the-bitbucket-application-link_{context}"]
= Setting up the Bitbucket application link

Set up a Bitbucket application link using OAuth 1.0.

.Prerequisites

* You are logged in to Bitbucket.
* link:https://www.openssl.org/[`openssl`] is installed in the operating system you are using.
* link:https://www.gnu.org/software/coreutils/base64[`base64`] is installed in the operating system you are using.

.Procedure

. On a command line, generate the `privatepkcs8-stripped.pem` key in the required format and with Base64 encoding:
+
[subs="+quotes,+attributes,+macros"]
----
$ openssl genrsa -out private.pem 2048

$ openssl pkcs8 -topk8 -inform pem -outform pem -nocrypt -in private.pem -out privatepkcs8.pem

$ cat privatepkcs8.pem | sed 's/-----BEGIN PRIVATE KEY-----//g' | sed 's/-----END PRIVATE KEY-----//g' | tr -d '\n' | base64 | tr -d '\n' > privatepkcs8-stripped.pem
----

. Save the Base64-encoded `privatepkcs8-stripped.pem` file for use when applying the Bitbucket application link Secret.

. On a command line, generate the `public-stripped.pub` key in the required format:
+
[subs="+quotes,+attributes,+macros"]
----
$ openssl rsa -in private.pem -pubout > public.pub

$ cat public.pub | sed 's/-----BEGIN PUBLIC KEY-----//g' | sed 's/-----END PUBLIC KEY-----//g' | tr -d '\n' > public-stripped.pub
----

. On a command line, generate a Base64-encoded consumer key:
+
[subs="+quotes,+attributes,+macros"]
----
$ openssl rand -base64 24 > bitbucket-consumer-key
----

. Save the Base64-encoded `bitbucket_consumer_key` file for use when applying the Bitbucket application link Secret.

. On a command line, generate a Base64-encoded shared secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ openssl rand -base64 24 > bitbucket-shared-secret
----

. Save the Base64-encoded `bitbucket-shared-secret` file for use when applying the Bitbucket application link Secret.

. Go to menu:Administration[Application Links].
//I can't find *Administration* when I am logged in to Bitbucket. max-cx
//using https://youtu.be/djXwI9OGvhQ?t=117 as a reference (also asking the SME). max-cx
//in the above YouTube tutorial: `<host>/bitbucket/plugins/servlet/applinks/listApplicationLinks`

. Enter `pass:c,a,q[{prod-url}]/` into the URL field and click *Create new link*.

. Under *The supplied Application URL has redirected once*, check the *Use this URL* checkbox and click *Continue*.

. Enter *{prod-short}* as the *Application Name*.

. Select *Generic Application* as the *Application Type*.

. Enter *{prod-short}* as the *Service Provider Name*.

. Paste the content of the `bitbucket-consumer-key` file as the *Consumer key*.

. Paste the content of the `bitbucket-shared-secret` file as the *Shared secret*.

. Enter `__<bitbucket_server_url>__/plugins/servlet/oauth/request-token` as the *Request Token URL*.

. Enter `__<bitbucket_server_url>__/plugins/servlet/oauth/access-token` as the *Access token URL*.

. Enter `__<bitbucket_server_url>__/plugins/servlet/oauth/authorize` as the *Authorize URL*.

. Check the *Create incoming link* checkbox.

. Click *Continue*.

. Paste the content of the `bitbucket_consumer_key` file as the *Consumer Key*.

. Enter *{prod-short}* as the *Consumer name*.

. Paste the content of the `public-stripped.pub` file as the *Public Key*.

. Click *Continue*.

.Additional resources

* link:https://confluence.atlassian.com/bitbucketserver/link-to-other-applications-1018764620.html[Atlassian Documentation: Link to other applications]