// Module included in the following assemblies:
//
// installing-{prod-id-short}-on-codeready-containers

[id="using-{prod-cli}-to-install-{prod-id-short}-on-red-hat-openshift-local_{context}"]
= Using {prod-cli} to install {prod-short} on Red Hat OpenShift Local 

This section describes how to install {prod-short} on Red Hat OpenShift Local using `{prod-cli}`.

.Prerequisites

* The `{prod-cli}` management tool is available. See xref:using-the-chectl-management-tool.adoc[].
* An installation of Red Hat OpenShift Local. See link:https://console.redhat.com/openshift/create/local[Installing Red Hat OpenShift Local].
* The path to the user's Red Hat OpenShift Local pull secret is known as __<pull-secret-file>__.

.Procedure

. Remove any previous cluster:
+
----
$ crc delete
----

. Configure your host machine for Red Hat OpenShift Local:
+
----
$ crc setup
----

. Start the Red Hat OpenShift Local virtual machine with at least 12 GB of RAM and specify the path to your pull secret, and take note of the password for the user `kubeadmin`, displayed at the end of the Red Hat OpenShift Local initiation:
+
[subs="+quotes"]
----
$ crc start --memory 12288 --pull-secret-file __<pull-secret-file>__
----

. Enable access to the `oc` command line interface embedded in Red Hat OpenShift Local:
+
----
$ eval $(crc oc-env)
----

. Install the {prod-short} instance using {prod-cli}:
+
[subs="+attributes"]
----
$ {prod-cli} server:deploy --platform crc
----


.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_openshift_local/[Product documentation for Red Hat OpenShift Local].
* link:https://github.com/code-ready/crc[Red Hat OpenShift Local on GitHub].
