
[id="migration-from-postgresql-9-to-postgresql-13_{context}"]
= Migration from PostgreSQL 9 to PostgreSQL 13

By the 11th of November, 2021, the PostgreSQL version 9.6 came out of support, and {prod-short} team recommends that all users undergo migrating to version 13.

Follow the procedure below to migrate to a newer version of PostgreSQL successfully without any data loss.

.Prerequisites

* The `{orch-cli}` tool is available.
* An instance of {prod-short} running in {orch-name}.

.Procedure

. In all running workspaces in the {prod-short} instance, save and push changes back to the Git repositories.
+
. Stop all workspaces in the {prod-short} instance.
+
. Scale down the {prod-short} and {identity-provider} deployments:
+
[subs="+quotes,+attributes"]
----
{orch-cli} scale deployment {prod-deployment} --replicas=0 -n {prod-namespace}
{orch-cli} scale deployment keycloak --replicas=0 -n {prod-namespace}
----

. Backup available databases:
+
[subs="+quotes,+attributes"]
----
POSTGRES_POD=$({orch-cli} get pods -n {prod-namespace} | grep postgres | awk '{print $1}')
CHE_POSTGRES_DB=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json  | jq '.spec.database.chePostgresDb')
{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "pg_dump $CHE_POSTGRES_DB > /tmp/che.sql"
{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "pg_dump keycloak > /tmp/keycloak.sql"
----

. Copy the obtained backups to a local file system:
+
[subs="+quotes,+attributes"]
----
{orch-cli} cp {prod-namespace}/$POSTGRES_POD:/tmp/che.sql che.sql
{orch-cli} cp {prod-namespace}/$POSTGRES_POD:/tmp/keycloak.sql keycloak.sql
----

. Scale down the PostgreSQL deployment:
+
[subs="+quotes,+attributes"]
----
{orch-cli} scale deployment postgres --replicas=0 -n {prod-namespace}
----

. Delete the corresponding PVC unit to clean up old data, a new one will appear in a few seconds:
+
[subs="+quotes,+attributes"]
----
{orch-cli} delete pvc postgres-data -n {prod-namespace}
----

. Set a new PostgreSQL version to use:
+
[subs="+quotes,+attributes"]
----
{orch-cli} patch checluster {prod-checluster} -n {prod-namespace} --type=json -p '[{"op": "replace", "path": "/spec/database/postgresVersion", "value": "13.3"}]'
----

. Scale up the PostgreSQL deployments:
+
[subs="+quotes,+attributes"]
----
{orch-cli} scale deployment postgres --replicas=1 -n {prod-namespace}
{orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component=postgres -n {prod-namespace} --timeout=120s
----

. Provision a database:
+
[subs="+quotes,+attributes"]
----
POSTGRES_POD=$({orch-cli} get pods -n {prod-namespace} | grep postgres | awk '{print $1}')
OPERATOR_POD=$({orch-cli} get pods -n {prod-namespace} | grep {prod-operator} | awk '{print $1}')

IDENTITY_POSTGRES_SECRET=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json | jq -r '.spec.auth.identityProviderPostgresSecret')
IDENTITY_POSTGRES_PASSWORD=$(if [ -z "$IDENTITY_POSTGRES_SECRET" ] || [ $IDENTITY_POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.auth.identityProviderPostgresPassword'; else {orch-cli} get secret $IDENTITY_POSTGRES_SECRET -n {prod-namespace} -o json | jq -r '.data.password' | base64 -d; fi)

{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE USER keycloak WITH PASSWORD '$IDENTITY_POSTGRES_PASSWORD'\""
{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"CREATE DATABASE keycloak\""
{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak\""

POSTGRES_SECRET=$({orch-cli} get checluster/{prod-checluster} -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresSecret')
CHE_USER=$(if [ -z "$POSTGRES_SECRET" ] || [ $POSTGRES_SECRET = "null" ]; then {orch-cli} get checluster/{prod-checluster}  -n {prod-namespace} -o json | jq -r '.spec.database.chePostgresUser'; else {orch-cli} get secret $POSTGRES_SECRET -n {prod-namespace} -o json | jq -r '.data.user' | base64 -d; fi)
{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql postgres -tAc \"ALTER USER $CHE_USER WITH SUPERUSER\""
----

. Copy the backups to the PostgreSQL Pod:
+
[subs="+quotes,+attributes"]
----
{orch-cli} cp che.sql {prod-namespace}/$POSTGRES_POD:/tmp/che.sql
{orch-cli} cp keycloak.sql {prod-namespace}/$POSTGRES_POD:/tmp/keycloak.sql
----

. Restore the database:
+
[subs="+quotes,+attributes"]
----
{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql keycloak < /tmp/keycloak.sql"
{orch-cli} exec -it $POSTGRES_POD -n {prod-namespace}  -- bash  -c "psql $CHE_POSTGRES_DB < /tmp/che.sql"
----

. Scale up the {identity-provider} and {prod-short} deployments:
+
[subs="+quotes,+attributes"]
----
{orch-cli} scale deployment keycloak --replicas=1 -n {prod-namespace}
{orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component=keycloak -n {prod-namespace} --timeout=120s
{orch-cli} scale deployment {prod-deployment} --replicas=1 -n {prod-namespace}
{orch-cli} wait --for=condition=ready pod -l app.kubernetes.io/component={prod-deployment} -n {prod-namespace} --timeout=120s
----
