// configuring-bitbucket-servers
 
[id="configuring_bitbucket_servers_{context}"]
= Configuring a Bitbucket server that uses self-signed TLS certificates
 
The following chapter describes how to configure a Bitbucket (BB) server that uses self-signed TLS certificates so that the {prod-short} server and workspace components can establish a trusted connection with BB.

* Creating ConfigMaps for additional TLS and `gitSelfSign` certificates. This enables:

** Launching a factory using a devfile URL.
** Importing and cloning a project.

[NOTE]
====
* Configure the OAuth 1 authentication on the BB server side. For more information, see xref:configuring-authorization#proc_configuring-bitbucket-server-oauth1_{context}[Configuring Bitbucket Server OAuth 1]
* Creating a ConfigMap for importing additional certificates is necessary only if a BB server is set up with self-signed TLS certificates. These certificates are needed for the proper functionality of {prod-short} server and tools inside of a workspace, which use them for performing Git operations related to a specific repository.
====

 
.Prerequisites

* A value of the BB server certification authority (CA) exported in the Base64 ASCII format and stored in a `ca.crt` file.
* An instance of {prod-short}.
 
.Procedure
 
. Provision the CA of the BB server to the {prod-short} server to enable it to read the devfiles stored in the BB server. To do so, add the following ConfigMap to the `{prod-namespace}` {orch-namespace}:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} create configmap bitbucket-ca-cert-for-factory --from-file=ca.crt -n {prod-namespace}
----
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} label configmap bitbucket-ca-cert-for-factory app.kubernetes.io/part-of=che.eclipse.org app.kubernetes.io/component=ca-bundle -n {prod-namespace}
----
 
. Provision the CA of the BB server to the {prod-short} server to be able to use Git operations. To do so, add a new ConfigMap to the `{prod-namespace}` {orch-namespace}:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} create configmap bitbucket-ca-for-git --from-file=ca.crt --from-literal=githost=__<bitbucket_server_url>__ -n {prod-namespace}
----
 
. Edit the CheCluster Custom Resource (CR) to configure the {prod-short} server. 
+
[source,yaml,subs="+quotes"]
----
spec:
  server:
    # …
    gitSelfSignedCert: __<boolean>__ <1>
----
<1> `true`: if BB is using a self-signed cert. Default value: `false`.
+
* For more information, see xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc[].
 
 
.Reference
 
* For adding a Bitbucket CA certificate into {prod-short}, see xref:installation-guide:importing-untrusted-tls-certificates.adoc[].
