// Module included in the following assemblies:
//
// running-custom-registries

[id="adding-a-custom-plug-in-registry-in-an-existing-{prod-id-short}-workspace_{context}"]
= Adding a custom plug-in registry in an existing {prod-short} workspace


The following section describes two methods of adding a custom plug-in registry in an existing {prod-short} workspace: 

* xref:adding-a-custom-plug-in-registry-using-command-palette_{context}[Adding a custom plug-in registry using Command palette] - For adding a new custom plug-in registry quickly, with a use of text inputs from Command palette command. This method does not allow a user to edit already existing information, such as plug-in registry URL or name. 

* xref:adding-a-custom-plug-in-registry-using-the-settings-file_{context}[Adding a custom plug-in registry using the `settings.json` file] - For adding a new custom plug-in registry and editing of the already existing entries.


[id="adding-a-custom-plug-in-registry-using-command-palette_{context}"]
== Adding a custom plug-in registry using Command Palette


.Prerequisites

* An instance of {prod-short}


.Procedure

. In the {prod-short} IDE, press kbd:[F1] to open the Command Palette, or navigate to *View -> Find Command* in the top menu.
+
The *command palette* can be also activated by pressing kbd:[Ctrl+Shift+p] (or kbd:[Cmd+Shift+p] on macOS).

. Enter the `Add Registry` command into the search box and pres kbd:[Enter] once filled.

. Enter the registry name and registry URL in next two command prompts.
+
* After adding a new plug-in registry, the list of plug-ins in the *Plug-ins* view is refreshed, and if the new plug-in registry is not valid, a user is notified by a warning message.



[id="adding-a-custom-plug-in-registry-using-the-settings-file_{context}"]
== Adding a custom plug-in registry using the `settings.json` file

The following section describes the use of the main {prod-short} Settings menu to edit and add a new plug-in registry using the `settings.json` file.


.Prerequisites

* An instance of {prod-short}

.Procedure

. From the main {prod-short} screen, select *Open Preferences* by pressing kbd:[Ctrl+,]
or using the gear wheel icon on the left bar.

. Select *Che Plug-ins* and continue by *Edit in `setting.json`* link.
+
The `setting.json` file is displayed.

. Add a new plug-in registry using the `chePlugins.repositories` attribute as shown below:
+
[source,yaml,subs="+macros,attributes"]
----
{
“application.confirmExit”: “never”,
“chePlugins.repositories”: {“test”: “pass:c,m,a,q[+https+://test.com]”}
}
----

. Save the changes to add a custom plug-in registry in an existing {prod-short} workspace.
+
* A newly added plug-in validation tool checks the correctness of URL values set in the `chePlugins.repositories` field of the `settings.json` file.
+
* After adding a new plug-in registry, the list of plug-ins in the *Plug-ins* view is refreshed, and if the new plug-in registry is not valid, a user is notified by a warning message. This check is also functional for plug-ins added using the Command palette command `Add plugin registry`.

