[id="backing-up-a-{prod-id-short}-instance-to-a-rest-backup-server-by-using-prod-cli-with-command-line-options_{context}"]
= Backing up a {prod-short} instance to a REST backup server by using {prod-cli} with command-line options

To make a backup snapshot of a {prod-short} instance and send the snapshot to a configured REST backup server, run {prod-cli} with the command-line options.

include::snip_warning-does-not-back-up-content-of-workspaces.adoc[]

.Prerequisites

* Installed `{prod-cli}`.
* Configured REST backup server. See xref:supported-restic-compatible-backup-servers.adoc[].

.Procedure

. Enter the `{prod-cli} server:backup` command with the following arguments:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:backup \
--repository-url=_<repository_url>_ \ <1>
--repository-password=_<repository_password>_ \ <2>
--username=_<username>_ \ <3>
--password=_<password>_ <4>
----
<1> Backup repository URL as an argument using the `--repository-url` or `-r` option.
<2> Backup repository password as an argument using the `--repository-password` or `-p` option.
<3> When authentication is required, the username for authenticating to the backup REST server as the `--username=_<username>_` argument.
<4> When authentication is required, the password for authenticating to the backup REST server as the `--password=_<password>_` argument.
+
include::snip_tip-omitting-prod-cli-options-for-server-backup-and-server-restore-onward-when-using-same-backup-server.adoc[]

//`--backup-server-config-name=__<name_of_CheBackupServerConfiguration>__` <>
//<> This option points {prod-cli} to a `CheBackupServerConfiguration` custom object.

. Verify the output of the command in the terminal window:
+
[subs="+quotes,+attributes"]
----
...
  ✔ Scheduling backup...OK
  ✔ Waiting until backup process finishes...OK
Backup snapshot ID: 9f0adce2
Command server:backup has completed successfully in 00:10.
----