[id="restoring-a-{prod-id-short}-instance-from-its-latest-backup-by-using-{prod-cli}_{context}"]
= Restoring a {prod-short} instance from its latest backup by using {prod-cli}

To restore the {prod-short} instance from its latest backup by using `{prod-cli}`, you can enter `latest` as the snapshot ID.

include::snip_warning-backup-snapshots-are-bound-to-specific-cluster.adoc[]

IMPORTANT: If the backup snapshot was taken in an earlier version of Che, add the `--version=__<earlier_version_number>__` option to the `chectl server:restore` command to roll back Che to that earlier version.

.Prerequisites

* Installed `{prod-cli}`.
* Backup snapshot of a {prod-short} instance on any of the following:
** xref:backups-of-che-instances-to-an-sftp-backup-server.adoc[SFTP backup server]
** xref:backups-of-che-instances-to-amazon-s3.adoc[Amazon S3 or S3 API compatible backup server]
** xref:backups-of-che-instances-to-a-rest-backup-server.adoc[REST backup server]
** xref:backups-of-che-instances-to-the-internal-backup-server.adoc[Internal backup server]

.Procedure

. Run the `{prod-cli} server:restore` command with the following arguments:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:restore \
--snapshot-id=latest \ <1>
--repository-url=_<repository-url>_ \ <2>
--repository-password=_<repository-password>_ <3>
----
<1> Specifies the latest snapshot.
<2> The backup repository URL as an argument using the `--repository-url` or `-r` option. (Omitted when using the internal backup server.)
<3> The backup repository password as an argument using the `--repository-password` or `-p` option. (Omitted when using the internal backup server.)
+
include::snip_tip-omitting-prod-cli-options-for-server-backup-and-server-restore-onward-when-using-same-backup-server.adoc[]

. When prompted in the output, enter `y` to confirm:
+
[subs="+quotes,+attributes"]
----
...
 ✔ Snapshot:          ...
 Asking for restore confirmation: Do you want to proceed? [y/n]
...
----
+
TIP: To skip this question, add the `--batch` option to the `server:restore` command.