// Used in:
// * installation-guide/installing-che-in-a-restricted-environment/
// * installation-guide/upgrading-che-using-the-cli-management-tool-in-restricted-environment/
// * administration-guide/building-custom-registry-images/

[id="building-a-custom-plug-ins-registry-image_{context}"]
= Building a custom plug-ins registry image

This section describes how to build a custom plug-ins registry image.
The procedure explains how to add a plug-in.
The image contains plug-ins or extensions metadata. 

.Prerequisites

* NodeJS 12.x

* A running version of yarn. See: link:https://yarnpkg.com/getting-started/install[Installing Yarn].

* `./node_modules/.bin` is in the `PATH` environment variable.

* A running installation of link:http://podman.io[podman] or link:http://docker.io[docker].
ifeval::["{project-context}" != "che"]
* Valid content for the `meta.yaml` file describing the plug-in to add. See: xref:end-user-guide:publishing-metadata-for-a-vs-code-extension.adoc[]
endif::[]


.Procedure

. Clone the plug-ins registry repository and check out the version to deploy:
+
include::example$snip_{project-context}-clone-the-plug-in-registry-repository.adoc[]

ifeval::["{project-context}" == "che"]
. In the `./{che-plugin-registry-directory}/` directory, edit the `che-theia-plugins.yaml` file.
endif::[]
ifeval::["{project-context}" != "che"]
. In the `./{che-plugin-registry-directory}/v3/plugins/` directory, create new directories `__<publisher>__/__<plugin-name>__/__<plugin-version>__/` and a `meta.yaml` file in the last directory.
endif::[]
+

ifeval::["{project-context}" == "che"]
. Add valid content to the `che-theia-plugins.yaml` file, for detailed information see: xref:end-user-guide:adding-a-vs-code-extension-to-the-che-plugin-registry.adoc[].
endif::[]
ifeval::["{project-context}" != "che"]
.File organization for a plugin
====
[subs="+attributes,+quotes"]
----
./{che-plugin-registry-directory}/v3/plugins/
├── _<publisher>_
│   └── _<plugin-name>_
│       ├── _<plugin-version>_
│       │   └── meta.yaml
│       └── latest.txt
----
====

. Add valid content to the `meta.yaml` file. See: xref:end-user-guide:publishing-metadata-for-a-vs-code-extension.adoc[].

. Create a file named `latest.txt` with content the name of the latest `_<plugin-version>_` directory.
+
.Example plug-in files tree
====
[subs="+attributes"]
----
include::example$snip_{project-context}-plug-in-tree.adoc[]
----
====
endif::[]

. Build a custom plug-ins registry image:
+
include::example$snip_{project-context}-build-a-custom-plug-in-registry.adoc[]
+
[NOTE]
====
To display full options for the `build.sh` script, use the `--help` parameter.
To include the plug-in binaries in the registry image, add the `--offline` parameter.
====

ifeval::["{project-context}" == "che"]
include::example$snip_{project-context}-plugin-registry-build-output.adoc[]
endif::[]

.Additional resources

* xref:running-custom-registries.adoc[].
