[id="restoring-a-{prod-id-short}-instance-from-a-backup-by-using-the-checlusterrestore-object_{context}"]
= Restoring a {prod-short} instance from a backup by using the CheClusterRestore custom object

You can restore a {prod-short} instance from a backup snapshot by using custom resources. A new `CheClusterRestore` custom object is required every time you restore a {prod-short} instance from a backup snapshot. (So editing an already consumed `CheClusterRestore` custom object, during or after backing up, has no effect.)

include::snip_warning-backup-snapshots-are-bound-to-specific-cluster.adoc[]

IMPORTANT: The `CheClusterRestore` custom object is unusable for recovering a {prod-short} instance of an earlier version of {prod-short}. Use `{prod-cli}` to recover a {prod-short} instance of an earlier version of {prod-short}; see xref:restoring-a-che-instance-from-a-backup-by-using-prod-cli_{context}[].

.Prerequisites

* Backup snapshot of a {prod-short} instance on any of the following:
** xref:backing-up-of-che-instances-to-an-sftp-backup-server.adoc[SFTP backup server]
** xref:backing-up-of-che-instances-to-amazon-s3.adoc[Amazon S3 or S3 API compatible backup server]
** xref:backing-up-of-che-instances-to-a-rest-backup-server.adoc[REST backup server]
** xref:backing-up-of-che-instances-to-the-internal-backup-server.adoc[Internal backup server]

.Procedure

. Create the `CheClusterRestore` custom object, which restores a backup:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterRestore
metadata:
  name: {prod-id}-restore
  namespace: {prod-namespace}
spec:
  backupServerConfigRef: backup-server-configuration <1>
  snapshotId: _<snapshot_id>_ <2>
----
<1> Name of the `CheBackupServerConfiguration` object that defines what backup server to use. You can find this name as `backupServerConfigRef` in `spec` of the `CheClusterBackup` custom object. (You can also find it as `name` in `metadata` of the `CheBackupServerConfiguration` custom object used to take the backup snapshot you are restoring.)
<2> Optional parameter defining the Snapshot ID to restore from. The default value is the last snapshot in the backup repository on the backup server.
+
[TIP]
====
To reuse a `name` for `CheClusterRestore` custom objects, first delete any existing custom object with the same `name`. To delete it on the command line, use {orch-cli}:
[source,shell,subs="+attributes,+quotes"]
----
$ {orch-cli} delete CheClusterRestore _<name>_ -n {prod-namespace}
----
====

. Read the `status` section of the `CheClusterRestore` object to monitor the recovery process, for example:
+
[source,yaml,subs="+attributes"]
----
status:
  message: 'Restore is in progress. Start time: <timestamp>' <1>
  stage: Restoring {prod-short} related cluster objects <2>
  state: InProgress <3>
----
<1> Overall state or error message; for example, `Restore successfully finished`.
<2> Current phase of the recovery process in a human-readable format.
<3> Recovery process state. One of `InProgress`, `Succeeded`, or `Failed`.
+
//here add the status Succeeded?

. Check that the {prod-short} instance has been recovered.
+
TIP: If errors occur in your browser after the recovery, clean up the browser data for the {prod-short} domain.

. Delete the `CheClusterRestore` object.