:_content-type: PROCEDURE
:description: Applying an application link Secret for the Bitbucket Server
:keywords: bitbucket, bitbucket-server, application-link, bitbucket-secret
:navtitle: Applying an application link Secret for the Bitbucket Server
// :page-aliases:

[id="applying-an-application-link-secret-for-the-bitbucket-server"]
= Applying an application link Secret for the Bitbucket Server

Prepare and apply the application link Secret for the Bitbucket Server.

.Prerequisites

* The application link is set up on the Bitbucket Server.

* The following files, which were created when setting up the application link, are prepared:
** `privatepkcs8-stripped.pem`
** Base64-encoded `bitbucket-consumer-key`
** Base64-encoded `bitbucket-shared-secret`

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: __<bitbucket_server_url>__ <2>
type: Opaque
data:
  private.key: __<Base64_content_of_privatepkcs8-stripped.pem>__ <3>
  consumer.key: __<Base64_content_of_bitbucket-consumer-key>__ <4>
  shared_secret: __<Base64_content_of_bitbucket-shared-secret>__ <5>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The URL of the Bitbucket Server.
<3> The content of the `privatepkcs8-stripped.pem` file, which was Base64-encoded when the file was generated.
<4> The content of the `bitbucket-consumer-key` file, which you manually encoded to Base64.
<5> The content of the `bitbucket-shared-secret` file, which you manually encoded to Base64.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the Secret is created.
