[id="configuring-prod-short-with-custom-resources-to-use-an-amazon-s3-backup-server_{context}"]
= Configuring {prod-short} with custom resouces to use an Amazon S3 backup server

To configure {prod-short} to use an Amazon S3 backup server:

.Prerequisites

* Configured backup server. See xref:supported-restic-compatible-backup-servers.adoc[]
* Backup repository. See link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html[Preparing a new repository].
* Password for the backup repository.

.Procedure

. Create the `CheBackupServerConfiguration` custom resource object in the {prod-namespace} namespace.
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: backup-server-configuration
spec:
  awss3:
    protocol: https <1>
    hostname: my-domain.net <2>
    port: 1234 <3>
    repositoryPath: {prod-id}-backups <4>
    repositoryPasswordSecretRef: backup-encryption-password-secret <5>
    awsAccessKeySecretRef: aws-user-credentials-secret <6>
----
<1> Optional property that specifies the protocol to be used. The default value is `https` with `http` as the second allowed option.
<2> Optional property that specifies the S3 hostname. The default value is `s3.amazonaws.com`.
<3> Optional property that specifies the port on which the backup server is running.
<4> The name of the bucket resource where the backup snapshots are stored. The bucket resource must be manually pre-created.
<5> The name of the secret containing a repository password, stored in the `repo-password` field. If the secret contains only one field, this name is arbitrary. The password is used to encrypt and decrypt backup snapshots data.
<6> The name of the secret containing user credentials stored in the `awsAccessKeyId` and `awsSecretAccessKey` fields.
+
NOTE: The Custom Resource object, stored in the `{prod-namespace}` namespace, must have only one section configured in the `spec` property.

. To configure multiple backup servers, create a separate `CheBackupServerConfiguration` custom resource object for each backup server.