// Module included in the following assemblies:
//
// Configuring Bitbucket server OAuth1

pass:[<!-- vale IBM.Headings = NO -->]

[id="proc_configuring-bitbucket-server-oauth1_{context}"]
= Configuring Bitbucket Server OAuth 1

pass:[<!-- vale IBM.Headings = YES -->]

This procedure describes how to activate OAuth 1 for Bitbucket Server to:

* Use devfiles hosted on a Bitbucket Server.
* xref:end-user-guide:authentication-against-bitbucket-server-with-the-personal-access-token.adoc[].

It enables {prod-short} to obtain and renew link:https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html[Bitbucket Server Personal access tokens].

.Prerequisites

* The `{orch-cli}` tool is available.
* Bitbucket Server is available from {prod-short} server.

.Procedure

. Generate a RSA key pair and a stripped down version of the public key:
+
[subs="+quotes,+attributes"]
----
openssl genrsa -out __<private.pem>__ 2048
openssl rsa -in __<private.pem>__ -pubout > __<public.pub>__
openssl pkcs8 -topk8 -inform pem -outform pem -nocrypt -in __<private.pem>__ -out __<privatepkcs8.pem>__
cat __<public.pub>__ | sed 's/-----BEGIN PUBLIC KEY-----//g' | sed 's/-----END PUBLIC KEY-----//g' | tr -d '\n' > __<public-stripped.pub>__
----

. Generate a consumer key and a shared secret.
+
[subs="+quotes,+attributes"]
----
openssl rand -base64 24 > __<bitbucket_server_consumer_key>__
openssl rand -base64 24 > __<bitbucket_shared_secret>__
----

. Create one {orch-name} Secret in {prod-short} namespace containing the consumer and private keys.
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} apply -f - <<EOF
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: <...> <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: <...> <2>
type: Opaque
data:
  private.key: <...> <3>
  consumer.key: <...> <4>
EOF
----
<1> {prod-short} namespace. The default is {prod-namespace}
<2> Bitbucket Server URL
<3> base64 encoded content of the __<privatepkcs8.pem>__ file without first and last lines.
<4> base64 encoded content of the `__<bitbucket_server_consumer_key>__` file.

. Configure an link:https://confluence.atlassian.com/adminjiraserver/using-applinks-to-link-to-other-applications-938846918.html[Application Link] in Bitbucket to enable the communication from {prod-short} to Bitbucket Server.

.. In Bitbucket Server, click the cog in the top navigation bar to navigate to *Administration*  > *Application Links*.

pass:[<!-- vale IBM.Usage = NO -->]

.. Enter the application URL: `pass:c,a,q[{prod-url}]` and click the btn:[Create new link] button.

pass:[<!-- vale IBM.Usage = YES -->]

pass:[<!-- vale IBM.PassiveVoice = NO -->]

.. On the warning message stating "No response was received from the URL" click the btn:[Continue] button.

pass:[<!-- vale IBM.PassiveVoice = YES -->]

.. Fill-in the *Link Applications* form and click the btn:[Continue] button.

Application Name::  `__<{prod-short}>__`

Application Type:: Generic Application.

Service Provider Name:: `__<{prod-short}>__`

Consumer Key:: Paste the content of the `__<bitbucket_server_consumer_key>__` file.

Shared secret:: Paste the content of the `__<bitbucket_shared_secret>__` file.

Request Token URL:: `__<Bitbucket Server URL>__/plugins/servlet/oauth/request-token`

Access token URL:: `__<Bitbucket Server URL>__/plugins/servlet/oauth/access-token`

Authorize URL:: `__<Bitbucket Server URL>__/plugins/servlet/oauth/access-token`

Create incoming link:: Enabled.

.. Fill-in the *Link Applications* form and click the btn:[Continue] button.

Consumer Key::  Paste the content of the `__<bitbucket_server_consumer_key>__` file.

Consumer name::  `__<{prod-short}>__`

Public Key:: Paste the content of the `__<public-stripped.pub>__` file.



.Additional resources

* link:https://bitbucket.org/product/enterprise[Bitbucket Server overview]
* link:https://bitbucket.org/product/download[Download Bitbucket Server]
* link:https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html[Bitbucket Server Personal access tokens]
* link:https://confluence.atlassian.com/jirakb/how-to-generate-public-key-to-application-link-3rd-party-applications-913214098.html[How to generate public key to application link 3rd party applications]
* link:https://confluence.atlassian.com/adminjiraserver/using-applinks-to-link-to-other-applications-938846918.html[Using AppLinks to link to other applications]
* xref:end-user-guide:authentication-against-bitbucket-server-with-the-personal-access-token.adoc[].
