:_content-type: PROCEDURE
:description: Applying the Microsoft Entra ID OAuth App Secret
:keywords: microsoft-azure-devops-entra-id-oauth-app, apply, secret
:navtitle: Applying the Microsoft Entra ID OAuth App Secret
// :page-aliases:

[id="applying-the-microsoft-entra-id-oauth-app-secret"]
= Applying the Microsoft Entra ID OAuth App Secret

Prepare and apply the Secret that enables {prod-short} to authenticate with Microsoft Entra ID for Azure DevOps repository access.

.Prerequisites

* You have set up the Microsoft Entra ID OAuth App.

* The following values, which were generated when setting up the Microsoft Entra ID OAuth App, are prepared:
** *Application (client) ID*
** *Directory (tenant) ID*
** *Client Secret*

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: azure-devops-oauth-config
  namespace: {prod-namespace}# <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: azure-devops
type: Opaque
stringData:
  tenant-id: __<Microsoft_Entra_ID_Tenant_ID>__# <2>
  id: __<Microsoft_Entra_ID_App_ID>__# <3>
  secret: __<Microsoft_Entra_ID_Client_Secret>__# <4>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The Microsoft Entra ID *Directory (tenant) ID*.
<3> The Microsoft Entra ID *Application (client) ID*.
<4> The Microsoft Entra ID *Client Secret*.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the Secret is created.

. Wait for the rollout of the {prod-short} server components to be completed.