// authenticating-to-the-{prod-id-short}-server

[id="authenticatinng-to-the-{prod-id-short}-server-using-other-authentication-implementations_{context}"]
= Authenticating to the {prod-short} server using other authentication implementations

This procedure describes how to use an OpenID Connect (OIDC) authentication implementation other than {identity-provider}.

.Procedure

. Update the authentication configuration parameters that are stored in the `multiuser.properties` file (such as client ID, authentication URL, realm name).

. Write a single filter or a chain of filters to validate tokens, create the user in the {prod-short} dashboard, and compose the `subject` object.

. If the new authorization provider supports the OpenID protocol, use the OIDC JS client library available at the settings endpoint because it is decoupled from specific implementations.

. If the selected provider stores additional data about the user (first and last name, job title), it is recommended to write a provider-specific *ProfileDao* implementation that provides this information.
