[id="enabling-readiness-init-containers-for-the-operator-installer_{context}"]
= Enabling the readiness init containers for the Operator installer

The readiness init containers are not enabled by default, so to use them you first have to enable them. To enable the readiness init containers for {prod-short} installed by the Operator installer:

.Prerequisites

* {prod} installed by the Operator installer.

.Procedure

. Find the name of the {prod-short} Operator Deployment. Usually it is `{prod-id-short}-operator`:
+
[source,yaml,subs="+quotes,+attributes"]
----
$ {orch-cli} get deployments -n {prod-namespace}
----

. Edit the Deployment as follows: Under `spec.template.spec.containers[0].env` of the Operator Deployment, insert the following lines:
+
[source,yaml,subs="+quotes,+attributes"]
----
 - name: ADD_COMPONENT_READINESS_INIT_CONTAINERS <1>
   value: "true"
----
<1> `ADD_COMPONENT_READINESS_INIT_CONTAINERS` is an environment variable.

. Wait while {prod-short} Operator restarts some components.

NOTE: Repeat these steps after each {prod-short} upgrade when a new Operator Deployment is created.
