:_content-type: PROCEDURE
:description: Applying the Bitbucket application link Secret
:keywords: bitbucket, bitbucket-application, bitbucket-app, bitbucket-application-link, bitbucket-app-link, bitbucket-secret, secret
:navtitle: Applying the Bitbucket application link Secret
// :page-aliases:

[id="applying-the-bitbucket-application-link-secret_{context}"]
= Applying the Bitbucket application link Secret

Prepare and apply the Bitbucket application link Secret.

.Prerequisites
* Setting up the Bitbucket application link is completed.
* The following Base64-encoded files, which were created when setting up the Bitbucket application link, are prepared:
** `privatepkcs8-stripped.pem`
** `bitbucket_consumer_key`
** `bitbucket-shared-secret`
* `{orch-cli}` is installed in the operating system you are using. See {link-installing-orch-cli}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: __<bitbucket_server_url>__ <2>
type: Opaque
data:
  private.key: __<Base64_content_of_privatepkcs8-stripped.pem>__ <3>
  consumer.key: __<Base64_content_of_bitbucket_server_consumer_key>__ <4>
  shared_secret: __<Base64_content_of_bitbucket-shared-secret>__ <5>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The Bitbucket server URL.
<3> The Base64-encoded content of the `privatepkcs8-stripped.pem` file.
<4> The Base64-encoded content of the `bitbucket_consumer_key` file.
<5> The Base64-encoded content of the `bitbucket-shared-secret` file.

. Apply the Secret by entering it with `{orch-cli}` on a command line:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the Secret is created.