[id="configuring-{prod-id-short}-with-custom-resources-to-use-an-sftp-backup-server_{context}"]
= Configuring {prod-short} with custom resources to use an SFTP backup server

To configure {prod-short} to use an SFTP backup server:

.Prerequisites

* Configured SFTP backup server. See xref:supported-restic-compatible-backup-servers.adoc[].

.Procedure

. Create a secret containing the `repo-password` key with a password:
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: backup-encryption-password-secret
  namespace: eclipse-che
type: Opaque
stringData:
  repo-password: __<password>__
----
+
(The {prod-short} Operator will set up this password for the backup repository that the {prod-short} Operator will create from this custom object on the backup server.)
+
include::snip_warning-about-losing-backup-repo-password.adoc[]

. Create a secret (for example, `name: ssh-key-secret`) containing the `ssh-privatekey` key with a private SSH key for logging in to the SFTP server without a password.

. Create the `CheBackupServerConfiguration` custom object:
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: backup-server-configuration
  namespace: {prod-namespace}
spec: <1>
  sftp:
    username: _<username>_ <2>
    hostname: _<hostname>_ <3>
    port: 1234 <4>
    repositoryPath: {prod-id}-backups <5>
    repositoryPasswordSecretRef: backup-encryption-password-secret <6>
    sshKeySecretRef: ssh-key-secret <7>
----
<1> `spec` property of this custom object must only have one section configured.
<2> User name on the remote server to log in using the SSH protocol.
<3> Remote server hostname.
<4> Optional property that specifies the port on which an SFTP server is running. The default value is `22`.
<5> Absolute or relative path on the server where backup snapshots are stored.
<6> Secret created in step 1.
<7> Secret created in step 2.

. Optional: To configure multiple backup servers, create a separate `CheBackupServerConfiguration` custom object for each backup server.

include::snip_important-backup-before-update-annotation.adoc[]