[id="proc_collecting-dev-workspace-operator-metrics-with-prometheus"]
= Collecting {devworkspace} Operator metrics

[role="_abstract"]
The {prod-short} Operator automatically configures the in-cluster Prometheus instance to collect, store, and query metrics about the {devworkspace} Operator.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* {devworkspace} metrics are enabled in the `CheCluster` Custom Resource. See xref:enabling-dev-workspace-operator-metrics[].

.Automatic configuration

When {devworkspace} Operator metrics are enabled via `spec.devEnvironments.metrics: true` (the default), the {prod-short} Operator automatically creates and manages the following resources:

* A `ServiceMonitor` custom resource named `devworkspace-controller` that monitors the {devworkspace} Operator metrics endpoint on port `8443`
* A `Role` and `RoleBinding` that grant the `prometheus-k8s` service account permission to scrape metrics from the {prod-short} namespace
* The `openshift.io/cluster-monitoring: "true"` label on the {prod-short} namespace to enable OpenShift cluster monitoring

These resources are automatically updated or recreated if modified or deleted, ensuring continuous metrics collection.

NOTE: The `devworkspace-controller-metrics` Service exposes metrics on port `8443` by default. This is preconfigured by the {devworkspace} Operator.

.Verification

. For a fresh installation of {prod-short}, generate metrics by creating a {prod-short} workspace from the Dashboard.

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `devworkspace_started_total` and click *Run queries*.
+
For more metrics, see xref:ref_devworkspace-specific-metrics[].

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

.Additional resources
* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]
* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]

