// Module included in the following assemblies:
//
// running-custom-registries

[id="adding-a-custom-plug-in-registry-in-an-existing-che-workspace_{context}"]
= Adding a custom plug-in registry in an existing {prod-short} workspace


The following section describes the use of the main {prod-short} Settings menu to edit and add a new plug-in registry using the `settings.json` file.


.Prerequisites

* An instance of {prod-short}

.Procedure

. From the main {prod-short} screen, select *Open Preferences* by pressing kbd:[Ctrl+,]
or using the gear wheel icon on the left bar.

. Select *Che Plug-ins* and continue by *Edit in `setting.json`* link.
+
The `setting.json` file is displayed.

. Add a new plug-in registry using the `chePlugins.repositories` attribute as shown below:
+
[source,yaml]
----
{
“application.confirmExit”: “never”,
“chePlugins.repositories”: {“test”: “++https++://test.com”}
}
----

. Save the changes to add a custom plug-in registry in an existing {prod-short} workspace.
+
* A newly added plug-in validation tool checks the correctness of URL values set in the `chePlugins.repositories` field of the `settings.json` file.
+
* After adding a new plug-in registry, the list of plug-ins in the *Plug-ins* view is refreshed, and if the new plug-in registry is not valid, a user is notified by a warning message. This check is also functional for plug-ins added using the Command palette command `Add plugin registry`.

