// Module included in the following assemblies:
//
// Configuring GitLab OAuth


[id="configuring-gitlab-oauth_{context}"]
= Configuring GitLab OAuth 2

OAuth 2 for GitLab allows accepting factories from private GitLab repositories.

.Prerequisites

* GitLab server is running and available from {prod-short}.

.Procedure

. link:https://docs.gitlab.com/ee/integration/oauth_provider.html#authorized-applications[Create an Authorized application in GitLab] with following parameters:
+
Application name:: {prod-short}
Callback URL:: {identity-provider} GitLab endpoint URL. 
+
.Callback URL default value
====
`++https://++keycloak-{prod-namespace}.__<DOMAIN>__/auth/realms/{prod-deployment}/broker/gitlab/endpoint`, where `__<DOMAIN>__` is the {orch-name} cluster domain. 
====
Store the `Application ID` and `Secret` values. 

. Create a custom OIDC provider link on {identity-provider} pointing to GitLab server. Fill the following fields:

Client ID:: a value from the `Application ID` field provided by GitLab server in previous step;
Client Secret:: a value from `Secret` field provided by GitLab server in previous step;
Authorization URL:: a URL which have a `https://__<GITLAB_DOMAIN>__/oauth/oauth/authorize` format;
Token URL:: a URL which have a `https://__<GITLAB_DOMAIN>__/oauth/oauth/token` format;
Scopes:: set of scopes which must contain (but not limited to) the following set: `api write_repository openid`

+ 
[NOTE]
====
* Substitute `_<GITLAB_DOMAIN>_` with the URL and port of the GitLab installation.
==== 


.Additional resources 

* xref:installation-guide:importing-untrusted-tls-certificates.adoc[].
* xref:installation-guide:deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc[].
