[id="restoring-a-prod-short-instance-from-a-backup-using-a-checlusterrestore-object_{context}"]
= Restoring a {prod-short} instance from a backup using a CheClusterRestore object

To recover a backup using a custom resource object:

WARNING: Backup snapshots are bound to the specific cluster and must only be recovered in that cluster.

.Prerequisites

* A backup. See xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#creating-a-backup-of-a-prod-short-instance-using-a-checlusterbackup-object_{context}[Creating a backup using a CheClusterBackup object].

.Procedure

. Create a `CheClusterRestore` object to restore a backup:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterRestore
metadata:
  name: {prod-short}-restore
spec:
  backupServerConfigRef: backup-server-configuration <1>
  snapshotId: ba92c7e0 <2>
----
<1> Name of the `CheBackupServerConfiguration` object that defines what backup server to use.
<2> Optional parameter defining the Snapshot ID to restore from. The default value is the last snapshot on the backup server.
+
[NOTE]
====
If you intend to reuse the object `name` for a new backup object, delete the old object first:

[subs="+attributes,+quotes"]
----
{orch-cli} delete CheClusterBackup _<name>_ -n {prod-namespace}
----
====

. Wait until the recovery process ends.
+
If errors occur in your browser after the recovery, clean up the browser data for the {prod-short} domain.

. Read the `status` section of the `CheClusterRestore` object to verify the recovery process:
+
[source,yaml,subs="+attributes"]
----
status:
  message: 'Restore is in progress. Start time: <timestamp>' <1>
  stage: Restoring {prod-short} related cluster objects <2>
  state: InProgress <3>
----
<1> Overall state or error message.
<2> Current phase of the recovery process in a human-readable format.
<3> Recovery process state. One of `InProgress`, `Succeeded`, or `Failed`.
