// Module included in the following assemblies:
//
// Configuring Bitbucket server OAuth1

[id="proc_configuring-bitbucket-server-oauth1_{context}"]
= Using Bitbucket with the OAuth 1 authentication

The following section describes configuration of the OAuth 1 authentication that is needed for performing read and write operations with Bitbucket repositories. To use BB repositories with allowed Git operations, such as `clone` and `push`, register a BB endpoint with {prod-short} first, and configure the OAuth 1 authentication.

[NOTE] 
====
This procedure requires:

* generating RSA key pairs
* generating a consumer key-secret pair
* creating an application link on the Bitbucket side
====

This procedure describes how to activate OAuth 1 for Bitbucket Server to:

* Use devfiles hosted on a Bitbucket Server.
* Enable {prod-short} to obtain and renew link:https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html[Bitbucket Server Personal access tokens].
* xref:end-user-guide:authenticating-on-scm-server-with-a-personal-access-token.adoc[].


.Prerequisites

* The `{orch-cli}` tool is available.
* Bitbucket Server is available from {prod-short} server.
* An instance of {prod-short}.

.Procedure

. Generate a RSA key pair and a stripped down version of the public key:
+
[subs="+quotes,+attributes"]
----
openssl genrsa -out __<private.pem>__ 2048
openssl rsa -in __<private.pem>__ -pubout > __<public.pub>__
openssl pkcs8 -topk8 -inform pem -outform pem -nocrypt -in __<private.pem>__ -out __<privatepkcs8.pem>__
cat __<public.pub>__ | sed 's/-----BEGIN PUBLIC KEY-----//g' | sed 's/-----END PUBLIC KEY-----//g' | tr -d '\n' > __<public-stripped.pub>__
----

. Generate a consumer key and a shared secret.
+
[subs="+quotes,+attributes"]
----
openssl rand -base64 24 > __<bitbucket_server_consumer_key>__
openssl rand -base64 24 > __<bitbucket_shared_secret>__
----

. Create a {orch-name} Secret in {prod-short} {orch-namespace} containing the consumer and private keys.
+
[source,yaml,subs="+quotes,+attributes"]
----
$ {orch-cli} apply -f - <<EOF
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: __<{prod-short}-namespace>__ <1>
  labels:
    app.kubernetes.io/component: 'oauth-scm-configuration'
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: '__<scm-server-endpoint>__' <2>
type: Opaque
data:
  private.key: '__<user-private-key>__' <3>
  consumer.key: '_<bitbucket_server_consumer_key>__' <4>
EOF
----
+
<1> {prod-short} namespace. The default is {prod-namespace}
<2> Bitbucket Server URL
<3> base64 encoded content of the __<privatepkcs8.pem>__ file without first and last lines.
<4> base64 encoded content of the `__<bitbucket_server_consumer_key>__` file.

. Configure an link:https://confluence.atlassian.com/adminjiraserver/using-applinks-to-link-to-other-applications-938846918.html[Application Link] in Bitbucket to enable the communication from {prod-short} to Bitbucket Server.

.. In Bitbucket Server, click the cog in the top navigation bar to navigate to *Administration*  > *Application Links*.

.. Enter the application URL: `pass:c,a,q[{prod-url}]` and click the btn:[Create new link] button.

.. In the warning message stating `No response was received from the URL`, click the btn:[Continue] button.

.. Fill-in the *Link Applications* form and click the btn:[Continue] button.
+
====
Application Name::  `__<{prod-short}>__`

Application Type:: Generic Application.

Service Provider Name:: `__<{prod-short}>__`

Consumer Key:: Paste the content of the `__<bitbucket_server_consumer_key>__` file.

Shared secret:: Paste the content of the `__<bitbucket_shared_secret>__` file.

Request Token URL:: `__<Bitbucket Server URL>__/plugins/servlet/oauth/request-token`

Access token URL:: `__<Bitbucket Server URL>__/plugins/servlet/oauth/access-token`

Authorize URL:: `__<Bitbucket Server URL>__/plugins/servlet/oauth/access-token`

Create incoming link:: Enabled.
====

.. Fill-in the *Link Applications* form and click the btn:[Continue] button.
+
====
Consumer Key::  Paste the content of the `__<bitbucket_server_consumer_key>__` file.

Consumer name::  `__<{prod-short}>__`

Public Key:: Paste the content of the `__<public-stripped.pub>__` file.
====


.Additional resources

* link:https://bitbucket.org/product/enterprise[Bitbucket Server overview]
* link:https://bitbucket.org/product/download[Download Bitbucket Server]
* link:https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html[Bitbucket Server Personal access tokens]
* link:https://confluence.atlassian.com/jirakb/how-to-generate-public-key-to-application-link-3rd-party-applications-913214098.html[How to generate public key to application link 3rd party applications]
* link:https://confluence.atlassian.com/adminjiraserver/using-applinks-to-link-to-other-applications-938846918.html[Using AppLinks to link to other applications]
* xref:end-user-guide:authenticating-on-scm-server-with-a-personal-access-token.adoc[].
