// caching-images-for-faster-workspace-start

[id="installing-image-puller-using-openshift-templates_{context}"]
= Installing {image-puller-name-short} using OpenShift templates

The {image-puller-name-short} repository contains OpenShift templates for deploying on OpenShift.

.Prerequisites

* A running OpenShift cluster.
* The `oc` tool is available.
* xref:defining-the-list-of-images-to-pull.adoc[].
* xref:defining-the-memory-parameters-for-the-image-puller.adoc[].

.Procedure

. Clone the {image-puller-name} repository:
+
include::example${project-context}-proc_deploying-image-puller-using-openshift-templates_cloning-project.adoc[]

. Configure the OpenShift templates in the `deploy/openshift` directory using following parameters:
+
include::example${project-context}-proc_deploying-image-puller-using-openshift-templates_parameters.adoc[]

. Create an OpenShift project to host the {image-puller-name-short}:
+
include::example${project-context}-proc_deploying-image-puller-using-openshift-templates_prepare.adoc[]

. Process and apply the templates to deploy the puller:
+
include::example${project-context}-proc_deploying-image-puller-using-openshift-templates_process.adoc[]

.Verification steps

. Confirm that a new deployment, `{image-puller-deployment-name}`, and a DaemonSet (named based on the value of the `DAEMONSET_NAME` parameter) exist. The DaemonSet needs to have a Pod for each node in the cluster:
+
[source%nowrap,dummy,subs="+quotes,+attributes"]
----
$ oc get deployment,daemonset,pod --namespace k8s-image-puller
deployment.extensions/{image-puller-deployment-name}   1/1       1            1           2m19s

NAME                                           DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.extensions/{image-puller-deployment-name}   1         1         1         1            1           <none>          2m10s

NAME                                           READY     STATUS    RESTARTS   AGE
pod/{image-puller-deployment-name}-5495f46497-mkd4p   1/1       Running   0          2m18s
pod/{image-puller-deployment-name}-n8bmf              3/3       Running   0          2m10s
----

. Check that the `ConfigMap` named `k8s-image-puller` has the values you specified in your parameter substitution, or that they contain the default values:
+
include::example${project-context}-proc_deploying-image-puller-using-openshift-templates_verify-configmap.adoc[]

