[id="backing-up-a-prod-short-instance-to-a-rest-backup-server-by-prod-cli-with-command-line-options_{context}"]
= Backing up a {prod-short} instance to a REST backup server by {prod-cli} with command-line options

You can use {prod-cli} with command-line options to take a backup snapshot of a {prod-cli} instance and to send the backup snapshot to a configured REST backup server:

.Prerequisites
* Backup repository. See link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html[Preparing a new repository].
* Password set for the backup repository.
+
WARNING: The backup repository password is used to encrypt the backup data. If you lose this password, you will lose the backup data.

.Procedure

. Enter the {prod-cli} command with the following arguments:

[source,shell,subs="+quotes,+attributes"]
----
chectl server:backup \
--repository-url=_<repository_url>_ \ <1>
--repository-password=_<repository_password>_ \ <2>
--username=_<username>_ \ <3>
--password=_<password>_ <4>
----
<1> Backup repository URL as an argument using the `--repository-url` or `-r` option.
<2> Backup repository password as an argument using the `--repository-password` or `-p` option.
<3> When authentication is required, the username for authenticating to the backup REST server as the `--username=_<username>_` argument.
<4> When authentication is required, the password for authenticating to the backup REST server as the `--password=_<password>_` argument.