[id="restoring-a-prod-short-instance-from-a-backup-using-the-checlusterrestore-object_{context}"]
= Restoring a {prod-short} instance from a backup using the CheClusterRestore custom object

You can restore a {prod-short} instance from a backup using custom resouces.

include::snip_warning-backup-snapshots-are-bound-to-specific-cluster.adoc[]

.Prerequisites

* A backup. See xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#creating-a-backup-of-a-prod-short-instance-using-a-checlusterbackup-object_{context}[Creating a backup using a CheClusterBackup object].

.Procedure

. Create the `CheClusterRestore` custom object, which restores a backup:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterRestore
metadata:
  name: {prod-id}-restore
  namespace: {prod-namespace}
spec:
  backupServerConfigRef: backup-server-configuration <1>
  snapshotId: _<snapshot_id>_ <2>
----
<1> Name of the `CheBackupServerConfiguration` object that defines what backup server to use.
<2> Optional parameter defining the Snapshot ID to restore from. The default value is the last snapshot in the backup repository on the backup server.
+
[NOTE]
====
If you intend to reuse a `name` for `CheClusterRestore` custom objects, first make sure to delete any existing custom object with the same `name`. To delete it on the command line, use {orch-cli}:
[source,shell,subs="+attributes,+quotes"]
----
$ {orch-cli} delete CheClusterRestore _<name>_ -n {prod-namespace}
----
====

. Wait until the recovery process ends.
+
If errors occur in your browser after the recovery, clean up the browser data for the {prod-short} domain.

. Read the `status` section of the `CheClusterRestore` object to verify the recovery process:
+
[source,yaml,subs="+attributes"]
----
status:
  message: 'Restore is in progress. Start time: <timestamp>' <1>
  stage: Restoring {prod-short} related cluster objects <2>
  state: InProgress <3>
----
<1> Overall state or error message.
<2> Current phase of the recovery process in a human-readable format.
<3> Recovery process state. One of `InProgress`, `Succeeded`, or `Failed`.
+
//here add the status Succeeded?

. Check that the {prod-short} instance has been recovered.

. Delete the `CheClusterRestore` object.