[id="configuring-{prod-id-short}-with-custom-resources-to-use-amazon-s3_{context}"]
= Configuring {prod-short} with custom resources to use Amazon S3

To configure {prod-short} to use Amazon S3:

.Prerequisites

* Configured Amazon S3. See xref:supported-restic-compatible-backup-servers.adoc[].

.Procedure

. Create a Secret containing the `repo-password` key with a password:
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: backup-encryption-password-secret
  namespace: eclipse-che
type: Opaque
stringData:
  repo-password: __<password>__
----
+
(The {prod-short} Operator will set up this password for the backup repository that the {prod-short} Operator will create from this custom object on the backup server.)
+
include::snip_warning-about-losing-backup-repo-password.adoc[]

. Create a Secret (for example, `name: aws-user-credentials-secret`) containing:
** `awsAccessKeyId` key with the AWS access key ID of the user
** `awsSecretAccessKey` key with the AWS secret access key of the user

. Create the `CheBackupServerConfiguration` custom object:
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: backup-server-configuration
  namespace: {prod-namespace}
spec: <1>
  awss3:
    protocol: https <2>
    hostname: s3.amazonaws.com <3>
    port: 443 <4>
    repositoryPath: {prod-id}-backups <5>
    repositoryPasswordSecretRef: backup-encryption-password-secret <6>
    awsAccessKeySecretRef: aws-user-credentials-secret <7>
----
<1> Must only contain one section (such as `awss3`).
<2> Optional property that specifies the protocol to be used. `https` is the default value; `http` is a permitted value.
<3> Optional property that specifies the S3 hostname. The default value is `s3.amazonaws.com`.
<4> Optional property that specifies the port on which the backup server is running. The default value is `443`.
<5> Name of the bucket resource that stores the backup snapshots. You must manually create the bucket resource before configuring it here.
<6> Secret created in step 1.
<7> Secret created in step 2.

. Optional: To configure multiple backup servers, create a separate `CheBackupServerConfiguration` custom object for each backup server.

include::snip_important-backup-before-update-annotation.adoc[]