[id="proc_defining-the-memory-parameters-for-the-image-puller_{context}"]
= Defining the memory parameters for the {image-puller-name-short}

[role="_abstract"]
Define the memory requests and limits parameters to ensure pulled containers and the platform have enough memory to run.

.Prerequisites

* xref:defining-the-list-of-images-to-pull.adoc[]

.Procedure

. To define the minimal value for `CACHING_MEMORY_REQUEST` or `CACHING_MEMORY_LIMIT`, consider the necessary amount of memory required to run each of the container images to pull.

. To define the maximal value for `CACHING_MEMORY_REQUEST` or `CACHING_MEMORY_LIMIT`, consider the total memory allocated to the DaemonSet Pods in the cluster:
+
----
(memory limit) * (number of images) * (number of nodes in the cluster)
----
+
====
Pulling 5 images on 20 nodes, with a container memory limit of `20Mi` requires `2000Mi` of memory.
====

.Additional resources

ifeval::["{project-context}" == "che"]
* xref:installing-image-puller-on-kubernetes-using-the-operator.adoc[]
endif::[]
* xref:installing-image-puller-on-openshift-using-operatorhub.adoc[]
* xref:installing-image-puller-on-openshift-using-openshift-templates.adoc[]
ifeval::["{project-context}" == "che"]
* xref:installing-image-puller-on-kubernetes-using-helm.adoc[]
endif::[]

