:_content-type: PROCEDURE
:description: Applying an oauth-2 application link Secret for the Bitbucket Server
:keywords: bitbucket, bitbucket-server, application-link, bitbucket-secret
:navtitle: Applying an application link Secret for the Bitbucket Server
// :page-aliases:

[id="applying-an-oauth-2-application-link-secret-for-the-bitbucket-server"]
= Applying an oauth-2 application link Secret for the Bitbucket Server

Prepare and apply the application link Secret for the Bitbucket Server.

.Prerequisites

* The application link is set up on the Bitbucket Server.

* The Base64-encoded values, which were generated when setting up the Bitbucket application link, are prepared:
** Bitbucket Client ID
** Bitbucket Client Secret

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: __<bitbucket_server_url>__ <2>
type: Opaque
data:
  id: __<Base64_Bitbucket_Client_ID>__ <3>
  secret: __<Base64_Bitbucket_Client_Secret>__ <4>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The URL of the Bitbucket Server.
<3> The Base64-encoded *Bitbucket Client ID*.
<4> The Base64-encoded *Bitbucket Client Secret*.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the Secret is created.
