// Used in:
// * administration-guide/building-custom-registry-images/

[id="building-a-custom-devfile-registry-image_{context}"]
= Building a custom devfile registry image

This section describes how to build a custom devfile registry image.
The procedure explains how to add a devfile.
The image contains all sample projects referenced in devfiles.

.Prerequisites

* A running installation of link:http://podman.io[podman] or link:http://docker.io[docker].

* Valid content for the devfile to add. See: xref:end-user-guide:making-a-workspace-portable-using-a-devfile.adoc[].

.Procedure

. Clone the devfile registry repository and check out the version to deploy:
+
include::example$snip_{project-context}-clone-the-devfile-registry-repository.adoc[]

. In the `./{che-devfile-registry-directory}/devfiles/` directory, create a subdirectory `__<devfile-name>__/` and add the `devfile.yaml` and `meta.yaml` files.
+
.File organization for a devfile
====
[subs="+attributes,+quotes"]
----
./{che-devfile-registry-directory}/devfiles/
└── __<devfile-name>__
    ├── devfile.yaml
    └── meta.yaml
----
====

. Add valid content in the `devfile.yaml` file. For a detailed description of the devfile format, see xref:end-user-guide:configuring-a-workspace-using-a-devfile.adoc[].

. Ensure that the `meta.yaml` file conforms to the following structure:
+
.Parameters for a devfile `meta.yaml`
[%header,format=csv,cols="1m,3"]
|===
Attribute, Description
description, Description as it appears on the user dashboard.
displayName, Name as it appears on the user dashboard.
globalMemoryLimit, The sum of the expected memory consumed by all the components launched by the devfile. This number will be visible on the user dashboard. It is informative and is not taken into account by the {prod-short} server.
icon, Link to an `.svg` file that is displayed on the user dashboard.
tags, List of tags. Tags typically include the tools included in the stack.
|===
+
.Example devfile `meta.yaml`
====
[source,yaml]
----
include::example$snip_{project-context}-devfile-meta.adoc[]
----
====

. Build a custom devfile registry image:
+
include::example$snip_{project-context}-build-a-custom-devfile-registry.adoc[]
+
[NOTE]
====
To display full options for the `build.sh` script, use the `--help` parameter.
====

.Additional resources

* xref:end-user-guide:making-a-workspace-portable-using-a-devfile.adoc[].

* xref:running-custom-registries.adoc[].
