[id="restoring-a-{prod-id-short}-instance-from-a-backup-by-snapshot-id_{context}"]
= Restoring a {prod-short} instance from a backup by snapshot ID

To restore a {prod-short} instance from a particular backup snapshot, you can enter the snapshot ID with `{prod-cli}`.

include::snip_warning-backup-snapshots-are-bound-to-specific-cluster.adoc[]

IMPORTANT: If the backup snapshot was taken in an earlier version of Che, add the `--version=__<earlier_version_number>__` option to the `chectl server:restore` command to roll back Che to that earlier version.

.Prerequisites

* Installed `{prod-cli}`.
* Backup snapshot of a {prod-short} instance on any of the following:
** xref:backups-of-che-instances-to-an-sftp-backup-server.adoc[External SFTP backup server]
** xref:backups-of-che-instances-to-amazon-s3.adoc[Amazon S3]
** xref:backups-of-che-instances-to-a-rest-backup-server.adoc[External REST backup server]
** xref:backups-of-che-instances-to-the-internal-backup-server.adoc[Internal backup server]
* Backup snapshot ID, which can be found in:
** Command-line output when creating a backup
** `status` of a `CheClusterBackup` custom object
** Command-line output of the restic command that can link:https://restic.readthedocs.io/en/stable/045_working_with_repos.html[list snapshots in the backup repository]

.Procedure

. Run the `{prod-cli} server:restore` command with the backup snapshot ID specified using the `--snapshot-id=` option:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:restore \
--snapshot-id=_<snapshot-id>_ \ <1>
--repository-url=_<repository-url>_ \ <2>
--repository-password=_<repository-password>_ <3>
----
<1> Specifies the snapshot ID.
<2> For the external backup server: the backup repository URL as an argument using the `--repository-url` or `-r` option. (Omitted when using the internal backup server.)
<3> For the external backup server: the backup repository password as an argument using the `--repository-password` or `-p` option. (Omitted when using the internal backup server.)
+
include::snip_tip-omitting-prod-cli-options-for-server-backup-and-server-restore-onward-when-using-same-backup-server.adoc[]

. When prompted in the output, enter `y` to confirm:
+
[subs="+quotes,+attributes"]
----
...
 ✔ Snapshot:          ...
 Asking for restore confirmation: Do you want to proceed? [y/n]
...
----
+
TIP: To skip this question, add the `--batch` option to the `server:restore` command.