:_module-type: PROCEDURE

[id="enabling-readiness-init-containers-for-olm-installer_{context}"]
= Enabling the readiness init containers for the OLM installer

The readiness init containers are not enabled by default, so to use them you first have to enable them. To enable the readiness init containers for {prod-short} installed by the Operator Lifecycle Manager (OLM) installer:

.Prerequisites

* {prod-short} is installed by the OLM installer.

.Procedure

. Find the {prod-short} Operator subscription name:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get subscriptions -n {prod-namespace}
----

. Find the CSV name in the {prod-short} Operator subscription:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get subscription <subscription-name> -n {prod-namespace} -o yaml | grep installedCSV
----

. Edit the `ClusterServiceVersion` (CSV) YAML manifest:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} edit csv _<csv-name>_ -n {prod-namespace}
----
. Add the following environment variable to the Operator Deployment spec:
+
[source,yaml,subs="+quotes,+attributes"]
----
 - name: ADD_COMPONENT_READINESS_INIT_CONTAINERS
   value: "true"
----

. Wait for the {prod-short} Operator restart to finish. The restarted Operator will then continue with restarting some of its components.

NOTE: Repeat these steps after each {prod-short} upgrade when a new CSV is created by OLM.
