[id="proc_collecting-dev-workspace-operator-metrics-with-prometheus"]
= Collecting {devworkspace} Operator metrics

[role="_abstract"]
To use the in-cluster Prometheus instance to collect, store, and query metrics about the {devworkspace} Operator:

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* An active `oc` session with administrative permissions to the destination OpenShift cluster. See link:https://docs.openshift.com/container-platform/{ocp4-ver}/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI].

* {devworkspace} Operator metrics are enabled. See xref:enabling-and-exposing-{prod-id-short}-metrics[Enabling {devworkspace} Operator metrics].

* Prometheus Operator is installed on the cluster.

.Procedure

. Allow the in-cluster Prometheus instance to detect the ServiceMonitor in the {prod-short} namespace. The default {prod-short} namespace is `{prod-namespace}`.
+
[source,subs="+attributes"]
----
$ oc label namespace {prod-namespace} openshift.io/cluster-monitoring=true
----
+
NOTE: The {prod-short} Operator automatically creates and manages the ServiceMonitor, Role, and RoleBinding resources required for Prometheus to scrape {devworkspace} Operator metrics when metrics are enabled.

.Verification

. Verify that the ServiceMonitor has been created:
+
[source,terminal,subs="+attributes,quotes"]
----
$ oc get servicemonitor -n {prod-namespace}
----
+
.Example output
[source,terminal,subs="+attributes"]
----
NAME                    AGE
devworkspace-controller 5m
----

. For a fresh installation of {prod-short}, generate metrics by creating a {prod-short} workspace from the Dashboard.

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `devworkspace_started_total` and click *Run queries*.
+
For more metrics, see xref:ref_devworkspace-specific-metrics[].

[TIP]
====

To troubleshoot missing metrics:

. Verify the ServiceMonitor, Role, and RoleBinding were created by the {prod-short} Operator:
+
[source,terminal,subs="+attributes,quotes"]
----
$ oc get servicemonitor,role,rolebinding -n {prod-namespace} | grep -E "devworkspace|prometheus"
----

. View the Prometheus container logs for possible RBAC-related errors:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

.Additional resources
* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]
* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]

