[id="configuring-prod-short-to-use-a-rest-backup-server_{context}"]
= Configuring {prod-short} to use a REST backup server

To configure {prod-short} to use a REST backup server:

.Procedure

. Create the `CheBackupServerConfiguration` custom resource object in the {prod-namespace} namespace.
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: backup-server-configuration
spec:
  rest:
    protocol: http                                                 <1>
    hostname: my-domain.net                                        <2>
    port: 1234                                                     <3>
    repositoryPath: {prod-short}-backups                           <4>
    repositoryPasswordSecretRef: backup-encryption-password-secret <5>
    credentialsSecretRef: rest-server-auth-secret                  <6>
----
<1> Optional property that specifies the protocol to be used. The default value is `https` with `http` as the second allowed option.
<2> Backup server hostname.
<3> Optional property that specifies the port on which the backup server is running. The default value is `8000`.
<4> Path on the backup server where the backup snapshots are stored.
<5> Secret name containing a repository password, stored in the `repo-password` field. If the secret contains only one field, its name is arbitrary. The password is used to encrypt and decrypt backup snapshots data.
<6> Optional property that specifies the name of the secret with the REST server user credentials, stored in the `username` and `password` fields.
+
NOTE: The Custom Resource object, stored in the `{prod-namespace}` namespace, must have only one section configured in the `spec` property.

. To configure multiple backup servers, create a separate `CheBackupServerConfiguration` custom resource object for each backup server.