:_content-type: PROCEDURE

[id="importing-extensions-from-the-open-vsx-registry"]
= Importing extensions from the Open VSX Registry

This section describes how to add VS Code extensions from link:https://open-vsx.org/[Open VSX Registry] to {prod-short}'s embedded Open VSX Registry.

.Prerequisites

. The extension should be published on link:https://open-vsx.org/[Open VSX Registry]
. The extension's ID, which is composed of publisher name and extension name, must be known (e.g. `redhat.vscode-xml`).

.Procedure

. Modify `openvsx-sync.json` file in the link:https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/dependencies/che-plugin-registry/openvsx-sync.json[plugin-registry repository] to add an information about the extension:
+
[source,json]
----
    {
        "id": "extension_id"
    }
----
If no `version` is provided, the latest version of the extension from link:https://open-vsx.org/[Open VSX Registry] will be included in the registry. Alternatively, set a `version` to pin to a specific version:
+
[source,json]
----
    {
        "id": "extension_id",
        "version": "extension_version"
    }
----
. To build the plug-in registry container image and publish it to a container registry, run the following commands:
+
[subs="+attributes,+quotes"]
----
$ ./build.sh -o username -r quay.io -t custom
$ {docker-cli} push quay.io/username/che-plugin-registry:custom
----
. Customize an instance of `CheCluster` Custom Resource in the cluster to point the image and save the changes:
+
[source,yaml,subs="+quotes"]
----
spec:
  components:
    pluginRegistry:
      deployment:
        containers:
          - image: quay.io/username/pluginregistry-rhel8:next
      openVSXURL: '' 
----
. Check that `plugin-registry` pod restarted and is running. Restart the workspace and check the available extensions in the Extensions view.
