[id="creating-a-backup-using-an-object_{context}"]
= Creating a backup using an object

To create a backup of {prod-short} using a custom resource object:

include::warning_does-not-back-up-content-of-workspaces.adoc[]

.Prerequisites

* xref:backup-server-setup.adoc[Backup server setup]

* xref:managing-backups-using-custom-resources.adoc#configuring-prod-short-to-use-a-backup-server_{context}[Configuring {prod-short} to use a backup server]

.Procedure

. Create a `CheClusterBackup` backup object to create a backup:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-short}-backup
spec:
  backupServerConfigRef: backup-server-configuration <1>
----
<1> Name of the `CheBackupServerConfiguration` object defining what backup server to use.

. Read the `status` section of the `CheClusterBackup` object to verify the backup process:
+
[source,yaml,subs="+attributes"]
----
status:
  message: 'Backup is in progress. Start time: <timestamp>' <1>
  stage: Collecting {prod-short} installation data          <2>
  state: InProgress                                         <3>
  snapshotId: ba92c7e0                                      <4>
----
<1> Displays the overall state or error message.
<2> Current phase of the backup process in a human-readable format.
<3> Backup process state: `InProgress` or `Succeeded` or `Failed`.
<4> ID of the created backup snapshot. The field appears only when `state` is `Succeeded`.

[NOTE]
====
To reuse the name of an existing backup object for a new backup object, delete the old object:

[subs="+attributes,+quotes"]
----
{orch-cli} delete CheClusterBackup _<name>_ -n {prod-namespace}
----
====