[id="proc_collecting-dev-workspace-operator-metrics-with-prometheus"]
= Collecting {devworkspace} Operator metrics

[role="_abstract"]
The {prod-short} Operator automatically manages the Prometheus resources required to collect {devworkspace} Operator metrics when metrics are enabled.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

.Procedure

. Configure the `CheCluster` Custom Resource to enable {devworkspace} Operator metrics collection. See xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml,subs="+attributes,+quotes"]
----
spec:
  devEnvironments:
    metrics: __<boolean>__ <1>
----
<1> `true` to enable, `false` to disable. Defaults to `true`.

The {prod-short} Operator automatically creates and manages the following resources when `spec.devEnvironments.metrics` is set to `true`:

* A `ServiceMonitor` object named `devworkspace-controller` to scrape metrics from the {devworkspace} Operator
* A `Role` and `RoleBinding` to grant the `prometheus-k8s` service account permission to scrape metrics
* The `openshift.io/cluster-monitoring=true` label on the {prod-short} namespace to enable discovery by the in-cluster Prometheus instance

No manual configuration is required.

.Verification

. For a fresh installation of {prod-short}, generate metrics by creating a {prod-short} workspace from the Dashboard.

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `devworkspace_started_total` and click *Run queries*.
+
For more metrics, see xref:ref_devworkspace-specific-metrics[].

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

.Additional resources
* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]
* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]

