//This module is included in:
//
// assembly_installing-che-on-openshift-4-using-operatorhub

[id="creating-an-instance-of-the-{prod-id-short}-operator_{context}"]
= Creating an instance of the {prod} Operator

Follow this procedure to install {prod} with the default configuration. To modify the configuration, see xref:understanding-the-checluster-custom-resource.adoc[].

.Procedure

// Steps from this procedure are included in administration-guide:proc_using-the-openshift-web-console-to-configure-the-checluster-custom-resource-during-installation.adoc[]. 

. In the left panel, click *Operators*, then click *Installed Operators*.

. On the *Installed Operators* page, click the *{prod}* name.

. On the *Operator details* page, in the *Details* tab, click the *Create instance* link in the *Provided APIs* section.
+
This navigates you to the *Create CheCluster* page, which contains the configuration needed to create a {prod-short} instance, stored in the `CheCluster` Custom Resource.

. Create the *{prod-checluster}* cluster by using the btn:[Create] button at the end of the page using the default values.

. On the *Operator details* page, in the *{prod} Cluster* tab, click the *{prod-checluster}* link.

. Navigate to the *{prod-checluster}* instance using the link displayed under the *{prod} URL* output. 
+
[NOTE]
====
The installation might take more than 5 minutes. The URL appears when the {prod} installation finishes. 
====

.Verification

. To verify the {prod-short} instance has installed correctly, navigate to the *{prod2} Cluster* tab of the *Operator details* page. The *CheClusters* page displays the list of {prod-short} instances and their status.

. Click *{prod-checluster}* `CheCluster` and navigate to the *Details* tab.

. See the content of the following fields:
+
* The *Message* field contains error messages. The expected content is `None`.
* The *{prod} URL* field contains the URL of the {prod} instance. The URL appears when the deployment finishes successfully.

. Navigate to the *Resources* tab. View the list of resources assigned to the {prod-short} deployment and their status.
