[id="configuring-openshift-oauth-with-initial-user_{context}"]
= Configuring OpenShift OAuth with initial user

.Prerequisites

* The `oc` tool is available.
* `{prod-cli}` management tool is available. See xref:installation-guide:using-the-chectl-management-tool.adoc[].

.Procedure

* Configure OpenShift identity providers on the cluster. See the link:https://docs.openshift.com/container-platform/latest/authentication/understanding-identity-provider.html#identity-provider-overview_understanding-identity-provider[Understanding identity provider configuration].
+
====
When a user skips the Configuring step of OpenShift {platforms-identity-provider}, and the OpenShift cluster does not already contain a configured {identity-provider}, {prod-short} creates an initial OpenShift user for the `HTPasswd` identity provider. Credentials of this user are stored in the `openshift-oauth-user-credentials` secret, located in the `openshift-config` namespace.

Obtain the credentials for logging in to an OpenShift cluster and {prod-short} instance:

. Obtain OpenShift user name:
+
[subs="+attributes,+quotes"]
----
$ oc get secret openshift-oauth-user-credentials -n openshift-config -o json | jq -r '.data.user' | base64 -d
----
. Obtain OpenShift user password:
+
[subs="+attributes,+quotes"]
----
$ oc get secret openshift-oauth-user-credentials -n openshift-config -o json | jq -r '.data.password' | base64 -d
----
====
+
* Deploy {prod-short} using xref:installation-guide:installing-che-on-openshift-4-using-operatorhub.adoc[OperatorHub] or the {prod-cli}, see the
link:{link-cli-github}#user-content-{prod-cli}-serverdeploy[`{prod-cli} server:deploy` specification] chapter. OpenShift OAuth will be enabled by default.

