[id="backing-up-a-prod-short-instance-using-the-checlusterbackup-custom-object_{context}"]
= Backing up a {prod-short} instance using the CheClusterBackup custom object

To take a backup snapshot of a {prod-short} instance by using a custom object:

include::snip_warning-does-not-back-up-content-of-workspaces.adoc[]

.Prerequisites

* Configured backup server. See xref:supported-restic-compatible-backup-servers.adoc[].
* Created `CheBackupServerConfiguration` custom object. See
ifeval::[ "{context}" == "backups-of-prod-short-instances-to-a-rest-backup-server"]
???
endif::[]
//* xref:backups-of-prod-short-instances-to-a-rest-backup-server.adoc#configuring-prod-short-with-custom-resources-to-use-a-rest-backup-server_{context}[]
//* xref:backups-of-prod-short-instances-to-an-amazon-s3-backup-server.adoc#configuring-prod-short-with-custom-resources-to-use-an-amazon-s3-backup-server_{context}[]
//* xref:backups-of-prod-short-instances-to-an-sftp-backup-server.adoc#configuring-prod-short-with-custom-resources-to-use-an-sftp-backup-server_{context}[]

.Procedure

. Create the `CheClusterBackup` custom object to create a backup snapshot:
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-id}-backup
spec:
  backupServerConfigRef: backup-server-configuration <1>
  useInternalBackupServer: false <2>
----
<1> Name of the `CheBackupServerConfiguration` object defining what backup server to use.
<2> Configures the custom resource to back up to an external backup server.

. Read the `status` section of the `CheClusterBackup` object to verify the backup process:
+
[source,yaml,subs="+quotes,+attributes"]
----
status:
  message: 'Backup is in progress. Start time: <timestamp>' <1>
  stage: Collecting {prod-short} installation data <2>
  state: InProgress <3>
  snapshotId: ba92c7e0 <4>
----
<1> Displays the overall state or error message.
<2> Current phase of the backup process in a human-readable format.
<3> Backup process state: `InProgress` or `Succeeded` or `Failed`.
<4> ID of the created backup snapshot. The field appears only when `state` is `Succeeded`.

[NOTE]
====
To reuse the name of an existing backup object for a new backup object, delete the old object:

[source,shell,subs="+attributes,+quotes"]
----
{orch-cli} delete CheClusterBackup _<name>_ -n {prod-namespace}
----
====