//The misleading thing are title and intro sentence: they say 'configure', but the command does a backup! mykola

[id="configuring-prod-cli-with-environment-variables-to-use-a-rest-backup-server_{context}"]
= Configuring {prod-cli} with environment variables to use a REST backup server

As an alternative to using command-line options for `{prod-cli} server:backup`, you can configure {prod-cli} for a REST backup server with environment variables that will allow you to run `{prod-cli} server:backup` without having to enter those arguments as options:

.Prerequisites
* Configured backup server. See xref:supported-restic-compatible-backup-servers.adoc[].

.Procedure

* Set the following environment variables:
** `BACKUP_REPOSITORY_URL` for the backup repository.
** `BACKUP_REPOSITORY_PASSWORD` for the backup repository password.
** When authentication is required, `REST_SERVER_USERNAME` for the username for authenticating to the backup REST server.
** When authentication is required, `REST_SERVER_PASSWORD` for the password for authenticating to the backup REST server.