[id="proc_collecting-dev-workspace-operator-metrics-with-prometheus"]
= Collecting {devworkspace} Operator metrics

[role="_abstract"]
The {prod-short} Operator automatically manages Prometheus resources to enable metric collection for the {devworkspace} Operator.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* An active `oc` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* The `devworkspace-controller-metrics` Service is exposing metrics on port `8443`. This is preconfigured by default.

.Procedure

. Enable {devworkspace} Operator metrics collection by configuring the `CheCluster` Custom Resource:
+
[source,shell,subs="+quotes,+attributes,+macros"]
----
{orch-cli} patch checluster {prod-checluster} \
  --namespace {prod-namespace} \
  --type merge \
  --patch '{
    "spec": {
      "devEnvironments": {
        "metrics": true <1>
      }
    }
  }'
----
<1> Set to `true` to enable metrics collection (default), or `false` to disable.
+
When `spec.devEnvironments.metrics` is set to `true`, the {prod-short} Operator automatically creates and manages the following resources:
+
* A `ServiceMonitor` resource named `devworkspace-controller` that configures Prometheus to scrape metrics from the {devworkspace} Operator
* A `Role` and `RoleBinding` that grant the `prometheus-k8s` service account permission to access the metrics endpoints
* The `openshift.io/cluster-monitoring=true` label on the {prod-short} namespace to enable the in-cluster Prometheus instance to discover the `ServiceMonitor`
+
NOTE: These resources are managed by the {prod-short} Operator. Manual modifications to these resources will be overwritten during reconciliation.

.Verification

. For a fresh installation of {prod-short}, generate metrics by creating a {prod-short} workspace from the Dashboard.

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `devworkspace_started_total` and click *Run queries*.
+
For more metrics, see xref:ref_devworkspace-specific-metrics[].

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

.Additional resources
* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]
* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]

