// configuring-bitbucket-servers
 
[id="configuring_bitbucket_servers_{context}"]
= Configuring Bitbucket servers
 
You can use the Bitbucket (BB) server as a project source supplier in {prod-short}}. To do so, configure the related CheCluster Custom Resource (CR) and {prod-short} instance devfile.

The following chapter describes configuring BB for use with public repositories, where the use of additional certificates, such as TLS, may be required. This includes the following processes:

* Creating a new ConfigMap for additional TLS and `gitSelfSign` certificates. This enables:

** Launching a factory using a devfile URL.
** Importing and cloning a project.

* Registering the BB server URL with {prod-short} server using the CR `CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS` property.

[NOTE]
====
For the use of BB with private repositories:
Configure CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS
Configure the OAuth 1 authentication on BB server side
====

 
.Prerequisites

* A value of the BB server certification authority (CA), which is exported in the Base64 ASCII format and stored in a file named `ca.crt`.
* An instance of {prod-short}
 
.Procedure
 
. Provision the CA of the BB server to the {prod-short} server to enable {prod-short} server to read the devfiles stored in the BB server. To do so, add the following ConfigMap to the `{prod-namespace}` {orch-namespace}:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} create configmap bitbucket-ca-cert-for-factory --from-file=ca.crt -n {prod-namespace}
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} label configmap bitbucket-ca-cert-for-factory app.kubernetes.io/part-of=che.eclipse.org app.kubernetes.io/component=ca-bundle -n {prod-namespace}
----
 
. Provision the CA of the BB server to the {prod-short} server for Git operations. To do so, add a new ConfigMap to the `{prod-namespace}` {orch-namespace}:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} create configmap bitbucket-ca-for-git --from-file=ca.crt --from-literal=githost=__<bitbucket_server_url>__ -n {prod-namespace}
----
 
. Edit the CheCluster Custom Resource (CR) to configure the {prod-short} server. 
+
[source,yaml,subs="+attributes"]
----
spec:
  server:
    # …
    gitSelfSignedCert: __<boolean>__ <1>
    customCheProperties:
      CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS:  "__<bitbucket_server_url>__" <2>
----
<1> `true`: if BB is using a self-signed cert. Default value: `false`.
<2> BB server URL is an HTTPS resource.
+
* Example: `CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS: "https://bitbucket-bitbucket.apps.ocp48-aws.crw-qe.com/"``
+
* See xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc[].
 
 
.Reference
 
* For adding a Bitbucket CA certificate into {prod-short}, see *xref:installation-guide:importing-untrusted-tls-certificates.adoc[].

