[id="backing-up-a-prod-short-instance-to-the-internal-server-using-a-checlusterbackup-object_{context}"]
= Backing up a {prod-short} instance to the internal server using a CheClusterBackup object

//issues: object vs custom resource? max-cx

When creating a custom resource to back up a {prod-short} instance to the internal backup server, as described in the following procedure, {prod-short} Operator configures the internal backup server.
//issues:{prod-short} Operator configures the internal backup server or {prod-short} or both? ask Mykola. max-cx

WARNING: Configuring a backup server inside the same cluster, for example the internal backup server, is not recommended for a production environment.

.Procedure

. Create a custom resource to send a backup snapshot to the internal backup server:
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-id}-backup
  namespace: {prod-namespace}
spec:
  useInternalBackupServer: true <1>
----
<1> Configures the `CheClusterBackup` object to back up to the internal backup server.

. Read the `status` section of the `CheClusterBackup` object to verify the backup process:
+
[source,yaml,subs="+quotes,+attributes"] 
----
...
status:
  message: 'Backup is in progress. Start time: <timestamp>' <1>
  stage: Collecting {prod-short} installation data <2>
  state: InProgress <3>
...
----
<1> Displays the overall state or error message.
<2> Current phase of the backup process in a human-readable format.
<3> Backup process state: `InProgress` or `Succeeded` or `Failed`.
+
[source,yaml,subs="+quotes,+attributes"] 
----
...
status:
  cheVersion: 7.37.0 <1>
  message: >- <2>
    Backup successfully finished at 2021-10-07 11:18:28.116103737 +0000 UTC
    m=+2384.430366711
  snapshotId: 40a09756 <3>
  state: Succeeded <4>
...
----
<1> The version of {prod-short} from which the backup snapshot was created. This field appears only when `state` is `Succeeded`.
<2> Displays the overall state or error message.
<3> The ID of the created backup snapshot. This field appears only when `state` is `Succeeded`.
<4> Backup process state: `InProgress` or `Succeeded` or `Failed`.


