1[id="creating-a-new-backup-using-the-internal-backup-server"]
= Creating a new backup using the internal backup server

To use the internal backup server, request automatic configuration from {prod-short} Operator.
//"The preparation described above is not required."???

WARNING: This procedure does not back up the content of users' workspaces. To back up the content of users' workspaces, see xref:managing-backups-of-persistent-volumes.adoc[Managing backups of persistent volumes].

NOTE: Configuring a backup server inside the same cluster, as described in this procedure, is not recommended for production use. See the recommended procedure: xref:proc_creating-a-new-backup-using-an-object.adoc[Creating a new backup using an object].

//CHECK WITH SME IF THESE PREREQS ARE NOT REQUIRED
.Prerequisites
* xref:setup-backup-server.adoc[A backup server is set up].

* xref:define-backup-server-for-operator.adoc[{prod-short} Operator is configured to use the backup server].

.Procedure

* Configure the automatic setup and sending of the backup to the internal backup server:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-short}-backup
spec:
  useInternalBackupServer: true
----