// deploying-the-registries

[id="deploying-registries-in-openshift_{context}"]
= Deploying registries in OpenShift

.Procedure

An OpenShift template to deploy the plug-in registry is available in the `deploy/openshift/` directory of the GitHub repository.

. To deploy the plug-in registry using the OpenShift template, run the following command:
+
[subs="+quotes"]
----
NAMESPACE=__<namespace-name>__  <1>
IMAGE_NAME="my-plug-in-registry"
IMAGE_TAG="latest"
oc new-app -f openshift/che-plugin-registry.yml \
 -n "$\{NAMESPACE}" \
 -p IMAGE="$\{IMAGE_NAME}" \
 -p IMAGE_TAG="$\{IMAGE_TAG}" \
 -p PULL_POLICY="Always"
----
<1> If installed using {prod-cli}, the default {prod-short} {orch-namespace} is `{prod-namespace}`. The OperatorHub installation method deploys {prod-short} to the users current {orch-namespace}.

. The devfile registry has an OpenShift template in the `deploy/openshift/` directory of the GitHub repository. To deploy it, run the command:
+
[subs="+quotes"]
----
NAMESPACE=__<namespace-name>__  <1>
IMAGE_NAME="my-devfile-registry"
IMAGE_TAG="latest"
oc new-app -f openshift/che-devfile-registry.yml \
 -n "$\{NAMESPACE}" \
 -p IMAGE="$\{IMAGE_NAME}" \
 -p IMAGE_TAG="$\{IMAGE_TAG}" \
 -p PULL_POLICY="Always"
----
<1> If installed using {prod-cli}, the default {prod-short} {orch-namespace} is `{prod-namespace}`. The OperatorHub installation method deploys {prod-short} to the users current {orch-namespace}.

:platform-routing: route
:registry-routing-name: plugin-registry
:platform-routing-host-path: .spec.host

include::partial$proc_verification-custom-registries.adoc[]
