// monitoring-{prod-id-short}

[id="collecting-{prod-id-short}-metrics-with-prometheus"]
= Collecting {prod-short} Server metrics with Prometheus

To use the in-cluster Prometheus instance to collect, store, and query JVM metrics for {prod-short} Server:

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* {prod-short} is exposing metrics on port `8087`. See xref:enabling-and-exposing-{prod-id-short}-metrics[Enabling and exposing {prod-short} server JVM metrics].

.Procedure

The {prod-operator} automatically creates the following resources when metrics are enabled:

* A `ServiceMonitor` resource named `{prod-host}` for detecting the {prod-short} JVM metrics Service
* A `Role` and `RoleBinding` granting the `prometheus-k8s` service account permission to scrape metrics endpoints in the {prod-namespace} namespace

To complete the monitoring configuration:

. Allow the in-cluster Prometheus instance to detect the ServiceMonitor in the {prod-short} namespace. The default {prod-short} namespace is `{prod-namespace}`.
+
[source,terminal,subs="+attributes,quotes"]
----
$ {orch-cli} label namespace {prod-namespace} openshift.io/cluster-monitoring=true
----

.Verification

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `process_uptime_seconds{job="che-host"}` and click *Run queries*.

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

[role="_additional-resources"]
.Additional resources


* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]

* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]
