// monitoring-{prod-id-short}

[id="collecting-{prod-id-short}-metrics-with-prometheus"]
= Collecting {prod-short} Server metrics with Prometheus

The {prod-short} Operator automatically configures Prometheus monitoring when {prod-short} Server metrics are enabled. The operator creates a ServiceMonitor, RBAC resources, and applies the necessary namespace labels for the in-cluster Prometheus instance to collect, store, and query JVM metrics.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* {prod-short} is exposing metrics on port `8087`. See xref:enabling-and-exposing-{prod-id-short}-metrics[Enabling and exposing {prod-short} server JVM metrics].

.Procedure

. Verify that metrics are enabled in the `CheCluster` Custom Resource:
+
[source,yaml,subs="+attributes,+quotes"]
----
spec:
  components:
    metrics:
      enable: true
----
+
The {prod-short} Operator automatically creates the following resources in the `{prod-namespace}` namespace:
+
* ServiceMonitor named `{prod-host}` for scraping {prod-short} Server metrics
* Role named `{prod-id-short}-prometheus` granting permissions to read services, endpoints, and pods
* RoleBinding named `{prod-id-short}-prometheus` binding the `prometheus-k8s` service account from the `openshift-monitoring` namespace
* Namespace label `openshift.io/cluster-monitoring=true` to enable cluster monitoring

.Verification

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `process_uptime_seconds{job="che-host"}` and click *Run queries*.

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

[role="_additional-resources"]
.Additional resources


* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]

* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]
