[id="removing-user-data_{context}"]
= Removing user data

== Removing user data according to GDPR

The General Data Protection Regulation (link:https://en.wikipedia.org/wiki/General_Data_Protection_Regulation[GDPR]) law enforces the right for individuals to have personal data erased.

The following procedure describes how to remove a user’s data from a cluster and the {identity-provider} database.

[NOTE]
====
The following commands use the default {platforms-namespace}, `{prod-namespace}`, as a user's example for the `-n` option.
====

.Prerequisites

* A user or an administrator authorization token. To delete any other data except the data bound to a user account, `admin` privileges are required. The `admin` is a special {prod-short} administrator account pre-created and enabled using the `pass:[CHE_SYSTEM_ADMIN__NAME]` and `pass:[CHE_SYSTEM_SUPER__PRIVILEGED__MODE = true]` Custom Resource definitions.
+
[subs="+quotes,macros"]
----
spec:
 server:
   customCheProperties:
     pass:[CHE_SYSTEM_SUPER__PRIVILEGED__MODE]: 'true'
     pass:[CHE_SYSTEM_ADMIN__NAME]: '__<admin-name>__'
----
+
If needed, use commands below for creating the `admin` user:
+
[subs="+quotes,macros,attributes"]
----
$ {orch-cli} patch checluster/{prod-checluster} \
  --type merge \
  -p '{ "spec": { "server": {"customCheProperties": {"pass:[CHE_SYSTEM_SUPER__PRIVILEGED__MODE]": "true"} } }}' \
  -n __{prod-namespace}__
----
+
[subs="+quotes,macros,attributes"]
----
$ {orch-cli} patch checluster/{prod-checluster} \
  --type merge \
  -p '{ "spec": { "server": {"customCheProperties": {"pass:[CHE_SYSTEM_ADMIN__NAME]": "__<admin-name>__"} } }}' \
  -n __{prod-namespace}__
----
+
[NOTE]
====
All system permissions are granted to the administrative user who is configured in the `CHE_SYSTEM_ADMIN__NAME` property (the default is `admin`). The system permissions are granted when the {prod-short} server starts. If the user record is not in the {prod-short} user database, it happens after the first user’s login.

.Authorization token privileges:

* `admin` - Can delete all personal data of all users
* `user` - Can delete only the data related to the user
====

* A user or an administrator is logged in the OpenShift cluster with deployed {prod-short}.

* A user ID is obtained. Get the user ID using the commands below:

** For the current user:
+
[subs="+quotes,macros,attributes"]
----
$ curl -X GET \
  --header 'Authorization: Bearer __<user-token>__' \
  'pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user'
----
 
** To find a user by name: 
+
[subs="+quotes,macros,attributes"]
----
$ curl -X GET \
  --header 'Authorization: Bearer __<user-token>__' \
  'pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/find?name=__<username>__'
----
 
** To find a user by email: 
+
[subs="+quotes,macros,attributes"]
----
$ curl -X GET \
  --header 'Authorization: Bearer __<user-token>__' \
  'pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/find?email=__<email>__'
----
+
.Example of obtaining a user ID
+
This example uses `vparfono` as a local user name.
+
====
[subs="+quotes,macros,attributes"]
----
$ curl -X GET \
  --header 'Authorization: Bearer __<user-token>__' \
  'https://che-vp-che.apps.che-dev.x6e0.p1.openshiftapps.com/api/user/find?name=vparfono'
----

The user ID is at the bottom of the curl command output.

[source,json]
----
{
 "name": "vparfono",
 "links": [
   {
.
.
.
   }
 ],
 "email": "vparfono@redhat.com",
 "id": "921b6f33-2657-407e-93a6-fb14cf2329ce"
}
----
====

.Procedure

. Update the `{prod-checluster}` `CheCluster Custom` Resource (CR) definition to permit the removal of a user’s data from the {identity-provider} database:
+
[subs="+quotes,macros,attributes"]
----
$ {orch-cli} patch checluster/{prod-checluster} \
  --patch "{\"spec\":{\"server\":{\"customCheProperties\": {\"pass:[CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED]\": \"true\"}}}}" \
  --type=merge -n _{prod-namespace}_
----

. Remove the data using the API:
+
[subs="+quotes,macros,attributes"]
----
$ curl -i -X DELETE \
  --header 'Authorization: Bearer __<user-token>__' \
  pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/__<user-id>__
----


.Verification

Running the following command returns code `204` as the API response:

[subs="+quotes,macros,attributes"]
----
$ curl -i -X DELETE \
  --header 'Authorization: Bearer __<user-token>__' \
  pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/__<user-id>__
----


.Additional resources

To remove the data of all users, follow the instructions for xref:installation-guide:uninstalling-che.adoc[].
