[id="pointing-prod-cli-to-the-configuration-object-using-a-command-line-argument_{context}"]
= Pointing {prod-cli} to the configuration object using a command-line argument

To point {prod-cli} to the backup server configuration object using a command-line argument:

.Procedure

* Enter the following command:

[source,shell,subs="+quotes,+attributes"]
----
SOMETHINGCOMMAND --backup-server-config-name SOMETHINGARGUMENT
----

`chectl server:backup` command from
proc_backing-up-a-che-instance-to-an-sftp-backup-server-by-prod-cli-with-command-line-options.adoc
proc_backing-up-a-che-instance-to-amazon-s3-by-prod-cli-with-command-line-options.adoc
proc_backing-up-a-che-instance-to-a-rest-backup-server-by-prod-cli-with-command-line-options.adoc
&
ORIGINAL TEXT:
====
It is possible to point directly to the backup server configuration object using `--backup-server-config-name` parameter or `BACKUP_SERVER_CONFIG_NAME` environment variable.
In such a case, all the configuration above is not needed. For more details, see xref:managing-backups-using-custom-resources.adoc[]
====