[id=configuring-prod-short-with-custom-resources-to-use-the-internal-backup-server_{context}"]
= Configuring {prod-short} with custom resources to use the internal backup server

To configure {prod-short} to use a REST backup server:

.Prerequisites
* `CheClusterBackup` custom resource. See xref:backing-up-prod-short-instances-using-a-rest-backup-server.adoc#creating-a-backup-of-a-prod-short-instance-using-a-checlusterbackup-object_{context}[Creating a backup of a Che instance using a CheClusterBackup object].

.Procedure

. Add `useInternalBackupServer: true` to the `spec` section of the `CheClusterBackup` custom resource object used to create a backup snapshot:
+
[source,yaml,subs="+quotes,+attributes"]
----
...
spec:
  useInternalBackupServer: true
...
----

WHAT DO TO ABOUT THE FOLLOWING INFO?

NOTE: The Custom Resource object, stored in the `{prod-namespace}` namespace, must have only one section configured in the `spec` property.

. To configure multiple backup servers, create a separate `CheBackupServerConfiguration` custom resource object for each backup server.