[id="configuring-prod-short-with-custom-resources-to-use-a-rest-backup-server_{context}"]
= Configuring {prod-short} with custom resources to use a REST backup server

To configure {prod-short} to use a REST backup server:

.Prerequisites

* Configured external backup server. See xref:supported-restic-compatible-backup-servers.adoc[].
* Created backup repository. See link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html[Preparing a new repository].
* Created backup repository password. See link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html[Preparing a new repository].

.Procedure

. Create a secret with the name `backup-encryption-password-secret` containing the `repo-password` key with the backup repository password as the value.

. Create a secret with the name `rest-server-auth-secret` containing the `username` and `password` keys for the REST server user credentials.
+
NOTE: Skip this step if not using the REST server user credentials.

. Create the `CheBackupServerConfiguration` custom object in the {prod-namespace} namespace.
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: backup-server-configuration
spec:
  rest:
    protocol: https <1>
    hostname: my-domain.net <2>
    port: 1234 <3>
    repositoryPath: {prod-id}-backups <4>
    repositoryPasswordSecretRef: backup-encryption-password-secret <5>
    credentialsSecretRef: rest-server-auth-secret <6>
----
<1> Optional property that specifies the protocol to be used: `https` is the default value; `http` is a permitted value.
<2> Backup server hostname.
<3> Optional property that specifies the port on which the backup server is running. The default value is `8000`.
<4> Path on the backup server where the backup snapshots are stored.
<5> The secret created in step 1.
<6> The secret created in step 2.
+
NOTE: The custom object, stored in the `{prod-namespace}` namespace, must have only one section configured in the `spec` property.

. To configure multiple backup servers, create a separate `CheBackupServerConfiguration` custom object for each backup server.