[id="proc_collecting-dev-workspace-operator-metrics-with-prometheus"]
= Collecting {devworkspace} Operator metrics

[role="_abstract"]
To use the in-cluster Prometheus instance to collect, store, and query metrics about the {devworkspace} Operator:

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* An active `oc` session with administrative permissions to the destination OpenShift cluster. See link:https://docs.openshift.com/container-platform/{ocp4-ver}/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI].

* The `devworkspace-controller-metrics` Service is exposing metrics on port `8443`. This is preconfigured by default.

.Procedure

The {prod-short} Operator automatically creates the following resources when metrics are enabled:

* A `ServiceMonitor` named `devworkspace-controller` that detects the {devworkspace} Operator metrics Service
* A `Role` named `{prod-id-short}-prometheus` that grants permissions to access services, endpoints, and pods in the `openshift-operators` namespace
* A `RoleBinding` named `{prod-id-short}-prometheus` that binds the `prometheus-k8s` ServiceAccount from the `openshift-monitoring` namespace to the Role
* The `openshift.io/cluster-monitoring: "true"` label on the {prod-short} namespace to enable the in-cluster Prometheus instance to detect the ServiceMonitor

No manual configuration is required. The Prometheus resources are managed automatically by the {prod-short} Operator and will be removed when the `CheCluster` is deleted.

.Verification

. For a fresh installation of {prod-short}, generate metrics by creating a {prod-short} workspace from the Dashboard.

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `devworkspace_started_total` and click *Run queries*.
+
For more metrics, see xref:ref_devworkspace-specific-metrics[].

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

.Additional resources
* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]
* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]

