
////
note from Max: this applies only to org repositories, which means users who have their own (GH/GL) forks already won't use it, but we need to investigate the git process for cloning a repository and its UX impact of starting a workspace with a cloned project repo and then forking it and setting up a remote (GH/GL) origin of the user.
////

////
ifeval::["{project-context}" == "che"]
include::partial$proc_using-a-badge-to-link-to-workspaces.adoc[leveloffset=+1]
endif::[]
////

[id="including-the-workspace-creating-badge-in-a-readme_{context}"]
= Including the workspace-greating badge in a README

.Procedure

. To open a workspace in your {prod-short} installation, substitute your URL and repository:
+
----
[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://your-che-host.com/f?url=https://your-repository-url)
----

. Add the link to your repository in the project `README` file.

.Example: Using link:https://workspaces.openshift.com[workspaces.openshift.com] as the {prod-short} host and a GitHub repository

The following snippet creates a badge that opens a developer workspace of the repository at `+https://github.com/org/repository+` in link:https://workspaces.openshift.com/[workspaces.openshift.com]:
----
[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://workspaces.openshift.com/f?url=https://github.com/org/repository)
----

.Additional resources

* THERE IS A FOLLOW-ON PROCEDURE OR CONCEPT MODULE IN THE USER GUIDE