// monitoring-{prod-id-short}

[id="collecting-{prod-id-short}-metrics-with-prometheus"]
= Collecting {prod-short} Server metrics with Prometheus

The {prod-short} Operator automatically configures the in-cluster Prometheus instance to collect, store, and query JVM metrics for {prod-short} Server when metrics are enabled.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* {prod-short} metrics are enabled. See xref:enabling-and-exposing-{prod-id-short}-metrics[Enabling and exposing {prod-short} server JVM metrics].

.Automatic configuration

When {prod-short} Server metrics are enabled via `spec.components.metrics.enable: true`, the {prod-short} Operator automatically creates and manages the following resources:

* A `ServiceMonitor` custom resource named `che-host` that monitors the {prod-short} Server metrics endpoint on port `8087`
* A `Role` and `RoleBinding` that grant the `prometheus-k8s` service account permission to scrape metrics from the {prod-short} namespace
* The `openshift.io/cluster-monitoring: "true"` label on the {prod-short} namespace to enable OpenShift cluster monitoring

These resources are automatically updated or recreated if modified or deleted, ensuring continuous metrics collection.

.Verification

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `process_uptime_seconds{job="che-host"}` and click *Run queries*.

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

[role="_additional-resources"]
.Additional resources


* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]

* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]
