[id="configuring-prod-short-with-custom-resources-to-use-an-sftp-backup-server_{context}"]
= Configuring {prod-short} with custom resources to use an SFTP backup server

To configure {prod-short} to use an SFTP backup server:

.Prerequisites

* Configured external backup server. See xref:supported-restic-compatible-backup-servers.adoc[]
* Created backup repository. See link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html[Preparing a new repository].
* Created backup repository password. See link:https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html[Preparing a new repository].

.Procedure

. Create a secret with the name `backup-encryption-password-secret` containing the `repo-password` key with the backup repository password as the value.

. Create a secret with the name `ssh-key-secret` containing the `ssh-privatekey` key with a private SSH key for logging in to the SFTP server without a password.

. Create the `CheBackupServerConfiguration` custom object in the {prod-namespace} namespace.
+
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheBackupServerConfiguration
metadata:
  name: backup-server-configuration
spec:
  awss3:
    username: user <1>
    hostname: my-domain.net <2>
    port: 1234 <3>
    repositoryPath: {prod-id}-backups <4>
    repositoryPasswordSecretRef: backup-encryption-password-secret <5>
    sshKeySecretRef: ssh-key-secret <6>
----
<1> User name on the remote server to login with using the SSH protocol.
<2> Remote server hostname.
<3> Optional property that specifies the port on which an SFTP server is running. The default value is `22`.
<4> Absolute or relative path on the server where backup snapshots are stored.
<5> The secret created in step 1.
<6> The secret created in step 2.
+
NOTE: The custom object, stored in the `{prod-namespace}` namespace, must have only one section configured in the `spec` property.

. To configure multiple backup servers, create a separate `CheBackupServerConfiguration` custom object for each backup server.