[id="installing-image-puller-using-che-operator_{context}"]
= Installing {image-puller-name-short} using the {prod-short} Operator

This section describes how to use the {prod-short} Operator to install the {image-puller-name-short}. This is a Community-supported technology preview feature.

.Prerequisites

* xref:defining-the-list-of-images-to-pull.adoc[]

* xref:defining-the-memory-parameters-for-the-image-puller.adoc[]

include::example$snip_{project-context}-installing-image-puller-using-che-operator-prerequisites.adoc[]

* The {prod-short} Operator is available. See xref:installation-guide:installing-che-on-openshift-4-using-operatorhub.adoc[]

.Procedure

. Edit the `CheCluster` Custom Resource and set `.spec.imagePuller.enable` to `true`
+
.Enabling {image-puller-name-short} in the `CheCluster` Custom Resource 
====
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: {prod-checluster}
spec:
  # ...
  imagePuller:
    enable: true
----
====
+
[NOTE]
.Uninstalling {image-puller-name-short} using {prod-short} Operator
====
* Edit the `CheCluster` Custom Resource and set `.spec.imagePuller.enable` to `false`.
====

. Edit the `CheCluster` Custom Resource and set the `.spec.imagePuller.spec` to configure the optional {image-puller-name-short} parameters for the {prod-short} Operator.
+
.Configuring {image-puller-name-short} in the `CheCluster` Custom Resource 
====
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: {prod-checluster}
spec:
  ...
  imagePuller:
    enable: true
    spec:
        configMapName: __<{image-puller-deployment-name}>__
        daemonsetName: __<{image-puller-deployment-name}>__
        deploymentName: __<{image-puller-deployment-name}>__
        images: {image-puller-images}
----
====

include::example$snip_{project-context}-image-puller-dockerfile.adoc[]


.Verification steps

. {platforms-name} creates a `{image-puller-operator-id}` Subscription.

. The `eclipse-che namespace` contains a `{image-puller-operator-name}` `ClusterServiceVersion`:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get clusterserviceversions
----

. The `eclipse-che namespace` contains these deployments: `{image-puller-deployment-name}` and `{image-puller-deployment-id}`.
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get deployments
----

. The {image-puller-operator-name} creates a `{image-puller-cr-name}` Custom Resource:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get kubernetesimagepullers
----
