:_content-type: PROCEDURE
:description: Applying the GitHub OAuth App Secret
:keywords: applying-the-github-oauth-app-secret, apply-the-github-oauth-app-secret, apply-github-oauth-app-secret, apply-secret, applying-secret, apply-a-secret, applying-a-secret
:navtitle: Applying the GitHub OAuth App Secret
// :page-aliases:

[id="applying-the-github-oauth-app-secret_{context}"]
= Applying the GitHub OAuth App Secret

Enable the users of your {prod-short} instance to access a private Git repository that is hosted on GitHub:

.Prerequisites
* xref:user-guide:setting-up-the-github-oauth-app.adoc[] has been completed.
* The values that were generated when xref:user-guide:setting-up-the-github-oauth-app.adoc[]:
** *GitHub OAuth Client ID*
** *GitHub OAuth Client Secret*
* `{orch-cli}` is installed in the operating system you are using.
////
{orch-cli}=oc
https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
////

.Procedure

. Prepare the secret as follows:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
type: Opaque
data:
  id: __<base64_github_oauth_client_id>__ <2>
  secret: __<base_github_oath_client_secret>__ <3>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The GitHub OAuth Client ID that you encoded to Base64 in step 1.
<3> The GitHub OAuth Client Secret that you encoded to Base64 in step 2.

. Apply the secret by entering it with `{orch-cli}` on a command line:
+
[source,subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the secret is created.