[id="defining-the-list-of-images-to-pull_{context}"]
= Defining the list of images to pull

The {image-puller-name-short} can pre-pull most images, including scratch images, which are the images with the included sleep command. However, due to limited support, it is not recommended to pre-pull the container images that mount volumes in their Dockerfile.

.Prerequisites

* The `curl` tool is available. See link:https://curl.se/[curl homepage].
* The `jq` tool is available. See link:https://stedolan.github.io/jq/[jq homepage].
* The `yq` tool is available. See link:https://pypi.org/project/yq/[yq homepage].

.Procedure

. Gather a list of relevant container images depending on the platform.
+
include::example$snip_{project-context}-getting-the-list-of-relevant-images.adoc[]


. Determine images from the list for pre-pulling. For faster workspace startup times, workspace-related images such as
che-theia, che-machine-exec, che-plugin-artifacts-broker, and che-plugin-metadata-broker should be considered for pre-pulling.

.Additional resources

pass:[<!-- vale CheDocs.Attributes = NO -->]

* xref:defining-the-memory-parameters-for-the-image-puller.adoc[].
ifeval::["{project-context}" == "che"]
* xref:installing-image-puller-on-kubernetes-using-the-image-puller-operator.adoc[]
endif::[]
* xref:installing-image-puller-on-openshift-using-operatorhub.adoc[]
* xref:installing-image-puller-on-openshift-using-openshift-templates.adoc[]
ifeval::["{project-context}" == "che"]
* xref:installing-image-puller-on-kubernetes-using-helm.adoc[]
endif::[]

pass:[<!-- vale CheDocs.Attributes = YES -->]
