[id="restoring-a-{prod-id-short}-instance-by-using-{prod-cli}-and-a-checluserbackup-custom-object_{context}"]
= Restoring a {prod-short} instance by using {prod-cli} and a CheClusterBackup custom object

You can restore a {prod-short} instance by entering the name of the `CheClusterBackup` custom object as an argument with the `{prod-cli} server:restore` command:

IMPORTANT: If the backup snapshot was taken in an earlier version of Che, then `chectl server:restore --backup-cr-name=__<name_of_custom_object>__` rolls back Che to that earlier version, which is specified in the `CheClusterBackup` custom object.

.Prerequisites
* Installed `{prod-cli}`.
* The `CheClusterBackup` custom object that was used to create the backup snapshot.
* The backup snapshot that was taken using the `CheClusterBackup` custom object and stored on any of the following:
** xref:backups-of-che-instances-to-an-sftp-backup-server.adoc#backing-up-a-che-instance-using-the-checlusterbackup-custom-object_{context}[SFTP backup server]
** xref:backups-of-che-instances-to-amazon-s3.adoc#backing-up-a-che-instance-using-the-checlusterbackup-custom-object_{context}[Amazon S3 or S3 API compatible backup server]
** xref:backups-of-che-instances-to-a-rest-backup-server.adoc#backing-up-a-che-instance-using-the-checlusterbackup-custom-object_{context}[REST backup server]
** xref:backups-of-che-instances-to-the-internal-backup-server.adoc[Internal backup server]

.Procedure

. Run the following command on a command line:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:restore \
--backup-cr-name=__<name_of_custom_object>__ <1>
----
<1> The name of the `CheClusterBackup` custom object.

. When prompted in the output, enter `y` to confirm:
+
[subs="+quotes,+attributes"]
----
...
 Asking for restore confirmation: Do you want to proceed? [y/n]
...
----
+
TIP: To skip this question, add the `--batch` option to the `server:restore` command.