// monitoring-{prod-id-short}

[id="collecting-{prod-id-short}-metrics-with-prometheus"]
= Collecting {prod-short} Server metrics with Prometheus

The {prod-short} Operator automatically manages Prometheus resources to enable metric collection when {prod-short} Server metrics are enabled.

.Prerequisites

* Your organization's instance of {prod-short} is installed and running in Red Hat OpenShift.

* An active `oc` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* {prod-short} Server metrics are enabled. See xref:enabling-and-exposing-{prod-id-short}-metrics[].

.Procedure

When `spec.components.metrics.enable` is set to `true` in the `CheCluster` Custom Resource, the {prod-short} Operator automatically creates and manages the following resources:

* A `ServiceMonitor` resource named `che-host` that configures Prometheus to scrape JVM metrics from the {prod-short} Server
* A `Role` and `RoleBinding` that grant the `prometheus-k8s` service account permission to access the metrics endpoints
* The `openshift.io/cluster-monitoring=true` label on the {prod-short} namespace to enable the in-cluster Prometheus instance to discover the `ServiceMonitor`

NOTE: These resources are managed by the {prod-short} Operator. Manual modifications to these resources will be overwritten during reconciliation.

.Verification

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Metrics*.

. Run a PromQL query to confirm that the metrics are available. For example, enter `process_uptime_seconds{job="che-host"}` and click *Run queries*.

[TIP]
====

To troubleshoot missing metrics, view the Prometheus container logs for possible RBAC-related errors:

. Get the name of the Prometheus pod:
+
[source,yaml,subs="+quotes"]
----
$ oc get pods -l app.kubernetes.io/name=prometheus -n openshift-monitoring -o=jsonpath='{.items[*].metadata.name}'
----

. Print the last 20 lines of the Prometheus container logs from the Prometheus pod from the previous step:
+
[source,yaml,subs="+quotes"]
----
$ oc logs --tail=20 __<prometheus_pod_name>__ -c prometheus -n openshift-monitoring
----

====

[role="_additional-resources"]
.Additional resources


* link:https://prometheus.io/docs/prometheus/latest/querying/basics/[Querying Prometheus]

* link:https://prometheus.io/docs/concepts/metric_types/[Prometheus metric types]
