:_content-type: PROCEDURE

[id="adding-or-removing-extensions-in-the-embedded-open-vsx-registry-instance"]
= Adding or removing extensions in the embedded Open VSX registry instance

You can add or remove extensions in the embedded Open VSX registry instance deployed by {prod-short} to support offline and proxied environments.

This will create a custom build of the Open VSX registry, which can be used in your organization’s workspaces. 

pass:[<!-- vale RedHat.TermsErrors = NO -->]

TIP: To get the latest security fixes after a {prod-short} update, rebuild your container based on the latest tag or SHA.

pass:[<!-- vale RedHat.TermsErrors = YES -->]

.Procedure

. Get the publisher and extension names of each chosen extension:

.. Find the extension on the link:https://www.open-vsx.org/[Open VSX registry website] and copy the URL of the extension's listing page.

.. Extract the __<publisher>__ and __<extension>__ names from the copied URL:
+
[subs="+quotes"]
----
https://www.open-vsx.org/extension/__<publisher>__/__<extension>__
----
+
[TIP]
====

If the extension is only available from link:https://marketplace.visualstudio.com/VSCode[Microsoft Visual Studio Marketplace], but not link:https://open-vsx.org[Open VSX], you can ask the extension publisher to also publish it on link:https://open-vsx.org[open-vsx.org] according to these link:https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension[instructions], potentially using this link:https://github.com/marketplace/actions/publish-vs-code-extension[GitHub action].

If the extension publisher is unavailable or unwilling to publish the extension to link:https://open-vsx.org[open-vsx.org], and if there is no Open VSX equivalent of the extension, consider link:https://github.com/open-vsx/publish-extensions/issues[reporting an issue] to the Open VSX team.

====

include::example$snip_{project-context}-steps-to-add-or-remove-extensions-in-openvsx-sync-json.adoc[]

** To add extensions, add the publisher and extension names to the `openvsx-sync.json` file.
** To remove extensions, remove the publisher and extension names from the `openvsx-sync.json` file.
** Use the following JSON syntax:
+
[source,json,subs="+quotes"]
----
    {
        "id": "__<publisher>__.__<extension>__"
    }
----
+
TIP: The latest extension version on link:https://open-vsx.org[open-vsx.org] is the default. Alternatively, you can add `"version": "__<extension_version>__"` on a new line to specify a version.
+
[NOTE]
====

If you have a closed-source extension or an extension developed only for internal use in your organization, you can add the extension directly from a `.vsix` file by using a URL accessible to your custom plugin registry container:
+
[source,json,subs="+quotes"]
----
    {
        "id": "__<publisher>__.__<extension>__",
        "download": "__<url_to_download_vsix_file>__",
        "version": "__<extension_version>__"
    }
----

Read the link:https://aka.ms/vsmarketplace-ToU[Terms of Use] for the link:https://marketplace.visualstudio.com/VSCode[Microsoft Visual Studio Marketplace] before using its resources.

====

. Build the plugin registry container image and publish it to a container registry like link:https://quay.io/[quay.io]:

.. {empty}
+
[subs="+attributes,+quotes"]
----
$ ./build.sh -o __<username>__ -r quay.io -t custom
----

.. {empty}
+
[subs="+attributes,+quotes"]
----
$ {docker-cli} push quay.io/__<username/plugin_registry:custom>__
----

. Edit the `CheCluster` custom resource in your organization's cluster to point to the image (for example, on link:https://quay.io/[quay.io]) and save the changes:
+
[source,yaml,subs="+quotes"]
----
spec:
  components:
    pluginRegistry:
      deployment:
        containers:
          - image: quay.io/__<username/plugin_registry:custom>__
      openVSXURL: '' 
----

.Verification

. Check that the `plugin-registry` pod has restarted and is running.

. Restart the workspace and check the available extensions in the *Extensions* view of the workspace IDE.
