// Module included in the following assemblies:
//
// mounting-a-secret-or-a-configmap-as-a-file-or-an-environment-variable-into-a-container


[id="mounting-a-secret-or-a-configmap-as-an-environment-variable-into-a-container"]
= Mounting a Secret or a ConfigMap as an environment variable into a {prod-short} container


.Prerequisites

* A running instance of {prod}.

.Procedure

include::partial$snip_mounting-a-secret-or-a-configmap-into-a-container.adoc[leveloffset=+1]

. Configure the annotation values. Annotations must indicate that the given object is mounted as an environment variable:
+
* `che.eclipse.org/mount-as: env` - to indicate that a object is mounted as an environment variable
* `che.eclipse.org/env-name: _<FOO_ENV>_` - to provide an environment variable name, which is required to mount a object key value

.Example:
====
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: {prod-deployment}-secret
data:
  mykey: myvalue
----
or
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: {prod-deployment}-configmap
data:
  mykey: myvalue
----
====

This results in two environment variables:

* `FOO_ENV`

* `myvalue`

being provisioned into a {prod-short} container.

If the object provides more than one data item, the environment variable name must be provided for each of the data keys as follows:

.Example:
====
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: {prod-deployment}-secret
stringData:
  mykey: __<data_content_here>__
  otherkey: __<data_content_here>__
----
or
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: {prod-deployment}-configmap
data:
  mykey: __<data content here>__
  otherkey: __<data content here>__
----
====

This results in two environment variables:

* `FOO_ENV`

* `OTHER_ENV`

being provisioned into a {prod-short} container.

NOTE: The maximum length of annotation names in a {orch-name} object is 63 characters, where 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the object.

IMPORTANT: To make the changes in a {prod-short} container visible, re-create the Secret or the ConfigMap object entirely.

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]

