[id="installing-image-puller-using-che-operator_{context}"]
= Installing {image-puller-name-short} using the {prod-short} Operator

This section describes how to use the {prod-short} Operator to install the {image-puller-name-short}, which is a community-supported feature in the technology preview state.

.Prerequisites

* xref:defining-the-list-of-images-to-pull.adoc[]

* xref:defining-the-memory-parameters-for-the-image-puller.adoc[]

include::example$snip_{project-context}-installing-image-puller-using-che-operator-prerequisites.adoc[]

* The {prod-short} Operator is available. See xref:installation-guide:installing-che-on-openshift-4-using-operatorhub.adoc[]

.Procedure

. Enable {image-puller-name-short} in the `CheCluster` Custom Resource by setting `.spec.imagePuller.enable` to `true`:
+
====
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: {prod-checluster}
spec:
  # ...
  imagePuller:
    enable: true
----
====
+
. Configure {image-puller-name-short} in the `CheCluster` Custom Resource:
+
====
[source,yaml,subs="+quotes,+attributes,+macros"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: {prod-checluster}
spec:
  ...
  imagePuller:
    enable: true
    spec:
        configMapName: __<{image-puller-deployment-name}>__
        daemonsetName: __<{image-puller-deployment-name}>__
        deploymentName: __<{image-puller-deployment-name}>__
        images: {image-puller-images}
----
====

include::example$snip_{project-context}-image-puller-dockerfile.adoc[]


.Default images

* The {prod-short} Operator populates the `.spec.imagePuller.spec.images` field with default images used for workspace startup (Theia images, plugin broker images, sidecar plugin images), provided that no images were added to this field before creating the `CheCluster` Custom Resource. The {prod-short} Operator updates the default images in the `.spec.imagePuller.spec.images` field after every rollout update of {prod-short}. However, if images were added to the `.spec.imagePuller.spec.images` field before creating the `CheCluster` Custom Resource, the {prod-short} Operator will not add default images.

* If user-provided images are added to the `.spec.imagePuller.spec.images` field **after** creating the `CheCluster` Custom Resource, the {prod-short} Operator
will still update default images on subsequent {prod-short} rollout updates. Non-default images remain unchanged in the `.spec.imagePuller.spec.images` field after rollout updates.


.Verification

* {platforms-name} creates a `{image-puller-operator-id}` Subscription.

* The `eclipse-che namespace` contains a `{image-puller-operator-name}` `ClusterServiceVersion`:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get clusterserviceversions
----

* The `eclipse-che namespace` contains these deployments: `{image-puller-deployment-name}` and `{image-puller-deployment-id}`.
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get deployments
----

* The {image-puller-operator-name} creates a `{image-puller-cr-name}` Custom Resource:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {orch-cli} get kubernetesimagepullers
----

.Uninstalling {image-puller-name-short} using {prod-short} Operator

. Edit the `CheCluster` Custom Resource and set `.spec.imagePuller.enable` to `false`.

. Edit the `CheCluster` Custom Resource and set the `.spec.imagePuller.spec` to configure the optional {image-puller-name-short} parameters for the {prod-short} Operator.