[id="managing-backups-using-{prod-cli}"]
= Managing backups using {prod-cli}


The following section describes how to create backups of {prod-short} installation and do recovery using {prod-cli}.

.Prerequisites

include::partial$snip_internal-backup-server-warning.adoc[]

* xref:setup-backup-server.adoc[Set up a backup server].

* xref:configuring-cli-to-use-backup-server.adoc[Configure {prod-cli} to use the backup server]

.Procedure

 * xref:cli-creating-a-new-backup[]
 * xref:cli-restoring-from-backup[]

[id="cli-creating-a-new-backup"]
== Creating a new backup

. Create a backup and send it to the pre-configured backup server:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {prod-cli} server:backup --repository-url=__<repository-url>__  --repository-password=__<repository-password>__
----

* It is possible to create other backups to the same backup server using the `server:backup` command with no arguments.
* After using the `server:backup` command with no arguments for the first time on installation of {prod-short}, an internal backup server is configured and used.


[id="cli-restoring-from-backup"]
== Restoring from a backup

. Recover to the previous state of {prod-short}:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {prod-cli} server:restore --repository-url=__<repository-url>__ --repository-password=__<repository-password>__ --snapshot-id=__<snapshot-id>__
----

. Recover to different than exiting version of {prod-short}:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {prod-cli} server:restore --version=__<version>__ --snapshot-id=__<snapshot-id>__
----
+
[NOTE]
====
Provided snapshot must be created from the version of {prod-short} to which recover is requested.
====

* If you have a dedicated backup repository for each {prod-short} version and want to use the most recent backup for the version,
you may provide `latest` as snapshot ID and it will be converted to the latest ID in the given repository.

. Recover to the state described by an existing backup Custom Resource object:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {prod-cli} server:restore --backup-cr-name=__<CheClusterBackupCRName>__
----

. Recover to the previous version after update:
+
{prod} automatically creates a backup when upgrading to a newer version.
To return to the previous installed version run:
+
[source,shell,subs="+quotes,+attributes"]
----
$ {prod-cli} server:restore --rollback
----
