:_content-type: CONCEPT

[id="selecting-an-open-vsx-registry-instance"]
= Selecting an Open VSX registry instance

The embedded Open VSX registry within the {prod-short} `plugin-registry` is the default.

TIP: xref:adding-or-removing-extensions-in-the-embedded-open-vsx-registry-instance[You can customize the list of extensions included in the default embedded Open VSX registry].

If the default Open VSX registry instance is not what you need, you can select one of the following instances:

* The Open VSX registry instance at `pass:c,a,q[https://open-vsx.org]` that requires access to the internet.

* A standalone Open VSX registry instance whose URL is accessible from within your organization's cluster and not blocked by a proxy.


.Procedure

* Edit the `openVSXURL` value in the `CheCluster` custom resource:
+
[source,yaml,subs="+quotes"]
----
spec:
  components:
    pluginRegistry:
      openVSXURL: "__<url_of_an_open_vsx_registry_instance>__" # <1>
----
<1> For example: `openVSXURL: "pass:c,a,q[https://open-vsx.org]"`.
