[id="installing-image-puller-using-operator_{context}"]
= Installing the {image-puller-name-short} on OpenShift using OperatorHub

This procedure describes how to install the {image-puller-name-short} on {kubernetes} using the Operator. This is the recommended installation method.


.Prerequisites

* An administrator account on a running instance of OpenShift 4.
* xref:defining-the-list-of-images-to-pull.adoc[]
* xref:defining-the-memory-parameters-for-the-image-puller.adoc[].

.Procedure

. To create an OpenShift project __<{image-puller-deployment-name}>__ to host the {image-puller-name-short}, open the OpenShift web console, navigate to the *Home* -> *Projects* section and click btn:[Create Project].

. Specify the project details:
+
* *Name*:  __<{image-puller-deployment-name}>__
* *Display Name*: __<{image-puller-name-short}>__
* *Description*: __<{image-puller-name}>__


. Navigate to btn:[*Operators*] → btn:[*OperatorHub*].  

. Use the btn:[*Filter by keyword*] box to search for `{image-puller-operator-name}`. Click the btn:[{image-puller-operator-name}].

. Read the description of the Operator. Click btn:[*Continue*] → btn:[*Install*].

. Select btn:[*A specific {orch-namespace} on the cluster*] for the btn:[*Installation Mode*]. In the drop-down find the OpenShift project __<{image-puller-deployment-name}>__. Click btn:[*Subscribe*].  

. Wait for the {image-puller-operator-name} to install. Click the btn:[*{image-puller-cr-name}*] → btn:[*Create instance*]. 

. In a redirected window with a YAML editor, make modifications to the `{image-puller-cr-name}` Custom Resource and click btn:[*Create*].

. Navigate to the btn:[*Workloads*] and btn:[*Pods*] menu in the __<{image-puller-deployment-name}>__ OpenShift project. Verify that the {image-puller-name-short} is available.

