[id="configuring-prod-short-to-use-the-internal-backup-server_{context}"]
= Configuring {prod-short} to use the internal backup server

The internal backup server is an optional REST backup server that is managed by {prod-short} Operator and intended for testing purposes. To use the internal backup server, you must request automatic configuration from {prod-short} Operator as follows:

WARNING: Configuring a backup server inside the same cluster, for example the internal backup server, is not recommended for a production environment.

.Procedure

//Create a CustomResourceDefinition to configure ...? max-cx
. Configure the automatic setup and sending of the backup to the internal backup server:
+
[source,yaml,subs="+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheClusterBackup
metadata:
  name: {prod-short}-backup
spec:
  useInternalBackupServer: true
----

. Read the `status` section of the `CheClusterBackup` object to verify the backup process:
+
[source,yaml,subs="+attributes"]
----
status:
  message: 'Backup is in progress. Start time: <timestamp>' <1>
  stage: Collecting {prod-short} installation data          <2>
  state: InProgress                                         <3>
  snapshotId: ba92c7e0                                      <4>
----
<1> Displays the overall state or error message.
<2> Current phase of the backup process in a human-readable format.
<3> Backup process state: `InProgress` or `Succeeded` or `Failed`.
<4> ID of the created backup snapshot. The field appears only when `state` is `Succeeded`.