// Module included in the following assemblies:
//
// {prod-id-short}-workspace-configuration

[id="storage-strategies-for-{prod-id-short}-workspaces_{context}"]
= Storage strategies for {prod-id-short} workspaces

Storage strategy::
A configurable method defining how {prod-short} workspaces use persistent volume claims (PVCs) and persistent volumes (PVs). 
This method defines the storage for workspace data, for example, projects, workspace logs, or additional volumes defined by a user.

.Storage strategies comparison
[width="100%",cols="1,1,1,1",options="header"]
|===
| Storage strategy name
| `common`
| `per-workspace`
| `unique`

| PV count
| One per user
| One per workspace
| Multiple PVs per workspace

| Default
| yes
| no
| no


| Limitations
| Maximum one running workspace per user when the PV is in the `ReadWriteOnce` access mode
| PV count depends on the number of workspaces
| Unpredictable PV count

|===

Persistent volumes (PVs) access mode::
The nature of the PV determines the available access mode: `ReadWriteMany` or `ReadWriteOnce`.
See link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[Kubernetes documentation - access mode].
For example, link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html[Amazon EBS] supports only the `ReadWriteOnce` access mode.


[id="the-common-storage-strategy_{context}"]
== The `common` storage strategy

This is the default storage strategy.
For each user, all workspaces use the same PV for the default data storage.

When the user starts a first non-ephemeral workspace, the workspace engine creates a common PV.

When the user starts another non-ephemeral workspace, the workspace engine uses the same common PV.
The workspace only binds simultaneously to one node in the {orch-name} cluster.
The workspace engine ignores user-defined volumes. 
The workspace engine replaces volumes related to user-defined volumes with a subPath in the common volume. 
SubPaths have a `_<workspace-ID>_` or `__<original-volume-name>__` prefix.
See xref:how-subpaths-are-used-in-persistent-volumes_{context}[].
The {prod-short} volume name is identical to the name of the user-defined PV.
Therefore, if a workspace container uses a {prod-short} volume with the same name as the user-defined PV, they will use the same shared folder in the common PV.

When the user deletes a workspace, the workspace engine deletes the corresponding subdirectory (`$\{ws-id}`) in the PV directory.

When the user deletes the last workspace, the workspace engine removes the common PV. 

Restrictions on the `common` storage strategy with the `ReadWriteOnce` access mode::
The `ReadWriteOnce` access mode limits each user to run only one concurrent workspace.
See xref:installation-guide:configuring-the-number-of-workspaces-that-a-user-can-run.adoc[].

Scalability::
The `common` storage strategy is not suitable for multi-node clusters with the 'ReadWriteOnce' access mode for PVs if the number of concurrently running workspaces per user is more than 1.

Persistent volumes (PV) provisioning::
Create a large enough PV to accommodate all projects to prevent a situation in which one project depletes the resources of others.

[id="the-per-workspace-storage-strategy_{context}"]
== The `per-workspace` storage strategy

Each workspace uses one dedicated PV. 
All {prod-short} volumes defined within a single workspace use the same PV.

Scalability::
Consider enabling this strategy on large multi-node clusters with a higher amount of users.

Persistent volumes (PV) provisioning::
Users can run multiple workspaces simultaneously. This action results in more PVs.

[id="the-unique-storage-strategy_{context}"]
== The `unique` storage strategy

Each {prod-short} volume defined in a workspace has its own PV.

When the user starts a workspace, the workspace engine creates the workspace PVs.

The workspace engine generates a unique name for each PV to prevent name conflicts with other PVs in the same {orch-namespace}.

To ensure that different storage strategies use the same PV data structure, subPaths of the mounted PVs that reference user-defined PVs are prefixed with `_<workspace-ID>_` or `__<persistent-volume-name>__`. 
See xref:how-subpaths-are-used-in-persistent-volumes_{context}[].

When the user deletes a workspace, the workspace engine deletes all workspace PVs.

PV provisioning::
This is the strategy, which creates the highest volume counts.


[id="how-subpaths-are-used-in-persistent-volumes_{context}"]
== How subPaths are used in persistent volumes (PVs)

SubPaths illustrate the folder hierarchy in the PV.

[subs="+quotes,+attributes"]
----
/__<pv0001>__
  /__<workspaceID1>__
  /__<workspaceID2>__
  /__<workspaceIDn>__
    /che-logs
    /projects
    /__<volume1>__
    /__<volume2>__
    /__<user-defined-volume-name-1>__
    /__<user-defined-volume-name-2>__
    /__<user-defined-volume-name-3|volume3>__
    ...
----

When a user defines volumes for components in the devfile, all components that define the volume of the same name will be backed by the same directory in the PV as `__<persistent-volume-name>__`, `__<workspace-ID>__`, or `__<original-volume-name>__`.
Each component can have this location mounted on a different path in its containers.
