[id="understanding-the-checluster-custom-resource_{context}"]
= Understanding the `CheCluster` Custom Resource

A default deployment of {prod-short} consist of a `CheCluster` Custom Resource parameterized by the {prod} Operator.

`CheCluster` Custom Resource:: 

* A Kubernetes object.
* You can configure it by editing the `CheCluster` Custom Resource YAML file. The file contains sections to configure each component: `auth`, `database`, `server`, `storage`.

Role of the {prod} Operator::

* To translate the `CheCluster` Custom Resource into configuration (ConfigMap) usable by each component of the {prod-short} installation.

Role of the {orch-name} platform::

* To apply the configuration (ConfigMap) for each component.
* To create the necessary Pods.
* When {orch-name} detects a change in the configuration of a component, it restarts the Pods accordingly.

.Configuring the main properties of the {prod-short} server component
====
. Apply the `CheCluster` Custom Resource YAML file with suitable modifications in the `server` component section.
. The Operator generates the `che` `ConfigMap`. 
. {orch-name} detects changes in the `ConfigMap` and triggers a restart of the {prod-short} Pod.
====

.Additional resources

* link:https://docs.openshift.com/container-platform/latest/operators/understanding/olm-what-operators-are.html[Understanding Operators].

ifeval::["{project-context}" == "crw"]

* link:https://docs.openshift.com/container-platform/latest/operators/understanding/crds/crd-managing-resources-from-crds.html[Understanding Custom Resources].

endif::[]

ifeval::["{project-context}" == "che"]

* link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Understanding Custom Resources].

endif::[]

