// Module included in the following assemblies:
//
// configuring-workspace-exposure-strategies

[id="workspace-exposure-strategies_{context}"]
= Workspace exposure strategies

Specific components of workspaces need to be made accessible outside of the {platforms-name} cluster. This is typically the user interface of the workspace's IDE, but it can also be the web UI of the application being developed. This enables developers to interact with the application during the development process.

The supported way of making workspace components available to the users is referred to as a _strategy_. This strategy defines whether new subdomains are created for the workspace components and what hosts these components are available on.

{prod-short} supports:
* `multi-host` strategy
ifeval::["{project-context}" == "che"]
* `single-host` strategy
* `default-host` strategy
endif::[]

== Multi-host strategy

With this strategy, each workspace component is assigned a new subdomain of the main domain configured for the {prod-short} server. On OpenShift, this is the only possible strategy, and manual configuration of the workspace exposure strategy is therefore always ignored.

This strategy is the easiest to understand from the perspective of component deployment because any paths present in the URL to the component are received as they are by the component.

On a {prod-short} server secured using the Transport Layer Security (TLS) protocol, creating new subdomains for each component of each workspace requires a wildcard certificate to be available for all such subdomains for the {prod-short} deployment to be practical.

== Single-host strategy

Single-host strategy have two subtypes with different implementation methods. First subtype is named `native`. This strategy is available and default on {kubernetes}, but not on OpenShift, since it uses ingresses for servers exposing. The second subtype named `gateway`, works both on
{platforms-name}, and uses a special pod with reverse-proxy running inside to route requests.

When any of those single-host types is used, all workspaces are deployed to sub-paths of the main {prod-short} server domain.

This is convenient for TLS-secured {prod-short} servers because it is sufficient to have a single certificate for the {prod-short} server, which will cover all the workspace component deployments as well.

There are two types of endpoints, that are defined in the devfiles, exposures in single-host strategy. To configured it, use `++CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE++`. It is effective only in single-host server strategy..

=== Devfile endpoints: `single-host`

`++CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE: 'single-host'++`

This single-host configuration exposes the endpoints on subpaths, e.g.: `++https://<che-host>/serverihzmuqqc/go-cli-server-8080++`. This limits the exposed components and user applications. Any absolute URL generated on the server side that points back to the server does not work. This is because the server is hidden behind a path-rewriting Ingress that hides the workspace and the component-specific URL prefix from the server.

For example, when the user accesses the hypothetical `[{prod-url}/component-prefix-djh3d/app/index.php]` URL, the application sees the request coming to `++https://internal-host/app/index.php++`. If the application used the host in the URL that it generates in its UI, it would not work because the internal host is different from the externally visible host. However, if the application used an absolute path as the URL (for the example above, this would be `/app/index.php`), such URL would still not work. This is because on the outside, such URL does not point to the application, because it is missing the component-specific prefix.

Therefore, only applications that use relative URLs in their UI work with the single-host workspace exposure strategy.

=== Devfile endpoints: `multi-host`
`++CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE: 'multi-host'++`

This single-host configuration exposes the endpoints on subdomains, e.g.: `++http://serverihzmuqqc-go-cli-server-8080.<che-host>++`. These endpoints will be exposed on unsecured HTTP port. We're using dedicated Ingress/Route for such endpoints, even with `gateway` single-host setup.

This configuration limits the usability of previews shown directly in the editor page when {prod-short} is configured with TLS. Because unsecured pages can't be loaded from secured ones, users must open their applications on another tab of the browser.

ifeval::["{project-context}" == "che"]
== Default-host strategy

This strategy exposes the components to the outside world on the sub-paths of the default host of the cluster. It is similar to the single-host strategy. All the limitations and advantages of the single-host strategy applying to this strategy as well.
endif::[]
