// Module included in the following assemblies:
//
// {prod-id-short}-workspace-configuration

[id="storage-strategies-for-{prod-id-short}-workspaces_{context}"]
= Storage strategies for {prod-id-short} workspaces

Storage strategy (PVC strategy):: A configurable method defining how {prod-short} workspaces uses persistent volume claims (PVCs). It defines the default data storage when storing data such as the following in their declared volumes:

* projects
* workspace logs
* additional Volumes defined by a user

Persistent volumes (PVs) access mode::
The PVCs are bound to the physical persistent volumes (PVs).
The nature of the PV determines the available access mode: `ReadWriteMany` or `ReadWriteOnce`. See link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes[Kubernetes documentation - access mode].
For example, link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html[Amazon EBS] supports only the `ReadWriteOnce` access mode.

[width="100%",cols="^,^,^,^",options="header"]
|===
| Strategy
| Details
| Pros 
| Cons

| `common` (default)
| One PVC per user
| Easy to manage and control storage 
| Maximum one running workspace per user when the PV is in `ReadWriteOnce` access mode.

| `per-workspace`
| One PVC per workspace
| Easier to manage and control storage than `unique` strategy  
| Unknown PV count, depending on the number of workspaces

| `unique`
| One PVC per workspace volume or user-defined PVC
| Storage isolation 
| Unknown PV count

|===

[id="the-common-pvc-strategy_{context}"]
== The `common` PVC strategy

This is the default storage strategy.
For each user, all workspaces use the same Persistent Volume Claim (PVC) as the default data storage.

{prod-short} creates the common PVC when it starts a non-ephemeral workspace.

{prod-short} removes the common PVC when the user deletes all his workspaces. 

When the user runs a workspace, it only binds simultaneously to one node in the {orch-name} cluster.

When creating a workspace, {prod-short} ignores user-defined PVCs. 
It replaces volumes related to user-defined PVCs with a subpath in the common volume. 
Subpaths have a `_<workspace-ID>_` or `__<original-PVC-name>__` prefix.
See xref:how-subpaths-are-used-in-pvcs_{context}[].

The {prod-short} Volume name is identical to the name of the user-defined PVC.
It means that if a machine is configured to use a {prod-short} volume with the same name as the user-defined
PVC has, they will use the same shared folder in the common PVC.

When deleting a workspace, {prod-short} deletes the corresponding subdirectory (`$\{ws-id}`) in the PV directory.

.Restrictions on using the `common` PVC strategy

`ReadWriteOnce` access mode::
The `ReadWriteOnce` access mode limits each user to run one unique concurrent workspace. See xref:installation-guide:configuring-the-number-of-workspaces-that-a-user-can-run.adoc[].

Scalability::
Consider using this strategy in single-node clusters.
The `common` PVC strategy is not suitable for large multinode clusters. 

PVC provisioning::
Create large enough PVC  to accommodate all projects to prevent a situation in which one project depletes the resources of others.

[id="the-per-workspace-pvc-strategy_{context}"]
== The `per-workspace` PVC strategy

Each workspace use a dedicated PVC. 
All Volumes for one workspace use the same PVC.

Scalability::
Consider using this strategy on large multinode clusters with a higher amount of users.

PVC provisioning::
Users can run multiple workspaces simultaneously. It results in more PVCs.

[id="the-unique-pvc-strategy_{context}"]
== The `unique` PVC strategy

Every {prod-short} Volume of a workspace has its own PVC. The workspace PVCs are then:

* Created when a workspace starts for the first time.
* Deleted when a corresponding workspace is deleted.

User-defined PVCs are created with the following specifics:

* They are provisioned with generated names to prevent naming conflicts with other PVCs in a {orch-namespace}.

* Subpaths of the mounted Physical persistent volumes that reference user-defined PVCs are prefixed with `_<workspace-ID>_` or `__<PVC-name>__`. This ensures that the same PV data structure is configured with different PVC strategies. For details, see xref:how-subpaths-are-used-in-pvcs_{context}[].


Scalability::
Consider using this strategy on larger multinode clusters with a lesser amount of users.

PVC provisioning::
This is the strategy creating the highest PVC count.


[id="how-subpaths-are-used-in-pvcs_{context}"]
== How subpaths are used in PVCs

Subpaths illustrate the folder hierarchy in the Persistent Volumes (PV).

----
/pv0001
  /workspaceID1
  /workspaceID2
  /workspaceIDn
    /che-logs
    /projects
    /<volume1>
    /<volume2>
    /<User-defined PVC name 1 | volume 3>
    ...
----

When a user defines volumes for components in the devfile, all components that define the volume of the same name will be backed by the same directory in the PV as `__<PV-name>__`, `__<workspace-ID>__, or `__<original-PVC-name>__`. Each component can have this location mounted on a different path in its containers.


.Example
Using the `common` PVC strategy, user-defined PVCs are replaced with subpaths on the common PVC. When the user references a volume as `_<my-volume>_`, it is mounted in the common-pvc with the `/workspace-id/_<my-volume>_` subpath.
