// Module included in the following assemblies:
//
// configuring-workspace-exposure-strategies

[id="configuring-workspace-exposure-strategies-using-a-helm-chart_{context}"]

= Configuring workspace exposure strategies using a Helm chart

A link:https://helm.sh/[Helm Chart] is a {kubernetes} extension for defining, installing, and upgrading {kubernetes} applications.

.Procedure

When deploying {prod-short} using the Helm chart, configure the workspace exposure strategy using the `global.serverStrategy`.  For single-host, optional `global.singleHostExposure` and `cheSinglehostGateway.deploy` properties may be configured as well. To do so, add the following option to the `helm install` or `helm upgrade` command:


Example for `native` single-host strategy type and `multi-host` or `default-host` strategies:

[subs="+quotes"]
----
$ helm install --set global.serverStrategy=__<exposure-strategy>__
----

or:

[subs="+quotes"]
----
$ helm upgrade --set global.serverStrategy=__<exposure-strategy>__
----

The supported values for `global.serverStrategy` are:

* xref:multi-host-workspace-exposure-strategy_{context}[`multi-host`]
* xref:single-host-workspace-exposure-strategy_{context}[`single-host`]
* xref:default-host-workspace-exposure-strategy_{context}[`default-host`]


.Gateway single-host on Kubernetes

Single-host on Kubernetes has 2 implementations, `native`(default) and `gateway`. To deploy with `gateway` use:

[subs="+quotes,+attributes"]
----
$ helm install --namespace {prod-namespace} \
--set global.serverStrategy=single-host \
--set global.singleHostExposure=gateway \
--set cheSinglehostGateway.deploy=true
----

or:

[subs="+quotes,+attributes"]
----
$ helm upgrade --install che --namespace {prod-namespace} \
--set global.serverStrategy=single-host \
--set global.singleHostExposure=gateway \
--set cheSinglehostGateway.deploy=true
----

Alternatively, predefined values file can be used as follows:

[subs="+quotes,+attributes"]
----
$ helm upgrade --install che --namespace {prod-namespace} \
-f "${SOURCE_HOME_DIR}"/deploy/kubernetes/helm/che/values/single-host-gateway.yaml
----
