// Module included in the following assemblies:
//
// upgrading-{prod-id-short}

[id="upgrading-{prod-id-short}-using-the-cli-management-tool_{context}"]
= Upgrading {prod-short} using the CLI management tool

This section describes how to upgrade from previous minor version using the CLI management tool.

.Prerequisites

* An administrative account on an instance of {platforms-name}.

* A running instance of a previous minor version of {prod}, installed using the CLI management tool on the same instance of {platforms-name}, in the `__<{prod-namespace}>__` project.

* An installation of the `{prod-cli}` {prod-ver} version management tool. See xref:overview:using-the-chectl-management-tool.adoc[].

.Procedure

. In all running workspaces in the {prod-short} {prod-prev-ver} instance, save and push changes back to the Git repositories.

. Shut down all workspaces in the {prod-short} {prod-prev-ver} instance.

. Run the following command to make sure your {prod-cli} version is the latest:
----
$ {prod-cli} update
----

. Upgrade {prod-short} with the following command:
+
[subs="+attributes,+quotes"]
----
$ {prod-cli} server:update -n {prod-namespace}
----

[NOTE]
====
For slow systems or internet connections, add the `--k8spodwaittimeout=1800000` flag option to the `{prod-cli} server:update` command to extend the Pod timeout period to 1800000 ms or longer.
====

.Verification steps

. Navigate to the {prod-short} instance.

. The {prod-ver} version number is visible at the bottom of the page.
