
[id="configuring-namespace-strategies_{context}"]
= Configuring {orch-namespace} strategies

ifeval::["{project-context}" == "che"]
NOTE: The term _{orch-namespace}_ ({kubernetes}) is used interchangeably with _project_ (OpenShift).
endif::[]

The {platforms-namespace} strategies are configured using the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` environment variable.

WARNING: `CHE_INFRA_KUBERNETES_NAMESPACE` and `CHE_INFRA_OPENSHIFT_PROJECT` are legacy variables. Keep these variables unset for a new installations. Changing these variables during an update can lead to data loss.

WARNING: By default, only one workspace in the same {orch-namespace} can be running at one time. See xref:installation-guide:running-more-than-one-workspace-at-a-time.adoc[].


== One {orch-namespace} per workspace strategy

The strategy creates a new {orch-namespace} for each new workspace.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must contain the `_<workspaceID>_` identifier. It can be used alone or combined with other identifiers or any string.

.One {orch-namespace} per workspace
====
To assign {orch-namespace} names composed of a __`{prod-workspace}`__ prefix and workspace id, set:

[subs="+quotes,+attributes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=__{prod-workspace}__-__<workspaceID>__
----
====

== One {orch-namespace} for all workspaces strategy

The strategy uses one predefined {orch-namespace} for all workspaces.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must be the name of the desired {orch-namespace} to use.

.One {orch-namespace} for all workspaces
====
To have all workspaces created in __`{prod-workspace}`__ {orch-namespace}, set:

[subs="+quotes,+attributes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=__{prod-workspace}__
----
====

== One {orch-namespace} per user strategy

The strategy isolates each user in their own {orch-namespace}.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must contain one or more user identifiers. Currently supported identifiers are `_<username>_` and `_<userId>_`.

.One {orch-namespace} per user
====
To assign {orch-namespace} names composed of a __`{prod-workspace}`__ prefix and individual usernames (`__{prod-workspace}__-user1`, `__{prod-workspace}__-user2`), set:

[subs="+quotes,+attributes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=__{prod-workspace}__-__<username>__
----
====

== Allowing user-defined workspace {orch-namespace}s

{prod-short} server can be configured to honor the user selection of a {orch-namespace} when a workspace is created. This feature is disabled by default. To allow user-defined workspace {orch-namespace}s:

ifeval::["{project-context}" == "che"]
* For Helm Chart deployments, set the following environment variable in the {prod-short} ConfigMap:
+
----
CHE_INFRA_KUBERNETES_NAMESPACE_ALLOW__USER__DEFINED=true
----
endif::[]

* For Operator deployments, set the following field in the CheCluster Custom Resource:
+
----
allowUserDefinedWorkspaceNamespaces
----

== Handling incompatible usernames or user IDs

{prod-short} server automatically checks usernames and\or ID-s for compatibility with Kubernetes objects naming convention before creating a {orch-namespace} from a template.
In case of incompatible user name or ID, it will be reduced to nearest valid name by replacing groups of unsuitable symbols with an `-` symbol. To avoid collisions,
some random 6 symbols suffix is added and result is stored into preferences for re-use.

== Pre-creating {orch-namespace}s for users

To pre-create {orch-namespace}s for users, use {orch-namespace} labels.

----
metadata:
  labels:
    app.kubernetes.io/component: workspace
    app.kubernetes.io/part-of: che.eclipse.org
    che.eclipse.org/username: <username>  <1>
----
<1> target user's username

To configure the labels, set the `CHE_INFRA_KUBERNETES_NAMESPACE_LABELS` to desired labels. See the xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc#che-server-component-system-properties-reference_advanced-configuration-options-for-the-che-server-component[Che server component system properties reference] for more details.

[IMPORTANT]
====
On OpenShift with OAuth, target user must have `admin` role privileges in target namespace:
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: <namespace> <1>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: <username> <2>
----
<1> pre-created namespace
<2> target user

On {kubernetes}, `che` ServiceAccount must have a cluster-wide `list namespaces` privilege as well as an `admin` role in target namespace.
====
