

[id="deploying-{prod-id-short}-with-support-for-git-repositories-with-self-signed-certificates_{context}"]
= Deploying {prod-short} with support for Git repositories with self-signed certificates

This procedure describes how to configure {prod-short} for deployment with support for Git operations on repositories that use self-signed certificates.

.Prerequisites

* Git version 2 or later
ifeval::["{project-context}" == "che"]
* link:https://helm.sh/[Helm] version 2.15 or higher
endif::[]

.Procedure

Configuring support for self-signed Git repositories.

. Create a new *ConfigMap* with details about the Git server:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} create configmap che-git-self-signed-cert \
  --from-file=ca.crt=__<path_to_certificate>__ \  <1>
  --from-literal=githost=__<host:port>__ -n {prod-namespace}  <2>
----
<1> Path to self-signed certificate
<2> The host and port of the HTTPS connection on the Git server (optional).
+
[NOTE]
====
* When `githost` is not specified, the given certificate is used for all HTTPS repositories.
* Certificate files are typically stored as Base64 ASCII files, such as. `.pem`, `.crt`, `.ca-bundle`. Also, they can be encoded as binary data, for example, `.cer`.  All `Secrets` that hold certificate files should use the Base64 ASCII certificate rather than the binary data certificate.
====

. Configure {prod-short} to use self-signed certificates for git repositories:
+
ifeval::["{project-context}" == "che"]
=====
.For {prod-short} deployed using a Helm Chart

. Clone the https://github.com/eclipse-che/che-server[{prod-short} server repository].
. Go to `deploy/kubernetes/helm/che` directory.
. Update the `global.useGitSelfSignedCerts` property. To do that, add the following option to the `helm upgrade` command:
+
[subs="+quotes,+attributes"]
----
$ helm upgrade che -n {prod-namespace} \
  --set global.useGitSelfSignedCerts=true \
  --set global.ingressDomain=__<kubernetes-cluster-domain>__ \
  -f values/multi-user.yaml -f values/tls.yaml .
----

On Minikube, substitute `_<kubernetes-cluster-domain>_` with `$(minikube ip).nip.io`.
=====
endif::[]
+
====

ifeval::["{project-context}" == "che"]
.For {prod-short} deployed using Operators
endif::[]

Update the `gitSelfSignedCert` property. To do that, execute:

[subs="+attributes"]
----
$ {orch-cli} patch checluster/{prod-checluster} -n {prod-namespace} --type=json \
  -p '[{"op": "replace", "path": "/spec/server/gitSelfSignedCert", "value": true}]'
----
====
// TODO
// [discrete]
// == Configuring support for self-signed Git repositories on OpenShift

. Create and start a new workspace. Every container used by the workspace mounts a special volume that contains a file with the self-signed certificate. The repository's `.git/config` file contains information about the Git server host (its URL) and the path to the certificate in the `http` section (see Git documentation about link:https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpsslCAInfo[git-config]). For example:
+
----
[http "https://10.33.177.118:3000"]
sslCAInfo = /etc/che/git/cert/ca.crt
----
