//This module is included in
//
// * assembly_installing-che-using-the-che-operator-in-openshift-4-web-console

[id="creating-an-instance-of-the-che-operator_{context}"]
= Creating an instance of the {prod} Operator

Follow this procedure to install {prod} with the default configuration. To modify the configuration, see xref:configuring-the-che-installation.adoc[].

.Procedure

. To create an instance of the {prod} Operator, in the left panel, navigate to the *Operators* -> *Installed Operators* section.

. In the *Installed Operators* screen, click the *{prod}* name.

. In the *Operator Details* screen, in the *Details* tab, inside of the *Provided APIs* section, click the *Create Instance* link.

. The *Create CheCluster* page contains the configuration of the overall {prod-short} instance to create. It is the `CheCluster` Custom Resource. Keep the default values. 

. To create the *{prod-checluster}* cluster, click the btn:[Create] button in the lower left corner of the window.

. On the *Operator Details* screen, in the *{prod} Cluster* tab, click on the *{prod-checluster}* link.

. To navigate to the *{prod-checluster}* instance, click the link under *{prod} URL*. 
+
[NOTE]
====
The installation might take more than 5 minutes. The URL appears after the {prod} installation finishes. 
====

.Verification steps

. To verify that the {prod} instance has installed correctly, navigate to the *{prod2} Cluster* tab. The *CheClusters* screen displays the list of {prod} instances and their status.

. Click *{prod-checluster}* `CheCluster` in the table and navigate to the *Details* tab.

. See the content of following fields:
+
* *Message*: the field contains error messages, if any. The expected content is `None`.
* *{prod} URL*: displays the URL of the {prod} instance, once the deployment is successful.

. Navigate to the *Resources* tab. The screen displays the list of the resources assigned to the {prod-short} deployment.

. To see more details about the state of a resource, click its name and inspect the content of the available tabs. 
