// Module included in the following assemblies:
//
// installing-{prod-id-short}-on-minikube

[id="installing-{prod-id-short}-on-minikube-using-{prod-cli}_{context}"]
= Installing {prod-short} on Minikube using {prod-cli}

This section describes how to install {prod-short} on Minikube using {prod-cli}.

.Prerequisites

* The `{prod-cli}` management tool is available. See xref:using-the-chectl-management-tool.adoc[].
* A running instance of Minikube. See xref:using-minikube-to-set-up-kubernetes_{context}[].

.Procedure

* To install {prod-short} in multi-user mode (default and recommended), run the following command:
+
[subs="+attributes"]
----
$ {prod-cli} server:start --platform minikube
----

* To install {prod-short} in single-user mode add one if the following parameters to the command above:

  ** Use Helm installer by providing `--installer helm` option.
  ** Pass `--che-operator-cr-patch-yaml patch.yaml`, where `patch.yaml` file has the following content:
+
[source,yaml]
----
spec:
  server:
    customCheProperties:
       CHE_MULTIUSER: "false"
----
