
[id="configuring-namespace-strategies_{context}"]
= Configuring workspace target {orch-namespace}

The {platforms-namespace} where a new workspace is deployed depends on the {prod-short} server configuration. {prod-short} deploys each workspace into a user's dedicated {orch-namespace}, which hosts all {prod-short} workspaces created by the user. The name of a {platforms-namespace} must be provided as a {prod-short} server configuration property or pre-created by {prod-short} administrator.

ifeval::["{project-context}" == "che"]
NOTE: The term _{orch-namespace}_ ({kubernetes}) is used interchangeably with _project_ (OpenShift).
endif::[]

With **Operator** installer, {platforms-namespace} strategies are configured using `server.workspaceNamespaceDefault` property.

*Operator CheCluster CR patch*
[subs="+quotes,+attributes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: <che-cluster-name>
spec:
  server:
    workspaceNamespaceDefault: __<workspace-namespace>__ <1>
----
<1> - {prod-short} workspace {orch-namespace} configuration


ifeval::["{project-context}" == "che"]
With **Helm** installer, {orch-namespace} strategies are configured using `global.cheWorkspacesNamespace` property.

*Helm*
[subs="+quotes,+attributes"]
----
$ helm install --namespace <namespace>
  --set global.cheWorkspacesNamespace=__<workspace-namespace>__ <1>
----
or
[subs="+quotes,+attributes"]
----
$ helm upgrade --namespace <namespace>
  --set global.cheWorkspacesNamespace=__<workspace-namespace>__ <1>
----
<1> - {prod-short} workspace namespace configuration
endif::[]

NOTE: The underlying environment variable that {prod-short} server uses is `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT`.

WARNING: By default, only one workspace in the same {orch-namespace} can be running at one time. See xref:configuring-the-number-of-workspaces-that-a-user-can-run.adoc[].

[WARNING]
====
{kubernetes} limits the length of a {orch-namespace} name to 63 characters (this includes the evaluated placeholders). Additionally, the names (after placeholder evaluation) must be valid DNS names.

On OpenShift with multi-host server exposure strategy, the length is further limited to 49 characters.

Be aware that the `_<userid>_` placeholder is evaluated into a 36 character long UUID string.
====

[WARNING]
====
Use <<pre-creating-namespace>> when:

* `che` ServiceAccount does not have enough permissions when creating new {orch-namespace}

pass:[<!-- vale Vale.Terms = NO -->]

* OpenShift OAuth with a `self-provisioner` cluster role is not linked to the `system:authenticated:oauth` group

pass:[<!-- vale Vale.Terms = YES -->]

* {prod-short} cannot create namespaces
====

== One {orch-namespace} per user strategy

The strategy isolates each user in their own {orch-namespace}.

To use the strategy, set the _{prod-short} workspace {orch-namespace} configuration_ value to contain one or more user identifiers. Currently supported identifiers are `_<username>_` and `_<userid>_`.

.One {orch-namespace} per user
====
To assign {orch-namespace} names composed of a __`{prod-workspace}`__ prefix and individual usernames (`__{prod-workspace}__-user1`, `__{prod-workspace}__-user2`), set:

*Operator installer (CheCluster CustomResource)*
[subs="+quotes,+attributes"]
----
...
spec:
  server:
    workspaceNamespaceDefault: __{prod-workspace}__-__<username>__
...
----

ifeval::["{project-context}" == "che"]
*Helm*
[subs="+quotes,+attributes"]
----
$ helm ... --set global.cheWorkspacesNamespace=__{prod-workspace}__-__<username>__
----
endif::[]
====

== Handling incompatible usernames or user IDs

{prod-short} server automatically checks usernames and IDs for compatibility with {orch-name} objects naming convention before creating a {orch-namespace} from a template. Incompatible usernames or IDs are reduced to the nearest valid name by replacing groups of unsuitable symbols with the `-` symbol. The addition of a random 6-symbol suffix prevents IDs from collisions. The result is stored in preferences for reuse.

[#pre-creating-namespace]
== Pre-creating a {orch-namespace} for each user

To pre-create a {orch-namespace} for each user, use {orch-name} labels and annotations. Such {orch-namespace} is used in preference to `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable.

----
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-namespace
  annotations:
    che.eclipse.org/username: <username>  <1>
----
<1> target user's username

To configure the labels, set the `CHE_INFRA_KUBERNETES_NAMESPACE_LABELS` to desired labels. To configure the annotations, set the `CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS` to desired annotations. See the xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc#{prod-id-short}-server-component-system-properties-reference_{context}[{prod-short} server component system properties reference] for more details.

[WARNING]
====
Do not create multiple namespaces for a single user. It may lead to undefined behavior.
====

[IMPORTANT]
====
On OpenShift with OAuth, the target user must have `admin` role privileges in the target namespace:
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: <namespace> <1>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: <username> <2>
----
<1> pre-created namespace
<2> target user

On {kubernetes}, `che` ServiceAccount must have a cluster-wide `list` and `get` `namespaces` permissions as well as an `admin` role in target namespace.
====

== Labeling the namespaces

{prod-short} updates the workspace's {orch-namespace} on workspace startup by adding the labels defined in `CHE_INFRA_KUBERNETES_NAMESPACE_LABELS`. To do so, `che` ServiceAccount has to have the following cluster-wide permissions to `update` and `get` `namespaces`:

----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <cluster-role-name> <1>
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - update
      - get
----
<1> name of the cluster role

----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <cluster-role-binding-name> <1>
subjects:
  - kind: ServiceAccount
    name: <service-account-name> <2>
    namespace: <service-accout-namespace> <3>
roleRef:
  kind: ClusterRole
  name: <cluster-role-name> <4>
  apiGroup: rbac.authorization.k8s.io
----
<1> name of the cluster role binding
<2> name of the `che` ServiceAccount
<3> {prod-short} installation namespace
<4> name of the cluster role created in previous step

[NOTE]
====
A lack of permissions does not prevent a {prod-short} workspace from starting, it only logs the warning. If you see the warnings in {prod-short} logs, consider disabling the feature by defining `CHE_INFRA_KUBERNETES_NAMESPACE_LABEL=false`.
====
