
[id="configuring-namespace-strategies_{context}"]
= Configuring {orch-namespace} strategies

ifeval::["{project-context}" == "che"]
NOTE: The term _{orch-namespace}_ ({kubernetes}) is used interchangeably with _project_ (OpenShift).
endif::[]

The {platforms-namespace} strategies are configured using the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` environment variable.

WARNING: `CHE_INFRA_KUBERNETES_NAMESPACE` and `CHE_INFRA_OPENSHIFT_PROJECT` are legacy variables. Keep these variables unset for a new installations. Changing these variables during an update can lead to data loss.

== One {orch-namespace} per workspace strategy

The strategy creates a new {orch-namespace} for each new workspace.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must contain the `_<workspaceID>_` identifier. It can be used alone or combined with other identifiers or any string.

.One {orch-namespace} per workspace
====
To assign {orch-namespace} names composed of a __`{prod-workspace}`__ prefix and workspace id, set:

[subs="+quotes,+attributes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=__{prod-workspace}__-__<workspaceID>__
----
====

== One {orch-namespace} for all workspaces strategy

The strategy uses one predefined {orch-namespace} for all workspaces.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must be the name of the desired {orch-namespace} to use.

.One {orch-namespace} for all workspaces
====
To have all workspaces created in __`{prod-workspace}`__ {orch-namespace}, set:

[subs="+quotes,+attributes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=__{prod-workspace}__
----
====

IMPORTANT: To run more than one workspace at a time when using this strategy together with the `common` PVC strategy, configure persistent volumes to use `ReadWriteMany` access mode.

== One {orch-namespace} per user strategy

The strategy isolates each user in their own {orch-namespace}.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must contain one or more user identifiers. Currently supported identifiers are `_<username>_` and `_<userId>_`.

.One {orch-namespace} per user
====
To assign {orch-namespace} names composed of a __`{prod-workspace}`__ prefix and individual usernames (`__{prod-workspace}__-user1`, `__{prod-workspace}__-user2`), set:

[subs="+quotes,+attributes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=__{prod-workspace}__-__<username>__
----
====

[IMPORTANT]
====
To run more than one workspace at a time when using this strategy together with the `common` PVC strategy, configure persistent volumes to use `ReadWriteMany` access mode.

To limit the number of concurrently running workspaces per user to one, set the `CHE_LIMITS_USER_WORKSPACES_RUN_COUNT` environment variable to `1`.

// Links to Helm and Operator docs need to be added below:

To limit the number of concurrently running workspaces per user to one (1):
ifeval::["{project-context}" == "che"]

* For Helm Chart deployments: set the `.global.workspace.number` parameter to `1`.
endif::[]

* For Operator deployments: set the `spec.server.cheCustomProperties.CHE_LIMITS_USER_WORKSPACE_RUN_COUNT` variable of the CheCluster Custom Resource (CR) to `1`.
====

== Allowing user-defined workspace {orch-namespace}s

{prod-short} server can be configured to honor the user selection of a {orch-namespace} when a workspace is created. This feature is disabled by default. To allow user-defined workspace {orch-namespace}s:

ifeval::["{project-context}" == "che"]
* For Helm Chart deployments, set the following environment variable in the {prod-short} ConfigMap:
+
----
CHE_INFRA_KUBERNETES_NAMESPACE_ALLOW__USER__DEFINED=true
----
endif::[]

* For Operator deployments, set the following field in the CheCluster Custom Resource:
+
----
allowUserDefinedWorkspaceNamespaces
----

== Pre-create {orch-namespace}s for users

To pre-create {orch-namespace}s for users, use {orch-namespace} labels.

----
metadata:
  labels:
    app.kubernetes.io/component: workspace
    app.kubernetes.io/part-of: che.eclipse.org
    che.eclipse.org/username: <username>  <1>
----
<1> target user's username

To configure the labels, set the `CHE_INFRA_KUBERNETES_NAMESPACE_LABELS` to desired labels. See the xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc#che-server-component-system-properties-reference_advanced-configuration-options-for-the-che-server-component[Che server component system properties reference] for more details.

[IMPORTANT]
====
On OpenShift with OAuth, target user must have `admin` role privileges in target namespace:
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: <namespace> <1>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: <username> <2>
----
<1> pre-created namespace
<2> target user

On Kubernetes, `che` ServiceAccount must have cluster-wide `list namespaces` privilege as well as `admin` role in target namespace.
====
