

// installing-che-on-openshift-3-using-the-operator

[id="installing-{prod-id-short}-on-openshift-3-using-the-operator_{context}"]
= Installing {prod-short} on OpenShift 3 using the Operator

This section describes how to install {prod-short} on OpenShift 3 with the `{prod-cli}` CLI management tool. The method of installation is using the Operator and enable TLS (HTTPS). 

[NOTE]
====
Methods for updating from a previous {prod-short} installation and enabling multiple instances in the same {ocp} {ocp3-ver} cluster are provided below the installation procedure.
====

Operators are a method of packaging, deploying, and managing a Kubernetes application which also provide the following:

* Repeatability of installation and upgrade.
* Constant health checks of every system component.
* Over-the-air (OTA) updates for OpenShift components and independent software vendor (ISV) content.
* A place to encapsulate knowledge from field engineers and spread it to all users.

[TIP]
====
This approach is only supported for use with {ocp} and {osd} version 3.11, but also work for newer versions of {ocp} and {osd}, and serves as a backup installation method for situations when the installation method using OperatorHub is not available.
====

.Prerequisites

* Administrator rights on a running instance of OpenShift 3.11.

* An installation of the `oc` OpenShift 3.11 CLI management tool. See link:https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html#installing-the-cli[Installing the OpenShift 3.11 CLI].

* An installation of the `{prod-cli}` management tool. See xref:using-the-chectl-management-tool.adoc[].

* To apply settings that the main {prod-cli} command-line parameters cannot set, prepare a configuration file `operator-cr-patch.yaml` that will override the default values in the `CheCluster` Custom Resource used by the Operator. See xref:installation-guide:configuring-the-che-installation.adoc[].

* __<namespace>__ represents the project of the target installation.

.Procedure

. Log in to OpenShift. See link:https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html#basic-setup-and-login[Basic Setup and Login].
+
[subs="+attributes,+quotes",options="nowrap"]
----
$ oc login
----

. Run the following command to verify that the version of the `oc` OpenShift CLI management tool is 3.11:
+
[subs="+attributes,+quotes",options="nowrap"]
----
$ oc version
oc v3.11.0+0cbc58b
----

. Run the following command to create the {prod-short} instance
+
** In the user-defined _<namespace>_:
+
[subs="+quotes,+attributes",options="nowrap"]
----
$ {prod-cli} server:start -n _<namespace>_ -p openshift
----

** In the default {orch-namespace} called {prod-namespace}:
+
[subs="+quotes,+attributes",options="nowrap"]
----
$ {prod-cli} server:start -p openshift
----


.Verification steps

. The output of the previous command ends with:
+
----
Command server:start has completed successfully.
----

. Navigate to the {prod-short} cluster instance: `pass:c,a,q[{prod-url}]`. The domain uses _Let’s Encrypt_ ACME certificates.


.Upgrading from a previous {prod-short} installation

* To upgrade from a previous {prod-short} installation in the same {ocp} {ocp3-ver} cluster, remove the Custom Resource Definition and the Cluster Roles:
+
[subs="+attributes,+quotes",options="nowrap"]
----
$ oc delete customresourcedefinition/checlusters.org.eclipse.che
$ oc patch customresourcedefinition/checlusters.org.eclipse.che \
    --type merge \
    -p '{ "metadata": { "finalizers": null }}'
$ oc delete clusterrole {prod-operator}
----

.Having multiple {prod-short} deployments

* To have multiple {prod-short} deployments in parallel using different versions in the same {ocp} {ocp3-ver} cluster, create a new service account for the new deployment. It is, however, strongly recommended that you update all your old {prod-short} deployments to the latest version instead, as this mix of versions may cause unexpected and unsupported results.
+
[subs="+attributes,+quotes",options="nowrap"]
----
$ oc patch clusterrolebinding {prod-operator} \
    --type='json' \
    -p '[{"op": "add", "path": "/subjects/0", "value": {"kind":"ServiceAccount", "namespace": "__<{prod-namespace}>__", "name": "{prod-operator}"} }]'
----
