

[id="importing-tls-certificates-to-{prod-id-short}-server-java-trustore_{context}"]
= Importing TLS certificates to {prod-short} server Java truststore

When {prod-short} server attempts to send an HTTPS request to an external service as {identity-provider}, a proxy or a git server, the connection fails if {prod-short} does not trust the TLS certificate used by the external service.

To fix this problem, configure {prod-short} to authorize HTTPS communication with external services, such as identity and Git servers, by adding information about the TLS certificates to the {prod-short} configuration.

.Prerequisites

* The `{orch-cli}` tool is available.

.Procedure

. Save the external services certificates to a local file system.

. Create a new configMap with the required TLS certificates:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} create configmap __<configMap-name>__ --from-file=__<certificate-file-path>__ -n=__<{project-context}-namespace-name>__
----
+
To apply more than one certificate, add another `--from-file=_<certificate-file-path>_` option to the above command.

. Update the existing {prod-short} server configuration
+
NOTE: Use these steps with existing instances of {prod-short}. To install a new instance of {prod-short} with self-signed TLS certificates, create a new `CheCluster` Custom Resource or Helm Chart property, based on the installation method selected, instead of updating the existing configuration.
+
====
** For a {prod-short} link:https://docs.openshift.com/container-platform/latest/operators/olm-what-operators-are.html[Operators] deployment:

* Define a name for the newly created configMap by editing the `spec.server.ServerTrustStoreConfigMapName` `CheCluster` Custom Resource property to match the previously created configMap:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} patch checluster {prod-checluster} -n che --type=json -p '[{"op": "replace", "path": "/spec/server/serverTrustStoreConfigMapName", "value": "__<config-map-name>__"}]'
----
====
+
ifeval::["{project-context}" == "che"]
====
** For a {prod-short} link:https://helm.sh/[Helm Chart] deployment: 
+
. Clone the https://github.com/eclipse/che[che] project.
. Go to the `deploy/kubernetes/helm/che` directory.
. Define a name for the newly created configMap by editing the `global.tls.serverTrustStoreConfigMapName` Helm Chart property to match the previously created configMap:
+
[subs="+quotes",options="nowrap",role=white-space-pre]
----
$ helm upgrade che -n che --set global.tls.serverTrustStoreConfigMapName=__<config-map name>__ \
   --set global.ingressDomain=__<kubernetes-cluster-domain>__ .
----
+
When using Minikube to run {prod-short}, substitute _<kubernetes-cluster-domain>_ with `$(minikube ip).nip.io`.
====
endif::[]

.Verification 

If the certificates have been added correctly, the {prod-short} server starts and obtains {identity-provider} configuration over HTTPS. Otherwise here is a list of things to verify: 

- CheCluster attribute `serverTrustStoreConfigMapName` value matches the name of the ConfigMap. Get the value using the following command :
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get -o json checluster/{prod-checluster} -n {prod-namespace} | jq .spec.server.serverTrustStoreConfigMapName
----
+
- {prod-short} Pod Volumes list contains one Volume that uses the ConfigMap as data-source. To get the list of Volumes of the {prod-short} Pod:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get po -o json __<{prod-id-short}-pod-name>__ -n {prod-namespace} | jq .spec.volumes
----
+
- Certificates are mounted in folder `/public-certs/` of the {prod-short} server container. This command returns the list of files in that folder:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} exec -t __<{prod-id-short}-pod-name>__ -n {prod-namespace} -- ls /public-certs/
----
+
- In the {prod-short} server logs there is a line for every certificate added to the Java truststore, including {prod-short} self signed certificate.
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} logs __<{prod-id-short}-pod-name>__ -n {prod-namespace}
(...)
Found a custom cert. Adding it to java trust store based on /usr/lib/jvm/java-1.8.0/jre/lib/security/cacerts
(...)
----
+
- ${prod-short} server Java trustore contains the certificates. The certificates SHA1 fingerpints are among the list of the SHA1 of the certificates included in the trustore returned by the following command:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} exec -t __<{prod-id-short}-pod-name>__ -n {prod-namespace} -- keytool -list -keystore /home/che/cacerts
Your keystore contains 141 entries

(...)
----
+
To get the SHA1 hash of a certificate on the local filesystem:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ openssl x509 -in __<certificate-file-path>__ -fingerprint -noout
SHA1 Fingerprint=3F:DA:BF:E7:A7:A7:90:62:CA:CF:C7:55:0E:1D:7D:05:16:7D:45:60
----
