// Module included in the following assemblies:
//
// configuring-workspace-exposure-strategies

[id="configuring-workspace-exposure-strategies-using-an-operator_{context}"]
= Configuring workspace exposure strategies using an Operator

link:https://docs.openshift.com/container-platform/latest/operators/olm-what-operators-are.html[Operators] are software extensions to {platforms-name} that use link:https://docs.openshift.com/container-platform/latest/operators/understanding/crds/crd-managing-resources-from-crds.html[Custom Resources] to manage applications and their components.

.Prerequisites

* The `{orch-cli}` tool is available.

.Procedure

When deploying {prod-short} using the Operator, configure the intended strategy by modifying the `spec.server.serverExposureStrategy` and  optionally `spec.k8s.singleHostExposureType` properties of the CheCluster Custom Resource object YAML file.

To activate changes done to CheCluster YAML file, do one of the following:

* Create a new cluster by executing the `{prod-cli}` command with applying a patch. For example:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:deploy  --installer=operator --platform=__<platform>__ \
  --che-operator-cr-patch-yaml=patch.yaml
----
+
[NOTE]
====
For a list of available {platforms-name} deployment platforms, use `{prod-cli} server:deploy --platform --help`.
====
+
ifeval::["{project-context}" == "che"]
* For the `native` single-host exposure type, use the following `patch.yaml` file:
+
[source,yaml,subs="+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: '__single-host__'
  k8s:
    singleHostExposureType: 'native'
----
endif::[]
+
* For the `gateway` type, use the following `patch.yaml`:
+
[source,yaml,subs="+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: 'single-host'
  k8s:
    singleHostExposureType: 'gateway'
----


* Update the YAML file properties of an already running cluster by executing the `{orch-cli} patch` command. For example:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} patch checluster {prod-checluster} --type=json \
  -p '[{"op": "replace", "path": "/spec/server/serverExposureStrategy", "value": "__single-host__"}] -n __<namespace-name>__'
----
+
Depending on the strategy used, replace the `_single-host_` option in the above example with `multi-host`
ifeval::["{project-context}" == "che"]
 or `default-host`
endif::[]
.
+
To change the `single-host` type, too, use:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} patch checluster {prod-checluster} --type=json \
  -p '[{"op": "replace", "path": "/spec/server/serverExposureStrategy", "value": "single-host"}, {"op": "replace", "path": "/spec/k8s/singleHostExposureType", "value": "gateway"}]' \
  -n _<namespace-name>_
----
