// Module included in the following assemblies:
//
// upgrading-che-using-operatorhub

[id="manually-upgrading-che-in-operatorhub_{context}"]
= Manually upgrading {prod-short} in OperatorHub

OperatorHub is ab assembly point designed to share Operators, which will help you deploy and update the desired application. The following section describes the process of upgrading {prod-short} from OperatorHub using the `Manual` approval strategy approach. The `Manual` approval strategy is useful when a user does not want to update an Operator with every release automatically.

.Prerequisites

* An administrator account on an instance of OpenShift.

* An instance of an earlier minor version of {prod-short}. You have installed the instance by using the Operator.

* The approval strategy in the subscription is `Manual`.

.Procedure

. Open the OpenShift web console.

. Navigate to the *Operators* -> *Installed Operators* page.

. In the list of the installed Operators, click *{prod}*.

. Navigate to the *Subscription* tab. 

. Next to the *Upgrade Status*, inspect the upgrades that require approval. The expected message is *1 requires approval*.

. Click *1 requires approval*.

. Click *Preview Install Plan*.

. Review the resources that are available for upgrade and click *Approve*.

.Verification steps

. Navigate to the *Operators* -> *Installed Operators* page.

. Monitor the upgrade progress. When complete, the status changes to *Succeeded* and *Up to date*. The {prod-ver} version number is visible at the end of the page.
