// Module included in the following assemblies:
//
// upgrading-{prod-id-short}

[id="upgrading-che-using-the-cli-management-tool-in-restricted-environment_{context}"]
= Upgrading {prod-short} using the CLI management tool in restricted environment

This section describes how to upgrade from previous minor version using the CLI management tool in restricted environment.

[NOTE]
====
.The following method of upgrading an older version of {prod-short} in restricted environment is:
 
* specific to OpenShift 3.11 and 4.x, but is relevant only when the existing instance has been installed using the {prod-cli} `--installer operator` method, which is the default installation method for OpenShift 3.11.

ifeval::["{project-context}" == "che"]
* available for instances deployed on Kubernetes.
endif::[]
====

.Prerequisites

* An administrative account on an OpenShift instance.

* A running instance of a previous minor version of {prod}, installed using the CLI management tool on the same instance of OpenShift, in the `_<{prod-namespace}>_` project.

* Essential container images are available to the {prod-short} server running in the cluster. See xref:pulling-images-used-by-che-to-a-private-registry.adoc[].

* The `{prod-cli}` {prod-ver} management tool is installed. See xref:overview:using-the-chectl-management-tool.adoc[].

.Procedure

. In all running workspaces in the {prod-short} {prod-prev-ver} instance, save and push changes back to the Git repositories.

. Terminate all workspaces in the {prod-short} {prod-prev-ver} instance.

. Run the following command:
+
[subs="+attributes,+quotes"]
----
$ {prod-cli} server:update --che-operator-image=__<image-registry>__/__<organization>__/{prod-operator-image-name}:{prod-ver} -n {prod-namespace}
----
+
* _<image-registry>_: A host name and a port of the container-image registry accessible in the restricted environment.
* _<organization>_: An organization of the container-image registry. See: xref:pulling-images-used-by-che-to-a-private-registry.adoc[].

.Verification steps

. Navigate to the {prod-short} instance.

. The {prod-ver} version number is visible at the bottom of the page.


////
.Additional resources

* A bulleted list of links to other material closely related to the contents of the procedure module.
* Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
