//This module is included in
//
// * assembly_installing-che-using-the-che-operator-in-openshift-4-web-console

[id="installing-the-che-operator_{context}"]
= Installing the {prod} Operator

{prod} Operator provides with all the resources for running {prod-short} such as PostgreSQL, Keycloak, Registries and the {prod-short} server, as well as configures all these services.

.Prerequisites

* Access to the Web Console on the cluster.

.Procedure

. To install the {prod} Operator, in the left panel, navigate to the *Operators* -> *OperatorHub* section.

. In the *Filter by keyword* field, type `{prod}` and click the *{prod}* tile.

. In the *{prod}* pop-up window, click the btn:[Install] button.

. On the *Install Operator* screen, specify the following options:
+
* *Installation mode*: *A specific {orch-namespace} on the cluster*
* *Installed Namespace*: *Pick an existing namespace* -> `{prod-namespace}`

.Verification steps

. To verify the {prod} Operator has installed correctly, in the left panel navigate to the *Operators* -> *Installed Operators* section.

. In the *Installed Operators* screen, click the *{prod}* name and navigate to the *Details* tab.

. In the *ClusterServiceVersion Details* section at the bottom of the page, wait for these messages:
+
* *Status*: `Succeeded`
* *Status Reason*: `install strategy completed with no errors`

. Navigate to the *Events* tab and wait for this message: `install strategy completed with no errors`.
