

// installing-che-on-openshift-3-using-the-operator

[id="installing-{prod-id-short}-on-openshift-3-using-the-operator_{context}"]
= Installing {prod-short} on OpenShift 3 using the Operator

This section describes how to install {prod-short} on OpenShift 3 with the `{prod-cli}` CLI management tool. The method of installation is using the Operator and enable TLS (HTTPS).

[NOTE]
====
Methods for updating from a previous {prod-short} installation and enabling multiple instances in the same {ocp} {ocp3-ver} cluster are provided below the installation procedure.
====

Operators are a method of packaging, deploying, and managing a {platforms-name} application which also provide the following:

* Repeatability of installation and upgrade.
* Constant health checks of every system component.
* Over-the-air (OTA) updates for OpenShift components and independent software vendor (ISV) content.
* A place to encapsulate knowledge from field engineers and spread it to all users.

[NOTE]
====
This approach is only supported for use with {ocp} and {osd} version 3.11, but also work for newer versions of {ocp} and {osd}, and serves as a backup installation method for situations when the installation method using OperatorHub is not available.
====

.Prerequisites

* Administrator rights on a running instance of OpenShift 3.11.

* An installation of the `oc` OpenShift 3.11 CLI management tool. See link:https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html#installing-the-cli[Installing the OpenShift 3.11 CLI].

* An installation of the `{prod-cli}` management tool. See xref:using-the-chectl-management-tool.adoc[].

* To apply settings that the main {prod-cli} command-line parameters cannot set, prepare a configuration file `operator-cr-patch.yaml` that will override the default values in the `CheCluster` Custom Resource used by the Operator. See xref:configuring-the-che-installation.adoc[].

* Use the {prod-namespace} namespace as the default installation project.

* Configure OpenShift to pull images from `registry.redhat.com`. See link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].

.Procedure

. Log in to OpenShift. See link:https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html#basic-setup-and-login[Basic Setup and Login].
+
[subs="+attributes,+quotes",options="nowrap"]
----
$ oc login
----

. Run the following command to verify that the version of the `oc` OpenShift CLI management tool is 3.11:
+
[subs="+attributes,+quotes",options="nowrap"]
----
$ oc version
oc v3.11.0+0cbc58b
----

. Run the following command to create the {prod-short} instance in the default {orch-namespace} called {prod-namespace}:
+
[subs="+quotes,+attributes",options="nowrap"]
----
$ {prod-cli} server:deploy -p openshift
----

.Verification steps

. The output of the previous command ends with:
+
----
Command server:deploy has completed successfully.
----

. Navigate to the {prod-short} cluster instance: `pass:c,a,q[{prod-url}]`.
