[id="using-the-operator-to-configure-communication-between-{prod-id-short}-components_{context}"]
= Using the Operator to configure communication between {prod-short} components

To change between external and internal inter-component communication, update the Custom Resource.

.Prerequisites

* An instance of {prod-short} running on {platforms-name}.
* You have installed {prod-short} by using the Operator.

.Procedure

* Configure the `__<property-value>__` value of the `disableInternalClusterSVCNames` property in the CheCluster Custom Resource server settings. Set the value of `__<property-value>__` to:
[horizontal]
`true`:: To use external {platforms-ingress}.
`false`:: To use internal {orch-name} DNS names.

+
====
[source,yaml,subs="+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# ...
spec:
  server:
    # ...
    disableInternalClusterSVCNames: __<property-value>__
----
====

.Verification steps
. Specify {prod-short} as the default project:
+
[subs="+quotes,attributes"]
----
$ {orch-cli} project {prod-namespace}
----
. Inspect the ConfigMap properties to determine, which communication method {prod-short} uses. Run the following commands and take note of the output:
+
[subs="+quotes,attributes,macros"]
----
$ {orch-cli} get configmap che -o \ 
jsonpath='{.data.pass:[CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL]}'
$ {orch-cli} get configmap che -o \ 
jsonpath='{.data.pass:[CHE_WORKSPACE_PLUGIN__REGISTRY__INTERNAL__URL]}'
----
* If {prod-short} components communicate externally, the output is empty.
* If {prod-short} components communicate internally, the output is following:
+
----
http://keycloak.eclipse-che.svc:8080/auth
http://plugin-registry.eclipse-che.svc:8080/v3
----
