// Module included in the following assemblies:
//
// upgrading-che-using-operatorhub

[id="manually-upgrading-{prod-id-short}-in-operatorhub_{context}"]
= Manually upgrading {prod-short} in OperatorHub

OperatorHub is an assembly point for sharing Operators. The OperatorHub helps you deploy and update applications. The following section describes the process of upgrading {prod-short} by using OperatorHub and the `Manual` approval strategy approach. Use the `Manual` approval strategy to prevent automatic updates of the Operator with every release.

.Prerequisites

* An administrator account on an instance of OpenShift.

* An instance of {prod-short} {prod-prev-ver} or earlier that was installed by using OperatorHub.

* The approval strategy in the subscription is `Manual`.

.Procedure

. Open the OpenShift web console.

. Navigate to the *Operators* -> *Installed Operators* page.

. In the list of the installed Operators, click *{prod}*.

. Navigate to the *Subscription* tab. 

. Next to the *Upgrade Status*, inspect the upgrades that require approval. The expected message is *1 requires approval*.

. Click *1 requires approval*.

. Click *Preview Install Plan*.

. Review the resources that are available for upgrade and click *Approve*.

.Verification steps

. Navigate to the *Operators* -> *Installed Operators* page.

. Monitor the upgrade progress. When complete, the status changes to *Succeeded* and *Up to date*. The {prod-ver} version number is visible at the end of the page.
