// Module included in the following assemblies:
//
// advanced-configuration

[id="defining-the-number-of-workspaces-a-user-can-run-using-the-operator_{context}"]
= Defining the number of workspaces a user can run using the Operator

This procedure describes how to run more than one workspace simultaneously using the Operator. 

//This makes it possible for multiple workspace contexts per user to run in parallel.
//TODO: fix second sentence
// pvc persistent volume claim

.Procedure

. Set the `per-workspace` or `unique` PVC strategy if the underlying storage backend does not support or is not configured to use the `ReadWriteMany` access mode. See xref:configuring-storage-strategies.adoc[].
+
IMPORTANT: The default `common` PVC strategy, which uses a single PVC per user, supports running multiple workspaces simultaneously only if the persistent volumes on the cluster are configured to use the `ReadWriteMany` access mode.
That way, any of the user's concurrent workspaces can read from and write to the common PVC. 
In some cases, configuring `ReadWriteMany` is not possible due to the storage limitations, for example, link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html[EBS] only supports `ReadWriteOnce` access mode. 
. In `CheCluster` Custom Resource `server` settings, add the `+CHE_LIMITS_USER_WORKSPACES_RUN_COUNT+` property to `customCheProperties`:
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "1"
----
====

Change the default limit of `1` to `-1` to allow an unlimited number of concurrent workspaces, or to the precise value, for example, `10` to allow running `10` concurrent workspaces per user simultaneously.


