// Module included in the following assemblies:
//
// configuring-workspace-exposure-strategies

[id="configuring-workspace-exposure-strategies-using-an-operator_{context}"]
= Configuring workspace exposure strategies using an Operator

link:https://docs.openshift.com/container-platform/latest/operators/olm-what-operators-are.html[Operators] are software extensions to {platforms-name} that use link:https://docs.openshift.com/container-platform/latest/operators/understanding/crds/crd-managing-resources-from-crds.html[Custom Resources] to manage applications and their components.

.Prerequisites

* The `{orch-cli}` tool is available.

.Procedure

When deploying {prod-short} using the Operator, configure the intended strategy by modifying the `spec.server.serverExposureStrategy` property of the CheCluster Custom Resource object YAML file.

The supported values for `spec.server.serverExposureStrategy` are:

* xref:multi-host-workspace-exposure-strategy_{context}[`multi-host`]
* xref:single-host-workspace-exposure-strategy_{context}[`single-host`]
ifeval::["{project-context}" == "che"]
* xref:default-host-workspace-exposure-strategy_{context}[`default-host`]
endif::[]

See xref:workspace-exposure-strategies_{context}[] for more detail about individual strategies.

To activate changes done to CheCluster YAML file, do one of the following:

* Create a new cluster by executing the `{prod-cli}` command with applying a patch. For example:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:deploy  --installer=operator --platform=__<platform>__ \
  --che-operator-cr-patch-yaml=patch.yaml
----
+
[NOTE]
====
For a list of available {platforms-name} deployment platforms, use `{prod-cli} server:deploy --platform --help`.
====
+

** Use the following `patch.yaml` file:
+
[source,yaml,subs="+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: '__<exposure-strategy>__' <1>
----
<1> - used workspace exposure strategy


* Update the YAML file properties of an already running cluster by executing the `{orch-cli} patch` command. For example:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} patch checluster {prod-checluster} --type=json \
  -p '[{"op": "replace",
  "path": "/spec/server/serverExposureStrategy",
  "value": "__<exposure-strategy>__"}]' \ <1>
  -n {prod-namespace}
----
<1> - used workspace exposure strategy

ifeval::["{project-context}" == "che"]

.Gateway single-host on Kubernetes
Single-host on Kubernetes has two implementations, `native`(default) and `gateway`. To deploy with `gateway` set the `k8s.singleHostExposureType` of CheCluster Custom Resource to `gateway`, or use this patch:

[source,yaml,subs="+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: 'single-host'
  k8s:
    singleHostExposureType: 'gateway'

----

endif::[]
