// Module included in the following assemblies:
//
// mounting-a-secret-or-a-configmap-as-a-file-or-an-environment-variable-into-a-container

[id="mounting-a-secret-or-a-configmap-as-an-environment-variable-into-a-container_{context}"]
= Mounting a Secret or a ConfigMap as an environment variable into a {prod-short} container

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see {link-installing-an-instance}.

.Procedure

. Create a new {platforms-name} Secret or a ConfigMap in the {platforms-name} {orch-namespace} where a {prod-short} is deployed. The labels of the object that is about to be created must match the set of labels:
+
* `app.kubernetes.io/part-of: che.eclipse.org`
* `app.kubernetes.io/component: <DEPLOYMENT_NAME>-<OBJECT_KIND>`
+
* The `<DEPLOYMENT_NAME>` coresponds to the one following deployments:

** `postgres`
** `keycloak`
** `devfile-registry`
** `plugin-registry`
** `{prod-deployment}` 
+
and
+
* `<OBJECT_KIND>` is either:
+
** `secret`
+
or
+ 
** `configmap`

// The following content is downstream friendly

.Example:
====
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: {prod-deployment}-secret
...
----
or
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-settings
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: {prod-deployment}-secret
...
----
====
Annotations must indicate that the given object is mounted as a environment variable. Configure the annotation values:

* `che.eclipse.org/mount-as: env` - to indicate that a object is mounted as an environment variable
* `che.eclipse.org/env-name: _<FOO_ENV>_` - to provide an environment variable name, which is required to mount a object key value

.Example:
====
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----
or
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----
====

This results in the environment variable named `FOO_ENV` and the value `myvalue` being provisioned into a {prod-short} container.

If the object provides more than one data item, the environment variable name must be provided for each of the data keys as follows:

.Example:
====
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: __<base64 encoded data content here>__
  otherkey: __<base64 encoded data content here>__
----
or
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: __<data content here>__
  otherkey: __<data content here>__
----
====

This results in two environment variables:

* `FOO_ENV`
* `OTHER_ENV`

being provisioned into a {prod-short} container.

NOTE: The maximum length of annotation names in a {orch-name} object is 63 characters, where 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the object.
