// Module included in the following assemblies:
//
// advanced-configuration

[id="defining-the-number-of-workspaces-a-user-can-run-using-the-operator_{context}"]
= Defining the number of workspaces a user can run using the Operator

This procedure describes how to run more than one workspace simultaneously using the Operator. 

.Placeholders used in examples
[cols="1,2"]
|===
| `_<number-of-workspaces>_`
| The number of workspaces to run simultaneously. The default value is `1`. Set the value to `-1` to allow the user to run an unlimited number of concurrent workspaces. Set it to a precise value to allow running that many concurrent workspaces.
|===

.Procedure
. If the Persistent Volume Claim (PVC) strategy of the cluster is `common`, configure the persistent volumes of the cluster to use the `ReadWriteMany` access mode.
+
If you are unable to use the `ReadWriteMany` access mode, configure the PVC strategy to `per-workspace` or `unique`. 
+
For more information, see xref:configuring-storage-strategies.adoc[].
+
[NOTE] 
==== 
In some cases, using the `ReadWriteMany` access mode is not possible due to the storage limitations. For example, link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html[EBS] only supports `ReadWriteOnce` access mode. 
====
. In `CheCluster` Custom Resource `server` settings, add the `+CHE_LIMITS_USER_WORKSPACES_RUN_COUNT+` property to `customCheProperties`:
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "<number-of-workspaces>"
----
====



