[id="configuring-communication-between-{prod-id-short}-components_{context}"]
= Configuring communication between {prod-short} components

You can select whether {prod-short} components communicate by using the internal network or external {platforms-ingress}. 

By default, {prod-short} components communicate by using the internal network. {prod-short} components use their internal services names, which are exposed in the internal {platforms-name} network.

As the administrator, you must disable the use of the internal services names to force the {prod-short} components to use external {platforms-ingress} in the following situations:

* To deploy {prod-short} across multiple {platforms-name} clusters. The internal services names are not shared between distinct clusters.
* To deploy {prod-short} across multiple namespaces. The {orch-name} NetworkPolicies restricts communication between namespaces.
* To deploy {prod-short} with the multitenant network plugin.

[IMPORTANT]
====
Using the external {platforms-ingress} might slow the traffic and lead to issues because it uses proxies, certificates, and firewalls.
====

.Prerequisites

* An instance of {prod-short} running on {platforms-name}.
* You have installed {prod-short} by using the Operator.

.Procedure

* In the CheCluster Custom Resource server settings, for the `disableInternalClusterSVCNames` property, set `__<property-value>__` to:
[horizontal]
`true`:: To use external {platforms-ingress}.
`false`:: To use internal {orch-name} DNS names.

+
====
[source,yaml,subs="+quotes"]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# ...
spec:
  server:
    # ...
    disableInternalClusterSVCNames: __<property-value>__
----
====

.Verification steps
. Specify {prod-short} as the default project:
+
[subs="+quotes,attributes"]
----
$ {orch-cli} project {prod-namespace}
----
. Inspect the ConfigMap properties to determine which communication method {prod-short} uses:
+
[subs="+quotes,attributes,macros"]
----
$ {orch-cli} get configmap che -o \ 
jsonpath='{.data.pass:[CHE_KEYCLOAK_AUTH__INTERNAL__SERVER__URL]}'
$ {orch-cli} get configmap che -o \ 
jsonpath='{.data.pass:[CHE_WORKSPACE_PLUGIN__REGISTRY__INTERNAL__URL]}'
----
* If {prod-short} components communicate internally, the output is following:
+
----
http://keycloak.eclipse-che.svc:8080/auth
http://plugin-registry.eclipse-che.svc:8080/v3
----
* Otherwise, if the components communicate externally, the output is empty.
