// Module included in the following assemblies:
//
// mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container

[id="mounting-a-secret-as-an-environment-variable-into-a-container_{context}"]
= Mounting a secret as an environment variable into a {prod} container

.Prerequisites

* A running instance of {prod}. To install an instance of {prod}, see {link-installing-an-instance}.

.Procedure

. Create a new {platforms-name} secret in the {platforms-name} {orch-namespace} where a {prod-short} is deployed. The labels of the secret that is about to be created must match the set of labels:

* `app.kubernetes.io/part-of: che.eclipse.org`
* `app.kubernetes.io/component: <DEPLOYMENT_NAME>-secret`

Where `<DEPLOYMENT_NAME>` is one of the following deployments: `postgres`, `keycloak`, `devfile-registry`, `plugin-registry` or `{prod-deployment}`

// The following content is downstream friendly

.Example:
====
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: {prod-deployment}-secret
...
----


Annotations must indicate that the given secret is mounted as a environment variable. Set up the annotation values:

* `che.eclipse.org/mount-as: env` - to indicate that a secret is mounted as an environment variable
* `che.eclipse.org/env-name: _<FOO_ENV>_` - to provide an environment variable name, which is required to mount a secret key value


[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/env-name: FOO_ENV
    che.eclipse.org/mount-as: env
  labels:
   ...
data:
  mykey: myvalue
----

This results in the environment variable named `FOO_ENV` and the value `myvalue` being provisioned into a {prod-short} container.

If the secret provides more than one data item, the environment variable name must be provided for each of the data keys as follows:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: custom-settings
  annotations:
    che.eclipse.org/mount-as: env
    che.eclipse.org/mykey_env-name: FOO_ENV
    che.eclipse.org/otherkey_env-name: OTHER_ENV
  labels:
   ...
data:
  mykey: myvalue
  otherkey: othervalue
----

This results in two environment variables with names `FOO_ENV`, `OTHER_ENV`, and values `myvalue` and `othervalue`, being provisioned into a  {prod-short} container.

NOTE: The maximum length of annotation names in a {orch-name} secret is 63 characters, where 9 characters are reserved for a prefix that ends with `/`. This acts as a restriction for the maximum length of the key that can be used for the secret.

====
