// Module included in the following assemblies:
//
// advanced-configuration

[id="switching-between-external-and-internal-communication_{context}"]
= Switching between external and internal DNS names in inter-component communication

By default, new {prod-short} deployments use {orch-name} services DNS names for communications between {prod-short} server, {identity-provider}, registries, and helps with:

* Bypassing proxy, certificates, and firewalls issues
* Speeding up the traffic

This type of communication is an alternative to the external method of inter-component communication, which uses {platforms-ingress} cluster host names. In the situations described below, using {orch-name} internal DNS names is not supported. By disabling the use of the internal cluster host name in inter-component communication, the communication using external {platforms-ingress} will come into effect.

.Internal inter-component communication restrictions in {platforms-name}

* The {prod-short} components are deployed across multi-cluster {platforms-name} environments.
* The {orch-name} NetworkPolicies restricts communication between namespaces.

The following section describes how to enable and disable the external inter-component communication for {platforms-ingress}.


.Prerequisites

* The `{orch-cli}` tool is available.
* An instance of {prod-short} running in {platforms-name}.


.Procedure

Switching between external and internal inter-component communication method is reached through the update against Custom Resource (CR).

ifeval::["{project-context}" == "che"]
* For {prod-short} deployed using Operators
endif::[]
. To use external {platforms-ingress} in inter-component communication:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} patch checluster/{prod-checluster} -n {prod-namespace} --type=json -p \
'[{"op": "replace", "path": "/spec/server/disableInternalClusterSVCNames", "value": true}]'
----

. To use internal {orch-name} DNS names in the inter-component communication:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} patch checluster/{prod-checluster} -n {prod-namespace} --type=json -p \
'[{"op": "replace", "path": "/spec/server/disableInternalClusterSVCNames", "value": false}]'
----

ifeval::["{project-context}" == "che"]
* For {prod-short} deployed using a Helm Chart

. Clone the https://github.com/eclipse-che/che-server[{prod-short} server] project
. Go to `deploy/kubernetes/helm/che` directory
. Update the `global.useInternalClusterSVCNames` property. To do that, add the following option to the `helm upgrade` command:
- To use external {platforms-ingress} in inter-component communication:
+
[subs="+quotes,+attributes"]
----
$ helm upgrade che -n {prod-namespace} --set global.useInternalClusterSVCNames=false \
-f values/multi-user.yaml -f values/tls.yaml .
----
- To use internal {orch-name} DNS names in the inter-component communication:
+
[subs="+quotes,+attributes"]
----
$ helm upgrade che -n {prod-namespace} --set global.useInternalClusterSVCNames=true  \
-f values/multi-user.yaml -f values/tls.yaml .
----
NOTE: if {prod} has been deployed in single-host mode or without TLS then remove the corresponding flags from the `helm upgrade` command and add others if needed.
endif::[]
