// Module included in the following assemblies:
//
// upgrading-{prod-id-short}

[id="upgrading-{prod-id-short}-using-the-cli-management-tool_{context}"]
= Upgrading {prod-short} using the CLI management tool

This section describes how to upgrade from previous minor version using the CLI management tool.

.Prerequisites

* And administrative account on an OpenShift instance.

* A running instance of a previous minor version of {prod}, installed using the CLI management tool on the same instance of OpenShift, in the `__<{prod-namespace}>__` project.

* An installation of the `{prod-cli}` {prod-ver} version management tool. See xref:overview:using-the-chectl-management-tool.adoc[].

.Procedure

. In all running workspaces in the {prod-short} {prod-prev-ver} instance, save and push changes back to the Git repositories.

. Shut down all workspaces in the {prod-short} {prod-prev-ver} instance.

. Run the following command:
+
[subs="+attributes,+quotes"]
----
$ {prod-cli} server:update --che-operator-image=__<image-registry>/<organization>__/{operator-image-name}:{prod-ver} -n __<{prod-namespace}>__
----
+
* _<internal-registry>_: A host name and a port of the container-image registry accessible in the restricted environment.
* _<organization>_: An organization of the container-image registry. See: xref:preparing-an-image-registry-for-installing-{prod-id-short}-in-a-restricted-environment[].


.Verification steps

. Navigate to the {prod-short} instance.

. The {prod-ver} version number is visible at the bottom of the page.
