//This module is included in
//
// assembly_installing-che-on-openshift-4-using-operatorhub

[id="installing-the-{prod-id-short}-operator_{context}"]
= Installing the {prod} Operator

{prod} Operator provides all the resources for running {prod-short}, such as PostgreSQL, {identity-provider}, image registries, and the {prod-short} server, and it also configures all these services.

.Prerequisites

* Access to the OpenShift web console on the cluster. 

.Procedure

. In the left panel, navigate to the *Operators* -> *OperatorHub* page.

. In the *Filter by keyword* field, enter `{prod}`. 

. Click the *{prod}* tile.

. In the *{prod}* pop-up window, click the btn:[Install] button.

. On the *Install Operator* page, click the btn:[Install] button.

.Verification steps

. To verify that the {prod} Operator has installed correctly, in the left panel, navigate to the *Operators* -> *Installed Operators* page.

. On the *Installed Operators* page, click the *{prod}* name and navigate to the *Details* tab.

. In the *ClusterServiceVersion details* section, wait for the following messages:
+
* *Status*: `Succeeded`
* *Status reason*: `install strategy completed with no errors`

. Navigate to the *Events* tab and wait for the following message: `install strategy completed with no errors`.
