  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_pvc_jobs_image_pull__policy_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Image pull policy of container that used for the maintenance jobs on {orch-name} cluster

// Default value for `+CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY+`:: `+IfNotPresent+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY+` as set by the Operator:: `+IfNotPresent+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY+` as set using the `configMap`:: `+IfNotPresent+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_PVC_JOBS_IMAGE_PULL__POLICY: "IfNotPresent"
----
====


