  
[id="{prod-id-short}-server-parameter-che_workspace_startup__debug__log__limit__bytes_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_STARTUP__DEBUG__LOG__LIMIT__BYTES+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Limit size of the logs collected from single container that can be observed by che-server when debugging workspace startup. default 10MB=10485760

// Default value for `+CHE_WORKSPACE_STARTUP__DEBUG__LOG__LIMIT__BYTES+`:: `+10485760+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_STARTUP__DEBUG__LOG__LIMIT__BYTES+` as set by the Operator:: `+10485760+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_STARTUP__DEBUG__LOG__LIMIT__BYTES+` as set using the `configMap`:: `+10485760+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_STARTUP__DEBUG__LOG__LIMIT__BYTES+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_STARTUP__DEBUG__LOG__LIMIT__BYTES: "10485760"
----
====


