  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_namespace_labels_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_NAMESPACE_LABELS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

List of labels to find {orch-namespace} that are used for {prod-short} Workspaces. They are used to:  - find prepared {orch-namespace} for users in combination with `che.infra.kubernetes.namespace.annotations`.  - actively label {orch-namespace} with any workspace.

// Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_LABELS+`:: `+app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_LABELS+` as set by the Operator:: `+app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_LABELS+` as set using the `configMap`:: `+app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_NAMESPACE_LABELS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: "app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace"
----
====


