  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_namespace_creation__allowed_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Indicates whether {prod-short} server is allowed to create {orch-namespace} for user workspaces, or they're intended to be created manually by cluster administrator. This property is also used by the OpenShift infra.

// Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED+`:: `+true+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED+` as set by the Operator:: `+true+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED+` as set using the `configMap`:: `+true+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED: "true"
----
====


