  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_pvc_storage__class__name_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines the storage class of Persistent Volume Claim for the workspaces. Empty strings means "use default".

// Default value for `+CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME+`:: `+Undefined+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME+` as set by the Operator:: `+Undefined+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME+` as set using the `configMap`:: `+Undefined+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME: "Undefined"
----
====


