  
[id="{prod-id-short}-server-parameter-che_workspace_projects_storage_default_size_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Used when {orch-name}-type components in a devfile request project PVC creation (Applied in case of `unique` and `per workspace` PVC strategy. In case of the `common` PVC strategy, it is rewritten with the value of the `che.infra.kubernetes.pvc.quantity` property.)

// Default value for `+CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE+`:: `+1Gi+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE+` as set by the Operator:: `+1Gi+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE+` as set using the `configMap`:: `+1Gi+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE: "1Gi"
----
====


