  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_namespace_default_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines Kubernetes default namespace in which user's workspaces are created if user does not override it. It's possible to use `<username>` and `<userid>` placeholders (for example: `che-workspace-<username>`). In that case, new namespace will be created for each user (or workspace). Used by OpenShift infra as well to specify a Project. The `<workspaceid>` placeholder is deprecated and is subject to removal in future releases. The `<username>` or `<userid>` placeholder is mandatory.

// Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT+`:: `+<username>-che+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT+` as set by the Operator:: `+<username>-che+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT+` as set using the `configMap`:: `+<username>-che+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: "<username>-che"
----
====


