  
[id="{prod-id-short}-server-parameter-che_workspace_auto__start_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_AUTO__START+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

By default, when users access a workspace with its URL, the workspace automatically starts (if currently stopped). Set this to `false` to disable this behavior.

// Default value for `+CHE_WORKSPACE_AUTO__START+`:: `+true+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_AUTO__START+` as set by the Operator:: `+true+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_AUTO__START+` as set using the `configMap`:: `+true+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_AUTO__START+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_AUTO__START: "true"
----
====


