  
[id="{prod-id-short}-server-parameter-che_factory_default__devfile__filenames_{context}"]
= {prod-short} server parameter: `+CHE_FACTORY_DEFAULT__DEVFILE__FILENAMES+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Devfile filenames to look on repository-based factories (for example GitHub). Factory will try to locate those files in the order they enumerated in the property.

// Default value for `+CHE_FACTORY_DEFAULT__DEVFILE__FILENAMES+`:: `+devfile.yaml,.devfile.yaml+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_FACTORY_DEFAULT__DEVFILE__FILENAMES+` as set by the Operator:: `+devfile.yaml,.devfile.yaml+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_FACTORY_DEFAULT__DEVFILE__FILENAMES+` as set using the `configMap`:: `+devfile.yaml,.devfile.yaml+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_FACTORY_DEFAULT__DEVFILE__FILENAMES+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_FACTORY_DEFAULT__DEVFILE__FILENAMES: "devfile.yaml,.devfile.yaml"
----
====


