  
[id="{prod-id-short}-server-parameter-che_limits_organization_workspaces_ram_{context}"]
= {prod-short} server parameter: `+CHE_LIMITS_ORGANIZATION_WORKSPACES_RAM+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

The total amount of RAM that a single organization (team) is allowed to allocate to running workspaces. An organization owner can allocate this RAM however they see fit across the team's workspaces.

// Default value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_RAM+`:: `+-1+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_RAM+` as set by the Operator:: `+-1+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_RAM+` as set using the `configMap`:: `+-1+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_RAM+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_LIMITS_ORGANIZATION_WORKSPACES_RAM: "-1"
----
====


