  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_pvc_enabled_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_PVC_ENABLED+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines whether use the Persistent Volume Claim for {prod-short} workspace needs, for example: backup projects, logs, or disable it.

// Default value for `+CHE_INFRA_KUBERNETES_PVC_ENABLED+`:: `+true+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_ENABLED+` as set by the Operator:: `+true+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_ENABLED+` as set using the `configMap`:: `+true+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_PVC_ENABLED+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_PVC_ENABLED: "true"
----
====


