  
[id="{prod-id-short}-server-parameter-db_schema_flyway_baseline_version_{context}"]
= {prod-short} server parameter: `+DB_SCHEMA_FLYWAY_BASELINE_VERSION+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Scripts with version up to this are ignored. Note that scripts with version equal to baseline version are also ignored.

// Default value for `+DB_SCHEMA_FLYWAY_BASELINE_VERSION+`:: `+5.0.0.8.1+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+DB_SCHEMA_FLYWAY_BASELINE_VERSION+` as set by the Operator:: `+5.0.0.8.1+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+DB_SCHEMA_FLYWAY_BASELINE_VERSION+` as set using the `configMap`:: `+5.0.0.8.1+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+DB_SCHEMA_FLYWAY_BASELINE_VERSION+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      DB_SCHEMA_FLYWAY_BASELINE_VERSION: "5.0.0.8.1"
----
====


