  
[id="{prod-id-short}-server-parameter-che_server_secure__exposer_jwtproxy_token_issuer_{context}"]
= {prod-short} server parameter: `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_ISSUER+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

`Jwtproxy` issuer string, token lifetime, and optional auth page path to route unsigned requests to.

// Default value for `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_ISSUER+`:: `+wsmaster+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_ISSUER+` as set by the Operator:: `+wsmaster+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_ISSUER+` as set using the `configMap`:: `+wsmaster+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_ISSUER+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_SERVER_SECURE__EXPOSER_JWTPROXY_TOKEN_ISSUER: "wsmaster"
----
====


