  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_singlehost_workspace_exposure_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines the way in which the workspace plugins and editors are exposed in the single-host mode. Supported exposures: `native`:: Exposes servers using Kubernetes Ingresses. Works only on Kubernetes. `gateway`:: Exposes servers using reverse-proxy gateway.

// Default value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE+`:: `+native+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE+` as set by the Operator:: `+native+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE+` as set using the `configMap`:: `+native+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE: "native"
----
====


