  
[id="{prod-id-short}-server-parameter-che_keycloak_cascade__user__removal__enabled_{context}"]
= {prod-short} server parameter: `+CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Configuration for enabling removing user from Keycloak server on removing user from Che database. By default it's disabled. Can be enabled in some special cases when deleting a user in Che database should execute removing related-user from Keycloak. For correct work need to set admin username $\{che.keycloak.admin_username} and password ${che.keycloak.admin_password}.

// Default value for `+CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED+`:: `+false+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED+` as set by the Operator:: `+false+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED+` as set using the `configMap`:: `+false+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_KEYCLOAK_CASCADE__USER__REMOVAL__ENABLED: "false"
----
====


