  
[id="{prod-id-short}-server-parameter-che_organization_email_member__added__template_{context}"]
= {prod-short} server parameter: `+CHE_ORGANIZATION_EMAIL_MEMBER__ADDED__TEMPLATE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

`You've been added to a Che Organization` organization notification template.

// Default value for `+CHE_ORGANIZATION_EMAIL_MEMBER__ADDED__TEMPLATE+`:: `+st-html-templates/user_added_to_organization+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_MEMBER__ADDED__TEMPLATE+` as set by the Operator:: `+st-html-templates/user_added_to_organization+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_MEMBER__ADDED__TEMPLATE+` as set using the `configMap`:: `+st-html-templates/user_added_to_organization+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_ORGANIZATION_EMAIL_MEMBER__ADDED__TEMPLATE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_ORGANIZATION_EMAIL_MEMBER__ADDED__TEMPLATE: "st-html-templates/user_added_to_organization"
----
====


