  
[id="{prod-id-short}-server-parameter-che_oauth_github_redirecturis_{context}"]
= {prod-short} server parameter: `+CHE_OAUTH_GITHUB_REDIRECTURIS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

GitHub OAuth redirect URIs. Separate multiple values with comma, for example: URI,URI,URI

// Default value for `+CHE_OAUTH_GITHUB_REDIRECTURIS+`:: `+http://localhost:${CHE_PORT}/api/oauth/callback+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_OAUTH_GITHUB_REDIRECTURIS+` as set by the Operator:: `+http://localhost:${CHE_PORT}/api/oauth/callback+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_OAUTH_GITHUB_REDIRECTURIS+` as set using the `configMap`:: `+http://localhost:${CHE_PORT}/api/oauth/callback+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_OAUTH_GITHUB_REDIRECTURIS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_OAUTH_GITHUB_REDIRECTURIS: "http://localhost:${CHE_PORT}/api/oauth/callback"
----
====


