  
[id="{prod-id-short}-server-parameter-che_keycloak_oidc__provider_{context}"]
= {prod-short} server parameter: `+CHE_KEYCLOAK_OIDC__PROVIDER+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Base URL of an alternate OIDC provider that provides a discovery endpoint as detailed in the following specification https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

// Default value for `+CHE_KEYCLOAK_OIDC__PROVIDER+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_OIDC__PROVIDER+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_OIDC__PROVIDER+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_KEYCLOAK_OIDC__PROVIDER+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_KEYCLOAK_OIDC__PROVIDER: "NULL"
----
====


