  
[id="{prod-id-short}-server-parameter-che_workspace_pod_tolerations__json_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_POD_TOLERATIONS__JSON+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Optionally configures tolerations for workspace Pod. Format is a string representing a JSON Array of taint tolerations, or `NULL` to disable it. The objects contained in the array have to follow this link:https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#toleration-v1-core[spec]. Example: `[{"effect":"NoExecute","key":"aNodeTaint","operator":"Equal","value":"aValue"}]`

// Default value for `+CHE_WORKSPACE_POD_TOLERATIONS__JSON+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_POD_TOLERATIONS__JSON+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_POD_TOLERATIONS__JSON+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_POD_TOLERATIONS__JSON+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_POD_TOLERATIONS__JSON: "NULL"
----
====


