  
[id="{prod-id-short}-server-parameter-che_infra_openshift_route_host_domain__suffix_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

The hostname that should be used as a suffix for the workspace routes. For example: Using `domain_suffix=__<{che-host}>__`, the route resembles: `routed3qrtk.__<{che-host}>__`. It has to be a valid DNS name.

// Default value for `+CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX: "NULL"
----
====


