  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_trusted__ca_dest__configmap__labels_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP__LABELS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Comma separated list of labels to add to the CA certificates ConfigMap in user workspace. See the `che.infra.kubernetes.trusted_ca.dest_configmap` property.

// Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP__LABELS+`:: `+Undefined+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP__LABELS+` as set by the Operator:: `+Undefined+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP__LABELS+` as set using the `configMap`:: `+Undefined+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP__LABELS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_TRUSTED__CA_DEST__CONFIGMAP__LABELS: "Undefined"
----
====


