  
[id="{prod-id-short}-server-parameter-che_workspace_pool_cores__multiplier_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_POOL_CORES__MULTIPLIER+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

This property is ignored when pool type is not set to `fixed`, `che.workspace.pool.exact_size` is set. When set, the pool size is `N_CORES * multiplier`.

// Default value for `+CHE_WORKSPACE_POOL_CORES__MULTIPLIER+`:: `+2+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_POOL_CORES__MULTIPLIER+` as set by the Operator:: `+2+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_POOL_CORES__MULTIPLIER+` as set using the `configMap`:: `+2+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_POOL_CORES__MULTIPLIER+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_POOL_CORES__MULTIPLIER: "2"
----
====


