  
[id="{prod-id-short}-server-parameter-che_system_admin__name_{context}"]
= {prod-short} server parameter: `+CHE_SYSTEM_ADMIN__NAME+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Grant system permission for 'che.admin.name' user. If the user already exists it'll happen on component startup, if not - during the first login when user is persisted in the database.

// Default value for `+CHE_SYSTEM_ADMIN__NAME+`:: `+admin+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_SYSTEM_ADMIN__NAME+` as set by the Operator:: `+admin+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_SYSTEM_ADMIN__NAME+` as set using the `configMap`:: `+admin+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_SYSTEM_ADMIN__NAME+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_SYSTEM_ADMIN__NAME: "admin"
----
====


