  
[id="{prod-id-short}-server-parameter-che_oauth_github_clientid_{context}"]
= {prod-short} server parameter: `+CHE_OAUTH_GITHUB_CLIENTID+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Configuration of GitHub OAuth client. You can setup GitHub OAuth to automate authentication to remote repositories. You need to first register this application with GitHub OAuth. GitHub OAuth client ID.

// Default value for `+CHE_OAUTH_GITHUB_CLIENTID+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_OAUTH_GITHUB_CLIENTID+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_OAUTH_GITHUB_CLIENTID+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_OAUTH_GITHUB_CLIENTID+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_OAUTH_GITHUB_CLIENTID: "NULL"
----
====


