  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_pvc_name_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_PVC_NAME+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines the settings of PVC name for {prod-short} workspaces. Each PVC strategy supplies this value differently. See documentation for `che.infra.kubernetes.pvc.strategy` property

// Default value for `+CHE_INFRA_KUBERNETES_PVC_NAME+`:: `+claim-che-workspace+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_NAME+` as set by the Operator:: `+claim-che-workspace+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_NAME+` as set using the `configMap`:: `+claim-che-workspace+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_PVC_NAME+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_PVC_NAME: "claim-che-workspace"
----
====


