  
[id="{prod-id-short}-server-parameter-che_limits_workspace_env_ram_{context}"]
= {prod-short} server parameter: `+CHE_LIMITS_WORKSPACE_ENV_RAM+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Workspaces are the fundamental runtime for users when doing development. You can set parameters that limit how workspaces are created and the resources that are consumed. The maximum amount of RAM that a user can allocate to a workspace when they create a new workspace. The RAM slider is adjusted to this maximum value.

// Default value for `+CHE_LIMITS_WORKSPACE_ENV_RAM+`:: `+16gb+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_LIMITS_WORKSPACE_ENV_RAM+` as set by the Operator:: `+16gb+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_LIMITS_WORKSPACE_ENV_RAM+` as set using the `configMap`:: `+16gb+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_LIMITS_WORKSPACE_ENV_RAM+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_LIMITS_WORKSPACE_ENV_RAM: "16gb"
----
====


