  
[id="{prod-id-short}-server-parameter-che_auth_user__self__creation_{context}"]
= {prod-short} server parameter: `+CHE_AUTH_USER__SELF__CREATION+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

{prod-short} has a single identity implementation, so this does not change the user experience. If true, enables user creation at API level

// Default value for `+CHE_AUTH_USER__SELF__CREATION+`:: `+false+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_AUTH_USER__SELF__CREATION+` as set by the Operator:: `+false+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_AUTH_USER__SELF__CREATION+` as set using the `configMap`:: `+false+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_AUTH_USER__SELF__CREATION+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_AUTH_USER__SELF__CREATION: "false"
----
====


