  
[id="{prod-id-short}-server-parameter-che_keycloak_admin__password_{context}"]
= {prod-short} server parameter: `+CHE_KEYCLOAK_ADMIN__PASSWORD+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Keycloak admin password. Will be used for deleting user from Keycloak on removing user from Che database. Make sense only in case $\{che.keycloak.cascade_user_removal_enabled} set to 'true'

// Default value for `+CHE_KEYCLOAK_ADMIN__PASSWORD+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_ADMIN__PASSWORD+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_ADMIN__PASSWORD+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_KEYCLOAK_ADMIN__PASSWORD+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_KEYCLOAK_ADMIN__PASSWORD: "NULL"
----
====


