  
[id="{prod-id-short}-server-parameter-che_oauth_service__mode_{context}"]
= {prod-short} server parameter: `+CHE_OAUTH_SERVICE__MODE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Configuration of OAuth Authentication Service that can be used in "embedded" or "delegated" mode. If set to "embedded", then the service work as a wrapper to Che's OAuthAuthenticator ( as in Single User mode). If set to "delegated", then the service will use Keycloak IdentityProvider mechanism. Runtime Exception wii be thrown, in case if this property is not set properly.

// Default value for `+CHE_OAUTH_SERVICE__MODE+`:: `+delegated+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_OAUTH_SERVICE__MODE+` as set by the Operator:: `+delegated+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_OAUTH_SERVICE__MODE+` as set using the `configMap`:: `+delegated+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_OAUTH_SERVICE__MODE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_OAUTH_SERVICE__MODE: "delegated"
----
====


