  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_ingress_labels_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_INGRESS_LABELS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Additional labels to add into every Ingress created by {prod-short} server to allow clear identification.

// Default value for `+CHE_INFRA_KUBERNETES_INGRESS_LABELS+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_INGRESS_LABELS+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_INGRESS_LABELS+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_INGRESS_LABELS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_INGRESS_LABELS: "NULL"
----
====


