  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_server__strategy_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_SERVER__STRATEGY+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines the way how servers are exposed to the world in Kubernetes infra. List of strategies implemented in {prod-short}: `default-host`, `multi-host`, `single-host`.

// Default value for `+CHE_INFRA_KUBERNETES_SERVER__STRATEGY+`:: `+multi-host+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_SERVER__STRATEGY+` as set by the Operator:: `+multi-host+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_SERVER__STRATEGY+` as set using the `configMap`:: `+multi-host+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_SERVER__STRATEGY+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_SERVER__STRATEGY: "multi-host"
----
====


