  
[id="{prod-id-short}-server-parameter-che_workspace_logs_root__dir_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_LOGS_ROOT__DIR+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines the directory inside the machine where all the workspace logs are placed. Provide this value into the machine, for example, as an environment variable. This is to ensure that agent developers can use this directory to back up agent logs.

// Default value for `+CHE_WORKSPACE_LOGS_ROOT__DIR+`:: `+/workspace_logs+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_LOGS_ROOT__DIR+` as set by the Operator:: `+/workspace_logs+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_LOGS_ROOT__DIR+` as set using the `configMap`:: `+/workspace_logs+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_LOGS_ROOT__DIR+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_LOGS_ROOT__DIR: "/workspace_logs"
----
====


