  
[id="{prod-id-short}-server-parameter-che_workspace_devfile_default__editor_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Default Editor that should be provisioned into Devfile if there is no specified Editor Format is `editorPublisher/editorName/editorVersion` value. `NULL` or absence of value means that default editor should not be provisioned.

// Default value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR+`:: `+eclipse/che-theia/latest+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR+` as set by the Operator:: `+eclipse/che-theia/latest+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR+` as set using the `configMap`:: `+eclipse/che-theia/latest+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR: "eclipse/che-theia/latest"
----
====


