  
[id="{prod-id-short}-server-parameter-che_organization_email_member__removed__subject_{context}"]
= {prod-short} server parameter: `+CHE_ORGANIZATION_EMAIL_MEMBER__REMOVED__SUBJECT+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

`You've been removed from a Che Organization` organization notification subject.

// Default value for `+CHE_ORGANIZATION_EMAIL_MEMBER__REMOVED__SUBJECT+`:: `+You'vebeen removed from a Che Organization+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_MEMBER__REMOVED__SUBJECT+` as set by the Operator:: `+You'vebeen removed from a Che Organization+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_MEMBER__REMOVED__SUBJECT+` as set using the `configMap`:: `+You'vebeen removed from a Che Organization+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_ORGANIZATION_EMAIL_MEMBER__REMOVED__SUBJECT+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_ORGANIZATION_EMAIL_MEMBER__REMOVED__SUBJECT: "You'vebeen removed from a Che Organization"
----
====


