  
[id="{prod-id-short}-server-parameter-che_workspace_devfile_default__editor_plugins_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Default Plug-ins which should be provisioned for Default Editor. All the plugins from this list that are not explicitly mentioned in the user-defined devfile will be provisioned but only when the default editor is used or if the user-defined editor is the same as the default one (even if in different version). Format is comma-separated `pluginPublisher/pluginName/pluginVersion` values, and URLs. For example: `eclipse/che-theia-exec-plugin/0.0.1,eclipse/che-theia-terminal-plugin/0.0.1,https://cdn.pluginregistry.com/vi-mode/meta.yaml` If the plugin is a URL, the plugin's `meta.yaml` is retrieved from that URL.

// Default value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR_PLUGINS: "NULL"
----
====


