  
[id="{prod-id-short}-server-parameter-che_workspace_server_ping__success__threshold_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Number of sequential successful pings to server after which it is treated as available. the {prod-short} Operator: the property is common for all servers, for example, workspace agent, terminal, exec.

// Default value for `+CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD+`:: `+1+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD+` as set by the Operator:: `+1+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD+` as set using the `configMap`:: `+1+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD: "1"
----
====


