  
[id="{prod-id-short}-server-parameter-che_oauth1_bitbucket_privatekeypath_{context}"]
= {prod-short} server parameter: `+CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Configurationof Bitbucket Server OAuth1 client. Used to obtain Personal access tokens. Location of the file with Bitbucket Server application consumer key (equivalent to a username). Location of the file with Bitbucket Server application private key

// Default value for `+CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH: "NULL"
----
====


