  
[id="{prod-id-short}-server-parameter-che_workspace_plugin__registry__url_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_PLUGIN__REGISTRY__URL+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Workspace plug-ins registry endpoint. Should be a valid HTTP URL. Example: ++http://che-plugin-registry-eclipse-che.192.168.65.2.nip.io++ In case {prod-short} plug-ins registry is not needed value 'NULL' should be used

// Default value for `+CHE_WORKSPACE_PLUGIN__REGISTRY__URL+`:: `+https://che-plugin-registry.prod-preview.openshift.io/v3+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PLUGIN__REGISTRY__URL+` as set by the Operator:: `+https://che-plugin-registry.prod-preview.openshift.io/v3+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PLUGIN__REGISTRY__URL+` as set using the `configMap`:: `+https://che-plugin-registry.prod-preview.openshift.io/v3+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_PLUGIN__REGISTRY__URL+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_PLUGIN__REGISTRY__URL: "https://che-plugin-registry.prod-preview.openshift.io/v3"
----
====


