  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_pvc_precreate__subpaths_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines whether to run a job that creates workspace's subpath directories in persistent volume for the `common` strategy before launching a workspace. Necessary in some versions of {orch-name} as workspace subpath volume mounts are created with root permissions, and therefore cannot be modified by workspaces running as a user (presents an error importing projects into a workspace in {prod-short}). The default is `true`, but should be set to `false` if the version of {orch-name} creates subdirectories with user permissions. Relevant issue: https://github.com/kubernetes/kubernetes/issues/41638 the {prod-short} Operator that this property has effect only if the `common` PVC strategy used.

// Default value for `+CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS+`:: `+true+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS+` as set by the Operator:: `+true+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS+` as set using the `configMap`:: `+true+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "true"
----
====


