  
[id="{prod-id-short}-server-parameter-che_limits_workspace_run_timeout_{context}"]
= {prod-short} server parameter: `+CHE_LIMITS_WORKSPACE_RUN_TIMEOUT+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

The length of time in milliseconds that a workspace will run, regardless of activity, before the system will suspend it.  Set this property if you want to automatically stop workspaces after a period of time.  The default is zero, meaning that there is no run timeout.

// Default value for `+CHE_LIMITS_WORKSPACE_RUN_TIMEOUT+`:: `+0+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_LIMITS_WORKSPACE_RUN_TIMEOUT+` as set by the Operator:: `+0+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_LIMITS_WORKSPACE_RUN_TIMEOUT+` as set using the `configMap`:: `+0+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_LIMITS_WORKSPACE_RUN_TIMEOUT+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_LIMITS_WORKSPACE_RUN_TIMEOUT: "0"
----
====


