  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_installer__server__min__port_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_INSTALLER__SERVER__MIN__PORT+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defined range of ports for installers servers By default, installer will use own port, but if it conflicts with another installer servers then OpenShift infrastructure will reconfigure installer to use first available from this range Unused, will be removed.

// Default value for `+CHE_INFRA_KUBERNETES_INSTALLER__SERVER__MIN__PORT+`:: `+10000+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_INSTALLER__SERVER__MIN__PORT+` as set by the Operator:: `+10000+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_INSTALLER__SERVER__MIN__PORT+` as set using the `configMap`:: `+10000+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_INSTALLER__SERVER__MIN__PORT+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_INSTALLER__SERVER__MIN__PORT: "10000"
----
====


