  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_pvc_wait__bound_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_PVC_WAIT__BOUND+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines if {prod-short} Server should wait workspaces Persistent Volume Claims to become bound after creating. Default value is `true`. The parameter is used by all Persistent Volume Claim strategies. It should be set to `false` when `volumeBindingMode` is configured to `WaitForFirstConsumer` otherwise workspace starts will hangs up on phase of waiting PVCs.

// Default value for `+CHE_INFRA_KUBERNETES_PVC_WAIT__BOUND+`:: `+true+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_WAIT__BOUND+` as set by the Operator:: `+true+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_PVC_WAIT__BOUND+` as set using the `configMap`:: `+true+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_PVC_WAIT__BOUND+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_PVC_WAIT__BOUND: "true"
----
====


