  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_singlehost_gateway_configmap__labels_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines labels which will be set to ConfigMaps configuring single-host gateway.

// Default value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS+`:: `+app=che,component=che-gateway-config+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS+` as set by the Operator:: `+app=che,component=che-gateway-config+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS+` as set using the `configMap`:: `+app=che,component=che-gateway-config+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_SINGLEHOST_GATEWAY_CONFIGMAP__LABELS: "app=che,component=che-gateway-config"
----
====


