  
[id="{prod-id-short}-server-parameter-che_limits_organization_workspaces_count_{context}"]
= {prod-short} server parameter: `+CHE_LIMITS_ORGANIZATION_WORKSPACES_COUNT+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

The maximum number of workspaces that a organization is allowed to own. The organization will be presented an error message if they try to create additional workspaces. This applies to the total number of both running and stopped workspaces.

// Default value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_COUNT+`:: `+-1+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_COUNT+` as set by the Operator:: `+-1+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_COUNT+` as set using the `configMap`:: `+-1+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_LIMITS_ORGANIZATION_WORKSPACES_COUNT+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_LIMITS_ORGANIZATION_WORKSPACES_COUNT: "-1"
----
====


