  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_async_storage_image_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_IMAGE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Docker image for the {prod-short} asynchronous storage

// Default value for `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_IMAGE+`:: `+quay.io/eclipse/che-workspace-data-sync-storage:0.0.1+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_IMAGE+` as set by the Operator:: `+quay.io/eclipse/che-workspace-data-sync-storage:0.0.1+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_IMAGE+` as set using the `configMap`:: `+quay.io/eclipse/che-workspace-data-sync-storage:0.0.1+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_ASYNC_STORAGE_IMAGE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_ASYNC_STORAGE_IMAGE: "quay.io/eclipse/che-workspace-data-sync-storage:0.0.1"
----
====


