  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_tls__secret_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_TLS__SECRET+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Name of a secret that should be used when creating workspace ingresses with TLS. This property is ignored by OpenShift infrastructure.

// Default value for `+CHE_INFRA_KUBERNETES_TLS__SECRET+`:: `+Undefined+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TLS__SECRET+` as set by the Operator:: `+Undefined+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TLS__SECRET+` as set using the `configMap`:: `+Undefined+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_TLS__SECRET+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_TLS__SECRET: "Undefined"
----
====


