  
[id="{prod-id-short}-server-parameter-che_workspace_sidecar_default__memory__limit__mb_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

RAM limit for each sidecar that has no RAM settings in the {prod-short} plug-in configuration. Value less or equal to 0 is interpreted as disabling the limit.

// Default value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB+`:: `+128+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB+` as set by the Operator:: `+128+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB+` as set using the `configMap`:: `+128+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB: "128"
----
====


