  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_namespace_annotations_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

List of annotations to find {orch-namespace} prepared for {prod-short} users workspaces. Only {orch-namespace} matching the `che.infra.kubernetes.namespace.labels` will be matched against these annotations. {orch-namespace} that matches both `che.infra.kubernetes.namespace.labels` and `che.infra.kubernetes.namespace.annotations` will be preferentially used for User's workspaces. It's possible to use `<username>` placeholder to specify the {orch-namespace} to concrete user.

// Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS+`:: `+che.eclipse.org/username=<username>+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS+` as set by the Operator:: `+che.eclipse.org/username=<username>+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS+` as set using the `configMap`:: `+che.eclipse.org/username=<username>+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: "che.eclipse.org/username=<username>"
----
====


