  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_pod_security__context_fs__group_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Defines security context for Pods that will be created by Kubernetes Infra. A special supplemental group that applies to all containers in a Pod. This is ignored by OpenShift infra.

// Default value for `+CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "NULL"
----
====


