  
[id="{prod-id-short}-server-parameter-che_workspace_sidecar_default__cpu__request__cores_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

CPU request default for each sidecar that has no CPU settings in the {prod-short} plug-in configuration. Specify either in floating point cores number, for example, `0.125`, or using the Kubernetes format, integer millicores, for example, `125m`.

// Default value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES+`:: `+-1+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES+` as set by the Operator:: `+-1+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES+` as set using the `configMap`:: `+-1+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: "-1"
----
====


