  
[id="{prod-id-short}-server-parameter-che_workspace_https__proxy_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_HTTPS__PROXY+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Configures environment variable HTTPS_PROXY to a specified value in containers powering workspaces.

// Default value for `+CHE_WORKSPACE_HTTPS__PROXY+`:: `+Undefined+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_HTTPS__PROXY+` as set by the Operator:: `+Undefined+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_HTTPS__PROXY+` as set using the `configMap`:: `+Undefined+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_HTTPS__PROXY+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_HTTPS__PROXY: "Undefined"
----
====


