  
[id="{prod-id-short}-server-parameter-che_workspace_storage_preferred__type_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_STORAGE_PREFERRED__TYPE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

The configuration property that defines a default value for storage type that clients such as the Dashboard should propose to users during workspace creation and update. The `async` value is an experimental feature, not recommended as default type.

// Default value for `+CHE_WORKSPACE_STORAGE_PREFERRED__TYPE+`:: `+persistent+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_STORAGE_PREFERRED__TYPE+` as set by the Operator:: `+persistent+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_STORAGE_PREFERRED__TYPE+` as set using the `configMap`:: `+persistent+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_STORAGE_PREFERRED__TYPE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_STORAGE_PREFERRED__TYPE: "persistent"
----
====


