  
[id="{prod-id-short}-server-parameter-che_keycloak_realm_{context}"]
= {prod-short} server parameter: `+CHE_KEYCLOAK_REALM+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Keycloak realm is used to authenticate users Can be set to NULL only if `che.keycloak.oidcProvider` is used

// Default value for `+CHE_KEYCLOAK_REALM+`:: `+che+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_REALM+` as set by the Operator:: `+che+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_REALM+` as set using the `configMap`:: `+che+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_KEYCLOAK_REALM+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_KEYCLOAK_REALM: "che"
----
====


