  
[id="{prod-id-short}-server-parameter-che_organization_email_org__renamed__subject_{context}"]
= {prod-short} server parameter: `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__SUBJECT+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

`Che Organization renamed` organization notification subject.

// Default value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__SUBJECT+`:: `+CheOrganization renamed+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__SUBJECT+` as set by the Operator:: `+CheOrganization renamed+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__SUBJECT+` as set using the `configMap`:: `+CheOrganization renamed+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__SUBJECT+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_ORGANIZATION_EMAIL_ORG__RENAMED__SUBJECT: "CheOrganization renamed"
----
====


