  
[id="{prod-id-short}-server-parameter-db_schema_flyway_baseline_enabled_{context}"]
= {prod-short} server parameter: `+DB_SCHEMA_FLYWAY_BASELINE_ENABLED+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

DB initialization and migration configuration If true, ignore scripts up to the version configured by baseline.version.

// Default value for `+DB_SCHEMA_FLYWAY_BASELINE_ENABLED+`:: `+true+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+DB_SCHEMA_FLYWAY_BASELINE_ENABLED+` as set by the Operator:: `+true+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+DB_SCHEMA_FLYWAY_BASELINE_ENABLED+` as set using the `configMap`:: `+true+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+DB_SCHEMA_FLYWAY_BASELINE_ENABLED+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      DB_SCHEMA_FLYWAY_BASELINE_ENABLED: "true"
----
====


