  
[id="{prod-id-short}-server-parameter-che_workspace_activity__check__scheduler__delay__s_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__DELAY__S+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Delay before first workspace idleness check job started to avoid mass suspend if ws master was unavailable for period close to inactivity timeout.

// Default value for `+CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__DELAY__S+`:: `+180+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__DELAY__S+` as set by the Operator:: `+180+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__DELAY__S+` as set using the `configMap`:: `+180+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__DELAY__S+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_ACTIVITY__CHECK__SCHEDULER__DELAY__S: "180"
----
====


