  
[id="{prod-id-short}-server-parameter-che_workspace_plugin__broker_pull__policy_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Docker image of {prod-short} plugin broker app that resolves workspace tools configuration and copies plugins dependencies to a workspace

// Default value for `+CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY+`:: `+Always+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY+` as set by the Operator:: `+Always+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY+` as set using the `configMap`:: `+Always+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY: "Always"
----
====


