  
[id="{prod-id-short}-server-parameter-che_keycloak_username_replacement__patterns_{context}"]
= {prod-short} server parameter: `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

User name adjustment configuration. Che needs to use the usernames as part of K8s object names and labels and therefore has stricter requirements on their format than the identity providers usually allow (it needs them to be DNS-compliant). The adjustment is represented by comma-separated key-value pairs. These are sequentially used as arguments to the String.replaceAll function on the original username. The keys are regular expressions, values are replacement strings that replace the characters in the username that match the regular expression. The modified username will only be stored in the Che database and will not be advertised back to the identity provider. It is recommended to use DNS-compliant characters as replacement strings (values in the key-value pairs). Example: `\\=-,@=-at-` changes `\` to `-` and `@` to `-at-` so the username `org\user@com` becomes `org-user-at-com.`

// Default value for `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_KEYCLOAK_USERNAME_REPLACEMENT__PATTERNS: "NULL"
----
====


