  
[id="{prod-id-short}-server-parameter-che_organization_email_org__renamed__template_{context}"]
= {prod-short} server parameter: `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__TEMPLATE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

`Che Organization renamed` organization notification template.

// Default value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__TEMPLATE+`:: `+st-html-templates/organization_renamed+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__TEMPLATE+` as set by the Operator:: `+st-html-templates/organization_renamed+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__TEMPLATE+` as set using the `configMap`:: `+st-html-templates/organization_renamed+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_ORGANIZATION_EMAIL_ORG__RENAMED__TEMPLATE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_ORGANIZATION_EMAIL_ORG__RENAMED__TEMPLATE: "st-html-templates/organization_renamed"
----
====


