  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_trusted__ca_src__configmap_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_TRUSTED__CA_SRC__CONFIGMAP+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Name of the ConfigMap in {prod-short} server namespace with additional CA TLS certificates to be propagated into all user's workspaces. If the property is set on OpenShift 4 infrastructure, and `che.infra.openshift.trusted_ca.dest_configmap_labels` includes the `config.openshift.io/inject-trusted-cabundle=true` label, then cluster CA bundle will be propagated too.

// Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_SRC__CONFIGMAP+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_SRC__CONFIGMAP+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_SRC__CONFIGMAP+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_SRC__CONFIGMAP+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_TRUSTED__CA_SRC__CONFIGMAP: "NULL"
----
====


