  
[id="{prod-id-short}-server-parameter-che_oauth_openshift_clientsecret_{context}"]
= {prod-short} server parameter: `+CHE_OAUTH_OPENSHIFT_CLIENTSECRET+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Configurationof OpenShift OAuth client. Used to obtain OpenShift OAuth token. OpenShift OAuth client ID. OpenShift OAuth client secret.

// Default value for `+CHE_OAUTH_OPENSHIFT_CLIENTSECRET+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_OAUTH_OPENSHIFT_CLIENTSECRET+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_OAUTH_OPENSHIFT_CLIENTSECRET+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_OAUTH_OPENSHIFT_CLIENTSECRET+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_OAUTH_OPENSHIFT_CLIENTSECRET: "NULL"
----
====


