  
[id="{prod-id-short}-server-parameter-che_keycloak_auth__server__url_{context}"]
= {prod-short} server parameter: `+CHE_KEYCLOAK_AUTH__SERVER__URL+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Url to keycloak identity provider server Can be set to NULL only if `che.keycloak.oidcProvider` is used

// Default value for `+CHE_KEYCLOAK_AUTH__SERVER__URL+`:: `+http://${CHE_HOST}:5050/auth+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_AUTH__SERVER__URL+` as set by the Operator:: `+http://${CHE_HOST}:5050/auth+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_AUTH__SERVER__URL+` as set using the `configMap`:: `+http://${CHE_HOST}:5050/auth+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_KEYCLOAK_AUTH__SERVER__URL+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_KEYCLOAK_AUTH__SERVER__URL: "http://${CHE_HOST}:5050/auth"
----
====


