  
[id="{prod-id-short}-server-parameter-che_keycloak_use__fixed__redirect__urls_{context}"]
= {prod-short} server parameter: `+CHE_KEYCLOAK_USE__FIXED__REDIRECT__URLS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Set to true when using an alternate OIDC provider that only supports fixed redirect Urls This property is ignored when `che.keycloak.oidc_provider` is NULL

// Default value for `+CHE_KEYCLOAK_USE__FIXED__REDIRECT__URLS+`:: `+false+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_USE__FIXED__REDIRECT__URLS+` as set by the Operator:: `+false+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_KEYCLOAK_USE__FIXED__REDIRECT__URLS+` as set using the `configMap`:: `+false+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_KEYCLOAK_USE__FIXED__REDIRECT__URLS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_KEYCLOAK_USE__FIXED__REDIRECT__URLS: "false"
----
====


