  
[id="{prod-id-short}-server-parameter-che_workspace_cleanup__temporary__period__min_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_CLEANUP__TEMPORARY__PERIOD__MIN+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Time period delay between the termination of one execution and the commencement of the next execution of temporary workspaces cleanup job

// Default value for `+CHE_WORKSPACE_CLEANUP__TEMPORARY__PERIOD__MIN+`:: `+180+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_CLEANUP__TEMPORARY__PERIOD__MIN+` as set by the Operator:: `+180+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_CLEANUP__TEMPORARY__PERIOD__MIN+` as set using the `configMap`:: `+180+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_CLEANUP__TEMPORARY__PERIOD__MIN+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_CLEANUP__TEMPORARY__PERIOD__MIN: "180"
----
====


