  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_trusted__ca_mount__path_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_TRUSTED__CA_MOUNT__PATH+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Configures path on workspace containers where the CA bundle should be mounted. Content of ConfigMap specified by `che.infra.kubernetes.trusted_ca.dest_configmap` is mounted.

// Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_MOUNT__PATH+`:: `+/public-certs+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_MOUNT__PATH+` as set by the Operator:: `+/public-certs+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_MOUNT__PATH+` as set using the `configMap`:: `+/public-certs+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_TRUSTED__CA_MOUNT__PATH+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_TRUSTED__CA_MOUNT__PATH: "/public-certs"
----
====


