  
[id="{prod-id-short}-server-parameter-che_infra_kubernetes_tls__enabled_{context}"]
= {prod-short} server parameter: `+CHE_INFRA_KUBERNETES_TLS__ENABLED+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Creates Ingresses with Transport Layer Security (TLS) enabled. In OpenShift infrastructure, Routes will be TLS-enabled.

// Default value for `+CHE_INFRA_KUBERNETES_TLS__ENABLED+`:: `+false+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TLS__ENABLED+` as set by the Operator:: `+false+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_INFRA_KUBERNETES_TLS__ENABLED+` as set using the `configMap`:: `+false+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_INFRA_KUBERNETES_TLS__ENABLED+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_INFRA_KUBERNETES_TLS__ENABLED: "false"
----
====


