  
[id="{prod-id-short}-server-parameter-che_factory_default__plugins_{context}"]
= {prod-short} server parameter: `+CHE_FACTORY_DEFAULT__PLUGINS+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Editor and plugin which will be used for factories that are created from a remote Git repository which does not contain any {prod-short}-specific workspace descriptor Multiple plugins must be comma-separated, for example: `pluginFooPublisher/pluginFooName/pluginFooVersion,pluginBarPublisher/pluginBarName/pluginBarVersion`

// Default value for `+CHE_FACTORY_DEFAULT__PLUGINS+`:: `+NULL+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_FACTORY_DEFAULT__PLUGINS+` as set by the Operator:: `+NULL+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_FACTORY_DEFAULT__PLUGINS+` as set using the `configMap`:: `+NULL+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_FACTORY_DEFAULT__PLUGINS+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_FACTORY_DEFAULT__PLUGINS: "NULL"
----
====


