  
[id="{prod-id-short}-server-parameter-che_workspace_plugin__broker_artifacts_image_{context}"]
= {prod-short} server parameter: `+CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE+`

// FIXME: Fix the language and remove the  vale off statement.
// pass:[<!-- vale off -->]

Docker image of Che plugin artifacts broker. This broker runs as an init container on the workspace Pod. Its job is to take in a list of plugin identifiers (either references to a plugin in the registry or a link to a plugin meta.yaml) and ensure that the correct .vsix and .theia extensions are downloaded into the /plugins directory, for each plugin requested for the workspace.

// Default value for `+CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE+`:: `+quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0+`

// If the Operator sets a different value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE+` as set by the Operator:: `+quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0+`

ifeval::["{project-context}" == "che"]
// If Helm sets a different default value, uncomment and complete following block:
Default value for `+CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE+` as set using the `configMap`:: `+quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0+`
endif::[]

// FIXME: If the parameter can be set with the simpler syntax defined for CheCluster Custom Resource, replace it here

.Setting the value for `+CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE+` using the Operator
====
[source,yaml]
----
apiVersion: org.eclipse.che/v1
kind: CheCluster
# [...]
spec:
  server:
    # [...]
    customCheProperties:
      CHE_WORKSPACE_PLUGIN__BROKER_ARTIFACTS_IMAGE: "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"
----
====


