// Module included in the following assemblies:
//
// hosted-che

[id="registering-to-hosted-che_{context}"]
= Registering to Eclipse Che hosted by Red Hat

This section describes how to register to Eclipse Che hosted by Red Hat.

.Procedure

. Navigate to link:https://developers.redhat.com/developer-sandbox[Developer Sandbox for Red Hat OpenShift].

. Register with an existing OpenShift Online, Red Hat Developer Program, or Red Hat Customer Portal account, *or* create a new Red Hat account.

. Verify the phone number

IMPORTANT: A valid phone number is required for reducing the creation of fraudulent accounts on the Developer Sandbox for Red Hat OpenShift. Red Hat will not use this information for any other reason, and you will never receive a phone call from Red Hat or any third-party as a result of trying the sandbox.

. Once the account is provioned, Eclipse Che hosted by Red Hat will be ready for use from both link:https://developers.redhat.com/developer-sandbox#assembly-field-sections-59571[Developer Sandbox] and https://workspaces.openshift.com pages.
