// Module included in the following assemblies:
//
// hosted-che


[id="about-hosted-che_{context}"]
= About Eclipse Che hosted by Red Hat

Eclipse Che hosted by Red Hat is an open source product based on link:https://www.eclipse.org/che/[Eclipse {prod-short}] that is running on link:https://www.openshift.com/products/dedicated/[OpenShift Dedicated].

[id="terms-of-service_{context}"]
== Terms of service

Eclipse Che hosted by Red Hat has the following usage limits and terms of service:

* Storage: 10 GB
* RAM: 7 GB
* Concurrent workspaces: 1
* Number of workspaces: Unlimited
* Number of projects per workspace: Unlimited
* Usage time limit: 14 days
+ 
NOTE: The account will be active for 14 days. At the end of the active period, the access will be revoked and all the data will be deleted. All existing workspaces will be lost. In order to start using Eclipse Che hosted by Red Hat again, a user must re-register.

* Maximum time for a running workspace: 8 hours
+
NOTE: Eclipse Che hosted by Red Hat automatically stops workspaces that run more than 8 hours regardless of activity.

* Workspace idling time: 30 minutes
+
NOTE: If there are no interactions with the IDE, the workspace will be stopped after 30 minutes.
