


[id="{prod-id-short}-glossary"]
= {prod-short} Glossary



This section provides an overview of the main terms and expressions used throughout {prod} documentation.

== Naming
{prod}:: A developer platform for the cloud that provides an in-browser editor (IDE). You can enhance {prod-short} tools by adding development services, such as language servers, debug adapters, or IDEs packaged as containers.

Che-Code:: The default editor component of a {prod-short} workspace. It is a {prod-short}-specific customization of the Visual Studio Code editor. You can enhance Che-Code with link:https://open-vsx.org[Visual Studio Code extensions].

{prod-short} Workspace:: A container-based development environment managed by {prod}. Every {prod-short} workspace is defined by a devfile. A {prod-short} workspace consists of an editor, runtime and build containers, and other development tools running inside containers.

== Terminology

`Editor`:: A web application used as an editor in a workspace.

`Plugin`:: Plugins are services that extend {prod-short} workspace capabilities. {prod-short} plugins are packaged as containers. Plugins are extensions of an editor or a service running in the container.
//TODO See for a diagram of {prod-short} extensibility architecture. 
Both {prod-short} plugins and editors are distributed through the {prod-short} plugins registry.
 
Workspace:: A container-based development environment managed by {prod}. Every  {prod-short} workspace is defined by a devfile. A  {prod-short} workspace consists of an editor, plugins, and runtime containers. Workspace runtime containers can be defined as simple container images or as {platforms-name} resources. A {prod-short} workspace can be associated with source code projects hosted on a remote CVS server. A {prod-short} workspace can contain the definition of one or more commands such as `run`, `build`, or `debug`.

Devfile:: A workspace configuration template. Use devfiles to create workspaces in the Dashboard. A devfile includes metadata such as scope, tags, components, description, name, and identification.

Factory:: A template that contains the configuration to automate the generation of a new workspace using a factory identifier or a devfile added to the URL of the IDE. Use factories to create replicas of existing workspaces or to automate the provisioning of statically or dynamically defined workspaces.

Project:: A source code repository.

