---
title: "Editor and Code Assistance"
keywords: workspace, runtime, project, editor, code-completion, code completion, code assistance, intellisense
tags: [workspace, runtime]
sidebar: che_6_docs
permalink: che-6/editor-code-assistance.html
redirect_from: editor-code-assistance.html
folder: che-6/user-guide
---


[id="orion-editor"]
== Orion editor

=== Use with Che
Eclipse Che uses the Orion editor to integrate it with the language servers, Git, debugger, and other services that run on the server and client side. Che allows the use of custom or user-provided editors. See link:editor.html[Editor] for more information.

[id="syntax-highlighting"]
=== Syntax highlighting with Orion

By default, the Orion editor provides syntax highlighting. Che overrides styles for some file types. Che uses existing styles for other file types. When the opened file does not have syntax highlighting, this means that Orion does not recognize this file type. You can define your own syntax highlighting for custom file types or override existing styles. See: link:editor.html[Editor] for more information.

[id="code-assistant"]
=== Code assistant

The Orion editor provides code assistance for JavaScript.

Code assistance for other languages is provided by link:language-servers.html[Language Servers]. Eclipse Che supports code assistance for Java, C#, PHP, Python, TypeScript, YAML and JSON. There are plans to add a language servers for Golang.

[id="configuring-editor-settings"]
=== Configuring editor settings

* To configure editor settings in the Che IDE, go to *Profile > Preferences > IDE > Editor*. Preferences can change key bindings, tabbing rules, language tools, whitespace, and ruler preferences. 

* To switch to vi-style or Emacs-style keybindings, go to *Profile > Preferences*.

* To configure the error and warning preferences for the Java compiler, go to  *Profile > Preferences > Java Compiler > Errors/Warnings*.

[NOTE]
====
If settings are not applied, you can refresh your settings.
====

[id="splitting-the-editor-into-multiple-panes"]
=== Splitting the editor into multiple panes 

You can split the editor into multiple panes. This allows easier navigation to edit across different files or parts of the same file at the same time. 

* To split the editor into multiple panes, right-click in the editor and select either *Split Vertical* or *Split Horizontal* on the drop down menu.

[id="splitting-the-consoles-into-multiple-panes"]
=== Splitting the consoles into multiple panes

You can split the consoles into multiple panes. This allows easier navigation when trying to see different console outputs at the same time. 

* To split the consoles into multiple panes, select *Split Vertical* or *Split Horizontal* from the drop down at the top right of the console area. 

* To put the new console in a newly created pane, select the open area below the tabs.

[id="fullsreen-mode-for-panes"]
=== Fullscreen mode for panes

The editor tabs and console outputs can be displayed fullscreen.

[id="displaying-the-editor-in-fullscreen"]
=== Displaying the editor in fullscreen 

* To display the editor in fullscreen mode, double-click on one of the editors tabs. All other panes will be collapsed when you do this. 

* To exit fullscreen mode, double-click again on the tab.

[id="fullscreen-for-consoles"]
=== Fullscreen for consoles

* To display the console outputs and processes tabs in fullscreen mode, double-click on one of the terminals or outputs tab to maximize it. All other panes will be collapsed when you do this. 

* To move to fullscreen mode, select the quick pane option displayed in the top right corner of the pane.

* To exit fullscreen mode, double-click again on the tab.

[id="previewing-html-files"]
=== Previewing HTML files

* To preview an HTML file, right-click in the project explorer and select *Preview* from the popup menu.

[id="previewing-images"]
=== Previewing images

* To preview images, double-click in the project explorer. The image opens in the editor area. 

* To open the image in the dedicated browser tab,  right-click the image in the project explorer and select *Preview* from the popup menu.
