---
title: "Organizations"
keywords: organizations, user management, permissions
tags: [organizations]
sidebar: user_sidebar
permalink: organizations.html
folder: user-management
---


[id="organizations-in-eclipse-che"]
== Organizations in Eclipse Che

Organizations allow administrators to group Eclipse Che users and allocate resources. The system adminstrator controls and allocates resources and permissions within the administrator dashboard.

[id="roles"]
== Roles

There are two different roles in an organization:

* *Admin*: Organizational administrators manage the organization, members, resources and sub-organization and edit settings. +
* *Members*: Organizational members are able to use, create, and manage workspaces.
* *System Admin*: System administrators have more permissions than the administrator and member role. System admininstrators create root organizations, manages all resources, members and sub-organizations.

[id="organization-structure"]
== Organization Structure

The top level organizations are called root organizations.  Any organization can have zero to a set number of sub-organizations. Only the system admistrator can create root organizations and manage the resources of the root organization. 

[id="creating-an-organization"]
== Creating an Organization

Only the system administrator is able to create root organizations. The organizational administrator creates sub-organizations. 

To create an organization:

.  Use the menu in the left sidebar, which leads to the list of organizations. A new page is displayed with all organizations in your system.

.  Click on the top-left button to create a new organization.

[id="organization-list"]
== Organization List

The list of all organizations are displayed on the organization page. The list contains the following general information for each organization: number of members, total RAM, available RAM and number of sub-organizations.

[id="adding-organization-members"]
== Adding members to organizations

To add members to organization:

. Click "Add" button.  A new popup displays. You can add, change the role of the member or remove the member from the organization.

[NOTE]
====
Users with the green checkmark beside their name already have an Eclipse Che account and can be added to the organization. Users without a checkmark do not have an account and can not be added into the organization.
====

[id="workspaces-in-organization"]
== Workspaces in Organization

You can choose the organizaton of the workspace.  The resources of the organization are used by the workspace. 

[id="email-notifications"]
== Setting email notifications

When a user joins or leaves an organization, Che server sends a notification. You either configure SMTP in `che.env` or for Openshift you add environment varibles to the deployment to send a notification.  Che does not have any built-in SMTP server by default. You may use any mail server.

To send notification email, set the following enviroment variables:

----
CHE_MAIL_PORT=465
CHE_MAIL_HOST=smtp.gmail.com
CHE_MAIL_SMTP_STARTTLS_ENABLE=true
CHE_MAIL_SMTP_AUTH=true
CHE_MAIL_SMTP_AUTH_USERNAME=no-reply@gmail.com
CHE_MAIL_SMTP_AUTH_PASSWORD=password
----

[NOTE]
====
This example is for gmail.
====

[id="create-sub-organization"]
== Creating sub-organizations

To create the sub-organization:

*  Select Sub-Organizations tab.

*  Click "Add Sub-Organization" button.

You use the same steps to create the sub-organization as organization.

[id="add-members-to-sub-organization"]
== Adding members to Sub-Organization

To add sub-organization member from the list of parent organization’s members:

[id="organization-and-sub-organization-administration"]
== Organization and Sub-Organization Administration

The organization settings are visible to all members of the organization.  Only the Eclipse Che system administrator modifies the settings.

[id="rename-an-organization-or-sub-organization"]
== Rename an organization or sub-organization

To rename an organization:

. Click in the "Name" field.

. Edit the name of the organization. The save mode appears after typing.

. Click on "Save" button to update the name.

The name of the organization is restricted to the following rules: +
* Only alphanumeric characters or a single "-" can be used. +
* Spaces can not be used in the name of the organization. +
* Each organization name must be unique within the Eclipse Che install. +
* Each sub-organization name must be unique within an organization.

[NOTE]
====
Renaming an organization or sub-organization is restricted to the Eclipse Che system administrator and administrator of the organization.
====

[id="leave-an-organization-or-sub-organization"]
== Leaving an organization or sub-organization

Members of an organization can not request to leave an organization or sub-organization. You contact the administrator of the organization or the system administrator to request that a member leaves an organization or sub-organization.  

[id="delete-an-organization-or-sub-organization"]
== Deleting an organization or sub-organization

To delete an organization or a sub-organization:

* Click on "Delete" button.

[IMPORTANT]
====
This action can’t be reverted and all workspaces created under the organization will be deleted.
All members of the organization will receive an email notification to inform about organization deletion. Only system adminstrators or administrators of the organization delete an organization or sub-organization. 
====

[id="organization-resources"]
== Organization Resources

The workspace use the resources allocated by the system administrator of the organization that it belongs to. The resources for sub-organizations are taken from the parent organization. Administrators control which resources of the parent organization are available to the sub-organization.

[id="managing-limits"]
== Managing Limits

*Action restricted to*: Eclipse Che system administrator and admins of the organization.

The organization default caps are taken from the system configuration. The admin of the organization can manage only the limits of it’s sub-organizations. By default, there are no resource limits applied to the organization so all members can benefit from all the allocated resources. If an organization admin wishes to set limits they have three options:

* *Workspace Cap*: The maximum number of workspaces that can exist in the organization. +
* *Running Workspace Cap*: The maximum number of workspaces which can run simultaneously in the organization. +
* *Workspace RAM Cap*: The maximum total RAM organization workspaces can use in GB.

[id="update-organization-and-sub-organization-member-roles"]
== Update Organization and Sub-Organization Member Roles

*Action restricted to*: Eclipse Che system administrator and admins of the organization.

To edit the role of a organization member click on the "Edit" button in the "Actions" column. You’ll get a pop-up where you can update the role of the selected member. Click "Save" to confirm the update.

[id="remove-organization-and-sub-organization-members"]
== Remove Organization and Sub-Organization Members

*Action restricted to*: Eclipse Che system administrator and admins of the organization.

To remove a member from the organization, you can click on the "Delete" button in the "Actions" column. You’ll get a confirmation pop-up, where you can confirm or cancel your action.

You can also select multiple members from the organization, using the checkboxes. A delete button will appear in the header of the table. The members that are removed from the organization will receive an email notification.
