---
title: "Organizations"
keywords: organizations, user management, permissions
tags: [organizations]
sidebar: user_sidebar
permalink: organizations.html
folder: user-management
---


[id="organizations-in-eclipse-che"]
== Organizations in Eclipse Che

Organizations allow administrators to group Eclipse Che users and allocate resources. The system adminstrator controls and allocates resources and permissions within the administrator dashboard.

[id="roles"]
== Roles

The following are roles in an organization:

* *Administrator*
    Manages the organization, sub-organization, members, resources, and edits settings. +
* *Member*
    Uses, creates, and manages workspaces.
* *System Adminstrator*: 
    Creates root organizations, manages resources, members and sub-organizations. System administrators have more permissions than the administrator and member. 

[id="organization-structure"]
== Root organizations and sub-organizations 

The top-level organizations are called root organizations.  Any organization can have zero to a set number of sub-organizations. Only the system admistrator can create root organizations and manage the resources of the root organization. 

[id="creating-an-organization"]
== Creating an organization

Only the system administrator is able to create root organizations. The administrator creates sub-organizations. 

To create an organization:

.  Click the menu in the left sidebar.  A new page displays all the organizations in your system.

.  Click on the top-left button to create a new organization.

[id="organization-list"]
== List of organizations

A list of all the organizations displays on the organization page. The list contains the following general information for each organization: number of members, total RAM, available RAM, and number of sub-organizations.

[id="adding-organization-members"]
== Adding members to organizations

To add members to organization:

. Click *Add* button to add a member.  A new pop-up window displays. 

. Enter member name.  

[NOTE]
====
Users with the green checkmark beside their name already have an Eclipse Che account and can be added to the organization. Users without a checkmark do not have an account and cannot be added into the organization.
====

[id="workspaces-in-organization"]
== Workspaces in organization

You can choose the organizaton of the workspace.  The resources of the organization are used by the workspace. 

[id="email-notifications"]
== Setting email notifications

When a user joins or leaves an organization, Che server sends a notification. You either configure SMTP in `che.env` or for OpenShift you add environment varibles to the deployment to send a notification.  Che does not have any built-in SMTP server by default. You may use any mail server.

For example, to send notification email to your Gmail account, set the following environment variables:

----
CHE_MAIL_PORT=465
CHE_MAIL_HOST=smtp.gmail.com
CHE_MAIL_SMTP_STARTTLS_ENABLE=true
CHE_MAIL_SMTP_AUTH=true
CHE_MAIL_SMTP_AUTH_USERNAME=no-reply@gmail.com
CHE_MAIL_SMTP_AUTH_PASSWORD=password
----

[id="create-sub-organization"]
== Creating sub-organizations

To create a sub-organization:

*  Select Sub-Organizations tab.

*  Click *Add Sub-Organization* button.

The steps to create a sub-organization are the same as that of creating an organization, use them to create the organization.

[id="add-members-to-sub-organization"]
== Adding members to sub-organizations

You can only add members of the parent organization as members of the sub-organization.

[id="organization-and-sub-organization-administration"]
== Organization and sub-organization administration

The settings of the organization are visible to all members of the organization.  Only the Eclipse Che system administrator modifies the settings.

[id="rename-an-organization-or-sub-organization"]
== Renaming an organization or sub-organization

[NOTE]
====
Only the  Eclipse Che system administrator and administrator of the organization can rename an organization or sub-organization.
====

To rename an organization:

. Click *Name* field to edit the name of the organization.  The save mode displays after typing.

. Click *Save* button to update the name.

The name of the organization is restricted to the following rules: +
* Only alphanumeric characters or a single "-" can be used. +
* Spaces can not be used in the name of the organization. +
* Each organization name must be unique within the Eclipse Che install. +
* Each sub-organization name must be unique within an organization.

[id="leave-an-organization-or-sub-organization"]
== Leaving an organization or sub-organization

Members of an organization can not leave an organization or sub-organization. To leave the organization, contact the administrator of the organization or the system administrator of Eclipse Che.  

[id="delete-an-organization-or-sub-organization"]
== Deleting an organization or sub-organization

To delete an organization or a sub-organization:

* Click on "Delete" button.

[IMPORTANT]
====
This action can not be reverted and all workspaces created under the organization will be deleted.
All members of the organization will receive an email notification to inform about the deletion of the organization. Only system adminstrators or administrators of the organization delete an organization or sub-organization. 
====

[id="organization-resources"]
== Allocating resources for organizations

The workspace use the resources of the organization that is allocated by the system administrator. The resources for sub-organizations are taken from the parent organization. Administrators control which resources of the parent organization are available to the sub-organization.

[id="managing-limits"]
== Managing Limits

[NOTE]
====
Managing limits is restricted to the Eclipse Che system administrator and administrator of the organization.
====

The system configuration defines the default limits. The administrator of the organization manages only the limits of its sub-organizations. No resource limits apply to the organization by default.  The following are the limits defined by the system adminstrator:

* *Workspace Cap*: The maximum number of workspaces that exists in the organization. +
* *Running Workspace Cap*: The maximum number of workspaces that run simultaneously in the organization. +
* *Workspace RAM Cap*: The maximum amount of RAM that a workspace uses in GB.


[id="update-organization-and-sub-organization-member-roles"]
== Updating organization and sub-organization member roles

[NOTE]
====
Updating the members of an organization or sub-organization is restricted to the Eclipse Che system administrator and administrator of the organization.
====

To edit the member role:

. Click *Edit* button in the *Actions* column. You update the role of the selected member in the pop-up window. 

. Click *Save* to confirm the update.

[id="remove-organization-and-sub-organization-members"]
== Removing members from an organization and sub-organization

To remove a member:

. Click *Delete* button in the *Actions* column. You confirm or cancel in the confirmation pop-up window.

To remove multiple members:

. Click the checkbox to select multiple members from the organization. 

. Click *Delete* button that appears in the header of the table. The members that are removed from the organization will receive an email notification.

[NOTE]
====
Removing the members of an organization or sub-organization is restricted to the Eclipse Che system administrator and administrator of the organization.
====

