---
title: "Permissions"
keywords: organizations, user management, permissions
tags: [organizations]
sidebar: user_sidebar
permalink: permissions.html
folder: user-management
---


[id="overview"]
== Overview

Permissions are used to control user actions. Rather than providing a fixed set of roles we use a broader set of permissions that can be applied in any combination of objects to establish the security model you need.

Che also provides a mechanisms and layers which allow to define "who" is allowed to do "what". Any user and administrator can control resources managed by Che and allow certain actions or behaviors for other users or groups. For example as workspace owner you can grant other users permission to see and/or use your workspace.

Permissions can be applied to:

* Workspace
* Organization
* Stack
* System

[id="workspace-permissions"]
== Workspace Permissions

The user who creates a workspace is the _workspace owner_ and has all permissions by default. Workspace owners can invite other users into the workspace and control their permissions for the workspace.

The following permissions are applicable to workspaces:

[cols=",",options="header",]
|===
|Permission |Description
|read |Allows reading workspace configuration.
|use |Allows using a workspace and interacting with it.
|run |Allows starting and stopping a workspace.
|configure |Allows defining and changing workspace configuration.
|setPermissions |Allows updating workspace permissions for other users.
|delete |Allows deleting the workspace.
|===

[id="organization-permissions"]
== Organization Permissions

An organization is a named set of users.

The following permissions are applicable to organizations:

[width="100%",cols="30%,70%",options="header",]
|===
|Permission |Description
|update |Allows editing of organization settings and information.
|delete |Allows deleting an organization.
|manageSuborganizations |Allows creating and managing sub-organizations.
|manageResources |Allows redistribution of an organization’s resources and defining resource limits.
|manageWorkspaces |Allows creating and managing all the organization’s workspaces.
|setPermissions |Allows adding and removing users as well as updating their permissions.
|===

[id="system-permissions"]
== System Permissions

System permissions control aspects that affect the whole Che installation.

The following permissions are applicable to organizations:

[cols=",",options="header",]
|===
|Permission |Description
|manageSystem |Allows control of the system, workspaces and organizations.
|setPermissions |Allows updating of permissions for users on the system.
|manageUsers |Allows creating and managing users.
|===

All system permissions will be granted to the administration user configured with the pass:[`CHE_SYSTEM_ADMIN__NAME`] property (the default is `admin`).
This happens at Che Server start. If the user is not present in the Che user database, it happens after the user's login.

[id="manage-system-permission"]
== manageSystem permission

Users with the `manageSystem` permission have access to the following services:

[cols=",,",options="header",]
|===
|Path | HTTP Method | Description
|`/resource/free/` |GET | Get free resource limits
|`/resource/free/{accountId}` |GET | Get free resource limits for given account
|`/resource/free/{accountId}` |POST | Edit free resource limit for given account
|`/resource/free/{accountId}` |DELETE | Remove free resource limit for given account
|`/installer/` |POST | Add installer to the registry
|`/installer/{key}` |PUT | Update installer in the registry
|`/installer/{key}` |DELETE | Remove installer from the registry
|/logger/ |GET | Get logging configurations in Che Server
|`/logger/{name}` |GET | Get configurations of logger by its name in Che Server
|/logger/{name}|PUT | Create logging in Che Server
|`/logger/{name}` |POST | Edit logging in Che Server
|/resource/{accountId}/details |GET | Get detailed information about resources for given account
|/system/stop |POST | Shutdown all system services, prepare Che to stop
|/stacks |All methods | All Stack service methods
|===

A Super Privileged mode can be enabled to extend with additional services.
To enable it, configure environment variable `CHE_SYSTEM_SUPER_PRIVILEGED_MODE=true` in the `che.env` file.

List of services that will be enabled for users with `manageSystems` permissions and Super Priviliged Mode on:
[cols=",,",options="header",]
|===
|Path | HTTP Method | Description
|/workspace/namespace/{namespace:.*} |GET |Get all workspaces for given namespace.
|/workspace/{id} |DELETE |Stop workspace
|/workspace/{key:.*} |GET | Get workspace by key
|/organization/resource/{suborganizationId}/cap |GET |Get resource cap for given organization
|/organization/resource/{suborganizationId}/cap |POST |Set resource cap for given organization
|/organization/{parent}/organizations |GET | Get child organizations
|/organization |GET | Get user's organizations
|===

[id="stack-permissions"]
== Stack Permissions

A stack is a runtime configuration for a workspace, see link:stacks.html[stack definition].

The following permissions are applicable to a stack:

[cols=",",options="header",]
|===
|Permission |Description
|search |Allows searching of the stacks.
|read |Allows reading of the stack’s configuration.
|update |Allows updating of the stack’s configuration.
|delete |Allows deleting of the stack.
|setPermissions |Allows managing permissions for the stack.
|===

[id="permissions-api"]
== Permissions API

All permissions can be managed by using the provided REST API. The APIs are documented using Swagger at `[{host}/swagger/#!/permissions]`.

[id="list-permissions"]
== List Permissions

List the permissions which can be applied to a specific resources: `GET /permissions`

Applicable `domain` values are the following:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===

Note: `domain` is optional, in this case the API will return all possible permissions for all domains.

[id="list-permissions-for-specific-user"]
== List Permissions for Specific User

List the permissions which are applied to a specific user: `GET /permissions/{domain}`

Applicable `domain` values are the following:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===

`instance` parameter corresponds to the ID of the resource you want to get the applied permissions.

[id="list-permissions-for-all-users"]
== List Permissions for All Users

List the permissions which are applied to a specific user (you must have sufficient permissions to allow you to see this information): `GET /permissions/{domain}/all`

Applicable `domain` values are the following:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===

`instance` parameter corresponds to the ID of the resource you want to get the applied permissions for all users.

[id="assign-permissions"]
== Assign Permissions

Assign permissions to a resource: `POST /permissions`

Applicable `domain` values are the following:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===

`instance` parameter corresponds to the ID of the resource you want to get the applied permissions for all users.

`userId` parameter corresponds to the ID of the user who want to grant certain permissions.

Sample `body` to grant user `userID` permissions to a workspace `workspaceID`:

[source,json]
----
{
  "actions": [
    "read",
    "use",
    "run",
    "configure",
    "setPermissions"
  ],
  "userId": "userID",
  "domainId": "workspace",
  "instanceId": "workspaceID"
}
----

[id="sharing-permissions"]
== Sharing Permissions

A user with `setPermissions` privileges can share a workspace, i.e. grant other users `read, use, run, configure or setPermissions` privileges.

Select a workspace in User Dashboard, navigate to `Share` tab and enter emails of users to share this workspace with (use comma or space as separator if there are multiple emails).
