---
title: "Permissions"
keywords: organizations, user management, permissions
tags: [organizations]
sidebar: user_sidebar
permalink: permissions.html
folder: user-management
---


[id="overview"]
== Overview

Permissions are used to control the actions of users and establish a security model. You can define _who_ is allowed to do _what_. You can control resources managed by Che and allow certain actions by assigning permissions to users.

Permissions can be applied to the following:

* Workspace
* Organization
* Stack
* System

[id="workspace-permissions"]
== Workspace permissions

The user who creates a workspace is the workspace owner. The workspace owner has the following permissions by default:  `read`, `use`, `run`, `configure`, `setPermissions`, and `delete`. Workspace owners invite users into the workspace and control workspace permissions for each user.

The following permissions are associated with workspaces:

[cols=",",options="header",]
|===
|Permission |Description
|read |Allows reading the workspace configuration.
|use |Allows using a workspace and interacting with it.
|run |Allows starting and stopping a workspace.
|configure |Allows defining and changing the workspace configuration.
|setPermissions |Allows updating the workspace permissions for other users.
|delete |Allows deleting the workspace.
|===

[id="organization-permissions"]
== Organization permissions

An organization is a named set of users.

The following permissions are applicable to organizations:

[width="100%",cols="30%,70%",options="header",]
|===
|Permission |Description
|update |Allows editing of the organization settings and information.
|delete |Allows deleting an organization.
|manageSuborganizations |Allows creating and managing sub-organizations.
|manageResources |Allows redistribution of an organization’s resources and defining the resource limits.
|manageWorkspaces |Allows creating and managing all the organization’s workspaces.
|setPermissions |Allows adding and removing users and updating their permissions.
|===

[id="system-permissions"]
== System permissions

System permissions control aspects of the whole Che installation.

The following permissions are applicable to the organization:

[cols=",",options="header",]
|===
|Permission |Description
|manageSystem |Allows control of the system, workspaces, and organizations.
|setPermissions |Allows updating the permissions for users on the system.
|manageUsers |Allows creating and managing users.
|===

[id="super-privileged-mode"]
== Super-privileged mode

The `manageSystem` permission can be extended to provide a super-privileged mode. This allows the user to perform advanced actions on any resources managed by the system. You can read and stop any workspaces with the `manageSystem` permission and assign permissions to users as needed.

The super-privileged mode is disabled by default. You can change to super-privileged mode by configuring the `CHE_SYSTEM_SUPER_PRIVILEGED_MODE` variable in the `che.env` file.

[id="stack-permissions"]
== Stack permissions

A stack is a runtime configuration for a workspace.  See link:stacks.html[stack definition] for more information on stacks.

The following permissions are applicable to stacks:

[cols=",",options="header",]
|===
|Permission |Description
|search |Allows searching of the stacks.
|read |Allows reading of the stack configuration.
|update |Allows updating of the stack configuration.
|delete |Allows deleting of the stack.
|setPermissions |Allows managing permissions for the stack.
|===

[id="permissions-api"]
== Permissions API

All permissions can be managed using the provided REST API. The APIs are documented using Swagger at `[{host}/swagger/#!/permissions]`.

[id="list-permissions"]
== Listing permissions

To list the permissions that apply to a specific resources, run this command:
----
$ GET /permissions
----

The `domain` values are:

[cols="",options="header",]
|===
|Domain
|`system`
|`organization`
|`workspace`
|`stack`
|===

[NOTE]
====
`domain` is optional.  In this case, the API returns all possible permissions for all domains.
====

[id="list-permissions-for-specific-user"]
== Listing permissions for a user

To list the permissions that apply to a user, run this command:

----
$ GET /permissions/{domain}
----

The `domain` values are:

[cols="",options="header",]
|===
|Domain
|`system`
|`organization`
|`workspace`
|`stack`
|===


[id="list-permissions-for-all-users"]
== Listing permissions for all users

[NOTE]
====
You must have sufficient permission to see this information.
====

To list the permissions that apply to all users, run this command:

----
GET /permissions/{domain}/all
----

The `domain` values are:

[cols="", options="header",]
|===
|Domain
|`system`
|`organization`
|`workspace`
|`stack`
|===


[id="assign-permissions"]
== Assigning permissions

To assign permissions to a resource, run this command:

`POST /permissions`

The `domain` values are:

[cols="",options="header",]
|===
|Domain
|`system`
|`organization`
|`workspace`
|`stack`
|===

The following is a message `body` that requests permissions for a user with a `userID` to a workspace with a `workspaceID`:

[source,json]
----
{
  "actions": [
    "read",
    "use",
    "run",
    "configure",
    "setPermissions"
  ],
  "userId": "userID",
  "domainId": "workspace",
  "instanceId": "workspaceID"
}
----

The `instanceId` parameter corresponds to the ID of the resource that retrieves the permission for all users. The `userId` parameter corresponds to the ID of the user that has been granted certain permissions.

[id="sharing-permissions"]
== Sharing permissions

A user with `setPermissions` privileges can share a workspace and grant `read`, `use`, `run`, `configure`, or `setPermissions` privileges to other users.

To share workspace permissions:

* Select a workspace in the user dashboard, navigate to the *Share* tab and enter emails of users. Use commas or space as separators
 if there are multiple emails).
