---
title: "Permissions"
keywords: organizations, user management, permissions
tags: [organizations]
sidebar: user_sidebar
permalink: permissions.html
folder: user-management
---


[id="overview"]
== Overview

Permissions are used to control the actions of users and establish a security model. You can define "who" is allowed to do "what". You control resources managed by Che and allow certain actions by assigning permissions to users.  

Permissions are applied to the following:

* Workspace
* Organization
* Stack
* System

[id="workspace-permissions"]
== Workspace Permissions

The user who creates a workspace is the workspace owner. The workspace owner has the following permissions by default:  read, use, run, configure, setPermissions, and delete. Workspace owners invite users into the workspace and control workspace permissions for each user.

The following permissions are associated with workspaces:

[cols=",",options="header",]
|===
|Permission |Description
|read |You can read the workspace configuration.
|use |You can use the workspace.
|run |You can start and stop a workspace.
|configure |You can define and change the workspace configuration.
|setPermissions |You can update workspace permissions for other users.
|delete |You can delete the workspace.
|===

[id="organization-permissions"]
== Organization Permissions

An organization is a set of users. 

The following permissions are associated with the organization:

[width="100%",cols="30%,70%",options="header",]
|===
|Permission |Description
|update |You can edit the settings and information of the organization.
|delete |You can delete an organization.
|manageSuborganizations |You can create and manage sub-organizations.
|manageResources |You can redistribute the organization’s resources and define resource limits.
|manageWorkspaces |You can create and manage all the organization’s workspaces.
|setPermissions |You can add and remove users and update their permissions.
|===

[id="system-permissions"]
== System Permissions

System permissions control aspects of the Che installation.

The following permissions are associated with the system:

[cols=",",options="header",]
|===
|Permission |Description
|manageSystem |You can control the system, workspaces and organizations.
|setPermissions |You can update the permissions for users on the system.
|manageUsers |You can create and manage users.
|===

[id="super-privileged-mode"]
== Super Privileged Mode

The permission "manageSystem" provides a super privileged mode that allows you to perform advanced actions on any resources managed by the system. You can read and stop any workspaces with the  "manageSystem" permission and assign permissions to users as needed. 

The super privilege mode is disabled by default. You can change to super privilege mode by configuring the `CHE_SYSTEM_SUPER_PRIVILEGED_MODE` in the `che.env` file.

[id="stack-permissions"]
== Stack Permissions

A stack is a runtime configuration for a workspace.  See link:stacks.html[stack definition] for more information on stacks.

The following permissions are associated with the stack:

[cols=",",options="header",]
|===
|Permission |Description
|search |You can search the stack.
|read |You can read the stack’s configuration.
|update |You can update the stack’s configuration.
|delete |You can delete the stack.
|setPermissions |You can manage permissions for the stack.
|===

[id="permissions-api"]
== Permissions API

All permissions can be managed using the provided REST API. You document APIs with Swagger at `[{host}/swagger/#!/permissions]`.

[id="list-permissions"]
== Listing permissions

To list the permissions that apply to a specific resources, run this command:
 `$ GET /permissions`

The `domain` values are:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===

[NOTE]
====
`domain` is optional, in this case the API will return all possible permissions for all domains.
====

[id="list-permissions-for-specific-user"]
== Listing permissions for a user

To list the permissions that apply to a user, run this command: 
`$ GET /permissions/{domain}`

The `domain` values are:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===


[id="list-permissions-for-all-users"]
== Listing permissions for all users

[NOTE]
====
You must have sufficient permission to see this information.
====

To list the permissions that apply to all users, run this command:  

`GET /permissions/{domain}/all`

The `domain` values are:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===


[id="assign-permissions"]
== Assigning Permissions

To assign permissions to a resource, run this command: 

`POST /permissions`

The `domain` values are:

[cols="",options="header",]
|===
|Domain
|system
|organization
|workspace
|stack
|===

The following is a message `body` that requests permissions for a user with a `userID` to a workspace with a `workspaceID`:

[source,json]
----
{
  "actions": [
    "read",
    "use",
    "run",
    "configure",
    "setPermissions"
  ],
  "userId": "userID",
  "domainId": "workspace",
  "instanceId": "workspaceID"
}
----

The `instanceId` parameter corresponds to the ID of the resource that retrieves the permission for all users. The `userId` parameter corresponds to the ID of the user who wants to grant certain permissions.

[id="sharing-permissions"]
== Sharing Permissions

A user with `setPermissions` privileges can share a workspace and grant `read, use, run, configure or setPermissions` privileges to users.

To share workspace permissions:

* Select a workspace in the user dashboard, navigate to *Share* tab and enter emails of users. Use commas or space as separator if there are multiple emails).
