////
COPIED, TO BE REWRITTEN:
:_content-type: assembly
:description: Projects with Git
:keywords: projects-with-git, project-with-git, onboarding-to-projects-git, onboarding-to-projects-with-git, projects-git, project-git, git-project, git-repository, git-repositories
:navtitle: Projects with Git
// :page-aliases:

[id="projects-with-git_{context}"]
= Projects with Git
////


MENTION THAT YOU MANAGE WORKSPACES IN THE DASHBOARD AND BY USING THE ESSENTIAL LINKS

////
REUSE BY XREF AS MANY OF THE FOLLOWING MODULES AS POSSIBLE IN BOTH 'PROJECTS WITH GIT' AND 'PROJECTS WITHOUT GIT'
  LOG IN AS A USER (SHOULD EXPLAIN WHEN/HOW THE LOGIN PAGE APPEARS)
//SEPARATE PROC DRAFTED: START A NEW WORKSPACE
  REOPEN BY REVISITING A COPIED/SAVED/BOOKMARKED LINK AFTER (FOR EXAMPLE, ACCIDENTALLY) CLOSING THE BROWSER TAB/WINDOW
////REUSE THIS ALSO IN THE PROC FOR STARTING A NEW WORKSPACE:
  ----
You can copy the link of the running workspace from the address bar of the browser, and/or you can bookmark the link in your browser. Here add the snip for bookmarking pages.

if you close the tab with the workspace by mistake, if your browser is still open, you can reopen the closed tab, and the workspace will reconnect.
If you log out from the dashboard and/or close your browser, or use a different browser, entering the workspace URL will result in having to log in and after that the running workspace will reconnect.

----
TIP: to go to the dashboard when you don't have the Che URL saved as a browser bookmark, just remove the workspace part of the URL (the Che URL will ?remain?), and press Enter go to the Che URL.
----

THE FOLLOWING IS RELEVANT TO (a) USING THE WORKSPACE, (b) STOP, (c) RESTART:
mention https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_idle_timeout
&
mention https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_run_timeout

Dealing with hitting limits:
like
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#_che_limits_workspace_env_ram
(timeout limits are covered in another section)
and users's limits
like
https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/#users-workspace-limits


include::partial$proc_uo-stopping-the-running-workspace.adoc[]
include::partial$proc_uo-restarting-a-workspace.adoc[]
include::partial$proc_uo-deleting-a-workspace.adoc[]
