[id="uo-starting-a-new-workspace-with-a-clone-of-a-git-repository_{context}"]
= Starting a new workspace with a clone of a Git repository

{prod-short} allows you to  start a new workspace that contains a clone of a Git repository. You can have your remote origin or fork cloned into a new starting workspace. Or you can have a common repository of a project cloned into a new starting workspace. With such Git providers as GitHub and GitLab, you can also specify the branch for the new starting workspace to checkout.

NOTE: Advanced users can compose and use their own devfiles, as well as use a local devfile.
//provide links on "compose" and "local devfile" to the corresponding sections in Advanced Use (User Guide). Max

.Prerequisites

* Your organization has a running instance of {prod-short}.
* You have been given the link:url-of-your-organizations-prod-id-instance.adoc[URL of your organization's {prod-short} instance].
* Your project maintainer keeps the `devfile.yaml` or `.devfile.yaml` file in the root directory of the Git repository.

.Procedure

. Optional: visit your {prod-short} link:url-of-your-prod-id-dashboard.adoc[dashboard] to log in as a {prod-short} user to your organization's instance of {prod-short}.

. Visit the link:urls-for-starting-a-new-workspace.adoc[URL to start a new workspace].
+
A new tab opens with the workspace-starting page in *Progress*.
+
When the new workspace is ready, the workspace user interface loads in the browser tab.
+
A clone of the Git repository is present in the filesystem of the new workspace.

.Additional resources

* xref:parameters-for-urls-for-starting-a-new-workspace.adoc[]
//* LINK TO ADVANCED USE FOR FEATURE BRANCHES THAT THE USER CAN HAVE A CUSTOM DEVFILE FOR
//* LINK TO ADVANCED USE FOR LONG-URL SYNTAX AND THE FEATURES IT ENABLES?
