:_content-type: CONCEPT
:description: URL parameter for starting duplicate workspaces
:keywords: start-duplicate-workspaces, start-duplicated-workspaces, duplicate-workspace, duplicate-workspaces, duplicated-workspace, duplicated-workspaces, how-to-start-a-duplicate, how-to-start-duplicate
:navtitle: URL parameter for starting duplicate workspaces
// :page-aliases:

[id="url-parameter-for-starting-duplicate-workspaces_{context}"]
= URL parameter for starting duplicate workspaces

Visiting a URL for starting a new workspace results in a workspace that is based on a combination of a devfile and a linked Git repository.

In some situations, you may need to start one or more workspaces from the same URL for starting a new workspace, resulting in workspaces that are duplicates in terms of the same devfile and the same linked Git repository. The URL parameter for starting a duplicate workspace is `new`. The URL for starting a new workspace has the following syntax with the `new` parameter:

[source,subs="+quotes,+attributes"]
----
{prod-url}#__<git_repository_url>__?new
----

TIP: Attempting to reuse the devfile and linked Git repository without the `new` URL parameter to start a new workspace in addition to a workspace that already exists results in an error message.

.Additional resources
* xref:urls-for-starting-a-new-workspace.adoc[]
* xref:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[]