REWRITE

:_content-type: concept
:description: URL parameter for devfile path
:keywords: devfile, devfile-path, url-parameter
:navtitle: URL parameter for devfile path
// :page-aliases:

[id="url-parameter-for-devfile-path_{context}"]
= URL parameter for devfile path

When you visit a link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace], {prod-short} searches the linked Git repository for a devfile with the file name `.devfile.yaml` or `devfile.yaml`. So the devfile in the linked Git repository must follow this convention.

In some situations, you may need to specify a different, non-conventional path for the devfile in the linked repository. The URL parameter for the link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] to specify a path of the devfile is ``. The link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] has the following syntax with the `` parameter:

[source,subs="+quotes,+attributes"]
----
{prod-url}#__<Git_repository_URL>__? <1>
----
<1> `<filename>__.yaml` is the non-conventional file path of the devfile in the linked Git repository.

TIP: The `?df=__<filename>__.yaml` parameter has a long version: `?devfilePath=__<filename>__.yaml`.

.Additional resources
* xref:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[]