:_content-type: concept
:description: URL parameter for devfile file path
:keywords: devfile, file-path, devfile-path, devfile-file-path, url-parameter, devfile-path-parameter, devfile-file-path-parameter
:navtitle: URL parameter for devfile file path
// :page-aliases:

[id="url-parameter-for-devfile-file-path_{context}"]
= URL parameter for devfile file path

When you visit a link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace], {prod-short} searches the root directory of the linked Git repository for a devfile (with the file name `.devfile.yaml` or `devfile.yaml`). So the file path of the devfile in the linked Git repository must follow this convention.

In some situations, you may need to specify a different, unconventional file path for the devfile in the linked Git repository. The URL parameter for the link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] to specify an unconventional file path of the devfile is `devfilePath=__<relative_file_path>__`. The link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] has the following syntax with the `devfilePath=__<relative_file_path>__` parameter:

[source,subs="+quotes,+attributes"]
----
{prod-url}#__<git_repository_url>__?devfilePath=__<relative_file_path>__ <1>
----
<1> `__<relative_file_path>__` is an unconventional file path of the devfile in the linked Git repository.

.Additional resources
* xref:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[Starting a new workspace with a clone of a Git repository]