REWRITE

:_content-type: concept
:description: URL parameter for devfile file name
:keywords: devfile, override-devfile-file-name, override-file-name, file-name, devfile-name, different-devfile-name
:navtitle: URL parameter for devfile file name
// :page-aliases:

[id="url-parameter-for-devfile-file-name_{context}"]
= URL parameter for devfile file name

When you visit a link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace], {prod-short} searches the linked Git repository for a devfile with the file name `.devfile.yaml` or `devfile.yaml`. So the devfile in the linked Git repository must follow this convention.

In some situations, you may need to specify a different, non-conventional file name for the devfile. The URL parameter for the link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] to specify a non-conventional file name of the devfile is `?df=__<filename>__.yaml`. The link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] has the following syntax with the `?df=__<filename>__.yaml` parameter:

[source,subs="+quotes,+attributes"]
----
{prod-url}#__<Git_repository_URL>__?df=__<filename>__.yaml <1>
----
<1> `<filename>__.yaml` is a non-conventional file name of the devfile in the linked Git repository.

TIP: The `?df=__<filename>__.yaml` parameter has a long version: `?devfilePath=__<filename>__.yaml`.




?che-editor=eclipse/che-theia/latest

?che-editor=eclipse/che-theia/next

?che-editor=che-incubator/intellij-community/latest

?che-editor=che-incubator/pycharm/latest

?che-editor=che-incubator/che-code/insiders



.Additional resources
* xref:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[]
