:_content-type: concept
:description: URL parameter for workspace IDE
:keywords: url-parameter-workspace-ide, workspace-ide, url-workspace-ide, url-parameter-workspace-editor, workspace-editor, url-workspace-editor
:navtitle: URL parameter for workspace IDE
// :page-aliases:

[id="url-parameter-for-workspace-ide_{context}"]
= URL parameter for workspace IDE

Che-Theia is currently the default integrated development environment (IDE) that a workspace loads with if no IDE is specified as a URL parameter as part of the link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace].

The URL parameter for the link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] to specify another supported IDE is `che-editor=__<editor_key>__`. The link:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[URL for starting a new workspace] has the following syntax with the `che-editor=__<editor_key>__` parameter:

[source,subs="+quotes,+attributes"]
----
{prod-url}#__<git_repository_url>__?che-editor=__<editor_key>__ <1>
----
<1> `__<editor_key>__` is one of the following values:

ifeval::["{project-context}" == "che"]
* `eclipse/che-theia/latest`
+
NOTE: This is the default IDE with link:https://github.com/che-incubator/chectl/[chectl stable]: this IDE loads in a new workspace without entering this URL parameter.

* `eclipse/che-theia/next`
+
NOTE: This is the default IDE with link:https://github.com/che-incubator/chectl/[chectl next]: this IDE loads in a new workspace without entering this URL parameter.
endif::[]

ifeval::["{project-context}" == "crw"]
* `eclipse/che-theia/latest`
+
NOTE: This is the default IDE: it loads in a new workspace without this URL parameter.
endif::[]

* `che-incubator/che-code/insiders`

* `che-incubator/intellij-community/latest`

* `che-incubator/pycharm/latest`

.Additional resources
* xref:starting-a-new-workspace-with-a-clone-of-a-git-repository.adoc[Starting a new workspace with a clone of a Git repository]
