---
title: "Recipes"
keywords: workspace, runtime, recipe, docker, stack
tags: [workspace, runtime, docker, kubernetes]
sidebar: user_sidebar
permalink: recipes.html
folder: workspace-admin
---


[id="supported-recipe-formats"]
== Supported Recipe Formats

Depending on the infrastructure, Che supports the following default recipe formats:

[cols=",,,,",options="header",]
|===
|*Infrastructure* |*Docker Image* |*Dockerfile* |*Composefile* |*Kubernetes yaml*
|*Docker* |Supported |Supported |Supported |Not supported
|*OpenShift* |Supported |Not supported |Not supported |Supported
|===

[id="docker-image"]
== Docker Image

The Docker image recipe pulls an image from a Docker registry or uses the local image.  The Docker image recipe runs the image and creates a pod that references this image in the container specification. The following are Docker image requirements and limitations for a workspace machine:

1.  Use a non-terminating `CMD` or `ENTRYPOINT`. If you use a custom image, ensure that `tail -f /dev/null` is one of the main processes.
2.  For OpenShift only, do not use any processes and operations with `sudo` in `CMD`. See link:openshift-config.html#enable-ssh-and-sudo[Enable sudo].
3.  For OpenShift only, use https://github.com/eclipse/che-dockerfiles/tree/master/recipes/stack-base[Che base stacks]. You can also build your own image, but inherit from one of the base stacks.

[id="dockerfile"]
== Dockerfile

A Dockerfile is a set of instructions that Docker performs to build an image. After you provide a Dockerfile for your workspace machine, Che initiates a Docker build and runs the resulting image. The following are the limitations:

1.  `COPY` and `ADD` fail because there is no context in docker build.
2.  The build of large images take a huge amount of time.  If you have a long Dockerfile, build an image locally, push it to DockerHub and then use it as a DockerImage recipe type. The start timeout for a workspace is 5 mins.

[id="composefile"]
== Composefile

You can run multi-container workspaces using Compose files on Docker.  The unsupported syntax: *Local "build.context" and "build.dockerfile"*

You cannot build locally. A git repository can act as a build context.

If the Dockerfile or build context requires other files to be `ADD` or `COPY` into the image,  you could run into a failure.  as the local Che workspace generator will not have access to those other remote files. To address this issue, you can pre-package the build context or Dockerfile into an image, push into a registry, and then reference the already-built image in your compose file. This is what we do for internal development at Codenvy.

[source,yaml]
----
build:
  ## remote context will work
  context: https://github.com/eclipse/che-dockerfiles.git#master:recipes/stack-base/ubuntu

  ## local context will not work
  context: ./my/local/filesystem
----

Using Private Repositories:

To use private repositories in a remote build context, you need to setup ssh keys on your host machine and add remote repository hostname/IP to the list of known hosts.

[source,yaml]
----
## The following will use master branch and build in recipes/stack-base/ubuntu folder
build:
  context: git@github.com:eclipse/che-dockerfiles.git#master:recipes/stack-base/ubuntu
----

*Build Image*

In the event that a Compose file includes both build instructions and a build image the build instructions are seen as overriding, so the build image is skipped if it exists.

*Container Name*

[source,yaml]
----
container_name: my_container
----

`container_name` is skipped during execution. Instead, Che generates container names based on its own internal patterns. Because many developers could be running the same Compose file on the same Che workspace node at the same time naming conflicts need to be avoided.

*Volumes*

To define volumes for workspace machines, see Volumes[volumes]. Volume instructions in a Composefile are not supported.

*Networks*

[source,yaml]
----
## Not supported
networks:
  internal:
  aliases: ['my.alias’]
## Not supported
networks:
  internal:
  driver: bridge
----

Che does not yet currently support compose networks. We do, however, support the use of aliases through `links` command.

*Hostname*

Hostname is not supported and the machine’s name will be used for the hostname. User can use `links` aliases syntax to add additional hostname(s) to a machine.

*Ports*

Binding ports to the host system is not supported. This is done to ensure that each container does not used already assigned host ports because many developers could be running the same compose file on the same Che server host at the same time. Users can add link:servers.html[servers] to machines though.

*Privileged*

To secure the underlying host system `privileged` compose command is not supported.

The Che server can be configured to give all containers privileged access by setting the environment variable `CHE_PROPERTY_machine_docker_privilege__mode=true`. However, this makes the host system vulnerable and gives all containers access to the host system.

*Environment File* The `env_file` compose command is not supported. Environment variables can be manually entered in compose file or machine configuration. See: link:env-variables.html[Environment variables].

[id="kubernetes-yaml"]
== Kubernetes YAML

When a workspace is being started, Che creates a https://kubernetes.io/docs/concepts/workloads/pods/pod/[Kubernetes pod]. A few gotchas:

1.  Che allows user to create pods and services only
2.  Other object kinds will be ignored (PVC and route) or a workspace fails to start with an exception from Kubernetes.
3.  Volumes are not supported both in container and pod definition. See: link:volumes.html[Volumes] for info about persisting ans sharing data between pods.

Below is an example of a custom recipe with two containers and one pod, and a service that is bound to port 8081:

[source,yaml]
----
kind: List
items:
-
 kind: Service
 apiVersion: v1
 metadata:
  name: my-service
 spec:
  selector:
    name: app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: app
  spec:
    containers:
      -
        image: eclipse/ubuntu_jdk8:latest
        name: main
        ports:
         -
          containerPort: 8081
          protocol: TCP
      -
        image: eclipse/ubuntu_jdk8:latest
        name: main1
----

You can also have one pod and several containers in it. Che will treat those containers as workspace machines. You can also define machine names in annotations. `PodName/Container Name` is the default naming pattern for a machine. You can use annotations though:

[source,yaml]
----
kind: List
items:
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: any123123
    annotations:
      org.eclipse.che.container.main.machine_name: myMachine
      org.eclipse.che.container.main1.machine_name: myMachine1
  spec:
    containers:
      -
        image: rhche/spring-boot:latest
        name: main
        ports:
          -
            containerPort: 8080
            protocol: TCP
        resources: {}

      -
        image: rhche/spring-boot:latest
        name: main1
        ports:
          -
            containerPort: 8080
            protocol: TCP
        resources: {}
----
