---
title: "Recipes"
keywords: workspace, runtime, recipe, docker, stack
tags: [workspace, runtime, docker, kubernetes]
sidebar: user_sidebar
permalink: recipes.html
folder: workspace-admin
---


[id="supported-recipe-formats"]
== Supported Recipe Formats

Depending on the infrastructure, Che supports the following default recipe formats:

[cols=",,,,",options="header",]
|===
|*Infrastructure* |*Docker-formatted container image* |*Dockerfile* |*Composefile* |*Kubernetes yaml*
|*Docker* |Supported |Supported |Supported |Not supported
|*OpenShift* |Supported |Not supported |Not supported |Supported
|===

[id="docker-formatted-container"]
== Docker-formatted container image requirements and limitations

The Docker-formatted container image recipe pulls an image from a Docker registry or uses the local image.  The Docker-formatted container image recipe runs the image and creates a pod that references this image in the container specification. The following are Docker-formatted container image requirements and limitations for a workspace machine:

1.  Use a non-terminating `CMD` or `ENTRYPOINT`. If you use a custom image, ensure that `tail -f /dev/null` is one of the main processes.
2.  For OpenShift only, do not use any processes and operations with `sudo` in `CMD`. See link:openshift-config.html#enable-ssh-and-sudo[enable sudo].
3.  For OpenShift only, use https://github.com/eclipse/che-dockerfiles/tree/master/recipes/stack-base[Che base stacks]. You can also build your own image, but inherit from one of the base stacks.

[id="dockerfile"]
== Dockerfile

A Dockerfile is a set of instructions that Docker performs to build an image. After you provide a Dockerfile for your workspace machine, Che initiates a Docker build and runs the resulting image. The following are the limitations:

1.  The `COPY` and `ADD` instructions fail because there is no context in docker build.
2.  The build of large images takes a huge amount of time.  If you have a long Dockerfile, build an image locally, push it to DockerHub and then use it as a Docker-formatted container image recipe type. The start timeout for a workspace is five minutes.

[id="composefile"]
== Compose file

You can run multi-container workspaces using Compose files on Docker.  The unsupported syntax is: *Local "build.context" and "build.dockerfile"*.

Since Che workspaces can be distributed, you cannot have host-local build and Dockerfile contexts.  You can place these aspects in a git repository where they are remotely hosted. Che can source the compose file from the remote system and use it as the build context.

You can run into a failure when the Dockerfile or build context requires you to `ADD` or `COPY` other files into the image.  The local Che workspace generator will not have access to those other remote files. To address this issue, you can pre-package the build context or Dockerfile into an image, push into a registry, and reference the already-built image in your compose file. 

The following is an example of a remote context that works:

[source,yaml]
----
build:
  ## remote context will work
  context: https://github.com/eclipse/che-dockerfiles.git#master:recipes/stack-base/ubuntu

  ## local context will not work
  context: ./my/local/filesystem
----

=== Using private repositories

To use private repositories in a remote build context, you need to setup the ssh keys on your host machine and add the remote repository hostname or IP to the list of known hosts.

The following is an example of a yaml file using a private repository:

[source,yaml]
----
## The following will use master branch and build in recipes/stack-base/ubuntu folder
build:
  context: git@github.com:eclipse/che-dockerfiles.git#master:recipes/stack-base/ubuntu
----

=== Using build images

When a Compose file includes both build instructions and a build image, the build instructions are seen as overriding and the build image is skipped if it exists.

=== Using container names

The `container_name` is skipped during execution. Instead, Che generates container names based on its own internal patterns. Naming conflicts need to be avoided because many developers could be running the same Compose file on the same Che workspace node at the same time.

The following is an example of a yaml file using a container name:

[source,yaml]
----
container_name: my_container
----

=== Defining volumes

To define volumes for workspace machines, see Volumes[volumes]. Volume instructions in a Composefile are not supported.

=== Using networks

Che does not support compose networks. The use of aliases is supported by the `links` command.

The following is an example of networks:

[source,yaml]
----
## Not supported
networks:
  internal:
  aliases: ['my.alias’]
## Not supported
networks:
  internal:
  driver: bridge
----

=== Using hostname

The hostname is not supported.  The machine’s name is used for the hostname. You can use `links` aliases syntax to add additional hostname(s) to a machine.

=== Binding ports

Binding ports to the host system is not supported in order to ensure that each container does not use already assigned host ports.  Many developers could be running the same compose file on the same Che server host at the same time. You can add link:servers.html[servers] to the machines.

=== Using the privileged command

The `privileged` compose command does not support securing the underlying host system.

The Che server can be configured to give all containers privileged access by setting the `CHE_PROPERTY_machine_docker_privilege__mode` variable to `true`. However, this makes the host system vulnerable and gives all containers access to the host system.

=== Using the environment file command

The `env_file` compose command is not supported. Environment variables can be manually entered in compose file or machine configuration. See link:env-variables.html[environment variables] for more information.

[id="kubernetes-yaml"]
== Kubernetes YAML

When a workspace is starting, Che creates a https://kubernetes.io/docs/concepts/workloads/pods/pod/[Kubernetes pod]. The following are limitatons and restrictions:

1.  Che allows user to create pods and services only.
2.  Other object kinds such as PVCs and routes will be ignored or a workspace fails to start with an exception from Kubernetes.
3.  Volumes are not supported in container and pod definition. See link:volumes.html[Volumes] for information about persisting and sharing data between pods.

The following is an example of a custom recipe with two containers and one pod, and a service that is bound to port 8081:

[source,yaml]
----
kind: List
items:
-
 kind: Service
 apiVersion: v1
 metadata:
  name: my-service
 spec:
  selector:
    name: app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: app
  spec:
    containers:
      -
        image: eclipse/ubuntu_jdk8:latest
        name: main
        ports:
         -
          containerPort: 8081
          protocol: TCP
      -
        image: eclipse/ubuntu_jdk8:latest
        name: main1
----

You can also have one pod and several containers in it. Che will treat those containers as workspace machines. You can also define machine names in annotations. `PodName/Container Name` is the default naming pattern for a machine.

The following is an example of using annotations:

[source,yaml]
----
kind: List
items:
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: any123123
    annotations:
      org.eclipse.che.container.main.machine_name: myMachine
      org.eclipse.che.container.main1.machine_name: myMachine1
  spec:
    containers:
      -
        image: rhche/spring-boot:latest
        name: main
        ports:
          -
            containerPort: 8080
            protocol: TCP
        resources: {}

      -
        image: rhche/spring-boot:latest
        name: main1
        ports:
          -
            containerPort: 8080
            protocol: TCP
        resources: {}
----
