---
title: "Volumes"
keywords: workspace, runtime, recipe, docker, stack, volume, volumes
tags: [workspace, runtime, docker, kubernetes]
sidebar: che_6_docs
permalink: volumes.html
folder: workspace-admin
---


[id="default-volumes"]
== Default volumes

Workspace containers start with a default volume and has a minimum of one PVC that is located in the following directory: `/projects`. Workspace projects are physically located in the `/projects` directory. When a workspace stops, the machines are destroyed and the volumes persists.

[id="user-provided-volumes"]
== User-provided volumes

Your workspace may need additional volumes to persist a local Maven repository, node_modules folder, ruby jems, or authorized_keys file for SSH connections. You can add as many additional volumes for your workspace machines as the machine's infrastructure can support or limit.

You can add volumes either by using the  *User Dashboard* or by updating the machine configuration.  The following is an example of the YAML configuration file: 

[source,json]
----
"volumes": {
  "myvolume": {
    "path": "/absolute/path/in/workspace"
  }
}
----

When adding a volume in the *User Dashboard*, the volume name and path are validated to avoid potential failures.  If you update the workspace configuration using REST API, the volume name and path are validated :

* the path contains `~` - an absolute path should be used
* the name and path contains special characters, including `-` and `_`

If you want your workspace machines to share volumes, create volumes for each machine with an identical name. This will allow machines to share the same volume.


[id="empty-dir-volumes"]
== Configuring workspaces

To configure workspaces on the OpenShift and Kubernetes infrastructure as ephemeral, set the `persistVolumes` attribute to `false` in the workspace configuration.

[source,json]
----
"attributes": {
  "persistVolumes": "false"
}
----

In this case, regardless of the link:openshift-admin-guide.html#che-workspaces-storage[PVC strategy], all volumes would be created as https://kubernetes.io/docs/concepts/storage/volumes/#emptydir[`emptyDir`] for the given workspace. When a workspace Pod is removed for any reason, the data in the `emptyDir` volume is deleted forever.
