---
title: "Volumes"
keywords: workspace, runtime, recipe, docker, stack, volume, volumes
tags: [workspace, runtime, docker, kubernetes]
sidebar: che_6_docs
permalink: volumes.html
folder: workspace-admin
---


[id="default-volumes_for_workspace_containers"]
== Default volumes for workspace containers

By default, workspace containers start with a default volume and have a minimum of one PVC that is located in the `/projects` directory. 

Workspace projects are physically located in the `/projects` directory. When a workspace stops, the machines are destroyed, but the volumes persist.

[id="Adding-volumes"]
== Adding volumes

In order for your data to persist for a local Maven repository, the `node_modules/` directory, Ruby gems, or the `authorized_keys` file for SSH connections, your workspace will need additional volumes. Each machine can add as many volumes as the underlying infrastructure can support. OpenShift may impose a limit on the number of volumes.

You can add volumes either by using the  *User Dashboard* or by updating the machine configuration.  The following is an example of the configuration file: 

[source,json]
----
"volumes": {
  "myvolume": {
    "path": "/absolute/path/in/workspace"
  }
}
----


To avoid failures when updating the workspace configuration using REST APIs: 

* Use an absolute path. 
* The name and path cannot contain special characters, including dashes (`-`) or underscores (`_`).

[NOTE]
====
To allow machines to share the same volume, create a volume for each machine with an identical name. 
====

[id="configuring-workspaces"]
== Configuring workspaces

To configure workspaces on the OpenShift and Kubernetes infrastructure as ephemeral, set the `persistVolumes` attribute to `false` in the workspace configuration.

The following is an example of the configuration file:

[source,json]
----
"attributes": {
  "persistVolumes": "false"
}
----

In this case, regardless of the link:openshift-admin-guide.html#che-workspaces-storage[PVC strategy], all volumes would be created as https://kubernetes.io/docs/concepts/storage/volumes/#emptydir[`emptyDir`] for the given workspace. When a workspace pod is removed for any reason, the data in the `emptyDir` volume is deleted forever.
