---
title: "Troubleshooting workspace start failures"
keywords: workspace, runtime, recipe, docker, yaml, Dockerfile, docker, kubernetes, container, pod
tags: [workspace, runtime, docker, kubernetes, troubleshooting]
sidebar: che_6_docs
permalink: workspaces-troubleshooting.html
folder: workspace-admin
---


Failures to start a workspace may be caused by different factors:

1.  Environment recipe
2.  Network conditions

[id="bad-recipes"]
== Bad Recipes

When a workspace is starting, the environment link:recipes.html[recipe] is sent to Docker or to the OpenShift API. The Che server then listens to events provided by a particular infrastructure. In simple words, the Che server expects a running container (Docker) or pod (OpenShift). If the infrastructure was unable to create and start a container or a pod from the provided recipe, the Che server fails to start an environment and consequently the starting of the workspace fails.

A recipe can be bad due to the following reasons:

* The Docker build fails with the provided `Dockerfile`. This can be because of a broken `Dockerfile` or because of Che. If the Docker build in Che link:recipes.html#dockerfile[does not support context], consider editing the Docker recipe locally to ensure that it is a valid `Dockerfile`. Add or copy resources into an image locally on your machine, push the image to a registry (say, DockerHub), and use the resulting images in the recipe.

* Che does not support certain link:recipes.html#composefile[Docker Compose syntax]. Ensure your `Composefile` is supported by Che.

* Timeouts: Installing packages in your Dockerfile instructions can take time. Moreover, in this case you depend on network conditions.

If a workspace start fails because the container or the pod was not launched, you will not see logs from link:installers.html[installers]. Usually, you will find logs from infrastructure, image pull, build,  etc. Analyze these logs to find the problem. The Che server also produces logs that are helpful in debugging the problem.

[id="network-conditions"]
== Network Conditions

The Che server, agents running in a workspace container or pod, and the user’s browser communicate with each other. Firewall, filtered ports, and other network restrictions may cause troubles when starting a workspace.

A workspace is considered to be in a `RUNNING` state after the Che server verifies that the workspace agent is up. The workspace agent also tries to reach the Che server. All this happens in separate containers or pods, and the user’s browser is not yet involved (you may start a workspace using REST API, for example). The *workspace started by user $userName* message from the Che server logs indicates that the workspace container or pod is up, the workspace agent has successfully started, and the Che server is able to reach it.

It is possible that your browser (the client) cannot connect to a workspace agent. The Che server may use an internal IP to reach the workspace agent, while you may access a workspace from a machine that is located in a different network. If you see a message saying that the IDE cannot be initialized, open the browser dev console and check the failed requests. There should be a few requests to project and project-type API. The reason for this is that the ephemeral port range is filtered in your network.

[id="bootstrapping-failures"]
== Failures in bootstrapping

When a workspace starts, the Che server creates and starts a container or a pod or a set of containers and pods as per the environment recipe. After the container or pod is running, a bootstrapping process begins - bootstrapper binary is downloaded and launched. If the server logs show bootstrapping failures, or you do not see any output in the *Machine* tab of the *Workspaces* view, the reason is that bootstrapper is not downloaded. Following are the reasons for the bootstrapper not being downloaded:

* Network conditions (for example, running firewalld).

* Bad bootstrapper binary URL that the Che server uses (often reproduced when deploying to OpenShift and missing necessary environment variables).

Manually download the bootstrapper binary. On OpenShift, access the pod on the command line (rsh or terminal in web console) and run the following command:

----
cd /tmp/bootstrapper
ls -la  # to check if there's a bootstrapper binary
curl ${CHE_URL}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
----

If this curl fails, something in your network blocks port `80`, or `443` (if you use https routes on OpenShift).
