:page-aliases: administration-guide:configuring-single-and-multiroot-workspaces.adoc
:_content-type: PROCEDURE
:description: Work with multiple projects in one workspace
:keywords: singleroot, multiroot, workspace
:navtitle: Work with multiple projects in one workspace

[id="configuring-single-and-multiroot-workspaces"]
= Work with multiple projects in one workspace


[role="_abstract"]
Work with multiple project folders in the same workspace by using the multi-root workspace feature. This is useful when you are working on several related projects at once, such as product documentation and product code repositories.

By default, workspaces open in multi-root mode. After a workspace starts, the `/projects/.code-workspace` workspace file is generated. The workspace file contains all the projects described in the devfile.

[source,json]
----
{
	"folders": [
		{
			"name": "project-1",
			"path": "/projects/project-1"
		},
		{
			"name": "project-2",
			"path": "/projects/project-2"
		}
	]
}
----

If the workspace file already exists, it is updated and all missing projects are taken from the devfile. If you remove a project from the devfile, it remains in the workspace file.

You can change the default behavior and provide your own workspace file or switch to a single-root workspace.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Add a workspace file with the name `.code-workspace` to the root of your repository. After workspace creation, the Visual Studio Code - Open Source ("Code - OSS") uses the workspace file as it is.
+
[source,json]
----
{
	"folders": [
		{
			"name": "project-name",
			"path": "."
		}
	]
}
----
+
[IMPORTANT]
====
Be careful when creating a workspace file. In case of errors, an empty Visual Studio Code - Open Source ("Code - OSS") opens instead. If you have several projects, the workspace file is taken from the first project. If the workspace file does not exist in the first project, a new one is created and placed in the `/projects` directory.
====

. Define the `VSCODE_DEFAULT_WORKSPACE` environment variable in your devfile with the path to an alternative workspace file.
+
[source,yaml]
----
   env:
     - name: VSCODE_DEFAULT_WORKSPACE
       value: "/projects/project-name/workspace-file"
----

. Define the `VSCODE_DEFAULT_WORKSPACE` environment variable and set it to `/` to open a workspace in single-root mode.
+
[source,yaml]
----
   env:
     - name: VSCODE_DEFAULT_WORKSPACE
       value: "/"
----

.Verification

* Start or restart the workspace and verify that Code - OSS opens with the expected workspace mode (single-root or multi-root).

[role="_additional-resources"]
.Additional resources

* link:https://code.visualstudio.com/docs/editing/workspaces/workspaces[What is a VS Code workspace]
* xref:trusted-extensions-for-microsoft-visual-studio-code.adoc[]
* xref:default-extensions-for-microsoft-visual-studio-code.adoc[]
* xref:editor-configurations-for-microsoft-visual-studio-code.adoc[]
