:page-aliases: administration-guide:extensions-for-microsoft-visual-studio-code-open-source.adoc
:_content-type: ASSEMBLY
:description: How the Open VSX extension registry works
:keywords: extensions, vs-code, vsx, open-vsx, marketplace
:navtitle: How the Open VSX extension registry works

[id="extensions-for-microsoft-visual-studio-code-open-source"]
= How the Open VSX extension registry works

[role="_abstract"]
The Open VSX extension registry works as the extension source for Microsoft Visual Studio Code - Open Source in {prod-short}, providing IDE extensions from one of several configurable registry instances.

To manage extensions, this IDE uses one of the Open VSX registry instances:

* The embedded instance of the Open VSX registry that runs in the `plugin-registry` pod of {prod-short} to support air-gapped, offline, and proxy-restricted environments. The embedded Open VSX registry contains only a subset of the extensions published on the public open-vsx.org registry. This subset is customizable.

* The public open-vsx.org registry that is accessed over the internet.

* A standalone Open VSX registry instance that is deployed on a network accessible from {prod-short} workspace pods.

include::example$snip_{project-context}-default-vsx-registry.adoc[]

include::partial$proc_selecting-an-open-vsx-registry-instance.adoc[leveloffset=+1]

include::partial$proc_adding-or-removing-extensions-in-a-workspace.adoc[leveloffset=+1]

include::partial$proc_adding-or-removing-extensions-on-linux.adoc[leveloffset=+1]