:page-aliases: administration-guide:trusted-extensions-for-microsoft-visual-studio-code.adoc
:_content-type: PROCEDURE
:description: Grant extensions access to OAuth tokens
:keywords: extensions, vs-code, vsx, open-vsx, marketplace
:navtitle: Grant extensions access to OAuth tokens

[id="visual-studio-code-trusted-extensions"]
= Grant extensions access to OAuth tokens


[role="_abstract"]
Grant specific extensions access to OAuth authentication tokens in Microsoft Visual Studio Code by configuring the `trustedExtensionAuthAccess` field. Extensions that access services such as GitHub or Microsoft can then authenticate without manual intervention.

[source,json,subs="+quotes"]
----
	"trustedExtensionAuthAccess": [
		"__<publisher1>.<extension1>__",
		"__<publisher2>.<extension2>__"
	]
----

Define the variable in the devfile or in a ConfigMap.

[WARNING]
====
Use the `trustedExtensionAuthAccess` field with caution as it could potentially lead to security risks if misused. Give access only to trusted extensions.
====

[IMPORTANT]
====
Since the Microsoft Visual Studio Code editor is bundled within `che-code` image, you can only change the `product.json` file when the workspace is started up.
====

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Define the `VSCODE_TRUSTED_EXTENSIONS` environment variable in devfile.yaml:
+
[source,yaml,subs="+quotes"]
----
   env:
     - name: VSCODE_TRUSTED_EXTENSIONS
       value: "__<publisher1>.<extension1>__,__<publisher2>.<extension2>__"
----

. Alternatively, mount a ConfigMap with the `VSCODE_TRUSTED_EXTENSIONS` environment variable. With a ConfigMap, the variable is propagated to all your workspaces and you do not need to add the variable to each devfile you are using.
+
[source,yaml,subs="+quotes"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: trusted-extensions
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  VSCODE_TRUSTED_EXTENSIONS: '__<publisher1>.<extension1>__,__<publisher2>.<extension2>__'
----

.Verification

* Start or restart the workspace and verify that the `trustedExtensionAuthAccess` section is added to the `product.json` file.

[role="_additional-resources"]
.Additional resources

* xref:configuring-single-and-multiroot-workspaces.adoc[]
* xref:default-extensions-for-microsoft-visual-studio-code.adoc[]
* xref:editor-configurations-for-microsoft-visual-studio-code.adoc[]
