---
title: Updating Che
keywords: 
tags: []
sidebar: che_7_docs
permalink: che-7/updating-che/
folder: che-7/installation-guide
summary: 
---

:parent-context-of-updating-che: {context}

[id='updating-che_{context}']
= Updating {prod-short}

:context: updating-che

This chapter describes how to upgrade from {prod-short} {prod-prev-ver} instance to {prod-short} {prod-ver}.

Following scenarios are covered:

* xref:upgrading-from-{prod-id-short}-{prod-prev-ver}-to-{prod-id-short}-{prod-ver}-on-openshift-4-using-the-operator_{context}[]

* xref:upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool_{context}[]

* xref:upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool_{context}[]

WARNING: The method that was used to install the {prod-short} {prod-prev-ver} instance determines the method to proceed with for the upgrade.

include::assembly_upgrading-from-che-6-to-che-7-on-openshift-4-using-the-operator.adoc[leveloffset=+1]

include::proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-4-using-the-cli-management-tool.adoc[leveloffset=+1]

include::proc_upgrading-from-prod-short-prod-prev-ver-to-prod-short-prod-ver-on-openshift-3-using-the-cli-management-tool.adoc[leveloffset=+1]

== Known issues

=== Upgrading from {prod-short} {prod-prev-ver} to {prod-short} {prod-ver} using the Operator

When upgrading the Operator of a {prod-short} {prod-prev-ver} installation to {prod-short} {prod-ver}, some components may not be automatically updated. To fix this, manually update the images listed in the `checluster` custom resource, which describes the {prod-short} installation. To reset the images to their default versions for given Operator version, set the image properties to empty strings. This forces the {prod-short} Operator to use the default versions it was built with.

Review the following components:

|===
| Component | CR attribute name 
| Postgresql | `spec.database.postgresImage` 
| Keycloak | `spec.auth.identityProviderImage` 
| PVC Jobs | `spec.storage.pvcJobsImage`
|===


=== Updating a {prod-short} installation using the Operator

When making changes to the `checluster` custom resource, use patching to make updates to it. For example:

On Kubernetes, run:

[subs="+quotes,+attributes"]
----
$ kubectl patch checluster _<my-che>_ --type=json -n _<che-namespace>_ -p '...'
----

On OpenShift, run:

[subs="+quotes,+attributes"]
----
$ oc patch checluster _<my-che>_ --type=json -n _<che-namespace>_ -p '...'
----

WARNING: Making local updates to the YAML file of the `checluster` resource and then applying such changed resource to
the cluster using `kubectl apply -f` or `oc apply -f` can result in an invalidation of the {prod-short} installation.

:context: {parent-context-of-updating-che}
