---
title: Updating Che
keywords: 
tags: []
sidebar: che_7_docs
permalink: che-7/updating-che/
folder: che-7/installation-guide
summary: 
---

:parent-context-of-updating-che: {context}

[id='updating-che_{context}']
= Updating Che

:context: updating-che

include::assembly_upgrading-from-che-6-to-che-7-on-openshift-4-using-the-operator.adoc[leveloffset=+1]

== Known issues

=== Upgrading from Che 6 to Che 7 using the Operator

When upgrading the Operator of a Che 6 installation to Che 7, some components may not be automatically updated. To fix this, manually update the images listed in the `checluster` custom resource, which describes the Che installation. To reset the images to their default versions for given operator version, set the image properties to empty strings. This forces the Che Operator to use the default versions it was built with.

Review the following components:

|===
| Component | CR attribute name 
| Postgresql | `spec.database.postgresImage` 
| Keycloak | `spec.auth.identityProviderImage` 
| PVC Jobs | `spec.storage.pvcJobsImage`
|===


=== Updating a Che installation using the Operator

When making changes to the `checluster` custom resource, use patching to make updates to it. For example:

On Kubernetes, run:

[subs="+quotes"]
----
$ kubectl patch checluster _<my-che>_ --type=json -n _<che-namespace>_ -p '...'
----

On OpenShift, run:

[subs="+quotes"]
----
$ oc patch checluster _<my-che>_ --type=json -n _<che-namespace>_ -p '...'
----

WARNING: Making local updates to the YAML file of the `checluster` resource and then applying such changed resource to
the cluster using `kubectl apply -f` or `oc apply -f` can result in an invalidation of the Che installation.

:context: {parent-context-of-updating-che}
