---
title: Installing Che in TLS mode with self-signed certificates
keywords: installation, tls, self-signed certificate, https
tags: []
sidebar: che_7_docs
permalink: che-7/installing-che-in-tls-mode-with-self-signed-certificates/
folder: che-7/contributor-guide
summary:
---

:page-liquid:
:parent-context-of-installing-che-in-tls-mode-with-self-signed-certificates: {context}

[id="installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates_{context}"]
= Installing {prod-short} in TLS mode with self-signed certificates

:context: installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates

WARNING: Self-signed certificates is usually used in development and evaluation enviromnents. If you want to use them in production you should understand the consequences.

The following section describes the deployment and configuration of {prod} with self-signed certificates.

{prod} can be deployed on:

 * Kubernetes family infrastructures
 * Openshift family infrastructures

### Delpoying {prod} on Kubernetes family infrastructures

By default, {prod} is deployed on Kubernetes family infratructures with self-signed certificate which is generated automatically during {prod} installation process. There is no need in any additional prerequiremens for the deployment.

However, it is required to link:{site-baseurl}che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-{prod-id-short}-with-tls_installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates[make the browser trust] generated self-signed CA certificate.
If `{prod-cli}` is used to deploy {prod}, it will export self-signed CA certificate into `cheCA.crt` file in current user home directory.
Otherwise, it could be obtained via `{prod-cli} cacert:export` command or directly by reading `self-signed-certificate` secret in the namespace to which {prod} is deployed.

If, due to some reasons, it is required to deploy {prod} with generated by user self-signed certificate, then a namespace for {prod} should be manually created before deployment as well as two secrets in it: `che-tls` TLS secret which holds server TLS certificate and key (with `tls.crt` and `tls.key` fields in the secret data correspondingly) which is signed by self-signed CA certificate, public part of which should be stored in opaque secret `self-signed-certificate` (`ca.crt` key under data section of the secret).
Please refer to the link:{site-baseurl}che-7/installing-che-in-tls-mode-with-self-signed-certificates/#generating-self-signed-certificates_installing-che-in-tls-mode-with-self-signed-certificates[generate needed keys and certificates] section for more info on how to generate the certificates manually or directly see link:{site-baseurl}che-7/installing-che-in-tls-mode-with-self-signed-certificates/#deploying-{prod-id-short}-with-self-signed-tls-on-kubernetes_installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates[full instruction for deploying {prod} with user-defined self-signed certificates on Kubernetes platform].

An example command how to deploy Eclipse Che on Minikube with self-signed certificate:
```sh
chectl server:start --platform=minikube
```

To deploy {prod} with commonly trusted TLS certificate, it is required to precreate single `che-tls` secret as described above in the corresponding namespace.

WARNING: Never create `self-signed-certificate` secret if {prod} deployment intended to use commonly trusted TLS certificate as {prod} will detect that data from `che-tls` secret doesn't match and will replace both secrets with autogenerated data.

NOTE: `che-tls` is the default name of the {prod} server TLS secret and could be changed in the configuration.

### Delpoying {prod} on Opeshift family infrastructures

{prod} uses default router certificate to secure its endpoints. So, it is completely depends on Openshift cluster configuration whether self-signed certificate is used.

Usually, {prod} automatically detects whether Openshift default router uses self-signed certificate by analyzing its certificate chain.
If default router does not put its self-signed CA certificate into the response certificate chain, then it is required to create `self-signed-certificate` secret (with `ca.crt` key in secret data) before {prod} deployment in the corresponding namespace. See link:{site-baseurl}che-7/installing-che-in-tls-mode-with-self-signed-certificates/#deploying-{prod-id-short}-with-self-signed-tls-on-openshift4-using-operator_installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates[this section] for more info.

In case when default router certificate is configured with non root CA certificate which is signed by non-cluster root CA certificate, it is required to add the root CA into additional trusted CA certificates config map in order to deploy {prod} on such Openshift cluster.
Sometimes, as a workaround, it is possible to create `self-signed-certificate` secret with router intermidiate CA certificate, see instructions in the paragraph above.

If self-signed certificate is used, it is required to link:{site-baseurl}che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-{prod-id-short}-with-tls_installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates[configure user's browser].

An example command to deploy {prod} on Openshift 4:
```sh
{prod-cli} server:start --platform=openshift
```

WARNING: In case of using Minishift it is required to replace outdated router certificate manually. See link:{site-baseurl}che-7/installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates/#deploying-{prod-id-short}-with-self-signed-tls-on-openshift3-using-operator_installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates[this section] for detailed instructions.

include::proc_deploying-che-with-self-signed-tls-on-openhift4-using-operator.adoc[leveloffset=+1]

include::proc_deploying-che-with-self-signed-tls-on-kubernetes.adoc[leveloffset=+1]

include::proc_deploying-che-with-self-signed-tls-on-openhift3-using-operator.adoc[leveloffset=+1]

include::proc_generating-self-signed-certificates.adoc[leveloffset=+1]

include::proc_using-che-with-tls.adoc[leveloffset=+1]

:context: {parent-context-of-installing-che-in-tls-mode-with-self-signed-certificates}
