---
title: Updating Che
keywords: 
tags: []
sidebar: che_7_docs
permalink: che-7/updating-che.html
folder: che-7/installation-guide
summary: 
---

:parent-context-of-updating-che: {context}

[id='updating-che_{context}']
= Updating Che

:context: updating-che


This paragraph is the assembly introduction. It explains what the user will accomplish by working through the modules in the assembly and sets the context for the user story the assembly is based on. Can include more than one paragraph. Consider using the information from the user story.

[id='prerequisites-{context}']
== Prerequisites

* A bulleted list of conditions that must be satisfied before the user starts following this assembly.
* You can also link to other modules or assemblies the user must follow before starting this assembly.
* Delete the section title and bullets if the assembly has no prerequisites.


Include modules here.

== Known issues

=== Upgrading from Che 6

If you installed Che 6 using the operator, you might have to do a couple of adjustments after the upgrade of
the operator. Upon its upgrade the operator ventures on updating Che server and other components of
the installation to the versions defined by the operator. Because of the change in how such upgrades are handled
between Che 6 and Che 7 operator, this might result in some components being stuck in their old versions.

To resolve this situation, it is necessary to manually update the images mentioned in the `checluster` custom resource
describing the Che installation. Namely, it might be necessary to review the following components:

|===
| Component | CR attribute name | How to update
| Postgresql | `spec.database.postgresImage` | The version of the Postgresql database actually hasn't changed. If you
manually changed the image of the Postgresql server, the change will be preserved.
| Keycloak | `spec.auth.identityProviderImage` | Che uses a customized version of Keycloak image that follows
the versioning of Che itself. Please update the image from `eclipse/che-keycloak:6.19.0` to `eclipse/che-keycloak:7.1.0`
if you upgraded to Che 7.1.0 or use any other corresponding version.
|===

=== Updating Che installation using the operator

When making changes to the `checluster` custom resource, make sure to use patching to make updates to it, e. g.:

```
kubectl patch checluster my-che --type=json -n che-namespace -p '...'
```

or

```
oc patch checluster my-che --type=json -n che-namespace -p '...'
```

WARNING: Making local updates to the YAML file of the `checluster` resource and then applying such changed resource to
the cluster using `kubectl apply -f` or `oc apply -f` can result in invalidation of the Che installation.

[id='related-information-{context}']
== Related information

* A bulleted list of links to other material closely related to the contents of the concept module.
* For more details on writing assemblies, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].

:context: {parent-context-of-updating-che}
