---
title: Installing Che in TLS mode with self-signed certificates
keywords: installation, tls, self-signed certificate, https
tags: []
sidebar: che_7_docs
permalink: che-7/installing-che-in-tls-mode-with-self-signed-certificates/
folder: che-7/contributor-guide
summary:
---

:page-liquid:
:parent-context-of-installing-che-in-tls-mode-with-self-signed-certificates: {context}

[id="installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates_{context}"]
= Installing {prod-short} in TLS mode with self-signed certificates

:context: installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates

The following section describes the deployment and configuration of {prod-short} with self-signed certificates. Self-signed certificates are certificates that are not signed by a commonly trusted certificate authority (CA), but instead signed by a locally created CA. Self-signed certificates are not trusted by default. For example, when a website owner uses a self-signed certificate to provide HTTPS services, users who visit that website see a warning in their browser.

WARNING: Self-signed certificates are usually used in development and evaluation environments. Use in production environments is not recommended.

ifeval::["{project-context}" == "che"]
{prod-short} can be deployed on:

 * Kubernetes-family infrastructures
 * OpenShift-family infrastructures
endif::[]

include::proc_generating-self-signed-tls-certificates.adoc[leveloffset=+1]

ifeval::["{project-context}" == "che"]
include::proc_deploying-che-with-self-signed-tls-certificates-on-kubernetes.adoc[leveloffset=+1]
endif::[]

include::proc_deploying-che-with-self-signed-tls-certificates-on-openhift-4.adoc[leveloffset=+1]

include::proc_deploying-che-with-self-signed-tls-certificates-on-openhift-3.adoc[leveloffset=+1]

include::proc_importing-self-signed-tls-certificates-to-browsers.adoc[leveloffset=+1]

:context: {parent-context-of-installing-che-in-tls-mode-with-self-signed-certificates}
