---
title: Installing Che in restricted environment
keywords: air-gap, airgap, offline
tags:
sidebar: che_7_docs
permalink: che-7/installing-che-in-restricted-environment/
folder: che-7/installation-guide
summary:
---

:page-liquid:
:parent-context-of-installing-che-in-restricted-environment: {context}

[id="installing-{prod-id-short}-in-restricted-environment_{context}"]
= Installing {prod-short} in restricted environment

:context: installing-{prod-id-short}-in-restricted-environment

The following sections describe how to deploy {prod-short} in a Kubernetes or OpenShift cluster in a restricted environment (also called _offline mode_ or _air-gap scenario_).

By default, {prod} workspaces reference various external resources, including container images available in public registries or sample projects hosted on GitHub.

To deploy {prod-short} in an environment where these external resources are not available (for example, on a cluster that is not exposed to the public Internet):

* Build images containing external resources (workspace plug-ins, projects).
* Pull all images needed for running {prod-short} to a registry that is accessible.
* Configure {prod-short} to use these images.

.Prerequisites

* You are logged in to the cluster using the developer account.

* Dynamic provisioning or pre-defined PVs configured before the deployment.

* Block-based storage volume or NFS share available outside of the cluster to serve dynamic storage provisioning or PVs. Block-based storage is recommended for optimal performance. 

include::con_network-connectivity-in-restricted-environments.adoc[leveloffset=+1]

include::proc_building-offline-versions-of-the-plug-in-and-devfile-registries.adoc[leveloffset=+1]

include::proc_pulling-images-used-by-che-to-a-private-registry.adoc[leveloffset=+1]

include::proc_configuring-che-to-run-in-a-restricted-environment.adoc[leveloffset=+1]

:context: {parent-context-of-installing-che-in-restricted-environment}
