[id="configuring-namespace-strategies_{context}"]
= Configuring namespace strategies

NOTE: The term _namespace_ (Kubernetes) is used interchangeably with _project_ (OpenShift).

=== One Namespace per User strategy

The strategy isolates each user in their own namespace.

To use the strategy, set the `CHE_INFRA_KUBERNETES_NAMESPACE` variable on Kubernetes or the `CHE_INFRA_OPENSHIFT_PROJECT` variable on OpenShift. The value must contain one or more user identifiers. Currently supported identifiers are `_<username>_` and `_<userid>_`.

.Example
To assign namespace names composed of a `che-ws` prefix and individual usernames (`che-ws-user1`, `che-ws-user2`), set:

[subs="+quotes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE=che-ws-__<username>__
----

[IMPORTANT]
====
Using the _One Namespace per User_ strategy with the `common` PVC strategy only works correctly when the user runs not more than one workspace at a time. To enforce this limit, set:

----
CHE_LIMITS_USER_WORKSPACES_RUN_COUNT=1
----
====
