// Module included in the following assemblies:
//
// installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates

[id="deploying-{prod-id-short}-with-self-signed-tls-certificates-on-openshift-3_{context}"]
= Deploying {prod-short} with self-signed TLS certificates on OpenShift 3

This section describes how to deploy {prod-short} with self-signed TLS certificates generated by the user on the OpenShift 3 platform.

NOTE: This method involves reconfiguration of OpenShift router to use user-provided TLS certificates.


.Prerequisites

* A running OpenShift 3 instance, version 3.11 or higher.
* All required keys and certificates. See xref:generating-self-signed-tls-certificates_{context}[].


.Procedure

. Log in to the default OpenShift project:
+
----
$ oc login -u system:admin --insecure-skip-tls-verify=true
$ oc project default
----

. Reconfigure the router with the generated certificate:
+
[subs="+quotes,+attributes"]
----
$ oc delete secret router-certs
$ cat domain.crt domain.key > openshift.crt
$ oc create secret tls router-certs --key=domain.key --cert=openshift.crt
$ oc rollout latest router
----

. Create a {orch-namespace} for {prod-short}:
+
[subs="+quotes,+attributes"]
----
$ oc create namespace {prod-namespace}
----

. Create a secret from the CA certificate:
+
[subs="+quotes,+attributes"]
----
$ oc create secret generic self-signed-certificate --from-file=ca.crt -n={prod-namespace}
----

. Deploy {prod-short} using `{prod-cli}`. {prod} is installed with TLS mode by default:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start --platform=openshift --installer=operator
----
ifeval::["{project-context}" == "che"]
+
When using Minishift, substitute `openshift` in the above command with `minishift`.
endif::[]


.Additional resources

* xref:importing-self-signed-tls-certificates-to-browsers_{context}[]
