---
title: Configuring namespace strategies
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/configuring-namespace-strategies/
folder: che-7/installation-guide
summary:
---

[id="configuring-namespace-strategies_{context}"]
= Configuring namespace strategies

NOTE: The term _namespace_ (Kubernetes) is used interchangeably with _project_ (OpenShift).

The namespace strategies are configured using the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` environment variable.

WARNING: `CHE_INFRA_KUBERNETES_NAMESPACE` and `CHE_INFRA_OPENSHIFT_PROJECT` are legacy variables. Keep these variables unset for a new installations. Changing these variables during an update can lead to data loss.

== One namespace per workspace strategy

The strategy creates a new namespace for each new workspace.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must contain the `_<workspaceID>_` identifier. It can be used alone or combined with other identifiers or any string.

.One namespace per workspace
====
To assign namespace names composed of a `che-ws` prefix and workspace id, set:

[subs="+quotes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=che-ws-__<workspaceID>__
----
====

== One namespace for all workspaces strategy

The strategy uses one predefined namespace for all workspaces.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must be the name of the desired namespace to use.

.One namespace for all workspaces
====
To have all workspaces created in `che-workspaces` namespace, set:

[subs="+quotes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=che-workspaces
----
====

IMPORTANT: To run more than one workspace at a time when using this strategy together with the `common` PVC strategy, configure persistent volumes to use `ReadWriteMany` access mode.

== One namespace per user strategy

The strategy isolates each user in their own namespace.

To use the strategy, the `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT` variable value must contain one or more user identifiers. Currently supported identifiers are `_<username>_` and `_<userId>_`.

.One namespace per user
====
To assign namespace names composed of a `che-ws` prefix and individual usernames (`che-ws-user1`, `che-ws-user2`), set:

[subs="+quotes"]
----
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT=che-ws-__<username>__
----
====

[IMPORTANT]
====
To run more than one workspace at a time when using this strategy together with the `common` PVC strategy, configure persistent volumes to use `ReadWriteMany` access mode.

To limit the number of concurrently running workspaces per user to one, set the `CHE_LIMITS_USER_WORKSPACES_RUN_COUNT` environment variable to `1`.

// Links to Helm and Operator docs need to be added below:

To limit the number of concurrently running workspaces per user to one (1):

* For Helm Chart deployments: set the `.global.workspace.number` parameter to `1`.
* For Operator deployments: set the `spec.server.cheCustomProperties.CHE_LIMITS_USER_WORKSPACE_RUN_COUNT` variable of the CheCluster Custom Resource (CR) to `1`.
====

== Allowing user-defined workspace namespaces

{prod-short} server can be configured to honor the user selection of a namespace when a workspace is created. This feature is disabled by default. To allow user-defined workspace namespaces:

ifeval::["{project-context}" == "che"]
* For Helm Chart deployments, set the following environment variable in the Che config map:
+
----
CHE_INFRA_KUBERNETES_NAMESPACE_ALLOW__USER__DEFINED=true
----
endif::[]

* For Operator deployments, set the following field in the CheCluster Custom Resource:
+
----
allowUserDefinedWorkspaceNamespaces
----

