// Module included in the following assemblies:
//
// installing-{prod-id-short}-in-tls-mode-with-self-signed-certificates

[id="deploying-{prod-id-short}-with-self-signed-tls-certificates-on-openshift-4_{context}"]
= Deploying {prod-short} with self-signed TLS certificates on OpenShift 4

This section describes how to deploy {prod-short} with self-signed TLS certificates on a local OpenShift 4 cluster.

{prod-short} uses a default router certificate to secure its endpoints. Therefore, it depends on the OpenShift cluster configuration whether a self-signed certificate is used or not. {prod-short} automatically detects if the OpenShift default router uses a self-signed certificate by analyzing its certificate chain.


.Prerequisites

* A running OpenShift 4 instance, version 4.2 or higher.
* All required keys and certificates. See xref:generating-self-signed-tls-certificates_{context}[].


.Procedure

. Log in to the default OpenShift project:
+
[subs="+quotes"]
----
$ oc login -u _<username> -p _<password>_
----

. Get the OpenShift 4 self-signed certificate:
+
[subs="+quotes"]
----
$ oc get secret router-ca -n openshift-ingress-operator -o jsonpath="{.data.tls\.crt}" | \
  base64 -d > ca.crt
----

. Pre-create a namespace for {prod-short}:
+
[subs="+quotes"]
----
$ oc create namespace {prod-namespace}
----

. Create a secret from the CA certificate:
+
[subs="+quotes"]
----
$ oc create secret generic self-signed-certificate --from-file=ca.crt -n={prod-namespace}
----

. Deploy {prod-short} using `{prod-cli}`:
+
[subs="+quotes,+attributes"]
----
$ {prod-cli} server:start --platform=openshift --installer=operator
----
+
When using CodeReady Containers, substitute `openshift` in the above command with `crc`.


.Additional resources

* xref:importing-self-signed-tls-certificates-to-browsers_{context}[]
