---
title: Mounting custom SSL certificates to Che workspace Pods
keywords:
tags: []
sidebar: che_7_docs
permalink: che-7/mounting-custom-ssl-certificates-to-che-workspace-pods/
redirect_from:
  - che-7/adding-self-signed-SSL-certificates-to-che
folder: che-7/installation-guide
summary:
---
:page-liquid:

[id="mounting-custom-ssl-certificates-to-{prod-id-short}-workspace-pods_{context}"]
= Mounting custom SSL certificates to {prod-short} workspace Pods

When a {prod-short} user attempts to authenticate with {identity-provider} that is using OpenShift OAuth, the authentication fails if the {identity-provider} does not know the certificates needed for authorization.

To fix this problem, configure {prod-short} to authorize HTTPS communication with various components, such as identity and Git servers, by adding information about the self-signed SSL certificates to the {prod-short} configuration.

.Prerequisites

* The OpenShift command-line tool, `oc`
ifeval::["{project-context}" == "che"]
or the Kubernetes command-line tool, `kubectl`,
endif::[]
is installed.

.Procedure

. Save the desired self-signed certificates to a local file system.

. Create a new configMap with the required self-signed SSL certificates:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} create configmap __<configMap-name>__ --from-file=__<certificate-file-path>__ -n=__<{project-context}-namespace-name>__
----
+
To apply more than one certificate, add another `--from-file=_<certificate-file-path>_` option to the above command.

. Define a name for the newly created configMap.
+
NOTE: Use these steps with existing instances of {prod-short}. To install a new instance of {prod-short} with self-signed SSL certificates, create a new Che Custom Resource or Helm Chart property, based on the installation method selected, instead of updating the existing configuration.
+
====
** For a {prod-short} link:https://docs.openshift.com/container-platform/latest/operators/olm-what-operators-are.html[Operators] deployment:

* Define a name for the newly created configMap by editing the `spec.server.ServerTrustStoreConfigMapName` Che Custom Resource property to match the previously created configMap:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} patch checluster {prod-checluster} -n che --type=json -p '[{"op": "replace", "path": "/spec/server/serverTrustStoreConfigMapName", "value": "__<config-map-name>__"}]'
----
====
+
ifeval::["{project-context}" == "che"]
====
** For a {prod-short} link:https://helm.sh/[Helm Chart] deployment: 
+
. Clone the https://github.com/eclipse/che[che] project.
. Go to the `deploy/kubernetes/helm/che` directory.
. Define a name for the newly created configMap by editing the `global.tls.serverTrustStoreConfigMapName` Helm Chart property to match the previously created configMap:
+
[subs="+quotes",options="nowrap",role=white-space-pre]
----
$ helm upgrade che -n che --set global.tls.serverTrustStoreConfigMapName=__<config-map name>__ \
   --set global.ingressDomain=__<kubernetes-cluster-domain>__ .
----
+
When using Minikube to run {prod-short}, substitute _<kubernetes-cluster-domain>_ with `$(minikube ip).nip.io`.
====
endif::[]

.Verification 

If the certificates have been added correctly, the {prod-short} server starts and obtains {identity-provider} configuration over HTTPS with a self-signed SSL certificate, allowing user to:

* Access the {prod-short} server.
* Log in using OpenShift OAuth.
* Clone from a Git repository that has a custom self-signed SSL certificate over HTTPS.
