// Module included in the following assemblies:
//
// uninstalling-{prod-id-short}

[id="uninstalling-{prod-id-short}-after-operatorhub-installation-using-openshift-cli_{context}"]
= Uninstalling {prod-short} after OperatorHub installation using OpenShift CLI

This section provides instructions on how to uninstall a {prod-short} instance using `oc` commands.

.Prerequisites

* {prod-short} was installed on an OpenShift cluster using OperatorHub.
* The `oc` tool is available.

.Procedure

The following procedure provides command-line outputs as examples. Note that output in the user terminal may differ.

To uninstall a {prod-short} instance from a cluster:

. Sign in to the cluster:
+
[subs="+quotes"]
----
$ oc login -u _<username>_ -p _<password>_ _<cluster_URL>_
----

. Switch to the project where the {prod-short} instance is deployed:
+
[subs="+quotes,attributes"]
----
$ oc project _<{prod-id-short}_project>_
----

. Obtain the {prod-short} cluster name. The following shows a cluster named `{prod-id}`:
+
[subs="+quotes,attributes"]
----
$ oc get checluster
NAME          AGE
{prod-id}   27m
----

. Delete the {prod-short} cluster:
+
[subs="+quotes,attributes"]
----
$ oc delete checluster {prod-id}
checluster.org.eclipse.che "{prod-id}" deleted
----

. Obtain the name of the {prod-short} cluster service version (CSV) module. The following detects a CSV module named `{prod-id}.v{prod-ver}`:
+
[subs="+quotes,attributes"]
----
$ oc get csv
NAME                 DISPLAY       VERSION   REPLACES             PHASE
{prod-id}.v{prod-ver}   {prod}   {prod-ver}     {prod-id}.v{prod-prev-ver}   Succeeded
----

. Delete the {prod-short} CSV:
+
[subs="+quotes,attributes"]
----
$ oc delete csv {prod-id}.v{prod-ver}
clusterserviceversion.operators.coreos.com "{prod-id}.v{prod-ver}" deleted
----
