// Module included in the following assemblies:
//
// uninstalling-{prod-id-short}

[id="uninstalling-{prod-id-short}-after-operatorhub-installation-using-openshift-web-console_{context}"]
= Uninstalling {prod-short} after OperatorHub installation using the OpenShift web console

This section describes how to uninstall {prod-short} from a cluster using the OpenShift Administrator Perspective main menu.

.Prerequisites

* {prod-short} was installed on an OpenShift cluster using OperatorHub.

.Procedure

. Navigate to the OpenShift web console and select the Administrator Perspective.

. In the *Home > Projects* section, navigate to the project containing the {prod-short} instance.
+
[TIP]
====
The default project name is __<{prod-namespace}>__.
====

. In the *Operators > Installed Operators* section, click *{prod}* in the list of installed operators.

. In the *{prod} Cluster* tab, click the displayed {prod} Cluster, and select the *Delete cluster* option in the *Actions* drop-down menu on the top right.
+
[TIP]
====
The default {prod} Cluster name is __<{prod-id}>__.
====

. In the *Operators > Installed Operators* section, click *{prod}* in the list of installed operators and select the *Uninstall Operator* option in the *Actions* drop-down menu on the top right.

. In the *Home > Projects* section, navigate to the project containing the {prod-short} instance, and select the *Delete Project* option in the *Actions* drop-down menu on the top right.

