[id="proc_viewing-dev-workspace-operator-metrics-on-grafana-dashboards"]
= View {devworkspace} Operator metrics from an {orch-name} console dashboard

View {devworkspace} Operator metrics on a custom dashboard in the *Administrator* perspective of the {orch-name} web console. This dashboard helps you monitor Operator health and detect workspace provisioning issues.

.Prerequisites

* {prod-short} is installed and running on a Red Hat OpenShift cluster.

* An active `oc` session with administrative permissions to the destination OpenShift cluster. See link:https://docs.openshift.com/container-platform/{ocp4-ver}/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the CLI].

* The in-cluster Prometheus instance is collecting metrics. See xref:collecting-dev-workspace-operator-metrics-with-prometheus[].

.Procedure

* Create a ConfigMap for the dashboard definition in the `openshift-config-managed` {orch-namespace} and apply the necessary label.
.. {empty}
+
[source,subs="+quotes"]
----
$ oc create configmap grafana-dashboard-dwo \
  --from-literal=dwo-dashboard.json="$(curl https://raw.githubusercontent.com/devfile/devworkspace-operator/main/docs/grafana/openshift-console-dashboard.json)" \
  -n openshift-config-managed
----
+
include::example$snip_{project-context}-disclaimer-for-configuring-observability.adoc[]
.. {empty}
+
[source,subs="+quotes"]
----
$ oc label configmap grafana-dashboard-dwo console.openshift.io/dashboard=true -n openshift-config-managed
----
+
[NOTE]
====
The dashboard definition is based on Grafana 6.x dashboards. Not all Grafana 6.x dashboard features are supported in the OpenShift web console.
====

.Verification

. In the *Administrator* view of the OpenShift web console, go to *Observe* -> *Dashboards*.

. Go to *Dashboard* -> *Dev Workspace Operator* and verify that the dashboard panels contain data.
