// configuring-server-logging

[id="configuring-log-levels"]
= Configure log levels

[role="_abstract"]
Configure the log levels of individual loggers in the {prod-short} server with the `CHE_LOGGER_CONFIG` environment variable to control log verbosity and simplify troubleshooting.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Configure the `CheCluster` Custom Resource. See xref:administration-guide:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml,subs="+attributes,+quotes"]
----
spec:
  components:
    cheServer:
      extraProperties:
        CHE_LOGGER_CONFIG: "__<key1=value1,key2=value2>__" <1>
----
<1> Comma-separated list of key-value pairs, where keys are the names of the loggers as seen
in the {prod-short} server log output and values are the required log levels.
+
.Configuring debug mode for the `WorkspaceManager`
====
[source,yaml]
----
spec:
  components:
    cheServer:
      extraProperties:
        CHE_LOGGER_CONFIG: "org.eclipse.che.api.workspace.server.WorkspaceManager=DEBUG"
----
====

.Additional resources

* xref:install:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:administration-guide:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]

