

:parent-context-of-che-quick-starts: {context}

[id="{prod-id-short}-quick-starts_{context}"]
= {prod-short} quick-starts

:context: {prod-id-short}-quick-starts

This section contains instructions for getting quickly started with {prod}. Various installation methods are covered in this documentation.

{prod-short} is available in two modes:

* *Single-user*: Non-authenticated {prod-short}, lighter and suited for personal environments
* *Multi-user*: Authenticated {prod-short} suited for organizations and developer teams


.Prerequisites

* A Kubernetes (version 1.9 or higher) or OpenShift (version 3.11 or higher) cluster to deploy {prod-short} on.


== Deploying {prod-short} on a local single-node cluster

WARNING: Single-node clusters are suited only for testing or single-user development. Do *not* use such clusters to run {prod-short} for organizations or developer teams.

* xref:installing-che-on-codeready-containers.adoc[]
* xref:installing-che-on-docker-desktop.adoc[]
* xref:installing-che-on-minikube.adoc[]
* xref:installing-che-on-minishift.adoc[]
* xref:installing-che-on-kind.adoc[]


== Deploying {prod-short} on private cloud

* xref:installing-che-on-kubespray.adoc[]
* xref:installing-che-on-openshift-3-using-the-operator.adoc[] using the Operator
* xref:installing-che-on-openshift-4-using-operatorhub.adoc[] using OperatorHub


== Deploying {prod-short} on public cloud

* xref:installing-che-on-aws.adoc[]
* xref:installing-che-on-google-cloud-platform.adoc[]
* xref:installing-che-on-microsoft-azure.adoc[]
* xref:accessing-che-from-openshift-developer-perspective.adoc[]

.Additional resources

For the list of {prod} supported platforms and their supported installation methods, see xref:installation-guide:supported-platforms.adoc[].

:context: {parent-context-of-che-quick-starts}
