// Module included in the following assemblies:
//
// accessing-{prod-id-short}-from-openshift-developer-perspective

[id="openshift-developer-perspective-integration-with-che_{context}"]
= OpenShift Developer Perspective integration with {prod-short}

This section provides information about OpenShift Developer Perspective support for {prod-short}.

When the {prod-short} Operator is deployed into OpenShift Container Platform 4.2 and later, it creates a `ConsoleLink` Custom Resource (CR). This adds an interactive link to the *Red Hat Applications* menu for accessing the {prod-short} installation using the OpenShift Developer Perspective console.

To access the *Red Hat Applications* menu, click the three-by-three square icon (░) on the main screen of the OpenShift web console. The {prod-short} *Console Link*, displayed in the drop-down menu, creates a new workspace or redirects the user to an existing one.

[NOTE]
====
.{ocp} console links are not created when {prod-short} is used with HTTP resources

When installing {prod-short} with the *From Git* option, the OpenShift Developer Perspective console link is only created if {prod-short} is deployed with HTTPS. The console link will not be created if an HTTP resource is used.
====
