:_content-type: PROCEDURE
:description: Applying the GitLab-authorized application Secret
:keywords: applying-the-gitlab-oauth-app-secret, apply-the-gitlab-oauth-app-secret, apply-gitlab-oauth-app-secret, apply-secret, applying-secret, apply-a-secret, applying-a-secret
:navtitle: Applying the GitLab-authorized application Secret
// :page-aliases:

[id="applying-the-gitlab-authorized-application-secret_{context}"]
= Applying the GitLab-authorized application Secret

Creating a secret for GitLab by a {prod-short} administrator

.Prerequisites
* The repository owner has xref:user-guide:setting-up-the-gitlab-authorized-application.adoc[set up the GitLab-authorized application].
* The repository owner has given you the generated (1) GitLab Application ID and (2) GitLab Client Secret.
* `{orch-cli}` is installed in the operating system you are using.
////
{orch-cli}=oc
https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
////

.Procedure

. Encode to Base64 the GitLab Application ID that the repository owner gave you:
+
[source,subs="+quotes,+attributes,+macros"]
----
$ echo -n '__<gitlab_application_id>__' | base64
----

. Encode to Base64 the GitLab Client Secret that the repository owner gave you:
+
[source,subs="+quotes,+attributes,+macros"]
----
$ echo -n '__<gitlab_client_secret>__' | base64
----

. Prepare the secret as follows:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: __<gitlab_server_url>__ <2>
type: Opaque
data:
  id: __<base64_gitlab_application_id>__ <3>
  secret: __<base64_gitlab_client_secret>__ <4>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The GitLab server URL.
<3> The GitLab Application ID that you encoded to Base64 in step 1.
<4> The GitLab Client Secret that you encoded to Base64 in step 2.

. Apply the secret by entering it with `{orch-cli}` on a command line:
+
[source,subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the secret is created.