:_content-type: PROCEDURE
:description: Applying the Bitbucket application link Secret
:keywords: applying-bitbucket, apply-the-bitbucket, apply-bitbucket, apply-secret, applying-secret, apply-a-secret, applying-a-secret, bitbucket, bitbucket-application, bitbucket-app, bitbucket-application-link, bitbucket-app-link, bitbucket-secret, secret
:navtitle: Applying the Bitbucket application link Secret
// :page-aliases:

[id="applying-the-bitbucket-application-link-secret_{context}"]
= Applying the Bitbucket application link Secret

Creating a secret for Bitbucket by a {prod-short} administrator


.Prerequisites
* The repository owner has xref:user-guide:setting-up-the-bitbucket-application-link.adoc[set up the Bitbucket application link].
* The repository owner has given you the (1) *privatepkcs8-stripped.pem* file and (2) *bitbucket_consumer_key* file.
* `{orch-cli}` is installed in the operating system you are using.
////
{orch-cli}=oc
https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
////

.Procedure

. Prepare the secret as follows:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: __<bitbucket_server_url>__ <2>
type: Opaque
data:
  private.key: __<base64_content_of_privatepkcs8-stripped.pem>__ <3>
  consumer.key: __<base64_content_of_bitbucket_server_consumer_key>__ <4>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The Bitbucket server URL.
<3> Base64-encoded content of the `privatepkcs8-stripped.pem` file.
<4> Base64-encoded content of the `bitbucket_consumer_key` file.

. Apply the secret by entering it with `{orch-cli}` on a command line:
+
[source,subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the secret is created.