:_content-type: PROCEDURE
:description: Applying the Bitbucket application link Secret
:keywords: applying-bitbucket, apply-the-bitbucket, apply-bitbucket, apply-secret, applying-secret, apply-a-secret, applying-a-secret, bitbucket, bitbucket-application, bitbucket-app, bitbucket-application-link, bitbucket-app-link, bitbucket-secret, secret
:navtitle: Applying the Bitbucket application link Secret
// :page-aliases:

[id="applying-the-bitbucket-application-link-secret_{context}"]
= Applying the Bitbucket application link Secret

Creating a secret for Bitbucket by a {prod-short} administrator


.Prerequisites
* The repository owner has xref:...[set up the Bitbucket application link].
* The repository owner has given you the generated (1) ... and (2) ....
* {orch-cli} is installed in the operating system you are using.
////
{orch-cli}=oc
https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
////

.Procedure

REWRITE ALL THE STEPS

The administrator can apply the secret by using `{orch-cli}` on a command line:

[source, bash]
----
{orch-cli} apply -f - <<EOF
kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-oauth-config
  namespace: __<...>__ <1>
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: __<...>__ <2>
type: Opaque
data:
  private.key: __<...>__ <3>
  consumer.key: __<...>__ <4>
EOF
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The Bitbucket server URL.
<3> Base64-encoded content of the `privatepkcs8-stripped.pem` file.
<4> Base64-encoded content of the `bitbucket_server_consumer_key` file.

================================================================================

. Encode to Base64 the ... that the repository owner gave you:
----
echo -n '__<bitbucket_...>__' | base64
----

. Encode to Base64 the ... that the repository owner gave you:
----
echo -n '__<bitbucket_...>__' | base64
----

. Prepare the secret as follows:
----
...
----
<1> The ... that you encoded to Base64 in step 1.
<2> The ... that you encoded to Base64 in step 2.

. Apply the secret by entering it with `{orch-cli}` on a command line:
[source, bash]
----
{orch-cli} apply -f - <<EOF
__<secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the secret is created.

the administrator of the {prod-short} instance for your organization