:_content-type: PROCEDURE
:description: Applying the GitHub OAuth App Secret
:keywords: applying-the-github-oauth-app-secret, apply-the-github-oauth-app-secret, apply-github-oauth-app-secret, apply-secret, applying-secret, apply-a-secret, applying-a-secret
:navtitle: Applying the GitHub OAuth App Secret
// :page-aliases:

[id="applying-the-github-oauth-app-secret_{context}"]
= Applying the GitHub OAuth App Secret

Creating a secret for GitHub by a {prod-short} administrator


.Prerequisites
* The repository owner has xref:setting-up-the-github-oauth-app.adoc[set up the GitHub OAuth App].
* The repository owner has given you the generated (1) GitHub OAuth Client ID and (2) GitHub OAuth Client Secret.
* {orch-cli} is installed in the operating system you are using.
////
{orch-cli}=oc
https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
////

.Procedure

. Encode to Base64 the GitHub OAuth Client ID that the repository owner gave you:
----
echo -n '__<github_oauth_client_id>__' | base64
----

. Encode to Base64 the GitHub OAuth Client Secret that the repository owner gave you:
----
echo -n '__<github_oauth_client_secret>__' | base64
----

. Prepare the secret as follows:
----
kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: {prod-namespace}
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
type: Opaque
data:
  id: __<...>__ <1>
  secret: __<...>__ <2>
----
<1> The GitHub OAuth Client ID that you encoded to Base64 in step 1.
<2> The GitHub OAuth Client Secret that you encoded to Base64 in step 2.

. Apply the secret by entering it with `{orch-cli}` on a command line:
[source, bash]
----
{orch-cli} apply -f - <<EOF
__<secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the secret is created.