[id="backup-and-recovery"]
= Backup and recovery
:navtitle: Backup and recovery
:keywords: administration-guide, backup-and-disaster-recovery, backup-and-restore, backup-and-recovery
:page-aliases: .:backup-and-disaster-recovery, .:backup-and-restore, .:backup-and-recovery

:context: backup-and-recovery

Backing up {prod-short} may involve any of the following methods, depending on the data that has to be backed up:

* Using {prod-short} Operator to back up and restore {prod-short} instances, excluding the content of users' workspaces, and involving a xref:backup-server-setup.adoc[configured backup server]:

** xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc[]

** xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc[]

* Backing up persistent volumes to back up and restore the content of users' workspaces:

** xref:backups-of-persistent-volumes.adoc[]

* Backing up and restoring external PostgreSQL:

** xref:managing-backups-of-external-postgresql.adoc[]



-

//[id="managing-backups-of-prod-short-instances-using-custom-resources"]
//= Managing backups of {prod-short} instances using custom resources
//:navtitle: Managing backups of {prod-short} instances using custom resources
//:keywords: administration-guide, backup, recovery, custom-resource, custom-resources, manage-backups-using-custom-resources, manage-backups-with-custom-resources
//:page-aliases:
//.:managing-backups-through-custom-resources, .:managing-backups-using-custom-resources

COPY ABOVE PROPERTIES TO ANOTHER FILE ^
RELOCATE THE FOLLOWING TEXT:
You can xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#creating-a-backup-of-a-prod-short-instance-using-a-checlusterbackup-object_{context}[create] and xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#restoring-a-prod-short-instance-from-a-backup-using-a-checlusterrestore-object_{context}[restore] backups of {prod-short} instances using custom resources. To manage backups using custom resources, you must have a xref:backup-server-setup.adoc[configured backup server] and {prod-short} xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#configuring-prod-short-to-use-a-backup-server_{context}[configured to use the backup server].
&
Alternatively, you can manage backups of {prod-short} instances xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc[using {prod-cli}].

-

//[id="managing-backups-of-prod-short-instances-using-prod-cli"]
//= Managing backups of {prod-short} instances using {prod-cli}
//:navtitle: Managing backups of {prod-short} instances using {prod-cli}
//:keywords: administration-guide, backup, recovery, manage-backups-using-cli, manage-backups-with-li
//:page-aliases: .:managing-backups-through-cli, .:managing-backups-using-prod-cli

//:context: managing-backups-using-prod-cli

COPY ABOVE PROPERTIES TO ANOTHER FILE ^
RELOCATE THE FOLLOWING TEXT:
You can xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc#creating-a-backup-of-a-prod-short-instance-using-prod-cli_{context}[create] and xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc#restoring-a-prod-short-instance-from-a-backup-using-prod-cli_{context}[restore] backups of {prod-short} instances using {prod-cli}. To manage backups with {prod-cli}, you must have a xref:backup-server-setup.adoc[configured backup server] and {prod-cli} xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc#configuring-prod-cli-to-use-a-backup-server_{context}[configured to use the backup server].
&
Alternatively, you can manage backups of {prod-short} instances xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc[using custom resources].

-

//:parent-context-of-configuring-prod-short-with-custom-resouces-to-use-a-backup-server: {context}

//[id="configuring-prod-short-with-custom-resouces-to-use-a-backup-server_{context}"]
//= Configuring {prod-short} with custom resources to use a backup server

//:context: configuring-prod-short-with-custom-resouces-to-use-a-backup-server

You can configure {prod-short} to use backup servers of any of the following types:

// * xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#configuring-prod-short-with-custom-resources-to-use-a-rest-backup-server_{context}[REST]
// * xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#configuring-prod-short-with-custom-resources-to-use-an-amazon-s3-backup-server_{context}[Amazon S3]
// * xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#configuring-prod-short-to-use_{context}[SFTP]

//include::partial$proc_configuring-prod-short-with-custom-resources-to-use-a-rest-backup-server.adoc[leveloffset=+1]
//include::partial$proc_configuring-prod-short-with-custom-resources-to-use-an-amazon-s3-backup-server.adoc[leveloffset=+1]
//include::partial$proc_configuring-prod-short-with-custom-resources-to-use-an-sftp-backup-server.adoc[leveloffset=+1]

//:context: {parent-context-of-configuring-prod-short-with-custom-resouces-to-use-a-backup-server}

-