:_content-type: PROCEDURE
:description: Concealing editors definitions
:keywords: administration guide, concealing, dashboard, editors
:navtitle: Concealing editors definitions

[id="concealing-editors-definitions"]
= Concealing editors definitions

Learn how to conceal {prod-short} editor definitions. This is useful when you want to hide selected editors from the Dashboard UI, e.g. hide the IntelliJ IDEA Ultimate and have only Visual Studio Code - Open Source visible.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the {orch-name} cluster. See {orch-cli-link}.

* `jq`. See link:https://stedolan.github.io/jq/download/[Downloading `jq`].

.Procedure

include::example$snip_che-editor-id-list.adoc[]

. Configure the `CheCluster` Custom Resource. See xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml]
----
spec:
  components:
    dashboard:
      deployment:
        containers:
        - env:
          - name: CHE_HIDE_EDITORS_BY_ID
            value: 'che-incubator/che-webstorm-server/latest, che-incubator/che-webstorm-server/next'    <1>
----
<1> A string containing comma-separated IDs of editors to hide.

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]

* {editor-definition-samples-link}

