:_content-type: PROCEDURE
:description: Configuring network policies
:keywords: administration guide, configuring, namespace, network policy, network policies, multitenant isolation
:navtitle: Configuring network policies
:page-aliases: installation-guide:configuring-network-policies.adoc

[id="configuring-networking-policies"]
= Configuring network policies

By default, all Pods in a {orch-name} cluster can communicate with each other even if they are in different namespaces.
In the context of {prod-short}, this makes it possible for a workspace Pod in one user {orch-namespace} to send traffic to another workspace Pod in a different user {orch-namespace}.

For security, multitenant isolation could be configured by using NetworkPolicy objects to restrict all incoming communication to Pods in a user {orch-namespace}.
However, Pods in the {prod-short} {orch-namespace} must be able to communicate with Pods in user {orch-namespace}s.

[id="operator-managed-network-policies"]
== Operator-managed network policies

On OpenShift clusters, {prod-short} can automatically create and manage NetworkPolicy resources for the {prod-short} {orch-namespace} and user workspace {orch-namespace}s. This feature is disabled by default.

When enabled, the operator creates the following fine-grained NetworkPolicy resources:

.NetworkPolicy resources in the {prod-short} {orch-namespace}
[cols="1,2",options="header"]
|===
|Policy name |Description

|`allow-from-same-namespace`
|Allows ingress traffic between {prod-short} pods in the same {orch-namespace}.

|`allow-from-workspaces`
|Allows ingress traffic from user workspace {orch-namespace}s.

|`allow-from-openshift-ingress`
|Allows ingress traffic from the OpenShift ingress {orch-namespace}.

|`allow-from-openshift-monitoring`
|Allows ingress traffic from the OpenShift monitoring {orch-namespace}.

|`allow-from-{prod-id-short}-operator`
|Allows ingress traffic from the operator pod to {prod-short} components.

|`allow-all-egress`
|Allows all egress traffic from {prod-short} pods.
|===

.NetworkPolicy resources in each user workspace {orch-namespace}
[cols="1,2",options="header"]
|===
|Policy name |Description

|`allow-from-{prod-namespace}`
|Allows ingress traffic from the {prod-short} {orch-namespace}.

|`allow-from-same-namespace`
|Allows ingress traffic between pods in the same {orch-namespace}.

|`allow-from-devworkspace-operator`
|Allows ingress traffic from the {devworkspace} operator.

|`allow-from-openshift-monitoring`
|Allows ingress traffic from the OpenShift monitoring {orch-namespace}.

|`allow-from-openshift-ingress`
|Allows ingress traffic from the OpenShift ingress {orch-namespace}.

|`allow-all-egress`
|Allows all egress traffic from workspace pods.
|===

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination OpenShift cluster. See {orch-cli-link}.

* An instance of {prod-short} running in OpenShift.

.Procedure

. Enable operator-managed network policies:
+
[source,subs="+quotes,attributes"]
----
{orch-cli} patch checluster/{prod-checluster} -n {prod-namespace} \
  --type='merge' -p \
  '{"spec":{"networking":{"networkPolicy":{"enabled":true}}}}'
----

.Verification

. Verify NetworkPolicy resources are created in the {prod-short} {orch-namespace}:
+
[source,subs="+quotes,attributes"]
----
{orch-cli} get networkpolicies -n {prod-namespace}
----

. Start a workspace and verify NetworkPolicy resources are created in the user {orch-namespace}:
+
[source,subs="+quotes,attributes"]
----
{orch-cli} get networkpolicies -n __<user_namespace>__
----

To disable operator-managed network policies and remove all managed NetworkPolicy resources:

[source,subs="+quotes,attributes"]
----
{orch-cli} patch checluster/{prod-checluster} -n {prod-namespace} \
  --type='merge' -p \
  '{"spec":{"networking":{"networkPolicy":{"enabled":false}}}}'
----

[id="manually-configuring-network-policies"]
== Manually configuring network policies

If you do not use operator-managed network policies, you can manually create NetworkPolicy objects to restrict incoming communication to Pods in a user {orch-namespace}.

.Prerequisites
* The {orch-name} cluster has network restrictions such as multitenant isolation.

.Procedure
* Apply the `allow-from-{prod-namespace}` NetworkPolicy to each user {orch-namespace}.
The `allow-from-{prod-namespace}` NetworkPolicy allows incoming traffic from the {prod-short} namespace to all Pods in the user {orch-namespace}.
+
.`allow-from-{prod-namespace}.yaml`
====
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: allow-from-{prod-namespace}
spec:
    ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                kubernetes.io/metadata.name: {prod-namespace}   <1>
    podSelector: {}   <2>
    policyTypes:
    - Ingress
----
<1> The {prod-short} namespace.
The default is `{prod-namespace}`.
<2> The empty `podSelector` selects all Pods in the {orch-namespace}.
====
+
* OPTIONAL: In case you applied link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp4-ver}/html/network_security/network-policy#multitenant-network-policy[Configuring multitenant isolation with network policy], you also must apply `allow-from-openshift-apiserver` and `allow-from-workspaces-namespaces` NetworkPolicies to `{prod-namespace}`.
The `allow-from-openshift-apiserver` NetworkPolicy allows incoming traffic from `openshift-apiserver` namespace to the `devworkspace-webhook-server` enabling webhooks.
The `allow-from-workspaces-namespaces` NetworkPolicy allows incoming traffic from each user project to `che-gateway` pod.
+
.`allow-from-openshift-apiserver.yaml`
====
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-apiserver
  namespace: {prod-namespace}   <1>
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: devworkspace-webhook-server   <2>
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-apiserver
  policyTypes:
    - Ingress
----
<1> The {prod-short} namespace.
The default is `{prod-namespace}`.
<2> The `podSelector` only selects devworkspace-webhook-server pods
====
+
.`allow-from-workspaces-namespaces.yaml`
====
[source,yaml,subs="+quotes,attributes"]
----
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-workspaces-namespaces
  namespace: {prod-namespace}   <1>
spec:
  podSelector: {}   <2>
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              app.kubernetes.io/component: workspaces-namespace
  policyTypes:
    - Ingress
----
<1> The {prod-short} namespace.
The default is `{prod-namespace}`.
<2> The empty `podSelector` selects all pods in the {prod-short} namespace.
====
+

.Additional resources
* xref:configuring-namespace-provisioning.adoc[]

* link:https://kubernetes.io/docs/concepts/security/multi-tenancy/#network-isolation[Network isolation]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp4-ver}/html/network_security/network-policy#multitenant-network-policy[Configuring multitenant isolation with network policy]
