:_content-type: CONCEPT
:navtitle: Configuring workspace target {orch-namespace}
:keywords: administration guide, configuring, namespace
:page-aliases: installation-guide:configuring-namespace-strategies, configuring-namespace-strategies

[id="configuring-workspace-target-namespace_{context}"]
= Configuring workspace target {orch-namespace}

For each user, {prod-short} isolates the workspaces in a {orch-namespace}.
You can configure the {orch-namespace} name template.

{prod-short} server checks usernames and IDs for compatibility with {orch-name} objects naming convention before creating a {orch-namespace} from a template:

* The `<username>` or `<userid>` placeholder is mandatory.
* Incompatible usernames or IDs are reduced to the nearest valid name by replacing groups of unsuitable symbols with the `-` symbol. 
* The `<userid>` placeholder is evaluated into a 14 character long string.
* When using `<userid>`, the addition of a random 6-symbol suffix prevents IDs from collisions. The result is stored in preferences for reuse.
* {kubernetes} limits the length of a {orch-namespace} name to 63 characters (this includes the evaluated placeholders). Additionally, the names (after placeholder evaluation) must be valid DNS names.
* OpenShift limits the length further to 49 characters.

.User workspaces {orch-namespace} name template examples
====
[%header,cols="1,1"]  
|=== 
|User workspaces {orch-namespace} name template
|Resulting {orch-namespace} example

|`<username>-{prod-id-short}` (default)
|user1-{prod-id-short}

|`<userid>-namespace` 
|`cge1egvsb2nhba-namespace-ul1411` 

|`<userid>-aka-<username>-namespace`
|`cgezegvsb2nhba-aka-user1-namespace-6m2w2b`
|=== 
====


.Procedure

* Set the `server.workspaceNamespaceDefault` property in CheCluster Custom Resource:
+
[source,yaml,subs="+quotes,+attributes"]
----
kind: CheCluster
apiVersion: org.eclipse.che/v1
# ...
spec:
  server:
    workspaceNamespaceDefault: __<workspaceNamespaceDefault_value>__
# ...
----

.Additional resources

* xref:understanding-the-checluster-custom-resource.adoc[]

