:_content-type: PROCEDURE
:description: Configuring OpenShift Route
:keywords: administration guide, configuring, routes
:navtitle: Configuring OpenShift Route
:page-aliases: installation-guide:configuring-routes.adoc

[id="configuring-routes_{context}"]
= Configuring OpenShift Route to work with Router Sharding

You can configure labels, annotations, and domains for OpenShift Route to work with link:https://docs.openshift.com/container-platform/4.7/networking/ingress-operator.html#nw-ingress-sharding_configuring-ingress[Router Sharding].

.Prerequisites

* An active `oc` session with administrative permissions to the OpenShift cluster. See link:https://docs.openshift.com/container-platform/{ocp4-ver}/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the OpenShift CLI].

* `{prod-cli}`. See: xref:installing-the-chectl-management-tool.adoc[].

.Procedure

* Configure the `CheCluster` Custom Resource. See xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml,subs="+quotes"]
----
spec:
  components:
    cheServer:
      extraProperties:
        CHE_INFRA_OPENSHIFT_ROUTE_LABELS: <labels> <1>
        CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX: <domain> <2>
    networking:
      labels: __<labels>__ <1>
      domain: __<domain>__ <2>
      annotations: __<annotations>__ <3>
----
<1> A comma-separated list of labels that the target ingress controller uses to filter the set of Routes to service.
<2> The DNS name serviced by the target ingress controller.
<3> An unstructured key value map stored with a resource.```


.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]
