:_content-type: PROCEDURE
:navtitle: Configuring {orch-ingress}
:description: Configuring labels and annotations on each {orch-ingress}
:keywords: administration guide, configuring, ingress, ingresses
:page-aliases: installation-guide:configuring-ingresses

[id="adding-labels-and-annotations-to-ingresses_{context}"]
= Adding labels and annotations to {orch-ingress}

You can configure {orch-ingress} labels and annotations, if your organization requires them.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* An instance of {prod-short} running in {orch-name}.

.Procedure

* Configure the `CheCluster` Custom Resource. See xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml,subs="+quotes,+attributes"]
----
spec:
  server:
    cheServerIngress:
      labels: __<labels>__ <1>
      annotations: __<annotations>__ <2>
    customCheProperties:
      CHE_INFRA_KUBERNETES_INGRESS_LABELS: __<labels>__ <1>
      CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS______JSON: "__<annotations>__" <2>
----
<1> A comma-separated list of labels for {orch-ingress}: `key1=value1,key2=value2`.
<2> Annotations for {orch-ingress} in JSON format: `{"key1": "value1", "key2" : "value2"}`.

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]

