:_content-type: PROCEDURE
:description: Configuring workspaces nodeSelector
:keywords: administration guide, configuring-workspaces-nodeselector
:navtitle: Configuring workspaces nodeSelector
:page-aliases: installation-guide:configuring-workspaces-nodeselector.adoc

[id="configuring-workspaces-nodeselector"]
= Configuring workspaces nodeSelector

This section describes how to configure link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/[`nodeSelector`] for Pods of {prod-short} workspaces.

.Procedure
.. Using NodeSelector
+
{prod-short} uses `CheCluster` Custom Resource to configure `nodeSelector`:
+
[source,yaml]
----
spec:
  devEnvironments:
    nodeSelector:
      key: value
----
This section must contain a set of `key=value` pairs for each link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#built-in-node-labels[node label] to form the link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector[nodeSelector] rule.

.. Using Taints and Tolerations
+
This works in the opposite way to `nodeSelector`. Instead of specifying which nodes the Pod will be scheduled on, you specify which nodes the Pod cannot be scheduled on. For more information, see: link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration[].
+
{prod-short} uses `CheCluster` Custom Resource to configure `tolerations`:
+
[source,yaml]
----
spec:
  devEnvironments:
    tolerations:
      - effect: NoSchedule
        key: key
        value: value
        operator: Equal
----

[IMPORTANT]
====
`nodeSelector` must be configured during {prod-short} installation. This prevents existing workspaces from failing to run due to volumes affinity conflict caused by existing workspace PVC and Pod being scheduled in different zones.

To avoid Pods and PVCs to be scheduled in different zones on large, multizone clusters, create an additional link:https://kubernetes.io/docs/concepts/storage/storage-classes/[`StorageClass`] object (pay attention to the `allowedTopologies` field), which will coordinate the PVC creation process.

Pass the name of this newly created `StorageClass` to {prod-short} through the `+CHE_INFRA_KUBERNETES_PVC_STORAGE__CLASS__NAME+` environment variable. A default empty value of this variable instructs {prod-short} to use the cluster's default `StorageClass`.
====

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]
