:_content-type: ASSEMBLY
:description: Configuring fuse for workspaces
:keywords: administration-guide, configuring-fuse
:navtitle: Configuring fuse-overlayfs
:page-aliases:

[id="configuring-fuse-overlayfs"]
= Configuring fuse-overlayfs

By default, the Universal Developer Image (UDI) contains Podman and Buildah which you can use to build and push container images within a workspace.
However, Podman and Buildah in the UDI are configured to use the `vfs` storage driver which does not provide copy-on-write support.
For more efficient image management, use the fuse-overlayfs storage driver which supports copy-on-write in rootless environments.

To enable fuse-overlayfs for workspaces for OpenShift versions older than 4.15, the administrator must first enable `/dev/fuse` access on the cluster by following xref:administration-guide:enabling-access-to-dev-fuse-for-openshift.adoc[].

This is not necessary for OpenShift versions 4.15 and later, since the `/dev/fuse` device is available by default. See link:https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-nodes-dev-fuse[Release Notes].

After enabling `/dev/fuse` access, fuse-overlayfs can be enabled in two ways:

. For all user workspaces within the cluster. See xref:administration-guide:enabling-fuse-for-all-workspaces.adoc[]. 
. For workspaces belonging to certain users. See xref:end-user-guide:using-the-fuse-overlay-storage-driver.adoc[].
