:_content-type: PROCEDURE
:navtitle: Configuring {prod-short} hostname
:keywords: administration guide, configuring, {prod}, {prod-short}, hostname
:page-aliases: installation-guide:configuring-che-hostname

[id="configuring-{prod-id-short}-server-hostname_{context}"]
= Configuring {prod} server hostname

This procedure describes how to configure {prod-short} to use custom hostname.

.Prerequisites

* The `{orch-cli}` tool is available.
* The certificate and the private key files are generated.

IMPORTANT: To generate the pair of a private key and certificate, the same certification authority (CA) must be used as for other {prod-short} hosts.

IMPORTANT: Ask a DNS provider to point the custom hostname to the cluster ingress.

.Procedure

. Pre-create a {orch-namespace} for {prod-short}:
+
[subs="+quotes,attributes"]
----
$ {orch-cli} create {orch-namespace} {prod-namespace}
----

. Create a TLS secret:
+
[subs="+quotes,attributes"]
----
$ {orch-cli} create secret TLS __<tls-secret-name>__ \ <1>
--key __<key-file>__ \ <2>
--cert __<cert-file>__ \ <3>
-n {prod-namespace}
----
<1> The TLS secret name
<2> A file with the private key
<3> A file with the certificate

. Add the required labels to the secret:
+
[subs="+quotes,attributes"]
----
$ {orch-cli} label secret __<tls-secret-name>__ \ <1>
app.kubernetes.io/part-of=che.eclipse.org -n {prod-namespace}
----
<1> The TLS secret name

. Set the following values in the Custom Resource:
+
[subs="+quotes,+attributes"]
----
spec:
  server:
    cheHost: <hostname>         <1>
    cheHostTLSSecret: <secret>  <2>
----
<1> Custom {prod} server hostname
<2> The TLS secret name

. If {prod-short} has been already deployed, wait until the rollout of all {prod-short} components finishes.
