:_content-type: PROCEDURE
:description: Defining the list of images
:keywords: administration-guide, image-puller, configuration
:navtitle: Defining the list of images
:page-aliases: .:defining-the-list-of-images-to-pull.adoc

[id="defining-the-list-of-images-to-pull"]
= Defining the list of images to pull

The {image-puller-name-short} can pre-pull most images, including scratch images such as `che-machine-exec`. However, images that mount volumes in the Dockerfile, such as `traefik`, are not supported for pre-pulling on OpenShift 3.11.

.Procedure

. Gather a list of relevant container images to pull by navigating to the `pass:c,a,q[{prod-url}]/plugin-registry/v3/external_images.txt` URL.

. Determine images from the list for pre-pulling. For faster workspace startup times, consider pulling workspace related images such as `universal-developer-image`, che-code`, `che-gateway`, and plug-in sidecar images.

.Additional resources
* xref:installing-image-puller-on-openshift-using-the-web-console.adoc[]
* xref:installing-image-puller-on-openshift-using-cli.adoc[]
