:_content-type: PROCEDURE
:navtitle: Enabling users to run multiple workspaces simultaneously
:description: Enabling users to run multiple workspaces simultaneously
:keywords: administration guide, number, workspaces

[id="enabling-users-to-run-multiple-workspaces-simultaneously_{context}"]
= Enabling users to run multiple workspaces simultaneously

By default, a user can run only one workspace at a time. You can enable users to run multiple workspaces simultaneously.

NOTE: If using the default `common` (or `per-user`) storage method, users might experience problems with concurrently running workspaces if pods are distributed across nodes in the cluster. Switching to `per-workspace` storage, or using the `ephemeral` storage type, can help with this. 

This configuration is part of the `CheCluster` Custom Resource:

[source,yaml,subs="+quotes"]
----
spec:
  components:
    devWorkspace:
      runningLimit: "__<running_workspaces_limit>__" <1>
----
<1> Sets the maximum number of simultaneously running workspaces per user. The default value is `1`.

.Procedure

. Get the name of the {prod-short} namespace. The default is `{prod-namespace}`:
+
[source,terminal,subs="+quotes,attributes"]
----
$ {orch-cli} get checluster --all-namespaces \
  -o=jsonpath="{.items[*].metadata.namespace}"
----

. Configure the `runningLimit`:
+
[source,terminal,subs="+quotes,attributes"]
----
$ {orch-cli} patch checluster/{context} -n _<{prod-namespace}>_ \ <1>
--type='merge' -p \
'{"spec":{"components":{"devWorkspace":{"runningLimit": "__<running_workspaces_limit>__"}}}}' <2>
----
<1> The {prod-short} namespace that you got in step 1.
<2> Your choice of the `__<running_workspaces_limit>__` value.

.Addtional resources

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]
