:_content-type: PROCEDURE
:description: Enabling fuse-overlayfs for all workspaces
:keywords: administration-guide, enable, fuse, all, workspaces
:navtitle: Enabling fuse-overlayfs for all workspaces
:page-aliases: 

[id="enabling-fuse-overlayfs-for-all-workspaces"]
= Enabling fuse-overlayfs for all workspaces

Learn how to configure the workspace's container entrypoint script so that you can use fuse-overlayfs for all workspaces using that container.

The Universal Developer Image (UDI) already contains the necessary configuration by default.
However, you must configure the script manually if you use custom images due to Podman 5.x requiring the `/home/user/.config` folder to be owned by the current user.

.Prerequisites

* For OpenShift versions 4.14 and lower, the xref:administration-guide:enabling-access-to-dev-fuse-for-openshift.adoc[] section has been completed.

* An active `{orch-cli}` session with administrative permissions to the destination OpenShift cluster. See {orch-cli-link}.

.Procedure

. Set the necessary annotation in the `spec.devEnvironments.workspacesPodAnnotations` field of the CheCluster custom resource.
+
====
[source,yaml,subs="+quotes,+attributes"]
----
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  devEnvironments:
    workspacesPodAnnotations:
      io.kubernetes.cri-o.Devices: /dev/fuse
----
====
+
[NOTE]
====
For OpenShift versions 4.14 and lower, the `io.openshift.podman-fuse: ""` annotation is also required.
====

. Optional: If you are using a custom image for the workspace container, create the `/home/user/.config` folder and configure the `storage.conf` file on runtime via the entrypoint.
To do this, add the following to the workspace container image's entrypoint script before building the image.
Creating the `/home/user/.config` folder in the entrypoint results in the folder being owned by the current user which is not known at image build time.
+
====
[source,subs="+quotes,+macros"]
----
# Configure container builds to use vfs or fuse-overlayfs
if [ ! -d "${HOME}/.config/containers" ]; then
  mkdir -p ${HOME}/.config/containers
  if [ -c "/dev/fuse" ] && [ -f "/usr/bin/fuse-overlayfs" ]; then
    (echo '[storage]';echo 'driver = "overlay"';echo '[storage.options.overlay]';echo 'mount_program = "/usr/bin/fuse-overlayfs"') > ${HOME}/.config/containers/storage.conf
  else
    (echo '[storage]';echo 'driver = "vfs"') > "${HOME}"/.config/containers/storage.conf
  fi
fi
----
====
+
This ensures that if the `/home/user/.config` doesn't already exist, the folder is created and owned by `user`.
The `/home/user/.config` may already exist for example, if it was stored in a persistent volume.
+

.Verification steps

. Start a workspace and verify that the owner for `/home/user/.config` is `user`.
+
[subs="+attributes,+quotes"]
----
$ ls -la /home/user
----

+
Example output:
+
[subs="+attributes,+quotes"]
----
...
drwxrwsr-x.  3 user 1000660000   24 Dec 24 15:40 .config
----

. Verify that the storage driver is `overlay`.
+
[subs="+attributes,+quotes"]
----
$ podman info | grep overlay
----

+
Example output:
+
[subs="+attributes,+quotes"]
----
graphDriverName: overlay
  overlay.mount_program:
    Executable: /usr/bin/fuse-overlayfs
    Package: fuse-overlayfs-1.14-1.el9.x86_64
      fuse-overlayfs: version 1.13-dev
  Backing Filesystem: overlayfs
----
+
[NOTE]
====
The following error might occur for existing workspaces:

[source]
----
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files ("/home/user/.local/share/containers/storage") to resolve.  May prevent use of images created by other tools 
----

In this case, delete the libpod local files as mentioned in the error message. 
====
