:_content-type: ASSEMBLY
:description: Extensions for Microsoft Visual Studio Code - Open Source
:keywords: extensions, vs-code, vsx, open-vsx, marketplace
:navtitle: Extensions for Microsoft Visual Studio Code - Open Source
//:page-aliases:

[id="extensions-for-microsoft-visual-studio-code-open-source"]
= Extensions for Microsoft Visual Studio Code - Open Source

To manage Visual Studio Code extensions {prod-short} uses link:https://open-vsx.org/[Open VSX Registry], it is an open source VS Code extensions registry.

The default Open VSX registry differs depending on how proxies or DNS is configued. 

If open-vsx.org can be resolved, the default will be to the public link:https://open-vsx.org/[Open VSX Registry]; if not, then the default will be a locally cached Open VSX registry instance within the plugin-registry pod to support airgapped, offline, and proxy-restricted deployments. 

It is also possible to control what instance of Open VSX should be used in the workspaces, should you want to include your own custom build. This configuration is part of the `CheCluster` Custom Resource:

[source,yaml,subs="+quotes"]
----
spec:
  components:
    pluginRegistry:
      openVSXURL: "__<Open_VSX_registry_URL>__" # <1> 
----

<1> Sets the URL of Open VSX registry. The default value is `https://open-vsx.org`. In case if the value is empty, {prod-short} will use a local Open VSX registry.

The local/embedded registry is running in the plugin-registry pod and provides a subset of VS Code extensions that are published on link:https://open-vsx.org/[Open VSX Registry].

.Next topics describe how to manage a local Open VSX registry:

include::partial$proc_importing-extensions-from-the-open-vsx-registry.adoc[leveloffset=+1]

include::partial$proc_importing-extensions-that-are-not-in-the-open-vsx-registry.adoc[leveloffset=+1]

include::partial$proc_removing-extensions-from-the-embedded-open-vsx-registry.adoc[leveloffset=+1]
