:_content-type: PROCEDURE
:description: Hiding editors definitions
:keywords: administration guide, hiding, dashboard, editors
:navtitle: Hiding editors definitions
:page-aliases: installation-guide:hiding-editors-definitions.adoc

[id="hiding-editors-definitions"]
= Hiding editors definitions

Learn how to hide {prod-short} editor definitions by editor ID.

TIP: An editor ID has the following format: `publisher/name/version`.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the {orch-name} cluster. See {orch-cli-link}.

.Procedure

include::example$snip_che-editor-id-list.adoc[]

. Configure the `CheCluster` Custom Resource. See xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml]
----
spec:
  components:
    dashboard:
      deployment:
        containers:
        - env:
          - name: CHE_HIDE_EDITORS_BY_ID
            value: 'che-incubator/che-webstorm-server/latest, che-incubator/che-webstorm-server/next'    <1>
----
<1> A string containing comma-separated IDs of editors to hide.
+
[IMPORTANT]
====
Make sure you specify actual values fof `publisher` and `version` from `metadata.attributes` when constructing editor IDs.
====

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]

* {editor-definition-samples-link}
