:_content-type: CONCEPT
:description: Importing untrusted TLS certificates to {prod-short}
:keywords: administration guide, tls, certificate
:navtitle: Importing untrusted TLS certificates to {prod-short}
:page-aliases: installation-guide:importing-untrusted-tls-certificates.adoc, installation-guide:importing-untrusted-tls-certificates-old.adoc

[id="importing-untrusted-tls-certificates"]
= Importing untrusted TLS certificates to {prod-short}

{prod-short} components communications with external services are encrypted with TLS.
They require TLS certificates signed by trusted Certificate Authorities (CA).
Therefore, you must import into {prod-short} all untrusted CA chains in use by an external service such as:

* A proxy
* An identity provider (OIDC)
* A source code repositories provider (Git)

{prod-short} uses labeled config maps in {prod-short} {orch-namespace} as sources for TLS certificates.
The config maps can have an arbitrary amount of keys with a random amount of certificates each.

[NOTE]
====
When an OpenShift cluster contains cluster-wide trusted CA certificates added through the link:https://docs.openshift.com/container-platform/latest/networking/configuring-a-custom-pki.html#nw-proxy-configure-object_configuring-a-custom-pki[cluster-wide-proxy configuration],
{prod-short} Operator detects them and automatically injects them into a config map with the `config.openshift.io/inject-trusted-cabundle="true"` label.
Based on this annotation, OpenShift automatically injects the cluster-wide trusted CA certificates inside the `ca-bundle.crt` key of the config map.
====

.Prerequisites
* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster.
See {orch-cli-link}.

* The `{prod-namespace}` {orch-namespace} exists.

* For each CA chain to import, the root CA and intermediate certificates, in link:https://wiki.openssl.org/index.php/PEM[PEM] format, in a `ca-cert-for-{prod-id-short}-__<count>__.pem` file.

.Procedure
. Concatenate all CA chains PEM files to import, into the `custom-ca-certificates.pem` file, and remove the return character that is incompatible with the Java trust store.
+
----
$ cat ca-cert-for-{prod-id-short}-*.pem | tr -d '\r' > custom-ca-certificates.pem
----

. Create the `custom-ca-certificates` config map with the required TLS certificates:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} create configmap custom-ca-certificates \
    --from-file=custom-ca-certificates.pem \
    --namespace={prod-namespace}
----

. Label the `custom-ca-certificates` config map:
+
[subs="+attributes,+quotes"]
----
$ {orch-cli} label configmap custom-ca-certificates \
    app.kubernetes.io/component=ca-bundle \
    app.kubernetes.io/part-of=che.eclipse.org \
    --namespace={prod-namespace}
----

. Deploy {prod-short} if it hasn't been deployed before.
Otherwise, wait until the rollout of {prod-short} components finishes.

. Restart running workspaces for the changes to take effect.

.Verification steps
. Verify that the config map contains your custom CA certificates.
This command returns your custom CA certificates in PEM format:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get configmap \
    --namespace={prod-namespace} \
    --output='jsonpath={.items[0:].data.custom-ca-certificates\.pem}' \
    --selector=app.kubernetes.io/component=ca-bundle,app.kubernetes.io/part-of=che.eclipse.org
----

. Verify {prod-short} pod contains a volume mounting the `ca-certs-merged` config map:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get pod \
    --selector=app.kubernetes.io/component={prod-id-short} \
    --output='jsonpath={.items[0].spec.volumes[0:].configMap.name}' \
    --namespace={prod-namespace} \
    | grep ca-certs-merged
----

. Verify the {prod-short} server container has your custom CA certificates.
This command returns your custom CA certificates in PEM format:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} exec -t deploy/{prod-id-short} \
    --namespace={prod-namespace} \
    -- cat /public-certs/custom-ca-certificates.pem
----

. Verify in the {prod-short} server logs that the imported certificates count is not null:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} logs deploy/{prod-id-short} --namespace={prod-namespace} \
    | grep custom-ca-certificates.pem
----

. List the SHA256 fingerprints of your certificates:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ for certificate in ca-cert*.pem ;
  do openssl x509 -in $certificate -digest -sha256 -fingerprint -noout | cut -d= -f2;
  done
----

. Verify  that {prod-short} server Java truststore contains certificates with the same fingerprint:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} exec -t deploy/{prod-id-short} --namespace={prod-namespace} -- \
    keytool -list -keystore {prod-home}/cacerts \
    | grep --after-context=1 custom-ca-certificates.pem
----

. Start a workspace, get the {orch-namespace} name in which it has been created: __<workspace_namespace>__, and wait for the workspace to be started.

. Verify that the `che-trusted-ca-certs` config map contains your custom CA certificates.
This command returns your custom CA certificates in PEM format:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get configmap che-trusted-ca-certs \
    --namespace=__<workspace_namespace>__ \
    --output='jsonpath={.data.custom-ca-certificates\.custom-ca-certificates\.pem}'
----

. Verify that the workspace pod mounts the `che-trusted-ca-certs` config map:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get pod \
    --namespace=__<workspace_namespace>__ \
    --selector='controller.devfile.io/devworkspace_name=__<workspace_name>__' \
    --output='jsonpath={.items[0:].spec.volumes[0:].configMap.name}' \
    | grep che-trusted-ca-certs
----

. Verify that the `universal-developer-image` container (or the container defined in the workspace devfile) mounts the `che-trusted-ca-certs` volume:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get pod \
    --namespace=__<workspace_namespace>__ \
    --selector='controller.devfile.io/devworkspace_name=__<workspace_name>__' \
    --output='jsonpath={.items[0:].spec.containers[0:]}' \
    | jq 'select (.volumeMounts[].name == "che-trusted-ca-certs") | .name'
----

. Get the workspace pod name __<workspace_pod_name>__:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} get pod \
    --namespace=__<workspace_namespace>__ \
    --selector='controller.devfile.io/devworkspace_name=__<workspace_name>__' \
    --output='jsonpath={.items[0:].metadata.name}' \
----

. Verify that the workspace container has your custom CA certificates.
This command returns your custom CA certificates in PEM format:
+
[subs="+attributes,+quotes",options="nowrap",role=white-space-pre]
----
$ {orch-cli} exec __<workspace_pod_name>__ \
    --namespace=__<workspace_namespace>__ \
    -- cat /public-certs/custom-ca-certificates.custom-ca-certificates.pem
----

.Additional resources
* xref:deploying-che-with-support-for-git-repositories-with-self-signed-certificates.adoc[].
