:_content-type: CONCEPT
:navtitle: Installing {prod-short} using storage classes
:description: Installing {prod-short} using storage classes
:keywords: administration guide, installing-che-using-storage-classes
:page-aliases: installation-guide:installing-che-using-storage-classes

[id="installing-{prod-id-short}-using-storage-classes_{context}"]
= Configuring storage classes

To configure {prod-short} to use a configured infrastructure storage, install {prod-short} using storage classes. This is especially useful when a user wants to bind a persistent volume provided by a non-default provisioner. To do so, a user binds this storage for the {prod-short} data saving and sets the parameters for that storage. These parameters can determine the following:

* A special host path
* A storage capacity
* A volume mod
* Mount options
* A file system
* An access mode
* A storage type
* And many others

{prod-short} has two components that require persistent volumes to store data:

 * A PostgreSQL database.
 * A {prod-short} workspaces. {prod-short} workspaces store source code using volumes, for example `/projects` volume.

[NOTE]
====
{prod-short} workspaces source code is stored in the persistent volume only if a workspace is not ephemeral.
====

.Persistent volume claims facts:

* {prod-short} does not create persistent volumes in the infrastructure.
* {prod-short} uses persistent volume claims (PVC) to mount persistent volumes.
* The {prod-short} server creates  persistent volume claims.
+
A user defines a storage class name in the {prod-short} configuration to use the storage classes feature in the {prod-short} PVC. With storage classes, a user configures infrastructure storage in a flexible way with additional storage parameters. It is also possible to bind a static provisioned persistent volumes to the {prod-short} PVC using the class name.

.Procedure

Use CheCluster Custom Resource definition to define storage classes:

. Define storage class names: configure the `CheCluster` Custom Resource, and install {prod-short}. See xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[].
+
[source,yaml,subs="+quotes,+attributes"]
----
spec:
  storage:
    # keep blank unless you need to use a non default storage class for PostgreSQL PVC
    postgresPVCStorageClassName: 'postgres-storage'
    # keep blank unless you need to use a non default storage class for workspace PVC(s)
    workspacePVCStorageClassName: 'workspace-storage'
----

. Define the persistent volume for a PostgreSQL database in a `che-postgres-pv.yaml` file:
+
.`che-postgres-pv.yaml` file
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/che/postgres"
----

. Define the persistent volume for a {prod-short} workspace in a `che-postgres-pv.yaml` file:
+
.`che-workspace-pv.yaml` file
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv-volume
  labels:
    type: local
spec:
  storageClassName: workspace-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/che/workspace"
----

. Bind the two persistent volumes:
+
[subs="+quotes,+attributes"]
----
$ kubectl apply -f che-workspace-pv.yaml -f che-postgres-pv.yaml
----

[NOTE]
====
You must provide valid file permissions for volumes. You can do it using storage class configuration or manually. To manually define permissions, define `storageClass#mountOptions` `uid` and `gid`. PostgreSQL volume requires `uid=26` and `gid=26`.
====

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]

