:_content-type: PROCEDURE
:description: Installing {prod-short} on OpenShift using the web console
:keywords: overview, installing, openshift, web console
:navtitle: Installing {prod-short} on OpenShift using the web console
:page-aliases: installation-guide:installing-che-on-openshift-4-using-operatorhub.adoc, overview:installing-che-on-openshift-4-using-operatorhub.adoc, creating-an-instance-of-the-che-operator.adoc, installing-che-on-openshift-4-using-operatorhub.adoc

[id="installing-{prod-id-short}-on-openshift-using-the-web-console"]
= Installing {prod-short} on OpenShift using the web console

If you have trouble xref:installing-che-on-openshift-using-cli.adoc[installing {prod-short} on the command line], you can alternatively install it through the OpenShift web console.

.Prerequisites

* An OpenShift web console session by a cluster administrator. See link:https://docs.openshift.com/container-platform/{ocp4-ver}/web_console/web-console.html[Accessing the web console].

* An active `oc` session with administrative permissions to the OpenShift cluster. See link:https://docs.openshift.com/container-platform/{ocp4-ver}/cli_reference/openshift_cli/getting-started-cli.html[Getting started with the OpenShift CLI].

* For a repeat installation on the same OpenShift cluster: you uninstalled the previous {prod-short} instance according to xref:uninstalling-che.adoc[].

.Procedure

. In the *Administrator* view of the OpenShift web console, go to *Operators* -> *OperatorHub* and search for `{prod}`.

. Install the {prod} Operator.
+
TIP: See link:https://docs.openshift.com/container-platform/{ocp4-ver}/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console_olm-adding-operators-to-a-cluster[Installing from OperatorHub using the web console].

. Create the `{prod-namespace}` project in OpenShift as follows:
+
[subs="+attributes"]
----
oc create namespace {prod-namespace}
----

. Go to *Operators* -> *Installed Operators* -> *{prod} instance Specification* -> *Create CheCluster* -> *YAML view*.

. In the *YAML view*, replace `namespace: openshift-operators` with `namespace: {prod-namespace}`.

. Select *Create*.
+
TIP: See https://docs.openshift.com/container-platform/4.10/operators/user/olm-creating-apps-from-installed-operators.html[Creating applications from installed Operators].

.Verification

pass:[<!-- vale RedHat.Spelling = NO -->]

. In *{prod} instance Specification*, go to *devspaces* to land on the *Details* tab.

pass:[<!-- vale RedHat.Spelling = YES -->]

. Under *Message*, check that there is *None*, which means no errors.

. Under *{prod} URL*, wait until the URL of the {prod-short} instance appears, and then open the URL to check the {prod-short} dashboard.

. In the *Resources* tab, view the resources for the {prod-short} deployment and their status.
