[id="managing-backups-using-custom-resources"]
= Managing backups using custom resources
:navtitle: Managing backups using custom resources
:keywords: administration-guide, backup, recovery, custom-resource, custom-resources, manage-backups-using-custom-resources, manage-backups-with-custom-resources
:page-aliases: .:managing-backups-through-custom-resources, .:managing-backups-using-custom-resources

In a production environment, you can xref:managing-backups-using-custom-resources.adoc#creating-a-backup-using-an-object_{context}[create] and xref:managing-backups-using-custom-resources.adoc#restoring-a-backup-using-custom-resource-objects_{context}[restore] backups using custom resources. To manage backups using custom resources in a production environment, you must have a xref:backup-server-setup.adoc[configured backup server] and `{prod-short}` xref:managing-backups-using-custom-resources.adoc#configuring-prod-short-to-use-a-backup-server_{context}[configured to use the backup server].

In a non-production environment, an xref:managing-backups-using-custom-resources.adoc#creating-a-backup-using-the-internal-backup-server_{context}[internal backup server] can also be used to create backups.

include::partial$assembly_configuring-prod-short-to-use-a-backup-server.adoc[leveloffset=+1]
include::partial$proc_creating-a-backup-using-a-checlusterbackup-object.adoc[leveloffset=+1]
include::partial$proc_creating-a-backup-using-the-internal-backup-server.adoc[leveloffset=+1]
include::partial$proc_restoring-a-backup-using-a-checlusterrestore-object.adoc[leveloffset=+1]
