[id="managing-backups-of-prod-short-instances-using-custom-resources"]
= Managing backups of {prod-short} instances using custom resources
:navtitle: Managing backups of {prod-short} instances using custom resources
:keywords: administration-guide, backup, recovery, custom-resource, custom-resources, manage-backups-using-custom-resources, manage-backups-with-custom-resources
:page-aliases: .:managing-backups-through-custom-resources, .:managing-backups-using-custom-resources

You can xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#creating-a-backup-of-a-prod-short-instance-using-a-checlusterbackup-object_{context}[create] and xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#restoring-a-prod-short-instance-from-a-backup-using-a-checlusterrestore-object_{context}[restore] backups of {prod-short} instances using custom resources. To manage backups using custom resources, you must have a xref:backup-server-setup.adoc[configured backup server] and {prod-short} xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#configuring-prod-short-to-use-a-backup-server_{context}[configured to use the backup server].

Alternatively, you can manage backups of {prod-short} instances xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc[using {prod-cli}].

include::partial$assembly_configuring-prod-short-to-use-a-backup-server.adoc[leveloffset=+1]
include::partial$proc_creating-a-backup-of-a-prod-short-instance-using-a-checlusterbackup-object.adoc[leveloffset=+1]
include::partial$proc_restoring-a-prod-short-instance-from-a-backup-using-a-checlusterrestore-object.adoc[leveloffset=+1]