[id="managing-backups-of-prod-short-instances-using-prod-cli"]
= Managing backups of {prod-short} instances using {prod-cli}
:navtitle: Managing backups of {prod-short} instances using {prod-cli}
:keywords: administration-guide, backup, recovery, manage-backups-using-cli, manage-backups-with-li
:page-aliases: .:managing-backups-through-cli, .:managing-backups-using-prod-cli

:context: managing-backups-using-prod-cli

You can xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc#creating-a-backup-of-a-prod-short-instance-using-prod-cli_{context}[create] and xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc#restoring-a-prod-short-instance-from-a-backup-using-prod-cli_{context}[restore] backups of {prod-short} instances using {prod-cli}. To manage backups with {prod-cli}, you must have a xref:backup-server-setup.adoc[configured backup server] and {prod-cli} xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc#configuring-prod-cli-to-use-a-backup-server_{context}[configured to use the backup server].

Alternatively, you can manage backups of {prod-short} instances xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc[using custom resources].

include::partial$proc_creating-a-backup-of-a-prod-short-instance-using-prod-cli.adoc[leveloffset=+1]
include::partial$assembly_restoring-a-prod-short-instance-from-a-backup-using-prod-cli.adoc[leveloffset=+1]
