:_content-type: PROCEDURE
:description: Uninstalling {prod-short}
:keywords: uninstall, remove, delete
:navtitle: Uninstall {prod-short}
:page-aliases: installation-guide:uninstalling-che.adoc, installation-guide:uninstalling-che-after-operatorhub-installation.adoc, uninstalling-che-on-openshift.adoc, installation-guide:uninstalling-che-after-chectl-installation.adoc, uninstalling-che-by-using-chectl.adoc, uninstalling-che.adoc

[id="proc_uninstalling-che"]
= Uninstall {prod-short}

[role="_abstract"]
Use `{prod-cli}` to uninstall the {prod-short} instance and remove all {prod-short}-related user data from the cluster.

[WARNING]
====
Uninstalling {prod-short} removes all {prod-short}-related user data.
====

.Prerequisites

* You have the `{prod-cli}` management tool installed. See xref:plan:installing-the-chectl-management-tool.adoc[].

.Procedure

. Remove the {prod-short} instance:
+
[source,bash,subs="+attributes,+quotes"]
----
$ {prod-cli} server:delete
----
+
[TIP]
====
The `--delete-namespace` option removes the {prod-short} namespace.

The `--delete-all` option removes the {devworkspace} Operator and the related resources.
====
+
[IMPORTANT]
====
Standard operating procedure (SOP) for removing {devworkspace} Operator manually without `{prod-cli}` is available in the {ocp} link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp4-ver}/html/web_console/web-terminal#removing-devworkspace-operator_uninstalling-web-terminal[official documentation].
====

[role="_additional-resources"]
.Additional resources

* xref:plan:installing-the-chectl-management-tool.adoc[]
