:_content-type: CONCEPT
:navtitle: Provisioning {orch-namespace}s
:keywords: administration guide, provisioning, {orch-namespace}
:page-aliases: 

[id="configuring-{orch-namespace}s_{context}"]
= Provisioning {orch-namespace}s

This procedure describes how to provision workpaces {orch-namespace}s in advance, rather than relying on automatic provisioning. 

.Prerequisites

* The workspace user cannot create namespaces on {orch-name}.

.Procedure

. Create one {orch-namespace} for each user, with following labels and annotations. Do not create multiple namespaces for a single user: it may lead to undefined behavior.
+
[subs="+quotes,+attributes"]
----
kind: Namespace
apiVersion: v1
metadata:
  name: __<{orch-namespace}_name>__ <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org <2>
    app.kubernetes.io/component: workspaces-namespace <2>
  annotations:
    che.eclipse.org/username: __<username>__ <3>
----
<1> {orch-namespace} name
<2> `server.customCheProperties.CHE_INFRA_KUBERNETES_NAMESPACE_LABELS` property value
<3> `server.customCheProperties.CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS` property value, replacing __<username>__ with workspace user username on {orch-name}.

. Ensure the __<username>__ workspace user has `edit` role privileges in the __<{orch-namespace}_name>__ {orch-namespace}:
+
.`admin` role binding
[subs="+quotes,+attributes"]
----
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: __<{orch-namespace}_name>__ <1>
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: __<username>__ <2>
    namespace: __<{orch-namespace}_name>__ <1>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
----
<1> {orch-namespace} name
<2> workspace user username on {orch-name}

. Create a __<{prod-id-short}-workspaces-namespaces-clusterrole>__ cluster role and cluster role binding to ensure the `che` ServiceAccount has a accurate permissions on the __<{orch-namespace}_name>__ {orch-namespace}. Use a name at your connvenance for __<{prod-id-short}-workspaces-namespaces-clusterrole>__.
+
.`__<{prod-id-short}-workspaces-namespaces-clusterrole>__` cluster role
[subs="+quotes,+attributes"]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: __<{prod-id-short}-workspaces-namespaces-clusterrole>__
rules:
  - verbs:
      - list <1>
      - get <1>
      - update <2>
    apiGroups:
      - ''
    resources:
      - namespaces
----
<1> Necessary permissions to let {prod-short} access the __<{orch-namespace}_name>__ {orch-namespace}.
<2> Optional permissions to let {prod-short} update the __<{orch-namespace}_name>__ {orch-namespace} labels on workspace startup.
+
.`__<{prod-id-short}-workspaces-namespaces-clusterrole>__` cluster role binding
[subs="+quotes,+attributes"]
----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: __<{prod-id-short}-workspaces-namespaces-clusterrole>__
subjects:
  - kind: ServiceAccount
    name: __<service-account-name>__ <2>
    namespace: __<service-account-namespace>__ <3>
roleRef:
  kind: ClusterRole
  name: __<{prod-id-short}-workspaces-namespaces-clusterrole>__
  apiGroup: rbac.authorization.k8s.io
----
<1> name of the cluster role binding
<2> name of the {prod-short} ServiceAccount
<3> {prod-short} installation namespace


. Optionally, configure {prod-short} to not update the {orch-namespace} labels when starting a workspace.
+
.`CheCluster` custom resource excerpt
----
...
spec:
  server:
    server.customCheProperties.CHE_INFRA_KUBERNETES_NAMESPACE_LABEL=false
...
----

.Additional resources

* xref:understanding-the-checluster-custom-resource.adoc[]
* xref:advanced-configuration-options-for-the-che-server-component.adoc[]

