:_content-type: CONCEPT
:navtitle: Provisioning {orch-namespace}s
:keywords: administration guide, provisioning, {orch-namespace}
:page-aliases: 

[id="configuring-{orch-namespace}s_{context}"]
= Provisioning {orch-namespace}s

This procedure describes how to provision workpaces {orch-namespace}s in advance, rather than relying on automatic provisioning. Repeat the procedure for each user.

.Prerequisites

* The workspace user cannot create namespaces on {orch-name}.

.Procedure

. Create the __<{orch-namespace}_name>__ {orch-namespace} for __<username>__ user, with following labels and annotations.
+
[source,yaml,subs="+quotes,+attributes"]
----
kind: Namespace
apiVersion: v1
metadata:
  name: __<{orch-namespace}_name>__ <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org <2>
    app.kubernetes.io/component: workspaces-namespace <2>
  annotations:
    che.eclipse.org/username: __<username>__ <3>
----
<1> Use a {orch-namespace} name at your convenance
<2> `server.customCheProperties.CHE_INFRA_KUBERNETES_NAMESPACE_LABELS` property value
<3> `server.customCheProperties.CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS` property value, replacing __<username>__ with workspace user username on {orch-name}.

. Create a role binding to ensure the __<username>__ workspace user has `edit` role privileges in the __<{orch-namespace}_name>__ {orch-namespace}:
+
.`{prod-id-short}-workspaces-namespace-edit-rolebinding` role binding
[source,yaml,subs="+quotes,+attributes"]
----
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {prod-id-short}-workspaces-namespace-edit-rolebinding
  namespace: __<{orch-namespace}_name>__
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: __<username>__
    namespace: __<{orch-namespace}_name>__
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
----


. Create a cluster role and cluster role binding to ensure the {prod-short} ServiceAccount has a accurate permissions on the __<{orch-namespace}_name>__ {orch-namespace}.
+
.`{prod-id-short}-workspaces-namespaces-clusterrole` cluster role
[source,yaml,subs="+quotes,+attributes"]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {prod-id-short}-workspaces-namespaces-clusterrole
rules:
  - verbs:
      - list <1>
      - get <1>
      - update <2>
    apiGroups:
      - ''
    resources:
      - namespaces
----
<1> Necessary permissions to let {prod-short} access the __<{orch-namespace}_name>__ {orch-namespace}.
<2> Optional permissions to let {prod-short} update the __<{orch-namespace}_name>__ {orch-namespace} labels on workspace startup.
+
.`{prod-id-short}-workspaces-namespaces-clusterrole` cluster role binding
[source,yaml,subs="+quotes,+attributes"]
----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {prod-id-short}-workspaces-namespaces-clusterrole
subjects:
  - kind: ServiceAccount
    name: {prod-id-short} <1>
    namespace: {prod-namespace} <2>
roleRef:
  kind: ClusterRole
  name: {prod-service-account}-workspaces-namespaces-clusterrole
  apiGroup: rbac.authorization.k8s.io
----
<1> {prod-short} service account name. Default: `{prod-id-short}`.
<2> {prod-short} installation {orch-namespace} name. Default: {prod-namespace}.


. Optionally, configure {prod-short} to not update the {orch-namespace} labels when starting a workspace.
+
.`CheCluster` custom resource excerpt
[source,yaml]
----
kind: CheCluster
apiVersion: org.eclipse.che/v1
# ...
spec:
  server:
    customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_LABEL: false
# ...
----

.Additional resources

* xref:understanding-the-checluster-custom-resource.adoc[]
* xref:advanced-configuration-options-for-the-che-server-component.adoc[]

