:_content-type: PROCEDURE
:navtitle: Removing user data
:description: Removing user data
:keywords: administration-guide, removing-user-data
:page-aliases: .:removing-user-data

[id="removing-user-data_{context}"]
= Removing user data

== Removing user data according to GDPR


You can remove the {prod-short} user’s data using the {prod-short} API.
Following this procedure makes the service compliant to EU General Data Protection Regulation (link:https://en.wikipedia.org/wiki/General_Data_Protection_Regulation[GDPR]) that enforces the right for individuals to have personal data erased.

.Prerequisites

* Log in to {prod-short} with a user with `admin` privileges. See xref:configuring-the-administrative-user.adoc[].

.Procedure

. Get the __<username>__ user __<id>__ `id`: navigate to pass:c,m,a,q[+https:+//__<{prod-host}>__]/swagger/#/user/find_1, click btn:[Try it out], set *name*: __<username>__, and click btn:[Execute]. Scroll down the *Response body* to find the `id` value.
// +
// [subs="+quotes,macros,attributes"]
// ----
// $ curl -X GET \
//   --cookie '_oauth_proxy=__<token>__' \
//   'pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/find?name=__<username>__'
// ----

. Remove the __<id>__ user data that {prod-short} server manages: navigate to pass:c,m,a,q[+https:+//__<{prod-host}>__]/swagger/#/user/remove, click btn:[Try it out], set *id*: __<id>__, and click btn:[Execute]. Expect a `204` response code:
// +
// [subs="+quotes,macros,attributes"]
// ----
// $ curl -i -X DELETE \
//   --cookie '_oauth_proxy=__<token>__' \
//   'pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/__<id>__'
// ----

. Optionally, remove the {orch-name} resources bound to the user.


.Verification

* {prod-short} server API reports that the user doesn't exist. Expect a `404` response code:
+
[subs="+quotes,macros,attributes"]
----
$ curl -i -X DELETE \
  --cookie '_oauth_proxy=__<token>__' \
  'pass:c,m,a,q[+https:+//__<{prod-host}>__]/api/user/find?name=__<username>__'
----

.Additional resources

* xref:managing-workloads-using-the-che-server-api.adoc[].
* To remove the data of all users, see xref:uninstalling-che.adoc[].
