[id="restoring-a-prod-short-instance-from-a-backup"]
= Restoring a {prod-short} instance from a backup
:navtitle: Restoring a {prod-short} instance from a backup
:keywords: administration-guide, backup, recovery, recover, restoration, restore, restoring, restoring-from-a-backup, restoring-instance, custom-resource, cli, {prod-cli}
:page-aliases: .:restoring-backups-through-custom-resources, .:managing-backups-using-custom-resources, .:managing-backups-using-{prod-cli}

////
You can xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#creating-a-backup-of-a-prod-short-instance-using-a-checlusterbackup-object_{context}[create] and xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#restoring-a-prod-short-instance-from-a-backup-using-a-checlusterrestore-object_{context}[restore] backups of {prod-short} instances using custom resources. To manage backups using custom resources, you must have a xref:backup-server-setup.adoc[configured backup server] and {prod-short} xref:managing-backups-of-prod-short-instances-using-custom-resources.adoc#configuring-prod-short-to-use-a-backup-server_{context}[configured to use the backup server].

Alternatively, you can manage backups of {prod-short} instances xref:managing-backups-of-prod-short-instances-using-prod-cli.adoc[using {prod-cli}].
////

include::partial$proc_restoring-a-prod-short-instance-from-a-backup-using-a-checlusterrestore-object.adoc[leveloffset=+1]
include::partial$assembly_restoring-a-prod-short-instance-from-a-backup-using-prod-cli.adoc[leveloffset=+1]