:_content-type: PROCEDURE
:description: Show deprecated editors
:keywords: administration guide, show deprecated, dashboard, editors
:navtitle:  Show deprecated editors
:page-aliases: installation-guide:show-deprecated-editors.adoc

[id="show-deprecated-editors"]
= Show deprecated editors

Learn how to show deprecated {prod-short} editors.

NOTE: By default, the deprecated editors are hidden in the Dashboard UI. To show them, you need to set the `CHE_SHOW_DEPRECATED_EDITORS` environment variable to `true`.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the {orch-name} cluster. See {orch-cli-link}.

* `jq`. See link:https://stedolan.github.io/jq/download/[Downloading `jq`].

.Procedure

. An editor ID has the following format: `publisher/name/version`. Find out the IDs of the deprecated editors:
+
[source,subs="+quotes,+attributes"]
----
{orch-cli} exec deploy/{prod-id-short}-dashboard -n {prod-namespace}  \
    -- curl -s http://localhost:8080/dashboard/api/editors | jq -r '[.[] | select(.metadata.tags != null) | select(.metadata.tags[] | contains("Deprecate")) | "\(.metadata.attributes.publisher)/\(.metadata.name)/\(.metadata.attributes.version)"]'
----

. Configure the `CheCluster` Custom Resource. See xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml]
----
spec:
  components:
    dashboard:
      deployment:
        containers:
        - env:
          - name: CHE_SHOW_DEPRECATED_EDITORS
            value: 'true'
----

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]
