:_content-type: PROCEDURE
:description: The Woopra telemetry plugin
:keywords: extensions, telemetry
:navtitle: The Woopra telemetry plugin
:page-aliases: extensions:the-woopra-telemetry-plug-in.adoc

[id="the-woopra-telemetry-plugin"]

= The Woopra telemetry plugin

The link:https://github.com/che-incubator/devworkspace-telemetry-woopra-plugin[Woopra Telemetry Plugin] is a plugin built to send telemetry from a {prod} installation to Segment and Woopra.
This plugin is used by link:https://workspaces.openshift.com[Eclipse Che hosted by Red Hat], but any {prod} deployment can take advantage of this plugin.
There are no dependencies other than a valid Woopra domain and Segment Write key.
The devfile v2 for the plugin, link:https://raw.githubusercontent.com/che-incubator/devworkspace-telemetry-woopra-plugin/main/plugin.yaml[plugin.yaml], has four environment variables that can be passed to the plugin:

- `WOOPRA_DOMAIN` - The Woopra domain to send events to.
- `SEGMENT_WRITE_KEY` - The write key to send events to Segment and Woopra.
- `WOOPRA_DOMAIN_ENDPOINT` - If you prefer not to pass in the Woopra domain directly, the plugin will get it from a supplied HTTP endpoint that returns the Woopra Domain.
- `SEGMENT_WRITE_KEY_ENDPOINT` - If you prefer not to pass in the Segment write key directly, the plugin will get it from a supplied HTTP endpoint that returns the Segment write key.

To enable the Woopra plugin on the {prod} installation:

.Procedure

* Deploy the `plugin.yaml` devfile v2 file to an HTTP server with the environment variables set correctly.

. Configure the `CheCluster` Custom Resource. See xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[].
+
[source,yaml]
----
spec:
  devEnvironments:
    defaultPlugins:
    - editor: eclipse/che-theia/next     <1>
      plugins:                           <2>
      - 'https://your-web-server/plugin.yaml'
----
<1> The `editorId` to set the telemetry plugin for.
<2> The URL to the telemetry plugin's devfile v2 definition.

.Additional resources

* xref:using-chectl-to-configure-the-checluster-custom-resource-during-installation.adoc[]

* xref:using-the-cli-to-configure-the-checluster-custom-resource.adoc[]
