:_content-type: PROCEDURE
:description: Uninstalling Che
:keywords: administration guide, uninstalling-che
:navtitle: Uninstalling Che
:page-aliases: installation-guide:uninstalling-che.adoc, installation-guide:uninstalling-che-after-operatorhub-installation.adoc, uninstalling-che-on-openshift.adoc, installation-guide:uninstalling-che-after-chectl-installation.adoc, uninstalling-che-by-using-chectl.adoc


[id="uninstalling-{prod-id-short}"]
= Uninstalling {prod-short}

WARNING: Uninstalling {prod-short} removes all {prod-short}-related user data!

To uninstall an instance of {prod} {prod-ver}:

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* `{prod-cli}`. See: xref:installing-the-chectl-management-tool.adoc[].

.Procedure

. Obtain the name of the {prod-short} {orch-namespace}. The default is `{prod-namespace}`.
+
[subs="+attributes,quotes"]
----
$ {orch-cli} get checluster --all-namespaces \
  -o=jsonpath="{.items[*].metadata.namespace}"
----

. Remove the {prod-short} instance from the `{prod-namespace}` {orch-namespace}:
+
[subs="+attributes,quotes"]
----
$ {prod-cli} server:delete -n {prod-namespace} # <1>
----
<1> The {orch-namespace} that you got in step 1.

include::example$snip_{project-context}-note-uninstalling-in-minikube-cluster.adoc[]

[NOTE] 
====
If {prod-short} was installed from the OpenShift web console, `{prod-cli}` will not uninstall the {devworkspace} operator.
To uninstall the {devworkspace} Operator, see link:https://docs.openshift.com/container-platform/{ocp4-ver}/web_console/odc-about-web-terminal.html#deleting-the-devworkspace-operator-dependency[Deleting the {devworkspace} Operator dependency].
====
