:_content-type: PROCEDURE
:navtitle: Upgrading {prod-short} using the CLI management tool
:keywords: administration guide, upgrading-che-using-the-cli-management-tool
:page-aliases: installation-guide:upgrading-che-using-the-cli-management-tool

[id="upgrading-{prod-id-short}-using-the-cli-management-tool_{context}"]
= Upgrading {prod-short} using the CLI management tool

This section describes how to upgrade from the previous minor version using the CLI management tool.

.Prerequisites

* An administrative account on {platforms-name}.

* A running instance of a previous minor version of {prod}, installed using the CLI management tool on the same instance of {platforms-name}, in the `__<{prod-namespace}>__` project.

* `{prod-cli}` is available and updated. See xref:using-the-chectl-management-tool.adoc[].


.Procedure

. Save and push changes back to the Git repositories for all running {prod-short} {prod-prev-ver} workspaces.

. Shut down all workspaces in the {prod-short} {prod-prev-ver} instance.

. Upgrade {prod-short}:
+
[subs="+attributes,+quotes"]
----
$ {prod-cli} server:update -n {prod-namespace}
----

[NOTE]
====
For slow systems or internet connections, add the `--k8spodwaittimeout=1800000` flag option to the `{prod-cli} server:update` command to extend the Pod timeout period to 1800000 ms or longer.
====

.Verification steps

. Navigate to the {prod-short} instance.

. The {prod-ver} version number is visible at the bottom of the page.
