:_content-type: PROCEDURE
:navtitle: Upgrading {prod-prev-short} {prod-last-version-pre-dwo} on OpenShift
:description: Upgrading {prod-prev-short} {prod-last-version-pre-dwo} on OpenShift
:keywords: administration-guide, migration, devworkspace
:page-aliases: 

[id="upgrading-{prod-prev-id-short}-{prod-last-version-pre-dwo}-on-openshift_{context}"]
= Upgrading {prod-prev-short} {prod-last-version-pre-dwo} on OpenShift

The workspace engine and authentication system used up to and including {prod-prev-short} version {prod-last-version-pre-dwo} are deprecated, which requires manual steps.

.Prerequisites

* An instance of {prod-prev-short} deployed on xref:supported-platforms.adoc[], using the default internal PostgreSQL database, and with OpenShift OAuth enabled. See {prod-docs-url-enable-oauth}.
* Command line tools `oc`, `curl`, and `jq` are available.
* The host running the upgrade commands is running on Linux.

.Procedure

. Optionally push back changes to Git repositories in all workspaces, stop all workspaces to avoid user experience degradation, and backup {prod-short} data. See {prod-docs-url-backup-recovery}.

. Set the environment variables to use in the migration scripts:
+
[source,bash,subs="+attributes"]
----
export INSTALLATION_NAMESPACE={prod-namespace}  #<1>
export PRODUCT_ID={prod-id}
export PRODUCT_DEPLOYMENT_NAME={prod-deployment}
export PRODUCT_OPERATOR_NAME={prod-operator}
export PRODUCT_OLM_STABLE_CHANNEL={prod-stable-channel}
export PRODUCT_OLM_CATALOG_SOURCE={prod-stable-channel-catalog-source}
export PRODUCT_OLM_PACKAGE={prod-stable-channel-package}
export PRE_MIGRATION_PRODUCT_OPERATOR_NAMESPACE={prod-namespace}  #<1>
export PRE_MIGRATION_PRODUCT_SHORT_ID={pre-migration-prod-id-short}
export PRE_MIGRATION_PRODUCT_DEPLOYMENT_NAME={pre-migration-prod-deployment}
export PRE_MIGRATION_PRODUCT_OPERATOR_NAME={pre-migration-prod-operator}
export PRE_MIGRATION_PRODUCT_CHE_CLUSTER_CR_NAME={pre-migration-prod-checluster}
export PRE_MIGRATION_PRODUCT_IDENTITY_PROVIDER_DEPLOYMENT_NAME={identity-provider-id}
export PRE_MIGRATION_PRODUCT_SUBSCRIPTION_NAME={pre-migration-prod-subscription}
----
<1> Set this environment variable to the {orch-namespace} where {prod-prev-short} was previously installed.

. Download and execute the migration scripts: xref:attachment$migration/1-prepare.sh[1-prepare.sh], xref:attachment$migration/2-migrate.sh[2-migrate.sh], xref:attachment$migration/3-subscribe.sh[3-subscribe.sh], and xref:attachment$migration/4-wait.sh[4-wait.sh].
+
[source,bash,subs="+attributes"]
----
chmod +x ./1-prepare.sh ./2-migrate.sh ./3-subscribe.sh ./4-wait.sh
./1-prepare.sh    #<1>
./2-migrate.sh    #<2>
./3-subscribe.sh  #<3>
./4-wait.sh       #<4>
----
<1> Shuts down {prod-prev-short} and {identity-provider}, fetch users data and dumps {prod-short} database.
<2> Fetches {prod-prev-short} {identity-provider} and database data, and repopulates the database with updated data.
<3> Deletes {prod-prev-short} Operator and {identity-provider} resources, updates CheCluster CR and creates a new {prod-short} Operator subscription.
<4> Waits until {prod-short} is ready (it can take more than 5 minutes).

.Verification

* Open {prod-short} dashboard and log in.

[IMPORTANT]
====
If migration fails, use the following steps to roll back to the previous {prod-prev-short} installation.

. Set the environment variables to use in the migration scripts:
+
[source,bash,subs="+attributes"]
----
export INSTALLATION_NAMESPACE={prod-namespace} #<1>
export PRODUCT_ID={prod-id}
export PRODUCT_SHORT_ID={prod-id-short}
export PRODUCT_DEPLOYMENT_NAME={prod-deployment}
export PRE_MIGRATION_PRODUCT_OPERATOR_NAMESPACE={prod-namespace}  #<1>
export PRE_MIGRATION_PRODUCT_DEPLOYMENT_NAME={pre-migration-prod-deployment}
export PRE_MIGRATION_PRODUCT_SUBSCRIPTION_NAME={pre-migration-prod-subscription}
export PRE_MIGRATION_PRODUCT_CHE_CLUSTER_CR_NAME={pre-migration-prod-checluster}
export PRE_MIGRATION_PRODUCT_OPERATOR_NAME={pre-migration-prod-operator}
export PRE_MIGRATION_PRODUCT_OLM_PACKAGE={pre-migration-prod-package}
export PRE_MIGRATION_PRODUCT_OLM_CHANNEL={pre-migration-prod-channel}
export PRE_MIGRATION_PRODUCT_OLM_CATALOG_SOURCE={pre-migration-prod-catalog-source}
----
<1> Set this environment variable to the {orch-namespace} where {prod-prev-short} was previously installed.

. Download and execute the rollback script: xref:attachment$migration/rollback.sh[rollback.sh].
+
[source,bash,subs="+attributes"]
----
chmod +x ./rollback.sh
./rollback.sh
----

.Verification

* Open {prod-prev-short} dashboard and log in.

====
