:_content-type: PROCEDURE
:description: Fix a duplicate DevWorkspace Operator after an OLM restart or cluster upgrade.
:keywords: devworkspace, operator, repair, duplicate
:navtitle: Fix a duplicate {devworkspace} Operator after a cluster upgrade
:page-aliases: administration-guide:repairing-the-devworkspace-operator-on-openshift.adoc

[id="repairing-the-devworkspace-operator-on-openshift"]
= Fix a duplicate {devworkspace} Operator after a cluster upgrade

[role="_abstract"]
Fix a duplicate {devworkspace} Operator installation that can occur when an link:https://docs.openshift.com/container-platform/{ocp4-ver}/operators/understanding/olm/olm-understanding-olm.html[OLM] restart or cluster upgrade leaves multiple Operator entries in a *Replacing* or *Pending* loop.

.Prerequisites

* An active `{orch-cli}` session as a cluster administrator to the destination OpenShift cluster. See {orch-cli-link}.

* On the *Installed Operators* page of the {platforms-name} web console, you see multiple entries for the {devworkspace} Operator or one entry that is stuck in a loop of *Replacing* and *Pending*.

.Procedure

. Delete the `devworkspace-controller` namespace that contains the failing pod.

. Update `DevWorkspace` and `DevWorkspaceTemplate` Custom Resource Definitions (CRD) by setting the conversion strategy to `None` and removing the entire `webhook` section:
+
[source,yaml]
----
spec:
  ...
  conversion:
    strategy: None
status:
...
----
+
[TIP]
====
You can find and edit the `DevWorkspace` and `DevWorkspaceTemplate` CRDs in the *Administrator* perspective of the OpenShift web console by searching for `DevWorkspace` in menu:Administration[CustomResourceDefinitions].
====
+
[NOTE]
====
The `DevWorkspaceOperatorConfig` and `DevWorkspaceRouting` CRDs have the conversion strategy set to `None` by default.
====

. Remove the {devworkspace} Operator subscription:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} delete sub devworkspace-operator \
-n __<devworkspace_operator_namespace>__ <1>
----
<1> The {orch-namespace} where the {devworkspace} Operator is installed, such as `openshift-operators`.

. Get the {devworkspace} Operator CSVs in the __<devworkspace_operator.vX.Y.Z>__ format:
+
[subs="+attributes"]
----
$ {orch-cli} get csv | grep devworkspace
----

. Remove each {devworkspace} Operator CSV:
+
[subs="+quotes,+attributes"]
----
$ {orch-cli} delete csv __<devworkspace_operator.vX.Y.Z>__ \
-n __<devworkspace_operator_namespace>__ <1>
----
<1> The {orch-namespace} where the {devworkspace} Operator is installed, such as `openshift-operators`.

. Re-create the {devworkspace} Operator subscription:
+
[subs="+attributes"]
----
$ cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devworkspace-operator
  namespace: openshift-operators
spec:
  channel: fast
  name: devworkspace-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  startingCSV: devworkspace-operator.v{devworkspace-operator-version-patch}
EOF
----
+
`installPlanApproval`:: `Automatic` or `Manual`.
+
[IMPORTANT]
====
For `installPlanApproval: Manual`, in the *Administrator* perspective of the OpenShift web console, go to menu:Operators[Installed Operators] and select the following for the *{devworkspace} Operator*: menu:Upgrade available[Preview InstallPlan > Approve].
====

.Verification

* In the *Administrator* perspective of the OpenShift web console, go to menu:Operators[Installed Operators] and verify the *Succeeded* status of the *{devworkspace} Operator*.

[role="_additional-resources"]
.Additional resources

* xref:specifying-the-update-approval-strategy.adoc[]
* xref:upgrading-che-using-the-web-console.adoc[]
