:_content-type: CONCEPT
:description: By default, newly created workspaces that do not specify a devfile use the Universal Developer Image (UDI).
:keywords: fuse, overlay, fuse-overlayfs, podman, buildah, storage, driver
:navtitle: How fuse-overlayfs works in Cloud Development Environments
:page-aliases:

[id="using-the-fuse-overlay-storage-driver-for-podman-and-buildah"]
= How fuse-overlayfs works in Cloud Development Environments

[role="_abstract"]
By default, newly created workspaces that do not specify a devfile use the Universal Developer Image (UDI).
The UDI contains common development tools and dependencies commonly used by developers.


Podman and Buildah are included in the UDI, allowing developers to build and push container images from their workspace.

By default, Podman and Buildah in the UDI are configured to use the `vfs` storage driver.
For more efficient image management, use the fuse-overlayfs storage driver which supports copy-on-write in rootless environments.

You must meet the following requirements to use fuse-overlayfs in a workspace:

* For {orch-name} versions older than 4.15, the administrator has enabled `/dev/fuse` access on the cluster.
* The workspace has the necessary annotations for using the `/dev/fuse` device.
* The `storage.conf` file in the workspace container is configured to use fuse-overlayfs.

[role="_additional-resources"]
.Additional resources
* xref:accessing-fuse.adoc[Accessing /dev/fuse]
* xref:enabling-overlay-with-a-configmap.adoc[Enabling the overlay storage driver with a ConfigMap]
* xref:administration-guide:configuring-fuse.adoc[Configuring fuse-overlayfs]
* link:https://github.com/devfile/developer-images[Universal Developer Image]
