:parent-context-of-using-a-visual-studio-code-extension-in-che: {context}

[id='using-a-visual-studio-code-extension-in-che_{context}']
= Using a Visual Studio Code extension in Che

:context: using-a-visual-studio-code-extension-in-che

Starting with Eclipse Che 7, Visual Studio Code (VS Code) extensions can be installed to extend the functionality of a Che workspace. VS Code extensions can run in the Che-Theia editor container, or they can be packaged in their own isolated and pre-configured containers with their prerequisites.

This document describes:

* Use of a VS Code extension in Che with workspaces
* Che Plug-ins panel
* How to publish a VS Code extension in the Che plug-in registry (to share the extension with other Che users)
+
** The extension-hosting sidecar container and the use of the extension in a devfile are optional for this.
** How to review the compatibility of the VS Code extensions to be informed whether a specific API is supported or has not been implemented yet.

include::proc_importing-a-vs-code-extension-in-the-che-theia-editor.adoc[leveloffset=+1]

include::assembly_publishing-a-vs-code-extension-into-the-che-plug-in-registry.adoc[leveloffset=+1]

include::assembly_adding-che-plug-in-registry-vs-code-extension-to-a-workspace.adoc[leveloffset=+1]

include::proc_choosing-the-sidecar-image.adoc[leveloffset=+1]

include::proc_verifying-the-vs-code-extension-api-compatibility-level.adoc[leveloffset=+1]

:context: {parent-context-of-using-a-visual-studio-code-extension-in-che}
