// Module included in the following assemblies:
//
// che-workspace-components

// This module can be included from assemblies using the following include statement:
// include::<path>/con_plug-in-broker.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: con_my-concept-module-a.adoc
// * ID: [id='con_my-concept-module-a_{context}']
// * Title: = My concept module A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// In the title, include nouns that are used in the body text. This helps
// readers and search engines find information quickly.
// Do not start the title with a verb. See also _Wording of headings_
// in _The IBM Style Guide_.
[id="plug-in-broker_{context}"]
= Plug-in broker

Plug-in brokers are special services that, given a plug-in meta.yaml file, will:

* Gather all the information to provide a Che plug-in definition that the Che server knows.

* Perform preparation actions in the workspace namespace (that is, download, unpack files, process configuration).

The main goal of the plug-in broker is to decouple the Che plug-in definition from the actual plug-ins that Che can support. With brokers, Che can support different plug-ins without updating the Che server.

The Che server starts the plug-in broker. The plug-in broker runs in the same Kubernetes namespace as the workspace. It has access to the plug-ins and project persistent volumes.

A plug-in broker is defined as a container image (example,  `eclipse/che-plugin-broker`). The plug-in type determines the kind of broker that will be started. Currently, two kinds of plug-ins are supported: Che plug-in and Che editor.

[cols=2*]
|===
| Source code
| link:https://github.com/eclipse/che-plugin-broker[Che Plug-in broker]

| Container image
| `eclipse/che-init-plugin-broker`
`eclipse/che-unified-plugin-broker`
|===
