// Module included in the following assemblies:
//
// che-workspace-components

// This module can be included from assemblies using the following include statement:
// include::<path>/con_che-plug-ins.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: con_my-concept-module-a.adoc
// * ID: [id='con_my-concept-module-a_{context}']
// * Title: = My concept module A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// In the title, include nouns that are used in the body text. This helps
// readers and search engines find information quickly.
// Do not start the title with a verb. See also _Wording of headings_
// in _The IBM Style Guide_.
[id="che-plug-ins_{context}"]
= Che plug-ins

Che plug-ins are special services that extend the Che workspace capabilities. Che plug-ins are packaged as containers. Packaging plug-ins into a container has the following benefits:

* It isolates the plug-ins from the main IDE, thus limiting the resources that a plug-in has access to.

* It uses the consolidated standard of container registries to publish and distribute plug-ins (as with any container image).

These containers that the plug-ins are packaged into,  run as sidecars of the Che workspace editor and augment its capabilities.

VS Code extensions packaged in containers are Che plug-ins for the Che-Theia editor and are currently the most popular type of Che plug-ins.

Multiple Che plug-ins can run in the same container (for better resource usage) or a Che plug-in can run in its dedicated container (for better isolation).
