:_content-type: PROCEDURE
:description: Use {kubernetes} namespaces instead of {orch-name} projects
:keywords: administration guide, configuring, namespace, openshift, project, projectrequest
:navtitle: Use {kubernetes} namespaces instead of {orch-name} projects
:page-aliases:

[id="configuring-kubernetes-namespace-creation-on-openshift"]
= Use {kubernetes} namespaces instead of {orch-name} projects


By default, on {ocp} clusters, {prod-short} uses the ProjectRequest API to create projects. This triggers cluster-specific link:https://docs.openshift.com/container-platform/latest/applications/projects/configuring-project-creation.html[Project Templates], which can apply additional resources or policies.

On {ocp}, you can bypass Project Templates and create standard {kubernetes} Namespaces directly. For example, this is useful when Project Templates introduce unwanted side effects.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Set the `createKubernetesNamespaces` field to `true`:
+
[source,shell,subs="+quotes,+attributes,+macros"]
----
{orch-cli} patch checluster {prod-checluster} \
  --namespace {prod-namespace} \
  --type merge \
  --patch '{
    "spec": {
      "devEnvironments": {
        "defaultNamespace": {
          "createKubernetesNamespaces": true
        }
      }
    }
  }'
----

[NOTE]
====
This setting applies only to {ocp} clusters. On {kubernetes} clusters, Namespaces are always created directly regardless of this setting.
====

[role="_additional-resources"]
.Additional resources

* xref:configuring-namespace-provisioning.adoc[]
* xref:configuring-a-user-namespace.adoc[]
* link:https://docs.openshift.com/container-platform/latest/applications/projects/configuring-project-creation.html[Configuring OpenShift project creation]
