:_content-type: PROCEDURE
:description: Configure backup with the integrated {orch-name} registry
:keywords: backup, storage, openshift, registry
:navtitle: Configure backup with the integrated {orch-name} registry
//:page-aliases:

[id="devworkspace-backup-integrated-openshift-registry"]
= Configure backup with the integrated {orch-name} registry


Configure the {devworkspace} backup to use the integrated {orch-name} container registry, available on clusters with the https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp4-ver}/html/registry/setting-up-and-configuring-the-registry[integrated container registry] enabled. This option requires no additional credentials configuration.

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* The https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp4-ver}/html/registry/setting-up-and-configuring-the-registry[integrated container registry] is enabled on the cluster.

To enable the backup use following configuration in the global DWOC:

[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
  namespace: $OPERATOR_INSTALL_NAMESPACE <1>
config:
  routing:
    defaultRoutingClass: basic
  workspace:
    backupCronJob:
      enable: true
      registry:
        path: default-route-openshift-image-registry.apps.{cluster ID}.openshiftapps.com
      oras:
        extraArgs: '--insecure' <2>
      schedule: '0 */4 * * *' # cron expression with backup frequency
    imagePullPolicy: Always
----
<1> For Red Hat OpenShift, the default installation namespace for the {devworkspace} operator is `openshift-operators`. See the xref:discover:devworkspace-operator.adoc[{devworkspace} operator overview].
<2> The `--insecure` flag can be required depending on the integrated registry's routing configuration.

**Note:** The `path` field must contain the URL to your OpenShift integrated registry given by the cluster.

To get a default path to registry run following command:

[source,shell,subs="+attributes,+quotes"]
----
echo "https://$(oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}'))"
----

Once the backup job is finished, the backup archives will be available in the {devworkspace} {namespace} under a repository
with a matching {devworkspace} name.

include::partial$snip_defining-dwo-namespace-for-backups.adoc[]
