# This Workflow performs an update of Che variables
name: Update Che variables in the docs
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch in which to update variables'
        required: true
        default: ''
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Release
        run: |
          git config --global user.name "Mykhailo Kuznietsov"
          git config --global user.email "mkuznets@redhat.com"
          export GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}

          BASE_BRANCH=${{ github.event.inputs.branch }}
          git checkout ${BASE_BRANCH}
          ./tools/environment_docs_gen.sh
          
          if git diff --name-status --exit-code; then
            echo "[INFO] no changes detected, pull request will not be created"
          else           
            PR_BRANCH="pr-update-base-images-$(date +%s)"
            git checkout -b ${PR_BRANCH}
            git add -A
            git commit -sm "chore: Update Che variables"
            git push origin ${PR_BRANCH}
            hub pull-request --base ${BASE_BRANCH} --head ${PR_BRANCH} -m "chore: Update Che variables in ${PR_BRANCH}"
          fi